### ISSUE TITLE
opendir: No such file or directory

### ISSUE THREAD

**Issue by mordax7** [Alexays/Waybar#1004]
After looking at the log output of Waybar I noticed these lines being output periodically every half an hour:
```
Jan 31 09:59:30 waybar[1892]: opendir: No such file or directory
Jan 31 09:59:30 waybar[1892]: Can't open /proc/1902/fd
Jan 31 10:22:55 waybar[22362]: opendir: No such file or directory
Jan 31 10:22:55 waybar[22362]: Can't open /proc/22368/fd
Jan 31 11:53:32 waybar[95249]: opendir: No such file or directory
Jan 31 11:53:32 waybar[95249]: Can't open /proc/95260/fd
Jan 31 11:53:32 waybar[95249]: opendir: No such file or directory
Jan 31 11:53:32 waybar[95249]: Can't open /proc/95261/fd
Jan 31 12:24:48 waybar[118804]: opendir: No such file or directory
Jan 31 12:24:48 waybar[118804]: Can't open /proc/118815/fd
Jan 31 12:24:48 waybar[118804]: opendir: No such file or directory
Jan 31 12:24:48 waybar[118804]: Can't open /proc/118816/fd
Jan 31 12:26:48 waybar[120296]: opendir: No such file or directory
Jan 31 12:26:48 waybar[120296]: Can't open /proc/120301/fd
Jan 31 12:26:48 waybar[120296]: opendir: No such file or directory
Jan 31 12:26:48 waybar[120296]: Can't open /proc/120302/fd
```

`config`:
<details><pre>
{
    "layer": "top",
    "height": 25,
    "modules-left": [
        "sway/workspaces",
        "sway/mode"
    ],
    "modules-right": [
        "custom/progress",
        "custom/yubikey",
        "custom/systemd",
        "custom/updates",
        "custom/recording",
        "custom/dnd",
        "pulseaudio",
        "network",
        "custom/vpn",
        "cpu",
        "memory",
        "backlight",
        "battery",
        "clock",
        "tray"
    ],

    "custom/progress": {
        "exec": "waybar-progress",
        "return-type": "json",
        "interval": 1
    },
    "custom/yubikey": {
        "exec": "waybar-yubikey",
        "return-type": "json"
    },
    "custom/systemd": {
        "exec": "waybar-systemd",
        "return-type": "json",
        "interval": 10
    },
    "custom/updates": {
        "exec": "waybar-updates show",
        "return-type": "json",
        "signal": 1,
        "on-click-right": "waybar-updates refresh",
        "interval": "once"
    },
    "custom/vpn": {
        "format": "{}",
        "return-type": "json",
        "exec": "waybar-vpn",
        "on-click": "nmcli con up office passwd-file /run/media/aljaz/wrk-stick/work/vpn/office/pass",
        "on-click-right": "nmcli con down office"
    },
    "custom/dnd": {
        "exec": "waybar-dnd",
        "return-type": "json",
        "signal": 2,
        "interval": "once",
        "on-click": "waybar-dnd toggle"
    },
    "custom/recording": {
        "exec": "waybar-recording",
        "return-type": "json",
        "signal": 3,
        "interval": "once"
    },
    "clock": {
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format": " {:%a, %d %b    %H:%M}"
    },
    "cpu": {
        "format": " {usage}%",
        "states": {
            "warning": 70,
            "critical": 90
        }
    },
    "memory": {
        "format": " {}%",
        "states": {
            "warning": 70,
            "critical": 90
        }
    },
    "backlight": {
        "format": "{icon} {percent}%",
        "format-icons": [""]
    },
    "battery": {
        "bat": "BAT0",
        "states": {
            "warning": 30,
            "critical": 15
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["", "", "", "", ""]
    },
    "network": {
        "interval": 2,
        "interface": "wlan0",
        "format-wifi": " {essid}",
        "format-ethernet": " {ifname}",
        "format-linked": " {ifname}",
        "format-disconnected": "  ",
        "tooltip-format": "{ifname}: {ipaddr}/{cidr}\n {bandwidthDownBits}\n {bandwidthUpBits}"
    },
    "pulseaudio": {
        "format": "{icon} {volume}%   {format_source}",
        "format-bluetooth": "{icon} {volume}%   {format_source}",
        "format-bluetooth-muted": " {icon}   {format_source}",
        "format-muted": "   {format_source}",
        "format-source": " {volume}%",
        "format-source-muted": "",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        },
        "on-click": "pavucontrol"
    }
}
</pre></details>

`style.css`:
<details><pre>
@define-color background #282828;
@define-color foreground #ebdbb2;
@define-color black      #222222;
@define-color yellow     #fabd2f;
@define-color red        #fb4934;
@define-color green      #b8bb26;

* {
    border: none;
    border-radius: 0;
    font-family: Input, "Font Awesome 5 Free";
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background: @background;
    color: @foreground;
    transition-property: background-color;
    transition-duration: 0.5s;
}

#workspaces button {
    padding: 0 10px;
    background: transparent;
    color: @foreground;
    border-top: 3px solid @background;
    border-bottom: 3px solid transparent;
}

#workspaces button.focused {
    border-bottom: 3px solid @green;
}

#workspaces button.urgent {
    border-bottom: 3px solid @yellow;
}

#mode {
    background-color: @black;
    border-top: 3px solid @black;
    border-bottom: 3px solid @red;
}

#custom-updates,
#custom-mail,
#custom-vpn.off,
#battery.warning,
#memory.warning,
#cpu.warning,
#custom-dnd.on,

#custom-systemd,
#battery.critical,
#memory.critical,
#cpu.critical,
#custom-yubikey,
#custom-recording {
    border-bottom: 3px solid @red;
}

#battery.charging {
    border-bottom: 3px solid @green;
}

#mode,
#pulseaudio,
#custom-yubikey,
#custom-systemd,
#custom-updates,
#network,
#cpu,
#memory,
#backlight,
#battery,
#clock {
    padding: 0 6px;
    margin: 0 6px;
}

#custom-vpn,
#custom-dnd,
#custom-recording {
    padding: 0;
    margin: 0 6px;
}

#tray {
    margin-left: -1000000px;
}
</pre></details>

I was trying to reproduce it by hand but could not find out what could cause it. Also checked at all my `systemd-timers` if they could somehow be related to it, but there is none which runs every half an hour.

Any ideas?

**Comment by Alexays** [comment]
Should be fixed on master
