### ISSUE TITLE
Clock stuck at same minute

### ISSUE THREAD

**Issue by kushraj** [Alexays/Waybar#1012]
Clock's minute letters are stuck at `:02` for any hour,  and hour changes a few minutes before it actually should. like in real time if its 3:30PM, waybar is showing it as 3:02PM, which changes to 5:02 somewhat a bit before 5 PM in real time.

Locale Output :

    LANG=en_IN.UTF-8
    LC_CTYPE="en_IN.UTF-8"
    LC_NUMERIC="en_IN.UTF-8"
    LC_TIME="en_IN.UTF-8"
    LC_COLLATE="en_IN.UTF-8"
    LC_MONETARY="en_IN.UTF-8"
    LC_MESSAGES="en_IN.UTF-8"
    LC_PAPER="en_IN.UTF-8"
    LC_NAME="en_IN.UTF-8"
    LC_ADDRESS="en_IN.UTF-8"
    LC_TELEPHONE="en_IN.UTF-8"
    LC_MEASUREMENT="en_IN.UTF-8"
    LC_IDENTIFICATION="en_IN.UTF-8"
    LC_ALL=

waybar [configs and log](https://gist.github.com/kushraj/3ef542b12db153244a5d51541b4bdb8b)
Waybar v0.9.5
sway version 1.5-89b4bc4b (Feb  2 2021, branch 'master')

**Comment by alebastr** [comment]
> Clock's minute letters are stuck at :02 for any hour, and hour changes a few minutes before it actually should.
```
"clock": {
    ...
    "format": "{:%I:%m %p}"
 },
```
Your clock format is hour:month.  The format string you'd want to use is `"{:%I:%M %p}"`

> and hour changes a few minutes before it actually should.

Is your system time correct? The code may give an error within one minute (clock module update interval), but I don't see how it can result in a larger inaccuracy.
