### ISSUE TITLE
SIGUSR2 kills waybar

### ISSUE THREAD

**Issue by luqasz** [Alexays/Waybar#1017]
Sending `SIGUSR2` instead of reloading it, kills it. 
Waybar v0.9.3
ubuntu 20.04

**Comment by mvdan** [comment]
I was also confused by this. I assumed I misunderstood the docs, so to "reload" the config I just kill it and manually start it again now.

**Comment by kepet19** [comment]
Hey.
SIGUSR2 is not even in the latest release version 0.9.5. it just kills the program. 
It does have SIGUSR1 too toggle the bar. 
@Alexays has to release a new version. 
If you compile from the master branch it works perfectly.

**Comment by mvdan** [comment]
Ah, I see. Maybe the wiki docs should clarify what features aren't released yet, to avoid confusion with users.

**Comment by Alexays** [comment]
Yeah that the issue with the Github wiki...
We can probably specify the version in which the functionality has been implemented.
