### ISSUE TITLE
mpd icon rendering

### ISSUE THREAD

**Issue by nicodebo** [Alexays/Waybar#1020]
Hello,
I'm using the default configuration for mpd and the double parenthesis does not render like it should (see picture attached herebelow)

![20210206_16h07m39s_grim](https://user-images.githubusercontent.com/20422995/107121969-7d81b380-6895-11eb-9e72-afa76ca0f4a6.png)

Info:

Waybar v0.9.5
sway version 1.5.1

```
> pacman -Qi waybar
...
Optional Deps : otf-font-awesome: Icons in the default configuration [installed]
...
```

**Comment by Alexays** [comment]
Dups of #606
