### ISSUE TITLE
Repeated 'waitpid failed: No child processes' & high CPU usage

### ISSUE THREAD

**Issue by tiosgz** [Alexays/Waybar#1023]
OK, I have solved the problem for myself so this is more a question.

I have a widget with static text that I want to have a CSS class (`custom/text#some-class` didn’t work for me; let’s suppose I want a dynamic class where this way isn’t an option). I have set its interval to be once & its exec to be `echo -e 'hi\n\nsome-class'`.

Usually it’s okay, but when I execute waybar ~~on kiwmi startup~~ in a sh script (changing it to zsh fixes it), the widget doesn’t appear & in the debug-level output I get `waitpid failed: No child processes` over 100 times a millisecond (I have a 1GiB log from about 2 minutes). This fact itself wouldn’t hurt so much, but the CPU usage gets to 50 to 100 % very soon.

I looked in the process tree (after adjusting the exec entry to loop infinitely), and it seems to be as expected.

I am using waybar v0.9.5.

What I want to ask:

- Do you know what could be the cause or what’s happening?
- Is it possible to catch that error & stop the loop immediately?

Update: today I tried to restart waybar via a key binding, spawned from kiwmi using sh — the result was the same, so it seems to depend only on that it’s `sh` & that it isn’t an interactive shell…

**Comment by kepet19** [comment]
I have this file for easy logging of programs. 
`autolog`
```
#!/usr/bin/env sh
mkdir -p /tmp/autolog
"$@" > /tmp/autolog/"$1.log" 2>&1
```

so i can say something like `autolog waybar` and I can se what is in the output by going to `/tmp/autolog/waybar.log`

if you do this. Does it then fix the problem with maybe not having an interactive shell?

**Comment by tiosgz** [comment]
> Does it then fix the problem with maybe not having an interactive shell?

No, it doesn’t… I can even add `&` at the last line of `autolog`, and when I run it from zsh, everything is okay. When there’s only sh, it’s broken again.

The issue itself seems to depend on one or both of

- how the shell handles disowning child processes
- if the shell is fast enough to exit &/ disown the background processes before waybar gets what it needs.

But look, I am like a child in this area; everything I say is pure guessing. I’d be very grateful if someone who understands it could reproduce this & find out what’s going wrong.

***

Even if this shell mystery cannot be solved, I hope it isn’t complicated to catch that concrete error and let the module just fail.

**Comment by kepet19** [comment]
just to be sure you have a script like this? 
`launch.sh` 
```sh
#!/bin/sh        this is what is wrong?
# and then you have this line? 
waybar & disown 
```

then you bind this script in a wm to launch it?

**Comment by kepet19** [comment]
I am not sure what is wrong.  
Can you send me the startup file when it fails and the startup file when it works? 
as I understand it you have a file like this 
`launcher.sh`
```sh
#!/bin/sh # this is the problem with sh instead of zsh maybe?
# then you have something like this?
waybar & disown
````

afterwards you bind this script to a key or something?

**Comment by tiosgz** [comment]
Sorry, I now don't have my computer for a few weeks, but I'll give you (the relevant parts of) the files that I used ASAP.

I *think* that I didn't use `disown`, but I'm not sure.

**Comment by kepet19** [comment]
You should not need to disown. 
I was just asking so I could try to reproduce it.

**Comment by tiosgz** [comment]
The waybar config (the CSS file can be empty)

```json
{
  "layer": "bottom",
  "position": "top",
  "height": 20,
  "modules-center": [ "custom/some-text" ],
  "custom/some-text": { "interval": "once", "exec": "echo called >&2; echo -ne 'Hi there\\n\\ncls'", },
}
```
Success is when the text `Hi there` appears & waybar doesn’t use too much CPU.

The kiwmi config is unfortunately much longer to not end up unable to do anything. The important parts are marked by horizontal rules. It’s all about the `zsh`/`sh` in the `spawn` lines.
```
kiwmi:spawn([[ zsh -c 'waybar' ]])
```

I made `sh` run on start & on `mod-period` & `zsh` to be executed on `mod-slash` (`mod` is `alt` if you run kiwmi in another graphical server, else `super`). The `sh -c` wrappers aren’t really needed, they’re there just for sort of consistency. Using `& disown` makes no difference.

Use `mod-escape` to quit kiwmi.

<details><summary>The full <code>~/.config/kiwmi/init.lua</code></summary>

```lua
terminal = os.getenv("TERM") or "alacritty"
if terminal == "linux" then terminal = "alacritty" end
mod = "super" -- "alt"
cursor = kiwmi:cursor()
last_view_under_cursor = nil
kbds = {}

cursor:on("motion", function()
  local view = cursor:view_at_pos()
  if view and not (view == last_view_under_cursor) then
    view:focus()
    last_view_under_cursor = view
  end
end)

cursor:on("button_down", function(btn)
  local view = cursor:view_at_pos()
  if not view then return end
  local keymod = false
  for _, kbd in pairs(kbds) do
    if kbd and kbd:modifiers()[mod] then
      keymod = true
      break
    end
  end
  if not keymod then return end
  if btn == 1 then
    view:imove()
    return true
  elseif btn == 2 then
    view:iresize({ "bottom", "right" })
    return true
  end
end)

cursor:on("button_up", function()
  kiwmi:stop_interactive()
end)

kiwmi:on("output", function(out)
  out:move(0, 0)
  -- if running under another session, use "alt" as the main modifier
  if string.find(out:name(), "[xX]11")
     or string.find(out:name(), "[wW][lL]") then
    mod = "alt"
  end
end)

kiwmi:on("view", function(view)
  view:show()
  view:focus()
  view:on("request_move", function(v)
    v:imove()
  end)
  view:on("request_resize", function(tbl)
    tbl.view:iresize(tbl.edges)
  end)
  view:on("destroy", function()
    local v = cursor:view_at_pos()
    if v then
      v:focus()
    end
  end)
end)

keybinds = {
  Escape = function()
    kiwmi:quit()
  end,
  Return = function()
    kiwmi:spawn(terminal or "alacritty")
  end,
  w = function()
    local view = kiwmi:focused_view()
    if view then view:close() end
  end,
---------------------------------------------------------------------------
  slash = function()
    kiwmi:spawn([[ zsh -c 'killall waybar; waybar' ]])
  end,
  period = function()
    kiwmi:spawn([[ sh -c 'killall waybar; waybar' ]])
  end,
  comma = function()
    kiwmi:spawn([[ killall waybar ]])
  end,
}

kiwmi:on("keyboard", function(keyboard)
  table.insert(kbds, keyboard)
  keyboard:on("key_down", function(ev)
    if ev.raw and ev.keyboard:modifiers()[mod] then
      local bind = keybinds[ev.key]
      if bind then
        bind(ev)
        return true
      end
    end
  end)
end)

---------------------------------------------------------------------------
kiwmi:spawn([[ sh -c 'waybar' ]])

-- vim: et:ts=2:sw=2
```

</details>
