### ISSUE TITLE
wlr/taskbar hide specific icons based on app_id [feature request]

### ISSUE THREAD

**Issue by bluebyt65** [Alexays/Waybar#1029]
I wish we can hide specific icons based on app_id on the module wlr/taskbar.
You can see in my bar that I have a lot of terminals and other icons I don't want to see.
Example
"Hide": "thunar","tilix", "org.gnome.Nautilus", "virt-manager", "conky"

![slurped](https://user-images.githubusercontent.com/18442224/107450910-39e8ad00-6b14-11eb-9613-f3d0cca49b99.png)

**Comment by Anakael** [comment]
Is any updates here?
I think I can implenent this if no one has't started yet.

**Comment by bluebyt65** [comment]
I don't think it's been implemented yet.

**Comment by Alexays** [comment]
Fixed by #1074 thx @Anakael!
