### ISSUE TITLE
Unhandled exception in signal handler

### ISSUE THREAD

**Issue by mithodin** [Alexays/Waybar#104]
With waybar-0.2.2, starting waybar fails with
```
(waybar:13299): glibmm-ERROR **:
unhandled exception (type std::exception) in signal handler:
what: argument not found
```
this is fixed by removing the comment around signal in main.cpp which has been introduced in https://github.com/Alexays/Waybar/blob/0abaaf2f7fcf606b470cf9ceca94ac5f08dd78c2/src/main.cpp#L16

**Comment by mithodin** [comment]
disregard that, it was a different issue that I fixed by mistake ^^

**Comment by Alexays** [comment]
This error is when you pass an argument {test} that doesn't exist, I should make a cleaner error
