### ISSUE TITLE
Allow custom tooltips for custom module.

### ISSUE THREAD

**Issue by LuxLucian** [Alexays/Waybar#1042]
I may be wrong, but it seems like the format and tooltip of the custom modules are always identical. Would it be possible to add custom tooltips for the module?

**Comment by g33kex** [comment]
If you set `return-type` to `json`, your custom command can return a `tooltip` string that will be used for the tooltip. See [here](https://github.com/Alexays/Waybar/wiki/Module:-Custom).

**Comment by LuxLucian** [comment]
Ah, thank you for the answer!
