### ISSUE TITLE
network state disconnected, even when connected

### ISSUE THREAD

**Issue by kevinoid** [Alexays/Waybar#1044]
With waybar 0.9.5 or `master` (cb1c7ea) on Debian testing with Linux 5.11, if a network interface is brought up after waybar has started, it shows the format for state disconnected even after the interface has been configured.  To demonstrate, using the configuration:

```json
{
  "modules-right": [
    "network"
  ],
  "network": {
    "format": "{ifname}: {ipaddr}/{cidr}",
    "format-disconnected": "{ifname}: Disconnected"
  }
}
```
On a machine with wireless interface (`wlp3s0`) initially disabled by soft rfkill (`nmcli radio wifi on`) and a wired interface (`enp0s25`) initially connected:

1. Run `waybar --config config`.
    Waybar correctly displays `enp0s25: 192.168.0.2/24`.
2. Bring down `enp0s25` (e.g. `nmcli device disconnect enp0s25`).
    Waybar correctly displays `enp0s25: Disconnected`.
3. Bring up `enp0s25` (e.g. `nmcli device connect enp0s25`).
    Waybar still **incorrectly** displays `enp0s25: Disconnected`.

Let me know if there's anything else I can do to help troubleshot.

Thanks,
Kevin

**Comment by sigmavirus24** [comment]
Related to one of #999 or #816 or #388 maybe?

**Comment by kevinoid** [comment]
Good catch.  Looks like a duplicate of #388 to me.  Sorry for the noise.

**Comment by sigmavirus24** [comment]
No worries. I was looking into this too and found a bunch of them. Just wanted to see if they were all related/the same issue.
