### ISSUE TITLE
Request: separate css class for pulseaudio-source

### ISSUE THREAD

**Issue by Macellatore** [Alexays/Waybar#1045]
I'd love to have a way to style the pulseaudio-source submodule indipendently from the main module.
Right now i'm styling #pulseaudio and #pulseaudio.muted using different colors, but this is affecting pulsaudio-source data too.
I wish we could have two additional styles, something like #pulseaudio-source and #pulseaudio-source.muted, to manage the mic data by itstelf.
EDIT: wait, i think this could be a double of what basically  #974 asks for.

**Comment by Alexays** [comment]
#974 merged into master
