### ISSUE TITLE
Steam flatpak icon not showing in tray

### ISSUE THREAD

**Issue by JordanL2** [Alexays/Waybar#1046]
Latest stable release (0.9.5-2) on Arch, with Wayfire.

I have the Steam flatpak installed, and when it's running the icon in the tray is broken. In the logs I see:
```
(waybar:985709): Gtk-WARNING **: 13:05:11.064: Could not find the icon 'steam_tray_mono'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
[2021-03-08 13:05:11.075] [error] Item 'steam': Icon 'steam_tray_mono' not present in theme breeze-dark
[2021-03-08 13:05:11.076] [error] Item 'steam': Icon 'steam_tray_mono' not present in theme breeze-dark
```

Here are the XDG environment variables I've set:
```
XDG_CACHE_HOME=/home/jordan/.cache
XDG_CONFIG_HOME=/home/jordan/.config
XDG_CURRENT_DESKTOP=KDE
XDG_DATA_DIRS=/home/jordan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/home/jordan/.var/app/com.valvesoftware.Steam/data:/usr/local/share:/usr/share
XDG_RUNTIME_DIR=/run/user/1000
```

Now, I've made symlinks in the `~/.local/share/flatpak/exports/share/icons/hicolor` directories so that `steam_tray_mono.png` always symlinks to `com.valvesoftware.Steam.png` in the same directory for all icon sizes, as otherwise the fact the flatpak's icons have a different name would cause this issue. This hasn't fixed the issue though, and I think it's due to this error:
```
The 'hicolor' theme was not found either, perhaps you need to install it.
```

This is very confusing, as there is a `icons/hicolor` directory in the following locations:
```
/home/jordan/.local/share/flatpak/exports/share
/home/jordan/.var/app/com.valvesoftware.Steam/data
/usr/share
```

This makes me think for some reason the problem is it's simply not looking for the hicolor directories in the XDG_DATA_DIRS locations. Wofi is finding icons in those locations fine if that's relevant.

**Comment by JordanL2** [comment]
Ok never mind I worked out the issue, the icon needs to be in `/usr/share/pixmaps/`.

**Comment by filmor** [comment]
Why did you close this issue, though? Isn't the underlying problem (not checking  `/pixmaps`) still present?
