### ISSUE TITLE
[Feature Request] AutoHide

### ISSUE THREAD

**Issue by varbhat** [Alexays/Waybar#1048]
I want  Autohide Feature in Waybar. Waybar must only show when the cursor is over it or cursor reaches the edge. I want this as option.

Popular Panel for xorg , tint2 has this feature.

[wf-shell](https://github.com/WayfireWM/wf-shell) too has the feature of autohide.

It would be good if this feature is implemented in Waybar too.

**Comment by varbhat** [comment]
How time flies!!

https://github.com/Alexays/Waybar/pull/2248

**Comment by feyokorenhof** [comment]
So this didn't get merged? I would love to have this as I have an OLED laptop and it hurts me to accidentally keep it shown.
