### ISSUE TITLE
Allow not cycling when scrolling through sway workspaces

### ISSUE THREAD

**Issue by ozls** [Alexays/Waybar#1057]
Hi! Thanks a lot for Waybar to everyone involved, it's really great and customizable. I have a feature I would like to suggest.
When you scroll through sway workspaces and you reach past the last one, you cycle back to the first one. I would like this to be optional, such that you would stay at the last workspace. Would that seem feasible? It could take the form of an option "no-cycle" in the "sway/workspaces" module.

**Comment by Alexays** [comment]
The setting you want is `disable-scroll-wraparound` c.f. https://github.com/Alexays/Waybar/wiki/Module:-Sway#workspaces
