### ISSUE TITLE
Feature Request : Pulsuaudio Module

### ISSUE THREAD

**Issue by kushraj** [Alexays/Waybar#1060]
It will really help a lot if there pulseaudio module on click, shows and allows to toggle between all the sound devices connected.

**Comment by etircopyh** [comment]
What are you talking about? PulseAudio module is already available. You can assign anything you want for a click action by executing custom script/binary/app.

Here's what I do:
```
 "on-click": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
 "on-click-right": "pavucontrol-qt"
```

So, your 'feature' is basically already present, let alone ability to write your own modules with [custom](https://github.com/Alexays/Waybar/wiki/Module:-Custom).

**Comment by Alexays** [comment]
As @etircopyh said, you can assign cmd to click handlers.
Otherwise, i'll close in favour of #33
