### ISSUE TITLE
Waybar is unstable when used on multiple monitors

### ISSUE THREAD

**Issue by MrKorner** [Alexays/Waybar#1062]
I am using wayfire with waybar on 2 monitors, named EDP1 laptop, and HDMI monitor, i have noticed that wayfire crashes often on this setup without any errors or logs given as to reason what happened.
It happens mostly when some new icon is loaded.
my config is at https://github.com/MrKorner/DotFiles/blob/main/configs/waybar/config
And waybar never crashed so far under single monitor instance

EDIT: version is v0.9.5

**Comment by Alexays** [comment]
Are using the master version?
Just release another version, 0.9.6, can you test with this version and reopen the issue, if your problem persist.
