### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by bemeurer** [Alexays/Waybar#107]
I'm currently compiling this on Gentoo, and found that not having the dependencies explicitly listed to be quite a pain. It'd be nice to have them in the readme.

**Comment by Alexays** [comment]
the name of the packets differs according to the distributions but to get an idea you can look at the meson.build https://github.com/Alexays/Waybar/blob/master/meson.build#L36
But i can provide a generic list maybe...

**Comment by Alexays** [comment]
Added dependencies to README
