### ISSUE TITLE
Regarding custom config from examples page

### ISSUE THREAD

**Issue by zeljkosh** [Alexays/Waybar#1082]
[this](https://github.com/cjbassi/config/tree/master/.config/waybar) it shows only .css file and his config file, but he uses custom modules that are not attached, does anyone know how  can i obtain them ? I know its not an actual bug from Waybar, but i think this would be best place to ask, since it example 1 on the example page and i cant get to work.

**Comment by zeljkosh** [comment]
[here ](https://i.ibb.co/MPd5WdJ/2021-04-26-T18-41-41-683142923-02-00.png) you can see how it looks on my screen. I dont know where to get those custom modules that are referenced in his .config file.

**Comment by Alexays** [comment]
You can create an issue in cjbassi/config repo, as it's not waybar default configuration.
