### ISSUE TITLE
Non exclusive bar.

### ISSUE THREAD

**Issue by snakedye** [Alexays/Waybar#1091]
Is it possible to make the bar's surface non exclusive?

**Comment by Kaligule** [comment]
What does "non exclusive" mean?

**Comment by snakedye** [comment]
https://github.com/swaywm/wlroots/blob/beae3018cbbbbb566e964de63cf04e405b7d8ba5/protocol/wlr-layer-shell-unstable-v1.xml#L152

Other surfaces can be displayed on top of the bar

**Comment by LogicalOverflow** [comment]
I wrote a small patch for that a while back (https://github.com/LogicalOverflow/Waybar/commit/c48a8bf87b1eb1209bd5e481f2203c3cd4436d55), it worked fine, but i decided that I didn't like the result (as in, I came to the realization that I disliked the non-exclusive bar). 

The patch adds `disable_exclusive_zone` as a config option and if set, just makes the `setExclusiveZone` functions more or less no-ops.

I can create a PR, if there is interest.

**Comment by alebastr** [comment]
Apparently I also had that implemented in one of the local branches. Part of infra support for swaybar ipc protocol which I never had time to finish :crying_cat_face: 
Extracted and published as [alebastr@`exclusive-and-passthrough`](https://github.com/alebastr/Waybar/commits/exclusive-and-passthrough), will send a PR later.
