### ISSUE TITLE
Output issue with tail + jq

### ISSUE THREAD

**Issue by soywod** [Alexays/Waybar#1097]
When a custom script is piped to [`jq`](https://stedolan.github.io/jq/), the output seems to be discard:

```sh
echo 42 > /tmp/file
```

```json
"custom/script": {
    "exec": "tail -f /tmp/file | jq -r '.'"
},
```

If I execute this command in my terminal I see well `42`. But it does not show `42` in the bar.
If I replace the command with `echo 42 | jq -r '.'`, it works.
If I replace the command with `tail -f /tmp/file` it also works.

Any clue on what's going on there?

---

`waybar -v`: Waybar v0.9.5
`uname -a`: Linux workstation 5.10.11-arch1-1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 x86_64 GNU/Linux

**Comment by YerinAlexey** [comment]
You should use `jq --unbuffered` in this case, this way jq will print the results immediately instead of buffering them until the file closes

**Comment by soywod** [comment]
Works like a charm, thanks for the help!
