### ISSUE TITLE
Unknown module: sway/*

### ISSUE THREAD

**Issue by daenney** [Alexays/Waybar#111]
I'm running in Sway 1.0-beta2 and when I run waybar I get:

```
Resources files: /home/daenney/.config/waybar/config, /etc/xdg/waybar/style.css
Unknown module: sway/workspaces
Unknown module: sway/mode
Unknown module: sway/window
```

Seeing how the Sway modules are built-in, I'm confused as to how this happens. I built Waybar with the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=waybar-git).

**Comment by Alexays** [comment]
Did you install sway after waybar ?

**Comment by Alexays** [comment]
What do you get if you do the command `where sway`?

**Comment by Alexays** [comment]
Otherwise I can make a meson option to force sway even if it doesn't find the binary

**Comment by daenney** [comment]
```sh
~ ❯❯❯ which sway
/usr/bin/sway
~ ❯❯❯ whereis sway
sway: /usr/bin/sway /etc/sway /usr/share/man/man5/sway.5.gz /usr/share/man/man1/sway.1.gz
```

**Comment by daenney** [comment]
As far as my sway config goes:

```
 {
    swaybar_command waybar
}
```

**Comment by Alexays** [comment]
Maybe just try recompiling waybar

**Comment by Alexays** [comment]
Otherwise if it changes nothing, go in the meson file and removes the if ```if find_program('sway', required : false).found()``` and recompile, I will do the option when I find the time ,sorry

**Comment by daenney** [comment]
Oh, I think I might know the issue. I build Waybar in a chroot, and there's no makedepends or regular depends on Sway, so I guess that didn't get built?

**Comment by daenney** [comment]
Alright, so I had to update the `PKGBUILD` like this:

- Change the `depends` on `wlroots` to `wlroots-git`
- Add a `makedepends` on `sway-git`

Now everything works!

**Comment by Alexays** [comment]
Right! I keep the issue open to think about making the changes thanks :)

**Comment by daenney** [comment]
Awesome. And thanks for creating Waybar, it's great!

**Comment by Alexays** [comment]
Added sway-git as a optdepend in the PKGBUILD
