### ISSUE TITLE
Undefined behavior in Battery.cpp

### ISSUE THREAD

**Issue by danielrparks** [Alexays/Waybar#1110]
I have a battery with the following files in sysfs:
```
$ ls /sys/class/power_supply/hid-0018\:04F3\:2A82.0008-battery
capacity  device  hwmon5  model_name  online  power  powers  present  scope  status  subsystem  type  uevent  wakeup37
```
Waybar detects this as a battery and adds it to the batteries_ map here: https://github.com/Max1Truc/Waybar/blob/master/src/modules/battery.cpp#L90

Then it tries to read files that the battery doesn't have here: https://github.com/Max1Truc/Waybar/blob/master/src/modules/battery.cpp#L166

And then it uses the values which were meant to be read from the files (but weren't, so they are uninitialized) here: https://github.com/Max1Truc/Waybar/blob/master/src/modules/battery.cpp#L182

Waybar should either not consider batteries that are missing the files that it reads, or have some fallback mechanism if it can't read the file.

**Comment by Max1Truc** [comment]
May you check if it works by replacing `power_now` with `power` on the linked line ? 
https://github.com/Max1Truc/Waybar/blob/master/src/modules/battery.cpp#L165

It it works I may submit a PR which checks for the presence of `power` if there are no `current_now` or `power_now`

**Comment by danielrparks** [comment]
That's not sufficient to fix the issue, because there will still be undefined behavior when computing the percentage using the `energy_now` and `energy_full` values.

**Comment by Max1Truc** [comment]
Could you post the output of `upower -i PATHOFBATTERY` where you can get `PATHOFBATTERY` with `upower -e` ?
I would like to check if upower figures out a way to know the percentage.

**Comment by danielrparks** [comment]
```
$ upower -i /org/freedesktop/UPower/devices/keyboard_hid_0018o04F3o2A82x0008_battery
  native-path:          hid-0018:04F3:2A82.0008-battery
  model:                04F31234:00 04F3:2A82
  power supply:         no
  updated:              Tue 18 May 2021 03:48:14 PM CDT (7 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       critical
    percentage:          1%
    icon-name:          'battery-caution-symbolic'

```
It looks like it's just falling back to something near zero.
I don't think this device is properly supported by Linux, so it makes sense that it's missing charge values.

**Comment by Max1Truc** [comment]
So do you think it should be ignored by Waybar ?

**Comment by danielrparks** [comment]
Probably, or at least it should be ignored if not explicitly configured, and if explicitly configured it should be reported as 0% (basically what UPower is doing).

**Comment by Alexays** [comment]
Is it better with #1105? @danielrparks

**Comment by danielrparks** [comment]
That change still exhibits undefined behavior, because [it will still attempt](https://github.com/Amanieu/Waybar/blob/4d067619a8f72aebd64042db9d686c6ef15a0a3e/src/modules/battery.cpp#L191) to read from files that do not exist.

As a result, the values `power_now`, `energy_full`, `energy_now`, and `energy_full_design` will all be uninitialized when added to the total values starting [here](https://github.com/Amanieu/Waybar/blob/4d067619a8f72aebd64042db9d686c6ef15a0a3e/src/modules/battery.cpp#L201). If the battery with missing info is the first battery, they will be garbage data; otherwise it will likely use the values from the previous battery which will skew the average.
