### ISSUE TITLE
bar is crashing when hotswapping battery :shrug: 

### ISSUE THREAD

**Issue by mintyleaf** [Alexays/Waybar#1111]
so i have x260 thinkpad and two batteries
i trying to use them "balanced", so i removed spring in right handler, so i can physically "disconnect" battery on the go

in battery.cpp there are exception throwing if battery didn't exist
and it raising, when i switching off battery, so the bar is crashin

can battery module handle this by some setting like "i don't care about that removed battery, just didn't show any output and wait for  it connect again"?)

**Comment by Alexays** [comment]
Are you talking about this throw?
https://github.com/Alexays/Waybar/blob/master/src/modules/battery.cpp#L104

**Comment by mintyleaf** [comment]
@Alexays 
nope, this: https://github.com/Alexays/Waybar/blob/94a882bf95b750173bd8071f579dada00545b170/src/modules/battery.cpp#L121
