### ISSUE TITLE
pulseaudio module leaks connections

### ISSUE THREAD

**Issue by Birdulon** [Alexays/Waybar#1115]
This probably won't affect too many people, but an unrelated problem with my setup has exposed this.
In my case, I have a display that keeps disconnecting/reconnecting while in standby. This results in waybar constantly removing and recreating bars on that display, and adding new pulseaudio connections, sadly without removing the old ones. This becomes noticeable when applications suddenly can't output any sound, and logs reveal pulseaudio rejecting new connections because the limit of 64 concurrent connections has been reached.

**Comment by lilydjwg** [comment]
I think I've fixed this but not very sure: https://github.com/lilydjwg/Waybar/tree/fixpa. Would you give it a try?

**Comment by Birdulon** [comment]
> I think I've fixed this but not very sure: https://github.com/lilydjwg/Waybar/tree/fixpa. Would you give it a try?

Looks good, running it now.

**Comment by Birdulon** [comment]
So far so good!

**Comment by lilydjwg** [comment]
Great, I didn't encounter any issue either. I've opened a pull request.
