### ISSUE TITLE
network shows disconnected interface instead of connected

### ISSUE THREAD

**Issue by kevinoid** [Alexays/Waybar#1117]
Since @Alexays asked for testing of @tperard's recent `network` changes in https://github.com/Alexays/Waybar/issues/388#issuecomment-849881941, I ran a few tests with `master` (5444a66) and noticed an issue:

On a computer with both a wireless interface (`wlp3s0`) and an ethernet interface (`enp0s25`), when the wireless interface goes down, Waybar displays information for the disconnected wireless interface rather than the connected ethernet interface.  To reproduce, using the following `config`:

```json
{
  "modules-left": [
    "network"
  ],
  "network": {
    "format": "{ifname}:{ipaddr}/{cidr}",
    "format-disconnected": "{ifname}:Disconnected"
  }
}
```

1. Start with wireless connected and ethernet disconnected.
   `nmcli status` reports:

       DEVICE   TYPE      STATE         CONNECTION
       wlp3s0   wifi      connected     WifiConn
       enp0s25  ethernet  unavailable   --
       lo       loopback  unmanaged     --

   `ip -4 -br addr` reports:

       lo               UNKNOWN        127.0.0.1/8
       wlp3s0           UP             192.168.21.10/24

   Start Waybar: `waybar -c config -l trace`.
   Waybar shows `wlp3s0:192.168.21.10/24`
2. Connect ethernet cable.
   `nmcli status` reports:

       DEVICE   TYPE      STATE         CONNECTION
       enp0s25  ethernet  connected     EthConn
       wlp3s0   wifi      connected     WifiConn
       lo       loopback  unmanaged     --

   `ip -4 -br addr` reports:

       lo               UNKNOWN        127.0.0.1/8
       enp0s25          UP             192.168.21.22/24
       wlp3s0           UP             192.168.21.10/24

   Waybar shows `wlp3s0:192.168.21.10/24`
3. Disconnect wireless (`nmcli device disconnect wlp3s0`).
   `nmcli status` reports:

       DEVICE   TYPE      STATE         CONNECTION
       enp0s25  ethernet  connected     EthConn
       wlp3s0   wifi      disconnected  --
       lo       loopback  unmanaged     --

   `ip -4 -br addr` reports:

       lo               UNKNOWN        127.0.0.1/8
       enp0s25          UP             192.168.21.22/24

   Waybar shows `wlp3s0:Disconnected`

After step 3, I would have expected `enp0s25:192.168.21.22/24`, as Waybar 0.9.5 does, since the info for the disconnected interface is less useful than the connected one.  (Note: 0.9.5 shows `enp0s25` when both are connected, then continues showing it when `wlp3s0` is disconnected.)

Capture of `stdout` with `-l trace` during the procedure described above:

    [2021-05-27 16:14:46.283] [info] Resources files: config, /home/kevin/.config/waybar/style.css
    [2021-05-27 16:14:46.290] [debug] Output detection done: LVDS-1 (Unknown 0x213E 0x00000000)
    [2021-05-27 16:14:46.293] [debug] network: new default route via if3
    [2021-05-27 16:14:46.293] [debug] network: wlp3s0, new addr 192.168.21.10/24
    [2021-05-27 16:14:46.331] [debug] GTK widget tree:
    window#waybar.background.LVDS-1.:dir(ltr)
      decoration:dir(ltr)
      box.horizontal:dir(ltr)
        box.horizontal.modules-left:dir(ltr)
          widget:dir(ltr)
            label#network:dir(ltr)
        box.horizontal.modules-center:dir(ltr)
        box.horizontal.modules-right:dir(ltr)
    
    [2021-05-27 16:14:46.333] [info] Bar configured (width: 1600, height: 17) for output: LVDS-1
    [2021-05-27 16:17:16.810] [debug] network: wlp3s0 addr deleted 192.168.21.10/24

Thanks for working on it!
Kevin

**Comment by tperard** [comment]
Hi, thanks for testing!

I think I've managed to reproduce the issue when using NetworkManager, so I should be able to fix the issue.

Thanks.

**Comment by kevinoid** [comment]
Thanks for investigating and implementing a fix @tperard!

Unfortunately, while testing it I noticed a similar issue now occurs when changing connections in the opposite order (disconnecting ethernet after both connected).  I opened #1129 to track that issue.  Sorry to be the bearer of bad news.
