### ISSUE TITLE
How do custom scripts work?

### ISSUE THREAD

**Issue by daenney** [Alexays/Waybar#112]
I tried something basic like this:

```
modules-right: ["custom/number", ...]

    "custom/number": {
      "format": "{}",
      "exec": "$HOME/.config/waybar/custom_modules/number.sh"
    },
```

Then I made an executable script at `$HOME/.config/waybar/custom_modules/number.sh` which just does `echo 100`.

But nothing shows up, and there's no output telling me something is wrong either.

I tried adding some CSS matching on `#custom-number` but that doesn't seem to be having any effect either.

**Comment by daenney** [comment]
Ah, the custom module definition. So it seems to be that without an interval waybar assumes the script runs forever and outputs as it goes along?

**Comment by Alexays** [comment]
That's right, but still without interval it's still supposed to display so I'll look at it.

**Comment by Alexays** [comment]
Added a warning about stopped endless custom module in 1d96d57b75a6695696ad8638950b3bde3d1d4951
