### ISSUE TITLE
Can't use dynamic colors without window module

### ISSUE THREAD

**Issue by kushraj** [Alexays/Waybar#1128]
changing colors based on current windows doesn't work unless window module is explicitly used in waybar somewhere, 
`
window#waybar.empty  {
    background-color: rgba(0,0,0,0.4);
    border: none;
}
`

it has no effect if i'm not using window module in waybar, is it intentional behaviour?

**Comment by malobre** [comment]
A quick workaround:
```json
{
    "modules-left": ["sway/window"],
    "sway/window": {
        "format": ""
    }
}
```

**Comment by kushraj** [comment]
yeah, i'm basically doing the same. was just wondering if window module is explicily required to be loaded for this feature

**Comment by Alexays** [comment]
Yes, the window module is required for this feature, it may sound weird, but it's this module that knows the number of windows if the current workspaces and so can add these classes
