### ISSUE TITLE
Waybar popups cannot find waybar as parent

### ISSUE THREAD

**Issue by ddorstijn** [Alexays/Waybar#113]
Running waybar on Sway. I can't seem to get the bar working where popups work correctly. They are all spawned as separate windows and in the terminal I get the following error:

Gdk-WARNING **: 02:16:00.427: Couldn't map as window 0x55fe3e1c14c0 as popup because it doesn't have a parent

Did O forget to configure something in the config?

**Comment by Alexays** [comment]
Yeah, it's a known problem #63, I have to look at where it comes from.

**Comment by josteink** [comment]
I'm not having a problem with popups showing up incorrectly, but I still get a similar warning (although not identical):

````
(waybar:326572): Gdk-WARNING **: 11:36:57.668: Couldn't map window 0x555555c0c550 as subsurface because its parent is not mapped.
````

Is this related? Is it a problem?

From what I can tell popups works fine, and I'm not experiencing stability issues related to popups, I just see these warnings in the log.
