### ISSUE TITLE
clock show calendar weeks

### ISSUE THREAD

**Issue by blauch** [Alexays/Waybar#1134]
I am fairly new to swaywm and struggled a bit at first but waybar was really a break through for my transition from KDE. Thanks for the great work! At this point I am missing a small feature specifically in the clock. Is it possible to display calendar weeks in the tooltip?

**Comment by adriangoransson** [comment]
I would appreciate this feature a lot too!

**Comment by spyjetfayed** [comment]
> I am fairly new to swaywm and struggled a bit at first but waybar was really a break through for my transition from KDE. Thanks for the great work! At this point I am missing a small feature specifically in the clock. Is it possible to display calendar weeks in the tooltip?

`"tooltip-format": "<big>{:%Y %B \t   week: %V }</big>\n<tt>{calendar}</tt>"` add this line to "clock" module in config file.

**Comment by adriangoransson** [comment]
> `"tooltip-format": "<big>{:%Y %B \t week: %V }</big>\n<tt>{calendar}</tt>"` add this line to "clock" module in config file.

This only shows the current week. What I (and I guess @blauch) too requests is a way to show the week numbers beside the week in the calendar. Like the output from `cal`.

```console
$ cal -w
       July 2021       
   Mo Tu We Th Fr Sa Su
26           1  2  3  4
27  5  6  7  8  9 10 11
28 12 13 14 15 16 17 18
29 19 20 21 22 23 24 25
30 26 27 28 29 30 31   
```

**Comment by blauch** [comment]
> > `"tooltip-format": "<big>{:%Y %B \t week: %V }</big>\n<tt>{calendar}</tt>"` add this line to "clock" module in config file.
> 
> This only shows the current week. What I (and I guess @blauch) too requests is a way to show the week numbers beside the week in the calendar. Like the output from `cal`.
> 
> ```
> $ cal -w
>        July 2021       
>    Mo Tu We Th Fr Sa Su
> 26           1  2  3  4
> 27  5  6  7  8  9 10 11
> 28 12 13 14 15 16 17 18
> 29 19 20 21 22 23 24 25
> 30 26 27 28 29 30 31   
> ```

yes @adriangoransson, this exactly what I was requesting. My bad if I was not clear enough

**Comment by opalvault** [comment]
@blauch @adriangoransson 

https://github.com/chris-marsh/galendae

Here is a cool little program that does what you'd like in the meantime. You'll need to configure the floating window behavior in the sway configuration as sway wants to dictate where floating windows live for some reason? Maybe something I'm missing.

In my sway config I have: 
`for_window [app_id="galendae"] floating enable, sticky enable, move position cursor, move down 35`

In my waybar config I have:
```   
"clock": {
        "format": "{: %I:%M %A %B %d}",
        "tooltip": false,
        "on-click": "galendae -c $HOME/.config/galendae-cal/galendae.conf"
    },
````
Note: the tooltip: false directive is not working as of 0.9.9 as a heads up.

[Here](https://raw.githubusercontent.com/opalvault/opalfiles/master/.config/galendae-cal/galendae.conf) is a link to my galendae.conf so you can tweak it how you'd like. Like I said before though, I haven't gotten the x, y, and initial placement values to work for me under sway.

**Comment by LukashonakV** [comment]
https://github.com/Alexays/Waybar/pull/1492 on review

**Comment by tmpm697** [comment]
@LukashonakV waybar `0.9.16-1` doesn't show week anymore, I had `"calendar-weeks-pos": "left",` in waybar/config.
follow wiki: https://github.com/Alexays/Waybar/wiki/Module:-Clock

**Comment by LukashonakV** [comment]
Hi @tmpm697 ,
According the history I see there were some changes since my last commits. But 5 days ago the were reverted back. I've just pull the freshest version from the git, built and don't see issue so far.
Please try to build the freshest release fro the trunk and check again.
Config I use
```json
"clock": {
        "format": "{:%H:%M}  ",
        "format-alt": "{:%A, %B %d, %Y (%R)}  ",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "calendar-weeks-pos": "right",
        "today-format": "<span color='#ff6699'><b><u>{}</u></b></span>",
        "format-calendar": "<span color='#ecc6d9'><b>{}</b></span>",
        "format-calendar-weeks": "<span color='#99ffdd'><b>W{:%V}</b></span>",
        "format-calendar-weekdays": "<span color='#ffcc66'><b>{}</b></span>",
        "on-scroll": {
                    "calendar": 1
                     }
    },
```

**Comment by tmpm697** [comment]
Thanks @LukashonakV but I think I'll wait for it on official release on arch even though display week is crucial for me to use calendar.

**Comment by LukashonakV** [comment]
Hi @blauch how to configure calendar please read here [Module Clock](https://github.com/Alexays/Waybar/wiki/Module:-Clock) . Could this issue be closed then?

**Comment by blauch** [comment]
Hi there

Yes, please go ahead and close it. It works great and your efforts are much
appreciated.

Cheers,
Christoph

ViktarL ***@***.***> schrieb am Do., 15. Dez. 2022, 09:12:

**Comment by LukashonakV** [comment]
@blauch I don't have grants for closing ) Please close it as you are an author. Thanks. Best wishes
