### ISSUE TITLE
custom colors based on gtk theme 

### ISSUE THREAD

**Issue by kushraj** [Alexays/Waybar#1136]
Is there any way we can define variables depending on system gtk theme , as in 

    if-dark-gtk-theme {
        @define-color 1 rgb (___);
        @define-color 2 rgb (___)
    }

    if-light-gtk-theme {
        @define-color 1 rgb (___);
        @define-color 2 rgb (___);
    }

**Comment by kushraj** [comment]
nvm, pywal is well suited for this task

**Comment by niksingh710** [comment]
can you explain how u integrated pywal in waybar?
