### ISSUE TITLE
High CPU usage in tray module

### ISSUE THREAD

**Issue by 12101111** [Alexays/Waybar#1138]
![old](https://user-images.githubusercontent.com/8438475/122958204-3a902a80-d3b5-11eb-9d28-41d43276faee.png)

https://github.com/Alexays/Waybar/blob/d08fbb2ef2b2a2cada05fd64e51ffe041aabb47c/src/modules/sni/item.cpp#L169-L176

This is caused by `value.equal(old_value)`.Maybe an upstream issue, the implement of `g_variant_equal` is compare them by their pretty-printing string, which use many CPU cycles.(This is the source code: https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gvariant.c#L2736)

I remove this compare and the CPU usage reduce nearly to zero:

```c++
    for (const auto& [name, value] : properties) {
        proxy_->set_cached_property(name, value);
        setProperty(name, const_cast<Glib::VariantBase&>(value));
    }
```
( But this give me a lot warning : `[2021-06-22 23:58:50.837] [warning] Failed to set tray item property: Fcitx.WindowId, value = 0, err = std::bad_cast` )

![new](https://user-images.githubusercontent.com/8438475/122964147-8ba21d80-d3b9-11eb-8f39-168c8d7808dd.png)

**Comment by alebastr** [comment]
Hm... With all the quirks of various SNI client implementations that was the most compatible way of writing this, so I'd like to preserve the current logic.
Following patch should solve the pretty-printing:
<details>
<summary>diff</summary>

```diff
--- a/src/modules/sni/item.cpp
+++ b/src/modules/sni/item.cpp
@@ -68,6 +68,7 @@ void Item::proxyReady(Glib::RefPtr<Gio::AsyncResult>& result) {
     for (const auto& name : cached_properties) {
       Glib::VariantBase value;
       this->proxy_->get_cached_property(value, name);
+      value.is_normal_form();
       setProperty(name, value);
     }

@@ -165,6 +166,7 @@ void Item::processUpdatedProperties(Glib::RefPtr<Gio::AsyncResult>& _result) {
     auto properties = properties_variant.get();

     for (const auto& [name, value] : properties) {
+      value.is_normal_form();
       Glib::VariantBase old_value;
       proxy_->get_cached_property(old_value, name);
       if (!old_value || !value.equal(old_value)) {
```
</details>

Another option is to infer changed properties from signals and update those unconditionally. I have a rough draft at https://github.com/alebastr/Waybar/commit/sni-enhancements, but it has way too much string comparisons to my taste.

I did not get to profile any of those though. Would appreciate if you can try and compare both.
