### ISSUE TITLE
Dmenu is drawn under waybar

### ISSUE THREAD

**Issue by Sqvid** [Alexays/Waybar#114]
Hey I'm new to waybar (just cloned and built it today) and it seems like a great project. I'm just wondering if there's any way to avoid dmenu being drawn under waybar? Looking through past commits I would've thought this would be fixed by #11 so maybe I'm just missing something? Any help would be much appreciated, thank you :)

P.S. Just using the standard config and style files for waybar.

**Comment by Alexays** [comment]
You can set layer to bottom in your config file :)

**Comment by Sqvid** [comment]
Oh I see it now. Feel silly for not figuring this out :( Thank you nonetheless!

**Comment by romainreignier** [comment]
Thank you @Sqvid and @Alexays 
I think see question should be added to the FAQ in the Wiki.

**Comment by McPig** [comment]
The problem with setting Waybar's layer to bottom is that tooltips of modules will be drawn under any opened application. Is there a way to change it?

**Comment by teutat3s** [comment]
> @Alexays The problem with setting Waybar's layer to bottom is that tooltips of modules will be drawn under any opened application. Is there a way to change it?

I am in the same situation - is there a way to draw tooltips on the top layer, but `waybar` on the bottom layer?
