### ISSUE TITLE
[tray icon] not displaying checkboxes

### ISSUE THREAD

**Issue by coldfix** [Alexays/Waybar#1148]
Hi,

first of all, I'm not sure whether this is a sway/waybar or wayland issue and I'm sorry if this is the wrong location to report. There will be three related issues, and I guess the same remark goes for all of them.

To the point: check boxes in the tray menu are currently not displayed; neither the box nor the check mark if checked.

Minimal example:

Using **Gtk/AppIndicator3**:

```python
from gi import require_version
require_version('Gtk', '3.0')
require_version('AppIndicator3', '0.1')

import signal
from gi.repository import Gtk
from gi.repository import AppIndicator3


def main():
    indicator = AppIndicator3.Indicator.new(
        'checkbox-test-app', 'dialog-error',
        AppIndicator3.IndicatorCategory.OTHER)
    indicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)
    indicator.set_menu(build_menu())
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Gtk.main()


def build_menu():
    check = Gtk.CheckMenuItem('CheckMenuItem')
    check.connect('activate', on_menuitem_check)

    quit = Gtk.MenuItem('Quit')
    quit.connect('activate', lambda _: Gtk.main_quit())

    menu = Gtk.Menu()
    menu.append(check)
    menu.append(quit)
    menu.show_all()
    return menu


def on_menuitem_check(item):
    print("active:", item.get_active())

if __name__ == '__main__':
    main()
```

But it's not a problem in AppIndicator, since the same problem occurs using **Qt/QSystemTrayIcon**:

```python
from PyQt5.QtWidgets import QAction, QApplication, QMenu, QSystemTrayIcon

import signal
import sys


def main():
    app = QApplication(sys.argv)
    style = app.style()
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    trayicon = QSystemTrayIcon(style.standardIcon(style.SP_MessageBoxCritical))
    trayicon.setVisible(True)
    trayicon.setContextMenu(build_menu(trayicon))
    trayicon.show()
    app.exec_()


def build_menu(parent, menu=None):
    check = QAction('CheckMenuItem', parent)
    check.setCheckable(True)
    check.triggered.connect(on_menuitem_check)

    quit = QAction('&Quit', parent)
    quit.setMenuRole(QAction.QuitRole)
    quit.triggered.connect(QApplication.quit)

    menu = menu or QMenu()
    menu.addAction(check)
    menu.addAction(quit)
    return menu


def on_menuitem_check(checked):
    print("active:", checked)


if __name__ == '__main__':
    main()
```

FWIW, I also checked that it isn't a problem in all menus: checkmenuitems in window menus are shown correctly, as can be verified by inserting the following in the qt main:

```python
    window = QMainWindow()
    build_menu(window, window.menuBar().addMenu('&File'))
    window.show()
```

So far I'm using successfully using an `ImageMenuItem` with checkbox icons as a workaround, but it would be nice if this were to be fixed upstream.

Same code works fine in my X session.

(Issue from https://github.com/coldfix/udiskie/issues/215)

Best, Thomas

**Comment by pocek** [comment]
This is because of:
```css
* {
    border: none;
    border-radius: 0;
    // ...
    min-height: 0;
}
```
in style.css.

**Comment by mvdan** [comment]
@pocek is absolutely right. I ended up moving those three lines to a section that only applies to the "workspaces" widget, as I imagine that's where it was intended to take effect.

**Comment by coldfix** [comment]
Cool! Will you create a PR with this changge @mvdan ?

**Comment by mvdan** [comment]
@coldfix @pocek see https://github.com/Alexays/Waybar/pull/1385 :)
