### ISSUE TITLE
Cannot get fontawesome icons to work

### ISSUE THREAD

**Issue by japhir** [Alexays/Waybar#115]
Most icons don't show, and some show up as weird curly characters. I've tried to add a `FontAwesome5Free` line to my [style](https://github.com/japhir/ArchConfigs/blob/master/waybarstyle), and I've played around with workspace names in my [sway config](https://github.com/japhir/ArchConfigs/blob/master/swayconfig) + [waybar config](https://github.com/japhir/ArchConfigs/blob/master/waybarconfig) but I cannot get it to work. I've also re-installed fontawesome, but to no avail.

**Comment by Alexays** [comment]
Did you install `otf-font-awesome`? the others seem to be bugging...

**Comment by japhir** [comment]
I installed otf-font-awesome, removed ttf-font-awesome, rebooted and also adjusted style.css, but it appears not to work. Are there any diagnostic commands I can run?

**Comment by japhir** [comment]
BTW, I'm not sure if it's reading my config correctly, since it still gives me a message `Disabling module "battery#bat2, No battery named BAT2` even though I omit the module from my config.

**Comment by Alexays** [comment]
For me it works with just in style.css `font-family style: Roboto, Helvetica, Arial, sans-serif;` and otf-font-awesome

**Comment by japhir** [comment]
With the latest update at least I'm certain it's loading my config (since when I launch it from terminal it tells me so, and it updates). I've managed to get some custom-module action going, but the fonts still don't work. They do work back home on my desktop, so I'll try to see if I can find what I've done differently there.

I guess this slightly relates to #107. Maybe the AUR package can list `otf-font-awesome` as an opt-depend?

**Comment by Alexays** [comment]
Added `otf-font-awesome` as a optdepend in the PKGBUILD

**Comment by alexthebuilder** [comment]
Just adding a comment since I ran into this as well. This was due to the font I was using. Certain Fonts override the font awesome fonts. To check if yours is one of those go to nerd fonts and see if there is a patched version for you. The font I used DejaVu Sans Mono needed to use a patched version for icons to show.

https://github.com/ryanoasis/nerd-fonts

**Comment by tmccombs** [comment]
Even with otf-font-awesome installed, I only get some of the icons. In particular the volume icons don't work. If I change the font family to "Font Awesome 5 Free" they work, but that seems less than desirable.

**Comment by tukusejssirs** [comment]
I had the very same problem and the way I fixed it is to _append_ `Font Awesome 5 Free` to the `font-family` in the `style.css`, like so:

```css
font-family: Ubuntu, "Font Awesome 5 Free";
```

**Comment by Scafir** [comment]
For the people like me using fedora, it seems that the font provided by the offical repos is incomplete. I had to download and manually install FontAwsome from the official [website](https://fontawesome.com/download), and then append `"Font Awesome 5 Free"` in `style.css`, as initially proposed by tukusejssirs.

**Comment by tukusejssirs** [comment]
@Scafir, I did it the same way as you did (also use Fedora), however, I can presumahly all icons, incl charging, volume and weather icons.

**Comment by Scafir** [comment]
> @Scafir, I did it the same way as you did (also use Fedora), however, I can presumahly all icons, incl charging, volume and weather icons.

@tukusejssirs Problem solved, it was because of a conflict between sans serif (in the default config) and fontawesome. I should have suspected it but this is definitely finicky.
