### ISSUE TITLE
[tray icon] icon not hidden when setting status to PASSIVE

### ISSUE THREAD

**Issue by coldfix** [Alexays/Waybar#1150]
Hi,

sway version: 1.6.1
waybar version: v0.9.7

according to the [docs](https://lazka.github.io/pgi-docs/#AyatanaAppIndicator3-0.1/enums.html#AyatanaAppIndicator3.IndicatorStatus) a tray icon should be hidden when setting it's status to `PASSIVE`. However that doesn't seem to be the case under sway/waybar.

Short example reproducing the issue:

```python
import signal

from gi import require_version
require_version('GLib', '2.0')
require_version('Gtk', '3.0')
require_version('AppIndicator3', '0.1')

from gi.repository import GLib
from gi.repository import Gtk
from gi.repository import AppIndicator3

ACTIVE = AppIndicator3.IndicatorStatus.ACTIVE
PASSIVE = AppIndicator3.IndicatorStatus.PASSIVE


def create_icon():
    indicator = AppIndicator3.Indicator.new(
        'myappindicator',
        'ICON-NOT-FOUND',
        AppIndicator3.IndicatorCategory.OTHER)
    menu = Gtk.Menu()
    item_quit = Gtk.MenuItem()
    item_quit.set_label('Quit')
    item_quit.connect('activate', Gtk.main_quit)
    menu.append(item_quit)
    menu.show_all()
    indicator.set_menu(menu)
    return indicator


def toggle_icon(icon):
    if icon.get_status() == ACTIVE:
        print("hide")
        icon.set_status(PASSIVE)
    else:
        print("show")
        icon.set_status(ACTIVE)
    return True


def main():
    icon = create_icon()
    GLib.timeout_add(1000, toggle_icon, icon)

    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Gtk.main()


if __name__ == '__main__':
    main()
```

For me, this regularly toggles the icon visibility in X, but permanently shows the icon in sway after first setting it to `ACTIVE`.

Again not sure, if this is an wayland/waybar/sway or even an AppIndicator problem.

(Issue from: https://github.com/coldfix/udiskie/issues/224)

Best, Thomas

**Comment by alebastr** [comment]
Thanks for the report and examples.

> Again not sure, if this is an wayland/waybar/sway or even an AppIndicator problem.

That's a waybar issue, handling of SNI item statuses is currently not implemented. I drafted the code over the weekend and will finish in a few more days.

**Comment by coldfix** [comment]
Awesome, many thanks for your work!
