### ISSUE TITLE
Configuration of multiple outputs fails

### ISSUE THREAD

**Issue by ian-s-mcb** [Alexays/Waybar#1152]
The configuration syntax for multiple outputs causes waybar to fail on start with a JSON related error.

The syntax is explained in [the wiki here][syntax-explanation]. Essentially, it says to put your config JS object into an array and use the `output` property as an output selector.

### Version
* My setup is: Linux kernel 5.12.9, sway 1.6-31b4b96e, and alacritty 0.8.0.
* I use the waybar-git AUR package. I get this error at the latest waybar commit (7c1303f), but not at a commit from last month (2016074). I hope that helps track down the culprit LOC.

### Error message
```bash
$ waybar --log-level trace
[2021-07-03 17:12:40.746] [info] Resources files: /home/ian/.config/waybar/config, /home/ian/.config/waybar/style.css
[2021-07-03 17:12:40.746] [error] in Json::Value::resolveReference(key, end): requires objectValue
```

### Steps to reproduce
1. Build waybar from source using the latest commit (7c1303f)
2. Save the following minimal config file. (I took it from [this example][minimal-config-example] in the wiki).
    ```js
    {
        "layer": "top",
        "modules-left": ["sway/workspaces", "sway/mode"],
        "modules-center": ["sway/window"],
        "modules-right": ["battery", "clock"],
        "sway/window": {
            "max-length": 50
        },
        "battery": {
            "format": "{capacity}% {icon}",
            "format-icons": ["", "", "", "", ""]
        },
        "clock": {
            "format-alt": "{:%a, %d. %b  %H:%M}"
        }
    }
    ```
2. Apply the syntax for multiple outputs, ie. put the JS object into an array. Realistically, a one element config array isn't an interesting example, but the next example shows that multiple config objects fail as well.
    ```js
    // ~/.config/waybar/config
    // Example-1
    [{
        "layer": "top",
        "modules-left": ["sway/workspaces", "sway/mode"],
        "modules-center": ["sway/window"],
        "modules-right": ["battery", "clock"],
        "sway/window": {
            "max-length": 50
        },
        "battery": {
            "format": "{capacity}% {icon}",
            "format-icons": ["", "", "", "", ""]
        },
        "clock": {
            "format-alt": "{:%a, %d. %b  %H:%M}"
        }
    }]
    ```
3. Restart waybar and startup will fail
4. Apply a more interesting multi-output config.
    ```js
    // ~/.config/waybar/config
    // Example-2
    [{
        "layer": "top",
        "output": "YOUR-OUTPUT-1",
        "modules-left": ["sway/workspaces", "sway/mode"],
        "modules-center": ["sway/window"],
        "modules-right": ["battery", "clock"],
        "sway/window": {
            "max-length": 50
        },
        "battery": {
            "format": "{capacity}% {icon}",
            "format-icons": ["", "", "", "", ""]
        },
        "clock": {
            "format-alt": "{:%a, %d. %b  %H:%M}"
        }
    },
    {
        "layer": "top",
        "output": "YOUR-OUTPUT-2",
        "modules-left": ["sway/workspaces", "sway/mode"],
        "modules-center": ["sway/window"],
        // NOTE: clock isn't shown on this output
        "modules-right": ["battery"],
        "sway/window": {
            "max-length": 50
        },
        "battery": {
            "format": "{capacity}% {icon}",
            "format-icons": ["", "", "", "", ""]
        }
    }]
    ```
5. Restart waybar and startup will fail

[syntax-explanation]: https://github.com/Alexays/Waybar/wiki/Configuration#configuration-of-multiple-outputs
[minimal-config-example]: https://github.com/Alexays/Waybar/wiki/Configuration#minimal-config

**Comment by Koffeinfriedhof** [comment]
Hi!
I have the same issue without a second monitor but with a configured second bar. Reverting the commit [https://github.com/Alexays/Waybar/commit/14f626d422a77b51bca4bbbe5282ee6e995169e0](url) „fixes“ the issue.

I do not know enough to fix this correctly, so I just commented the new lines and inserted config_ = parser.parse(str); again.

**Comment by ian-s-mcb** [comment]
@Koffeinfriedhof Good to know. The commit you reverted falls within the range of commits that caused my issue with multiple outputs. Seems like PR #995, which introduced that commit, is problematic.

**Comment by colemickens** [comment]
Is it worth reverting? I'm debating pinning `waybar` to a known-good version in `nixpkgs-wayland` until this is resolved, otherwise.

**Comment by Koffeinfriedhof** [comment]
> Is it worth reverting?
Well, as waybar does not start with my config I had no choice then removing the mentioned lines. I think there are some checks missing, something like tmp_config_["include"].exists(), but there is no such method. As I do not know how to use this json-stuff and don't have appropriate config files to test, I'll just wait for it to be fixed.

**Comment by Artturin** [comment]
Reproducible with 
```
[
{
    "layer": "top",
    "position": "bottom",
    "height": 23,
}, {
    "layer": "top",
     "position": "bottom",
     "height": 25,
}
]
```

**Comment by colemickens** [comment]
I'm going to start patching nixpkgs-wayland's build with this fix, it's been broken too long: https://github.com/nix-community/nixpkgs-wayland/commit/f5a5560cd23217851736e1dfca13c1a6844ce228
