### ISSUE TITLE
Add swap to memory module

### ISSUE THREAD

**Issue by mredaelli** [Alexays/Waybar#1156]
I just moved over from `i3status-rs` and love `waybar`.

The one thing I miss is out-of-the-box swap support along with RAM stats. With memory-hungry stuff I'm used now to keep an eye on the free sway. I can certainly make a simple custom module, but since the infrastructure if all there (at least for linux. No idea about BSD), I think it might be a nice addition.

**Comment by Anakael** [comment]
So, you want to see swap usage separately, don't you?

**Comment by mredaelli** [comment]
Yep.

Though, what do you mean, "separately"? Is it now included in something? A search for "swap" in the wiki doesn't give results

**Comment by Anakael** [comment]
I asked whether it should be calculated as a part of RAM on not.
I think I can add in memory module the same options as now for RAM. E.g `swap-available`.

**Comment by mredaelli** [comment]
That would be great!
--

M.


10 Aug 2021 10:20:05 Anakael ***@***.***>:

**Comment by Anakael** [comment]
Can you check https://github.com/Anakael/Waybar/tree/pr/anakael/add-swap-flags ?
If it works fine, I'll open PR.

**Comment by asas1asas200** [comment]
@Anakael I have tried it in my machine, it looks well, can you merge it into mainilne?

Thanks.

**Comment by lockywolf** [comment]
Could an icon for swap be added as well?
In my build, I am just doing it like this:

```
sed -i 's/fmt::arg("icon", getIcon(used_ram_percentage, icons)),/fmt::arg("icon", getIcon(used_ram_percentage, icons)), fmt::arg("iconswap", getIcon(used_swap_percentage, icons)),/g' src/modules/memory/common.cpp
```
