### ISSUE TITLE
XDG_CONFIG_HOME should be assumed if not set

### ISSUE THREAD

**Issue by ainola** [Alexays/Waybar#116]
Currently waybar moves on to other configuration locations if $XDG_CONFIG_HOME is not set. Per the spec:

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Thanks!

**Comment by Alexays** [comment]
Done in 2ec34e4adb6190543111b91134e72f3ab8eed298
