### ISSUE TITLE
Question about waybar with multiple monitors

### ISSUE THREAD

**Issue by Hydranet** [Alexays/Waybar#1164]
First of all, thank you for waybar!!! I do have a question not an an issue. Currently Waybar automatically loads a bar on each of my monitors, is it possible to only have one bar load on my main monitor instead one on both of my monitors?

**Comment by keith24** [comment]
For anyone looking, use the `"output"` key in your config.  Not documented yet but there's some sample code here: https://github.com/Alexays/Waybar/issues/147#issuecomment-459863670
