### ISSUE TITLE
Waybar not working after last update 

### ISSUE THREAD

**Issue by moghaazi** [Alexays/Waybar#1166]
After I updated Waybar version 0.9.7-2, it didn't appear.. I tried to type waybar in the terminal it's showing me this message

`waybar: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory`

then I tried to install **fmt** it's showing me this message

```
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing fmt (8.0.0-2) breaks dependency 'libfmt.so=7-64' required by spdlog
```

then I tried to build it form the source, It's worked after I typed `./build/waybar` but it's showing me this message, and **waybar** disappear after I close the terminal

```
[2021-07-18 03:00:24.065] [info] Resources files: /home/moghaazi/.config/waybar/config, /home/moghaazi/.config/waybar/style.css
[2021-07-18 03:00:24.099] [warning] module backlight: Disabling module "backlight", No backlight found
[2021-07-18 03:00:24.101] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[2021-07-18 03:00:24.102] [error] media stopped unexpectedly, is it endless?

** (waybar:5321): WARNING **: 03:00:24.147: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
[2021-07-18 03:00:24.267] [info] Bar configured (width: 1024, height: 18) for output: VGA-1
```

**Comment by Kommynct** [comment]
https://github.com/Alexays/Waybar/pull/1144 

already fixed here, just waiting until next release

For now use waybar-git from the AUR

**Comment by moghaazi** [comment]
> #1144
> 
> already fixed here, just waiting until next release
> 
> For now use waybar-git from the AUR, assuming you're on arch.

Yes, I'm using Arch, I removed **waybar** and downloaded **waybar-git** and reloaded my **swaywm** with **alt+shift+c** it's working now

**Comment by Kommynct** [comment]
Might wanna leave this open until the next release as I imagine there's gonna be a flood of these reports.

**Comment by moghaazi** [comment]
> Might wanna leave this open until the next release as I imagine there's gonna be a flood of these reports.

Ok, I'll leave it open

**Comment by Kommynct** [comment]
Fixed for me on arch.
