### ISSUE TITLE
Bar hangs if interval on clock <60

### ISSUE THREAD

**Issue by Robinhuett** [Alexays/Waybar#118]
If I set the interval on clock to 20 for example, the complete bar freezes for a good amount of time.

Is there a reason why the clock module sets the interval like this:
https://github.com/Alexays/Waybar/blob/2ec34e4adb6190543111b91134e72f3ab8eed298/src/modules/clock.cpp#L8-L14

Why not set the interval like on the other modules with:
```
dp.emit();
thread_.sleep_for(interval_);
```

I can make a PR for this if you like.

**Comment by Alexays** [comment]
Because if we launch the bar at 18h32 and 50 seconds with an interval of 60 it will be updated at 18h33 and 50 seconds so there is always a delay and we are not on time, I look at it tomorrow

**Comment by Alexays** [comment]
Fixed in 7befd2705915f980e8e74e99a2846639f29d6605
