### ISSUE TITLE
Glyphs truncated with Cascadia Code font

### ISSUE THREAD

**Issue by mnussbaum** [Alexays/Waybar#1185]
I've noticed that certain wide glyphs appear to be truncated when rendered using the [Cascadia Code font](https://github.com/microsoft/cascadia-code). Specifically I've noticed the   and  glyphs are truncated, while something like  isn't. I've tried adding text after the glyphs and the text renders fully, so I believe something about the width of the characters triggers the issue.

Here's a screen shot with correctly rendered text after the truncation to demonstrate the problem:

![truncated-batter-icon](https://user-images.githubusercontent.com/473482/127396268-70f2fed4-4fed-4b5e-ade2-2de925eac197.png)

Happy to provide any more detail or testing! I'm running waybar `v0.9.7` and cascadia code version `2106.17`.

**Comment by flipflop133** [comment]
I think this may solve your issue:
https://github.com/ryanoasis/nerd-fonts/issues/442
If yes, please close the issue as it doesn't seems related to waybar itself.

**Comment by mnussbaum** [comment]
Adding the trailing invisible character suggested in https://github.com/ryanoasis/nerd-fonts/issues/442#issuecomment-894028647 does fix the issue, thanks!
