### ISSUE TITLE
[Feature Request] Change tag on click functionality with river/tags

### ISSUE THREAD

**Issue by antaxiom** [Alexays/Waybar#1189]
More or less self explanatory, I'd like to be able to click on a tag and then be sent to the tag, at the moment they tag functionality is purely visual and does not provide any functionality. I'm unsure how difficult it would be to implement, but I am interested and could put in some work if needed.

**Comment by AtifChy** [comment]
I also need this feature.

**Comment by AtifChy** [comment]
@Alexays river uses this command ```riverctl set-focused-tags $((1 << ($i - 1)))``` to change tags. This command can be used for changing for tags on click.

**Comment by antaxiom** [comment]
Yep, all I need is the actual functionality to implement it, even just on "on-cilck" for each tag button would suffice for now. Obviously a full implementation that just runs the command for each tag would be ideal.

**Comment by charlie39** [comment]
I am struggling to configure river/tags . Can I have a look at your config?

**Comment by charlie39** [comment]
You can try this 
https://codeberg.org/dnkl/yambar/src/branch/master/examples/scripts/dwl-tags.sh
