### ISSUE TITLE
Separate styles for multiple instances of a module

### ISSUE THREAD

**Issue by ian-s-mcb** [Alexays/Waybar#119]
Is it possible to specify separate styles for multiple instances of a module?

I ask because I have two modules `network#wireless` and `network#wired` and I want the CSS selector `network#disconnected` to applied to the first module but not the second one.

**Comment by Alexays** [comment]
Done in b554094c7e7d47415f91f11cec5976b5d05b9ada
In your css file you can do something like this:
```css
#network.wireless {
	...
}
#network.wired {
	...
}

**Comment by Perodactyl** [comment]
Please rename this issue because I'm trying to find answers for its original title and this doesn't help.
