### ISSUE TITLE
Monitoring a removable battery (Surface book / other detachables)

### ISSUE THREAD

**Issue by tmarkov** [Alexays/Waybar#1193]
I have a Surface Book - a detachable with two batteries. One battery is in the tablet part, the other - in the keyboard. So I have two battery modules monitoring them. However, when I detach the tablet part, only one battery is left, and so Waybar crashes with

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No battery named BAT2
fish: Job 1, 'waybar' terminated by signal SIGABRT (Abort)
```

Is there a way to manage a battery that can appear or disappear?

Here's my battery config:

```
    "battery": {
        "states": {
            // "good": 95,
            "warning": 30,
            "critical": 15
        },
        "format": "{capacity}% {icon}",
        "format-charging": "{capacity}% ",
        "format-plugged": "{capacity}% ",
        "format-alt": "{time} {icon}",
        // "format-good": "", // An empty format will hide the module
        // "format-full": "",
        "format-icons": ["", "", "", "", ""]
    },
    "battery#bat2": {
        "bat": "BAT2"
    },
```

**Comment by bhartshorn** [comment]
Same problem with a Thinkpad with both internal and external batteries.

**Comment by LukashonakV** [comment]
Fixed: https://github.com/Alexays/Waybar/pull/1481

**Comment by glow12121** [comment]
Did you solve the issue? I have two batteries on x240 but only one shows up.

**Comment by glow12121** [comment]
> Same problem with a Thinkpad with both internal and external batteries.

Did you solve the issue? I have two batteries on x240 but only one shows up.

**Comment by tmarkov** [comment]
This issue was about Waybar crashing, not about two only one battery showing up. Closing since it's marked as fixed.
