### ISSUE TITLE
Calendar in clock module always starts on sunday 

### ISSUE THREAD

**Issue by michaeljaeger95** [Alexays/Waybar#1195]
I can't see any way to change the start of week, like when invoking `cal -m` from terminal. Adding `LC_TIME="de_DE.UTF-8"` to `/etc/locale.conf` doesn't seem to have any effect.

**Comment by Anakael** [comment]
It can be achived that way:
Set in waybar config `timezone` and `locale` options. Also, desired locale should be generated by uncommenting in `/etc/locale.gen` and should be generated by `sudo locale-gen`.

**Comment by michaeljaeger95** [comment]
Thanks @Anakael, that solved it. 

Strangely, it doesn't seem to respect system locale. Maybe this can be fixed at some point, so I'll leave this issue open (feel free to close if you disagree). I think this deserves the "good first issue"-label.

In the meantime I've added a hint to the troubleshooting section of the relevant wiki page.

**Comment by LukashonakV** [comment]
Hi @michaeljaeger95 please close the issue if it's not relevant more
