### ISSUE TITLE
Setting max-length on a custom module replaces entire module text with "..."

### ISSUE THREAD

**Issue by Hubro** [Alexays/Waybar#1199]
I have a couple of custom modules that uses `mediaplayer.py`:

```javascript
"custom/spotify": {
    "exec": "/usr/bin/python3 /home/hubro/Dropbox/Config/waybar/custom_modules/mediaplayer.py --player spotify",
    "format": "{}  ",
    "return-type": "json",
    "on-click": "playerctl -p spotify play-pause",
    "on-click-middle": "killall -KILL /opt/spotify/spotify",
    "on-scroll-up": "playerctl -p spotify next",
    "on-scroll-down": "playerctl -p spotify previous"
},
"custom/chromium": {
    "exec": "/usr/bin/python3 /home/hubro/Dropbox/Config/waybar/custom_modules/mediaplayer.py --player chromium",
    "format": "{}  ",
    "return-type": "json",
    "on-click": "playerctl -p chromium play-pause"
},
```

This works great:

![image](https://user-images.githubusercontent.com/597206/128637667-0b3671db-1348-4926-802d-2c89f35929ac.png)

Although Youtube video titles tend to be quite wordy, so I want to limit the text length. However, if I add `max-length` to the custom modules:

```javascript
"custom/spotify": {
    "exec": "/usr/bin/python3 /home/hubro/Dropbox/Config/waybar/custom_modules/mediaplayer.py --player spotify",
    "format": "{}  ",
    "max-length": 30,
    "return-type": "json",
    "on-click": "playerctl -p spotify play-pause",
    "on-click-middle": "killall -KILL /opt/spotify/spotify",
    "on-scroll-up": "playerctl -p spotify next",
    "on-scroll-down": "playerctl -p spotify previous"
},
"custom/chromium": {
    "exec": "/usr/bin/python3 /home/hubro/Dropbox/Config/waybar/custom_modules/mediaplayer.py --player chromium",
    "format": "{}  ",
    "max-length": 30,
    "return-type": "json",
    "on-click": "playerctl -p chromium play-pause"
},
```

Then the text of both modules are completely replaced with "...":

![image](https://user-images.githubusercontent.com/597206/128637691-d0a52d0d-0223-4760-9cc4-a18fc7a9b9fb.png)

Am I doing something wrong, or is this a bug?

```
➜ pacman -Q | grep waybar
waybar 0.9.7-1
```

**Comment by RRRadicalEdward** [comment]
Have the same

**Comment by RRRadicalEdward** [comment]
I have replaced `python3 ~/.config/waybar/custom_modules/mediaplayer.py --player spotify"` to
` "exec": "python3 ~/.config/waybar/mediaplayer.py 2> /dev/null",` and `max-length` started to work.

**Comment by Hubro** [comment]
I'm still having this exact problem with Waybar v0.9.9. On my laptop, the media module for youtube is taking up a third of the width of the monitor, and I can't limit the width without the entire module text being replaced with `...`.

**Comment by amarshall** [comment]
This appears to happen when the edge of modules-left or modules-right would go over the center of the bar, even if there are no center modules. Setting `fixed-center` to `false` in the top-level config makes the (empty) center less sticky, allowing the left or right side to expand over it when a module has max-length set.

**Comment by Hubro** [comment]
@amarshall That definitely wasn't the problem for me, as this also happened on my 5120x1440 desktop monitor, even when modules-right was miles away from the center modules.

However, your comment just prompted me to try again, since it's been a long time since I posted this issue, and apparently this has been fixed now! :smile: :tada: 

![image](https://user-images.githubusercontent.com/597206/175406175-97e076ba-f2cd-40f8-8fd2-519ed6bcb0dc.png)

**Comment by BBaoVanC** [comment]
I'm getting this issue -- I have max-length set on a right-aligned module, but when the center module (window title) becomes too large then it turns the right-aligned module into just `...`

**Comment by danilo-alm** [comment]
Still no fix. So for those who aren't programmers: if you want to have the script limit the characters so you don't have to set max-length, find where the text is sent to stdout and add this (python):

e.g. for mediaplayer.py, limiting output to 30 chars
```python
def write_output(self, text, player):  # this function already exists...
    if len(text) > 30:
        text = text[:30] + "..."
```

Not really a fix but meh I wanted to use the module
