### ISSUE TITLE
Strange config error

### ISSUE THREAD

**Issue by Crandel** [Alexays/Waybar#1200]
I use waybar 0.9.7 with swaywm on arch linux, my config works very well. On my work I need to install Ubuntu, so I use ppa from readme, but with the same config I have this errors
```bash
$ waybar
[2021-08-09 09:24:14.205] [info] Resources files: /home/crandel/.config/waybar/config, /home/crandel/.config/waybar/style.css
[2021-08-09 09:24:14.205] [error] * Line 94, Column 5
  Missing '}' or object member name
```

I basically copy all fonts from arch to ubuntu, so the problem is not in the fonts
```bash
$ fc-list | rg -i hack
...
/usr/share/fonts/TTF/Hack-Regular-Nerd-Font-Complete-Mono.ttf: Hack Nerd Font Mono:style=Regular
...
```
[config](https://github.com/Crandel/home/blob/master/.config/waybar/config), [style.css](https://github.com/Crandel/home/blob/master/.config/waybar/style.css)

**Comment by pinselimo** [comment]
That's probably the json parser expecting an object after the comma in line 93 of your config.

~~~
93        },
94    },
~~~

Remove the comma and also all other commas that are directly followed by a ```}```.
(That would be line 93, 101, 104, 119, 152, 160, 168 and 178 .. and maybe one I've missed now :)

**Comment by Crandel** [comment]
Thanks, now it works. I'm curious how it works with comma on arch?

**Comment by pinselimo** [comment]
[Seems like](https://github.com/open-source-parsers/jsoncpp/pull/1098) support for trailing commas was added in ```libjsoncpp``` version ```1.9.3```. So I guess Waybar on Ubuntu uses a version prior to that.

**Comment by Crandel** [comment]
Thanks for explanation @pinselimo. Now everything make sense for me.
