### ISSUE TITLE
sway/language: Add ability to display shortDescription of the layout

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#1208]
I pondered over the file `/usr/share/X11/xkb/rules/xorg.xml`, which contains metainfo for all the keyboard layouts.

Each layout has a `name` property, which corresponds to the layout file in the `/usr/share/X11/xkb/symbols` directory and in the language module it's displayed with format `{short}`.   
Example: **us**.

Also each layout has a `description` property, which is displayed with format `{long}`.   
Example: **English (US)**.

Also some layouts have several variants, if one of them is selected, it is displayed with format `{variant}`.  
Example:  **dvorak**.

But also each layout has a `shortDescription` property, which is a short tag, abbreviated from the layout's language name. Sometimes it is the same as the `name`, such as in the **ru** layout. But sometimes it's different. For example the **us** layout has **en** `shortDescription`, because the language is English. I would prefer to see the `shortDescription` value in the panel, but there is no way to display it with this module right now.

I don't know if it's possible without parsing that XML file though.

Also, it would be great to have the ability to uppercase the displayed text.

@Anakael, you've been very responsive to the requests about this module before. Could you please see if anything can be done about this?

**Comment by Anakael** [comment]
1) I've open PR for shortDescription support..
2) About uppercase: fmt library doesn't have native uppercase (https://fmt.dev/latest/syntax.html). So, it's require to add uppercase option for each of them and I'm not sure if this a good idea.

**Comment by eternal-sorrow** [comment]
> it's require to add uppercase option for each of them

Or just  one single config option to uppercase the module label text. But yeah, that's a crutch...

**Comment by Alexays** [comment]
> > it's require to add uppercase option for each of them
> 
> Or just one single config option to uppercase the module label text. But yeah, that's a crutch...

You can try to uppercase with css too
Closing as @Anakael PR is merged

**Comment by eternal-sorrow** [comment]
> You can try to uppercase with css too

I just tried and got this:
```
[error] style.css:73:15'text-transform' is not a valid property name
```

**Comment by nacknime-official** [comment]
> > You can try to uppercase with css too
> 
> I just tried and got this:
> 
> ```
> [error] style.css:73:15'text-transform' is not a valid property name
> ```

The same thing.
Before the last update the letters of the widget were in uppercase. After update - lowercase.

**Comment by eternal-sorrow** [comment]
Yep, GTK doesn't support it yet. But I stirred some movement to that direction in the GTK gitlab issues: https://gitlab.gnome.org/GNOME/gtk/-/issues/505

They even merged the required feature on pango side: https://gitlab.gnome.org/GNOME/pango/-/merge_requests/421

**Comment by nacknime-official** [comment]
> Yep, GTK doesn't support it yet. But I stirred some movement to that direction in the GTK gitlab issues: https://gitlab.gnome.org/GNOME/gtk/-/issues/505
> 
> They even merged the required feature on pango side: https://gitlab.gnome.org/GNOME/pango/-/merge_requests/421

Good job! I keep calm and wait ;)
