### ISSUE TITLE
Endless custom module keeps running after the bar dies

### ISSUE THREAD

**Issue by jeremejevs** [Alexays/Waybar#121]
During my experiments in #120 I've noticed that my custom Bash script doesn't get killed when the bar dies, and just keeps complaining about a broken pipe. Adding `set -o errexit` is an easy fix, but it would be better if the children would get auto-killed too. [One potential solution.](https://stackoverflow.com/a/4054436/242684)

**Comment by Alexays** [comment]
Damn, i forgot this :/, fixed in 1b13f9e38cde45a82bc8899921f4f55954a16a67

**Comment by jeremejevs** [comment]
I don't think `1b13f9e` addresses this issue. Even a simple `pkill waybar` leaves the script running.

**Comment by Alexays** [comment]
Ok got it you mean when waybar stop unexpectedly.

**Comment by jeremejevs** [comment]
Yep, sorry, should've been explicit about it, instead of referencing #120 :slightly_smiling_face:

**Comment by Alexays** [comment]
Fixed with 90d89fe9742fec690677fc6965d28b25df8fc14f

**Comment by Gigadoc2** [comment]
It seems that if waybar is killed with a SIGTERM, the custom scripts still keep running.

**Comment by ErikReider** [comment]
Doesn't seem to work when piping though. Here's a simple example:

swaync-client.sh
```bash
while read -r line; do
    echo "test"
done < <(swaync-client -s)
```

```json
"custom/notification": {
  "interval": "once",
  "return-type": "text",
  "exec": "swaync-client.sh"
},
```

Before killing Waybar:
![image](https://user-images.githubusercontent.com/35975961/148851730-603d7846-0a33-4d20-8996-505f63a0ff14.png)

After killing Waybar:
![image](https://user-images.githubusercontent.com/35975961/148851813-aa8b85a6-680a-4244-a703-75534d4c4228.png)

It seems like it kills the initial process but not the loop and `swaync-client`?

Note: I've got Waybar open on two monitors so it execs double the amount of scripts

**Comment by L11R** [comment]
@ErikReider did you find the way to fix it? I use own script https://github.com/L11R/waybar-updates and keep getting processes multiplied everytime I restart waybar. Already got temporary banned by Aurweb (429)...

**Comment by ErikReider** [comment]
> @ErikReider did you find the way to fix it? I use own script [L11R/waybar-updates](https://github.com/L11R/waybar-updates) and keep getting processes multiplied everytime I restart waybar. Already got temporary banned by Aurweb (429)...

I've just integrated waybar support into my binaries 😅
