### ISSUE TITLE
Tray icon size in 0.9.8 on external non-HiDPI monitor

### ISSUE THREAD

**Issue by roper79** [Alexays/Waybar#1212]
Hi, since the 0.9.8 update, some icons in the tray on an external non-HiDPI monitor are bigger. The built-in display is HiDPI and they are ok.
![2021-08-17_18-08-1629216261](https://user-images.githubusercontent.com/4477111/129761270-7b7c54b6-8783-420c-9be3-2f717f3744f2.png)

**Comment by helloworld1** [comment]
I have HiDPI display but with scale = 2. Some icons like udiskie are much bigger than some other icons.

**Comment by Alexays** [comment]
Hi, can you try if #1211 is fixing your issue? :)

**Comment by Alexays** [comment]
Closing as #1211 merged!
