### ISSUE TITLE
Clock module: Scrolling timezones doesn't seem to work

### ISSUE THREAD

**Issue by rinpatch** [Alexays/Waybar#1214]
According to the [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Clock):
> timezones - A list of timezones (as in timezone) to use for time display, changed using the scroll wheel.

I am running Waybar 0.9.8 on sway 1.6.1 and I have trouble getting that to work. Scrolling on the clock does nothing. Scrolling on other modules like pulseaudio seems to work. I would appreciate some help with figuring out what's wrong with my config.

My waybar config:
```
{
    "layer": "top",
    "modules-left": ["sway/workspaces", "sway/mode", "sway/language"],
    "modules-right": ["pulseaudio", "clock", "tray"],
    "clock": {
        "format": "{:%F %H:%M %Z}",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "timezones": ["America/New_York", "Europe/Moscow", "Asia/Vladivostok"]
    },
    "tray": {
      "icon-size": 20,
      "spacing": 3
    },
    "pulseaudio": {
      "format": "{volume}% {icon}",
      "format-bluetooth": "{volume}% {icon}",
      "format-muted": "",
      "format-icons": {
          "headphone": "",
          "hands-free": "",
          "headset": "",
          "phone": "",
          "portable": "",
          "car": "",
          "default": ["", ""]
      },
      "scroll-step": 1,
      "on-click": "pavucontrol"
    },
    "height": 24
}
```

**Comment by evyatark2** [comment]
I think #1417 should fix this

**Comment by LukashonakV** [comment]
Hi @rinpatch can you provide update there? If it's not relevant more please close the issue

**Comment by LukashonakV** [comment]
Hi @rinpatch , up

**Comment by LukashonakV** [comment]
Hi @rinpatch , up)

**Comment by Quist0n** [comment]
You need to add an "actions" section like 
```json
"clock": {
   // your other clock stuff here, 
  "actions": {
     "on-scroll-down": "tz_up",
     "on-scroll-down": "tz_down",
  },
}
```
I had a similar issue but I figured it out via going to this part of the [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Clock#actions)

I suggest that you use ``on-middle-click`` instead of ``on-scroll-up/down`` if you use a touchpad since it will be user to do one discrete click versus a swipe which will likely scroll several entries at once.

**Comment by rinpatch** [comment]
Sorry for inactivity, it has indeed been resolved.
