### ISSUE TITLE
Unable to adjust Waybar height

### ISSUE THREAD

**Issue by WilliamBehrens** [Alexays/Waybar#1218]
my config is located correctly in ~/.config/waybar/config

config: 
```
  1 {
  2     "height": 10,
  3     "position": "top",
  4     "modules-left": ["sway/workspaces", "sway/mode"],
  5 }
```
I'm just launching it using the `waybar` command and the output is
```
[2021-08-21 15:29:41.963] [info] Resources files: /home/will/.config/waybar/config, /home/will/.config/waybar/style.css

** (waybar:24950): WARNING **: 15:29:41.974: gtk-layer-shell v0.6.0 may not work on GTK v3.24.29. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

(waybar:24950): GLib-GObject-WARNING **: 15:29:41.975: ../gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '73'

(waybar:24950): GLib-GObject-WARNING **: 15:29:41.975: ../gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '72'
[2021-08-21 15:29:41.977] [warning] Requested height: 10 exceeds the minimum height: 73 required by the modules
[2021-08-21 15:29:41.977] [info] Bar configured (width: 1440, height: 73) for output: DP-3
[2021-08-21 15:29:41.977] [warning] Requested height: 10 exceeds the minimum height: 73 required by the modules
[2021-08-21 15:29:41.977] [info] Bar configured (width: 2560, height: 73) for output: DP-2
```
I'm running Sway on Void Linux(glibc, all up to date)

![scrn-2021-08-21-15-33-40](https://user-images.githubusercontent.com/35979547/130334155-a6ad6d25-2a43-40a5-b81b-13125ce9a55b.png)

**Comment by flipflop133** [comment]
As stated in your logs:
`Requested height: 10 exceeds the minimum height: 73 required by the modules`
This is the intended behavior, to keep a correct ratio for the modules.
If you want to really set your bar to an height of 10, you need to set the font size to something smaller in "style.css", something like so should work:
```
/* GENERAL */
* {
  font-family: Roboto, JetBrainsMono Nerd Font;
  font-size: 9px;
  border: none;
  border-radius: 0;
  min-height: 0;
}
```

**Comment by WilliamBehrens** [comment]
thank you, that worked

**Comment by Subhashis2007** [comment]
Still not fixed? mine giving same error, so I set waybar to be spawn with Minwaita theme and it worked for a while but now after sometime it is again 45

**Comment by Jimmytalksalot** [comment]
ur font size controls ur height. use px instead of percentage though
