### ISSUE TITLE
Allow users to disable reverse scrolling in pulseaudio module

### ISSUE THREAD

**Issue by lewisbolaton** [Alexays/Waybar#1220]
When using a touchpad with natural (reverse) scrolling enabled via libinput, volume adjustment behavior by scrolling on the pulseaudio module also gets reversed. In other words, scrolling up decreases the volume while scrolling down increases it.

**Comment by mrusme** [comment]
I'd like to see this as well. When you use natural scrolling for the mouse wheel, the same thing happens. It would be nice to have a flag that would allow for scrolling to be inverse.

**Comment by aashu** [comment]
I use `on-scroll-up` & `on-scroll-down` flags for doing this, though I agree it would be great if they provide a flag to disable reverse scrolling.
for now, u can do like this in pulseaudio module section:
`"on-scroll-up": "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 -1%"`
`"on-scroll-down": "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 +1%"`
