### ISSUE TITLE
Workspaces with wayfire

### ISSUE THREAD

**Issue by aalhitennf** [Alexays/Waybar#1225]
I'm unable to get workspaces working with wayfire, is it supported? I currently have values from default config:

    "modules-left": [
        "sway/workspaces"
    ],
    "sway/workspaces": {
        "disable-scroll": true,
        "all-outputs": true,
        "format": "{name}: {icon}",
        "format-icons": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "5": "",
            "urgent": "",
            "focused": "",
            "default": ""
    },

Waybar version 0.9.8, wayfire 0.7.2

**Comment by Anakael** [comment]
No, `sway/workspaces` works only with `sway`.

**Comment by LinArcX** [comment]
Is there any plan to support wayfire?

**Comment by Anakael** [comment]
`sway/workspaces` will work only with sway.
https://github.com/Alexays/Waybar/wiki/Module:-Workspaces will support once original protocol merged and implemented in wayfire.

**Comment by Mehdi-YC** [comment]
Hi, is this available now ?
