### ISSUE TITLE
Clock module doesn't handle manually setting time

### ISSUE THREAD

**Issue by flipflop133** [Alexays/Waybar#1226]
If we manually change the time in linux, the module crash and displays the same time forever, for example by using the following command:
`sudo date +%T -s 4:10:15`
My config:
```
"clock": {
		"interval": 5,
		"format": "{:%I:%M %p}"
},
```

**Comment by ChrisLane** [comment]
I've just come across this while testing some other time-based software.
Specifically, the clock module will get stuck if the time is set behind the currently displayed date/time but will continue to work if the clock is set after the currently displayed date/time.

**Comment by RobertMueller2** [comment]
I'm observing this with a laptop that's dual booting Windows and Debian. I never adjusted the behaviour on Windows (although I fully intend to now that I've understood the problem), so the laptop's RTC is set to local time (CET). Systemd eventually adjusts the time.

But I think that systemd's time adjustment races with my login attempt in the morning, and then sometimes the clock can get stuck for a while.

If I had to guess, the reason might be the thread_.sleep_until function used in both modules/simpleclock.cpp and modules/clock.cpp. Other modules use sleep_for instead, perhaps that is an idea for a workaround.

If I'm reading this https://en.cppreference.com/w/cpp/thread/sleep_until correctly (but I'm not much of a C++ guy and most of this goes way over my head anyway :P ), the behaviour of the function could vary depending on libstdc++ implementation.
