### ISSUE TITLE
Battery Percentage is half of actual percent

### ISSUE THREAD

**Issue by Weasnerb** [Alexays/Waybar#126]
I am having an issue where the batter percentage displayed in the waybar is exactly half (with rounding of decimal) of the percentage of what is in my /sys/class/power_supply/BAT0/capacity file. 

I did go though the other folders in the /sys/class/power_supply to see if waybar may be grabbing the wrong information, however I did confirm that this is the only one that is consistently correlated with the information displayed.

**Comment by Alexays** [comment]
However you can set in your configuration file "bat" to "BAT0" because it seem to be a special case for you, can you give me the content of the "uevent" file of your Wacom battery there may be an info :)

**Comment by Weasnerb** [comment]
Ohhh, ok. I just totally misread the docs. Thank you very much for the help and  for making this project!

**Comment by yoyou446** [comment]
This has happened to me as well on the the HP Spectre x360 13xxxx
It would assume that this will be a miss configuration for any laptop with phantom devices and will stop Waybar from working out of the box.

**Comment by tomalexander** [comment]
This also happened to me on my pixelbook
