### ISSUE TITLE
[warning] module clock: Unknown module: clock

### ISSUE THREAD

**Issue by wizard-28** [Alexays/Waybar#1262]
I updated to waybar version `0.9.5`, and my config broke (clock module). it's no longer displayed.

I ran waybar with the default config and saw this in the logs
```log
[2021-09-24 11:04:50.589] [warning] module clock: Unknown module: clock
```

Any fix for this?

**Comment by aarongable** [comment]
This is the same as #977, which is the result of the decision in #668 to drop support for the "clock" module from the Debian package until it can be included without a dependency on hhdate.

I don't agree with this decision -- seems like not having a clock is going to hinder adoption a lot more than having a dependency on a common package -- but that's how it is.

**Comment by LukashonakV** [comment]
Hi @wizard-28 , @danielytics , @aarongable , Please check [Clock WIKI](https://github.com/Alexays/Waybar/wiki/Module:-Clock). There is a description about Clock implementation.
@wizard-28  can you close the issue as it doesn't related directly to the waybar itself.
Thank you
