### ISSUE TITLE
BLuetooth module not showing up

### ISSUE THREAD

**Issue by Iss-in** [Alexays/Waybar#1270]
Using Bluetooth module with default setting, but its not showing anything on waybar, like it dont even exist. nothing in debug logs either

**Comment by Iss-in** [comment]
git version from aur, maybe thats the issue

**Comment by cristobaltapia** [comment]
Yes, that is the issue. Modify the `PKGBUILD` to include `--auto-features=enabled`. You can look at the `PKGBUILD` of the repository version [here](https://github.com/archlinux/svntogit-community/blob/packages/waybar/trunk/PKGBUILD).
