### ISSUE TITLE
Unable to Launch Waybar with river/tags in config

### ISSUE THREAD

**Issue by Notezi** [Alexays/Waybar#1280]
When i launch Waybar I am greeted with an error message : 

- river_status_manager_v1 not advertised
[text.txt](https://github.com/Alexays/Waybar/files/7311639/text.txt)

**Comment by erikrodrgz** [comment]
I reproduce it.

**Comment by charlie39** [comment]
Same issue with river compositer. I get this error: 

```Gdk-Message: 01:18:19.157: Error 88 (Socket operation on non-socket) dispatching to Wayland display.```

**Comment by charlie39** [comment]
@Alexays what could be the issue here ? ``` Socket operation on non socket``` 
this looks related to gtk layer shell ?  Is this on part of river compositor , gtk layer shell or waybar ?

**Comment by charlie39** [comment]
But when I click on the pulseaudio module if does open the the pavucontrol tool in a new window . So I am thinking gtk layer shell is fine. The problem may be on river not opening a socket that waybar is expecting or waybar is looking in the wrong location. 
I want to look into the issue just need some direction

**Comment by AbhishekDarshi** [comment]
Even I am facing the same issue.
```
** (waybar:9986): WARNING **: 18:57:44.100: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

(waybar:9986): GLib-GObject-WARNING **: 18:57:44.100: ../glib/gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '73'

(waybar:9986): GLib-GObject-WARNING **: 18:57:44.100: ../glib/gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '72'
[2021-11-02 18:57:44.100] [error] river_status_manager_v1 not advertised
Gdk-Message: 18:57:44.103: Error 88 (Socket operation on non-socket) dispatching to Wayland display.
```

**Comment by charlie39** [comment]
> Even I am facing the same issue.
> 
> ```
> ** (waybar:9986): WARNING **: 18:57:44.100: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
> 
> (waybar:9986): GLib-GObject-WARNING **: 18:57:44.100: ../glib/gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '73'
> 
> (waybar:9986): GLib-GObject-WARNING **: 18:57:44.100: ../glib/gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '72'
> [2021-11-02 18:57:44.100] [error] river_status_manager_v1 not advertised
> Gdk-Message: 18:57:44.103: Error 88 (Socket operation on non-socket) dispatching to Wayland display.
> ```

 can you mention which gtk version are you on??

**Comment by AbhishekDarshi** [comment]
> > Even I am facing the same issue.
> > ```
> > ** (waybar:9986): WARNING **: 18:57:44.100: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
> > 
> > (waybar:9986): GLib-GObject-WARNING **: 18:57:44.100: ../glib/gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '73'
> > 
> > (waybar:9986): GLib-GObject-WARNING **: 18:57:44.100: ../glib/gobject/gsignal.c:2081: type 'GtkWindow' is already overridden for signal id '72'
> > [2021-11-02 18:57:44.100] [error] river_status_manager_v1 not advertised
> > Gdk-Message: 18:57:44.103: Error 88 (Socket operation on non-socket) dispatching to Wayland display.
> > ```
> 
> can you mention which gtk version are you on??

gtk3-1:3.24.30+90+g20be04f7ac-1 on arch

**Comment by alebastr** [comment]
If you see the error on river - it is caused by an incorrect binding to the `zriver_status_manager_v1` interface. https://github.com/Alexays/Waybar/commit/024fd42e272f79cb08e594eb3af86c93b1446c91 fixes that and is required to use `river/tags` with current versions of river. Your options are to use waybar-git or to convince Arch maintainer to add the patch.

If you see it not on river - it's' expected. `river/tags` uses protocols specific to river and will fail with `river_status_manager_v1 not advertised` on any other compositor.

Gtk (with gtk-layer-shell) simply uses the same wayland connection and receives the protocol errors caused by the issues above.

**Comment by AbhishekDarshi** [comment]
> If you see the error on river - it is caused by an incorrect binding to the `zriver_status_manager_v1` interface. [024fd42](https://github.com/Alexays/Waybar/commit/024fd42e272f79cb08e594eb3af86c93b1446c91) fixes that and is required to use `river/tags` with current versions of river. Your options are to use waybar-git or to convince Arch maintainer to add the patch.
> 
> If you see it not on river - it's' expected. `river/tags` uses protocols specific to river and will fail with `river_status_manager_v1 not advertised` on any other compositor.
> 
> Gtk (with gtk-layer-shell) simply uses the same wayland connection and receives the protocol errors caused by the issues above.

Thanks for the info! After trying with source compiled waybar, it is working with river.
