### ISSUE TITLE
Font rendering is really bad

### ISSUE THREAD

**Issue by pta2002** [Alexays/Waybar#1285]
I am running waybar with sway on NixOS, and since I last updated the system the font rendering got really bad, here's how it looks without changing any styles:

![image](https://user-images.githubusercontent.com/7443916/137000738-ed6f34d4-ec08-4f32-a24c-98b719248098.png)

I can confirm this happens with whatever font I choose, it's not just this one font

**Comment by sweenu** [comment]
@pta2002 Could you say what the fix is? I have the same problem I think.

**Comment by pta2002** [comment]
I think all I did was pass through he environment variable XDG_DESKTOP_PORTAL_DIR to the systemd service. I also installed xdg-desktop-portal-wlr, could've been that.

**Comment by matejdro** [comment]
In case anyone else stumbles upon this issue:

1. You have to have `xdg-desktop-portal-gtk` installed
2. If gtk is not your preferred desktop portal, you must add `org.freedesktop.impl.portal.Settings=gtk` to your `portals.conf` file (see https://wiki.archlinux.org/title/XDG_Desktop_Portal#Backends)
