### ISSUE TITLE
pulseaudio module and mousescroll

### ISSUE THREAD

**Issue by kleshas** [Alexays/Waybar#1287]
Not sure if this is a bug or a config error, but mouse scrolling the pulseaudio module to change the volume doesn't do anything on my main monitor, but DOES work on the other two monitors.  It also works fine when waybar is started from the command line.

sway config is simply

bar {
   swaybar_command waybar
}

The outputs for the three monitors are correct (dimensions, relative position and Hz settings in sway config).  Clicking on the module brings up pavucontrol app as expected (so it's not a misalignment of the cursor or anything)

Same result if I use exec waybar in sway config instead of the above.

Not sure what else to look at.

**Comment by vvrein** [comment]
The same for me! I did nothing to solve this except train myself to tune volume on another monitor (what a shame!).

**Comment by vvrein** [comment]
Its working again! @kleshas can you check (upgrade if needed) ?

**Comment by kleshas** [comment]
It's changed slightly for me.  Up to date on arch, and occasionally still happens that mouse scroll doesn't work on either monitor (sometimes just one of them).  Clicking on the volume does reset it most of the time and it then works on both.  Just happened where I was watching mpv in full screen.  Non-viewing monitor didn't work for volume, when I stopped the video, the main monitor also wasn't working.  Clicking on the icon, and both monitors worked fine with scrollwheel.
