### ISSUE TITLE
[Feature Request] Standby Inhibitor timeout

### ISSUE THREAD

**Issue by Psykar** [Alexays/Waybar#1288]
I can't count the number of times I've hit the standby inhibitor and forgotten to turn it off later.
I generally want to inhibit standby for a set period of time (30 mins, 1 hour, 2 hours etc.)

Similar tools work by selecting a timeout, but could also work by clicking multiple times to cycle between a set of timeout periods.

I may get around to trying to implement this myself at some point... but wanted to put it here meanwhile in case I don't.

**Comment by jmcclelland** [comment]
I'm also interested. 

If #690 or #1237 were possible, then you could use the `on-click` [parameter](https://github.com/Alexays/Waybar/issues/299) to launch an executable that sleeps for a certain period of time and then shuts off the inhibitor. 

But adding a timeout parameter to the configuration would be much more elegant.
