### ISSUE TITLE
Octets vs bytes

### ISSUE THREAD

**Issue by dschrempf** [Alexays/Waybar#1290]
When using the `network` module, the speed is given in octets per second. This is very fine. However, the `o` looks like a zero and I always misread the numbers. Could we consider using a `B` instead of an `o`. (B, kB, MB, ...). (Or at least provide an option?) Thanks for considering this!

I know of https://github.com/Alexays/Waybar/issues/804, but maybe knowing the `o` confusion changes your minds :-).

**Comment by brodi1** [comment]
@Alexays This issue can be closed now because of https://github.com/Alexays/Waybar/commit/fcf93a6c45eede8fb5a31e6a1c0613f368e09ecc
