### ISSUE TITLE
Is it possible to check/wait for the tray to be available?

### ISSUE THREAD

**Issue by Hubro** [Alexays/Waybar#1291]
If waybar is too slow to start (and currently it's *extremely* slow to start [because of this bug](https://github.com/Alexays/Waybar/issues/1266)), the tray won't be available when my autostart applications launch. When Waybar finally starts, I have no icons in the tray. This makes it a huge pain to use several applications, like Dropbox, Discord, Teamspeak etc.

Is there any way to detect if the tray is available, so I can delay starting my applications?

**Comment by Hubro** [comment]
I no longer need this

**Comment by pmatos** [comment]
> If waybar is too slow to start (and currently it's _extremely_ slow to start [because of this bug](https://github.com/Alexays/Waybar/issues/1266)), the tray won't be available when my autostart applications launch. When Waybar finally starts, I have no icons in the tray. This makes it a huge pain to use several applications, like Dropbox, Discord, Teamspeak etc.
> 
> Is there any way to detect if the tray is available, so I can delay starting my applications?

Interesting, I came here because of this issue. Tray takes too long to start so apps start before tray is available. How did you solve it?

**Comment by Hubro** [comment]
I think in my case the root cause was this: https://github.com/NVIDIA/egl-wayland/issues/47

I pinned this package to version 1.1.7 on my laptop, which resolved this issue. This was a while ago though, so take that with a grain of salt.

**Comment by Hubro** [comment]
> > @pmatos I think in my case the root cause was this: [NVIDIA/egl-wayland#47](https://github.com/NVIDIA/egl-wayland/issues/47)
> > 
> > I pinned this package to version 1.1.7 on my laptop, which resolved this issue. This was a while ago though, so take that with a grain of salt.
> 
> Have you tried 1.1.11? Do you still get the slowdown. I do. Unfortunately I don't think it's trivial to revert to an old version on Arch. Will take a look.

I downloaded the old package from [the Arch Linux Archives](https://archive.archlinux.org/packages/e/egl-wayland/) and installed it with `pacman -O` (iirc) then I pinned the version in the pacman config so it doesn't get updated.
