### ISSUE TITLE
wlr/taskbar hide specific windows based on app_id and title 

### ISSUE THREAD

**Issue by Iss-in** [Alexays/Waybar#1293]
will it be possible to extend the functionality of #1029 , to use app_id and title simultaneously for window identification
There are a lot of sub windows for apps like open/save/properties  file/folder dilogues, which are opened for a limited time and should not appear on taskbar as they serve no purpose. more to add will be firefox microphone and pip windows.

@Anakael  could you please look into it

**Comment by Anakael** [comment]
@Iss-in 
Merged in master.

**Comment by Iss-in** [comment]
awesome, thanks a lot 😀
