### ISSUE TITLE
Caledar display issue

### ISSUE THREAD

**Issue by Iss-in** [Alexays/Waybar#1295]
Using monospace font for calendar tooltip, yet its not spaced properly

module config :

            "tooltip-format": "<span font='IBM Plex Mono Bold 13'><big>{:%d %B}</big>\n<tt><small>{calendar}</small></tt></span>",

![image](https://user-images.githubusercontent.com/36916613/138083454-64e1b393-6862-425c-985f-91e2f555f24d.png)

**Comment by jlaunay** [comment]
Any news about this?
I have exactly the same problem.
I've tried several fonts, change the Waybar configuration, change the GTK theme, change the CSS...
Nothing to do, I still have this shifted display on Sway and on Hyprland too.

**Comment by LukashonakV** [comment]
Hi @Iss-in  and @jlaunay 
Kindly share the full clock config block. The reason I'm asking for is, I've installed IBM Plex Mono font and for me it looks good so far

```xml
    "clock": {
        "format": "{:%H:%M}  ",
        "format-alt": "{:%A, %B %d, %Y (%R)}  ",
        "tooltip-format": "<span font='IBM Plex Mono Bold 13'><big>{:%d %B}</big>\n<tt><small>{calendar}</small></tt></span>",
        "today-format": "<span color='#ff6699'><b><u>{}</u></b></span>",
        "format-calendar": "<span color='#ecc6d9'><b>{}</b></span>",
        "on-scroll": {
                    "calendar": 1
                     }
    },

```

---

![ps_2022-12-13-17_02_43](https://user-images.githubusercontent.com/23121044/207353549-4951a074-50d2-4b0a-ad26-16a652fbf895.png)

**Comment by jlaunay** [comment]
I installed this font and I have the same problem.
![cal2](https://user-images.githubusercontent.com/1137028/207358622-73bc871b-7d2c-498f-a2b5-d766f5feb0d8.png)

**Comment by Iss-in** [comment]
my bad, i totally forgot about this,   I did check again and not sure what the issue was, but it look fine from my side as well

using same tooltip config as mentioned in OG comment

**Comment by LukashonakV** [comment]
You might faced with the same issue https://github.com/Alexays/Waybar/issues/1874#issuecomment-1349150106
@jlaunay had the same problem
