### ISSUE TITLE
Any space characters after icons are misrendered

### ISSUE THREAD

**Issue by 0xdec** [Alexays/Waybar#131]
Putting the icon in front of the text results in adjacent space characters appearing as a box with 0020 inside (representing U+0020, the space character). See the green module here:
![waybar](https://user-images.githubusercontent.com/3586264/50468288-e9974b00-099e-11e9-8899-f5922e3b1bbb.png)

The text resulting in this is ` {usage}%`

**Comment by Alexays** [comment]
Yep install otf-font-awesome and uninstall the other package like ttf

**Comment by Alexays** [comment]
Is your problem solved? :)

**Comment by 0xdec** [comment]
That fixed it, thank you! I was under the impression that ttf generally has better support in Linux, thanks for the heads up!

**Comment by matzebond** [comment]
For me this did not appear after every icon.
Space error after the backlight icon but not after the wifi or sound icon.
