### ISSUE TITLE
false bar

### ISSUE THREAD

**Issue by imigorella** [Alexays/Waybar#1310]
Good day!
After installing the waybar, another bar appeared at the bottom of the desktop!
how to remove from it?
![2021-11-05](https://user-images.githubusercontent.com/93761534/140499456-35e89154-0d3a-4a79-8999-d882a7731b7b.png)

**Comment by gmykhailiuta** [comment]
You have 2 bars running on screenshot. You didn't say what OS nor what window manager is that. Is it SwayWM? If yes, try to replace `status_command ..` with `swaybar_command waybar` in "bar" section of sway config (~/.config/sway/config).

**Comment by imigorella** [comment]
> You have 2 bars running on screenshot. You didn't say what OS nor what window manager is that. Is it SwayWM? If yes, try to replace `status_command ..` with `swaybar_command waybar` in "bar" section of sway config (~/.config/sway/config).

**Comment by imigorella** [comment]
> You have 2 bars running on screenshot. You didn't say what OS nor what window manager is that. Is it SwayWM? If yes, try to replace `status_command ..` with `swaybar_command waybar` in "bar" section of sway config (~/.config/sway/config).

Проблему решил!
Вместо "swaybar_command waybar", добавил в конец конфигурационного файла строку "exec waybar"
![2021-11-06](https://user-images.githubusercontent.com/93761534/140606265-7e2ab79a-b3ac-40de-9a60-df9b372f4cdf.png)
