### ISSUE TITLE
[Question] How do I set the value in my waybar config to the output of bash command

### ISSUE THREAD

**Issue by WilliamBehrens** [Alexays/Waybar#1313]
I'm trying to set the icon theme of "wlr/taskbar" to `awk '{print $3}' <(gsettings list-recursively org.gnome.desktop.interface | grep icon-theme)`

**Comment by l3nkz** [comment]
There is a special setting for the taskbar module called `icon-theme` (See [here](https://github.com/Alexays/Waybar/wiki/Module:-Taskbar)). Just set the corresponding value in your config before starting waybar.

**Comment by WilliamBehrens** [comment]
I was wondering if there was a way to dynamically set it based off the the default icon theme

**Comment by l3nkz** [comment]
If you don't specify any icon theme in the config, the module uses the system wide default icon theme as fallback. But this is only loaded once at the start of waybar. Do you want the theme to change dynamically during runtime?

**Comment by WilliamBehrens** [comment]
Where does it check the icon theme? from gtk? qt?

**Comment by l3nkz** [comment]
Currently it uses the gtk icon theme loading functionality. Hence the gtk system default will be used.
