### ISSUE TITLE
Blur background effect ?

### ISSUE THREAD

**Issue by Ogromny** [Alexays/Waybar#132]
Hi,

Do you think it's possible to implement a blurry background effect ?

Sorry for my english, I'm French

**Comment by myfreeweb** [comment]
This needs support from the compositor, e.g. KDE has a protocol for this: https://github.com/KDE/kwayland/blob/master/src/client/protocols/plasma-effects.xml

**Comment by mh4nx7net** [comment]
yes we can, by poor way
put fake blurred background by using transparent_blurred.png as mentioned as background-image
hahaha

**Comment by p00f** [comment]
> yes we can, by poor way
> put fake blurred background by using transparent_blurred.png as mentioned as background-image
> hahaha
This is actually viable though - status bars don't move, you just generate it once on startup

**Comment by AntiHeadacheGuy** [comment]
> yes we can, by poor way
put fake blurred background by using transparent_blurred.png as mentioned as background-image
hahaha
I even get the background that makes Waybar looks like blured while the configuration is default

**Comment by pavel-kolesnikov** [comment]
In 2021 GTK4.0 seems to support the effect with something like `filter: blur(50px)` [here](https://gitlab.gnome.org/GNOME/gtk/-/commit/86c60592fbfdadaab183e55d17c20572e8b9d674).
Don't know if it released yet. Also, it seems `waybar` uses `GTK3`.

`waybar` complains:
```
 [error] style.css:10:8'filter' is not a valid property name
```

OS: Archlinux
```
Name            : waybar
Version         : 0.9.9-1
Description     : Highly customizable Wayland bar for Sway and Wlroots based
                  compositors
Architecture    : x86_64
URL             : https://github.com/Alexays/Waybar/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : gtkmm3  libjsoncpp.so=25-64  libsigc++  fmt  wayland
                  libdate-tz.so=3-64  libspdlog.so=1-64  gtk-layer-shell  libevdev
                  libpulse  libnl  libappindicator-gtk3  libdbusmenu-gtk3
                  libmpdclient  libsndio.so=7-64  libxkbcommon
Optional Deps   : otf-font-awesome: Icons in the default configuration [installed]
Required By     : None
Optional For    : sway
Conflicts With  : None
Replaces        : None
Installed Size  : 1055.84 KiB
Packager        : Maxim Baz <pgp@maximbaz.com>
Build Date      : Mon 10 Jan 2022 17:27:21 +04
Install Date    : Wed 02 Feb 2022 17:26:07 +04
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by Alexays** [comment]
Can't be fixed while using gtk3
