### ISSUE TITLE
Waybar overwrites config on reinstall

### ISSUE THREAD

**Issue by masoudd** [Alexays/Waybar#1324]
Waybar overwrites `/etc/xdg/waybar/config` and `style.css` on ninja install.

on Archlinux:
I had waybar installed from `community/waybar`, and did some modifications to `/etc/xdg/waybar/config`, then decided to try waybar-git from aur. Installing it overwrote the config.

**Comment by Anakael** [comment]
You can put your configs to `~/.config/waybar/` as described here:
https://github.com/Alexays/Waybar/wiki/Configuration
