### ISSUE TITLE
Custom tooltips for tray icons

### ISSUE THREAD

**Issue by busywhistling** [Alexays/Waybar#1336]
Is it possible to add custom tooltips to the tray icons (for e.g., the network manager tray icon)? Or if it's not, can this functionality be considered for addition? The usecase I have in mind is to display the local IP address (as well as the global IP address via a geoIP service) in the tooltip for the network manager icon. (I already know that we can have custom modules with custom tooltips, but this is about the tray icon bar)

**Comment by aspauldingcode** [comment]
I'm also wondering this.

**Comment by busywhistling** [comment]
Hey all, I have since stopped using waybar, and since there are already many issues in this repo, I'd rather close this. If you have the exact same problem, I'd recommend opening a new issue which will convey relevance & up-to-dateness to the maintainers. I hope you understand.
