### ISSUE TITLE
Spaces around icons being ignored

### ISSUE THREAD

**Issue by jvdavim** [Alexays/Waybar#1343]
When format contains Font Awesome 5 Free Solid Icons, any space around the icon are ignored.

config file sample:
```
[
    {
        "name": "topbar",
        "layer": "top",
        "position": "top",
        "height": 20,
        "modules-left": [
            "sway/workspaces",
            "sway/window"
        ],
        "modules-center": [
            "tray"
        ],
        "modules-right": [
            "network#vpn",
            "network#wifi",
            "network#ethernet",
            "network#disconnected",
            "custom/weather",
            "battery",
            "disk",
            "memory",
            "cpu",
            "temperature",
            "pulseaudio",
            "backlight",
            "clock",
            "idle_inhibitor"
        ],
        "cpu": {
            "format": "          {usage}%",
            "tooltip": false
        },
        ...
]
```

style.css sample:
```
* {
    border: none;
    border-radius: 0;
    font-family: "Clear Sans", "Font Awesome 5 Free Solid";
    font-size: 11px;
    min-height: 0;
}

#cpu {
    padding: 0 6px;
    margin: 0 0px;
    color: #ffffff;
}
```
waybar
![printscreen](https://user-images.githubusercontent.com/16657663/144869884-8aab80ff-530e-4a3b-9a00-8b8771791948.png)

**Comment by tamirzb** [comment]
I also got this ever since upgrading pango to 1:1.50.0-2 (on Arch Linux).
No idea why it happens though.

**Comment by tamirzb** [comment]
Update: Seems that it's a problem with pango, which [this merge request](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/552) is supposed to fix.

**Comment by tamirzb** [comment]
Updating to pango 1.50.2 fixes this issue for me.

**Comment by jvdavim** [comment]
As mentioned by @tamirzb, it was a pango issue. Fixed in this commit: https://gitlab.gnome.org/GNOME/pango/-/commit/4b651fca1f40355334a95effb46b2420b1c0ca36.

**Comment by Indigo183** [comment]
I am getting this issue with pango version 1.56.4-1, is it still due to pango?
