### ISSUE TITLE
Not possible to install waybar in arch linux

### ISSUE THREAD

**Issue by ghost** [Alexays/Waybar#1356]
warning: cannot resolve "libjsoncpp.so=24-64", a dependency of "waybar"
:: The following package cannot be upgraded due to unresolvable dependencies:
waybar

**Comment by Magnitudexx** [comment]
this is a dependecy issue, probably a fast fix when a maintainer gets to it. For the moment you could just use `pacman -Syu --ignore waybar` if you want to update and wait until it is fixed

**Comment by kahnclusions** [comment]
I get this too when upgrading my system:

```
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing jsoncpp (1.9.5-1) breaks dependency 'libjsoncpp.so=24-64' required by waybar-git
```

**Comment by etrnal70** [comment]
For me, i fixed it by removing currently installed waybar and all it's dependencies with `pacman -Rns waybar` and reinstall it again

**Comment by Magnitudexx** [comment]
@Alexays do you package ẁaybar-git` yourself? I would do it if a knew how but i don't

**Comment by jfred9** [comment]
@outdvgrxve Try to delete the AUR helper cache folder for waybar-git. I had the same problem. When I deleted ~/.cache/paru/clone/waybar-git and installed it again it worked fine.

If you are using a different AUR helper than paru then your cache path is likely different.

**Comment by KoalaV2** [comment]
I resolved it by uninstalling waybar-git, updating, reinstalling.

**Comment by jalada** [comment]
> I resolved it by uninstalling waybar-git, updating, reinstalling.

This worked for me but I also had to clear out my caches. I'm using `yay` so it was `yay -Sc`.

**Comment by bluebyt65** [comment]
I have also this error when I started Waybar.
waybar: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory

I Builded Waybar from source, Does anybody know how to uninstall it?

**Comment by ahmadraniri1994** [comment]
> I have also this error when I started Waybar. waybar: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory
> 
> I Builded Waybar from source, Does anybody know how to uninstall it?

sudo ninja -c build uninstall
