### ISSUE TITLE
Failed to acquire required resources

### ISSUE THREAD

**Issue by Dennetix** [Alexays/Waybar#136]
Hi,
when I start Waybar I get the error Failed to acquire required resources.
I've done some debugging and it seem like the handleGlobal function doesn't get called with the zwlr_layer_shell_v1, nor the zxdg_output_manager_v1 interfaces.
I'm fairly new to Wayland so I have no idea what causes this problem.

**Comment by Dennetix** [comment]
Arch Linux and sway

**Comment by Alexays** [comment]
You can paste the output of `sway -v`

**Comment by Dennetix** [comment]
Sorry, I was using version 0.15 (from pacman). I'm now at the newest version and it works. Thanks :)

**Comment by jubalh** [comment]
I have the same issue. Launching waybar on terminal in sway:

```
waybar
Resources files: /etc/xdg/waybar/config, /etc/xdg/waybar/style.css 
Failed to acquire required resources
```

waybar 0.2.3
sway 0.15.2
openSUSE Tumbleweed

Any hints?

**Comment by jubalh** [comment]
Will wait until 1.0 is out then. Thanks

**Comment by marektmn** [comment]
Hi :wave: 
Newbie here, trying to setup waybar (using Wayland) by following the [wiki](https://github.com/Alexays/Waybar/wiki/)
I've hit a roadblock with this error:
```
waybar 
[2022-01-16 21:58:22.890] [info] Resources files: /home/marek/.config/waybar/config, /home/marek/.config/waybar/style.css
[2022-01-16 21:58:22.892] [error] Failed to acquire required resources
```
Any ideas what could be wrong?
