### ISSUE TITLE
Tray not working in gentoo

### ISSUE THREAD

**Issue by aniketfuryrocks** [Alexays/Waybar#1367]
On Gentoo, I have installed each and every dependency listed in `meson.build` but still `meson` doesn't compile tray into `waybar`.

Compiling `waybar` after removing the [check](https://github.com/Alexays/Waybar/blob/ce56a807927e4773df0e17ddb66830cd0d2944bd/meson.build#L210), everything works fine
but I still get the following warning (tray icons show up)

```bash
[2022-01-03 11:28:39.317] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
```

*Use flags*
```bash
USE="-kde -qt5 -systemd -quicktime -plasma -gnome qml gtk gtk3 gtk4 screencast openrc policykit dbus ssl udev udisks unicode upower vim-syntax wifi video sound zip gnome-keyring network networkmanager pcre32 wayland xwayland gles2 gles3 vulkan egl theora bluetooth mp3 mp4 mpeg png introspection popups menu tray systray dbusmenu-gtk fish-completion mpd clang"
```

I went as far as to provide the following local USE flags
```bash
gui-apps/waybar mpd network popups tray wifi dbusmenu-gtk experimental logind rfkill -systemd
```

**Comment by mazunki** [comment]
Works for me, using Gentoo on ~amd64. `gui-apps/waybar-0.9.8`, and `dev-libs/libappindicator-12.10.1_p20200706`

`equery u wayland` tells me I have installed waybar with `mpd network popups pulseaudio -sndio tray udev wifi` flags. `libappindicator` uses `abi_x86_32 introspection -test`.

waybar depends on `dev-libs/libappindicator` if `tray` use flag is enabled, thus `equery d libappindicator` shows me waybar (among other things). I never needed to export a fake XDG variable saying I'm under Unity.

**Comment by nfm886** [comment]
Not working for me too... Compiled from GH as well as version =9999 from gentoo repo.

**Comment by lepz0r** [comment]
It's working on sway for me if launched with ``dbus-run-session sway`` otherwise it's not working

**Comment by mazunki** [comment]
> It's working on sway for me if launched with `dbus-run-session sway` otherwise it's not working

I am running dbus as a user service, exporting `DBUS_SESSION_BUS_ADRESS` afterwards to sway.

**Comment by shawnhaigh** [comment]
I seem to be having a similar issue... and I realize the tray is still in beta, but wanted to post this information none the less.

I have **libappindicator** installed
```
# emerge libappindicator
[ebuild   R   ] dev-libs/libappindicator-12.10.1_p20200706
```
**Waybar**
```
$ waybar -v
Waybar v0.9.9
```
and **sway**
```
$ sway -v
sway version 1.7
```

running **waybar** with the trace flag returns:
```
$ waybar -c .config/waybar/config -l trace
...
[warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
...
```

I am also launching sway in a dbus-session, and have XDG_CURRENT_DESKTOP set to "Unity"
```
$ dbus-run-session sway

$ export | grep DBUS_SESSION_BUS_ADDRESS
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-MchMpVd8Rhm,guid=b665e413caf2e88f9s8s8a9sa9s8989a"

$ export | grep XDG_CURRENT_DESKTOP
declare -x XDG_CURRENT_DESKTOP="Unity"
```

The tray still does not work when executing apps like ```keepassxc``` which display a tray icon.

**Comment by ignamartinoli** [comment]
I'm having the same issue

**Comment by LukashonakV** [comment]
Works well for me:

1. `dev-libs/libappindicator
      Latest version available: 12.10.1_p20200706
      Latest version installed: 12.10.1_p20200706
      Size of files: 74 KiB
      Homepage:      https://launchpad.net/libappindicator
      Description:   A library to allow applications to export a menu into the Unity Menu bar
      License:       LGPL-2.1 LGPL-3`
2. `export | grep DBUS_SESSION_BUS_ADDRESS && export | grep XDG_CURRENT_DESKTOP
DBUS_SESSION_BUS_ADDRESS unix:abstract=/tmp/dbus-PqazDHJlc8,guid=44dc6760f29fb2d71f26…
XDG_CURRENT_DESKTOP Unity`
4.

**Comment by bakerk98** [comment]
Works on both my Gentoo machines

**Comment by ignamartinoli** [comment]
It works on mime too now

**Comment by aniketfuryrocks** [comment]
Well, I am no longer using `gentoo`. Thank you guys for giving in the time.
Since It works for @ignamartinoli @bakerk98. Should I consider this resolved and close the issue ?

**Comment by ignamartinoli** [comment]
I vote for it to be closed. If I were you, I would wait 3 days and if the creator doesn't respond I would close it

**Comment by bakerk98** [comment]
> I am no Klinger using gentoo

Ooo What you switched to?

**Comment by aniketfuryrocks** [comment]
@bakerk98 fedora rawhide (Gnome 42), with tiling assistant

**Comment by dryya** [comment]
I'd also like to ask about the warning to set a fake `XDG_CURRENT_DESKTOP=Unity`. It was added in this commit: https://github.com/Alexays/Waybar/commit/ed240ac105636b04a016003e2f5d2c502d777d93 but as far as I can tell, it hasn't been relevant for years. Plus, it always pops up even if the tray is working fine, confusing users. Perhaps it's time for a second look at it - or is there something I'm missing, and is there any reason it shouldn't be removed?
