### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by array-in-a-matrix** [Alexays/Waybar#1372]
the config link 404s 
https://github.com/Alexays/Waybar/wiki/Examples#wtls-configuration

**Comment by array-in-a-matrix** [comment]
the image and config are missing 
https://github.com/Alexays/Waybar/wiki/Examples#krathalans-configuration

**Comment by Alexays** [comment]
Up to you to clean the wiki :)

**Comment by array-in-a-matrix** [comment]
Done.
