### ISSUE TITLE
More CSS properties

### ISSUE THREAD

**Issue by array-in-a-matrix** [Alexays/Waybar#1377]
I don't know if its possible but can more CSS properties can be added? I feel like waybar would benefit a lot if it can use properties like `clip-path`.

**Comment by keithbowes** [comment]
I'm pretty sure it's just the CSS properties supported by GTK and you'd have to take it up with the GTK developers.  The missing GTK CSS properties that bother me are max-width and max-height (it has the min-* variety but not the max-* variety).

**Comment by Alexays** [comment]
Yeah, it's up to GTK devs, sorry :/
