### ISSUE TITLE
Feature request: Wf-recorer widget

### ISSUE THREAD

**Issue by timsofteng** [Alexays/Waybar#1378]
Hello. I have idea about wf-recorder widget in waybar.
Is it possible to implement stopwatch with rec icon when wf-recorder start to work? And disable it when it finish.

**Comment by primalmotion** [comment]
I do this with a custom module

```
	"custom/recording": {
		"interval": 2,
		"exec-if" : "pgrep wf-recorder",
		"exec": "echo '<span font=\"FontAwesome 5 Free Solid\">\uf111</span>'",
		"tooltip": false
	},
```
You can probably add different exec if you need the time counter

**Comment by Alexays** [comment]
Go for a custom module :)
