### ISSUE TITLE
libfmt 8.1.0 breaks compilation

### ISSUE THREAD

**Issue by mazunki** [Alexays/Waybar#1379]
`src/modules.clock.cpp` fails during compilation if using `>=libfmt-8.1.0` or above: 

https://github.com/Alexays/Waybar/blob/d9b5c2595a08e481520d96d7ee30daab4ac07f1b/src/modules/clock.cpp#L236

due to libfmt making `specs` a private variable:

https://github.com/fmtlib/fmt/commit/f8542cd9888b0f07e40500ad5813d3b8ad4d9c68

We should probably use `libfmt`'s formatter altogether.

**Comment by mazunki** [comment]
Here is a hotfix which seems to work for me.

https://github.com/mazunki/Waybar/commit/2301788a810b64be9361b15fbd8f510002c74cc4

**Comment by ahmadraniri1994** [comment]
> Here is a hotfix which seems to work for me.
> 
> [mazunki@2301788](https://github.com/mazunki/Waybar/commit/2301788a810b64be9361b15fbd8f510002c74cc4)

Thanks, bro.

**Comment by ahmadraniri1994** [comment]
> Here is a hotfix which seems to work for me.
> 
> [mazunki@2301788](https://github.com/mazunki/Waybar/commit/2301788a810b64be9361b15fbd8f510002c74cc4)

Dunno why, I tried your fork but my compilation still complains about fmt.

**Comment by mazunki** [comment]
> Dunno why, I tried your fork but my compilation still complains about fmt.

Can you tell me what error you're getting? I can take a look tomorrow.

**Comment by mazunki** [comment]
Closing this issue since there's an active pull request to solve it.
