### ISSUE TITLE
suggestion(keyboard-state): tell user that add user to input group in readme

### ISSUE THREAD

**Issue by asas1asas200** [Alexays/Waybar#1383]
`keyboard-state` module tried to read the files in `/dev/input`.

In order to open the devices in `/dev/input`, user must belongs to input group or root:
```
$ ls -l /dev/input
total 0
drwxr-xr-x 2 root root     140 Jan  7 15:31 by-id
drwxr-xr-x 2 root root     180 Jan  7 15:31 by-path
crw-rw---- 1 root input 13, 64 Jan  7 15:31 event0
crw-rw---- 1 root input 13, 65 Jan  7 15:31 event1
crw-rw---- 1 root input 13, 74 Jan  7 15:31 event10
crw-rw---- 1 root input 13, 75 Jan  7 15:31 event11
crw-rw---- 1 root input 13, 76 Jan  7 15:31 event12
crw-rw---- 1 root input 13, 77 Jan  7 15:31 event13
crw-rw---- 1 root input 13, 78 Jan  7 15:31 event14
crw-rw---- 1 root input 13, 79 Jan  7 15:31 event15
crw-rw---- 1 root input 13, 80 Jan  7 15:31 event16
crw-rw---- 1 root input 13, 81 Jan  7 15:31 event17
crw-rw---- 1 root input 13, 82 Jan  7 15:31 event18
crw-rw---- 1 root input 13, 83 Jan  7 15:31 event19
crw-rw---- 1 root input 13, 66 Jan  7 15:31 event2
crw-rw---- 1 root input 13, 84 Jan  7 15:31 event20
crw-rw---- 1 root input 13, 67 Jan  7 15:31 event3
crw-rw---- 1 root input 13, 68 Jan  7 15:31 event4
crw-rw---- 1 root input 13, 69 Jan  7 15:31 event5
crw-rw---- 1 root input 13, 70 Jan  7 15:31 event6
crw-rw---- 1 root input 13, 71 Jan  7 15:31 event7
crw-rw---- 1 root input 13, 72 Jan  7 15:31 event8
crw-rw---- 1 root input 13, 73 Jan  7 15:31 event9
crw-rw---- 1 root input 13, 63 Jan  7 15:31 mice
crw-rw---- 1 root input 13, 32 Jan  7 15:31 mouse0
```

Otherwise the `open()` function in `openDevice()` will always return `-1` and error number `13` which means `Permission denied`.

https://github.com/Alexays/Waybar/blob/18cbd2aa1a90aacbc938c1e92b54b314eccf2661/src/modules/keyboard_state.cpp#L88-L92

I spend much time to find this problem, so I think it can describe in readme or manual page to remind users add themselves into input group.

And all the `std::runtime_error` message has beed catched, I cannot see any useful message in log even in trace loglevel.
So I debuged with manually print by myself and recompiled it, weather it can prompt more details in log?

**Comment by GrantMoyer** [comment]
Huh, It looks like my user is in the input group, but I don't recall adding myself to it. It looks like [systemd might automatically add me to the group][1], or something. Do you happen to not use systemd?

In any case, I'll make a PR to improve the error message and update the docs.

[1]: https://wiki.archlinux.org/title/Users_and_groups#Pre-systemd_groups
