### ISSUE TITLE
Conditionally show modules?

### ISSUE THREAD

**Issue by hahuang65** [Alexays/Waybar#1391]
I share the same waybar config between a desktop and a laptop.

Is there a way to conditionally show modules? In particular, I'm asking about the battery. On the desktop it just shows up with an icon, but it doesn't make sense since it's always plugged in.

I also can't just remove it cuz I need to see the battery on my laptop.

**Comment by hahuang65** [comment]
NM, turns out it was the volume icon for headset. For some reason it was a battery...

**Comment by manfred3000** [comment]
The option to load different config files/locations would be nice, though.
