### ISSUE TITLE
0.9.9 - don't work "network" {bandwidth*}

### ISSUE THREAD

**Issue by 0xIDENTITY** [Alexays/Waybar#1392]
**'Network speed' is working on 0.9.8.**
I don't know why. Now (0.9.9) always static 0 bit/s (or octet). Maybe I can try something step-by-step? Let me know, please.
My config:

    "network": {
        "format-wifi": " {bandwidthDowbBits}  {bandwidthUpBits} ",
        "format-ethernet": " {bandwidthDownBits}  {bandwidthUpBits} ",
        "format-linked": "(No IP)",
        "format-disconnected": "",
        "on-click": "alacritty -e nmtui",
        "tooltip": false,
        "interval": 5
    }

And, and, and. When "format-wifi" - nothing is displayed (empty, even without icons).

**Comment by ibrokemypie** [comment]
I believe it was caused by commit 9d9f95976926d5817837d03344b9506d700cee16 which states that setting interface to "*" should result in the same as the old auto implementation. This isn't documented in the wiki though and should probably be the default since the old default no longer works.

**Comment by bd-g** [comment]
I've done testing on that commit and setting the interface to "*" does __not__ have the same behavior as the old auto implementation. There probably wasn't enough testing done on different configurations prior to this commit, and I'm working on a fix. In the meantime, a PR to fix the wiki and reset the default would be helpful.

**Comment by 0x159BABA11227B902** [comment]
> I've done testing on that commit and setting the interface to "*" does __not__ have the same behavior as the old auto implementation.

How to set up multiple interfaces?

**Comment by mvdan** [comment]
I don't think it's just the "auto" or wildcard detection; even when I set up the interface to `enp5s0`, my wired connection, I still get `0o/s` even though I can clearly see large numbers in /dev:

```
$ cat /proc/net/dev | grep enp5s0
enp5s0: 3793211018 3216162    0    4    0     0          0      1262 325850572 1492065    0    0    0     0       0          0
```

**Comment by bd-g** [comment]
https://github.com/Alexays/Waybar/issues/610 was the initial issue that the commit was trying to fix
https://github.com/Alexays/Waybar/issues/1327 is a duplicate issue 

@ciarand Thanks for taking up the initial issue and pushing a fix! Before anyone else dives into the code, do you have an idea of why the above behavior would be happening?

**Comment by droc12345** [comment]
I had another type problem (network related) so I looked at the code.
and between 0.98 and 0.99 only 2 changes were made to network.cpp (1 of which was a comment)
the other is line 81 want_route_dump was changed from false to true, changing it back fixed my problem.

I think that the change was done to try and show initial parameters (bandwidth doesn't show immediately, but after 1st refresh)
But evidently setting want_route_dump to true creates some other issue(s).

**Comment by bd-g** [comment]
I don't believe this solves the "auto-select" problem either

**Comment by bd-g** [comment]
I agree - it appears with regex you can ignore interfaces you don't care about, but there isn't logic to determine prioritization of networks. Maybe we could add some logic to find all interfaces matching the config file, then sort by volume of network traffic?

**Comment by tombh** [comment]
Ohhh, thanks to @droc12345, I've just realised what was meant by "interface" in this thread! It's a waybar config setting. So now adding the `interface` line makes my bandwidth show up again :)

```
"network": {
    "interface": "wlan0", // This is the magic line
    "format-wifi": " {bandwidthDownBits}  {bandwidthUpBits} ",
    "format-ethernet": " {bandwidthDownBits}  {bandwidthUpBits} ",
    "format-linked": "(No IP)",
    "format-disconnected": "",
    "on-click": "alacritty -e nmtui",
    "tooltip": false,
    "interval": 5
}
```

**Comment by bd-g** [comment]
> 

Great point. Just brainstorming here. What about this - building in scroll functionality for the network module, where when you scroll on the module, it cycles through all the interfaces that match the regex? This would remove the need for interface to be a required parameter, or for us to try and guess a default.

**Comment by droc12345** [comment]
If there is no interface specified (not sure why we really want that) then is there a way to provide an ability to show all interfaces and allow the user to select one? prog/script pops up when no interface is specified or there is more than 2 interfaces (lo and another) . To me this would be easier than trying to fit scrolling/cycing.
The reason I don't disregard lo completely is that someone, somewhere will want to see it. *lol*

Lets look at my case, I have lo, eth0 and when I turn on the vpn I have tun0, and when I turn the vpn off tun0 goes away.
Could that be handled by scrolling/cycling, ie would the choices be static (from when I started waybar)?

**Comment by bd-g** [comment]
I believe that the networks would be polled and matched against the "interface" parameter on every refresh. The current default is 60s.

So it would be a matter of storing an array of interfaces with associated network information and updating the entire array each refresh period. Then having way bar select one interface from that array to display, and building a functionality to change which is displayed (whether the built in scroll ability, the click functionality, or something new) and persisting that selection across refreshes.

**Comment by droc12345** [comment]
That might work (mine is 2 sec refresh as I like to see more or less current usage) and as long as the interface parm is still being recognized, then I see no harm. 

You might want to keep a flag for interface/no-interface(or wildcard) so that easy choices could be made if this extends into more than one or two functions though.

**Comment by droc12345** [comment]
If a function calls some other function or the code changes extends into multiple functions, and it has to make choices based on being given an interface name or finding them out, it would be nice to have a flag saying it's been given an interface vs figure out the interfaces, kind of like the want_route_dump flag, just something that's easy to use for making choices. 
I could just be overthinking it too. *lol*

I'll mention the interface (config file) once again, whether using the interface tag or making a choice because they're offered multiple interfaces (scrolling, etc), they HAVE to make a choice. To me it's easiest to do it in the config file.

Another possible option (just off the top of my head) is if no interface specified, put all that data into something like a tooltip that shows all interfaces (and data) when hovered, rather than letting them select from scrolling/menu selection

**Comment by bd-g** [comment]
I think just updating the wiki and describing the scroll/function is best, and leaving the current config default of "*" if no interface is specified.

> Another possible option (just off the top of my head) is if no interface specified, put all that data into something like a tooltip that shows all interfaces (and data) when hovered, rather than letting them select from scrolling/menu selection

So this would entail changing the default tooltip format to being a list of possible interfaces and data. I think it would only be feasible to list the interfaces, not the data. That would be a ton of text for a tooltip otherwise. But that is a good idea - could format it like the default CPU tooltip? 

Could we combine the two ideas? If no interface is specified use * as the default, have the default tooltip be a list of interfaces, and include scroll functionality by default as well?

**Comment by droc12345** [comment]
That sounds feasible

**Comment by droc12345** [comment]
Might mention in the docs/wiki that the interface name (config option) is the same as what is returned from 
ifconfig, ip addr or netstat -i

**Comment by bd-g** [comment]
That's really helpful, I agree. 

I'm going to start work on this at https://github.com/bd-g/Waybar, you're welcome to contribute/collaborate

**Comment by droc12345** [comment]
line 108-117 of network.cpp has an if condition to check whether the interface is up (want_route_dump_)
then either sets the flag OR sets it for link and addr. I think this is wrong.
I think that link and addr should always be set (remove them from the else) and just toggle the route flag if interface is not specified. I'm basing this on the fact that want_* are supposed to handle multiple calls. 

This is off the top of my head, so I haven't tried it.

**Comment by siikamiika** [comment]
I'm not sure about compatibility with old behavior but got mine to work without explicit `interface` with this change to `Network::checkInterface`

```diff
diff --git a/src/modules/network.cpp b/src/modules/network.cpp
index 74b54d9..3b88011 100644
--- a/src/modules/network.cpp
+++ b/src/modules/network.cpp
@@ -395,7 +395,8 @@ bool waybar::modules::Network::checkInterface(std::string name) {
     return config_["interface"].asString() == name ||
            wildcardMatch(config_["interface"].asString(), name);
   }
-  return false;
+  spdlog::debug("ifname_: {}; name: {}", ifname_, name);
+  return ifname_ == name;
 }

 void waybar::modules::Network::clearIface() {
```

**Comment by cmprmsd** [comment]
For me the bandwidth did not show up correctly on wlan0 as described here and https://github.com/Alexays/Waybar/issues/610.

I built a go custom app based on i3-netusage and uploaded it to Github. Maybe it helps you as well :)

I tried to add autodetection of the gateway interface. Not sure if it does work correctly. Just had some late night coding time :D 

https://github.com/cmprmsd/sway-netusage

**Comment by SuperCowProducts** [comment]
> bandwidthDowbBits

For anyone else trying this, watch out for the typo!

@tombh could you edit the comment?

**Comment by tombh** [comment]
Oops, thanks, updated.
