### ISSUE TITLE
Random crash at startup with "Type is not convertible to string"

### ISSUE THREAD

**Issue by zsolt-donca** [Alexays/Waybar#1402]
Waybar randomly crashes at startup with the below error message. I am running waybar as a systemd user service, and it takes lots and lots of retries to catch one instance of Waybar that actually runs. It keeps restarting for 10-20 seconds usually until it finally starts correctly.

The error message is:

```
unhandled exception (type std::exception) in signal handler:
what: Type is not convertible to string
```

The results of `coredumpctl dump waybar` is at, along with my config and style.css files: https://gist.github.com/zsolt-donca/8c4d3a8003ae2a9af6f7c9e27ec98f97

I am on Arch Linux using the [official build](https://archlinux.org/packages/community/x86_64/waybar/) from the community repo. Last time I checked [waybar-git](https://aur.archlinux.org/packages/waybar-git/) it was doing the same.

In case it's relevant, I am using a HiDPI display with a scale factor = 2.

**Comment by Ranguvar** [comment]
I'll update this later but have been having random crashes on Arch with the official build as well.

At least one of the crashes is with the same error message.

**Comment by zenista** [comment]
i think i have found a temporary solution for now... just comment out the line that says "custom/weather".... and waybar works fine after that. In default config setup... in "modules-right" section the line is at no 32.

**Comment by zsolt-donca** [comment]
> i think i have found a temporary solution for now... just comment out the line that says "custom/weather".... and waybar works fine after that. In default config setup... in "modules-right" section the line is at no 32.

Thank for the hint of looking into the modules. Even though I also have "custom/weather", the troublemaker in my case is not that, but ["custom/waybar-mpris"](https://git.hrfee.pw/hrfee/waybar-mpris). This module is of return type JSON, and the exec command (`waybar-mpris --position`) apparently sometimes returns an invalid json:
```
Couldn't dial socket, deleting instead: dial unix /tmp/waybar-mpris.sock: connect: connection refused{}
```
When it works, I guess it just returns empty JSON object `{}` (or non-empty, depending on whether I something play).

While this seems to be a bug in the custom module itself (which I will report), I guess waybar should also better handle invalid JSON messages and not just crash.

**Comment by zsolt-donca** [comment]
waybar-mpris returning the error message on the standard output was fixed already: https://git.hrfee.pw/hrfee/waybar-mpris/issues/6

I guess what's remaining here is a more robust error handling in Waybar for custom modules of JSON type.

**Comment by Ranguvar** [comment]
I think in my case this was caused by custom/media.

After disabling it, no crashes so far for hours.

**Comment by jallbrit** [comment]
I was having this issue starting with even the default config, and it keeps popping up seemingly randomly. I can sometimes hunt down an individual line in the config that causes it, but I don't understand what's happening.

**Comment by jasperjonker** [comment]
I'm having this issue as well randomly and receive the same error message. Will run it now without the custom weather app and update if it's any better

**Comment by Ranguvar** [comment]
Getting this again often despite no change to the package or config

This is with both waybar 0.9.9-1 and waybar 0.9.9-2 from Arch's repository

May try to get a stack trace or such, any tips appreciated
