### ISSUE TITLE
intermittent crash caused by backlight module

### ISSUE THREAD

**Issue by qubidt** [Alexays/Waybar#1409]
Occasionally (every couple of hours), I am getting this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ptr was null
```

Stack trace:
```
Stack trace of thread 16139:
#0  0x00007f1282ddfd22 raise (libc.so.6 + 0x3cd22)
#1  0x00007f1282dc9862 abort (libc.so.6 + 0x26862)
#2  0x00007f128318a802 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x99802)
#3  0x00007f1283196c8a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa5c8a)
#4  0x00007f1283196cf7 _ZSt9terminatev (libstdc++.so.6 + 0xa5cf7)
#5  0x00007f1283196f8e __cxa_throw (libstdc++.so.6 + 0xa5f8e)
#6  0x000055c0f9e9c61d check_nn (waybar + 0xd361d)
#7  0x000055c0f9e9c776 _ZN6waybar7modules9Backlight17enumerate_devicesIN9__gnu_cxx17__normal_iteratorIPNS1_12BacklightDevESt6vectorIS5_SaIS5_EEEESt20back_insert_iteratorIS9_EEEvT_SD_T0_P4udev (waybar + 0xd3776)
#8  0x000055c0f9e9b05d _ZZN6waybar7modules9BacklightC4ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN4Json5ValueEENKUlvE_clEv (waybar + 0xd205d)
#9  0x000055c0f9e0cc61 _ZNKSt8functionIFvvEEclEv (waybar + 0x43c61)
#10 0x00007f12831c43c4 execute_native_thread_routine (libstdc++.so.6 + 0xd33c4)
#11 0x00007f1282f7a259 start_thread (libpthread.so.0 + 0x9259)
#12 0x00007f1282ea15e3 __clone (libc.so.6 + 0xfe5e3)
```

i.e. this block of code:
https://github.com/Alexays/Waybar/blob/96caa9f094f26755217156a77f4d5bf4a46ce91b/src/modules/backlight.cpp#L208-L217

---

For the record, I am using the brightness module with [ddcci-driver-linux](https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/)

**Comment by AustralEpitech** [comment]
Same problem here, I use [ddcci-driver-linux](https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/) on Fedora Rawhide
After a few hours, the bar crashes with this message:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  ptr was null
`

**Comment by qubidt** [comment]
Been using this fix for about 20 hours now and my bar hasn't crashed yet (it usually would crash a dozen times or so in that timespan). I should've thought to log it as a warning tho. oh well
