### ISSUE TITLE
Error while istalling Waybar on fedora using sudo make install

### ISSUE THREAD

**Issue by GeoDerp** [Alexays/Waybar#141]
This is what it spitted out in the /home/(username)/Waybar/build/meson-logs/meson-log.txt while running the make install on fedora 29 workstation, any ideas ?

```
Determining dependency 'wayland-client' with CMake executable '/usr/bin/cmake'
Try CMake generator: auto
Called `/usr/bin/cmake --trace-expand -DNAME=wayland-client .` in /home/(username)/Waybar/build/meson-private/cmake_wayland-client -> 0
Dependency wayland-client found: NO (tried pkgconfig and cmake)

meson.build:36:0: ERROR:  Dependency "wayland-client" not found, tried pkgconfig and cmake

```

**Comment by Alexays** [comment]
You need a wayland environment, are you on sway or wlroots based compositor?

**Comment by Alexays** [comment]
Otherwise you need these following depencies:
```
gtkmm3
jsoncpp
libinput
libsigc++
wayland
wlroots
libpulse [Pulseaudio module]
libnl [Network module]
sway [Sway modules]
libdbusmenu-gtk3 [Tray module]
```

**Comment by GeoDerp** [comment]
> You need a wayland environment, are you on sway or wlroots based compositor?

I am using sway

**Comment by jeefberkey** [comment]
Sway from the fedora repos is too old, you have to compile from source.

**Comment by GeoDerp** [comment]
> Sway from the fedora repos is too old, you have to compile from source.

GRATE, after doing the painstaking process of compiling sway I successfully installed waybar.

I now get this error when running waybar, any ideas?
```
Resources files: /home/(username)/.config/waybar/config, /home/(username)/.config/waybar/style.css
Failed to acquire required resources
```
I already have an config and style.css file in the dir with the defult configs

**Comment by c-edw** [comment]
If you're struggling to build Sway, feel free to check out some of these resources I created:

- [Fedora 29 Sway Dockerfile](https://gist.github.com/c-edw/24ea239084f7d68f7528bde341f8a4f1)
- [Development Setup](https://github.com/swaywm/sway/wiki/Development-Setup)
