### ISSUE TITLE
Feature Suggestion: Backlight Scroll

### ISSUE THREAD

**Issue by Agvantibo** [Alexays/Waybar#1411]
Hello. The backlight module is nice, but there is no scroll by default. This is easily fixable by creating a helper script  like so:
```fish
#!/bin/fish
set backlight_device $argv[1]
set action $argv[2]
set dvalue $argv[3]

echo Backlight device: $backlight_device Bumping: $action By: $dvalue

set current_value (cat $backlight_device)

if test $action = up
    echo (math $current_value + $dvalue) > $backlight_device
else if test $action = down
    echo (math $current_value - $dvalue) > $backlight_device
else
    exit 2
end
```
And prepending the module config with somthing like
```json
        "interval" : 0.2,
        "device": "intel_backlight",
        "on-scroll-down": "backlight_delta /sys/class/backlight/intel_backlight/brightness down 50",
        "on-scroll-up": "backlight_delta /sys/class/backlight/intel_backlight/brightness up 50",
```
You are unable to see it from the screencast, but the level is actually changing: 
https://mega.nz/file/ubgk1baZ#01vxMsjlZ4KRBI_weng8qg7SrIG7xHbCeNupLXd5xv0
It is probably even possible to minify/hardcode some stuff and make an easily insertable oneliner

**Comment by Agvantibo** [comment]
There, I've recorded an unsettlingly lo-fi demo if the script in action: https://mega.nz/file/yOwGzDiQ#Y30rIKgcIldKcDUbPnC6bXYP6kYQxsUrwXpgrXp-zuA

**Comment by LukashonakV** [comment]
Waybar v0.9.12
`"on-scroll-up": "exec light -A 4",
        "on-scroll-down": "exec light -U 2"`
works perfect
