### ISSUE TITLE
Adding a function to select the audio source to display in the pulseaudio module

### ISSUE THREAD

**Issue by TAforever** [Alexays/Waybar#1415]
I'm using EasyEffects and when some music application starts, the pulseaudio module outputs the volume percentage from EasyEffects and not from Analog stereo. I change the volume with a hotkey, the volume changes, but is not displayed in the module, since I change the Analog stereo, and it outputs easyeffect_sink.

**Comment by frap129** [comment]
See issue https://github.com/Alexays/Waybar/issues/1347
