### ISSUE TITLE
Network not showing proper data in 0.9.9

### ISSUE THREAD

**Issue by droc12345** [Alexays/Waybar#1420]
Using latest git

Network used to show [iface dn up] with iface either eth0 (always visible) or tun0 (only when vpn turned on)
Now, I see both interfaces buttons (even though tun is not active) showing and only "lo" printed in both, no other data.
And "lo" is not in the config file.

commit  d9b5c2595a08e481520d96d7ee30daab4ac07f1b was fine

commit d22d6a45222ebc1b6b060a1a45f2405d0d47ecfc shows the problem.
(It's still there a/o 12caae8fd244b212b6f776e50f2ea085edafc943)

Edit to add: 
I do have network and network#tun modules, and the tun is set with format disconnected, 
so not sure if that's part of the problem.

Edit to add 2: 
using fmt 7.1.3 if it makes a difference, haven't tested with ver 8.

**Comment by droc12345** [comment]
Found out what the problem is (for me).
There was a change between tag 0.98 and 0.99 that caused the problem.

src/modules/cpp line 81 want_route_dump was changed from false to true, changing it back fixed the issue.

I think they changed it to true because you don't get bandwidth data until the first refresh.
But something else evidently doesn't like it being true, when waybar is started, I haven't chased it down any further than that.

This could be closed, but I'll leave it for now to let others know about the problem

**Comment by bd-g** [comment]
This is bundled up with a lot of the issues raised in #1392. There was an update to the network module that was needed for more granularity in up/down bits, but a few issues have been raised.

**Comment by droc12345** [comment]
This is fixed, so I'll close this
