### ISSUE TITLE
Wrong wording in PulseAudio section of documentation

### ISSUE THREAD

**Issue by Pound-Hash** [Alexays/Waybar#1424]
In the [docs](https://github.com/Alexays/Waybar/wiki/Module:-PulseAudio), the word _until_ should be changed to _since_. _Until_ means that the feature was **discontinued** with version `0.9.0`, but I'm using `0.9.9` and the feature works. See attached screenshot.

![20220205_14h53m53s_grim](https://user-images.githubusercontent.com/51193876/152661723-54530cb1-1977-41fd-a161-39366e484b5c.jpeg)

**Comment by Alexays** [comment]
You can update the doc :)
