### ISSUE TITLE
Clock shows tooltip despite ("tooltip": false,)

### ISSUE THREAD

**Issue by Pound-Hash** [Alexays/Waybar#1425]
The clock's tooltip continues to appear even though I disabled it.

Config:
```
    "clock": {
		"tooltip": false,
    },
```

- Waybar 0.9.9-1

**Comment by opalvault** [comment]
Can confirm, tooltip still shows up when "tooltip" is false on v0.9.9

**Comment by asahaf** [comment]
tooltip still shows up when "tooltip" is false, even on v0.9.9

**Comment by LukashonakV** [comment]
> tooltip still shows up when "tooltip" is false, even on v0.9.9

Waybar v0.9.12 - is not reproduced. Behavior is correct

**Comment by asahaf** [comment]
The issue was fixed already

**Comment by LukashonakV** [comment]
Hi @Pound-Hash, if the issue is solved can you close it please?
