### ISSUE TITLE
Typo in the Battery's documentation

### ISSUE THREAD

**Issue by Pound-Hash** [Alexays/Waybar#1427]
The [docs](https://github.com/Alexays/Waybar/wiki/Module:-Battery) state, `format | string | {capacity}% | The format, how the time should be displayed`, but this format displays the _capacity_, not the _time_.

If you like, I can submit pull requests for mistakes in the docs. I'm an English teacher; I can help with English mechanics as well.

**Comment by Alexays** [comment]
Of course go ahead if you have some time to help us!
