### ISSUE TITLE
Indicate in the wiki, how to adjust the configuration of sway

### ISSUE THREAD

**Issue by oliverpool** [Alexays/Waybar#143]
First of all great project!

I had a hard time figuring out how to configure sway (i.e. edit the `sway/config` file):

According to #111, one should use:

```
bar {
    swaybar_command waybar
}
```

For https://github.com/Alexays/Waybar/issues/44#issuecomment-450026960, it is apparently:

```
exec waybar
```

What is the official way?
Could it be documented somewhere on the wiki?

thanks!

**Comment by Alexays** [comment]
There is no official way, both works good, i'll put both ways in the wiki to help people.
