### ISSUE TITLE
font awesome icons in workspace names are too small

### ISSUE THREAD

**Issue by eoli3n** [Alexays/Waybar#1433]
```bash
$ sway --version
sway version 1.7

$ waybar --version
Waybar v0.9.9
```
Sway config: https://github.com/eoli3n/dotfiles/blob/master/roles/sway/templates/config.j2#L100-L109
Waybar config: https://github.com/eoli3n/dotfiles/blob/master/roles/waybar/templates/style.j2

### Before
![before](https://user-images.githubusercontent.com/14223657/153415312-c186762d-0c40-4ddf-bbad-cfb58c21a6c7.png)

### After
![sway](https://user-images.githubusercontent.com/14223657/153414880-16889e8f-592b-4fc1-9ded-6d3ee99bb30f.png)

It look like twice tinier than before without changing any config.
I can't find why, any idea ?

**Comment by eoli3n** [comment]
oh ! good catch, thanks

**Comment by etrnal70** [comment]
From the discurrsion in https://github.com/greshake/i3status-rust/issues/1428, looks like changing font name from `Font Awesome 5 Free` to `Font Awesome 6 Free` fixed the issue. But while the font icons are back to normal, the font character looks bigger and ugly

![image](https://user-images.githubusercontent.com/5826834/153528459-fd7f062b-0439-4211-b6b1-e04c8f43c424.png)

**Comment by eoli3n** [comment]
actually, ionicons is even worse, all icons are small too, and finding icons in the font is pretty hard without a unicode cheatsheet
