### ISSUE TITLE
Feature request: add on-click for sway/language

### ISSUE THREAD

**Issue by Artturin** [Alexays/Waybar#1438]
then we could set it to `swaymsg input type:keyboard xkb_switch_layout next` to switch to the next layout

**Comment by Alexays** [comment]
It should already be possible

**Comment by Artturin** [comment]
i didn't see it in the manpage or the wiki so i didn't know
i now added it to the wiki page https://github.com/Alexays/Waybar/wiki/Module:-Language
still needs to be added to the manpage
