### ISSUE TITLE
Waybar fails to start (sometimes)

### ISSUE THREAD

**Issue by keshto** [Alexays/Waybar#1439]
Sometimes fails to start with.
```
 ** (waybar:1124): ERROR **: 15:28:13.348: 
 unhandled exception (type std::exception) in signal handler:
 what: Type is not convertible to string
```

**Comment by OctopusET** [comment]
https://github.com/Alexays/Waybar/issues/1381#issuecomment-1036397686

This might be related. I got same error message.

**Comment by krisman** [comment]
I'm also observing this on v0.9.9 (debian package 0.9.9-1).  Removing the '{calendar}' reference in tootip-format fixes it for me too.

Any idea what this {calendar} formatting is for?  I only found a few references to it on the wiki but it is still to clear to me.

**Comment by droc12345** [comment]
"<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
Bigger font, year and month, 
tt monospace font
{calendar} is current month, done with smaller font
Pango markup (if I remember right)

I personally haven't had problems with the calendar line, but here are some things that might affect using it
gtk+ version (should use gtk3 not 4)
libfmt version
gtk-layer-shell version
and of course, xwayland, wayland and protocols and wlroots versions.

**Comment by jonmast** [comment]
I had a similar issue, replacing `%l` with `%I` in my time format fixed it for me (both 12hr format, `%I` is zero padded).
