### ISSUE TITLE
Window title (sway/window) styling for inactive screen

### ISSUE THREAD

**Issue by funcrab** [Alexays/Waybar#1448]
I have made the following settings in `style.css`.
Is there any way to stop the window title decoration that is done on inactive screen?

```
#window {
    font-weight: bold;
    color: black;
    background-color: gold;
    border-radius: 10px;
    padding-left: 10px;
    padding-right: 10px;
}
```

Window title of active screen:
![active](https://user-images.githubusercontent.com/55499652/156377922-fe4f6e52-611b-48ea-a624-eec1edbdc540.png)

Window title of inactive screen:
![inactive](https://user-images.githubusercontent.com/55499652/156377984-6dbee60d-2c85-4bc6-89ab-dc9c29fd35c8.png)

config:
```
    "modules-center": [
        "sway/window"
    ],
```

**Comment by Alexays** [comment]
See #1403

**Comment by Alexays** [comment]
```
#window.empty {
  display: none;
 }
 ```

**Comment by funcrab** [comment]
Thanks. But unfortunately it doesn't seem to work.
```
[2022-03-08 20:58:19.181] [error] style.css:244:9'display' is not a valid property name
```

**Comment by funcrab** [comment]
The following did not change the display
```
window#waybar.empty {
    color:            black;
    background-color: black;
    border-radius:    0px;
    padding-left:     0px;
    padding-right:    0px;
}
```

**Comment by funcrab** [comment]
If you are referring to window#waybar.empty, I'm wondering if this is not an inactive workspace, but a workspace without a single window?
https://github.com/Alexays/Waybar/wiki/Module:-Sway#window

Looking at the Wiki, it doesn't seem like there is an inactive style format yet

**Comment by mgoral** [comment]
Hi, @Alexays, @funcrab.

The hint with setting `display: none` for `#window` doesn't work because of the reason given by @funcrab. I had the same problem though and fixed it this way:

```
#waybar.empty #window {
    background: none;
}
```

Hope it helps! :)

**Comment by funcrab** [comment]
@mgoral Works perfectly. I'm glad, Thank you!

Window title of active screen:
![image](https://user-images.githubusercontent.com/55499652/160082892-d2ec3c8c-8142-42d4-91a6-2641582d4c99.png)

Window title of inactive screen:
![image](https://user-images.githubusercontent.com/55499652/160083236-0de1bcc8-3f65-47a9-bfd8-433c586a96c8.png)

style.css
```
#waybar.empty #window {
    background: none;
}
```

**Comment by funcrab** [comment]
I wrote it in the Wiki.
https://github.com/Alexays/Waybar/wiki/Module:-Sway
![image](https://user-images.githubusercontent.com/55499652/160086470-47bba7c9-0271-4494-bc7a-da5f990be23f.png)
