### ISSUE TITLE
Feature Request: easier access to more info on network module

### ISSUE THREAD

**Issue by oliverpool** [Alexays/Waybar#145]
Hi,

Here is my use-case:
> I'm usually connected via wifi and I like always seeing the essid of the network I'm currently connected too. Sometimes I also need to access my local IP-Address (but not often enough to waste the space of the bar).

I see 2 possibilities to fix this (implemented in other modules):
- support `format-alt` so that a click toggles my IP-Address (as in the clock module)
- add a tooltip (along with other infos) (as in the CPU module)

I would personally prefer the `format-alt` solution (more flexibility regarding the info to display), but from a first glance at the code, it seems a bit harder to implement.

I would be ready to start a PR with one of those solutions (or both maybe !), after having some feedback about this proposal :-)

**Comment by Robinhuett** [comment]
You can use `format-alt` on the network module. In fact, you can use it on any module

**Comment by oliverpool** [comment]
The network module is probably the only one, where I can't get `format-alt` to work :-(

Looking at the [code](https://github.com/Alexays/Waybar/blob/ad638357b5fb0387c2e8a5163306a6b6d0b32470/src/modules/network.cpp#L110), the `format` property is overwriten on `update`, so the `alt` is not visible

**Comment by Robinhuett** [comment]
Could you please post your config? I just tested it and it works flawlessly here :)

**Comment by Alexays** [comment]
@oliverpool We agree, format-alt works but not indefinitely, right?

**Comment by oliverpool** [comment]
On my computer (currently connected to wifi), I can't get it to work at all (it works fine on the clock module).

Waybar v0.2.3 (installed from AUR)
```
    "network": {
        // "interface": "wlp2s0", // (Optional) To force the use of this interface
        "format-wifi": " {essid} <small>{signalStrength}%</small>",
        "format-ethernet": " {ifname}: {ipaddr}/{cidr}",
        "format-disconnected": "⚠ Disconnected",
        "format-alt": "alt"
    },
```

**Comment by oliverpool** [comment]
If I comment `"format-wifi"`, then the `alt` works fine!
