### ISSUE TITLE
stop zero-filling in the clock

### ISSUE THREAD

**Issue by funcrab** [Alexays/Waybar#1452]
Thanks for the cool gear.

This is not a bug report, but a request.

Now it's "invalid format" and I can't use it.
Is there any way to use padding like the following date command?

```
$ date +"%-m/%d(%a)%-H:%M"
3/06(Sun)8:37
$
```
Currently, only those with the following zero-fillings appear to be available.

```
$ date +"%m/%d(%a)%H:%M"
03/06(Sun)08:38
$
```

**Comment by funcrab** [comment]
If this is the same problem as #1447, please feel free to close it.
I downgraded to V0.9.9-1 and was able to display the following.
```
"format": "{:%-m/%d(%a)%-H:%M}",
```

**Comment by Alexays** [comment]
Dups of https://github.com/Alexays/Waybar/issues/1447
