### ISSUE TITLE
Network module matches the wrong interface

### ISSUE THREAD

**Issue by gnull** [Alexays/Waybar#1455]
I'm using Waybar version `r1833.383d999-1` (built from AUR). Since I upgraded to this version, the network module fails to match my eth0 interface. In my config I have

```
    "network#eth0": {
        "interface": "eth0",
        "format": " {ipaddr}",
        "tooltip-format": "↓{bandwidthDownOctets} ↑{bandwidthUpOctets}",
        "format-disconnected": " ",
        "format-disabled": "  off",
    },
```

But the IP address shown in waybar comes from the interface `wwp0s20u4` (my 4G LTE interface).

Is this a bug?

**Comment by 1995parham** [comment]
I have the same issue, I think this is a bug.

**Comment by gnull** [comment]
In case this helps debugging: the wlan0 interface is matched correctly for
me. For some reason it mismatches only eth0. And the bug is very stable, I
see the same result all the time, doesn't seem to depend on any temporal
factors.

**Comment by 1995parham** [comment]
Yes exactly it is always show me the same interface and also wildcard is not working for me

**Comment by BoostCookie** [comment]
Changing https://github.com/Alexays/Waybar/blob/383d999fec4ccff37b57cecc8c99aa609df2e12b/src/modules/network.cpp#L81 back to `want_route_dump_(false),` fixes it for me.
According to git blame this change was introduced with https://github.com/Alexays/Waybar/commit/e10c9dd011e394b734be7bab6fc2ca6885f9de1f.
The commit message even says
> changing want_route_dump to default to true, since we say we have gwaddr support
Maybe the author of this commit @mazunki can elaborate why this was changed?

**Comment by mazunki** [comment]
> Changing
> 
> https://github.com/Alexays/Waybar/blob/383d999fec4ccff37b57cecc8c99aa609df2e12b/src/modules/network.cpp#L81
> back to `want_route_dump_(false),` fixes it for me.
> According to git blame this change was introduced with [e10c9dd](https://github.com/Alexays/Waybar/commit/e10c9dd011e394b734be7bab6fc2ca6885f9de1f).
> The commit message even says
> 
> > changing want_route_dump to default to true, since we say we have gwaddr support
> 
> Maybe the author of this commit @mazunki can elaborate why this was changed?

I changed `want_route_dump_()` to get the values for `gwaddr` loaded at all. Without it, after some update, it didn't seem to fetch the routes.

My guess is that the dump, while required if we're using `gwaddr`, should only dump the interface we're looking for. It's probably taking whatever it can find right now. What was the initial reason that function existed, and why did it default to false initially?

When changing it, I didn't realize it would match the wrong device. I can take a further look this weekend.

**Comment by droc12345** [comment]
https://github.com/Alexays/Waybar/issues/1420 also references this problem/bug.

In my case, it always showed the lo (local) interface with no data, changing it from true back to false makes it work the way it was, as far as this issue is concerned.

A comment, by me, from that post.
> I think they changed it to true because you don't get bandwidth data until the first refresh.
But something else evidently doesn't like it being true, when waybar is started, I haven't chased it down any further than that.

**Comment by BoostCookie** [comment]
So yes, this is fixed now for me and can be closed in my opinion.
