### ISSUE TITLE
Crash at startup with "Type is not convertible to string"

### ISSUE THREAD

**Issue by hikkidev** [Alexays/Waybar#1457]
I've installed arch linux and got this exception. It seems a missing package.

![out](https://user-images.githubusercontent.com/52655010/156958403-87bca19e-ddd9-45cc-b94a-c954072984d2.jpg)

Here are all the installed packages:
[pkglist.txt](https://github.com/Alexays/Waybar/files/8194336/pkglist.txt)

P.S. If I remove the `clock#format`, it will work fine.

**Comment by Ranguvar** [comment]
Upgrade waybar to 0.9.10-1, I believe it's fixed there

#1451

**Comment by hikkidev** [comment]
Fixed.

> Upgrade waybar to 0.9.10-1, I believe it's fixed there
> 
> #1451
