### ISSUE TITLE
Possible to change the icon size of app icon in sway/window module?

### ISSUE THREAD

**Issue by Hikandy** [Alexays/Waybar#1461]
It looks like it was recently added in the latest update. As much as how nice the feature is the icon seems quite big for my bar and is kinda uneven, is it possible to change its size so that it fits with other icons

**Comment by mefromthepast** [comment]
Also consider that there are icons with difference size (e.g. sublime-text seems to have a larger icon), which leads to waybar changing its size as soon as sublime gets focused.

**Comment by Alexays** [comment]
@FlexW maybe you can give a shot if you have time? :)

**Comment by FlexW** [comment]
@Alexays I will try to work on it on the weekend.

**Comment by seabassapologist** [comment]
![waybar_icons](https://user-images.githubusercontent.com/1698705/157337999-65504533-ebb5-419c-9ba0-ea42481776ef.png)

Not sure if this needs it own issue or not, but is it possible to change the padding around just the icons? I like the size, but the icon is little bit off-center from the bottom border and the top of the bar

**Comment by RobertMueller2** [comment]
I think it would be good if the image somehow was CSS identifiable.

Right now, only the label gets the name passed to AIconLabel. Perhaps even the whole box could get that, although that would certainly break existing styles as well as consistency with ALabel.

![swappy-20220312_104523](https://user-images.githubusercontent.com/29629287/158013066-912dd7b4-c44e-48a6-98d1-8573c3f3a357.png)
