### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Sigmw** [Alexays/Waybar#1462]
waybar crashes and gives segmentation fault when I change workspace too fast
some errors here:
![image](https://user-images.githubusercontent.com/89428643/157108706-ab3a09d2-7518-4db9-9fd6-3fc128a77222.png)
![image](https://user-images.githubusercontent.com/89428643/157108851-e5ce633c-fdf8-4901-820c-7a030c649d43.png)
![image](https://user-images.githubusercontent.com/89428643/157108943-d174535d-f90d-4d4d-a6c7-b017e991b7cf.png)

**Comment by Alexays** [comment]
Can you try disabling icon in sway/window module?

**Comment by Sigmw** [comment]
where is?

**Comment by LordRishav** [comment]
@Sigmw In .config/waybar/config
```json
    "sway/window": {
        "icon": false,
    },
```

**Comment by Sigmw** [comment]
thats solved 😄

**Comment by p00f** [comment]
Can you please reopen this - disabling icon is a workaround, not a fix

**Comment by Sigmw** [comment]
> Can you please reopen this - disabling icon is a workaround, not a fix

Unbelievably this solved and made it my waybar more beautiful

**Comment by p00f** [comment]
Yes but waybar still crashes if the icon is not disabled

**Comment by Sigmw** [comment]
> Yes but waybar still crashes if the icon is not disabled

I really dont care, i will not use icons

**Comment by Sigmw** [comment]
> Yes but waybar still crashes if the icon is not disabled

I really dont care, i will not use icons

**Comment by setpill** [comment]
> Can you please reopen this - disabling icon is a workaround, not a fix

Opened a new issue to track this.
