### ISSUE TITLE
How to disable icon on bar?

### ISSUE THREAD

**Issue by tmpm697** [Alexays/Waybar#1465]
I had open an issue here: https://github.com/alacritty/alacritty/issues/5939

But it seems `waybar` try to display the `alacritty`'s icon instead of from `alacritty` itself.

![image](https://i.imgur.com/AWqCoH9.png)

How can I remove/disable displaying icon on bar? (center one, as I had workspace and window around)

**Comment by FlexW** [comment]
You can set the `icon` property of `sway/window` to `false`. Take a look at the man. https://github.com/Alexays/Waybar/pull/1459/commits/50fc63b749288d03e6d31fc6ea6e730a8357da08#

**Comment by tmpm697** [comment]
thanks, but should it off by default? as i don't observe this issue before (so i believe it's not enabled previously)

**Comment by tsdh** [comment]
I use 0.9.10 where `waybar-sway-window(5)` doesn't list an `icon` property.  I run that version with the same config on two machines and on one, icons are shown for some windows (foot, emacs but not firefoxdeveloperedition) and on the other they are not shown.  Config is:

```json
    "sway/window": {
        "format": "{}",
        "tooltip": false,
        "max-length": 50
    },
```

Is there some requirement to make icons show up?

**Comment by tsdh** [comment]
@tmpm697 Yeah, my question was not really about the missing manpage entry but rather why on two machines with 0.9.10 and identical up-to-date distros and configs, icons show up only on one machine (and even then not for all windows).

**Comment by tmpm697** [comment]
`0.9.10-1` latest from archlinux repo doesn't have `icon` enabled. build both from `-git` would work.

**Comment by tsdh** [comment]
@tmpm697 Well, but I do have icons on one machine with that exact version.  AFAICS, icons are enabled in that version, it's just that the man-page didn't document the `icon` property.  But I guess that's not really the point of this issue.  I'll open a new one.
