### ISSUE TITLE
Inconsistent icon sizes for Sway Window module

### ISSUE THREAD

**Issue by GrantMoyer** [Alexays/Waybar#1470]
It looks like icons just use whatever size the image is in the Sway Window module (and probably any AIconLabel). Instead, they should be scaled to a standard size, or there should be a config option to do so.

Extreme example:

![icon_sizes](https://user-images.githubusercontent.com/6333127/157365653-5750bb4e-bec8-4867-bc0c-46c32ce151d8.gif)

**Comment by GrantMoyer** [comment]
somehow I missed #1461 when submitting this.

**Comment by Alexays** [comment]
Yep dups of #1461
