### ISSUE TITLE
Show invisible and occupied workspace for sway.

### ISSUE THREAD

**Issue by ahmadraniri1994** [Alexays/Waybar#1472]
Is that possible ? If this have been asked before, feel free to close it. Thanks.

**Comment by tmpm697** [comment]
Does it because `sway` only show workspaces that contain windows? Then `waybar` has nothing to do with.

**Comment by ahmadraniri1994** [comment]
Well, other bar seems able to do it (e.g yambar), I tried tho. So, waybar doesn't have such configurations for it yet.

**Comment by RobertMueller2** [comment]
Have you tried the persistent_workspaces setting?

**Comment by ahmadraniri1994** [comment]
> Have you tried the persistent_workspaces setting?

That's not what I want to achieve, I'll post a picture to describe it.

**Comment by lidgnulinux** [comment]
So, it's yambar, I want to achieve something like this, for example workspace one where some windows opened but unfocused and workspace 3 with window and focused and the rest is from persistent workspace. Waybar just have persistent workspace, visible, and focused for style, but waybar doesn't have something like unfocused.
![2022-03-13T05:36:17,783757583+07:00](https://user-images.githubusercontent.com/99301306/158037396-55d38240-95b9-4545-9841-c391097cd299.png)

**Comment by ahmadraniri1994** [comment]
> So, it's yambar, I want to achieve something like this, for example workspace one where some windows opened but unfocused and workspace 3 with window and focused and the rest is from persistent workspace. Waybar just have persistent workspace, visible, and focused for style, but waybar doesn't have something like unfocused. ![2022-03-13T05:36:17,783757583+07:00](https://user-images.githubusercontent.com/99301306/158037396-55d38240-95b9-4545-9841-c391097cd299.png)

Sorry, It's my second GitHub account.

**Comment by lgaboury** [comment]
Try the following.  In your waybar config, use:
```
    "sway/workspaces": {
        "disable-scroll": true,
        "persistent_workspaces": {
            "1": [],
            "2": [],
            "3": [],
            "4": [],
        },
    },
```

and in your style.css, use:
```
#workspaces button {
    transition: none;
    color: white;
    background: transparent;
    padding: 5px;
    font-size: 18px;
}

#workspaces button.persistent {
    color: yellow;
    font-size: 12px;
}

#workspaces button.focused {
    color: lightgreen;
}
```

![2022-09-04T12:05:41,109285935-05:00](https://user-images.githubusercontent.com/50297059/188325110-fd6f3bc2-6f41-4a6c-9a2e-84c10d2c2579.png)

* Large green number:  indicate focused workspace with or without opened window(s).  Note: being focused, it enables you to see if the workspace has opened windows.  
* Large white number: indicate unforcused workspace(s) with opened window(s).
* Small yellow number: indicate unforcused workspace(s) without opened window.  
Not exactly what you are looking for but does the trick for me. Simply adjust the styles as you see fit and add persistent workspaces for your requirement.
