### ISSUE TITLE
Enabling icons causes segfaults

### ISSUE THREAD

**Issue by setpill** [Alexays/Waybar#1474]
### Some logs:

![image](https://user-images.githubusercontent.com/37372069/157622961-4b015b79-3a6b-48d9-8867-fe1c53db1fca.png)

![image](https://user-images.githubusercontent.com/37372069/157623022-efce0028-125d-413d-9bda-29f7871c1045.png)

![image](https://user-images.githubusercontent.com/37372069/157623083-ee86be8f-b4ca-4ed4-a163-a1fdc8736dc7.png)

### Temporary workaround:

```
    "sway/window": {
        "icon": false,
    },
```

### Additional context

See https://github.com/Alexays/Waybar/issues/1462

Original reporter considers the workaround good enough for his usecase; opening a new issue to track the underlying cause.

**Comment by Alexays** [comment]
Icon is now disabled by default on latest version

**Comment by LordRishav** [comment]
I have been using Waybar with sway/window icons enabled for 3 days constantly now and I haven't seen any crashes yet (which were **much** more frequent more than a month back when the original issue was filed). Is there an update on this?
