### ISSUE TITLE
Feature request: hide tooltip

### ISSUE THREAD

**Issue by trobjo** [Alexays/Waybar#148]
I'd would like to be able to hide the tooltip as only find it annoying. 

E.g. if I accidentally move my cursor to the top center where the title of the current active window is, it will change to 'waybar'. This new title is too short to be under the cursor, thus it becomes inactive and focus switches to my previous window. Now the focus of my cursor is the title of waybar again, and it will switch back to 'waybar'. This creates a rapid back-and-forth in active window state, which manifests itself as a flickering screen.

**Comment by Arnaudv6** [comment]
#172 duplicate?

**Comment by Alexays** [comment]
Done in 83a6475510df2c3db325c6ba24b377858b487ca5
Just set in each module `"tooltip": false`
