### ISSUE TITLE
Module spacing configuration

### ISSUE THREAD

**Issue by mnussbaum** [Alexays/Waybar#149]
Thanks for all your work on waybar, I'm really enjoying its feature set and customizability!

I've looked through the wiki and old issues and haven't found any info, but apologies if I've overlooked something. Is it possible to eliminate the gap areas between modules? In the screen shot below I'd like to make the colored blocks continuous without the dark gaps between the modules. Thanks for your help!

![image](https://user-images.githubusercontent.com/473482/51372912-943cee00-1ab3-11e9-8c36-1ea9ef5b3540.png)

**Comment by trobjo** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/26080212/51373938-c37a4c00-1b01-11e9-8b5e-3d76d6841fb0.png)

Have a look at my config:
https://transfer.sh/7G5QR/styleDark.css
~ $

**Comment by mnussbaum** [comment]
:100: thanks for the pointer!

**Comment by hughwilliams94** [comment]
As this link is dead the question should be reopened until the info contained within it is available
