### ISSUE TITLE
No context menus opening on clicking tray icons

### ISSUE THREAD

**Issue by itsKia2** [Alexays/Waybar#1494]
Running riverwm on Arch Linux, I recently installed waybar and setup the configuration. Everything else seems to be running fine, however when I start an applet, such as nm-applet --indicator or blueman-applet, they show up on the systray however do not show any context menus or options when clicked on (neither of the 3 buttons work). All applications are up to date and I have libappindicator-gtk3 installed as well.

tested with discord as well, no reaction to my clicking on discords tray icon either.
Tray section in config file is attached below.
```
     "tray": {
        "icon-size": 19,
        "spacing": 10
   },
```

**Comment by hochata** [comment]
I also have the same issue. Works well under Sway, but no context menu with River.

**Comment by itsKia2** [comment]
I've found a workaround but not a fix for this issue. Adding the config option `"gtk-layer-shell": false` in the waybar config file seems to open a context menu in the middle of the screen. Inconvenient but provides a menu. Still waiting for a fix so we can use context menus over the actual tray.

**Comment by hochata** [comment]
Ohh, thanks for the workaround! At least is it better than no menu at all.

**Comment by daslastic** [comment]
Why is this not fixed yet?

**Comment by gmr458** [comment]
the same thing happens to me in hyprland

**Comment by daslastic** [comment]
Looks like it is working now :)
Could be a recent river or waybar update.

**Comment by Narice** [comment]
This issue is similar to #1850

**Comment by ticks-tan** [comment]
> I've found a workaround but not a fix for this issue. Adding the config option `"gtk-layer-shell": false` in the waybar config file seems to open a context menu in the middle of the screen. Inconvenient but provides a menu. Still waiting for a fix so we can use context menus over the actual tray.

Good idea, in hyprland with windows rule can be a perfect solution：
`windowrulev2 = move cursor 0 10, class:^(waybar)$, floating:1`

**Comment by itsKia2** [comment]
> This issue is similar to #1850, is the issue on river fixed for you @itsKia2?

Seems to be working now, closing issue. Thanks for all the help
