### ISSUE TITLE
sway-workspaces: can't scroll on inactive monitor when "all-outputs" = false

### ISSUE THREAD

**Issue by rorytm** [Alexays/Waybar#1496]
If you have multiple monitors and only have the workspaces shown on their respective waybars, then you can't use the scroll wheel to change workspace on the inactive monitor(s). 

Setting `all-outputs` to true allows scrolling on all monitors as expected. 

sway version 1.8-dev-ca016689 (Mar 22 2022, branch 'master')
Waybar v0.9.12

**Comment by VAWVAW** [comment]
Still an issue. (waybar v0.9.24)
