### ISSUE TITLE
Clock not updating

### ISSUE THREAD

**Issue by TheCycoONE** [Alexays/Waybar#1497]
Unlike #498 adding an "interval": 30 does not appear to fix my issue. The clock is stuck on the last time shown, unless it is manually refreshed by clicking through the formats.

Other indicators update as expected.

I am using waybar 0.9.12 on archlinuxarm

[config.txt](https://github.com/Alexays/Waybar/files/8367495/config.txt)
[style.css.txt](https://github.com/Alexays/Waybar/files/8367497/style.css.txt)

Perhaps relevant, but when I first boot up my clock is completely wrong, reflecting the previous boot. It gets corrected late boot after waybar is launched, and the intial clock in waybar reflects that time.

**Comment by RobertMueller2** [comment]
Might be similar to what's described in second/third comment in #1226. I think that sleep_until in the clock module is tricked by any sort of system clock adjustment to a time beyond that if it's happening after the module started.

Is your system clock set to local time? Have you considered using UTC?

**Comment by TheCycoONE** [comment]
My system clock is UTC. It seems to be a hardware quirk (this is a rockchip 3399 aarch64 system)

**Comment by TheCycoONE** [comment]
I think this is fixed
