### ISSUE TITLE
Module minimum width

### ISSUE THREAD

**Issue by mnussbaum** [Alexays/Waybar#150]
:wave: I've likely missed a CSS configuration option for this, if so I apologize! I'd like to configure a minimum width for module sections of the bar to prevent them from changing size when e.g. the CPU usage percentage goes from two digits to one. I tried to set a `min-width` property on a span but it seems like GTK doesn't support that property on spans.

Is there any way to get a minimum or otherwise consistent width on module output (or just CPU module output) to prevent frequent resizing of the bar?

Thanks for your help!

**Comment by Robinhuett** [comment]
You should be able to set a `min-width` like this:

```
#clock {
    min-width:  140px;
}
```
