### ISSUE TITLE
network indicator stuck on ethernet disconnect

### ISSUE THREAD

**Issue by huguesb** [Alexays/Waybar#1503]
On my laptop, the network module is correctly showing my wifi or ethernet connection when only a single one of the two is on. If both are on it seems to pick the one with the lowest route metric, as I would expect. However, after disconnecting the ethernet cable while the wifi is on, it stays stuck in a "disconnected" state, instead of reverting to showing wifi status. I have to explicitly mark the ethernet interface as down for waybar to show me the wifi status again, which is not ideal.

This is with waybar 0.9.12 on Arch linux

**Comment by kekkoudesu** [comment]
I have found that explicitly reloading Sway's config file (by default, $mod+shift+c) will force the network module to recognise the wi-fi network is active as another workaround.
