### ISSUE TITLE
Temperature module isn't working well

### ISSUE THREAD

**Issue by luisfscoelho** [Alexays/Waybar#1504]
The temperature module always shows 0°C

![screenshot_2022-04-01-20:54:37](https://user-images.githubusercontent.com/22839492/161355911-a769fd1c-adf0-4c00-9c55-c0e23a11b66d.png)

My `/sys/class/hwmon/hwmon2/temp1_input` shows `36125`

`Waybar v0.9.12`

`sway version 1.7`

`Kernel: 5.17.1-arch1-1`

`Arch Linux`

**Comment by eneshecan** [comment]
I think you need to set `hwmon-path` to `/sys/class/hwmon/hwmon2/temp1_input` in waybar config if that is the correct path for your cpu temp. For me it was `/sys/class/hwmon/hwmon6/temp1_input`.

**Comment by luisfscoelho** [comment]
It works, thank you!

**Comment by Jojol-supra** [comment]
Thanks
