### ISSUE TITLE
Help needed [network module]

### ISSUE THREAD

**Issue by EliaHKM** [Alexays/Waybar#1505]
Hi 🙋🏻,
Could you correct me 

`"network": {
       // "interface": "wlp2*", // (Optional) To force the use of this interface
       "format-wifi": "{essid} ({signalStrength}%) 🌊",
       "format-ethernet": "{ifname}: {ipaddr}/{cidr} 🔗 | {bandwidthUpBits} ⬆️  {bandwidthDownBits}     ⬇️ ",
       "format-linked": "{ifname} (No IP) ⛔",
      "format-disconnected": "Disconnected ✈️",
      "format-alt": "{ifname}: {ipaddr}/{cidr}"

  },`
how can I make the bandwidth working 
it gives 0b/s 
thanks in advance

**Comment by thatLeaflet** [comment]
Same issue. And if I put in {bandwidthUpBytes}, it the module disappears entirely.

**Comment by UltraBlackLinux** [comment]
Whenever I use  format-ethernet together with bandwitdh** I just get an error, that the argument can't be found

**Comment by hboetes** [comment]
bandwidthupbytes does exist. It has a bug.
```
% grep bandwidthUpB
man/waybar-network.5.scd
*{bandwidthUpBits}*: Instant up speed in bits/seconds.

src/modules/network.cpp
      fmt::arg("bandwidthUpBits", pow_format(bandwidth_up * 8ull / interval_.count(), "b/s")),
      fmt::arg("bandwidthUpBytes", pow_format(bandwidth_up / interval_.count(), "B/s")));
          fmt::arg("bandwidthUpBits", pow_format(bandwidth_up * 8ull / interval_.count(), "b/s")),
          fmt::arg("bandwidthUpBytes", pow_format(bandwidth_up / interval_.count(), "B/s")));
```

**Comment by yoogottamk** [comment]
The speed stays 0 initially but starts updating speed after a minute. The `interval` setting is 60 by default.

```jsonc
"network": {
    "interval": 5, // in seconds
    "format-wifi": "{essid} ({signalStrength}%) ocean",
    "format-ethernet": "{ifname}: {ipaddr}/{cidr} link | {bandwidthUpBits} arrow_up {bandwidthDownBits} arrow_down ",
    "format-linked": "{ifname} (No IP) no_entry",
    "format-disconnected": "Disconnected airplane",
    "format-alt": "{ifname}: {ipaddr}/{cidr}"
}
```

**Comment by kooskaspers** [comment]
So the interval gets ignored regarding the {bandwidthUpBits} or {bandwidthUpBytes} variable?

**Comment by kooskaspers** [comment]
Got it. I assigned "1" as an interval, it shoud've been just 1, without quotes (int).

**Comment by kohane27** [comment]
@kooskaspers 
The request for a fixed width for network module is mentioned in [Limit length of modules · Issue #486 · Alexays/Waybar](https://github.com/Alexays/Waybar/issues/486) and the pr: [Add a custom formatter for "pow" numbers. by layus · Pull Request #472 · Alexays/Waybar](https://github.com/Alexays/Waybar/pull/472#issue-320672419)

In short:
```
        "format-wifi": " {bandwidthDownBytes:>4} {bandwidthUpBytes:>4}",
```
and I get a constant fixed by reserving space for it.

**Comment by kooskaspers** [comment]
> @kooskaspers The request for a fixed width for network module is mentioned in [Limit length of modules · Issue #486 · Alexays/Waybar](https://github.com/Alexays/Waybar/issues/486) and the pr: [Add a custom formatter for "pow" numbers. by layus · Pull Request #472 · Alexays/Waybar](https://github.com/Alexays/Waybar/pull/472#issue-320672419)
> 
> In short: `"format-wifi": " {bandwidthDownBytes:>} {bandwidthUpBytes:>}",` and I get a constant fixed by reserving space for it.

Tested, and working great! Thanks.
