### ISSUE TITLE
Battery plugin updates weirdly

### ISSUE THREAD

**Issue by jonas-w** [Alexays/Waybar#1506]
I have set the interval of the module to something crazy like 1.
After i plug in the power cord it displays the power cord icon:
![image](https://user-images.githubusercontent.com/32615971/161442080-2f6a9bc7-d6e1-420c-9617-ac98c4fa5883.png)
And only after a few seconds it gets the "charging" label (for css).

Why is it that the icon directly shows up after plugging in but the charging class gets inserted with a delay?

**Comment by matejdro** [comment]
Is this supposed to be fixed? It was closed so suddenly without explanation. 

I'm still experiencing this in 0.9.20.
