### ISSUE TITLE
Hide sway/window when there is no window in focus

### ISSUE THREAD

**Issue by the-argus** [Alexays/Waybar#1507]
Here is my bar when a window is in focus:
![good_example](https://user-images.githubusercontent.com/70479099/161472631-04c6ca2d-adf1-44bb-9764-c79d39b30974.png)

And here it is with nothing in focus.
![setup](https://user-images.githubusercontent.com/70479099/161472643-cfbcd680-d424-4368-8b6b-f1a2806dfdaf.png)

It would be nice to be able to remove the artefact in the second image where the sway/window modules remains but is empty.

**Comment by RobertMueller2** [comment]
Did you have a look at #1448 or #1349?

I think you could style
 `
window#waybar.empty #window {
  background:none;
}
`
or similar.

**Comment by the-argus** [comment]
Works perfectly, thanks! I was a bit confused because the fact that its done through styling doesn't seem to match the pattern that would be used for other widgets, for example doing this in the config for my network module:
```
"network": {
    "format-disconnected": ""
}
```
In order to hide it while its in a certain state.

**Comment by RobertMueller2** [comment]
It is a bit counter-intuitive indeed. I've added a remark regarding CSS hierarchy to the wiki page.
