### ISSUE TITLE
formatting upower module: gap between icon and percentage

### ISSUE THREAD

**Issue by p00f** [Alexays/Waybar#1532]
how do i add a space between the icon and percentage? I couldn't find it here so I tried `formatting: "{icon} {percentage}%}" and that didn't work either
![image](https://user-images.githubusercontent.com/36493671/164680630-cc87a176-1eb7-4f40-9a13-8902abdf9246.png)

**Comment by ErikReider** [comment]
You should be able to add a margin in your CSS file
