### ISSUE TITLE
Margins on `window#waybar`

### ISSUE THREAD

**Issue by fosskers** [Alexays/Waybar#1533]
For some time I've noticed that `margin`s (or padding) given to the `#waybar` aren't respected. For example:
```css
window#waybar {
  background: transparent;
  color: white;
  border: 1px solid #8fd4ff;
  border-radius: 10px;
  margin-left: 100px;
}
```
This _should_ make me see a huge gap between the left edge of the screen and the beginning of the waybar border, but it doesn't. The border is always glued right to the edge.

Have I configured something incorrectly? Anyway, thank you for a great project.

**Comment by berbiche** [comment]
Hi,

The margin for the window cannot be configured with GTK CSS, it must be done with the `margin` setting.

See the wiki for more information: https://github.com/Alexays/Waybar/wiki/Configuration#bar-config=

**Comment by fosskers** [comment]
It worked! Thank you!

**Comment by aylurus** [comment]
Contrary to the _margin_ property in CSS, the _margin_ value (and other values like tray icon size) in the Waybar config are hardcoded in pixels. I would like the margin to automatically scale with font size. Is there any trick to achieve this? E.g. by using some kind of invisible wrapper around the window in the CSS?

**Comment by LoneWolf4713** [comment]
Hi, I am having the same issue with padding, the thing is, padding gets applied when I configure it in
`* {
padding: 10px;
}
but not when I do:
```
window#waybar {
padding:10px;
}
```

neither does it apply in configuration file, when I do:
`"padding": 10,`

how can I fix this?

**Comment by mobsenpai** [comment]
> Hi, I am having the same issue with padding, the thing is, padding gets applied when I configure it in `* { padding: 10px; } but not when I do:
> 
> ```
> window#waybar {
> padding:10px;
> }
> ```
> 
> neither does it apply in configuration file, when I do: `"padding": 10,`
> 
> how can I fix this?

I would also like to know this.

**Comment by Cource** [comment]
for the padding, try
```css
window#waybar>box {
    padding:10px;
}
```

**Comment by mobsenpai** [comment]
@Cource, Hey man brilliantly answered! I immediately implemented it in my config. Is there anything you can help me with this. #3324. (Shamelessly plugging my issue)
