### ISSUE TITLE
Trouble with wlr/taskbar and custom/

### ISSUE THREAD

**Issue by UltraBlackLinux** [Alexays/Waybar#1534]
Hey there,
I'm currently setting up waybar on Wayfire, but I am facing some issues: All my attempts of creating custom modules or using wlr/taskbar have failed. Waybar just throws a warning, that the module is unknown.
These are the troublesome modules:
```json
    "wlr/taskbar": {
        "format": "{icon}",
        "icon-size": 14,
        "icon-theme": "Flatery",
        "tooltip-format": "{title}",
        "on-click": "activate",
        "on-click-middle": "close",
        "ignore-list": [
            "Alacritty"
        ]
    },
    "custom/pacman": {
        "exec": "~/.config/waybar/checkupdates.sh | wc -l",
        "exec-if": "exit 0",
        "on-click": "alacritty --hold --title 'Updating system...' -e sudo pacman -Syyu",
        "interval": 10,
        "format": " {}",
    }
```
Why is this causing problems?
Thanks!

**Comment by Anakael** [comment]
Which version of Waybar do you use?

**Comment by UltraBlackLinux** [comment]
> Which version of Waybar do you use?

Oh sorry, Waybar v0.9.12, installed from the arch repos

**Comment by Anakael** [comment]
Can you provide debug logs?

**Comment by Anakael** [comment]
And also can you provide full log?
It seems like you've forgotten add module to modules list.
