### ISSUE TITLE
[Feature] Add module to configure PowerProfiles

### ISSUE THREAD

**Issue by columbarius** [Alexays/Waybar#1539]
[power-profiles-daemon](https://gitlab.freedesktop.org/hadess/power-profiles-daemon) is a daemon, which lets you change the Powerprofile, which is useful to prolong battery life on laptops. 

I've created a prototype in [python](https://gist.github.com/columbarius/88c753aa4f4582371243d9a98756184b).

Would you be interested if I would port this to a c++ module?

I'm not familiar with C++ so I probably need some help doing this.

**Comment by colemickens** [comment]
Very disappointing this hasn't been added. I simply am not qualified to write C++ but this is a single executable or dbus call to get/set this value. Not sure how this doesn't have more attention from laptop users.

**Comment by picnoir** [comment]
I can't close this issue by myself, but this has been implemented by https://github.com/Alexays/Waybar/pull/2971. 

See manual or the [module wiki page](https://github.com/Alexays/Waybar/wiki/Module:-PowerProfilesDaemon) for more information.
