### ISSUE TITLE
How do I use the volume scroll on my keyboard?

### ISSUE THREAD

**Issue by tiagaoalb** [Alexays/Waybar#1542]
I have a `Corsair K70 Lux keyboard` and would like to be able to use the `volume scroll` on it.
Is there a way to do it?

**Comment by manfred3000** [comment]
Isn't there a way to keybind your scroll thingy within your Desktop/WM configuration? To use it on a bar module sounds rather awkward...

**Comment by tiagaoalb** [comment]
> 

I dont know. I asked because I can use the scroll out the box on most WM, but here is different...
