### ISSUE TITLE
Feature request: tail option for custom module

### ISSUE THREAD

**Issue by xi** [Alexays/Waybar#1558]
The custom module currently allows to include the output from a command in the bar. That command is re-run either on a fixed interval (polling) or when a signal is received.

Some bars (e.g. polybar and lemonbar) have yet another option: The command runs in an infinite loop and only the last line of output is included in the bar. This is more efficient than polling and IMHO simpler than signals.

In polybar this behavior is activated with the `tail` option. Would it be possible to add such an option to waybar? Or are there any strong arguments against it?

**Comment by Zaedus** [comment]
This is already implemented.
See the [custom modules wiki page](https://github.com/Alexays/Waybar/wiki/Module:-Custom)
For an example, look at the MPRIS controller example.

**Comment by xi** [comment]
I must have missed that. Thanks!
