### ISSUE TITLE
Double bar

### ISSUE THREAD

**Issue by ilyss01** [Alexays/Waybar#1559]
Bug: I have two monitors and each one have waybar on it. They have the same config file. And waybar duplicates for some reason (look at screenshot)

Sway config that relates to the bar:
```
bar {
	position top
	status_command 'waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css -l off'
}
```

Waybar `config` and `style.css` files:
https://github.com/ilyss01/dotfiles/blob/main/waybar/.config/waybar/config
https://github.com/ilyss01/dotfiles/blob/main/waybar/.config/waybar/style.css

Waybar and sway are installed from arch repo

![image](https://user-images.githubusercontent.com/47274578/168967372-bb4099c2-9fd3-4d28-8f1e-abd0c8df4275.png)

**Comment by Alexays** [comment]
https://github.com/Alexays/Waybar/wiki/Installation
Prefer swaybar_command

**Comment by 01Destiny01** [comment]
Same here... Did u find a solution?
