### ISSUE TITLE
status "plugged" is not detected

### ISSUE THREAD

**Issue by name-snrl** [Alexays/Waybar#1560]
I want to see when my laptop plugged. A similar issue is described in #253.
My device is a Thinkpad t440s with NixOS unstable on board. I use tlp to set charging thresholds

![Untitled](https://user-images.githubusercontent.com/72071763/168993458-1807b13c-d53b-43a4-b8ef-926eccdd0703.png)

I also tried using "format-plugged" but nothing changed.

**Comment by clownhelmet** [comment]
Same issue here. I'm not using TLP but it seems it uses the same interface `/sys/class/power_supply/BAT0/charge_control_end_threshold`. 

`cat /sys/class/power_supply/BAT0/status
Not charging`

`cat /sys/class/power_supply/AC0/online
1`

**Comment by dtk9289** [comment]
bump

**Comment by Alexays** [comment]
Should be fixed with #1679

**Comment by ericliou** [comment]
@Alexays the fix didn't work for me, Arch, Lenovo laptop.
I think the problem might be on line 473 below. 
When my laptop is plugged, the value of `/sys/class/power_supply/BAT0/status` is `Not Charging`. It wouldn't enter the `if` in my case.
https://github.com/Alexays/Waybar/blob/92cc01f40149292d315456f7e5bbdad6dc099caf/src/modules/battery.cpp#L473-L479

Another question that might be related. Why does L477 reads `/status` from the adapter? It seems that my adapter doesn't have the `/status` node, only the battery has it.
```
ls /sys/class/power_supply/ADP0/
device	hwmon0	online	power  subsystem  type	uevent	wakeup26
```

**Comment by geogiraux** [comment]
hi, sorry to make this "revive" but I have the same problem with waybar 0.11.0. Could @clownhelmet or @name-snrl confirm it is solved please ? If it's ok for you I will fill a new issue and provide my  own informations
