### ISSUE TITLE
[BUG `waybar-network`] Enforcing `interface` causes `{gwaddr}` to be empty

### ISSUE THREAD

**Issue by subnut** [Alexays/Waybar#1564]
### config
```json
"network#wifi": {
  "interface": "wl*"
  "format-wifi": "{gwaddr}",
}
```
### result
module is empty

### debug log (network-relevant entries only)
```log
[2022-05-21 13:27:25.066] [debug] network: selecting new interface wlp3s0/3
[2022-05-21 13:27:25.066] [debug] network: wlp3s0, new addr aaa.bbb.ccc.ddd/24
```

### config
```json
"network#wifi": {
  "format-wifi": "{gwaddr}",
}
```
### result
module contains gateway address

### debug log (network-relevant entries only)
```log
[2022-05-21 13:28:08.345] [debug] network: new default route via aaa.bbb.ccc.xxx on if3 metric 3003
[2022-05-21 13:27:25.066] [debug] network: wlp3s0, new addr aaa.bbb.ccc.ddd/24
```

# NOTE
In the logs, I have replaced the actual IP address with `aaa.bbb.ccc.ddd` and `aaa.bbb.ccc.xxx`

**Comment by subnut** [comment]
### Diagnosis
- If `interface` is set in the config, then `config_["interface"].isString()` is true.
- When `config_["interface"].isString()` is true, the module never sets `want_route_dump_ = true;` 
- so `askForStateDump()` never asks for a route dump 
- so `handleEvents()` never receives a `RTM_NEWROUTE` message
- and so it never sets  `net->gwaddr_`
- and therefore, `gwaddr_` remains unset.

**Comment by Alexays** [comment]
Should be better wirh a4d27ea

**Comment by subnut** [comment]
Nope, still not fixed.

**Comment by felixauringer** [comment]
Same for me.

**Comment by Reylak** [comment]
Still happening with waybar 0.9.24.

**Comment by andreafrati1969** [comment]
Any news ? Issue still persist on waybar 0.10.3-1

**Comment by cunlem** [comment]
This bug is still present in 0.15.0

@Alexays can you please reopen since the issue hasn't ever been fixed really
