### ISSUE TITLE
Waybar 0.9.13 position lleft with width appears in the middle of the screen.

### ISSUE THREAD

**Issue by dron1885** [Alexays/Waybar#1568]
After upgrading 0.9.12 -> 0.9.13 Waybar will appear in the middle of the screen when position left (or right) if the width is set to a non-default value other than 0.

top/bottom works wine with height.

Relevant lines from the config. When setting the width to 0 or commenting the line the bar will appear at the correct position.

```
"position": "left", // Waybar position (top|bottom|left|right)
"width": 60, // Waybar width 
```

Sway, Arch Linux.

**Comment by ShinobiX9X** [comment]
hallo,

Same here. Commenting the line with width "solved" it, thank you.

Sway, Arch Linux

**Comment by wherenog** [comment]
Same issue. I;m using wayfire, Arch linux

**Comment by 1edenec** [comment]
same here. ArchLinux.
```
[2022-05-24T10:52:15+0300] [ALPM] upgraded waybar (0.9.12-2 -> 0.9.13-1)
```
