### ISSUE TITLE
incorrect arrangement of modules

### ISSUE THREAD

**Issue by labi-le** [Alexays/Waybar#1573]
![image](https://user-images.githubusercontent.com/65619560/170455625-b63bbab7-7442-436c-9699-f17250173c9d.png)
![image](https://user-images.githubusercontent.com/65619560/170453425-8d95b25d-60b8-423d-928e-31520c31462d.png)

**Comment by daangoossens22** [comment]
If the problem is that everything is squashed in the middle, this is probably because the width of the whole bar is set to 10px. Removing the line ```"width": 10,``` should then solve the issue.

**Comment by labi-le** [comment]
ty
