### ISSUE TITLE
waybar 1 pixel down from top of screen

### ISSUE THREAD

**Issue by yorickvP** [Alexays/Waybar#158]
Since updating waybar today, it moved down a single pixel, and moving my mouse to the top of the screen mean it's not over any of the workspace buttons. I don't know if this is a waybar or sway issue, so I'm submitting it here.

**Comment by yorickvP** [comment]
https://github.com/swaywm/sway/issues/3546

**Comment by Alexays** [comment]
Fixed on sway master
