### ISSUE TITLE
Width and height values seem to not be respected

### ISSUE THREAD

**Issue by Sqvid** [Alexays/Waybar#1583]
After the latest update (to v0.9.13) I noticed my bar had shrunk. When running waybar on the terminal I noticed the error "not using units is deprecated." Including px units everywhere in my config did seem to exxpand the bar but "width" and "height" values dont seem to be respected.

I have set the height and width to ridiculous values so that a change is apparent.
config: https://pastebin.com/gS8uVSJb
style: https://pastebin.com/xfwvFtHx

I imagine this is my mistake, but as my bar was functioning before the update I assume I relied some deprecated behaviour that was finally removed.

Thank you for your time and for this amazing project.

**Comment by daangoossens22** [comment]
Relevant section from the man page:
https://github.com/Alexays/Waybar/blob/fb2ac8a7651a8a4222b063557e37bdf088506028/man/waybar.5.scd.in#L39-L45
They both values need to be an integer. So changing this:
```jsonc
    "height": "1000px",
    "width": "50px",
```
to this:
```jsonc
    "height": 1000,
    "width": 50,
```
should do the trick. But you probably want to change these values as I doubt you want the bar height to take up 1000 pixels. Also note not defining the width will make the bar fill the whole width.

**Comment by Sqvid** [comment]
This was absolutely right. Waybar was complaining about pixel values missing elsewhere and I accidentally added them here as well. Thank you.
