### ISSUE TITLE
Issue on Network module (disconnected hidden)

### ISSUE THREAD

**Issue by thyeun** [Alexays/Waybar#1594]
Facing on network module while disconnected, the module will hide itself. As for the example by @Alexays, if the ```format-disconnected``` are empty than only it will hidden. But with the setting below, it still hidden. Can anyone advised why?

OS : Arch Linux (5.18.3-arch1-1)
Waybar version : 0.9.13
Sway version : 1.7 

```
"network": {
        "interval": 5,
        "format-wifi": "  {essid} ({signalStrength}%)", // Icon: wifi
        "format-disconnected": "⚠  ISP are too lazy", //An empty format will hide the module.
        "tooltip-format": "{ifname}: {ipaddr} ({signalStrength}%)",
        "max-length":18,
        "on-click": "nm-connection-editor",
    },

```
Connected wifi
![2022-06-17T18:05:33,906044984+08:00](https://user-images.githubusercontent.com/1939446/174277549-2e3ddb01-a05b-49b5-9ba0-a4ac01d99cf8.png)

Disconnected wifi
![2022-06-17T18:06:33,703597687+08:00](https://user-images.githubusercontent.com/1939446/174277614-83b22efd-eef1-4a45-b24b-8f1d42e6390d.png)

**Comment by Alexays** [comment]
Try with `format-disabled`

**Comment by thyeun** [comment]
have to using ```format-disabled``` instead of ```format-disconnected``` on Network module
