### ISSUE TITLE
When layer is set to bottom (default) tooltip shown under windows

### ISSUE THREAD

**Issue by Alexays** [Alexays/Waybar#16]

**Comment by Alexays** [comment]
Might be fixed with #441 can someone test?

**Comment by David96** [comment]
Related: https://github.com/swaywm/sway/issues/4684 and https://github.com/swaywm/sway/pull/4781
I currently don't have the time to dig deep enough into the sway rendering code to properly fix this and I'm also not sure whether the way the pull request "solves" the issue is the best way of dealing with it.

**Comment by ainola** [comment]
This is not fixed with gtk-layer-shell - Tooltips are still displayed underneath unless layer is explicitly set to top.

**Comment by piu130** [comment]
@ainola How do you set it to top?

**Comment by eternal-sorrow** [comment]
@piu130 `"layer": "top",`

**Comment by dd23** [comment]
I had the waybar layer set to bottom, so `bemenu` would be shown on top of waybar (as recommended in #474), but since the last release also **tray icon context menus** disappeared behind windows.
Just wanted to say that this is not limited to tooltips.

**Comment by L0stLink** [comment]
Exactly as dd23 said, I would have no problem using the workaround but I need to be able to use `bmenu` as well and I cannot do that if it gets hidden behind `waybar`.

**Comment by teutat3s** [comment]
One possible workaround is to use `bemenu --no-overlap` and configure `waybar` to with `"layer": "top"`

**Comment by David96** [comment]
This is now fixed in sway (https://github.com/swaywm/sway/pull/4781), therefore can be closed I think. Also the default layer should probably be bottom now, so things like bemenu can display over waybar.

**Comment by Alexays** [comment]
Thanks @David96 🎉
