### ISSUE TITLE
wlr/workspaces "all-outputs" option not working

### ISSUE THREAD

**Issue by ObsidianChickenz** [Alexays/Waybar#1605]
When I set "all-outputs" to true, I don't see all of my workspaces. I'm not sure if this is a distro-specific problem, as NixOS has a different filesystem layout compared to other distros. I can provide more details as needed.

OS: NixOS Unstable
Compositor: Hyprland

**Comment by Misterio77** [comment]
I'm also running NixOS and Hyprland, and `all-outputs` works nicely.

**Comment by ObsidianChickenz** [comment]
Weird. Only the workspaces with windows in them are showing for me.

**Comment by Misterio77** [comment]
Wait, that's intended. AFAIK the workspaces only exist if either: they're currently focus or they have a window in it

**Comment by Misterio77** [comment]
Once you move away from a workspace without any windows in it, it's destroyed

**Comment by ObsidianChickenz** [comment]
Oh, well that explains it. Thanks!

**Comment by thomascft** [comment]
> Wait, that's intended. AFAIK the workspaces only exist if either: they're currently focused or they have a window in it

Is there a way to show workspaces without windows in them? I'd like to see workspaces 1-5 showing up with only two having any windows
