### ISSUE TITLE
#workspace button.focused changes nothing on Hyprland

### ISSUE THREAD

**Issue by ObsidianChickenz** [Alexays/Waybar#1609]
On Hyprland, the style for the focused workspace never appears (at least for me). There is no way to distinguish between the selected workspace and the other workspaces. Is this a bug or am I stupid?

**Comment by ObsidianChickenz** [comment]
Fixed by using debug mode, I guess the wiki is out of date?

**Comment by hyq12358** [comment]
> Fixed by using debug mode, I guess the wiki is out of date?

I got the same issue.
By the way, how to use debug mode?

**Comment by hyq12358** [comment]
> On Hyprland, the style for the focused workspace never appears (at least for me). There is no way to distinguish between the selected workspace and the other workspaces. Is this a bug or am I stupid?

Have u solved this?

**Comment by hyq12358** [comment]
> On Hyprland, the style for the focused workspace never appears (at least for me). There is no way to distinguish between the selected workspace and the other workspaces. Is this a bug or am I stupid?

I got the same problem.
How do you s love it?

**Comment by ObsidianChickenz** [comment]
You need to set the style for #workspace button.active, not button.focused or button.visible. Hope this helps!
