### ISSUE TITLE
Missing required resources files

### ISSUE THREAD

**Issue by bemeurer** [Alexays/Waybar#161]
Since I didn't want to install waybar proper, I just symlinked the binary to a folder in my `$HOME` and in my `$PATH`. However, when I try to run waybar I get: 
```
$ ~/bin/waybar
Missing required resources files
```

Why is this happening, and what is the right way to do this?

**Comment by Alexays** [comment]
You are missing the configuration and style files.
If you want you can specify them with `-c` and `-s` args

**Comment by bemeurer** [comment]
Got it, thanks!

**Comment by Arnaudv6** [comment]
got hit also...  
I suggest "config" wiki page be updated with a note like:
`ensure you also have *styles.css* file for waybar to run properly (for instance in .*/config/waybar*)`.
