### ISSUE TITLE
Change cursor on hover of clickable module?

### ISSUE THREAD

**Issue by ton** [Alexays/Waybar#1610]
Would it be possible to change the cursor shape when hovering a module? Specifying the CSS `cursor` property makes Waybar error out saying the `cursor` CSS property is not supported.

It would be nice to get some visual feedback that a module is clickable when hovering over it with the mouse.

**Comment by slithery0** [comment]
I was testing with css to change cursor on hover, but the waybar do not showup after setting any css with cursor property.

**Comment by Sophed** [comment]
Still waiting on this functionality.

**Comment by Prayag2** [comment]
Any updates on this?

**Comment by lilydjwg** [comment]
I don't like this idea. For native UI widgets, the clickability is often indicated by a slight background change (e.g. buttons, menu items, tabs), or not indicated at all (e.g. menubar, item list).

The hand cursor is an invention of the Web, and not used on native interfaces (except when a hyperlink is indicated). You don't get the hand cursor on your browser's native UI widgets.

**Comment by Sophed** [comment]
This might be a crazy take but perhaps not everything web and native has to stay separate? It's not like the two haven't massively influenced each others design principles.

If it really bothers you, maybe it could be made a per-widget option like polybar.

**Comment by lilydjwg** [comment]
Yes, it would be great for it to be configurable (either per widget or global). The main issue it brings to me is that the cursor change draws attention when my cursor wanders around. (That's perhaps why I first noticed it on my laptop but not desktop.)

**Comment by SeanHub** [comment]
Been investigating the cursor option and come to this issue. I have noticed that the waybar hyprland workspaces module uses both the arrow and hand in odd ways. If you hover on the very edge of the workspace item you will see a hand cursor, but when you hover over the workspace item you will see an arrow cursor. If anything it should be the other way round (ideally configurable).
