### ISSUE TITLE
Waybar language should have the layout as class name

### ISSUE THREAD

**Issue by carlosV2** [Alexays/Waybar#1615]
Hi,

In general all the waybar modules are pretty straight forward and configurable enough to come with any styling.

The language module, however, I believe it could be more powerful. For example, by adding the layout (gb, es, ...) as a class name, it would allow for more styling.

Here is an example of what I mean:
![2022-07-10T09:32:11,119204942+01:00](https://user-images.githubusercontent.com/2642839/178137599-3ee165f7-12eb-4e90-b450-01c444c0fd3d.png)

I've managed to build this language module by using a custom one and, so far it works great and shows the corresponding flag whenever you change the language layout but, because I have to use a custom module, I need to use a polling aproach with 1s minimum which feels rather sluggish some times (plus it is a waste of resources).

I think adding the layout as class name to the module would simplify this setup and enable many more.

If you like the idea, I can attempt a PR.

**Comment by carlosV2** [comment]
I'm closing this issue since [its PR](https://github.com/Alexays/Waybar/pull/1628) has been merged.

**Comment by DrPandemic** [comment]
Were you able to show flags with your CSS approach?

**Comment by carlosV2** [comment]
@DrPandemic yes, the screenshot I took is from my computer. I can toggle the language with a key combination and the corresponding flag shows there 😄.

**Comment by DrPandemic** [comment]
Is there some documentation for that? I tried using CSS `content` but waybar was complaining about it.

**Comment by carlosV2** [comment]
Not sure what documentation are you asking for. The PR I sent uses the language layout as CSS selector (f.e. `.gb`, `.es`, etc).
I hasn't been rolled out to Manajaro tho 🤦🏼‍♂️ so I haven't tested it.

What helps me massively is the GTK debugger. You can trigger it with:
```sh
GTK_DEBUG=interactive waybar
```

This will render a second waybar but it will also show a window with a detailed view of all the components and their properties (including the CSS selectors).
