### ISSUE TITLE
Ibus tray icon is missing?

### ISSUE THREAD

**Issue by toaranotdev** [Alexays/Waybar#1626]
Hello everyone,

I had quite a bit of trouble with this since I see the tray icon is missing, I thought ibus wasn't working which is weird cuz I can use ibus just fine in KDE Wayland but as it turns out the tray icon was deceiving me, ``ibus-daemon`` was running the whole time. Discord's tray icon works just fine without the need for that XDG_CURRENT_DESKTOP environment variable (I tried it anyway, no success)

Some information that might help:
- I have that show system tray icon toggled in ``ibus-setup``
- I installed the lastest ibus-git version from the AUR
- I'm also using waybar-git, I saw that experimental package but haven't tried it (Not sure if it helps though)
- WM: sway

The tray icon is important to me cuz I'm using [ibus-bamboo](https://github.com/BambooEngine/ibus-bamboo) and I can only configure it by right clicking the tray icon and AFAIK there's no way to access that menu without a tray icon

**Comment by datMaffin** [comment]
If you mean by "missing" that the "'missing icon' placeholder is used for the icon", then my PR #1627 might fix it.

**Comment by toaranotdev** [comment]
> If you mean by "missing" that the "'missing icon' placeholder is used for the icon", then my PR #1627 might fix it.

By missing I mean non-existent :( There are no placeholder, no nothing really

Maybe #254 is why?

**Comment by toaranotdev** [comment]
More info on this:
- Running ``ibus-daemon`` without the ``-d`` flag shows this: 
``portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1``

**Comment by lyokha113** [comment]
Hi, is there any new update for this issue ?
I got same with ibus-bamboo, no icon on Tray module, even it is still working

**Comment by toaranotdev** [comment]
> Hi, is there any new update for this issue ? I got same with ibus-bamboo, no icon on Tray module, even it is still working

![image](https://github.com/Alexays/Waybar/assets/85060424/5272c7ac-e288-404c-baff-7331b0d57312)

I just tried again today, trying to figure out if I can help it in anyway but it has magically fixed itself. I'm closing this issue :) (Waybar v0.9.17)
