### ISSUE TITLE
[wlr/workspaces] Feature request: Persistent workspaces

### ISSUE THREAD

**Issue by Pebor** [Alexays/Waybar#1629]
Currently, there is no option to have persistent workspaces on wlr/workspaces, only showing workspaces that have window or windows in them.
This just hurts ricing and usability on anything other than sway.
I have not found an answer as to why this isn't possible.

**Comment by Spaxly** [comment]
Any update on this?

**Comment by hackedWifi** [comment]
This would be a nice feature to have. If you have three occupied workspaces and switch to, for example number 6. It looks like you are on workspace 4 due to the fact that it just add an icon to the right of the already occupied ones. Also on Hyprland once you switch to an empty workspace; and try to switch to another empty one - the bar displays like a workspace icon momentarily (flashes on and off) next to the empty one. I think I did not explain it pretty well :)

**Comment by Spaxly** [comment]
@Alexays

**Comment by Spaxly** [comment]
> +1 this would be very useful for hyprland. seems https://github.com/Alexays/Waybar/blob/master/src/modules/sway/workspaces.cpp#L77-L114 is the related code for sway workspaces. not sure if there are some technical challenges for wlr though.

I have found a way to show all workspaces using wlr/workspaces and the waybar-hyprland fork. Basically, it would silently open a terminal without actually showing it, making the workspace visible on waybar since waybar only shows workspaces that have apps open on. I will share this in a gist later.

**Comment by Spaxly** [comment]
> @Spaxly Hi, I'd love to see this solution!

```
# Global persistent workspace rules 
windowrule=float,title:^PERSISTENT_WORKSPACE.*$
windowrule=nofocus,title:^PERSISTENT_WORKSPACE.*$
windowrule=noblur,title:^PERSISTENT_WORKSPACE.*$
windowrule=size 0 0,title:^PERSISTENT_WORKSPACE.*$
windowrule=move 0 0,title:^PERSISTENT_WORKSPACE.*$
windowrule=opacity 0,title:^PERSISTENT_WORKSPACE.*$
# Individual persistent workspace rules
windowrule=workspace 1,title:^(PERSISTENT_WORKSPACE_1)$
windowrule=workspace 2,title:^(PERSISTENT_WORKSPACE_2)$
windowrule=workspace 3,title:^(PERSISTENT_WORKSPACE_3)$
windowrule=workspace 4,title:^(PERSISTENT_WORKSPACE_4)$
windowrule=workspace 5,title:^(PERSISTENT_WORKSPACE_5)$
# Exec commands to keep each workspace persistent 
exec-once=alacritty -t PERSISTENT_WORKSPACE_1 & 
exec-once=alacritty -t PERSISTENT_WORKSPACE_2 & 
exec-once=alacritty -t PERSISTENT_WORKSPACE_3 & 
exec-once=alacritty -t PERSISTENT_WORKSPACE_4 & 
exec-once=alacritty -t PERSISTENT_WORKSPACE_5 & 
```

Add the above to your hyprland.conf, if you don't use alacritty, change the terminal. That is what I use for persistent workspaces.

**Comment by zjeffer** [comment]
@Spaxly That's horrific but I guess it kind of works lol

The current issue I have is that there is a tiny window in the top left corner of every monitor, which also moves when I switch to a different workspace. Do you also have this problem?

**Comment by Spaxly** [comment]
> @Spaxly That's horrific but I guess it kind of works lol
> 
> The current issue I have is that there is a tiny window in the top left corner of every monitor, which also moves when I switch to a different workspace. Do you also have this problem?

Ik, but that was only solution. Also, I don't have the problem you are talking about.

**Comment by HanoJing** [comment]
> > @Spaxly Hi, I'd love to see this solution!
> 
> ```
> # Global persistent workspace rules 
> windowrule=float,title:^PERSISTENT_WORKSPACE.*$
> windowrule=nofocus,title:^PERSISTENT_WORKSPACE.*$
> windowrule=noblur,title:^PERSISTENT_WORKSPACE.*$
> windowrule=size 0 0,title:^PERSISTENT_WORKSPACE.*$
> windowrule=move 0 0,title:^PERSISTENT_WORKSPACE.*$
> windowrule=opacity 0,title:^PERSISTENT_WORKSPACE.*$
> # Individual persistent workspace rules
> windowrule=workspace 1,title:^(PERSISTENT_WORKSPACE_1)$
> windowrule=workspace 2,title:^(PERSISTENT_WORKSPACE_2)$
> windowrule=workspace 3,title:^(PERSISTENT_WORKSPACE_3)$
> windowrule=workspace 4,title:^(PERSISTENT_WORKSPACE_4)$
> windowrule=workspace 5,title:^(PERSISTENT_WORKSPACE_5)$
> # Exec commands to keep each workspace persistent 
> exec-once=alacritty -t PERSISTENT_WORKSPACE_1 & 
> exec-once=alacritty -t PERSISTENT_WORKSPACE_2 & 
> exec-once=alacritty -t PERSISTENT_WORKSPACE_3 & 
> exec-once=alacritty -t PERSISTENT_WORKSPACE_4 & 
> exec-once=alacritty -t PERSISTENT_WORKSPACE_5 & 
> ```
> 
> Add the above to your hyprland.conf, if you don't use alacritty, change the terminal. That is what I use for persistent workspaces.

I use this solution, though, I have a dual monitor setup and somehow when I turn the DPMS of both monitors off, and on again, the workspace of the secondary monitor gets added to my first monitor and then my secondary monitor gets a new workspace that is `workspace-number+1`.
Also after DPMS is turned on again, the focus of the workspace is switched somehow. 
Eh, let's hope that one day, there will be a better solution.

**Comment by redxtech** [comment]
Any news on this?

I would love to get persistent workspaces working in `wlr/hyprland`, but don't want to have to make an invisible terminal window for each one!

**Comment by MonstrousOgre** [comment]
I managed to modify the code and add persistent workspaces, but it shows them twice if there's a window in the workspace. I can probably fix it if I have time, but I won't be able to work on this for a while.

**Comment by MonstrousOgre** [comment]
@HanoJing here's the config I was testing with

```
"persistent_workspaces": {
            "1": [],
            "4": [],
            "5": ["eDP-1", "HDMI-A-1"], 
            "7": ["eDP-1", "HDMI-A-1"],
            "9": ["HDMI-A-1"],
            "10": ["eDP-1"]
        }
```
The array for each workspace determines what monitor/output it'll show up on. If it's an empty array, it'll show up on all monitors.

That's how it works for [sway/workspaces] too and I wanted to keep consistency.

**Comment by HanoJing** [comment]
@MonstrousOgre Ah, I see.

It sadly still doesn't work. This is my config:
```
"persistent_workspaces": {
            "1": [],
            "2": [],
            "3": [],
            "4": [],
            "5": [],
            "6": [],
            "7": [],
            "8": [],
            "9": [],
            "10": [],
            "11": ["DP-3"]
    },
```

**Comment by MonstrousOgre** [comment]
@HanoJing Is it inside [wlr/workspaces]? I forgot to mention that. Mine is actually something like this.

```
"wlr/workspaces": {
        "persistent_workspaces": {
            "1": [],
            "4": [],
            "5": ["eDP-1", "HDMI-A-1"], 
            "7": ["eDP-1", "HDMI-A-1"],
            "9": ["HDMI-A-1"],
            "10": ["eDP-1"]
        }
    }

```

**Comment by HanoJing** [comment]
OOh, yup, mine is not inside wlr/workspaces.

**Comment by HanoJing** [comment]
Yes! It works! And I even don't have the issue you described with duplicate workspaces on either monitor!

**Comment by MonstrousOgre** [comment]
Do you have multiple monitors? The duplicate workpspaces issue shouldn't be present if there's only one monitor. If you have multiple, well then... there might be another reason I'm seeing duplicates on mine.

If you have multiple monitors, do you have any workspaces that are "bound" to a monitor? I'm guessing that's another possible reason I'm seeing duplicates.

**Comment by HanoJing** [comment]
> Do you have multiple monitors? The duplicate workpspaces issue shouldn't be present if there's only one monitor. If you have multiple, well then... there might be another reason I'm seeing duplicates on mine.

Yes. I have a dual-monitor setup.

> If you have multiple monitors, do you have any workspaces that are "bound" to a monitor? I'm guessing that's another possible reason I'm seeing duplicates.

Yes. 
Here's my hyprland.conf:
[hyprland-conf.log](https://github.com/Alexays/Waybar/files/11146450/hyprland-conf.log)

**Comment by HanoJing** [comment]
The parts of the config where I bind workspaces to monitors are:
```
monitor=DP-2,2560x1440@60,1920x0,1
workspace=DP-2,1
workspace=DP-2,2
workspace=DP-2,3
workspace=DP-2,4
workspace=DP-2,5
workspace=DP-2,6
workspace=DP-2,7
workspace=DP-2,8
workspace=DP-2,9
workspace=DP-2,10

monitor=DP-3,1920x1080@60,0x0,1
workspace=DP-3,11
```
and
```
wsbind=11,DP-3
wsbind=1,DP-2
wsbind=2,DP-2
wsbind=3,DP-2
wsbind=4,DP-2
wsbind=5,DP-2
wsbind=6,DP-2
wsbind=7,DP-2
wsbind=8,DP-2
wsbind=9,DP-2
wsbind=10,DP-2
```

**Comment by HanoJing** [comment]
@MonstrousOgre Do you mind If I take a look at your `hyprland.conf` and waybar `config`?

**Comment by MonstrousOgre** [comment]
This is just a hunch but what's your `"all-outputs"` set to in your Waybar config for wlr/workspaces? Is it even there in your config?

**Comment by HanoJing** [comment]
> This is just a hunch but what's your `"all-outputs"` set to in your Waybar config for wlr/workspaces? Is it even there in your config?

Nope, I haven't got it set.

**Comment by MonstrousOgre** [comment]
That might be it. If you don't mind, could you set it to true and see if you get duplicates?

**Comment by HanoJing** [comment]
sure

**Comment by MonstrousOgre** [comment]
That explains it. Right now you get duplicates if you have multiple monitors and have "all-outputs" set to true

**Comment by HanoJing** [comment]
Yes. Glad I could be of help. Let me know if you need more info. May I inform Alexays, so it get's merged soon?

**Comment by MonstrousOgre** [comment]
@HanoJing sure

**Comment by HanoJing** [comment]
@Alexays Please checkout persistent workspaces for hyprland: https://github.com/Alexays/Waybar/compare/master...MonstrousOgre:Waybar_hyprland_persistent:master 

Let us know if you would consider merging it! Thanks in advance!

**Comment by hurutparittya** [comment]
It's working like a charm on 4 monitors as well. Hoping it gets merged soon.

**Comment by MonstrousOgre** [comment]
@LeGrosFaisan unfortunately I don't know how the CSS classes are handled. It'll be a while before I can go through the code and understand it.

**Comment by hackedWifi** [comment]
@MonstrousOgre @hurutparittya I suggest moving this discussion to your fork. Not everyone wants to get email notifications for something that is not related to #1629. It keeps this issue clean and organized.

**Comment by arDrag0n** [comment]
@MonstrousOgre Thanks for the patch btw. Is it possible to display the empty persistant workspaces with a different color tried #workspaces button.persistant but it doesn't work

**Comment by MonstrousOgre** [comment]
@arDrag0n not at the moment. I plan to add it in the future once I figure out how. But for now I'm trying to merge what I already have.

**Comment by myNicole98** [comment]
@MonstrousOgre I tried to install this version but it says "[warning] module wlr/workspaces: Unknown module: wlr/workspaces" do you have any idea?

**Comment by HanoJing** [comment]
> @MonstrousOgre I tried to install this version but it says "[warning] module wlr/workspaces: Unknown module: wlr/workspaces" do you have any idea?

Yes, I have had the same issue as you

use this command to build waybar:

```
sed -i -e 's/zext_workspace_handle_v1_activate(workspace_handle_);/const std::string command = "hyprctl dispatch workspace " + name_;\n\tsystem(command.c_str());/g' src/modules/wlr/workspace_manager.cpp
meson --prefix=/usr build
meson configure -Dexperimental=true build
sudo ninja -C build install
```

This is also the command I use to build Waybar.

https://wiki.hyprland.org/Useful-Utilities/Status-Bars/

**Comment by myNicole98** [comment]
> > @MonstrousOgre I tried to install this version but it says "[warning] module wlr/workspaces: Unknown module: wlr/workspaces" do you have any idea?
> 
> Yes, I have had the same issue as you
> 
> use this command to build waybar:
> 
> ```
> sed -i -e 's/zext_workspace_handle_v1_activate(workspace_handle_);/const std::string command = "hyprctl dispatch workspace " + name_;\n\tsystem(command.c_str());/g' src/modules/wlr/workspace_manager.cpp
> meson --prefix=/usr build
> meson configure -Dexperimental=true build
> sudo ninja -C build install
> ```
> 
> This is also the command I use to build Waybar.
> 
> https://wiki.hyprland.org/Useful-Utilities/Status-Bars/

Thanks it worked! Even though now I have duplicates of active workspaces e.e

**Comment by MonstrousOgre** [comment]
@LeGrosFaisan @arDrag0n I created pull request #2153 for empty persistent workspaces just like you wanted. It's a feature I've wanted too. Hopefully it gets merged soon.

**Comment by arDrag0n** [comment]
Thanks! It's working perfectly.
