### ISSUE TITLE
fmt dependancy check fails

### ISSUE THREAD

**Issue by CaptainBloodz** [Alexays/Waybar#163]
Here on gentoo we also have dev-ml/fmt-0.8.4.
So I was confused at first.
But because of version n°, I  fnally installed  libfmt-5.2.1

Found CMake: /usr/bin/cmake (3.9.6)
Initial error: fmt = dependency('fmt', version : ['>=5.2.1'], fallback : ['fmt', 'fmt_dep'])

Dependency fmt found: NO (tried pkgconfig and cmake)
Not looking for a fallback subproject for the dependency libfmt because:
Use of fallbackdependencies is disabled.

Then I patched meson.build to: fmt = dependency('libfmt', version : ['>=5.2.1'], fallback : ['fmt', 'fmt_dep'])

Found CMake: /usr/bin/cmake (3.9.6)
Dependency fmt found: NO (tried pkgconfig and cmake)
Not looking for a fallback subproject for the dependency libfmt because:
Use of fallbackdependencies is disabled.

I'm very new to packaging design so solution may be out of reach of my technical skill.

Edit: Finally worked with

fmt = dependency('fmt', version : ['>=5.2.1'], fallback : ['libfmt', 'fmt_dep'])

Plz close, I don't know how to do it.
Sorry for that, I'm learning...

**Comment by Alexays** [comment]
@CaptainBloodz Thx i'll update the file with `libfmt` :)
