### ISSUE TITLE
A minimum height of 200 by default

### ISSUE THREAD

**Issue by MojiRiAnt** [Alexays/Waybar#164]
Just paying some attention to a thing which is probably not that much of a bug.
If I start a waybar with an empty config or a config like this:
`
{
    "height": 15
}
`
(so, it's basically an empty bar with no modules), it shows up as expected, but outputs a message like this:
```
Requested height: 30 exceeds the minimum height: 200 required by the modules
Bar configured (width: 1366, height: 200) for output: LVDS-1
```
So, there is this number 200 showing up. As soon as I add a clock module to my config (others not tested), it starts working normally.
Thus, just a small note.

**Comment by Alexays** [comment]
Should be fixed on master :)
