### ISSUE TITLE
Unknown module: wlr/workspaces

### ISSUE THREAD

**Issue by TheSunCat** [Alexays/Waybar#1640]
Hi!
I'm trying to use the Waybar package from the Arch community repositories, and it does not seem to recognize the `wlr/workspaces` module [described in the wiki](https://github.com/Alexays/Waybar/wiki/Module:-Workspaces). It prints the following log:
```
[2022-08-01 16:16:07.546] [warning] module wlr/workspaces: Unknown module: wlr/workspaces
[2022-08-01 16:16:07.546] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[2022-08-01 16:16:07.551] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.
```

I'm using the Hyprland compositor, which has support for the necessary protocol.

**Comment by Polluktus** [comment]
did you read https://github.com/hyprwm/Hyprland/wiki/FAQ#i-want-to-use-waybar-but-the-workspaces-dont-work and added
```
#define HAVE_WLR
#define USE_EXPERIMENTAL
```
on top of include/factory.hpp?

**Comment by TheSunCat** [comment]
Ah darn, that was the issue. I did (and was using the hyprland-specific AUR package for a while), but since I saw the module in the Waybar wiki I thought it may have been enabled in the official build.
Sorry!

**Comment by c3n21** [comment]
> did you read https://github.com/hyprwm/Hyprland/wiki/FAQ#i-want-to-use-waybar-but-the-workspaces-dont-work and added
> 
> ```
> #define HAVE_WLR
> #define USE_EXPERIMENTAL
> ```
> 
> on top of include/factory.hpp?

Is there any reason why this isn't defined upstream?
