### ISSUE TITLE
`width` parameter renders bar incorrectly

### ISSUE THREAD

**Issue by marcothms** [Alexays/Waybar#1648]
When using the bar on the left side and trying to specify then `width` parameter, the bar instead gets rendered in the middle of the screen.

Without:
![image](https://user-images.githubusercontent.com/39596050/183282882-ad87035e-73ce-47b1-a80d-539f384e2a4b.png)

With `width` property, it just moves it to the center of the screen:
![image](https://user-images.githubusercontent.com/39596050/183282894-7175ff78-0a96-46cc-8667-5b32697a5779.png)

When adding the `height` property, it get rendered properly to the left side of the screen:
![image](https://user-images.githubusercontent.com/39596050/183282916-465e3676-79ea-4352-aa44-4e4d7fe73b10.png)

When using `"position": "bottom"`, the bar is, correctly, rendered in the middle of the screen:
![image](https://user-images.githubusercontent.com/39596050/183282951-32604684-3559-4027-9e4c-1b6650e6eaa7.png)

I think the problem is, that you assume, that the bar is always on the top or bottom, so this bug is just a corner case.

**Comment by Dieff** [comment]
I ran into the same issue. It seems to have been introduced between Waybar v0.9.10 and Waybar v0.9.13.

My workaround is to set a `min-width` property in CSS, but that doesn't quite work the same way.

**Comment by daangoossens22** [comment]
This is probably a duplicate of #1568, for which a fix is already merged into master. But this hasn't made it to a release yet. So if you really want to set the width and have a vertical bar, you'll have to build from master until a new release is out.

**Comment by marcothms** [comment]
Looks like it fixes my problem, i somehow didn't find the other issue eventhough i looked through them. I'll close this then! My workaround was to set extra margin on one of the modules, instead of using width.
