### ISSUE TITLE
Add ability to configure styles in groups

### ISSUE THREAD

**Issue by selfuryon** [Alexays/Waybar#1649]
Hello!
Currently, we can apply styles only to three big predefined groups: `modules-left`, `modules-center`, `modules-right`. I also found a #1305 module group feature ,but don't know it allows hierarchy configuration or not, hope yes.
It will be an excellent thing to have the ability to apply a style to these hierarchy groups. For example, this appearance could be possible to configure:
![image](https://user-images.githubusercontent.com/2993917/183408124-b4474025-dbb5-4066-a734-748f2146d119.png)
Without groups and hierarchy, it is possible to configure only like that:
![image](https://user-images.githubusercontent.com/2993917/183408613-49252ee4-1740-4163-a4a1-37043363bf2a.png)

**Comment by p2p-sergey-y** [comment]
I found out that I can do the same layout by using margin and padding :)

**Comment by selfuryon** [comment]
I found out that I can do this easily by using padding and margin only :)

**Comment by Keremimo** [comment]
How! How did you do it??? HOW???

**Comment by selfuryon** [comment]
@Keremimo I don't remember exactly, but I think I just added something like `margin-right: -15px;` with `padding-right` combination.

**Comment by Keremimo** [comment]
@selfuryon I did it in the end, thank you! :)
