### ISSUE TITLE
Q: Which dependencies are build time only?

### ISSUE THREAD

**Issue by CaptainBloodz** [Alexays/Waybar#165]
Hi,
Could you please tell which packages build only dependencies packages, maybe in readme. Despite I have a couple of ocaml packages required with ocamlopt config enabled, I bet I have  quite a uneducated guess there; so some help would be approcated.
Thks 4 ur attention.

**Comment by Alexays** [comment]
I'm sure that is listed on the readme. lines with brackets [] are optional

**Comment by CaptainBloodz** [comment]
Ok, 
I was only considering these brakets as possibly refering to config options.
Thks

**Comment by CaptainBloodz** [comment]
Ok, 
I was only considering these brakets as possibly refering to config options.
Thks

**Comment by CaptainBloodz** [comment]
Ok, 
I was only considering these brakets as possibly refering to config options.
Thks
