### ISSUE TITLE
 character display ends each waybar colored block

### ISSUE THREAD

**Issue by CaptainBloodz** [Alexays/Waybar#166]
There this strange display of  character at the end of each colored block.
Default config file seems full of it.
Libreoffice character table reports:
Hexa U + 20
Decimal 1

My guess is that my system is missing something for proper display.
Any idea?

**Comment by Alexays** [comment]
You need to install the fontawesome-otf font :)

**Comment by CaptainBloodz** [comment]
media-fonts/fontawesome:  The iconic font, I guess

Additionnal guess is that it should be install whether libdbusmenu-gtk3 is installed or not?

Another depencency for the README maybe...

ThksBOQ

**Comment by Alexays** [comment]
No version constraint for fontawesome :)
And yes libdbusmenu-gtk3 is for the tray module

**Comment by Arnaudv6** [comment]
For what its worth: I use a custom font for my icons, and was hit by this problem:
a wild guess was that pango was searching for the `space` glyph which of course I did not fill.
I solved it having my icons in `<span font=\"my font\">` tags. My spaces and text out, with default font.
Bump me if needed more precision: I am not on my machine now, but only answering from memory.

**Comment by weasnerb** [comment]
I can confirm that wrapping the custom icons in a `<span font='my-font'>` tag does fix this, however now when I hover over the items, the info that pops up in the middle of the screen includes the spans. This can be seen in the attached picture:
![2019-02-26-112402-focused](https://user-images.githubusercontent.com/24311514/53436693-00671780-39b9-11e9-8add-5c66da36ba5f.png)

**Comment by Robinhuett** [comment]
Try using `[otf-font-awesome](https://www.archlinux.org/packages/community/any/otf-font-awesome/)` instead of the ttf version

**Comment by Arnaudv6** [comment]
> You need to install the fontawesome-otf font :)

I overlooked the "otf" part of the name. Any rationnale for why `.otf` is required? Are there more feature imparities to expect?

**Comment by Alexays** [comment]
Look at https://github.com/FortAwesome/Font-Awesome/issues/13067 for some informations.
Gtk try to use the font awesome space character just after the font awesome icons, but that's fail.

**Comment by Arnaudv6** [comment]
https://gitlab.gnome.org/GNOME/pango/issues/265
