### ISSUE TITLE
idle_inhibit tooltip-format

### ISSUE THREAD

**Issue by daveriedstra** [Alexays/Waybar#1663]
Seems like the idle_inhibit module doesn't have a tooltip-format option and just uses the {state} format string. It would be good to have a tooltip-format like eg the battery, network, and wlr/taskbar modules.

**Comment by bd-g** [comment]
@daveriedstra Can this be closed now?

**Comment by daveriedstra** [comment]
@bd-g yes, thanks for asking and thanks @asas1asas200 for implementing. I didn't notice it had been done :)
