### ISSUE TITLE
Battery showing 0%

### ISSUE THREAD

**Issue by AblatedSprocket** [Alexays/Waybar#1664]
Waybar works great on my laptop and desktop, but on my pinephone, the battery shows 0%. I set the bat property to axp20x-battery, which is the name of the directory in /sys/class/power_supply containing the capacity, uevent, type, and status files. Sometimes the proper charge shows up, but I haven't determined why. It returns to zero as soon as I start charging the phone. Should bat be pointing to a different location?

**Comment by Alexays** [comment]
Should be better on master
