### ISSUE TITLE
Battery module keeps switching states while charging

### ISSUE THREAD

**Issue by 6b6279** [Alexays/Waybar#1666]
Hello,

I have configured the battery module followingly:

```
    "battery": {
        "bat": "BAT0",
        "interval": 60,
        "design-capacity": true,
        "states": {
            "warning": 30,
            "critical": 15
        },
        "format": "<span color=\"#BBBBBB\">BAT:</span> {capacity}% ({time} rem.)",
        "format-critical": "<span color=\"#BBBBBB\">BAT:</span> <span color=\"#ff0000\">{capacity}%</span> (only {time} rem.)",
        "format-charging": "<span color=\"#BBBBBB\">BAT:</span> <span color=\"#0aff0a\">{capacity}%</span> ({time} until full)",
        "tooltip": false
    }
```

For some reason, the format keeps switching between `default` and `charging` while the adapter is plugged. While in the `default` state, `capacity` and `time` are evaluated to "" (see picture below).
![20220826_11h03m01s_grim](https://user-images.githubusercontent.com/109346960/186868871-a4f4446d-65b7-496b-baeb-4aab62326e8e.png)
After a random amount of time (usually before the update interval is elapsed), the state will switch to `charging`, but displaying a (most likely) incorrect `time` value.
![20220826_11h00m57s_grim](https://user-images.githubusercontent.com/109346960/186869254-db073c8b-9468-402d-8234-2a5aa3d98495.png)
Finally, after a few minutes, the correct `time` value is displayed.
![20220826_11h01m36s_grim](https://user-images.githubusercontent.com/109346960/186869387-4c12b7f9-b9d0-46c1-a221-ec76dbb2c2aa.png)
Eventually the module will switch to the `default` state again, starting the cycle anew.

Waybar doesn’t output any warnings into stdout while the problem occurs.

**Comment by Alexays** [comment]
Should be better on master
