### ISSUE TITLE
libnl >=v3 & libsigc++ >=v2  dependency?

### ISSUE THREAD

**Issue by CaptainBloodz** [Alexays/Waybar#167]
Arch [https://aur.archlinux.org/packages/waybar-git/](url) states dependency to libnl >= v3.
Can you confirm the version constrain?

Likewise it also states dependency to libsigc++ >= v2.
Can you confirm the version constrain?

Thks 4 ur attention.

**Comment by Alexays** [comment]
Version 3 or greater is required for libnl, but for libsigc++ i don't know, I'll check it out
