### ISSUE TITLE
Waybar acts different with the exact same command

### ISSUE THREAD

**Issue by MelihDarcanxyz** [Alexays/Waybar#1676]
The title may not be self explanatory so here it goes.

If I run ```waybar``` from ```sway``` config file as autostart, or ```river``` init file as autostart, or run it with ```rofi```, or with ```riverctl spawn waybar```;
1st and the 3rd bars are the results.

If I run it from my ```foot``` terminal or just run a script that calls ```waybar```, the 2nd bar is the result. I couldn't understand why and couldn't come up with a solution. I hope you can help me with that.

![waybar-debug](https://user-images.githubusercontent.com/57872471/188239565-c7f1eb28-7bd5-4c43-bf49-aa4b21a10635.png)

The explanation may be vague but I think this is a problem with the caller. Maybe sway or river or rofi doesn't have necessary permissions. Or bash does something extra I don't know. But my scripts were called in bash too, there should be no difference.

Here, some examples:

My river autostart script which run at the start
```bash
#!/bin/bash
riverctl spawn waybar
```

An alternative to it to test things
```bash
#!/bin/bash
waybar &
```

My sway config's related part
```bash
exec waybar
```

Running ```rofi``` and then typing ```waybar```

They all give me the 1st and the 3rd bars.

The interesting thing is:
```bash
#!/bin/bash
waybar &
```
This one gives me the 2nd bar if I run it from my terminal but not from river at startup.

```bash
#!/bin/bash
riverctl spawn waybar
```
This one still gives 1rd and 3rd even if I call it from terminal.

This feels like black magic to be honest and I may not be the best explainer. Please let me know if you need any extra info.

**Comment by inga-lovinde** [comment]
> Maybe sway or river or rofi doesn't have necessary permissions. Or bash does something extra I don't know. 

My guess would be the environment.
At least on my system, `env > ~/env.txt` and `riverctl spawn "env > ~/env.txt"` ran from the same foot produce slightly different results, and maybe that slight difference matters to waybar.

**Comment by MelihDarcanxyz** [comment]
You're right. I've checked them and one particular line makes them look different. I wrote a wrapper and now they all look like the second bar. Here is the wrapper:
```bash
#!/bin/bash

export GTK_THEME=Arc-Dark
exec waybar

```
I'm not sure what makes them different. But here it is. My problem is solved but I'm not sure if this behavior is a problem so I'll leave this issue open for the maintainers to decide.

**Comment by MelihDarcanxyz** [comment]
According to this, this is a feature:
https://github.com/Alexays/Waybar/wiki/Styling#making-waybar-follow-the-gtk-theme
Closing the issue.
