### ISSUE TITLE
Q: How it the tray supposed to work?

### ISSUE THREAD

**Issue by CaptainBloodz** [Alexays/Waybar#168]
Sorry to ask but I not sure how the tray is supposed to work?
So I'm not sure how to check if it does works.

AFAIK dependencies are installed.
But using the default config file, nothing shows up.
I also ried to click somewhere at the end of the bar, due to my possibly faulty understanding og the config file.. Nothing.

Maybe I should search and possibly tweak config options passed to meson...

Thks 4 ur attention.

**Comment by Alexays** [comment]
You need `libappindicator-gtk3` (added to AUR package)
and launch apps with `env XDG_CURRENT_DESKTOP=Unity slack`

**Comment by Epse** [comment]
This does also not work for everything, for example `blueberry-tray` does not work

**Comment by Alexays** [comment]
Cause some apps use the old protocol so we need to implement a XEmbed proxy #254
