### ISSUE TITLE
dpgraham4401's link leads to nowhere

### ISSUE THREAD

**Issue by Gxnum** [Alexays/Waybar#1680]
I like dpgraham4401's example on the Examples page in Waybar, but the link does not lead anywhere. I found his config files in GitHub, here is the real link: https://github.com/dpgraham4401/.dotfiles/tree/Fedora-ws/sway/.config/waybar

Close this issue once you read this.

**Comment by apiraino** [comment]
@Gxnum FYI the wiki of this repository is open for edits, feel free to apply changes to fix dead links.

In this case you can choose to fix the dead link with one of these configs: [this](https://github.com/dpgraham4401/.dotfiles/tree/fedora/sway/.config/waybar) or [this](https://github.com/dpgraham4401/.dotfiles/tree/Arch-M1/sway/.config/waybar) (not sure which one, I didn't test those configs)
