### ISSUE TITLE
Waybar ignoring config at ~/.config/waybar/config.json 

### ISSUE THREAD

**Issue by ApproachingApathy** [Alexays/Waybar#1682]
I'm using waybar with river and couldn't get the river modules to work. On starting waybar I notice this `[info] Using configuration file /etc/xdg/waybar/config`. This is despite the fact that that I have a `config.json` in `~/.config/waybar`.

**Comment by terminatorbs** [comment]
try deleting the extension. call the file just "config". 

Yes it's annoying, my VsCodium keeps thinking it is json and marking it all red, but it's apparently jsonc. i wish we could have the option of waybar looking for files with extension, and if none found look for the current file for compatibility.

**Comment by ApproachingApathy** [comment]
I feel a bit silly now. I should've read more carefully.
