### ISSUE TITLE
In some applications the tray bar is clicked and then the next click is incorrectly positioned.

### ISSUE THREAD

**Issue by st0nie** [Alexays/Waybar#1683]
## System information
OS:Arch Linux
wm:Hyprland

## How to Reproduce
Open an application from the libappindicator tray.(for example,telegram desktop)
Click other module in waybar.
## Expected results
The clicked button is triggered.
## Actual results
The last clicked tray icon is triggered again.(In this case it is telegram)

**Comment by xd003** [comment]
Can confirm this bug exists even now & is really annoying

**Comment by malteo** [comment]
can confirm too, latest arch, latest hyprland, latest waybar

**Comment by BionicKnight** [comment]
I confirm too, Arch, using aur packages hyprland-git and waybar-hyprland, all updated
By a brief test it seems to happens only with QT apps, KeepassXC and Telegram (and It's forks), while blueman tray and steam don't seem to behave wrongly, but it can be just my luck, can anyone with more tray apps confirm this?

**Comment by Gajus84** [comment]
Seems also to affect custom modules. For example Terminal-Programs like NeoMutt that get executed by click.

**Comment by ston-afk** [comment]
Maybe this is a hyprland specific issue
I can't reproduce it on wayfire.

在 2022/11/28 01:25, Gajus84 写道:

**Comment by k4j8** [comment]
I am having this issue with Sway on Arch. Waybar version is 0.9.16-2. For me, activating a custom module causes all other clicks to retrigger the custom module until I reload my Sway configuration.
