### ISSUE TITLE
Backlight module icon missing

### ISSUE THREAD

**Issue by J0nnyMak0** [Alexays/Waybar#1688]
I have the latest waybar running on Arch. I have otf-font-awesome installed. When I look at the default config file, I see all icons except the ones for backlight module. Icon next to backlight percentage is missing in the bar. Any suggestions as to what if any other fonts I'm missing?
![backlight-icon](https://user-images.githubusercontent.com/6559121/190635066-95786bd7-4280-4ae8-a04f-bb8c0c2f9722.png)

**Comment by brodi1** [comment]
@J0nnyMak0 do you have ttf-font-awesome installed too? How does your waybar config look like? (the backlight part)

**Comment by J0nnyMak0** [comment]
> @J0nnyMak0 do you have ttf-font-awesome installed too? How does your waybar config look like? (the backlight part)

Yes, I have ttf-font awesome installed. I'm using the default config file. In there, brightness icons display as a bunch of empty boxes like so:
```
 "format-icons": ["", "", "", "", "", "", "", "", ""]

**Comment by brodi1** [comment]
@J0nnyMak0 I don't know if these icons use font-awesome....I personally just use two sun emoji's like this: 
`"format-icons": ["🔅", "🔆"]`

If you want to choose one from font-awesome there isn't much to choose from....
paid version: https://fontawesome.com/search?q=brightness&o=r
free version: https://fontawesome.com/search?q=brightness&o=r&m=free

**Comment by J0nnyMak0** [comment]
I see. Ok, thanks. I'll use those then.

**Comment by dryya** [comment]
I was able to get those icons with ttf-meslo-nerd-font-powerlevel10k, available in the AUR or from here: https://github.com/romkatv/powerlevel10k-media

However, I just ended up reverting the brightness icons to those from this commit: https://github.com/Alexays/Waybar/pull/873/commits/2273ade3590edb572ba234e8c2d6bf3e0da3bb9b

Perhaps a note about compatible fonts should be added to the wiki? I also still have some issues with certain glyphs, like "hands-free": "", despite having the complete set of Noto fonts, font-awesome, etc. installed. I think it might be worth considering changing some of these very obscure glyphs which aren't included in most fonts.

**Comment by mlazzarotto** [comment]
What package for ubuntu?
I installed `fonts-font-awesome` but no brightness icon

**Comment by br-olf** [comment]
The font packages you need are *Font Awesome* and *Meslo LG*.
Using arch you can install `ttf-meslo-nerd` and `ttf-font-awesome` from the official repo and everything works.

@mlazzarotto I don't know why this font is not packaged for ubuntu but you can follow this to install them: https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
