### ISSUE TITLE
bluetooth detection not working

### ISSUE THREAD

**Issue by dkrieger** [Alexays/Waybar#169]
pulseaudio segment does not detect bluetooth.

relevant portion of `pactl info sinks`:

```
Sink #6
	State: RUNNING
	Name: bluez_sink.40_EF_4C_39_89_B2.a2dp_sink
	Description: Razer Leviathan
	Driver: module-bluez5-device.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 31
	Mute: no
	Volume: front-left: 19643 /  30% / -31.40 dB,   front-right: 19643 /  30% / -31.40 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: bluez_sink.40_EF_4C_39_89_B2.a2dp_sink.monitor
	Latency: 60133 usec, configured 45317 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		bluetooth.protocol = "a2dp_sink"
		device.description = "Razer Leviathan"
		device.string = "40:EF:4C:39:89:B2"
		device.api = "bluez"
		device.class = "sound"
		device.bus = "bluetooth"
		device.form_factor = "speaker"
		bluez.path = "/org/bluez/hci0/dev_40_EF_4C_39_89_B2"
		bluez.class = "0x240414"
		bluez.alias = "Razer Leviathan"
		device.icon_name = "audio-speakers-bluetooth"
	Ports:
		speaker-output: Speaker (priority: 0, available)
	Active Port: speaker-output
	Formats:
		pcm
```

`pactl info`:

```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 32
Server Protocol Version: 32
Is Local: yes
Client Index: 704
Tile Size: 65472
User Name: redacteduser
Host Name: redactedhost
Server Name: pulseaudio
Server Version: 12.2-rebootstrapped
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: bluez_sink.40_EF_4C_39_89_B2.a2dp_sink
Default Source: alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie: a098:0fbb
```

Built Waybar from d0370ac, installed dependencies (from Fedora 29 repos, excepting wlroots 0.3.0 and sway 1.0 rc1 built from source in the past week) until meson found everything (including optional dependencies).

Edit: for clarity, I'm referring to the `format-bluetooth` functionality in the pulseaudio module

**Comment by Alexays** [comment]
Yep, but you can still define `bluez_sink.40_EF_4C_39_89_B2.a2dp_sink` in your config with an icon :)

**Comment by dkrieger** [comment]
The documentation and code suggest this is an existing feature, and the `a2dp_sink` string the code checks for / tries to check for is present. Is that code/feature abandoned?

I appreciate you sharing a workaround, looks like I'll need to do that for every Bluetooth device I connect.

**Comment by Alexays** [comment]
Oh yeah forgot that feature, but you want a special icon, right? Because what is implemented is the ability to use a class

**Comment by FlorianFranzen** [comment]
I think he is talking about the ```format-bluetooth``` options of the pulseaudio module, that is broken.

**Comment by dkrieger** [comment]
Correct. Edited issue for clarity
