### ISSUE TITLE
Network module does not update when switching interface

### ISSUE THREAD

**Issue by Dordovel** [Alexays/Waybar#1690]
I`m using nmcli for switch interface:

```
#!/usr/bin/bash
IFS=$'\n'
newInterface=$(nmcli -g name,type connection show | grep "ethernet" | cut -d ':' -f 1 | rofi -dmenu)

if [ ! -z "$newInterface" ]
then
    activeInterface=$(nmcli -g name,type connection show --active | grep "ethernet" | cut -d ':' -f 1);

    if [[ ! -z "$activeInterface" ]]
    then
        for interface in $activeInterface
        do
            nmcli c down "$interface";
        done
    fi

    nmcli c up "$newInterface";
fi
```

![qwe2](https://user-images.githubusercontent.com/33456625/190976899-beb91f67-7aeb-4321-972d-9b9b144ca928.png)
![qwe](https://user-images.githubusercontent.com/33456625/190978358-15c4cf5a-c6d5-4db7-824b-101cea8f30f5.png)
![qwe1](https://user-images.githubusercontent.com/33456625/190976939-7caf3719-1159-4669-ba37-b9370f2a0f43.png)

**Comment by Alphare** [comment]
Also, a network module with an empty "disconnected"' format correctly does not appear when started with the interface disconnected, but turning off the interface *after* Waybar is initialized will show the default "format" instead of the module disappearing.
