### ISSUE TITLE
Waybar crashes when enabling a disabled CPU

### ISSUE THREAD

**Issue by Nogesma** [Alexays/Waybar#1692]
When using the CPU module, and enabling a disabled CPU, it crashes in the getCpuUsage() function because [in this loop](https://github.com/Alexays/waybar/blob/710f895/src/modules/cpu/common.cpp#L78) prev_times.size() < curr_times.size(). 

I think the best option would be to do something like this
```cpp
std::vector<std::tuple<size_t, size_t>> curr_times = parseCpuinfo();
while (prev_times.size() != curr_times.size())
{
    prev_times_ = curr_times;
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    curr_times = parseCpuinfo();
}
```
or to just report the cpu usage without the new core until the next function call
```cpp
for (size_t i = 0; i < std::min(prev_times.size(), curr_times.size()); ++i)
```

**Comment by Alexays** [comment]
Can you open a PR with your fix?

**Comment by chairclr** [comment]
I recently encountered this issue. Any ETA on this?

**Comment by cetio** [comment]
just encountered this issue, can we get an ETA for a fix?

**Comment by hakusaro** [comment]
I realize that this is very esoteric, but for users of certain highly eccentric workflows, this is infuriating.
