### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by Anakael** [Alexays/Waybar#1693]
After recently updates I've faced with problems with icons: some of them have normal size, but some of them - not.
Examples:
![image](https://user-images.githubusercontent.com/17771546/191624522-33caff1f-ec86-4549-83a2-b5b309d1afa8.png)
![image](https://user-images.githubusercontent.com/17771546/191624541-2ddcaf40-0a7f-44eb-9c5e-9732a9a5d1c2.png)
They used to have normal size before.

Config:
```json
    "sway/workspaces": {
        "format": "{icon}",
	    "on-click": "activate",
        "format-icons": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "urgent": "",
            "default": ""
        }
    },

```

waybar version: 0.9.13

**Comment by lygamac** [comment]
You have probably installed nerd font (or patched) that uses the mono variant.

The default `style.css` won't match font awesome first but rather nerd fonts if the name is not exactly correct.

Run `fc-list | grep -i "font awesome"`, get the name of font awesome and put it in the font-family of your `style.css`, e.g.:
```css
font-family: NotoSans, FontAwesome6Free, SymbolsNerdFont;
```
