### ISSUE TITLE
Clock Format No Longer has an Option for No Leading Zeros

### ISSUE THREAD

**Issue by WammKD** [Alexays/Waybar#1696]
It may've been a change in the version update; I used to be able to use `%l` to dislay the 12-hour (I assume there was an equivalent for 24-hour, as well) hour without a leading zero: e.g. `9` vs. `09`.

After updating to v0.9.13, Waybar threw an error of an invalid format being used and it doesn't seem like an equivalent is, now, available. The option to not have leading zeros seems entirely removed.

**Comment by JStation** [comment]
I'm also having this issue. It looks like the formatting library used by waybar doesn't support the `%l` or `%k` sequences nor the `-` or `_` modifiers that remove padding zeroes or replace them with spaces respectively.

There is a little more detail on #1469

**Comment by JStation** [comment]
The fmt issue might be more directly relevant:
fmtlib/fmt#2959

**Comment by LukashonakV** [comment]
Hi @WammKD can you close the issue as a clone of https://github.com/Alexays/Waybar/issues/1469
Please check the last comment in it

**Comment by LukashonakV** [comment]
Hi @WammKD , up :)
