### ISSUE TITLE
\n does not do line break 

### ISSUE THREAD

**Issue by Spaxly** [Alexays/Waybar#1698]
```
"clock": {
        "format": "<span>{:%I\n%M %p}</span>",
        "max-length": 40,
    },
```

The code above does not break into a new line, also without the span tag, it does not work.

**Comment by Spaxly** [comment]
\r dos not work either.

**Comment by Spaxly** [comment]
![1664299377_grim](https://user-images.githubusercontent.com/68564017/192595449-9e2efc07-971c-43b0-badc-a0f3d9492a8e.png)
this is what happens.

**Comment by LukashonakV** [comment]
Hi @Spaxly , can you:

1. Check again using the freshest waybar(from master)
2. For test purposes do not use <span>

Actually if works well for me
![ps_2023-03-01-12_51_50](https://user-images.githubusercontent.com/23121044/222104426-10bf32fc-bd13-4ec5-881d-d5e11a2ed7ab.png)

**Comment by LukashonakV** [comment]
Hi @Spaxly , ping

**Comment by LukashonakV** [comment]
@Spaxly, please close the issue then. Thanks )

**Comment by LukashonakV** [comment]
@Spaxly  please close the issue then as you an author. Thanks :)
