### ISSUE TITLE
Bug: Sway/window "{shell}" format replacement not working (argument not found)

### ISSUE THREAD

**Issue by paulodiovani** [Alexays/Waybar#1708]
I'm using Waybar `v0.9.13` on Manjaro and trying to include the shell (xdg_shell or xwayland) information on the window module, but that does not work. It makes the module not show and throw errors to stderr.

Config: 

```json
  "sway/window": {
    "format": "{title} [{shell}]"
  },
```

Full config (without the shell, bc it does not work): https://github.com/paulodiovani/dot-files/blob/main/home/user/.config/waybar/config

## Expected behavior

- Show the window name + shell in the desired format (e.g. "Zoom [xwayland]")

## Current behavior

- When included `{shell}` on `sway/window#format` config, the module is not rendered (nothing is shown)
- Sway output includes (in journalctl): `[error] sway/window: argument not found`

## Screenshots

Without shell. Format: `{title}`

![image](https://user-images.githubusercontent.com/1295197/194080609-606633ee-97ce-4b8a-96a4-86072e2233a9.png)

With shell. Format: `{title} [{shell}]`

![image](https://user-images.githubusercontent.com/1295197/194080451-90b46838-6d26-485d-a107-23ad3ccf0e82.png)

**Comment by schauveau** [comment]
The "shell" feature was added on Aug 10, 2022 so after the release of waybar 0.9.13 in may. You will have to wait for the next release 0.9.14 or compile it yourself from master.

**Comment by paulodiovani** [comment]
Perfect. Compiling from latest git worked. :)

![image](https://user-images.githubusercontent.com/1295197/195395701-cff4f61c-386a-44bf-9dd0-4780ba8749a4.png)

Thanks.
