### ISSUE TITLE
Man pages (improvement)

### ISSUE THREAD

**Issue by docquantum** [Alexays/Waybar#171]
There are no man pages for waybar. I think this would be useful for users that might need to quickly look up a config option. More or less just manualizing the wiki.

I'd be willing to do this as well if no one picks it up (I'd need to learn how to make a man page first).

(Also, I wasn't able to add a label to it for some reason)

**Comment by Alexays** [comment]
Yeah, it's a nice to have but i don't have much time right now, so if you have the motivation to do it :)

**Comment by docquantum** [comment]
So, I've been looking into it a bit and asking a few friends that have done this. I've also looked at a few other projects to see how they handle man page creation.

I've found that one of the easiest ways to accomplish this would be to write the manual in markdown-like format, which is mostly done through the wiki. It'd just need to be reformatted and reorganized a bit. 

With the markdown, we could use something such as [scdoc](https://drewdevault.com/2018/05/13/scdoc.html) which is what sway uses to create its manpages.

In fact, since this project coincides with sway quite well, I think it wouldn't be bad if we model it after their method.

[Here's an example](https://github.com/swaywm/sway/blob/master/sway/sway.1.scd)
[Here's the git for scdoc](https://git.sr.ht/~sircmpwn/scdoc)

**Comment by Asgavar** [comment]
@docquantum: have you already started? (if you still are willing to do this ofc ;])

**Comment by docquantum** [comment]
@Asgavar I have not, I've been busy with schoolwork, if no one picks it up by mid May, I'll try and start it.

**Comment by MichaelAquilina** [comment]
I've made my first attempt at adding a man page in this PR using `scdoc`: https://github.com/Alexays/Waybar/pull/431
