### ISSUE TITLE
Some child processes are still left open when waybar terminates 

### ISSUE THREAD

**Issue by matejdro** [Alexays/Waybar#1713]
To reproduce:

1. Setup a custom module (and add that module to the waybar):

```json
    "custom/process-broken-demo": {
        "return-type": "json",
        "escape": false,
        "exec": "$HOME/.config/waybar/process-test.sh"
    }
```

2. Put this into the `process-test.sh`:

```bash
#!/usr/bin/env bash

function_call() {
    sleep 1
}

while read line; do
        function_call
done < <(sleep 9999)
```

3. Run `ps -u | grep process-test`. Note that the only returned entry should be the grep process.
4. Start waybar.
5. Run step 3 again. Note that there are two extra processes now, started by waybar
6. Close waybar
7. Run step 3 again. Note that one extra process is still there, even though waybar has been closed

Probably related to #358?

**Comment by Alexays** [comment]
Can you check with #1748?

**Comment by matejdro** [comment]
Thanks for looking into it. I tried it out and it still seems to happen. I've updated the first post with full reproduce steps, so it should be much easier to reproduce now.

**Comment by lilydjwg** [comment]
I noticed that this issue states a different case than what I had and have fixed. I have zombies when a monitor disconnects and reconnects repeatedly, but this issue is about waybar termination.

**Comment by matejdro** [comment]
@Alexays Can you reopen this issue? From my previous testing, PR does not fix this issue.

**Comment by L11R** [comment]
Also there is a problem with `mediaplayer.py` which is python and does not use process substitution.
![изображение](https://user-images.githubusercontent.com/5345489/236147622-95a30b7c-c65b-4c0c-b9e8-090db9b2bd34.png)
