### ISSUE TITLE
Upower module causes a segfault when when docking/undocking laptop

### ISSUE THREAD

**Issue by gnull** [Alexays/Waybar#1714]
For some weeks I've been experiencing crashes when connecting or disconnecting my two external monitors. The crashes happen about 50% of the time.

I'm using Kanshi. When I connect my two external monitors, Kanshi puts them side by side and disables the laptop screen. When I disconnect them, Kanshi enables back the laptop screen and sets its fractional scaling to `1.4`.

```
$ waybar -v
Waybar v0.9.13-158-g5da45ec (branch 'master')
```

- [Crash log](https://paste.sr.ht/~ph14nix/7119b195ceb5d708e25e53d49105cba9e88fcd68). The “no modem specified” error comes from one of my custom modules I think, so just ignore it. You can also see it throwing some weird characters to the ouput way before crashing, so it might be hinting at some memory corruption going on there.
- [Coredumpctl output](https://paste.sr.ht/~ph14nix/dbb3048fae1bd7bc44a6c32bd2abdb86713c9d64). I'm running the release build of Waybar with no debugging symbols, but I still show backtrace in this log. Hope it helps.

I can reproduce the same behavior even if I disable Kanshi and remove the custom modules (I'm saying this because I saw other issues that mention these as possible causes of crashes).

Let me know if you want me to provide any more logs or a coredump.

Ivan

**Comment by gnull** [comment]
https://paste.sr.ht/~ph14nix/1feb699a0574da3e324af2869c9d64bce10f1eb1

I just tried something new. I ran Waybar under Valgrind and it printed a lot of errors as I was connecting/disconnecting monitors, and right before crashing. I can't interpret this easily since I'm not an expert in Valgrind or Waybar codebase, but posting it here in case it helps.

**Comment by Alexays** [comment]
@ErikReider any ideas on this?

**Comment by ErikReider** [comment]
Hmm. Couldn't reproduce with the UPower module but found a similar issue with the Gamemode module

**Comment by ErikReider** [comment]
@gnull What modules are you running?

**Comment by gnull** [comment]
Haven't thought about it before. But maybe I can try disabling different
modules and try to identify the one that is causing the problem.

**Comment by gnull** [comment]
@ErikReider, here the full list:

```json
"modules-left": ["sway/workspaces", "sway/window"],
"modules-center": [],
"modules-right": ["tray", "backlight", "pulseaudio", "custom/modemmanager", "network#wlan0", "network#eth0", "temperature", "upower", "clock"],
```

I already tried disabling the custom module, the problem was still there.

**Comment by ErikReider** [comment]
Seems like the Upower module is what's causing this issues. Does it still segfault if you remove that module? @gnull

**Comment by gnull** [comment]
The options are:

```json
"upower": {
     "format": "{percentage} ",
     "icon-size": 20,
     "hide-if-empty": true,
     "tooltip": true,
     "tooltip-spacing": 20
}
```

CSS config is:

```css
#upower {
	padding-left: 10px;
	padding-right: 10px;
	background: #689d6a;
	color: #282828;
}
```

I tried replacing upower by battery, and I can't reproduce the crash anymore. Normally, the crashes were very "reliable", I'd get them every time or every second time. Thanks a lot for the suggestion!

Ivan

**Comment by ErikReider** [comment]
What devices are shown in Upower?

**Comment by gnull** [comment]
Here it is. It lists one Bluetooth headset and my laptop's internal battery. Interesting, I haven't thought there might be something other than monitors causing the issue, but it could also be something with the power sources which change when docking/undocking my laptop.

```
$ upower -d
Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              Thu 20 Oct 2022 12:58:47 PM CEST (1904 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              no
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               LGC
  model:                45N1113
  serial:               <removed>
  power supply:         yes
  updated:              Thu 20 Oct 2022 01:30:24 PM CEST (7 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              17.64 Wh
    energy-empty:        0 Wh
    energy-full:         18.45 Wh
    energy-full-design:  23.48 Wh
    energy-rate:         0 W
    voltage:             12.498 V
    charge-cycles:       181
    percentage:          95%
    capacity:            78.5775%
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT1
  native-path:          BAT1
  vendor:               SMP
  model:                45N1736
  serial:               <removed>
  power supply:         yes
  updated:              Thu 20 Oct 2022 01:30:24 PM CEST (7 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              38.08 Wh
    energy-empty:        0 Wh
    energy-full:         44 Wh
    energy-full-design:  52 Wh
    energy-rate:         23.549 W
    voltage:             11.81 V
    charge-cycles:       78
    time to empty:       1.6 hours
    percentage:          86%
    capacity:            84.6154%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'
  History (charge):
    1666265364	86.000	discharging
  History (rate):
    1666265424	23.549	discharging
    1666265394	10.356	discharging
    1666265364	11.668	discharging
    1666265334	8.046	discharging

Device: /org/freedesktop/UPower/devices/headset_dev_<MAC removed>
  native-path:          /org/bluez/hci0/dev_<MAC removed>
  model:                Roxcore Vibe S
  serial:               <removed>
  power supply:         no
  updated:              Thu 20 Oct 2022 12:50:03 PM CEST (2428 seconds ago)
  has history:          yes
  has statistics:       no
  headset
    warning-level:       none
    percentage:          80%
    icon-name:          'battery-missing-symbolic'
  History (charge):
    1666265431	0.000	unknown
  History (rate):
    1666265431	0.000	unknown

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              Thu 20 Oct 2022 01:30:24 PM CEST (7 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               discharging
    warning-level:       none
    energy:              55.72 Wh
    energy-full:         62.45 Wh
    energy-rate:         23.549 W
    charge-cycles:       N/A
    time to empty:       2.4 hours
    percentage:          89.2234%
    icon-name:          'battery-full-symbolic'

Daemon:
  daemon-version:  1.90.0
  on-battery:      yes
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: HybridSleep
```

**Comment by ErikReider** [comment]
Oh, so you're using a laptop dock with monitors and power connected through one cable?

**Comment by gnull** [comment]
![image](https://user-images.githubusercontent.com/7102119/196996383-e389b2eb-d664-4940-af57-9ea38ba6ed02.png)

It's not even a cable, but this kind of old-fashioned interface wit pins under the bottom of the laptop. The charger that connects to the docking station powers everything and charges the laptop.

**Comment by ErikReider** [comment]
Hmm. This could be quite difficult to debug on my end. A simple USB C dongle would do but I don't have one. Could you run `gdm` with waybar?

My simple guess of what this could be is the `device_notify` being executed in another thread while the module is being destroyed?

**Comment by gnull** [comment]
>Hmm. This could be quite difficult to debug on my end. A simple USB C dongle would do but I don't have one. Could you run `gdm` with waybar?

What do you mean exactly? Does waybar work on GDB (I mean, the login window thingie)?

Ivan
