### ISSUE TITLE
Disable or modify module popups from on hover [question]

### ISSUE THREAD

**Issue by docquantum** [Alexays/Waybar#172]
Is there anyway to control the popups that get created when hovering over modules. I would like to move them to the top of the screen and customize the look as well as what pop's up on hover. There doesn't seem to be any documentation on this.

e.g. Hover over battery opens the status popup at _top_ of screen with different style options.
A plus to this would be customizing what info is shown such as time to discharge (part of the acpi command so I'm sure it can be queried from /sys/class/power_supply, but I might be wrong)

**Comment by Alexays** [comment]
The fact that they positioned in the center is a bug, but yeah i can make a option to disable them

**Comment by Alexays** [comment]
Done in 83a6475510df2c3db325c6ba24b377858b487ca5
Just set in each module `"tooltip": false`
