### ISSUE TITLE
Border/Padding/Margin added to module after switch to AButton

### ISSUE THREAD

**Issue by ppascher** [Alexays/Waybar#1731]
Since commit (bisected) [button: Add AButton class](https://github.com/Alexays/Waybar/commit/b8322c4b4b023d8e6fbe8b6bf4100d6c60a06e42)
I get a border (maybe padding, margin?) next to my custom arrow module - before/after:
![image](https://user-images.githubusercontent.com/10400581/196479646-37256df7-3abe-4c81-8f50-b1e352740b35.png)

Each arrow is a simple separate custom module using the background-/font-color of the next/previous module.

```
#clock.time {                                                                   
  background: #2e3440;                                                          
  color: #e5e9f0;                                                               
  font-weight: bold;                                                            
}                                                                               
#custom-arrow10 {                                                               
  font-size: 17px;                                                              
  color: #2e3440;                                                               
  background: #3b4252;                                                          
}                                                                               
                                                                                
#clock.date {                                                                   
  background: #3b4252;                                                          
  color: #e5e9f0;                                                               
  font-weight: bold;                                                            
}                                                      
```
I tried setting border/margin/padding/box-shadow to 0 or none. 
Is there a way to restore the previous behavior?

**Comment by Alexays** [comment]
@pinselimo any ideas on that? thx :)

**Comment by pinselimo** [comment]
That could very well be the border value set in #1729 

@ppascher have you tried it after the latest merge today?

I can check it tomorrow, am on mobile atm

**Comment by ppascher** [comment]
I tried both before and after that commit. Issue exists in both.
My config code for the custom arrow is simply:
```
"custom/arrow1": {
        "format": "",
        "tooltip": false
    },
```
Thank you for looking into this.

**Comment by pinselimo** [comment]
> edit: setting the font size for the arrow from 17px to 27px and the padding is gone.

I found that you can also set the margin-right to a negative value. It doesn't seem to affect all text. The clock module has no extra margins. I also tried to set all button margins to zero in ``src/AButton.cpp`` itself and nothing changed.

**Comment by pinselimo** [comment]
Adding a space in front of the icon also fixes the issue.

**Comment by pinselimo** [comment]
Ok, I found the definite solution to the problem. Setting min-width to zero resolves the problem for all arrows without having to change each and every one of them:

~~~
* {
...
    min-width: 0;
...
}
~~~

**Comment by Alexays** [comment]
@pinselimo Can we foce the min width on the code side, in that we don't have a breaking change for the next version.

**Comment by ppascher** [comment]
Thank you @pinselimo. Adding min-width: 0 to my styles.css fixed the issue.

**Comment by Scrumplex** [comment]
I was using min-width and min-height to set the aspect ratio of my buttons to 1:1.

Now it doesn't work anymore and I don't know how to override this style.

https://github.com/Alexays/Waybar/blob/1374b0fce40f283b113e051f0558564fa1d9ad22/src/AButton.cpp#L22-L25

**Comment by pinselimo** [comment]
@Scrumplex I can look into it. Would you mind sharing the config snippet you used to achieve that aspect ratio?

**Comment by Scrumplex** [comment]
I basically just set
```
button {
  min-width: 32px;
  min-height: 32px;
}
```

**Comment by Alexays** [comment]
@Scrumplex Can you try with latest commit (d48eebd)

**Comment by Scrumplex** [comment]
> @Scrumplex Can you try with latest commit ([d48eebd](https://github.com/Alexays/Waybar/commit/d48eebd4d3d92d7a8f39cf28574dd8543c105b8a))

That works!
