### ISSUE TITLE
tooltip shown behind windows even when set layer to top on hyprland

### ISSUE THREAD

**Issue by Aleksanaa** [Alexays/Waybar#1745]
And if the window is right below the button, tooltip can never be toggled.

archlinux
waybar 0.9.13-2.1
hyprland r1906.b71d7c9-1 (latest git at this moment) or 0.16.0beta-1
![1](https://user-images.githubusercontent.com/42209822/197326103-59f4055f-8345-419a-8aa2-d900b5a69d36.png)
![2](https://user-images.githubusercontent.com/42209822/197326128-01c114c2-d4ed-4a0e-9a7d-7a24059eaab0.png)

```
// waybar-clock
    "clock": {
		"interval": 60,
		"align": 0,
		"rotate": 0,
        //"timezone": "America/New_York",
        "tooltip-format": "<big>{:%B %Y}</big>\n<tt><big>{calendar}</big></tt>",
        "format": " {:%H:%M}",
        "format-alt": " {:%a %b %d, %G}"
    },
```

```
    "include": "~/.config/waybar/modules",
    "name": "main-bar", 
    "id": "main-bar", 	
    "layer": "top", 	
    "mode": "dock", 	
    "exclusive": true, 	
    "passthrough": false, 
    "position": "top",
    "output": "eDP-1", 	
    "height": 36, 		
    "width": "", 		
    "spacing": 6, 		
    "margin": 0, 		
    "margin-top": 0, 	
    "margin-bottom": 0, 
    "margin-left": 0, 	
    "margin-right": 0, 	
    "fixed-center": true, 
    "ipc": true, 		
```

**Comment by Aleksanaa** [comment]
Should be something wrong with hyprland.

**Comment by revuwa** [comment]
Had exactly the sam issue, with more or less the same config.
Turns out it has something to to with the `"mode": "dock"`. 
I commented out just that one line, and tooltips workin' again for me \o/

**Comment by filipdutescu** [comment]
This bug is still present. I think there is an argument to be made with regards to reopening the issue maybe?

**Comment by Axenide** [comment]
> This bug is still present. I think there is an argument to be made with regards to reopening the issue maybe?

Have you tried with `"layer": top`? Worked for me.

**Comment by filipdutescu** [comment]
Yep, it only worked when not setting `mode`. Im on ArchLinux, on Waybar with Wayland support from AUR, if it helps.

**Comment by PolGZ** [comment]
> Yep, it only worked when not setting `mode`. Im on ArchLinux, on Waybar with Wayland support from AUR, if it helps.

I had to do the same (waybar v.0.9.24 and hyprland 0.33.1), comment out the `"mode": "dock"` line... which is not pointed on [the wiki](https://github.com/Alexays/Waybar/wiki/Configuration), and neither is the "default" value for the mode... so if I actually wanted the dock one, why wouldn't I write that line?
