### ISSUE TITLE
toggling hide mode breaks waybar randomly.

### ISSUE THREAD

**Issue by jkim5959** [Alexays/Waybar#1749]
I'm on Hyprland which is on VirtualBox.

when I do `killall -SIGUSR1 waybar`, it works but sometimes randomly bricks waybar and waybar simply does not respond to anything except when I type `killall waybar` to kill waybar.

It doesn't do anything. no more hide toggling, no more reloading with `killall -SIGUSR2 waybar`, not updating time, no tooltips, no volume control with wheel and no on-click action.

Is this happening to anyone else or is it because I'm on vbox?

**Comment by jonas-w** [comment]
Can reproduce on archlinux with sway

**Comment by Lassebq** [comment]
Can't reproduce this. Seems to only break when using reload function.
Tested on Arch with Hyprland, Sway and River

**Comment by ALizarazoTellez** [comment]
The error is back. It does not produce logs.

**Comment by ALizarazoTellez** [comment]
https://github.com/Alexays/Waybar/assets/65132831/49264e87-a0ed-45c3-84c6-4375a101e2b3

The video shows the error, at the end it is necessary to restart Waybar manually.
