### ISSUE TITLE
Pulseaudio scroll improve and limit

### ISSUE THREAD

**Issue by AlessioDP** [Alexays/Waybar#175]
Scrolling with touch pad is a bit complicated, I cannot be precise when I scroll, even if I set scroll up to 1.

Can we set a limit on audio? For example from 0 to 100%?

**Comment by Organic-Code** [comment]
Isn't there already a limit since 3e34137ac775d9b4ea7394c9bb0c48a74bb1fcb2 ? I'm a bit confused
The volume is bounded to 0-99% on my side

**Comment by AlessioDP** [comment]
My volume is bounded to 0-150%.

Anyway, the most important thing is slow down the scroll of the touch pad, its impossible to be precise when scrolling. (this is not a problem related to pulseaudio module but every)

**Comment by Alexays** [comment]
@Synthetica9 can you also add your changes to the pulseaudio modules?
Missed it :)

**Comment by Synthetica9** [comment]
Oh, yeah, sure :)

**Comment by Synthetica9** [comment]
Actually, maybe this behaviour should be moved to `IModule`, since it's currently quite a bit of repeated code. @Alexays, thoughts?

**Comment by Alexays** [comment]
Yeah! but IModule is an interface, but you can create an abstract `AModule` like `ALabel` but more generic and moves the code here :)

**Comment by Synthetica9** [comment]
I'll see what I can do, going to be offline for the weekend though.

**Comment by Synthetica9** [comment]
#387 should fix tihs

**Comment by Alexays** [comment]
Merged in master :)
