### ISSUE TITLE
Reuse modules with different settings, i.e. disk-module with different paths?

### ISSUE THREAD

**Issue by ad-on-is** [Alexays/Waybar#1754]
Is it possible to reuse modules with different settings? My root and my home partitions are different BTRFS volumes, and I'd like to show both of their usages.

something along these lines

```json
"disk.1": {
        "format": "<span foreground='#74c7ec'> {path}</span> {free} ({percentage_free}%)",
        "path": "/home"
    },
"disk.2": {
        "format": "<span foreground='#74c7ec'> {path}</span> {free} ({percentage_free}%)",
        "path": "/"
    },
    
    "modules-center":["disk.1", "disk.2"],
```

**Comment by ad-on-is** [comment]
Nevermind... I didn't see the docs

**Comment by raffaem** [comment]
> Nevermind... I didn't see the docs

For those  who came here: https://github.com/Alexays/Waybar/wiki/Configuration#multiple-instances-of-a-module
