### ISSUE TITLE
Latest SPDLOG breaks build

### ISSUE THREAD

**Issue by frkli1965** [Alexays/Waybar#1755]
Hi,

Just a heads up, the latest spdlog breaks the Waybar build.

Here's the trace...

[71/136] Compiling C++ object test/waybar_test.p/.._src_config.cpp.o
FAILED: test/waybar_test.p/.._src_config.cpp.o
c++ -Itest/waybar_test.p -Itest -I../test -I../include -I../subprojects/date-3.0.1/include -I/usr/local/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/lib/x86_64-linux-gnu/atkmm-1.6/include -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/atk-1.0 -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/jsoncpp -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 '-DVERSION="0.9.13-266-gebdf575 (branch '"'"'master'"'"')"' -DHAVE_LANGINFO_1STDAY '-DSYSCONFDIR="//usr/local/etc"' -DHAVE_CPU_LINUX -DHAVE_MEMORY_LINUX -DHAVE_SWAY -DHAVE_WLR -DHAVE_RIVER -DHAVE_HYPRLAND -DHAVE_LIBNL -DHAVE_GAMEMODE -DHAVE_UPOWER -DHAVE_LIBPULSE -DHAVE_LIBJACK -DHAVE_DBUSMENU -DHAVE_LIBUDEV -DHAVE_LIBEVDEV -DHAVE_LIBINPUT -DHAVE_LIBMPDCLIENT -DHAVE_GTK_LAYER_SHELL -DHAVE_LIBSNDIO -DHAVE_GIO_UNIX -DHAVE_LIBDATE -DUSE_OS_TZDB=1 -DSPDLOG_COMPILED_LIB -pthread -MD -MQ test/waybar_test.p/.._src_config.cpp.o -MF test/waybar_test.p/.._src_config.cpp.o.d -o test/waybar_test.p/.._src_config.cpp.o -c ../src/config.cpp
In file included from ../include/util/json.hpp:3,
                 from ../src/config.cpp:11:
/usr/include/fmt/ostream.h: In function ‘void fmt::v9::print(std::basic_ostream<Char>&, const S&, Args&& ...)’:
/usr/include/fmt/ostream.h:131:15: error: ‘make_args_checked’ is not a member of ‘fmt’
  131 |          fmt::make_args_checked<Args...>(format_str, args...));
      |               ^~~~~~~~~~~~~~~~~
/usr/include/fmt/ostream.h:131:37: error: expected primary-expression before ‘...’ token
  131 |          fmt::make_args_checked<Args...>(format_str, args...));
      |                                     ^~~
In file included from ../src/config.cpp:11:
../include/util/json.hpp: At global scope:
../include/util/json.hpp:9:56: error: expected class-name before ‘{’ token
    9 | struct fmt::formatter<Json::Value> : ostream_formatter {};
      |                                                        ^
In file included from /usr/local/include/spdlog/fmt/fmt.h:24,
                 from /usr/local/include/spdlog/common.h:45,
                 from /usr/local/include/spdlog/spdlog.h:12,
                 from ../src/config.cpp:3:
/usr/local/include/spdlog/fmt/bundled/core.h: In instantiation of ‘static void fmt::v9::detail::value<Context>::format_custom_arg(void*, typename Context::parse_context_type&, Context&) [with T = Json::Value; Formatter = fmt::v9::formatter<Json::Value>; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; typename Context::parse_context_type = fmt::v9::basic_format_parse_context<char>]’:
/usr/local/include/spdlog/fmt/bundled/core.h:1293:19:   required from ‘constexpr fmt::v9::detail::value<Context>::value(T&) [with T = const Json::Value; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>]’
/usr/local/include/spdlog/fmt/bundled/core.h:1760:14:   required from ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = Json::Value&]’
/usr/local/include/spdlog/fmt/bundled/core.h:1777:29:   required from ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = fmt::v9::detail::type::custom_type; T = Json::Value&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/usr/local/include/spdlog/fmt/bundled/core.h:1901:77:   required from ‘constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Json::Value}]’
/usr/local/include/spdlog/fmt/bundled/core.h:1918:31:   required from ‘constexpr fmt::v9::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v9::make_format_args(Args&& ...) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}]’
/usr/local/include/spdlog/logger.h:375:68:   required from ‘void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}; spdlog::string_view_t = fmt::v9::basic_string_view<char>]’
/usr/local/include/spdlog/logger.h:90:13:   required from ‘void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&>]’
/usr/local/include/spdlog/logger.h:96:12:   required from ‘void spdlog::logger::log(spdlog::level::level_enum, fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&>]’
/usr/local/include/spdlog/logger.h:146:12:   required from ‘void spdlog::logger::trace(fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&>]’
/usr/local/include/spdlog/spdlog.h:149:32:   required from ‘void spdlog::trace(fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&>]’
../src/config.cpp:116:22:   required from here
/usr/local/include/spdlog/fmt/bundled/core.h:1311:28: error: ‘struct fmt::v9::formatter<Json::Value>’ has no member named ‘parse’
 1311 |     parse_ctx.advance_to(f.parse(parse_ctx));
      |                          ~~^~~~~
/usr/local/include/spdlog/fmt/bundled/core.h:1314:22: error: ‘struct fmt::v9::formatter<Json::Value>’ has no member named ‘format’; did you mean ‘formatter’?
 1314 |     ctx.advance_to(f.format(*static_cast<qualified_type*>(arg), ctx));
      |                    ~~^~~~~~
      |                    formatter

Kind regards,

**Comment by asas1asas200** [comment]
What the OS and spdlog version you used?

I haved tried spdlog `1.10.0-3` on arch linux and built successfully.
The spdlog in `subprojects` also did.

**Comment by frkli1965** [comment]
Hi asas1asas200,

I cloned from the following...

https://github.com/gabime/spdlog.git

which builds fine on my system consisting of Ubuntu 22.04.1 with the v6.1rc3 Linux kernel.

I then attempt to build the Waybar with the latest source and I get the above failure.

Just tried it again with the same result alas.

If I compile the spdlog source from the weekend i.e. prior to fmtlib v1.9.1 the Waybar builds and runs fine btw.

Kind regards,

**Comment by frkli1965** [comment]
Addendum:-

Having just taken a cursory glance at the latest spdlog source, I note that the 'print' function from 'ostream.h' has changed from:-

template <typename S, typename... Args,
          typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>>
void print(std::basic_ostream<Char>& os, const S& format_str, Args&&... args) {
         vprint(os, to_string_view(format_str),
              fmt::make_args_checked<Args...>(format_str, args...));

}

to...

template <typename... Args>
void print(std::wostream& os,
           basic_format_string<wchar_t, type_identity_t<Args>...> fmt,
           Args&&... args) {
  vprint(os, fmt, fmt::make_format_args<buffer_context<wchar_t>>(args...));
}

which obviously goes to explain the first compilation error encountered above.

As stated in my OP, my intent was to give you guys a heads up as to what's coming down the pike.

The reason why I started using the latest spdlog source rather than version provided by the Ubuntu repository was because the latter lagged behind that relied upon by the Waybar official source found here some time back resulting in failed builds as a result.

Didn't think to use the spdlog subproject provided here tbh.

Kind regards,

**Comment by frkli1965** [comment]
I note with interest that the Waybar subproject version of the spdlog acquired from:-

https://github.com/gabime/spdlog/archive/v1.10.0.tar.gz

contains source files that are all dated 4th April 2022 whereas those cloned directly from the v1.x branch are somewhat more recent being dated 20th Oct 2022, hence the discrepancy we've been experiencing. Therefore you will no doubt encounter the very same issues that I've been having in the not too distant future.

Nevertheless, I appreciate that the Waybar project may prefer to adhere to what could be deemed as the more stable archived version of the spdlog for now rather than chance it with the bleeding-edge offering. Though rest assured that the latest-and-greatest version of the spdlog integrated just fine with the Waybar until a few short days ago.

Whichever the case may be, as the saying goes, to be forewarned is to be forearmed and in that vain I am more than happy to have spent some time on greasing the wheels of this most excellent project.

Kind regards,

**Comment by frkli1965** [comment]
SPDLOG v1.11.0 officially released now..
