### ISSUE TITLE
Padding issue in latest waybar

### ISSUE THREAD

**Issue by J0nnyMak0** [Alexays/Waybar#1756]
After updating to latest waybar (0.1.94), I'm facing a couple of issues with padding.
1. Previously, not specifying padding defaulted to 0 padding. Now I'm getting a huge amount of padding between elements
2. Even when explicitly specifying 0px padding like so:
`padding: 0 0px;`, I still get a border between elements. Looks like about 1px thick.

**Comment by charlesrocket** [comment]
Same here. Only `window` and `workspaces` looks normal, the rest is now with round corners and extra padding.

**Comment by gilbsgilbs** [comment]
It indeed seems that 0.9.14 introduced lots of regressions with styling:
 
![image](https://user-images.githubusercontent.com/3407667/199441771-13278cf0-507d-4bd1-8705-261d1286df89.png)

(0.9.14 on top, 0.9.13 on bottom)

- padding and round corners on each module
- pango markup is no longer interpreted and is just printed raw

[config.txt](https://github.com/Alexays/Waybar/files/9918098/config.txt)
[style.css.txt](https://github.com/Alexays/Waybar/files/9918099/style.css.txt)
[logs.txt](https://github.com/Alexays/Waybar/files/9918132/logs.txt)

**Comment by s0ulslack** [comment]
See 1753 or 1726

**Comment by J0nnyMak0** [comment]
I think the issue is not so much the change in defaults. The problem is explicit values to control round corners using `border-radius` and padding are not being respected. 0 is being interpreted as something small but not quite zero. So setting `border-radius: 0px` reduces the rounding of the corners but doesn't get rid of it. Same with padding. Not sure if this is a gtk issue or a waybar issue.

**Comment by tmpm697** [comment]
I tried `waybar-git` and saw the bar totally messed up with font and spaces...etc and then somehow it introduced to official package in community/waybar (pacman/archlinux). Had to downgrade to use it normally.

**Comment by Alexays** [comment]
@pinselimo can you help me with that? :D

**Comment by Matias-Hall** [comment]
git-bisect suggests the issue (at least the padding) comes from b8322c4b4b023d8e6fbe8b6bf4100d6c60a06e42

**Comment by pinselimo** [comment]
@Alexays  yet, I can reproduce the issue using @gilbsgilbs configs and am going to have a look at it.

**Comment by Theraa0** [comment]
Adding 
`* { all: initial; }`
to the style.css file works as a workarround for me.

**Comment by TRPB** [comment]
that fixes the padding, but symbols use in arrows like [gilbsgilbs](https://github.com/gilbsgilbs)'s screenshot cannot be styled with background/foreground colours.

**Comment by charlesrocket** [comment]
and some coloring is also failing, but this might be a solid workaround for lots of configs probably

**Comment by J0nnyMak0** [comment]
> Adding
> `* { all: initial; }`
> to the style.css file works as a workaround for me.

`*{ all:initial;
    border-radius: 0px;
   }`

seems to get back to behavior prior to the update in terms of spaces. Colors and symbols are a different story.

**Comment by fuzunspm** [comment]
have the same issue after the update. `all: initial;` fixes the padding but losing all other colors and styles

**Comment by J0nnyMak0** [comment]
> have the same issue after the update. `all: initial;` fixes the padding but losing all other colors and styles

`all: initial;` and `border-radius: 0px` need to be scoped into the elements as needed to preserve color. I think I'm going to close this issue, since this is specific to padding and the workaround has fixed the regression for me.

**Comment by kj** [comment]
I think it's too early to close the issue unless the issue is fixed or the workaround is officially adopted and documented as the solution.

**Comment by charlesrocket** [comment]
@J0nnyMak0 `border` with `border-radius` are fixing the layout, but adding `all: initial` breaks colors/font

**Comment by josch** [comment]
> I think I'm going to close this issue, since this is specific to padding and the workaround has fixed the regression for me.

While you may have a workaround that works for you, closing this issue wont help all the other people that upgrade their waybar and find themselves in the same situation.

I don't think it should be expected of waybar users that upgrade and find their setups broken to first search the (potentially already closed) issues whether there is some workaround that works for them. Instead, when waybar adds changes that break people's configuration like this, there should be a clear big message in the changelog that announces what will break and what users should do to make their setup work with the new version.

I think this issue should be closed either by:

 - reverting the change that breaks user setups or by
 - clear documentation in the release notes what will break and how to fix it

That this change was made in a minor version update also doesn't help. Usually, changes that require configuration adjustments are only made in major version updates...

**Comment by sereinity** [comment]
my workaround:

```css
button {
  border-radius: 0px;
  all: initial;
}
```

**Comment by gonX** [comment]
Yes, this seems to have been fixed between 0.9.15 and master (tested d2b22c6e) - at least in terms of no longer needing the workaround.

However, I'd like to note that I had to change some styling in my CSS (`widget > label` -> `widget label`) to make it 1:1 to 0.9.13, since it seems there instead is a button containing the label - however, this issue is a lot less significant and can be fixed by running e.g. `:%s/widget\(.*\)> label/widget\1label/` in vim.

**Comment by J0nnyMak0** [comment]
Thanks for the fix.

**Comment by tmpm697** [comment]
Didn't work for me with latest 0.9.15-1 on archlinux. Would try it back some days more.

**Comment by gilbsgilbs** [comment]
@tmpm697 it's fixed on master (including arrows stuff), but not released yet.
