### ISSUE TITLE
0.9.14 changelog & breaking changes

### ISSUE THREAD

**Issue by HarHarLinks** [Alexays/Waybar#1759]
Arch linux package was updated to 0.9.14 which doesn't yet have a changelog under https://github.com/Alexays/Waybar/releases.

The update broke, among others, the ability to format custom plugins like this:
![image](https://user-images.githubusercontent.com/2803622/199436085-7692dcaa-b815-4928-88ea-191ff036e86a.png)

The `<b>` would previously make the `A` bold. The plugin is a bash script outputting json.

**Comment by rnestler** [comment]
For me the whole bar looks different:
Old:
![old](https://user-images.githubusercontent.com/1435346/199453182-2d03c620-cb92-4fbe-874d-b310ef277c07.png)
New:
![new](https://user-images.githubusercontent.com/1435346/199453521-f91a6c31-bb33-48fb-917f-cad20181a5d6.png)

**Comment by s0ulslack** [comment]
See 1753 or 1726

**Comment by HarHarLinks** [comment]
indeed, thanks for pointing out the formatting issue is #1726.

on top of that there are a good amount of additional issues including the unclear release state with an existing git tag landing in downstream packages without a proper release.

**Comment by WhyNotHugo** [comment]
The clock is now rendering grey text for me, even though I have this in my config:

```
#clock {
  color: #ffffff;
}
```

**Comment by maximbaz** [comment]
@Alexays do you think we could expect 0.9.15 reasonably soon, now that for example #1687 is reverted, and only styling seems to be the problem? 

Although I understand the intention behind deleting a tag, it is generally not the best practice to do, but more importantly, there is over 250 commits of more than 5 months of contributions since 0.9.13, it would be awesome to get all those improvements into the hands of the users 🙂

**Comment by FilippoBonazziSUSE** [comment]
> Although I understand the intention behind deleting a tag, it is generally not the best practice to do

I agree, things got very confusing when I couldn't find the upstream 0.9.14 release corresponding to the one on [OBS](https://build.opensuse.org/package/show/X11:Wayland/waybar). Any announcement would have been appreciated (open an issue, add a notice to the README, ...).

**Comment by Alexays** [comment]
0.9.15 released, sorry for the mess

**Comment by FilippoBonazziSUSE** [comment]
Wow that was quick. Thanks a lot, very much appreciated

**Comment by jubalh** [comment]
Thanks @Alexays. openSUSE OBS package got [updated](https://build.opensuse.org/request/show/1033009)

**Comment by maximbaz** [comment]
Arch too, thanks for the swift response! 👍

**Comment by WhyNotHugo** [comment]
Thanks for addressing this confusion quickly.

Suggestion: If tags should not be picked up by downstream packagers (and only GH releases) I'd suggest adding a small section for packagers on the README would be great to avoid confusion. Generally, when a tag pops up packagers will assume it's ready to ship (unless it says alpha or alike).

**Comment by wioo** [comment]
0.9.15 doesnt fix the issue in second post. (arch linux)

0.9.15
![0 9 15](https://user-images.githubusercontent.com/8883640/199713986-d13041e3-c631-4242-b665-095bcaabfc8d.png)

0.9.13
![0 9 13](https://user-images.githubusercontent.com/8883640/199714039-105176eb-7446-4d60-bc52-990ae3c14cea.png)

**Comment by FilippoBonazziSUSE** [comment]
Same on openSUSE Tumbleweed:

0.9.15
![20221103_10h54m41s_grim](https://user-images.githubusercontent.com/101266837/199722377-07accc29-0ca2-49ea-98e8-13ec62a8b965.png)


0.9.13
![20221103_10h55m30s_grim](https://user-images.githubusercontent.com/101266837/199722304-e2e75020-06d5-40f6-a15c-02a0b56d3064.png)

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Similar issues.

With 0.9.13:
![Waybar 0 9 13](https://user-images.githubusercontent.com/2873785/199974564-588c513a-e802-4ed9-bf61-8d3a888fe075.png)

With 0.9.15:
![Waybar 0 9 15](https://user-images.githubusercontent.com/2873785/199974607-9831d472-1942-49c3-a0d6-29c10de718be.png)

Main regressions I have:
- text for modules without `on-click` is different
- fixed width format with the network module is not working anymore

**Comment by TRPB** [comment]
There's also an issue with `"format": "",` these no longer display the arrows correctly. The foreground colour isn't set and the arrow doesn't take up the entire block

**Comment by mcepl** [comment]
0.9.15 does nothing good for me on openSUSE/Tumbleweed, see https://github.com/openSUSE/openSUSEway/issues/79.

**Comment by KFearsoff** [comment]
> There's also an issue with `"format": "",` these no longer display the arrows correctly. The foreground colour isn't set and the arrow doesn't take up the entire block.

Can confirm. My bar uses it, and now looks completely differently.
Old: 
![image](https://user-images.githubusercontent.com/66781795/200182149-dd38782f-62f5-42b1-9f6c-30a1ac4feab1.png)
New:
![image](https://user-images.githubusercontent.com/66781795/200182164-b42f343f-c875-4e23-8d81-5b4b0bb8d8ac.png)

I'm assuming there are backwards-incompatible changes in Waybar, but I haven't had much luck finding how to migrate my old configs properly.
