### ISSUE TITLE
&amp; instead of &

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Alexays/Waybar#1765]
I'm using : 
`waybar --version
Waybar v0.9.15`

Fonts are configured like : 
`
 42 #waybar {
 44     background: rgba(50, 50, 50, 1);
 45     color: white;
 46     font-family: "DejaVu Sans Mono", "Font Awesome 6 Free";
 47     font-size: 12px;
 48 }
`
In the bar i've got `&amp;` instead of & 

I've also try other fonts, like Liberation and Vera same `&amp;` instead of &

**Comment by Galicarnax** [comment]
Same here, noticed this in MPD's titles, where previously ampersands displayed normal. Probably, this came with one of latest updates.

**Comment by HarHarLinks** [comment]
probably similar to #1757 as this is a html (-> pango) escape code

**Comment by Alexays** [comment]
Should be fixed for MPD module
