### ISSUE TITLE
Waybar crashes on monitor hotplug

### ISSUE THREAD

**Issue by mgbowe1** [Alexays/Waybar#1768]
I'm using a kvm switch that doesn't support EDID emulation (no EDID emulators exist for the DP1.4 standard that I can find). When my machine is not the active machine, this results in a temporarily headless system, and upon returning waybar has crashed. I've attached a log consisting of the stdout and stderr info.

[waybar.log](https://github.com/Alexays/Waybar/files/9939932/waybar.log)

**Comment by mgbowe1** [comment]
[waybar.log](https://github.com/Alexays/Waybar/files/9939986/waybar.log)

The previous log did not contain the issue due to a compositor crash before the waybar crash. This log should be correct.

**Comment by oniGino** [comment]
pretty sure this is the same issue as me in #1674

**Comment by mgbowe1** [comment]
It's different. This issue has nothing to do with sleep, only with disconnecting monitors.

**Comment by oniGino** [comment]
> It's different. This issue has nothing to do with sleep, only with disconnecting monitors.

Yes it's the same read the comments

**Comment by mgbowe1** [comment]
Realized this is a duplicate
