### ISSUE TITLE
 Wrong layout name when contains comma 

### ISSUE THREAD

**Issue by hiimjako** [Alexays/Waybar#1771]
Module: "Hyprland/language"

It happens on layouts that contains one or multiple commas ","  that the layout name displayed is not the correct one.
An example could be with the layout: `English (US, intl., with dead keys)`
Other examples could found using `xkbcli list` selecting layouts with description containing commas.

I think the problem could be in the way that the module extract the format from the event. It looks the last comma and it assumes that the following string is the layout, excluding the case in which there were commas in the name. 
Using the previous example the output will be: `with dead keys)`.
Deduction made looking at `src/modules/hyprland/language.cpp` in the `onEvent` function.

This problem does not make the option `format-<lang>` option usable correctly with those layouts.

Does anyone have ideas on how to fix it? I can do it but idk the right way of doing it

**Comment by eneshecan** [comment]
Could you please check again with latest master?

**Comment by hiimjako** [comment]
It works perfectly, thanks 🙂
