### ISSUE TITLE
No updating of battery percentage, network-linked ip address and unwanted shadows since 0.9.15.

### ISSUE THREAD

**Issue by tim3dman** [Alexays/Waybar#1777]
Since 0.9.15 no updating of battery percentage stuck at 100%. Network-linked not showing ip address only showing wan0 ip address.
Custom modules showing white shadow background when hovered over.
Downgrading to 0.9.13 fixes all issues.
Arch Linux 6.0.7-arch1-1, lenovo t470, sway 1.7.

**Comment by grfrederic** [comment]
The battery is comes from you having two batteries, single battery works.
The shadows have been discussed in different issues, including [here](https://github.com/Alexays/Waybar/issues/1763).

**Comment by grfrederic** [comment]
As for the battery, I added a [PR](https://github.com/Alexays/Waybar/pull/1788).

**Comment by Alexays** [comment]
Closing in favor of #1763
