### ISSUE TITLE
MPD module doesn´t work properly since update to 0.9.14

### ISSUE THREAD

**Issue by saltasatelites** [Alexays/Waybar#1778]
Hi,
I have been using the MPD module with the "default" configuration without any kind of issue until version 0.9.13-2. (Running on Archlinux and installed directly from the community repository)
Since the 0.9.14 update and higher, the module only shows information about the track, but it is not possible to manage MPD directly from Waybar (stop, pause...).
Has anyone else found this problem, or suggest any solution?
Thanks in advance.

(PD: If more information is necessary, please don't hesitate to ask me)

Config (as I've said is the default):

   "mpd": {
   "format": "{stateIcon} {consumeIcon}{randomIcon}{repeatIcon}{singleIcon}{artist} - {album} - {title} ({elapsedTime:%M:%S}/{totalTime: %M:%S}) ï",
    "format-disconnected": "Disconnected ï",
    "format-stopped": "{consumeIcon}{randomIcon}{repeatIcon}{singleIcon}Stopped ï",
    "interval": 10,
    "consume-icons": {
        "on": "ï " // Icon shows only when "consume" is on
    },
    "random-icons": {
        "off": "<span color=\"#f53c3c\">ï´</span> ", // Icon grayed out when "random" is off
        "on": "ï´ "
    },
    "repeat-icons": {
        "on": "ï "
    },
    "single-icons": {
        "on": "ï1 "
    },
    "state-icons": {
        "paused": "ï",
        "playing": "ï"
    },
    "tooltip-format": "MPD (connected)",
    "tooltip-format-disconnected": "MPD (disconnected)"
    },

Style.css:

#mpd {
    background-color: #90b1b1;
    color: #ffffff;
}
#mpd.disconnected {
    background-color: #f53c3c;
}
#mpd.stopped {
    background-color: #90b1b1;
}
#mpd.paused {
    background-color: #666666;
    color: #ffffff;
}

**Comment by saltasatelites** [comment]
Am I really the only one with this problem? Can anyone put me in the correct direction?

**Comment by Zapeth** [comment]
Was https://github.com/Alexays/Waybar/pull/1810 supposed to fix this? I'm experiencing the same issue with v0.9.16, I can also provide more information if necessary.
