### ISSUE TITLE
Padding issue with latest waybar? 

### ISSUE THREAD

**Issue by tmpm697** [Alexays/Waybar#1781]
There're multiple issues created but with current 0.9.15-2 on archlinux, still not fixed for me.
I had to downgrade both spdlog from 1.11 to 1.10.0-3 and waybar from 0.9.15-2 to 0.9.13-2.

idk why most of issues closed, but I'd rather keep this here to track the issue.

**Comment by meemo** [comment]
For others in the same position, here's a single command to downgrade on Arch:

```
sudo pacman -U https://archive.archlinux.org/packages/w/waybar/waybar-0.9.13-2-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/s/spdlog/spdlog-1.10.0-3-x86_64.pkg.tar.zst
```

**Comment by tmpm697** [comment]
to downgrade without local files: paru -Sy downgrade; sudo downgrade spdlog; sudo downgrade waybar

**Comment by Alexays** [comment]
Closed as reverted
