### ISSUE TITLE
CSS doesnt understand !important

### ISSUE THREAD

**Issue by ceselder** [Alexays/Waybar#1782]
Adding !important in css doesnt work as expected, waybar refuses to launch
![image](https://user-images.githubusercontent.com/94973748/200887467-889d345b-e1ad-46ae-be28-6702d01ea9df.png)

**Comment by saltasatelites** [comment]
Hi, please publish line 70 of your style. The warning tells you where exactly the error is.

**Comment by ceselder** [comment]
![image](https://user-images.githubusercontent.com/94973748/201484999-755726af-ae86-4cc0-9789-d01206d902c8.png)
line 70 is the line that contains !important

**Comment by saltasatelites** [comment]
What's the reason of add "!important" after the background color? Breaks your style.css

**Comment by ceselder** [comment]
I can see that it breaks my style.css, thats the whole point of this issue. I was using !important as a way to debug a weird issue where the background of the elements in my bar turned white on hover

**Comment by saltasatelites** [comment]
With the last update there has been a bunch of problem related to colors, but all the solutions sould be done on the config file, not the style.css

**Comment by saltasatelites** [comment]
With the last update there have been a lot of colors -related problems, but all solutions must be done in the configuration file, not in the Style.CSS file.
It has many alternatives, the most useful is to add on-click:""  to each module in the configuration file. See https://github.com/alexays/waybar/issues/1764. Maybe helps you. Bye.

**Comment by ceselder** [comment]
gotcha, thanks

**Comment by ceselder** [comment]
keeping this issue open though since important is part of css spec

**Comment by herlev** [comment]
I believe `!important` not working is a limitation of Waybar using GTK for CSS, which works with a limited subset of CSS [1]. An overview of the subset can be found [here](https://docs.gtk.org/gtk3/css-overview.html). 

For debugging the [GTK inspector](https://wiki.gnome.org/action/show/Projects/GTK/Inspector) can be very useful. It is started with `env GTK_DEBUG=interactive waybar`.

[1] https://github.com/Alexays/Waybar/wiki/Styling

**Comment by Alexays** [comment]
Sorry, it's a GTK limitation, can't be fixed on waybar side
