### ISSUE TITLE
Format issue with network module since v0.9.15

### ISSUE THREAD

**Issue by TheTumultuousUnicornOfDarkness** [Alexays/Waybar#1786]
It seems that #472 is not working anymore since v0.9.15 with network module. I am using `bandwidthUpOctets` and `bandwidthDownOctets`.

With 0.9.13:
![Waybar 0 9 13](https://user-images.githubusercontent.com/2873785/199974564-588c513a-e802-4ed9-bf61-8d3a888fe075.png)

With 0.9.15:
![Waybar 0 9 15](https://user-images.githubusercontent.com/2873785/199974607-9831d472-1942-49c3-a0d6-29c10de718be.png)

Even if I use `{bandwidthDownOctets}`, `{bandwidthDownOctets:>}`, `{bandwidthDownOctets:06}` or `{bandwidthDownOctets:>6}`, format is ignored.
The problem is my modules are in constant movement now, giving me a kind of seasickness.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Git bisection points b8322c4b4b023d8e6fbe8b6bf4100d6c60a06e42.
```
$ git bisect bad             git:(0.9.15~34^2~3|bisect)
b8322c4b4b023d8e6fbe8b6bf4100d6c60a06e42 is the first bad commit
```

**Comment by Alexays** [comment]
Closed as reverted
