### ISSUE TITLE
Waybar doesn't display bar when stdout points to /dev/null

### ISSUE THREAD

**Issue by Mango0x45** [Alexays/Waybar#1789]
My window manager is configured to spawn `waybar` on startup, but when it spawns processes it sets `stdout` and `stderr` to `/dev/null` which causes `waybar` to not actually display the bar. Here is a small C program to reproduce the issue:

```c
#include <fcntl.h>
#include <paths.h>
#include <unistd.h>

int
main(void)
{
	close(STDOUT_FILENO);
	int fd = open(_PATH_DEVNULL, O_WRONLY);
	dup2(fd, STDOUT_FILENO);
	close(fd);
	execlp("waybar", "waybar", NULL);
}
```

**Comment by prohornikitin** [comment]
I don't know why waybar can't work without valid stdout. But there is a bug in your program either:
When you close(STDOUT_FILENO), you release descriptor 1.
In next line you again acquire descriptor with minimal number. And it is 1!
Then, right before executing waybar you close stdout (descriptor 1).
Therefore waybar executes without any stdout.
If you swap first two lines of main() waybar will work fine.
