### ISSUE TITLE
Sway workspaces module hover style

### ISSUE THREAD

**Issue by AlessioDP** [Alexays/Waybar#179]
Is it possible to remove/change hover event of the module sway/workspace? (it creates a white border on top of the button)

**Comment by Robinhuett** [comment]
Have a look here: https://github.com/Alexays/Waybar/wiki/FAQ#the-workspace-buttons-have-a-strange-hover-effect

**Comment by AlessioDP** [comment]
Perfect, it fixed my problem :)

I think that should be by default inside style.css, maybe with a comment that link to that FAQ.

**Comment by Alexays** [comment]
I'll add it in the default config file
