### ISSUE TITLE
Add rotate support to hyprland/window

### ISSUE THREAD

**Issue by Estebiu** [Alexays/Waybar#1790]
The title is self-explanatory. The hyprland/window doesn't have support to rotate as of right now. I think it would be cool to add it, for the vertical bar users. Thanks.

**Comment by rubyowo** [comment]
this works now.
![image](https://user-images.githubusercontent.com/105302757/208089328-9390a316-fcba-44bf-9304-7e6d81d3a97b.png)

**Comment by Estebiu** [comment]
> this works now. ![image](https://user-images.githubusercontent.com/105302757/208089328-9390a316-fcba-44bf-9304-7e6d81d3a97b.png)

Awesome, thank you for letting me know.
