### ISSUE TITLE
⚠️ 0.9.15 regressions

### ISSUE THREAD

**Issue by Alexays** [Alexays/Waybar#1792]
Hi folks,
I'm creating a new issue to have all the regressions related to 0.9.15 in one place and be able to fix them more easily.
I also thought of revert https://github.com/Alexays/Waybar/pull/1120
What do you think?

https://github.com/Alexays/Waybar/issues/1781
https://github.com/Alexays/Waybar/issues/1786
https://github.com/Alexays/Waybar/issues/1763
https://github.com/Alexays/Waybar/issues/1775
https://github.com/Alexays/Waybar/issues/1778
https://github.com/Alexays/Waybar/issues/1743
https://github.com/Alexays/Waybar/issues/1741
https://github.com/Alexays/Waybar/issues/952
https://github.com/Alexays/Waybar/issues/1761
https://github.com/Alexays/Waybar/issues/1752
https://github.com/Alexays/Waybar/issues/1791
https://github.com/Alexays/Waybar/issues/1765

**Comment by Estebiu** [comment]
I would also like to add that when I upgraded waybar to 0.9.15 the battery indicator is "strange". It shows me the exact half of what my battery capacity is. So if htop says I'm at 100%, waybar will say that I'm at 50%. If I'm at 34%, waybar will say that I'm at 17% and so on.

**Comment by grfrederic** [comment]
@Estebiu I made changes to the battery calculation recently, could you give more info? What is your exact version? Do you have more than one battery (say, in `/sys/class/power_supply/`)?

**Comment by PowerMan2206** [comment]
I think you should revert #1120.

**Comment by Estebiu** [comment]
> @Estebiu I made changes to the battery calculation recently, could you give more info? What is your exact version? Do you have more than one battery (say, in `/sys/class/power_supply/`)?

I'm using the latest waybar-hyprland-git from the AUR as I'm on Hyprland. And no, I don't have another battery; my laptop doesn't support it (asus zenbook ux363ea). Just now I tried the standard waybar package and the battery monitor works normally. Very strange.

**Comment by grfrederic** [comment]
@Estebiu Right, that does sound like #1788 might have broken it for you. The tricky part is I only have a laptop with TWO batteries. I can remove one of them once I'm home and see if I can replicate the issue.

**Comment by roland-rollo** [comment]
@grfrederic I tested it now and unplugged my laptop from power source. To 79% falling was normal, and then for few minutes it changed to 43% to change 62% for long time and now it normally show 42%. For me it doesn't matter as I'm always on charger, but if you want me to check something then go ahead - everything that I can do without knowing C. :P

**Comment by grfrederic** [comment]
@roland-rollo that does not really sound related. I changed the capacity computation to divide by the total number of batteries, and for @Estebiu around that time it starts showing half the capacity. Perhaps the jumps in reported battery level might mean your battery digraded/is not calibrated. In any case, as long as `/sys/class/power_supply/BAT0/capacity` shows the same number as waybar it's probably not an issue with waybar.

**Comment by TRPB** [comment]
Can I suggest reverting back to 0.9.13 as the primary release (possibly release it as 0.9.16) and then the release with these changes as a 0.10 beta so they can be fixed and not upgraded to automatically by users?

0.9.15 broke a lot of stuff to the point where it is unusable for a lot of us.

**Comment by grfrederic** [comment]
@Estebiu I tried with one battery unplugged and -- it works on my machine :) If you would be up for it we can try figuring out together what makes it break on your laptop. I'm not sure this is the best place to do it though, maybe we should discuss on the closed PR #1788? I'm not that fluent with github etiquette.

Reverting temporarily #1120 (or more) and fixing things on the side before rerelease sounds reasonable to me. I can help with testing and (perhaps with some pointers from more regular contributors) some coding.

**Comment by bloodandcoffee** [comment]
I think reverting #1120 is introduces breaking changes for no good reason. Such changes should be avoided in the future

**Comment by meemo** [comment]
> I think reverting #1120 is introduces breaking changes for no good reason. Such changes should be avoided in the future

It's introducing a breaking change to fix that breaking change which breaks many themes.

For example, here is what my theme (a [slightly modified](https://github.com/meemo/dotfiles/tree/master/.config/waybar) version [cjbassi's config](https://github.com/cjbassi/config/tree/master/.config/waybar)) looks like on 0.9.13:

![0.9.13](https://user-images.githubusercontent.com/8729155/202930128-cec80e20-fa3c-417b-9ad4-ac1c70dafe2b.png)

And here is how it looks on 0.9.15:

![0.9.15](https://user-images.githubusercontent.com/8729155/202930156-3fc833dd-880e-47db-a0dc-e7e4a0ddb2f3.png)

I had some luck with [this comment](https://github.com/Alexays/Waybar/issues/1741#issuecomment-1304875657) in #1741, however now everything is tiny:

![0.9.15 unset all](https://user-images.githubusercontent.com/8729155/202930210-a4d745e6-fe96-420b-b9f9-381728b86853.png)

I tried several suggestions in other issues and unfortunately have had no luck in getting my theme working again.

**Comment by pinselimo** [comment]
As the author of #1120 I also think it's better to revert it now, try to fix the issue and introduce it in a more major update after some beta-testing.

On the other hand, a lot of the features using buttons adds over using labels are also available after a shift to Gtk4, so this may be an option for a major version bump as well.

The heterogeneity of configurations is a major issue for quality assurance. It would be great to introduce some guarantees for the users as to which configs are certain to look the same across updates. E.g. have some example configs covering most of the heterogeneity be required to look the same.

**Comment by Alexays** [comment]
Agree with you @pinselimo, do you think you have some time to revert the PR?
I'll try to find some times next week, otherwise.

**Comment by Alexays** [comment]
Closed as reverted
