### ISSUE TITLE
[hyprland/window] show active window on a per monitor basis not working

### ISSUE THREAD

**Issue by 5ysk3y** [Alexays/Waybar#1794]
Hey,

After updating to the newest Waybar version, I seem to be having an issue with one of the newly implemented features, namely from this PR: https://github.com/Alexays/Waybar/pull/1719

If I add this to my Waybar config:

```
"hyprland/window": {
    "separate-outputs": true
}
```

And then start Waybar, the moment I move my mouse between 2 windows it crashes out with the following:

```
terminate called after throwing an instance of 'Json::LogicError'
  what():  LargestInt out of UInt range
```

I'm using `waybar-hyprland` from the AUR, as I am a Hyprland user; both this variant and the `-git` version give me the same issue. I've also tried testing this with a default config file (namely to ensure it wasnt my conf somehow borking things) and the crash persists. Setting `separate-outputs` to `0`/`false` causes Waybar to work normally as expected, i.e. no crash, but also the window titles are not per-monitor.

Not sure if this is reproducable by others; feel free to let me know if I can supply anything further.

**Comment by herlev** [comment]
I can't reproduce. What is the output if you run the commands `hyprctl monitors -j` and `hyprctl workspaces -j`?

**Comment by herlev** [comment]
I can reproduce this if using named workspaces. Named workspaces in Hyprland start at ID -1337 and count down, which causes an error when executing the line `return (*monitor)["activeWorkspace"]["id"].as<uint>()`.

**Comment by herlev** [comment]
@5ysk3y, can you check if #1809 resolves your issue?

**Comment by 5ysk3y** [comment]
@herlev I've just tested via the waybar-hyprland-git AUR repo and the issue does look to be fixed; works perfectly, in fact. Thank you for your work on this feature.
