### ISSUE TITLE
Adjust the color of the bar when there is a single app on the screen

### ISSUE THREAD

**Issue by Nikki1993** [Alexays/Waybar#180]
Greetings,

How would one go about changing the background of the bar when there is only 1 app in the entire workspace? I frequently have Chrome opened while not sharing space with any of the apps and would like to change the background color from transparent to a solid color. 

Thank you!

**Comment by Alexays** [comment]
Ohh, it could be a nice improvement.

**Comment by Alexays** [comment]
Done in bb8ff5a99fbc67126aba3b4b75729009da97664c
Class `empty` is added to the `window` tag when no windows is in the focused workspace
Class `solo` is added when one window is the focused workspace
And the `app_id` will be added as a class when it's the only window in the workspace like `.chromium`
