### ISSUE TITLE
Crash in wlr/workspaces with named workspaces on Hyprland

### ISSUE THREAD

**Issue by trippwill** [Alexays/Waybar#1803]
I'm using the AUR package waybar-hyprland-git. Using a named workspace causes a crash in wlr/workspaces. Based on the debug log it's caused by the stoi call used for sorting by number.

**Comment by trippwill** [comment]
PID: 42557 (waybar)
           UID: 1000 (tripp)
           GID: 1000 (tripp)
        Signal: 11 (SEGV)
     Timestamp: Sun 2022-11-20 14:28:30 GMT (9min ago)
  Command Line: waybar -l debug
    Executable: /usr/bin/waybar
 Control Group: /user.slice/user-1000.slice/session-19.scope
          Unit: session-19.scope
         Slice: user-1000.slice
       Session: 19
     Owner UID: 1000 (tripp)
       Boot ID: 2e9ee8c741ac417d883d8225e3e73dde
    Machine ID: f3b74e67fe604ff7be8c6254747e6a0e
      Hostname: catosframe
       Storage: /var/lib/systemd/coredump/core.waybar.1000.2e9ee8c741ac417d883d8225e3e73dde.42557.1668954510000000.zst (present)
  Size on Disk: 2.4M
       Message: Process 42557 (waybar) of user 1000 dumped core.
                
                Stack trace of thread 42557:
                #0  0x00005567e89f100b n/a (waybar + 0x10800b)
                #1  0x00005567e89f10ac n/a (waybar + 0x1080ac)
                #2  0x00007ff4ffe814f6 n/a (libffi.so.8 + 0x74f6)
                #3  0x00007ff4ffe7df5e n/a (libffi.so.8 + 0x3f5e)
                #4  0x00007ff4ffe80b73 ffi_call (libffi.so.8 + 0x6b73)
                #5  0x00007ff501562645 n/a (libwayland-client.so.0 + 0x7645)
                #6  0x00007ff501562e03 n/a (libwayland-client.so.0 + 0x7e03)
                #7  0x00007ff501562ffc wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x7ffc)
                #8  0x00007ff500cea2d9 n/a (libgdk-3.so.0 + 0x622d9)
                #9  0x00007ff500cb9019 gdk_display_get_event (libgdk-3.so.0 + 0x31019)
                #10 0x00007ff500cf38b8 n/a (libgdk-3.so.0 + 0x6b8b8)
                #11 0x00007ff5000e787b g_main_context_dispatch (libglib-2.0.so.0 + 0x5587b)
                #12 0x00007ff50013e279 n/a (libglib-2.0.so.0 + 0xac279)
                #13 0x00007ff5000e6132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                #14 0x00007ff5003100ce g_application_run (libgio-2.0.so.0 + 0xde0ce)
                #15 0x00005567e892aa54 n/a (waybar + 0x41a54)
                #16 0x00005567e8929436 main (waybar + 0x40436)
                #17 0x00007ff4ff954290 n/a (libc.so.6 + 0x23290)
                #18 0x00007ff4ff95434a __libc_start_main (libc.so.6 + 0x2334a)
                #19 0x00005567e8934bb5 n/a (waybar + 0x4bbb5)
                
                Stack trace of thread 42565:
                #0  0x00007ff4ffa317fd syscall (libc.so.6 + 0x1007fd)
                #1  0x00007ff500137ad7 g_cond_wait_until (libglib-2.0.so.0 + 0xa5ad7)
                #2  0x00007ff5000b5893 n/a (libglib-2.0.so.0 + 0x23893)
                #3  0x00007ff5000b5a37 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x23a37)
                #4  0x00007ff50011a516 n/a (libglib-2.0.so.0 + 0x88516)
                #5  0x00007ff500114e05 n/a (libglib-2.0.so.0 + 0x82e05)
                #6  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #7  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42563:
                #0  0x00007ff4ff96a6ba __sigtimedwait (libc.so.6 + 0x396ba)
                #1  0x00007ff4ff969d8c sigwait (libc.so.6 + 0x38d8c)
                #2  0x00005567e896a0ec n/a (waybar + 0x810ec)
                #3  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #4  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42570:
                #0  0x00007ff4ffa2804c read (libc.so.6 + 0xf704c)
                #1  0x00005567e89a440c n/a (waybar + 0xbb40c)
                #2  0x00005567e8955781 n/a (waybar + 0x6c781)
                #3  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #4  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #5  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42567:
                #0  0x00007ff4ffa2c0bf __poll (libc.so.6 + 0xfb0bf)
                #1  0x00007ff50013e1df n/a (libglib-2.0.so.0 + 0xac1df)
                #2  0x00007ff5000e6132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                #3  0x00007ff4fb471fde n/a (libdconfsettings.so + 0x5fde)
                #4  0x00007ff500114e05 n/a (libglib-2.0.so.0 + 0x82e05)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42566:
                #0  0x00007ff4ffa2c0bf __poll (libc.so.6 + 0xfb0bf)
                #1  0x00007ff50013e1df n/a (libglib-2.0.so.0 + 0xac1df)
                #2  0x00007ff5000e6ddf g_main_loop_run (libglib-2.0.so.0 + 0x54ddf)
                #3  0x00007ff50033c33c n/a (libgio-2.0.so.0 + 0x10a33c)
                #4  0x00007ff500114e05 n/a (libglib-2.0.so.0 + 0x82e05)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42568:
                #0  0x00007ff4ff9b44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007ff4ff9b72d7 pthread_cond_clockwait (libc.so.6 + 0x862d7)
                #2  0x00005567e8a55419 n/a (waybar + 0x16c419)
                #3  0x00005567e8955781 n/a (waybar + 0x6c781)
                #4  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42571:
                #0  0x00007ff4ffa2804c read (libc.so.6 + 0xf704c)
                #1  0x00005567e89a867c n/a (waybar + 0xbf67c)
                #2  0x00005567e8955781 n/a (waybar + 0x6c781)
                #3  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #4  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #5  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42572:
                #0  0x00007ff4ff9b44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007ff4ff9b72d7 pthread_cond_clockwait (libc.so.6 + 0x862d7)
                #2  0x00005567e895c87f n/a (waybar + 0x7387f)
                #3  0x00005567e8955781 n/a (waybar + 0x6c781)
                #4  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42576:
                #0  0x00007ff4ff9b44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007ff4ff9b72d7 pthread_cond_clockwait (libc.so.6 + 0x862d7)
                #2  0x00005567e8950376 n/a (waybar + 0x67376)
                #3  0x00005567e8955781 n/a (waybar + 0x6c781)
                #4  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42578:
                #0  0x00007ff4ff9b44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007ff4ff9b72d7 pthread_cond_clockwait (libc.so.6 + 0x862d7)
                #2  0x00005567e89af7cf n/a (waybar + 0xc67cf)
                #3  0x00005567e8955781 n/a (waybar + 0x6c781)
                #4  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42573:
                #0  0x00007ff4ffa2804c read (libc.so.6 + 0xf704c)
                #1  0x00007ff4ff9b0656 _IO_file_underflow (libc.so.6 + 0x7f656)
                #2  0x00007ff4ff9b1686 _IO_default_uflow (libc.so.6 + 0x80686)
                #3  0x00007ff4ff9a506b _IO_getline_info (libc.so.6 + 0x7406b)
                #4  0x00007ff4ff9a4142 _IO_fgets (libc.so.6 + 0x73142)
                #5  0x00005567e8953316 n/a (waybar + 0x6a316)
                #6  0x00005567e8955781 n/a (waybar + 0x6c781)
                #7  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #8  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #9  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42582:
                #0  0x00007ff4ff9b44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007ff4ff9b72d7 pthread_cond_clockwait (libc.so.6 + 0x862d7)
                #2  0x00005567e8a06885 n/a (waybar + 0x11d885)
                #3  0x00005567e8955781 n/a (waybar + 0x6c781)
                #4  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42569:
                #0  0x00007ff4ff9b44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007ff4ff9b72d7 pthread_cond_clockwait (libc.so.6 + 0x862d7)
                #2  0x00005567e89a85b9 n/a (waybar + 0xbf5b9)
                #3  0x00005567e8955781 n/a (waybar + 0x6c781)
                #4  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42575:
                #0  0x00007ff4ff9fe7c5 clock_nanosleep (libc.so.6 + 0xcd7c5)
                #1  0x00007ff4ffa032d7 __nanosleep (libc.so.6 + 0xd22d7)
                #2  0x00005567e89fdcc1 n/a (waybar + 0x114cc1)
                #3  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #4  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #5  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42584:
                #0  0x00007ff4ffa2c0bf __poll (libc.so.6 + 0xfb0bf)
                #1  0x00007ff4ffff38c7 n/a (libpulse.so.0 + 0x338c7)
                #2  0x00007ff4fffdd46c pa_mainloop_poll (libpulse.so.0 + 0x1d46c)
                #3  0x00007ff4fffe742c pa_mainloop_iterate (libpulse.so.0 + 0x2742c)
                #4  0x00007ff4fffe74e1 pa_mainloop_run (libpulse.so.0 + 0x274e1)
                #5  0x00007ff4ffff7c02 n/a (libpulse.so.0 + 0x37c02)
                #6  0x00007ff4ff006c57 n/a (libpulsecommon-16.1.so + 0x5bc57)
                #7  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #8  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42564:
                #0  0x00007ff4ffa2c0bf __poll (libc.so.6 + 0xfb0bf)
                #1  0x00007ff50013e1df n/a (libglib-2.0.so.0 + 0xac1df)
                #2  0x00007ff5000e6132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                #3  0x00007ff5000e6182 n/a (libglib-2.0.so.0 + 0x54182)
                #4  0x00007ff500114e05 n/a (libglib-2.0.so.0 + 0x82e05)
                #5  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 42583:
                #0  0x00007ff4ffa39096 epoll_wait (libc.so.6 + 0x108096)
                #1  0x00005567e8a059bd n/a (waybar + 0x11c9bd)
                #2  0x00005567e8955781 n/a (waybar + 0x6c781)
                #3  0x00007ff4ffcd62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #4  0x00007ff4ff9b78fd n/a (libc.so.6 + 0x868fd)
                #5  0x00007ff4ffa39a60 n/a (libc.so.6 + 0x108a60)
                ELF object binary architecture: AMD x86-64

**Comment by Gusser93** [comment]
I can confirm this bug. Maybe this line
https://github.com/Alexays/Waybar/commit/9a0013cb10ce449e429e6d0986abd0b154db21ac#diff-1e3fe235d8ac230e16d6bda17e39bf3fb4bc1d38a193ed6e42d2ad2589070513R69
could be placed into the if branch where it is used? It is not used anywhere else as far as I can see, and this would very very slightly improve performance because the operation is only performed when used instead of every time. This would at least allow people with named workspaces to disable this sort and would not break existing configs using this feature.
