### ISSUE TITLE
on-click requires two click

### ISSUE THREAD

**Issue by yogeshkumar98103** [Alexays/Waybar#1805]
When I add on-click handler to a module, it actually requires two clicks to fire. After one click the element goes to active state and on second click it goes to focused state. I've verified this by applying different css styles using :focus and :active pseudo-classes. Is this the expected behavior or a bug?

**Comment by bd-g** [comment]
Could you give more details on your setup, OS, version, etc? I don't observe this behavior on any of my modules that have an on-click handler.

**Comment by yogeshkumar98103** [comment]
It was probably a bug in some other library. I updated things and they work fine now. We can close this.
