### ISSUE TITLE
clock.timezone field has no effect

### ISSUE THREAD

**Issue by anarcat** [Alexays/Waybar#1806]
I have the following modules:

```
    "clock": {
        "format": "{:%Y-%m-%d %H:%M:%S %Z}",
        "on-click": "exec foot --hold ncal -C -A2",
        "on-click-right": "exec foot --hold ncal -C -y",
        "interval": 1,
    },
    "clock#utc": {
        "format": "{:%H:%M %Z}",
        "on-click": "exec foot --hold undertime --table",
        "timezone": "Etc/UTC",
    },
```

and they both display show up on the bar. however, the `clock#utc` widget has the same time as the main `clock` widget, even though they are supposed to be in different time zones.

here, right now, the local zone (`%Z`) is UTC-5 (`EST`), not UTC. Yet both times are identical. The second widget even says it's also showing me `EST` which leads me to believe the `timezone` parameter is completely ignored.

I have also tried using the `timezones` parameter instead, `UTC` and `Iceland` as timezones, nothing seems to work. I have also tried to set it for the first clock, no effect.

This is on waybar 0.9.15 on debian testing ("bookworm").

**Comment by Alexays** [comment]
Did you try with another timezone just to check?

**Comment by anarcat** [comment]
yes, i have just tried `[America/Cordoba](https://en.wikipedia.org/wiki/America/Argentina/Cordoba)`, without luck, for example.

**Comment by encbar5** [comment]
I think "Etc/UTC" is not a valid timezone string. It doesn't work for me either. I tried with "GMT" and "UTC" and they both worked. I also tried with "America/Chicago" and that worked.

**Comment by anarcat** [comment]
On 2022-11-27 17:53:39, EN wrote:
> I think "Etc/UTC" is not a valid timezone string. It doesn't work for me either. I tried with "GMT" and "UTC" and they both worked. I also tried with "America/Chicago" and that worked.

Well I don't know how you tell what a valid string is, but I have tried:

 * UTC
 * GMT
 * Etc/UTC
 * America/Chicago

... none of those work here. I'll also note that the wiki page about the
clock module:

https://github.com/Alexays/Waybar/wiki/Module:-Clock

explicitly links to this Wikipedia page:

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

... which lists "Etc/UTC" as "Canonical" and "UTC" as a "link" to
"Etc/UTC". :p

So something else is going on here. Maybe I have the wrong locale?

-- 
La mer, cette grande unificatrice, est l'unique espoir de l'homme.
Aujourd'hui plus que jamais auparavant, ce vieux dicton dit
littéralement ceci: nous sommes tous dans le même bateau.
                        - Jacques Yves Cousteau - Océanographe

**Comment by encbar5** [comment]
Oops, yeah if I run `timedatectl list-timezones` I get a full list which includes Etc/UTC. I'm using Wabar v0.9.16 on ArchLinux.

**Comment by ewollesen** [comment]
I'm seeing the same behavior as the original author. I've tried several timezones as well.

Waybar 0.9.9 on Ubuntu 22.04... So I guess my next step is to update to the latest version. The 0.9.9 is what was distributed with Ubuntu.

**Comment by anarcat** [comment]
using the latest in debian (0.9.17) and i still have this problem.

**Comment by anarcat** [comment]
i have also tried with the latest HEAD, no luck still. is there some way i could debug this further? i have tried enabling debugging (log-level=trace), but it doesn't give that much info.

**Comment by anarcat** [comment]
> latest HEAD

for the record, that was d259307

**Comment by anarcat** [comment]
i was informed this could be an instance of #1908, which is basically a packaging problem in Debian (or waiting for C++ to modernize, see #668).

workaround:

```
    "custom/clock": {
        "exec": "TZ=UTC date +'%H:%M %Z'",
        "interval": 5
    },
```
