### ISSUE TITLE
2 icons 

### ISSUE THREAD

**Issue by GeoDerp** [Alexays/Waybar#182]
There seems to be 2 icons appering with an _or_ in the middle, "it should be showing `Editor ` ".

(As shown on the top left of this image) 
![screenshot](https://lh3.googleusercontent.com/W2H7fzwS62bYpa5Z5JAsDkVeGXQlPXjHnwI4ZHAfZYtpPpgtMhgkAwhnVieB9Qm25Y6gStxMDHgFY9V3YEvfpU8D-aPDUN7SoAKDYvX7Y1qZDtfK9zeY3cke0YPRCyJH6JFQ06e1TfQ=w666-h375-no)

Using compiled version of sway and waybar on Fedora 29 and using `font-family: FontAwesome5Free;`

**Comment by GarlandKey** [comment]
Do you have an icon listed in your waybar config too? If so, waybar might be confused as to which one it should use. Please post the section of your waybar config regarding workspaces.

**Comment by GeoDerp** [comment]
> Do you have an icon listed in your waybar config too? If so, waybar might be confused as to which one it should use. Please post the section of your waybar config regarding workspaces.

[config](https://github.com/GeoDerp/Fedora-Sway-WM-Build-/blob/master/dooooots/waybar/config})
[my dot files](https://github.com/GeoDerp/Fedora-Sway-WM-Build-/tree/master/dooooots)

**Comment by Alexays** [comment]
@GeoDerp Did you fix your pb?

**Comment by GeoDerp** [comment]
> @GeoDerp Did you fix your pb?

Unfortunately not, even with the latest versions of everything im still getting some weird things happening with  and  using ```font-family: FontAwesome5Free``` .  Seems to me here are 2 icons sharing the same unicode or something. 

I'm grabbing the *FontAwesome5Free* strait from github. Copying Font Awesome 5 Brands-Regular-400,  Font Awesome 5 Free-Regular-400, Font Awesome 5 Free-Solid-900 otf files to the .fonts dir 

My dot files if your interested in helping out: [SwayWM_Build](https://github.com/GeoDerp/SwayWM_Build/tree/master/dooooots)

![2019-04-25-000134_grim](https://user-images.githubusercontent.com/18461782/56668323-7b655980-66ee-11e9-93cf-927c10f720ad.png)

**Comment by GeoDerp** [comment]
Figured it out. Pulled the git repository but only copied the .ttf files and not the .otf fields. It seems like for Font Awesome the oft files store the majority of the text + some random icons and the .ttf file store only icons. While using the .otf's there must be also a clash with some of their old icons and new ones making fonts confused to which on to use. 
Since im only using the icons from the .ttf's for font awesome (meaning no text will show up) I *stole* your style.css example and modified it to  ``` font-family: FontAwesome5Free, Roboto, Helvetica, Arial, sans-serif; ``` which allows font awesome icons to be displayed and on highest priority and all the other  font files to fill in the caps underneath. 

If anyone is interested this is my new way for pulling from github:
```
  cd ~/
  git clone https://github.com/FortAwesome/Font-Awesome.git
  mkdir ~/.fonts
  mv Font-Awesome/webfonts/*.ttf ~/.fonts/
  sudo rm -r ~/Font-Awesome # clean up 
```

Thanks so much
