### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by darksilentcore** [Alexays/Waybar#1830]
Hello & thanks

My bar in v0.9.15
![000000000001](https://user-images.githubusercontent.com/112352585/204059538-f41c1be1-cc35-41f8-aa26-57a56e0d9ac9.jpeg)

Same bar in 0.9.16
![221126014122](https://user-images.githubusercontent.com/112352585/204059582-ab68107b-9cdc-41e5-bc2a-6413d936cf13.jpeg)

I don't have much knowledge
Please help me
I struggled a lot with the config file
But I could not get the output of the previous version in the new version
[config.zip](https://github.com/Alexays/Waybar/files/10095212/config.zip)

Thanks again

**Comment by Alexays** [comment]
Yep we reverted some breaking change in 0.9.16, you could add padding to your config to fix the issue :)

**Comment by darksilentcore** [comment]
Tx
I edited but i have 1 new idea
I will open new issue
