### ISSUE TITLE
Stop suggesting users to set `XDG_CURRENT_DESKTOP=Unity`

### ISSUE THREAD

**Issue by q234rty** [Alexays/Waybar#1833]
Currently waybar does this in https://github.com/Alexays/Waybar/blob/f2fcadbf625344f9b952a80276cfb54c46253b8b/src/modules/sni/tray.cpp#L13-L15 . This can have unforseen consequences like Qt apps using the gtk theme, or things like flameshot or xdg-desktop-portal not functioning correctly. Plus, I'm not aware of any popular app that still needs this.

**Comment by LukashonakV** [comment]
Agree, tray works well with XDG_CURRENT_DESKTOP=sway. This config is mandatory for xdg-desktop-portal with wayland session. According [Arch wiki](https://wiki.archlinux.org/title/Xdg-utils#Environment_variables) XDG_CURRENT_DESKTOP should contain actual DE.

**Comment by Alexays** [comment]
Done in 2111865efe25528829c9407696a0f093bff142e2
