### ISSUE TITLE
[help] hover color on custom module

### ISSUE THREAD

**Issue by Antidote1911** [Alexays/Waybar#1838]
With 0.9.15 i can change the hover color to red of a simple custom launcher module:

```bash
"custom/firefox": {
	"format": "",
        "on-click": "firefox"
},
```
In css:
```css
#custom-firefox:hover{
    color: red;
}
```

But not work with 0.9.16 with the revert of https://github.com/Alexays/Waybar/pull/1120

Anyone can help to achieve this with 0.9.16 ? thank you. 

Merci beaucoup pour le boulot. Waybar est super chouette !

**Comment by stefonarch** [comment]
Here it works perfect with 0.9.16-2 on arch, actually I ignored always the syntax `custom-<module>` and tried with  `custom/module>` which never worked. So thanks!
```

    "custom/kbdlayout": {
        "format": "{}",
        "max-length": 40,
        "interval": 1,
        "exec": "/home/stef/bin/kbdlayout",
    }
```

```
#custom-kbdlayout{
  color: white;
}
```

Imo issue can be closed.

**Comment by Wadekiny** [comment]
same problem, `:hover` with 0.9.17  seems to do nothing, although I set `on-click`

**Comment by BvngeeCord** [comment]
Is there any way to do this? With the revert of #1120, I can't figure it out. Tried a bunch of options, but as it seems from reading through github issues it's not possible anymore. I also read something about a bump to gtk4 from 3 being helpful? Are we stuck for now?

**Comment by iamkarlson** [comment]
It would be really nice to have hover effects on all elements of the waybar, it would add so much juice to the interface.

**Comment by benmoussatMouad** [comment]
Why was #1120 reverted, this feature takes the styling to another level.

**Comment by phrogg** [comment]
I would also love to have this!

**Comment by Alexays** [comment]
Fixed with https://github.com/Alexays/Waybar/pull/3145
