### ISSUE TITLE
How to show all workspaces in module on hyprland

### ISSUE THREAD

**Issue by yuneguy** [Alexays/Waybar#1849]

**Comment by eneshecan** [comment]
I assume you use `wlr-workspaces`. `all-outputs` options is the one you looking for.

**Comment by Okanda** [comment]
This doesn't work for me. I put these  tow lines but only active workspace are visibles. 
	"wlr/workspaces": {
		"active-only": "false",
		"all-outputs": "true",

**Comment by eneshecan** [comment]
Ah, wait. The values should be of type `bool` like this;
```json
"wlr/workspaces": {
"active-only": false,
"all-outputs": true,
"...": "..."
}
```

**Comment by theg721** [comment]
I have the same issue. I'm definitely using bools not strings.

**Comment by theshatterstone** [comment]
@theg721 Yes, same issue, now fixed. @Alexays I think you can now close this because it's been fixed.
