### ISSUE TITLE
add max character length for hyprland/window

### ISSUE THREAD

**Issue by chinh4thepro** [Alexays/Waybar#1859]
Firefox has really long tab names and keeps messing with my clock's location, I've tried using the `max-length` in my configuration but it doesn't seem like it does anything.

ex. 
![image 1](https://user-images.githubusercontent.com/34662114/205316192-7fe57892-f531-45ef-8753-3a62002dd457.png)

How it should look.
![image 1(1)](https://user-images.githubusercontent.com/34662114/205316846-59c89f12-1d28-4590-a8d0-4ca961c07b51.png)

This is how I used it in my hyprland configuration:
```
"hyprland/window": {
    	"max-length": 10,
        "format": "{}",
        "separate-outputs": true
},
```

**Comment by eneshecan** [comment]
I believe it's a default feature for modules having a label. FYI, I just tested this on the latest head and saw that it works for me.

**Comment by rubyowo** [comment]
yep its the default
