### ISSUE TITLE
[feature request] taskbar

### ISSUE THREAD

**Issue by Arnaudv6** [Alexays/Waybar#186]
I know that's not tiling managers priority, but I can think of a few cases where this is nice;
* fast switching between full-screen windows.
* sharing a window manager with a loving wife who prefers classical paradigms (paint me here)
by the way, very nice piece of software: thank you much.

**Comment by Arnaudv6** [comment]
let's mention work ongoing from @Anakael: #343

**Comment by Alexays** [comment]
Implemented with #692
