### ISSUE TITLE
format-calendar-weeks won't accept format strings 

### ISSUE THREAD

**Issue by LukashonakV** [Alexays/Waybar#1874]
Reopened. Is based on [Issue 1565](https://github.com/Alexays/Waybar/issues/1565).
Reason: [Commit](https://github.com/Alexays/Waybar/commit/c5babb4c4455a42d0818d401a7f9ab89dc2c3501) breaks the functionality

**Comment by jlaunay** [comment]
I don't know if this is related but I can't manage to have week numbers align.
My calendar is completely shifted, exactly like [here](https://github.com/Alexays/Waybar/issues/1295)
![cal](https://user-images.githubusercontent.com/1137028/207194233-0b34c5e7-5394-403f-807c-e4f58b7bace4.png)

**Comment by LukashonakV** [comment]
Hi @jlaunay  can you share your config please in order to reproduce your case. And which waybar revision do you use ?

**Comment by jlaunay** [comment]
I'm using the git version.
Here is my config:

```json
        "clock": {
            //"tooltip-format": "<span font=\"DejaVu Sans Mono 10\"><big>{:%B %Y}</big>\n<tt><small>{calendar}</small></tt></span>",
            "align": 0,
            "format-alt": "{:%a %d/%m/%Y}",
            "tooltip-format": "<big>{:%B %Y}</big>\n<tt><small>{calendar}</small></tt>",
            "today-format": "<span color='#ff6699'><b><u>{}</u></b></span>",
            "format-calendar": "<span color='#ecc6d9'><b>{}</b></span>",
            "format-calendar-weeks": "<span color='#99ffdd'><b>S{:%V}</b></span>",
            "format-calendar-weekdays": "<span color='#ffcc66'><b>{}</b></span>",
            "calendar-weeks-pos": "right",
            "interval": 30,
            "on-click-right": "gnome-calendar",
            "on-scroll": {
                "calendar": 1
            }
```

**Comment by LukashonakV** [comment]
I guess you're using some specific system font. Which one ? 
On my machine for Waybar it used
```xml
* {
    border: none;
    font-family: "Ubuntu NF";
}

```
With yours config I have 

----

![ps_2022-12-13-17_09_49](https://user-images.githubusercontent.com/23121044/207355603-e87653a8-990a-47a2-95e4-bb60c118fad3.png)

**Comment by LukashonakV** [comment]
Looks like the issue with the system locale. @jlaunay which locale is configured on your machine ?

**Comment by jlaunay** [comment]
I tried with the following style.

```json
* {
    border: none;
    font-family: "Ubuntu NF";
}
```
and even add 

```json
* {
   all: initial;
}
```
But still the same error.

![cal3](https://user-images.githubusercontent.com/1137028/207360381-f3ce2482-cf70-4922-a6eb-f26385886411.png)


My locale is `LANG=fr_FR.utf8` and even with a minimal waybar config the problem persist, I will use a minimal style.css and config to send you.

**Comment by LukashonakV** [comment]
Not sure what's going on here :)))
1. I've installed fr_FR.utf8
2. I'm using yours config

----

![ps_2022-12-13-17_42_44](https://user-images.githubusercontent.com/23121044/207363724-39e9b2a4-0146-47f4-baa3-786418b0a1d2.png)

**Comment by LukashonakV** [comment]
Can you check you're using the freshest git due to yesterday the was changes for clock component?

**Comment by jlaunay** [comment]
I'm sure I'm using the last git revision, I just rebuild it now using the [following PKGBUILD](https://aur.archlinux.org/packages/waybar-git).
I made a minimal test with only clock and the default css from the wiki.

![2022-12-13T15:48:01,423873921+01:00](https://user-images.githubusercontent.com/1137028/207366130-3bbf329d-6483-4b08-9ab2-db0a02272645.png)

**Comment by LukashonakV** [comment]
Can you please try to build [LukashonakV ISSUE#1874](https://github.com/LukashonakV/Waybar/tree/ISSUE%231874) . I've made changes to check whether the issue with aligning of spaces. So it used calendar-format now. If it's OK I'll create PR to the main trunk

**Comment by jlaunay** [comment]
I had a local.conf fontconfig with this

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match>
        <edit mode="prepend" name="family"><string>Noto Sans</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>serif</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Serif</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>sans-serif</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Sans</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>monospace</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Mono</string></edit>
    </match>
</fontconfig>
```

I don't even really remember why, an emoji problem with Firefox maybe.
After deleting this file everything works perfectly, sorry for the time spent on this non subject.

**Comment by LukashonakV** [comment]
Thank you @jlaunay it was useful for me. Moreover I found shall performance issue which want to fix soon )

**Comment by jlaunay** [comment]
Now that my font config problem is gone it's almost perfect.
Only problem with the last week number for some months shift on the right.
I have this for the months of July 2022, April 2023, December 2023, March 2024...
![cal4](https://user-images.githubusercontent.com/1137028/207433119-5eb790de-ab73-431d-8205-388a448f1056.png)
It's not really critical but it would be interesting to know if you have the same issue?

**Comment by LukashonakV** [comment]
Yeah, got the same. Hmm interesting. Need to investigate

**Comment by jlaunay** [comment]
I confirm that commit fix the right padding for week numbers.
(Waybar v0.9.13-355-g995802e)
Thks
