### ISSUE TITLE
max-length in MPD module gets ignored

### ISSUE THREAD

**Issue by 6b6279** [Alexays/Waybar#1892]
Waybar seems to ignore the actual max-length value in the MPD module when the user sets the max-length attribute in the config file.

`max-length: 500` vs. `max-length: 150` with the same track playing on MPD:
![20221217_22h05m09s_grim](https://user-images.githubusercontent.com/109346960/208266002-bde658d0-b2bf-49d8-ba57-35df168673ff.png)
![20221217_22h06m19s_grim](https://user-images.githubusercontent.com/109346960/208266003-70f95172-2313-4145-9199-a8e9de123f2e.png)
It seems like the text gets truncated around 104 characters regardless of the value set in the config file.

**Comment by PickNicko13** [comment]
Doesn't appear to be the case at the moment. Can you confirm that you also don't experience the issue now?

**Comment by 6b6279** [comment]
Yes, the issue has apparently since been solved.

**Comment by Moth-Tolias** [comment]
i'm still getting an issue with mpd incorrectly using max-length - if max-length is set, the module shrinks to a single ellipsis.
