### ISSUE TITLE
[hyprland/language] not respecting format-<lang> options

### ISSUE THREAD

**Issue by k1gen** [Alexays/Waybar#1894]
I compiled Waybar from source, latest commit, in case waybar-hypland-git in AUR is more than 3 days old. I have this: ![image](https://user-images.githubusercontent.com/62500387/208291147-3b59c6f8-1dc7-4a97-b196-67d6fd95725f.png) instead of this: ![image](https://user-images.githubusercontent.com/62500387/208291215-ff7f7101-1d04-46dc-a354-a2b8fbb412b8.png). 
Here's my [config](https://termbin.com/ewbzj).

**Comment by eneshecan** [comment]
Should be fixed with my latest PR on master. git versions of aur always point to the latest commit. Have you tried restarting your bar?

**Comment by k1gen** [comment]
I am having this issue since I installed waybar-hyprland-git three days ago, and your pr is four days old, I am on the latest commit

**Comment by eneshecan** [comment]
It works for me. Maybe, could you please check the debug log prints?

Otherwise, try to set `keyboard-name` to `at-translated-set-2-keyboard`. You can get yours via `hyprctl devices` command.

**Comment by eneshecan** [comment]
Wait, I also belive that there is no `format-us`, it should be `format-en`. Wiki is wrong about that.

**Comment by k1gen** [comment]
I have three layouts: us,ru,ua. And russian is displayed correctly: "ru", but English and Ukrainian are not. I think it may be because of format-us and not format-en & format-ua instead of format-uk. I have blackout now since I'm Ukrainian, so I will update on this ASAP

**Comment by k1gen** [comment]
![image](https://user-images.githubusercontent.com/62500387/208778925-4d138614-8c7b-45ef-a64a-5df3be44a25d.png) with `"format-en": "us"`. `-uk` instead of `-ua` for Ukrainian worked too. @eneshecan, thank you for help, it was actually wiki's fault
