### ISSUE TITLE
Waybar does not function properly in overlay mode

### ISSUE THREAD

**Issue by alyssa-sudo** [Alexays/Waybar#1895]
The bar is unable to be clicked or hovered over when in overlay mode, happens regardless of layer being top or bottom.
https://streamable.com/1u7szw

**Comment by alebastr** [comment]
It's a feature, see "mode overlay" description in [`sway-bar(5)`](https://github.com/swaywm/sway/blob/master/sway/sway-bar.5.scd). Modes in waybar match the behavior of corresponding swaybar modes.

If you don't need to control the bar with sway IPC, you can get the same effect by removing `mode` and setting `"exclusive": false`.

**Comment by alyssa-sudo** [comment]
Ah, I see, thank you. I'll close the issue now.

**Comment by alyssa-sudo** [comment]
It seems like this bug has been reintroduced in 0.9.24

https://github.com/Alexays/Waybar/assets/83582297/629cd05b-0ebf-46c0-b763-244a29349bda

**Comment by alyssa-sudo** [comment]
Figured it out again, has to do with double quotes around the boolean. Closing.
