### ISSUE TITLE
(hyprland/language) "format-<shortcode>" doesn't resolve if a keyboard variant is used

### ISSUE THREAD

**Issue by flowfield-dev** [Alexays/Waybar#1901]
I'm trying to display my keyboard layouts with the following configuration:
```json
"hyprland/language": {
    "format": "{}",
    "format-en": "English",
    "format-hu": "Hungarian"
}
```

This configuration works well when I'm not using a specific keyboard variant for the Hungarian layout. However, I need to use the `101_qwerty_comma_dead` variant to type Hungarian on an English keyboard without any issues. When I specify this variant in my hyprland configuration, Waybar displays the XKBD name for the layout (`Hungarian (QWERTY, 101-key, comma, dead keys)`) instead of the name I specified in the `format-hu` field (`Hungarian`).

Is there a way to specify the variation that not mentioned in the wiki, or is it not possible yet?

**Comment by k1gen** [comment]
try `format-hu_101_qwerty_comma_dead` or `format-hu-101_qwerty_comma_dead` or something like that

**Comment by flowfield-dev** [comment]
Tried both of them already, they don't work unfortunately :(

**Comment by k1gen** [comment]
I had a [similar issue](https://github.com/Alexays/Waybar/issues/1894), but didn't have to use layout variants to fix it

**Comment by eneshecan** [comment]
Could you please check again with latest master?

**Comment by flowfield-dev** [comment]
This seems to solve it, thank you!

**Comment by guttermonk** [comment]
I'm having a similar issue using two english variants (qwerty and colemak-dh) and getting the customized "US" and "DH"  names to display.

```
        "hyprland/language" = {
          format = "{}";
          format-en = "  us";
          format-en = "  dh";
          keyboard-name = "apple-inc.-apple-internal-keyboard-/-trackpad";
          on-click = "hyprctl switchxkblayout apple-inc.-apple-internal-keyboard-/-trackpad next";
        };
```
I get the following error when I try to use the above configuration in NixOS:
`error: attribute 'format-en' already defined at /nix/store/jcw0hy1dz7lxpvrccnl0c9gdcq34qyj6-source/home/system/waybar/default.nix:174:11`

As suggested above, I tried including the variant on the second format-en (i.e. format-en_colemak_dh), but that didn't work either.

When I don't specify `format-en` at all, they appear in waybar as `English (US)` and `English (Colemak-DH)`, which is little too verbose for a toolbar. Any suggestions on how to use two variants of the same language? Thanks in advance to anyone that can help.

**Comment by wtf-is-flying** [comment]
> As suggested above, I tried including the variant on the second format-en (i.e. format-en_colemak_dh), but that didn't work either.

Using `format-en-colemak_dh` works for me now.

My full configuration:

```
  "hyprland/language": {
    "format": "  {}",
    "format-en": "en",
    "format-en-colemak_dh": "dh"
  },
```

Hope this helps.
