### ISSUE TITLE
document two different implementations of "clock"

### ISSUE THREAD

**Issue by mythi** [Alexays/Waybar#1908]
it's not obvious for the wiki or man page readers that there are two different implementations of clock. `simpleclock` does not come with all the calendar features and just errors:

```
[error] clock: argument not found
```

`simpleclock` gets selected by default in Debian based distro's where the date lib is not available.

**Comment by wdog** [comment]
I have the same error, can you explain in more detail the  cause of the problem (and the fix... is there's one)?

**Comment by mythi** [comment]
> clock works for me (debian/bookworm) but not the calendar

Debian does not build with all the needed build dependencies to satisfy calendar needs so `simpleclock` get selected:
https://github.com/Alexays/Waybar/blob/ea38eec2afd249481df737cc38e055974f83967c/meson.build#L322-L330

I *think* ` libhowardhinnant-date-dev` is needed for that but that's only available in unstable. #1959 added some options but that requires GCC 13.

**Comment by anarcat** [comment]
this was also extremely confusing to me and was basically the cause of #1806... it seems to me simpleclock and clock should just be two separate modules.... maybe the `clock` module should just not be available otherwise..

**Comment by rustycoat** [comment]
Outside of documentation on the wiki (and man-page) to make this issue clear until it is resolved, it seems like a runtime warning would be wise if it's non-trivial to implement it.

Obviously if there's a fix instead it eliminates having to document :).

**Comment by LukashonakV** [comment]
Actually I'm thinking of migration from date library to std:chrono. Need to investigate this.

**Comment by LukashonakV** [comment]
Hi @mythi , [WIKI CLock](https://github.com/Alexays/Waybar/wiki/Module:-Clock) is updated. Please check.
If it's ok, can you close the issue?

Thank you

**Comment by anarcat** [comment]
LGTM.

**Comment by mythi** [comment]
@LukashonakV thanks! I made minor updates but thanks a lot for doing this. I'm fine closing.
