### ISSUE TITLE
Sharing custom modules configuration

### ISSUE THREAD

**Issue by monsieurh** [Alexays/Waybar#195]
It would be great to have a central place to share config tips & trics and/or dotfiles. What is the preferred way to do so ?
- The wiki ?
- A folder with samples ?
- A third party website ?

**Comment by cjbassi** [comment]
I think a wiki page would be a good way to do it. I just added a wiki page to post examples: [link](https://github.com/Alexays/Waybar/wiki/Examples) Feel free to add yours! I think it works well, the only issue being that statusbars are kindof a weird dimension so its a little hard to see the images :man_shrugging:

**Comment by Alexays** [comment]
You can add your custom module here `/resources/custom_modules` :smiley: 
And yeah it's great to add your bar settings to the wiki :heart:
