### ISSUE TITLE
MPRIS: omit empty values

### ISSUE THREAD

**Issue by rodrgz** [Alexays/Waybar#1953]
I put a song on youtube through qutebrowser and possibly the album field was not omitted, the same happens in other browsers.

Another thing that I found strange is the length of the track, as well as it font size. 

I think it would be interesting if the format could be essentially dynamic, so if you receive a:
`"format": "DEFAULT: {player_icon} {artist} {album} {title}"`
and if the album was null, it would just hide that field.

![2023-01-17T11:22:37,519652017-03:00](https://user-images.githubusercontent.com/53882428/212926286-642362bc-d5f1-44b3-83fe-bf4fed6dd87a.png)

my config:

```
    "mpris": {
      "format": "{player_icon} {status_icon} {dynamic}",
      "format-paused": "{player_icon} {status_icon} <i>{dynamic}</i>",
      "max-length": 45,
      "player-icons": {
        "chromium": "爵",
        "default": "",
        "firefox": "",
        "kdeconnect": "",
        "mopidy": "",
        "mpv": "",
        "spotify": "阮"
      },
      "status-icons": {
        "paused": "",
        "playing": "契",
        "stopped": "栗"
      }
    },
```

**Comment by chayleaf** [comment]
this is already implemented in the current version as `{dynamic}` tag

**Comment by rodrgz** [comment]
fixed by https://github.com/Alexays/Waybar/pull/2011
