### ISSUE TITLE
Backlight module hangs instead of disabeling

### ISSUE THREAD

**Issue by Robinhuett** [Alexays/Waybar#196]
I share my config between my notebook and my workstation.
On my notebook everything works fine but on my workstation the backlight modules hangs because of the missing backlight.
Since it's outputting a empty string there is a gap in my bar.
I think the best way to handle this, would be to disable the module (like the battery module).

**Comment by Alexays** [comment]
@ianhattendorf There is a possibility to do a throw outside the thread so that the module disables itself?

**Comment by ianhattendorf** [comment]
@Robinhuett, by "hangs" you mean that it just isn't finding a backlight resulting in a gap in the bar, right? Should be easy enough to do an initial check for a backlight and exit if not found.

**Comment by Robinhuett** [comment]
@ianhattendorf Exactly. Would be nice to a check like this in place.
