### ISSUE TITLE
Refreshing Tray icons

### ISSUE THREAD

**Issue by hughwilliams94** [Alexays/Waybar#197]
Tray items are often used to give updates on the status of running programs i.e. Nextcloud will inform whether the local folder is up to date with a green tick. However, when waybar initially loads icons generally appear in one state (Nextcloud client has grey syncing symbol) and then the waybar tray icons remain in that state forever, as if the tray is not refreshing or something. Killing waybar after the programs have fully loaded and reopening waybar causes the correct tray icons to appear. Is there any way for the Waybar tray to refresh periodically to capture changing states of icons?

**Comment by Alexays** [comment]
Yeah this is not implemented atm, i have to find time to do this
Dups of #21
