### ISSUE TITLE
Font rendering issues

### ISSUE THREAD

**Issue by martinlindhe** [Alexays/Waybar#1970]
waybar 0.9.17, sway 1.8

I want to display the current moon phase in a waybar plugin that I made.

I chose to use the code points 1f311 to 1f318 of to show the current phase.

Rendering these glyphs on waybar have a visual artifact that can be seen in this image:

![20230123_12h59m10s_grim](https://user-images.githubusercontent.com/181531/214034505-9f0fd8bc-13a4-44b6-bff8-d27a666c97ad.png)

Here is a waybar config snippet to trigger the rendering issue from the screenshot:

```
...
    "clock": {
        "format": "{:%H:%M} 🌑🌒🌓🌔🌕🌖🌗🌘"
    }
...
``` 

Font used: Noto Color Emoji   # pacman -S noto-fonts-emoji

**Comment by Alexays** [comment]
I think the glitch is due to the use of a text-shadow on css side?

**Comment by martinlindhe** [comment]
Wow, in hindsight that's obvious. Thank you for being spot-on :)

 `text-shadow` from my css for `window#waybar` was the issue!
