### ISSUE TITLE
"Battery time remaining" format should enable for leading zeros

### ISSUE THREAD

**Issue by Zocker1999NET** [Alexays/Waybar#1974]
On the [wiki for the Battery module](https://github.com/Alexays/Waybar/wiki/Module:-Battery) there is only described in the example for the `format_time` option how to insert the hour & minute data. However, they do not add leading zeros, so the format `{H}:{M}` looks like `1:5` for 1 hour and 5 minutes, which looks awful (at least to me). E.g. I would like to have `1:05` in such cases. So I would propose to add support for the lower cases `h` & `m` to show a leading zero for single digit numbers.

If there is already a way to have a leading zero, it maybe should be added to the wiki page.

**Comment by mike-lloyd03** [comment]
I came looking for the same info and found #1412. Use `{m}` in the format string.

**Comment by Zocker1999NET** [comment]
@mike-lloyd03 Thanks for your hint! Finally I have satisfaction when reading the remaining time of my battery. I added it to the [the wiki page](https://github.com/Alexays/Waybar/wiki/Module:-Battery).
