### ISSUE TITLE
Feature request: set device for upower module

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#1979]
It would be nice to have an ability to set an exact Upower device, which will instead of a main battery. I want to see both my laptop battery and my bluetooth headphones (when connected) battery level on the panel (not in the tooltip). For laptop battery, `battery` module does fine, but headphones only show up in upower.

**Comment by eternal-sorrow** [comment]
I need it for `upower` module, not battery module. Bluetooth devices battery is not available for the battery module, only for the upower.

**Comment by LukashonakV** [comment]
Hi @eternal-sorrow this is done.  You can check now

**Comment by eternal-sorrow** [comment]
I looked at the PR, seems okay to me. I'll wait until this is in the release to check it out.
