### ISSUE TITLE
PangoMarkupFormat stopped working?

### ISSUE THREAD

**Issue by alexthebuilder** [Alexays/Waybar#198]
Looks like a recent update has caused the spans I use to separate and style some inner text is now showing. Was there a change in how the output needs to be formatted or is this a defect?

[Image of my current bar](https://imgur.com/a/PrExFyv)

**Comment by Alexays** [comment]
Reverted the change 0271e9bc1a3ed0d29b99519f3b6ae59b0bbeb677
Should work as intended now

**Comment by alexthebuilder** [comment]
Looks good now Thanks!

**Comment by Robinhuett** [comment]
@Alexays Wouldn't it be better to introduce a toggle to disable the escaping instead of just reverting the change. I think escaping text should be default as I think that it can be quiet irritating for new users :thinking:

**Comment by alexthebuilder** [comment]
If the idea is to be similar to i3blocks they addressed the issue in this - https://github.com/vivien/i3blocks/issues/226

**Comment by Alexays** [comment]
@Robinhuett for me the best default option would be to leave it like that and make an option for beginners to escape the script output

**Comment by Robinhuett** [comment]
Fair enough. Espeacially since this is the behaviour of i3blocks (and as far as I could see also polybar).
If you like I can make an PR tomorrow.

**Comment by Alexays** [comment]
@Robinhuett No worries, done in 79b0367e6c61063d2a6107afa2c5e53f90a575fb
