### ISSUE TITLE
Virtual keyboard 

### ISSUE THREAD

**Issue by baltevl** [Alexays/Waybar#1980]
I'm on sway v1.8 using waybar v0.9.17 with the language module. Everything working fine except utilizing a wayland virtual keyboards (for example with 'wtype') causes the module to stop displaying the current keyboard layout. Switch the layouts fixes the issue.  
Part of output of `swaymsg -t get_inputs`:  
``` 
{
    "identifier": "0:0:wlr_virtual_keyboard_v1",
    "name": "wlr_virtual_keyboard_v1",
    "vendor": 0,
    "product": 0,
    "type": "keyboard",
    "repeat_delay": 600,
    "repeat_rate": 25,
    "xkb_layout_names": [
      "English (US)",
      "German"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)"
},
```

**Comment by EorlBruder** [comment]
This looks related to  #1536
