### ISSUE TITLE
hyprland/language module is not updating on layout change

### ISSUE THREAD

**Issue by Vladeeg** [Alexays/Waybar#1989]
I recently moved to the waybar-hyprland-git AUR package from waybar-hyprland, and noticed some changes with hyprland/language:

1. Now it correctly sets layout name on startup, even respecting format-<name> settings (confirmed by changing the layout and restarting waybar)
2. Module doesn't seem to react on layout changes while waybar is running (stays on the layout detected on startup)

My config for it is:
```json
"hyprland/language": {
    "format": "{}",
    "format-ru": "ru",
    "format-us": "us",
    "format-en": "us",
    "keyboard-name": "at-translated-set-2-keyboard"
}
```

Switching back to waybar-hyprland fixes the issue (it is now on 0.9.16 version from 2023-01-17), but format-<name> settings are not respected (module shows full layout name instead of shorthands).

**Comment by Vladeeg** [comment]
Update: on version 2023-01-17, module shows nothing until first layout change, not full layout name.

By "format- settings are not respected" I meant "format- settings are not respected on startup" :)

**Comment by impankratov** [comment]
@Vladeeg had same problem too, just updated to `0.9.17.r66.gea38eec2-1`, restarted waybar and it seems to detect layout change correctly now

**Comment by Vladeeg** [comment]
> @Vladeeg had same problem too, just updated to `0.9.17.r66.gea38eec2-1`, restarted waybar and it seems to detect layout change correctly now

You're right, tried that too and now it works! Guess I can close the issue now, thanks
