### ISSUE TITLE
System freeze after refreshing after style.css update

### ISSUE THREAD

**Issue by GarlandKey** [Alexays/Waybar#201]
I've noticed that everytime I adjust style.css and then refresh sway, the entire system freezes - no journalctl errors listed. I have to hard reset each time this happens. If I log out of sway and log back in this doesn't happen. I can otherwise refresh sway repeatedly and it won't crash unless I've edited style.css.

I don't get a kernel panic but the trackpad and keyboard stop responding and all on screen activity is frozen.

**Comment by Alexays** [comment]
Surely not waybar fault.
