### ISSUE TITLE
clock module not recognizing {calendar} and not displaying html formatting in tooltip

### ISSUE THREAD

**Issue by rustycoat** [Alexays/Waybar#2014]
Using the example below:

"clock": {
        "format": "{:%I:%M}",
        "tooltip-format": "<big>{:%a %b
%d}</big>\n<tt><small>{calendar}</small></tt>",

}

I get the following in my log when running waybar: "[error] clock: argument not found". 

At that point, if you mouseover, there is no tooltip.

In trying to track down what was going on, I tried checking whether tooltips worked on the clock by removing the braces from 'calendar', in which case, it then displays with all html/pango formatting as plain text. If, within the tooltip, I use clock formatting, such as "{:%H}" the replacement is probably processed, but any html/pango formatting is still plaintext.

This is with Waybar v0.9.17 on Sway 1.7 and Debian Bookworm.

**Comment by rustycoat** [comment]
A couple more bits of info.

1. The error is the same as if 'calendar' was not recognized (if I replace {calendar} with {typo}) I get the same error. Similar if I set "time-zoned_time_list" as the replacement, I get the same error.
2. The error repeats itself on every update. 
3. If you set "tooltip": false, then the error doesn't occur.

I think the error is being thrown in these lines somewhere (195-198 of clock.cpp):
`text = fmt::format(locale_, fmt::runtime(tooltip_format), shifted_ztime,
                         fmt::arg(kCalendarPlaceholder.c_str(), calendar_lines),
                         fmt::arg(KTimezonedTimeListPlaceholder.c_str(), timezoned_time_lines));
label_.set_tooltip_markup(text);`

Unfortunately I've not got the time, setup or knowledge to contribute, but I tried to at least narrow down some things. I'm guessing it's an error displayed from the gtk_label's set_tooltip_markup call...

I'm not sure if displaying raw html/pango in tooltips is connected to this problem or not. That is occurring in all tooltips. I'm guessing Pango is somehow not working on the calls to set_tooltip_markup (perhaps a dependency issue -- this is on Debian 12 but I believe I had the problem on 11 too on this machine before upgrading -- with minimal sway install).

**Comment by LukashonakV** [comment]
Hi @rustycoat ,
1. Can you provide here the whole clock config section
2. Can you check Clock [WIKI](https://github.com/Alexays/Waybar/wiki/Module:-Clock) and try it first

**Comment by LukashonakV** [comment]
Hi @rustycoat  is there any update ?

**Comment by rustycoat** [comment]
Hi there, I've not got a running copy right now, but I gave an example of a config that generates the bug in my first post. Even if the exact config in the wiki is pasted, i.e.:
 
` "clock": {
        "format": "{:%H:%M}",
        "tooltip-format": "<tt><small>{calendar}</small></tt>"
}`

The same bug is generated. As I said, also the pango is not shown formatted -- so if I change tooltip-format to "<small>test</small>" it will display as plaintext "<small>test</small>" written rather than in small text.

Unfortunately I'm not running my sway setup right now, so it's hard to test any potential changes, but I put a large amount of time into testing every possibility. So unless there's something specific you'd like me to try (already checked locales and specified them) or a package dependency you think I might be missing, it's not worth it for me to reinstall and set things up... But if there's something very specific you think I can do to narrow things down for you to diagnose or reproduce, I can set aside some time to reinstall and set things up...

**Comment by LukashonakV** [comment]
@rustycoat Are you using it on Debian?

**Comment by rustycoat** [comment]
Yes. Debian Bookworm (Testing/12) I provided versions in the first post: "This is with Waybar v0.9.17 on Sway 1.7 and Debian Bookworm."

**Comment by LukashonakV** [comment]
> Yes. Debian Bookworm (Testing/12) I provided versions in the first post: "This is with Waybar v0.9.17 on Sway 1.7 and Debian Bookworm."

@rustycoat there is an issue #1908. It is found out there are two clock modules. On Debian there are not date library support,  so simple clock is used instead of clock. Simple clock doesn't support calendar functionality,  time zones looping..

**Comment by rustycoat** [comment]
Yup, looks like issue #1908 is a duplicate on the calendar issue.

Still there's the pango formatting not being processed in all modules tooltips, but since I've not got time to reinstall I'm fine if you want to just close out the issue...

**Comment by LukashonakV** [comment]
@rustycoat can you close the issue then? Only author or project owner can close it. 
Thanks
