### ISSUE TITLE
waybar crashes when mpd disconnects

### ISSUE THREAD

**Issue by hellobye65536** [Alexays/Waybar#2020]
When using a unix domain socket to connect to mpd, waybar crashes when mpd disconnects.

Using sway on gentoo, with waybar 0.9.17

logs:
```
[2023-02-20 21:35:56.730] [debug] mpd: fetching state information
[2023-02-20 21:35:56.731] [debug] mpd: fetch complete
[2023-02-20 21:35:57.646] [warning] mpd: Playing: error: Broken pipe
[2023-02-20 21:35:57.646] [debug] mpd: Playing: disabled 1 second periodic timer.
[2023-02-20 21:35:57.646] [debug] mpd: Disconnected: enabled interval timer.
waybar: ../libmpdclient-2.20/src/status.c:390: mpd_status_get_song_pos: Assertion `status != NULL' failed.
fish: Job 1, 'waybar --log-level trace' terminated by signal SIGABRT (Abort)
```

**Comment by 2e0byo** [comment]
I think this is identical to my issue in #2045 (not that that helps here as I've not caught what's causing it).  Are you able to trigger this reliably just by disconnecting mpd?  and how are you doing so---just killing the process?

**Comment by 2e0byo** [comment]
@hellobye65536 can you try my PR? but if mpd dies whilst waybar is accessing it then it will fail, because `libmpdclient` doesn't handle that gracefully.

**Comment by hellobye65536** [comment]
I've tried your PR (I assume you mean #2046), and it doesn't seem to fix it. I can trigger this reliably by just killing the mpd process. This crash doesn't happen while using the TCP socket for mpd, and only happens using the unix domain socket.
