### ISSUE TITLE
calendar: week number wrong

### ISSUE THREAD

**Issue by Linus789** [Alexays/Waybar#2029]
Waybar always says the week number is 00 for the first week of the year. If it is a continuation from the old year, it should be 52 instead. Also, the week number 01 is not determined correctly for some years. Please take a look at this: https://en.wikipedia.org/wiki/Week#Numbering. If possible, a date library should be used to determine the week number, because there are several different numbering systems: https://en.wikipedia.org/wiki/Week#Other_week_numbering_systems.

**Comment by LukashonakV** [comment]
Hi @Linus789 ,
You opened the issue, btw there are no any proofs, waybar config you're using, system locale
For example:
1. Config
```json
"clock": {
        "format": "{:%H:%M}  ",
        "format-alt": "{:%A, %B %d, %Y (%R)}  ",
        "tooltip-format": "\n<small><tt>{calendar}</tt></small>",
        "calendar": {
                    "mode"          : "year",
                    "mode-mon-col"  : 3,
                    "weeks-pos"     : "right",
                    "on-scroll"     : 1,
                    "format": {
                              "months":     "<span color='#ffead3'><b>{}</b></span>",
                              "days":       "<span color='#ecc6d9'><b>{}</b></span>",
                              "weeks":      "<span color='#99ffdd'><b>W{}</b></span>",
                              "weekdays":   "<span color='#ffcc66'><b>{}</b></span>",
                              "today":      "<span color='#ff6699'><b><u>{}</u></b></span>"
                              }
                    },
        "actions": {
                   "on-click-right": "mode",
                   "on-click-forward": "tz_up",
                   "on-click-backward": "tz_down",
                   "on-scroll-up": "shift_up",
                   "on-scroll-down": "shift_down"
                    }

```
2. Screenshot
![ps_2023-02-28-14_48_52](https://user-images.githubusercontent.com/23121044/221849958-3ffb8c2a-2baf-42ab-a4fb-c19fe54688b8.png)
3. Have you checked supported formats ? https://howardhinnant.github.io/date/date.html see section **to_stream formatting** Take an attention on formats: %U and %W. These flags are supported by the waybar config
4. It's better to ask a question in [Discussions](https://github.com/Alexays/Waybar/discussions)
5. Waybar Clock doesn't calculate Week number itself. This functionality is provided by the [Date library](https://howardhinnant.github.io/date/date.html) and calculates is based on the first day of the row(per week)

**Comment by Linus789** [comment]
@LukashonakV Thanks! It seems like %W is not ISO-based but %V is. Using %V has solved this issue.
