### ISSUE TITLE
calendar: mode action not working without format-alt

### ISSUE THREAD

**Issue by Linus789** [Alexays/Waybar#2030]
Without the `format-alt` option specified in the clock, right clicking to change the mode does not work.

Config (right click does not work here):
```json
"clock": {
	"format": "{:%Y-%m-%d}",
	"tooltip-format": "<tt><small>{calendar}</small></tt>",
	"tooltip": true,
	"calendar": {
		"mode": "year",
		"mode-mon-col": 3,
		"weeks-pos": "right",
		"on-scroll": 1,
		"on-click-right": "mode",
		"format": {
			"months": "<span color='#ffead3'><b>{}</b></span>",
			"days": "<span color='#ecc6d9'><b>{}</b></span>",
			"weeks": "<span color='#99ffdd'><b>W{}</b></span>",
			"weekdays": "<span color='#ffcc66'><b>{}</b></span>",
			"today": "<span color='#ff6699'><b><u>{}</u></b></span>"
		}
	}
},
```

**Comment by LukashonakV** [comment]
Hi @Linus789 , redefining of the module action is implemented and waiting for approval. Once it's merged you can specify any button for actions are supported by Clock module. See https://github.com/Alexays/Waybar/pull/2019

**Comment by LukashonakV** [comment]
Hi @Linus789 #2019 is merge into the master.
So now your are able to redefine Clock actions on your wish. 
Please see: 
1. [Module actions config](https://github.com/Alexays/Waybar/wiki/Configuration#module-actions-config)
2. [Wiki clock](https://github.com/Alexays/Waybar/wiki/Module:-Clock)

If it's Ok for you , please close an issue.
Thank you

**Comment by Linus789** [comment]
@LukashonakV Now I’m not even able to change the mode or scroll to change the year. My config:
```json
"clock": {
	"format": "{:%Y-%m-%d}",
	"format-alt": "{:%Y-%m-%d}",
	"tooltip-format": "<tt><small>{calendar}</small></tt>",
	"tooltip": true,
	"calendar": {
		"mode": "year",
		"mode-mon-col": 3,
		"weeks-pos": "right",
		"on-scroll": 1,
		"format": {
			"months": "<span color='#ffead3'><b>{}</b></span>",
			"days": "<span color='#ecc6d9'><b>{}</b></span>",
			"weeks": "<span color='#99ffdd'><b>W{:%V}</b></span>",
			"weekdays": "<span color='#ffcc66'><b>{}</b></span>",
			"today": "<span color='#ff6699'><b><u>{}</u></b></span>"
		},
		"actions": {
			"on-click-right": "mode",
			"on-click-forward": "tz_up",
			"on-click-backward": "tz_down",
			"on-scroll-up": "shift_up",
			"on-scroll-down": "shift_down"
		}
	},
	"interval": 1
},
```
Built waybar from commit b7e6a2d.

**Comment by LukashonakV** [comment]
@Linus789 Actions should be under Clock block, not calendar.

**Comment by LukashonakV** [comment]
> @LukashonakV Thanks, that worked. But when I remove the `format-alt` option in the clock, the right click still doesn’t work.

That's interesting,  will check soon

**Comment by LukashonakV** [comment]
Hi, @Linus789 .Fix is merged. Please check again.

**Comment by Linus789** [comment]
@LukashonakV Yes, it works now. Thanks for the fast fix!
