### ISSUE TITLE
segfault with mpd: `song_.get()` can return null.

### ISSUE THREAD

**Issue by 2e0byo** [Alexays/Waybar#2045]
Under some conditions* no song is in fact playing, so `song_.get()` returns null, but waybar does not realise this and tries to update the label anyway.  Thus `libmpdclient` functions are called with a nullpointer and segfault.

*Unfortunately in the middle of debugging I restarted mopidy and the problem went away, so I don't know what was happening, only that mopidy was running fine and had no problem interacting with `mpc`.  I have waybar built with debugging symbols and running in gdb to catch this when it happens again.  I'll update this issue and remove this message when that happens.   As a guess `stopped()` is probably failing.

**Comment by bretello** [comment]
I think I have been experiencing this issue, which seemed to happen when waking up from sleep/suspend (mpd being stopped), resulting in the module not updating anymore. I'll test this in the coming days, but I think that #2046 might fix this. Thanks!
