### ISSUE TITLE
[Feature] workspaces scrolling for wlr/workspaces

### ISSUE THREAD

**Issue by milkknife** [Alexays/Waybar#2050]
Scrolling with the mouse wheel on the workspaces module to cycle between workspaces works fine for [sway](https://github.com/Alexays/Waybar/wiki/Module:-Sway#workspaces) but not on [hyprland](https://github.com/Alexays/Waybar/wiki/Module:-Workspaces).

**Comment by dedguy21** [comment]
are you including the needed hyprctl call?
