### ISSUE TITLE
Wireplumber shows on bar but does not update its volume level until connect and disconnect bluetooth headset.

### ISSUE THREAD

**Issue by mrpingo** [Alexays/Waybar#2069]
Hello, and thank you for bringing us Waybar.

Wireplumber module shows on waybar at first instance but the module does not update volume state until I connect and disconnect for example a bluetooth headset. After that, module shows volume as it should be from the start.

Thanks in advance.

**Comment by Phl3gmaTREEc** [comment]
Can confirm same issue here, anything we can provide to help resolve this? Or is there to a way to configure the module?

**Comment by smoak** [comment]
What version of waybar are you running?

The latest release (0.9.17) was on Jan 11 and does not have this fix https://github.com/Alexays/Waybar/commit/4e8ccf36b54cacf5281726d23ea14312a133f977

Can you try compiling from source to see if that fixes your issue?

**Comment by mrpingo** [comment]
Yes, that is the first thing I did, I did also today just to see if something changed but no. Neither 0.9.17 nor latest sources fix the issue.

Same issues as this one popped out:
https://github.com/Alexays/Waybar/issues/2086

**Comment by mrpingo** [comment]
Hovering the mouse on top of the icon shows "Loopback PCM"

**Comment by mrpingo** [comment]
some useful logs:

```
[2023-04-15 17:55:12.396] [warning] [wireplumber]: (onMixerChanged) - Object with id 68 not found
[2023-04-15 17:55:12.397] [warning] [wireplumber]: (onMixerChanged) - Object with id 68 not found
[2023-04-15 17:55:12.472] [warning] [wireplumber]: (onMixerChanged) - Object with id 68 not found
```

**Comment by mrpingo** [comment]
Hey @smoak! I just compiled from sources and now is working as it should be! Many thanks! I will keep this issue opened until the next release is out to keep testing it.

**Comment by mrpingo** [comment]
-This is still happening when changing volume with wireplumber as it seems everytime I press the volume +/- key it prints each time 132 in theese lines which is related to the volume key I guess:
(Each time I press it prints one line)

**sway.log**
`[2024-01-05 17:29:03.311] [warning] [wireplumber]: (onMixerChanged) - Object with id 132 not found
[2024-01-05 17:29:03.316] [warning] [wireplumber]: (onMixerChanged) - Object with id 132 not found
------------------------
[2024-01-05 17:29:03.323] [warning] [wireplumber]: (onMixerChanged) - Object with id 132 not found
[2024-01-05 17:29:04.679] [warning] [wireplumber]: (onMixerChanged) - Object with id 132 not found
[2024-01-05 17:29:04.682] [warning] [wireplumber]: (onMixerChanged) - Object with id 132 not found
`

-When I press the mute key nothing is printed.

-When I press the key to mute the mic, then 51 is printed:
(Each time I press it prints one line)

`[2024-01-05 17:32:09.321] [warning] [wireplumber]: (onMixerChanged) - Object with id 51 not found
[2024-01-05 17:32:09.914] [warning] [wireplumber]: (onMixerChanged) - Object with id 51 not found
[2024-01-05 17:32:10.142] [warning] [wireplumber]: (onMixerChanged) - Object with id 51 not found
`

So this is still around.

Many thanks again for improving WayBar and for taking a look into this.

**Comment by izmyname** [comment]
Can confirm, I have the same problem with the volume level not updating when connecting Bluetooth headphones.

**Comment by izmyname** [comment]
> I just tried building `master` (using arch AUR, commit [21906f0](https://github.com/Alexays/Waybar/commit/21906f07b312d56f51ce7cd2b26925cd12880ada)) and I can't reproduce the bug there, seems to be working perfectly.
> 
> @izmyname @mrpingo does it work for you?

Not on top of my priority to test this, for now, I'm sorry.

**Comment by izmyname** [comment]
> I just tried building `master` (using arch AUR, commit [21906f0](https://github.com/Alexays/Waybar/commit/21906f07b312d56f51ce7cd2b26925cd12880ada)) and I can't reproduce the bug there, seems to be working perfectly.
> 
> @izmyname @mrpingo does it work for you?

yup

**Comment by mrpingo** [comment]
Also for me! Thanks!
