### ISSUE TITLE
keyboard-state with caps:swapescape 

### ISSUE THREAD

**Issue by burbschat** [Alexays/Waybar#2082]
I am using waybar with sway. In my sway config I have
```
input "type:keyboard" {
    xkb_options caps:swapescape
}
```
as I prefer to have escape and caps lock switched for usage with vim.

In my waybar config I have something like the following:
```
"keyboard-state": {
    "capslock": true,
    "format": "{name} {icon}",
    "format-icons": {
        "locked": " ",
        "unlocked": " "
    }
}
```
This results in the intended behavior if I remove the escape/caps lock option from my sway config. 
However if it is there, the indicator behaves weirdly, but never just changes when I press escape (which now should have the effect of caps lock), or caps lock (which now should have the effect of escape) alone.
I found that when I press escape and then caps lock the indicator toggles reliably.
I have verified this on two different keyboards.

I'd suspect that this may be related to how the caps lock state is retrieved.

**Comment by IIlllllII** [comment]
Today I experimented swapping the `Esc` and `Caps` keys in Sway. Then `keyboard-state` broke, so I added this configuration (refer to [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Keyboard-State#config)) to fix it: 
```
"binding-keys": [58, 1, 70]
```
where `1` corresponds to the `Esc` keycode.
