### ISSUE TITLE
Wireplumber module not responding to updates

### ISSUE THREAD

**Issue by zenzoa** [Alexays/Waybar#2086]
Waybar launches showing the correct current volume level, but when I then change the volume, Waybar fails to update. I'm using Hyprland on Arch Linux.
Here are the following (potentially) relevant bits of my waybar config:
```
{
"layer": "top",
"position": "top",
"height": 30,
"margin": 6,
"spacing": 0,
"modules-left": [ "wlr/workspaces" ],
"modules-center": [ "hyprland/window" ],
"modules-right": [ "wireplumber", "network", "battery", "clock" ],

"wireplumber": {
	  "format": "<span size='xx-large'>{icon}</span>",
	  "format-muted": "<span size='xx-large'>󰝟</span>",
	  "format-icons": ["", "", ""],
	  "tooltip-format": "volume: {volume}%"
},

...
```

And my hyprland.conf:
```
# start panel
exec-once = waybar

# start volume/brightness indicator
$WOBSOCK = ~/.config/wob.sock
exec-once = rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob

# start easyeffects
exec-once = easyeffects --gapplication-service

# volume
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume -l "1.0" @DEFAULT_AUDIO_SINK@ 5%+
bindle = , XF86AudioRaiseVolume, exec, wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}' > $WOBSOCK
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume -l "1.0" @DEFAULT_AUDIO_SINK@ 5%-
bindle = , XF86AudioLowerVolume, exec, wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}' > $WOBSOCK
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMute, exec, wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{if ($3) print 0; else print int($2*100)}' > $WOBSOCK

...
```

**Comment by theshatterstone** [comment]
Hi. I'm running into similar issues with the Wireplumber module. For me, this is how I run my wireplumber config:

 "wireplumber": {
        "format": "Vol: {volume}%",
        "format-muted": "Vol: M"
    },

I also run amixer instead of wpctl commands for keybindings.

!!!IMPORTANT!!! PLEASE READ BELOW!!! Also, @Alexays This might be helpful for fixing the wireplumber issues:

For me, it starts updating the volume only when it detects a change of device e.g connecting to my Bluetooth headphones. It works when I connect the headphones, it works when I disconnect them, but it doesn't start working, until I connect them once, I don't know why. I just think that this can be helpful to make it work. If your Bluetooth device connects before the bar is started, disconnect it, and the bar will work. It somehow triggers on device change, I don't know why.

**Comment by zenzoa** [comment]
Is there a way to force-trigger a device change as a workaround in the meantime?

(Btw I am using AUR's wayland-hyprland-git)

**Comment by zenzoa** [comment]
One more clue - I'm not sure what I was doing when this happened, but waybar logged this error, suggesting that it has the wrong node id:
```
[2023-04-07 07:15:34.094] [warning] [wireplumber]: (onMixerChanged) - Object with id 99 not found
[2023-04-07 07:15:34.097] [warning] [wireplumber]: (onMixerChanged) - Object with id 99 not found
[2023-04-07 07:15:34.109] [warning] [wireplumber]: (onMixerChanged) - Object with id 99 not found
```
The actual id is 79:
```
 ├─ Sinks:
 │      37. Easy Effects Sink                   [vol: 1.00]
 │  *   79. Built-in Audio Analog Stereo        [vol: 0.15]
```

**Comment by smoak** [comment]
What version of waybar are you running?

The latest release (0.9.17) was on Jan 11 and does not have this fix https://github.com/Alexays/Waybar/commit/4e8ccf36b54cacf5281726d23ea14312a133f977

Can you try compiling from source to see if that fixes your issue?

**Comment by theshatterstone** [comment]
@smoak Hi, Just wanted to let you knw that I tried compiling from source, as you recommended (I'm also using Hyprland on Arch Linux) and not only did that not fix things, but also the wlr/workspaces module is now not being recognised by waybar as a module for some reason, so now I don't even get the workspaces showing up, while the wireplumber issue is still there.

**Comment by o-peter** [comment]
Using Hyprland on Gentoo same issue, even when built straight from the master branch (aka live ebuild on gentoo). Only goes away when I change the output device.

**Comment by zenzoa** [comment]
Nice! Since the hyprland patch isn't included by default, I'm stuck with waybar-hyprland/waybar-hyprland-git for now. But at least that tells us that the problem is solved somewhere in the experimental features, and the fix would just need to be un-experimental-ized... and maybe hyprland workspace support along with it? ;)

**Comment by foopsss** [comment]
I'm also facing this issue on Gentoo with the latest stable version (0.9.17). Using the PulseAudio module is not an option anymore if using PipeWire because now the use flag that compiles Waybar with support for that module also brings the PulseAudio daemon as a dependency.
