### ISSUE TITLE
Clock with seconds

### ISSUE THREAD

**Issue by javierpenadalua** [Alexays/Waybar#209]
Hi,
First of all, thank you for this very nice bar!

I am trying to configure the clock module with seconds, using this format:
:%A %d %B %Y %I:%M:%S %p
I setted the interval parameter with value of 1 second, but the clock only get refreshed every two or three seconds.

Best regards,
Javi.

**Comment by Alexays** [comment]
Fixed with ef88f0a223a9211743332ea471b6f554fc20f1a1

**Comment by javierpenadalua** [comment]
Now works fine! Thank you so much :)
