### ISSUE TITLE
certain songs with characters cause mpris title too not update

### ISSUE THREAD

**Issue by Hellzbellz123** [Alexays/Waybar#2091]
was working on turning my current hyprland theme into something shareable and i noticed that the mpris module was spewing this into the log, not sure how to prevent this on my end, is their a way too have the title not treated as special by gtk?

`
(waybar:114900): Gtk-WARNING **: 15:43:58.688: Failed to set text 'spotify    BLXXDY NXSE (feat. Scarlxrd & nascar aloe)  Jasiah  01:50/03:07' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
`

**Comment by chayleaf** [comment]
please try https://github.com/Alexays/Waybar/pull/2092
