### ISSUE TITLE
Show all workspaces?

### ISSUE THREAD

**Issue by ReekyMarko** [Alexays/Waybar#210]
I'm very new to Sway and Waybar, so sorry if this is a stupid question.

I have my setup almost complete, but I would like to show all workspaces, even empty ones. Is this possible to do somehow? The reason for doing this, is if I open something in workspace 2 before workspace 1, they appear in the wrong order on the bar which is very confusing.

**Comment by FlorianFranzen** [comment]
Yes, just add the following to your config:
```
"sway/workspaces": {
    "all-outputs": true
}
```

**Comment by ReekyMarko** [comment]
I already have that in my config

**Comment by Alexays** [comment]
Sway only gives the workspace that are created, so it is not possible unless the user specifies the workspace in the waybar config file and we can add this feature

**Comment by AGCaesar** [comment]
I would love this feature. AwesomeWM has it as a default behaviour, but sway refuses do implement this. @Alexays what do you mean with specify the workspaces in waybar config?
I tried this, but it still only showed the first workspace:

 "sway/workspaces": {
         "disable-scroll": false,
         "all-outputs": true,
         "format": "{name}: {icon}",
         "format-icons": {
             "1": ".",
             "2": "",
             "3": "",
             "4": ".",

**Comment by Alexays** [comment]
@AGCaesar Yeah it's just a exemple to how we can implement this feature

**Comment by AGCaesar** [comment]
Please try to implement it! I searched for persistent workspaces for sawy/i3 and found many people who would love this feature!
Thanks for your work with this beautiful and easy to use bar!

**Comment by Alexays** [comment]
Done in #330
