### ISSUE TITLE
CSS options for idle_inhibitor?

### ISSUE THREAD

**Issue by ainola** [Alexays/Waybar#211]
I'd like to be able to have css styling dependent on the state of the idle_inhibitor module - by making the inhibitor visually loud it'd reduce the likelihood of my accidentally leaving it on.

Does it make sense to have `#idle_inhibitor.enabled` and `#idle_inhibitor.disabled`?

**Comment by Alexays** [comment]
Added with 973cec17139c2a4423483c1f975f02f7577bdf83
So you can use `.activated` or `.deactivated`
