### ISSUE TITLE
Define (color) variables in the css config file?

### ISSUE THREAD

**Issue by fritzrehde** [Alexays/Waybar#2112]
It seems like I can't define CSS variables in a `:root` section in the config file. I am trying to do: 
```
:root {
	/* Define generic colors */
	--black: #000000;
	--darkgrey: #2e3440;
	--grey: #787C8F;
	--white: #ffffff;
	--offwhite: #d8dee9;
	--red: #bf616a;

	/* Define theme-specific fg and bg colors */
	--fg: var(--white);
	--bg: var(--black);
}
```
but get the error `[error] style.css:1:1Invalid name of pseudo-clas`. Any ideas why? If this isn't supported, is there any other way of defining variables (for colors)?

**Comment by fritzrehde** [comment]
Thanks a lot, that worked great! If you don't mind me asking (I'm a novice at CSS and new to waybar), is this a general CSS feature (that would work in any CSS file) or a waybar config file CSS specific feature?

**Comment by rileyrg** [comment]
Is there anyway of using an ENV or including a host specific css? I want a different pt size depending on laptop or desktop without duplicating the entire waybar.css.
