### ISSUE TITLE
Custom Module breaking Waybar.

### ISSUE THREAD

**Issue by StarsetKnight** [Alexays/Waybar#2115]
I am Running Hyprland on Arch Linux. I built a custom module called `custom/swaync` which has and Icon and does various commands related to sway notification center. When I left click the module it runs `swaync-client -t -sw` which opens the notification center. When Hyprland (and therefore Waybar) starts up it works fine until I left click on this custom module. Then if I click anywhere else on my bar it opens up swaync, instead of the desired action, until restart. (my config is attached [had to rename it as a txt for GitHub to let me upload it])
[config.txt](https://github.com/Alexays/Waybar/files/11227566/config.txt)

**Comment by child404** [comment]
It's a duplicate of https://github.com/Alexays/Waybar/issues/1968

**Comment by StarsetKnight** [comment]
Ok, that worked. I'll close this.

**Comment by AnoRebel** [comment]
I seem to be facing the same issue and the fix isn't working at all.

**Comment by thore** [comment]
Try adding the 'max-length' option to your custom waybar module config, e.g.:
`"max-length": 2`

**Comment by v4u6h4n** [comment]
> Try adding the 'max-length' option to your custom waybar module config, e.g.: `"max-length": 2`

That worked, thankyou :-)
