### ISSUE TITLE
Per monitor configuration stopped working

### ISSUE THREAD

**Issue by alexjp** [Alexays/Waybar#212]
Hi,

I was using per monitor configuration, by starting config by: [{ .... }, {.... }] , but this seems broken.
If i remove the starting [] it works, but then i lose the possibility of customizing per monitor.

Is there a new way I am not aware of ? this started some 3 or 4 commits back.

Thanks !

**Comment by Alexays** [comment]
Fixed with 2995da845d75b0807ea757833605a4a14ecdc1ea

**Comment by alexjp** [comment]
that was fast :) super thanks !
