### ISSUE TITLE
Can't use curly braces in string in JSON config file

### ISSUE THREAD

**Issue by fritzrehde** [Alexays/Waybar#2123]
I am trying to add the following custom module:
```
    "custom/power_usage": {
        "format": "󰌵 {}",
        "exec": "awk '{ printf("%.2f", $1*10^-6) }' /sys/class/power_supply/BAT0/power_now",
        "restart-interval": 2
    },
```
However, I get the error:
```
[2023-04-17 15:15:37.208] [error] * Line 27, Column 32
  Missing ',' or '}' in object declaration
```
with line 27 being the exec/awk line.
I think this is because of the curly brackets I have inside the string. According to official json, this should be fine, maybe this is a bug in the json parser?

**Comment by tudusek** [comment]
The problem is that you use " in printf so the waybar thinks that its end of the string. Maybe escaping it might work.
`"exec": "awk '{ printf(\"%.2f\", $1*10^-6) }' /sys/class/power_supply/BAT0/power_now",`

**Comment by fritzrehde** [comment]
Thanks, you're right, that fixed it.
