### ISSUE TITLE
[Feature request] Display battery percentage as weighted average of battery levels

### ISSUE THREAD

**Issue by bruceblore** [Alexays/Waybar#2126]
Right now, if you are using a laptop with multiple batteries, it appears that the displayed capacity percentage is just an average of the capacity levels of the individual batteries. This is fine if the batteries are of a similar size, but if the batteries are of significantly different sizes, this can result in the reported percentage not being an accurate representation of how much battery life remains.

For example, it is common for thinkpads to have a 24 WHr internal battery and a 72 WHr removable battery, and to use the removable battery first. The first 50% reported by Waybar will last a long time because the first battery is large. But the second 50% will not last nearly as long. At the moment where 50% is displayed, the laptop really only has 25% of its overall capacity left. In the opposite scenario with the internal battery drained but the removable battery completely full, Waybar still displays 50%, but the laptop has 75% of its overall capacity left.

By using the weighted average of battery capacity levels, with the battery capacities as weights, the battery percentage displayed by Waybar would be much more accurate. It would probably be best to make this optional, in case someone prefers the existing behavior. And it would probably be good to use the `design-capacity` option to determine whether current capacity or design capacity gets used in the calculation.

**Comment by bruceblore** [comment]
I just got some free time and decided to try implementing this myself in pull request #2134. Should I close this issue?

**Comment by Icey-Glitch** [comment]
@bruceblore i was wondering you provide an example of how to use what you added. i have a thinkpad and avg of the 2 bats would be great. thanks!

**Comment by bruceblore** [comment]
"battery": {
            "weighted-average": true
    }
