### ISSUE TITLE
module cava: Unknown module: cava

### ISSUE THREAD

**Issue by XxRiKxX** [Alexays/Waybar#2130]
so I copy-pasted the cava config from the wiki to my config file and when I start waybar, it says that the module is not found. I am using hyprland with waybar-hyprland-git from aur

**Comment by pbosab** [comment]
seems an aur package problem or am I wrong?
https://aur.archlinux.org/cgit/aur.git/log/?h=waybar-hyprland-git

**Comment by LukashonakV** [comment]
It might depend on whether aur contain particular waybar package. Cava was released a couple of days ago.

**Comment by XxRiKxX** [comment]
don't know why they did it, but I will just install the non-git version. Also does the default waybar arch repository works without any problems in hyprland? Thanks!

**Comment by LukashonakV** [comment]
> seems an aur package problem or am I wrong?
> https://aur.archlinux.org/cgit/aur.git/log/?h=waybar-hyprland-git
> 
> *edit: last edit message is: [Remove cava module](https://aur.archlinux.org/cgit/aur.git/commit/?h=waybar-hyprland-git&id=227ac1a905e1429f528614c537fea90a417b9df1)

Thank you, at least now the reason is clear for me. I'll check next week how to handle the issue properly

**Comment by maxmx03** [comment]
I tried to build, but I was getting these errors. I installed Cava, but I still kept getting the error:

`44:16: ERROR: C++ shared or static library 'cava' not found.`

I had to modify line 345 in the meson.build file:

```
cava = compiler.find_library('cava',
                             required: false)
```

distro opensuse - hyprland.

**Comment by thyeun** [comment]
for waybar-hyprland-git version at aur arch linux, during installation/compile, you can see a line mentioned that cava been disable.

Not sure related to this or not.

**Comment by LukashonakV** [comment]
> for waybar-hyprland-git version at aur arch linux, during installation/compile, you can see a line mentioned that cava been disable.
> 
> Not sure related to this or not.

This log exact means waybar was built without cava module support

**Comment by XxRiKxX** [comment]
why did they left cava out though? and also the waybar package from official repo does not work fully. Like the workspaces module.

**Comment by thyeun** [comment]
@XxRiKxX if your WM is under `hyprland` and your config is using `wlr/workspaces` than you need `waybar-hyprland-git` version to make the workspaces work, but if your workspace is under sway (not with wlroots), than you need only `waybar-git`. i think they separate it for cover up wlroot and others, instead that they can combine into one, to have a `mode setting` for wlroot or others.
