### ISSUE TITLE
waybar: error while loading shared libraries: libcava.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by prathameshk23** [Alexays/Waybar#2133]
I get this error while running waybar it runs fine from the ./build

**Comment by LukashonakV** [comment]
Hi @prathameshk23, can you try `sudo ldconfig`, please

**Comment by prathameshk23** [comment]
Still the same

**Comment by LukashonakV** [comment]
> Hi @LukashonakV Still the same

Can you please check:
1. `ninja -C build install`
2. `sudo ldconfig`

**Comment by prathameshk23** [comment]
> > Hi @LukashonakV Still the same
> 
> Can you please check:
> 1. `ninja -C build install`
> 2. `sudo ldconfig`
> 3. and try run waybar as usual

The ninja -C build is not completing throw error while compiling. I tried installing it from the aur still getting the libcava.so error

**Comment by LukashonakV** [comment]
> > > Hi @LukashonakV Still the same
> > 
> > Can you please check:
> > 1. `ninja -C build install`
> > 2. `sudo ldconfig`
> > 3. and try run waybar as usual
> 
> The ninja -C build is not completing throws error while compiling. I tried installing it from the aur still getting the libcava.so error

Can you share aur repo, link, package?

**Comment by prathameshk23** [comment]
> > > > Hi @LukashonakV Still the same
> > > 
> > > Can you please check:
> > > 1. `ninja -C build install`
> > > 2. `sudo ldconfig`
> > > 3. and try run waybar as usual
> > 
> > The ninja -C build is not completing throws error while compiling. I tried installing it from the aur still getting the libcava.so error
> 
> Can you share aur repo, link, package?

https://archlinux.org/packages/community/x86_64/waybar/

**Comment by LukashonakV** [comment]
> > > > Hi @LukashonakV Still the same
> > > 
> > > Can you please check:
> > > 1. `ninja -C build install`
> > > 2. `sudo ldconfig`
> > > 3. and try run waybar as usual
> > 
> > The ninja -C build is not completing throws error while compiling. I tried installing it from the aur still getting the libcava.so error
> 
> Can you share aur repo, link, package?

`sudo ninja -C build install` installs waybar application you just built. It also should install libcava. Then `sudo ldconfig` . Can you try not just build but install too

**Comment by prathameshk23** [comment]
> > > > > Hi @LukashonakV Still the same
> > > > 
> > > > Can you please check:
> > > > 1. `ninja -C build install`
> > > > 2. `sudo ldconfig`
> > > > 3. and try run waybar as usual
> > > 
> > > The ninja -C build is not completing throws error while compiling. I tried installing it from the aur still getting the libcava.so error
> > 
> > Can you share aur repo, link, package?
> 
> `sudo ninja -C build install` installs waybar application you just built. It also should install libcava. Then `sudo ldconfig` . Can you try not just build but install too 

Yes I have done that. Still the same

**Comment by LukashonakV** [comment]
Please last try)
1. `git clone github.com/Alexays/waybar waybar`
2. `cd waybar`
3. `make`
4. `sudo ninja -C build install`
5. `sudo ldconfig`

**Comment by prathameshk23** [comment]
> 

Still not working :(

**Comment by LukashonakV** [comment]
> Hey @LukashonakV, it's working now
If you could check the build log, was waybar built with cava support?

**Comment by ac1dTigR** [comment]
> Hey [@LukashonakV](https://github.com/LukashonakV) its working now

How did you fix it?

**Comment by LukashonakV** [comment]
@ac1dTigR please try to follow [waybar wiki](https://github.com/Alexays/Waybar/wiki/Module:-Cava#solving-issues)

Starting libcava 0.7 this issue should not appear more. But it seems in your system installed the old one. Once you removed old libcava  you will need to rebuild waybar
