### ISSUE TITLE
hyprland/language active keymap does not update

### ISSUE THREAD

**Issue by xadips** [Alexays/Waybar#2137]
The module fails to initialize with my keyboard and I can't seem to get it to work.
Current module config.
```yaml
"hyprland/language": {
        "format": "test {}",
        "format-us": "us",
        "format-lt": "lt",
        "keyboard-name": "duckychannel-international-co.,-ltd.-ducky-keyboard"
}
```
Waybar logs
```
Apr 24 14:01:52 ducky waybar[15926]: [2023-04-24 14:01:52.020] [error] Hyprland IPC: Couldn't get host (2)
Apr 24 14:01:52 ducky waybar[15926]: [2023-04-24 14:01:52.020] [error] hyprland language initLanguage failed with basic_string::substr: __pos (which is 50) > this->size() (which is 0)
Apr 24 14:01:52 ducky waybar[15926]: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '73'
Apr 24 14:01:52 ducky waybar[15926]: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '72'
Apr 24 14:01:52 ducky waybar[15926]: [2023-04-24 14:01:52.028] [error] Hyprland IPC: Couldn't get host (2)
Apr 24 14:01:52 ducky waybar[15926]: [2023-04-24 14:01:52.028] [error] hyprland language initLanguage failed with basic_string::substr: __pos (which is 50) > this->size() (which is 0)
```
I'm not sure whether this is an issue with waybar module or hyprland handling keyboards, there's currently multiple keyboards detected probably because of my keyboard firmware
`hyprctl devices`
```bash
	Keyboard at fb166560:
		duckychannel-international-co.,-ltd.-ducky-keyboard-system-control
			rules: r "", m "", l "us, lt", v "", o "grp:alt_shift_toggle"
			active keymap: English (US)
			main: no
	Keyboard at fb1e01c0:
		duckychannel-international-co.,-ltd.-ducky-keyboard
			rules: r "", m "", l "us, lt", v "", o "grp:alt_shift_toggle"
			active keymap: Lithuanian
			main: no
	Keyboard at fb12cea0:
		duckychannel-international-co.,-ltd.-ducky-keyboard-1
			rules: r "", m "", l "us, lt", v "", o "grp:alt_shift_toggle"
			active keymap: English (US)
			main: no
	Keyboard at fb21e100:
		duckychannel-international-co.,-ltd.-ducky-keyboard-consumer-control
			rules: r "", m "", l "us, lt", v "", o "grp:alt_shift_toggle"
			active keymap: English (US)
			main: yes
```
But only a single one gets its keymap changed when I use the keymap toggle keybind, I've tried setting the keyboard name to all of the above restarting waybar but still got the same error with all of them.

**Comment by xadips** [comment]
After getting the newest commit I can see the indicator but have the same issue of the keymap not changing when I change it with my keybind `grp:alt_shift_toggle`

**Comment by xadips** [comment]
using version
`0.9.17.r161.g757f20fc-1`
The keymap only updates on waybar restart and stays the same no matter 
@d4r1us-drk try using the latest commit, for some people it helped, same as https://github.com/Alexays/Waybar/issues/1989

**Comment by d4r1us-drk** [comment]
I installed waybar-hyprland-git-0.9.17.r161.g757f20fc-1 from the AUR and now the indicator changes with the keybind, which is weird. I forgot to say that the previous behavior was the same as @xadips's situation, the indicator only updates on restart and then stays the same. But now weirdly enough I installed the latest commit and it's working fine.

Also when I first installed waybar-hyprland (last Saturday I think), I installed the git version from the AUR and the module failed to initialize, but when I changed the layout with the keybind, it fixed itself. So I installed the version 0.9.17 and the problem was gone, then the thing stopped updating the keymap and the rest is what I did right now.

**Comment by d4r1us-drk** [comment]
After further testing, I realized this has something to do with the "keyboard-name" variable, when I deleted it, the issue was fixed on version 0.9.17 (not the latest git), I guess now the module now picks whatever keyboard is set to default, which is better for me actually, because I use external keyboards on my laptop. Maybe this issue was all about we setting one specific keyboard with this variable, in which case it's obvious that the indicator will not change if another keyboard is connected and set by default by Hyprland.

**Comment by xadips** [comment]
Version `0.9.17` core dumps for me, can't really check, but it could be to hyprland setting the wrong main keyboard as my keyboard is detected as multiple keyboards currently.
```bash
❯ waybar
[2023-04-27 10:16:10.370] [info] Using configuration file /home/spidax/.config/waybar/config
[2023-04-27 10:16:10.370] [info] Using CSS file /home/spidax/.config/waybar/style.css
[2023-04-27 10:16:10.373] [info] Hyprland IPC starting
[2023-04-27 10:16:10.379] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.
C 10:16:10.384583       GLib-GObject (null):(null):(null): ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '73'
C 10:16:10.384588       GLib-GObject (null):(null):(null): ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '72'
E 10:16:10.390807               GLib (null):(null):(null): g_log_set_writer_func() called multiple times
zsh: trace trap (core dumped)  waybar
```

**Comment by xadips** [comment]
Sadly still doesn't work just wrote myself a custom script to grep the current layout for my keyboard name as a band-aid workaround for now, will revisit if there's any updates to this module.
```bash
#!/bin/bash
LAYOUT=$(hyprctl devices | rg -A 2 'duckychannel-international-co.,-ltd.-ducky-keyboard-1' | grep keymap | awk '{ print $3 }')
[[ "$LAYOUT" == "English" ]] && echo "us" || echo "lt"
```

```json
"custom/keymap": {
        "format": "{}",
        "exec": "bash ~/.config/waybar/scripts/keymap.sh",
        "interval": 1
    }
```

**Comment by archdron** [comment]
> After further testing, I realized this has something to do with the "keyboard-name" variable, when I deleted it, the issue was fixed on version 0.9.17 (not the latest git), I guess now the module now picks whatever keyboard is set to default, which is better for me actually, because I use external keyboards on my laptop. Maybe this issue was all about we setting one specific keyboard with this variable, in which case it's obvious that the indicator will not change if another keyboard is connected and set by default by Hyprland.

Bumping up, as I have the same situation with multiple keyboards. Perhaps, it has something to do with the module not  accepting an array of values for a variable: if you try to pass it like @xadips in the first post, it considers **one device name**, not two; if you pass it in brackets like in module lists (["keyboard 1", "keybopard2"]), you get:

`[warning] module hyprland/language: Disabling module "hyprland/language", Type is not convertible to string`

**Comment by xadips** [comment]
@Alexays #2424 only fixed capslock,numlock toggle issues in keyboard state module, hyprland/language still has issues when it finds multiple keyboards as in language doesn't change when switching, please re-open.

**Comment by pashafst** [comment]
I have the same problem.. After diving in the hyprland language module source code and looking at my debug logs, I might found out that the dispatcher delimiter is `,` and in our keyboard name, there is a comma.. that means, that the event is parsed incorrectly:

my debug log:
```bash
[2023-12-19 11:03:31.793] [debug] hyprland IPC received activelayout>>hp,-inc-hyperx-alloy-origins,English (US)
#                                                                                                                                   ^ not delimiter                  ^ the delimiter
```

`language.cpp`:
```cpp
void Language::onEvent(const std::string& ev) {
  std::lock_guard<std::mutex> lg(mutex_);
  std::string kbName(begin(ev) + ev.find_last_of('>') + 1, begin(ev) + ev.find_first_of(','));
  //                                                                                                                                               ^ this tries to find the delimiter
  // in my case, kbName will be 'hp' instead of 'hp,-inc-hyperx-alloy-origins
  auto layoutName = ev.substr(ev.find_first_of(',') + 1);

  if (config_.isMember("keyboard-name") && kbName != config_["keyboard-name"].asString())
    return;  // ignore

  layoutName = waybar::util::sanitize_string(layoutName);

  layout_ = getLayout(layoutName);

  spdlog::debug("hyprland language onevent with {}", layoutName);

  dp.emit();
}
```

Please note that i haven't really try to fix the code or really debug the source code, since i haven't pulled the wayland source code and mess with it. But I think that we need to adjust the delimiter to be `;` instead of `,` to prevent this problem. I also haven't figured out how to adjust the format of the IPC..

**Comment by pashafst** [comment]
@Alexays I would like to fix this issue by changing the `find_first_of` method.. is there any reason why `find_first_of` method is used and not `find_last_of`?

**Comment by holisticode** [comment]
Sorry but I am not sure I understand how multiple keyboards need to be handled. The ticket is closed but I still have the issue that I have two keyboards, and only one seems to be supported by the widget.

That is, when I try to add both (comma-separated?), the widget doesn't work, and it never changes the content. So currently I have just one keyboard (the external one) enabled, but if I disconnect the laptop to use standalone, of course it doesn't work anymore.

Thanks for clarifying how to have the widget work for both keyboards.
