### ISSUE TITLE
Waybar always dies when I disconnect HDMI cable

### ISSUE THREAD

**Issue by fritzrehde** [Alexays/Waybar#2141]
I know this has been an issue in the past, but I thought this was fixed by now. 
Everytime I connect to an external display (in sway), another waybar shows up on the external display (this is expected).
However, when I disconnect the display, the waybar on my laptop dies, and I have to reload sway to get it back.

**Comment by fritzrehde** [comment]
I will try to build waybar myself soon, and then provide some more detailed error messages. But one thing I noticed today was that the crash/seg fault only occured when I had the power plugged in on my laptop. When my laptop wasn't plugged in, and I unplugged the hdmi cable, waybar didn't die. I thought that was quite strange

**Comment by fritzrehde** [comment]
This seems to have been fixed for me now, I haven't encountered the crash in a while.

**Comment by Alexays** [comment]
Might be fixed with https://github.com/Alexays/Waybar/pull/3215
