### ISSUE TITLE
Crashes when using Firefox to play video

### ISSUE THREAD

**Issue by DivineBicycle** [Alexays/Waybar#2147]
When using Firefox to play video, tried with YouTube, Waybar core dumps:
```
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/optional:477: _Tp &std::_Optional_base_impl<std::basic_string<char>, std::_Optional_base<std::basic_string<char>, false, false>>::_M_get() [_Tp = std::basic_string<char>, _Dp = std::_Optional_base<std::basic_string<char>, false, false>]: Assertion 'this->_M_is_engaged()' failed.

[1]  + 166556 IOT instruction (core dumped)  waybar
```

Seems to be related to #1945, although that mentions it has been fixed. Any way of fixing this other than not using the `mpris` module?

**Comment by OJFord** [comment]
#2065

**Comment by DivineBicycle** [comment]
Slightly erroneous mention in my opinion, that also mentions it's been fixed, but it's not working for me. Using the latest git commit.

**Comment by OJFord** [comment]
They said it 'might be', and it's not closed; I linked it precisely so you might feed back there 'no, still an issue for me too'.
