### ISSUE TITLE
bluetooth module visible if no bluetooth controller found

### ISSUE THREAD

**Issue by Firgen** [Alexays/Waybar#2163]
Issue #1707 still occurs in v0.9.17. I wasn't sure if I should tag you so I opened a new issue.

When the module has some padding or margin set, it is visible as an empty field.
![screenshot_20230508_193951-726744043](https://user-images.githubusercontent.com/29487700/236893937-e7262d94-ac0c-49ef-b547-2d3f2ef48149.png)

When you click on it, it appears as if bluetooth was enabled (my computer doesn't have bluetooth):
![screenshot_20230508_194032-378481588](https://user-images.githubusercontent.com/29487700/236893952-aa13d033-3ee5-4838-9799-9d02dc678a9b.png)

**Comment by PucklaJ** [comment]
I was about to open basically the same issue instead I want to add something to this one. I propose that the module should show either the "format" or "format-disabled" entry when no bluetooth controller has been found.
