### ISSUE TITLE
Cava module on way bar not working

### ISSUE THREAD

**Issue by PraveenRoyal** [Alexays/Waybar#2169]
I am trying to show cava visualizer on my way bar on top but it is not working also my workspaces are also not showing up on the bar I am using waybar inbuilt cava module and also i used the workspaces in built module for way bar. why is it not working i will share my config code here 

`{
  "layer": "top",
  "position": "top",
  "height": 30,
  "width": 1920, // Comment for dynamic width
  "modules-left": [
    "sway/workspaces",
    "custom/separator",
    "idle_inhibitor",
    "mpd",
    "custom/cava-internal",
    "custom/todo"
  ],
  "modules-center": [
    "clock"
  ],
  "modules-right": [
    "network",
    "custom/separator",
    "pulseaudio",
    "custom/separator",
    "backlight",
    "custom/separator",
    "cpu",
    "custom/separator",
    "memory",
    "custom/separator",
    "battery",
    "tray"
  ],
  "custom/separator": {
    "format": "|",
    "interval": "once",
    "tooltip": false
  },
  "sway/workspaces": {
    "disable-scroll": true,
    "persistent_workspaces": {
      "1": [],
      "2": [],
      "3": [],
      "4": [],
      "5": [],
      "6": [],
      "7": [],
      "8": [],
      "9": []
    }
  },
  "clock": {
    "format": "<span foreground='#7dcfff'></span> {:%d %B %Y - %I:%M %p}",
    "interval": 60,
    "tooltip": true,
    "tooltip-format": "{:%A, %d %B %Y}\n<tt>{calendar}</tt>"
  },
  "mpd": {
    "max-length": 30,
    "format": "<span foreground='#bb9af7'></span> {title}",
    "format-paused": "<span style='italic'> {title}</span>",
    "format-stopped": "<span foreground='#bb9af7'></span>",
    "format-disconnected": "",
    "on-click": "mpc --quiet toggle",
    "on-click-right": "mpc ls | mpc add",
    "on-click-middle": "kitty ncmpcpp",
    "on-scroll-up": "mpc --quiet prev",
    "on-scroll-down": "mpc --quiet next",
    "smooth-scrolling-threshold": 5,
    "tooltip-format": "{title} - {artist} ({elapsedTime:%M:%S}/{totalTime:%H:%M:%S})"
  },
  "disk": {
    "interval": 18000,
    "format": "<span foreground='#9ece6a'>﫭</span> {percentage_used}%",
    "tooltip-format": "{used} used out of {total} on {path}"
  },
  "cpu": {
    "interval": 1,
    "format": "<span foreground='#e0af68'></span> {usage}%"
  },
  "memory": {
    "interval": 300,
    "format": "<span foreground='#7aa2f7'>﬙</span> {percentage}%",
    "tooltip-format": "{used:0.2f}GiB used out of {total:0.2f}GiB"
  },
  "battery": {
    "interval": 600,
    "design-capacity": false,
    "states": {
      "warning": 15,
      "critical": 10
    },
    "format": "<span foreground='#f7768e'>{icon}</span> {capacity}%",
    "format-charging": "<span foreground='#f7768e'>{icon}</span> {capacity}%",
    "format-time": "{H}h {M}m",
    "format-icons": [
      "",
      "",
      "",
      "",
      "",
      ""
    ]
  },
  "tray": {
    "icon-size": 15,
    "spacing": 5
  },
  "network": {
    "interval": 1,
    "format-wifi": "<span foreground='#61AF1F'>說</span> {essid} ({signalStrength}%)",
    "format-ethernet": "<span foreground='#61AF1F'></span> {ifname} ({ipaddr})",
    "format-linked": "<span foreground='#61AF1F'>說</span> {essid} (No IP)",
    "format-disconnected": "<span foreground='#61AF1F'>說</span> Disconnected",
    "tooltip": false
  },
  "backlight": {
    "device": "intel_backlight",
    "on-scroll-up": "light -A 5",
    "on-scroll-down": "light -U 5",
    "format": "<span foreground='#b48ead'>{icon}</span> {percent}%",
    "format-icons": [
      "",
      "",
      "",
      ""
    ]
  },
  "pulseaudio": {
    "scroll-step": 1,
    "format": "<span foreground='#d08770'>{icon}</span> {volume}%",
    "format-muted": "婢 Muted",
    "format-icons": {
      "default": [
        "",
        "",
        ""
      ]
    },
    "states": {
      "warning": 85
    },
    "on-click": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
    "tooltip": false
  },
  "custom/cava-internal": {
    "exec": "~/.config/waybar/Cava.sh",
    //"exec": "~/.config/waybar/cava-internal.sh",
    "tooltip": false
  },
  "idle_inhibitor": {
    "tooltip": false,
    "format": "{icon}",
    "format-icons": {
      "activated": "",
      "deactivated": ""
    }
  }
}`

**Comment by LukashonakV** [comment]
Hi @PraveenRoyal ,
Please provide waybar logs: in terminal just run waybar
+ according your's config you are not using standart cava module from the box..  See [Wiki](https://github.com/Alexays/Waybar/wiki/Module:-Cava)
+ One clarification question: are you using waybar hyperland ?

**Comment by PraveenRoyal** [comment]
i ran the waybar command on terminal and i fixed the error.
I yanked the script from some one elses github 
I tried to configure it on my own using built it cava module of waybar but it was not working
so i yanked the script from some one else 
now when i play music i cannot see cava on my waybar i have to run the command "killall -SIGUSR2 waybar" command to reload my waybar and suddenly my waybar appears. How to fix this so that id dont need to reload my waybar when ever i play my music 
and yes i am using hyprland you asked for my log i am providing you with 2 logs one is before cava was not working 

 `sh: line 1: /home/royaleinstein/.config/waybar/Cava.sh: Permission denied
[2023-05-13 12:50:19.601] [error] cava-internal stopped unexpectedly, is it endless?

(waybar:20729): GLib-GObject-CRITICAL **: 12:50:19.640: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '73'

(waybar:20729): GLib-GObject-CRITICAL **: 12:50:19.640: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '72'
[2023-05-13 12:50:19.641] [warning] module wlr/workspaces: Unknown module: wlr/workspaces
[2023-05-13 12:50:19.645] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.
sh: line 1: /home/royaleinstein/.config/waybar/Cava.sh: Permission denied
[2023-05-13 12:50:19.661] [error] cava-internal stopped unexpectedly, is it endless?
[2023-05-13 12:50:20.600] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:20.642] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:25.602] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:25.643] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:30.604] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:30.645] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:35.606] [error] mpd: Failed to connect to MPD: Connection refused
[2023-05-13 12:50:35.646] [error] mpd: Failed to connect to MPD: Connection refused`

now the second logs after this above log are because of my workspaces not working 
`[2023-05-13 13:21:19.267] [info] Using configuration file /home/royaleinstein/.config/waybar/config.jsonc
[2023-05-13 13:21:19.267] [info] Using CSS file /home/royaleinstein/.config/waybar/style.css
[2023-05-13 13:21:19.276] [warning] module wlr/workspaces: Unknown module: wlr/workspaces
[2023-05-13 13:21:19.278] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.

(waybar:26500): GLib-GObject-CRITICAL **: 13:21:19.310: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '73'

(waybar:26500): GLib-GObject-CRITICAL **: 13:21:19.310: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '72'
[2023-05-13 13:21:19.310] [warning] module wlr/workspaces: Unknown module: wlr/workspaces
[2023-05-13 13:21:19.312] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.
`
now cava is working but i need to reload my waybar when ever i start my music player
2. my workspaces are not showing up on my waybar

**Comment by LukashonakV** [comment]
In your case when you don't use cava out of the box:

1. [custom_cava waybar config](https://gitlab.com/Viktar/dotfiles/-/blob/main/.config/waybar/config#L165)
2. [cava config for the first point](https://gitlab.com/Viktar/dotfiles/-/blob/main/.config/cava/waybar_cava.conf)

**Comment by PraveenRoyal** [comment]
when i am using the inbuilt cava module why is the log say Cava unknown module ?
`2023-05-13 21:51:28.101] [info] Using configuration file /home/royaleinstein/.config/waybar/config.jsonc
[2023-05-13 21:51:28.101] [info] Using CSS file /home/royaleinstein/.config/waybar/style.css
[2023-05-13 21:51:28.108] [warning] module cava: Unknown module: cava
[2023-05-13 21:51:28.111] [info] Bar configured (width: 1920, height: 40) for output: HDMI-A-1`

**Comment by PraveenRoyal** [comment]
the code snippet you highlighted worked just fine thanks but the inbuilt cava module not working ?

**Comment by LukashonakV** [comment]
> when i am using the inbuilt cava module why is the log say Cava unknown module ?
> `2023-05-13 21:51:28.101] [info] Using configuration file /home/royaleinstein/.config/waybar/config.jsonc
> [2023-05-13 21:51:28.101] [info] Using CSS file /home/royaleinstein/.config/waybar/style.css
> [2023-05-13 21:51:28.108] [warning] module cava: Unknown module: cava
> [2023-05-13 21:51:28.111] [info] Bar configured (width: 1920, height: 40) for output: HDMI-A-1`

Cause hyperland's maintaner, for some reason disabled cava ability.

**Comment by PraveenRoyal** [comment]
i have one more problem now the workspaces module is not working when i name it i call it wlr/workspaces but in the bar there is no workspaces icons that i put i dont get it... the log says unknown module wlr/workspaces.

**Comment by LukashonakV** [comment]
> i have one more problem now the workspaces module is not working when i name it i call it wlr/workspaces but in the bar there is no workspaces icons that i put i dont get it... the log says unknown module wlr/workspaces.

It's not related to cava. I have no answer on it. Please close the current issue, as the cava is solved for you. For a new issue, for at first try to find the same in issues backlog. Thanks
