### ISSUE TITLE
Enable Pango markup in sway/workspaces

### ISSUE THREAD

**Issue by xPMo** [Alexays/Waybar#217]
Pango markup is available in i3bar and swaybar, for reference:

![Reference image](https://i.imgur.com/6rEhSRz.png)

It is enabled there together with pango markup for the rest of the bar components.
```
bar {
    pango_markup enabled
}
```

**Comment by Alexays** [comment]
Done in bc9a49787a444202ec915694711b87750d498f87
Can be disabled by set `disable-markup: true` in waybar `sway/workspaces` configuration
