### ISSUE TITLE
`sway/window` module text got overlapped with floating window

### ISSUE THREAD

**Issue by declanqian** [Alexays/Waybar#218]
Not sure whether this is known issue, or expected behaviour. Looks broken to me though.
Floating window got hide behind the way. Once you move it under, you can't drag it out by clicking and hold on the title bar using the mouse. 

Does it make more sense to keep the bar at the bottom of windows?

Here is screen shot:
https://imgur.com/Wk8Kzfi

**Comment by Alexays** [comment]
For the desired behaviour you can set layer to bottom
```jsonc
{
    "layer": "bottom",
    "modules-left": ["sway/workspaces", "sway/mode"],
    "modules-center": ["sway/window"],
    "modules-right": ["battery", "clock"],
    "sway/window": {
        "max-length": 50
    },
    "battery": {
        "format": "{capacity}% {icon}",
        "format-icons": ["", "", "", "", ""]
    },
    "clock": {
        "format-alt": "{:%a, %d. %b  %H:%M}"
    }
}
```
