### ISSUE TITLE
Show pulseaudio microphone volume and muted status

### ISSUE THREAD

**Issue by phw** [Alexays/Waybar#219]
Similar to the existing PA module, but show default source instead of default sink with different icon. This could either be integrated into the existing pulseaudio module (with some configuration to show or hide the mic status), or the existing pulseaudio module gets split into two (maybe more flexible for users who want only one or the other).

Use case: I often do audio/video conferencing using a variety of tools. To easily mute / unmute my mic I have configured a keyboard shortcut. But sometimes I don't remember the state of the microphone, having this displayed in waybar would solve this.

**Comment by Alexays** [comment]
Done in bb4af295bc2ee493a3f680c621449566d206976c
Look at the wiki for the configuration :)

**Comment by varac** [comment]
@phw Could you please share the config you're using ?

**Comment by rodrigoramos** [comment]
You can use the properties "format-source" e "format-source-muted".

Example:
```
"pulseaudio": {
    "format": "{icon} {volume}% {format_source}",
    "format-source": "Mic ON",
    "format-source-muted": "Mic OFF"
}
```
