### ISSUE TITLE
Spotiy example module not working

### ISSUE THREAD

**Issue by Anders2303** [Alexays/Waybar#220]
I've copied the spotify example given in the wiki, and the mediaplayer.py file, but nothing is showing up on the bar, and no error messages are printed. Running mediaplayer.py works fine, so there might be a bug in the custom script function?

My config (related parts):
``` 
... 
"modules-right": ["custom/spotify", "pulseaudio", "network", "cpu", "memory", "battery"]
...
    "custom/spotify": {
         "format": " {}",
         "max-length": 40,
         "interval": 30, // Remove this if your script is endless and write in loop
         "exec": "$HOME/.config/waybar/mediaplayer.sh 2> /dev/null", // Script in resources folder
         "exec-if": "pgrep spotify"
     }
...
```
 Did I miss something obvious here?

**Comment by Alexays** [comment]
Try to launch the script by hand, you may missing some dependencies :/

**Comment by Anders2303** [comment]
It seems to be working fine
```[~]$ python .config/waybar/mediaplayer.py 
Home - Sleep
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)
 MASTER BOOT RECORD - Hard Disk (Dma 5)```

By the way, Im using the AUR versions, waybar-git and wlroots-git (I tried the official repository versions, but they didnt work either), if that matters at all

**Comment by Alexays** [comment]
`"exec": "$HOME/.config/waybar/mediaplayer.sh 2> /dev/null"`
Look at the file extension ;)

**Comment by Anders2303** [comment]
Oh! Nice catch! However, it didn't seem to help :/
Tried changing it to `"exec": "$HOME/.config/waybar/mediaplayer.sh 2> /dev/null"`
and `"exec": "python $HOME/.config/waybar/mediaplayer.sh 2> /dev/null"` and still got nothing

**Comment by Alexays** [comment]
Try without the redirection `2> /dev/null` it may print something

**Comment by Anders2303** [comment]
Okay, so it did print something (while not adding `python` to the exec string):
`sh:  ~/.config/waybar/mediaplayer.py: Permission denied´ (repeated each interval)
adding `pyhton` to the string made no prints appear.

Tried `chmod +x .config/waybar/mediaplayer.py`, and it went back to not printing anything :/

**Comment by guyfedwards** [comment]
@Anders2303 I was having issues with this and removing `interval` from the config got it working for me.
My config block looks like this now:
```
    "custom/spotify": {
        "format": "  {}",
        "exec": "$HOME/.config/waybar/spotify 2> /dev/null",
        "exec-if": "pgrep spotify"
    },
```

**Comment by Alexays** [comment]
The mediaplayer script has been refactored and so the config also changed, take a look on it ;)

**Comment by hughwilliams94** [comment]
The refactored script works well apart from one problem, it doesn't show what Spotify is playing if Spotify is started after Waybar. I have to kill Waybar and restart it to get the module to appear.
