### ISSUE TITLE
Clock module no longer scrolls through timezones and doesn't handle empty string as default timezone

### ISSUE THREAD

**Issue by Arnavion** [Alexays/Waybar#2204]
```json
    "clock": {
        "format": "{:%F %T %a %Z}",
        "interval": 1,
        "locale": "C",
        "timezones": [
            "",
            "US/Eastern",
            "UTC"
        ],
        "tooltip-format": "{timezoned_time_list}\n<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
    },
```

This config in v0.9.17 defaulted to my default timezone US/Pacific and allowed me to mouse scroll over the clock module to cycle through the timezones. As of v0.9.18 it displays US/Eastern by default and mouse scrolling does nothing.

Looking at the commits between v0.9.17 and v0.9.18 I came up with this workaround:

```diff,json
     "clock": {
+        "actions": {
+            "on-scroll-up": "tz_up",
+            "on-scroll-down": "tz_down"
+        },
         "format": "{:%F %T %a %Z}",
         "interval": 1,
         "locale": "C",
         "timezones": [
             "",
             "US/Eastern",
             "UTC"
         ],
         "tooltip-format": "{timezoned_time_list}\n<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
     },
```

If it's intentional that users have to bind the event actions to the internal action names in the config manually, then the waybar-clock manpage should be updated to say this because currently it still says that scrolling switches timezones by default. But I assume the change is not intentional and `waybar::modules::Clock` ctor ought to be adding those to `eventActionsMap_` itself.

---

Next, even with this workaround the default is US/Eastern and scrolling switches between only it and UTC, ie it's ignoring the `""` entry instead of treating it like the default timezone, so I had to set that explicitly instead:

```diff,json
     "clock": {
         "actions": {
             "on-scroll-up": "tz_up",
             "on-scroll-down": "tz_down"
         },
         "format": "{:%F %T %a %Z}",
         "interval": 1,
         "locale": "C",
         "timezones": [
-            "",
+            "US/Pacific",
             "US/Eastern",
             "UTC"
         ],
         "tooltip-format": "{timezoned_time_list}\n<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
     },
```

This is again contrary to the manpage which says that `""` represents the system's local timezone.

**Comment by LukashonakV** [comment]
Hi @Arnavion , by nature application is developing. Users wants more options, features, etc. Please revisit : [Wiki Clock](https://github.com/Alexays/Waybar/wiki/Module:-Clock)
New changes brought opportunities to redefine Clock actions. Right in [Example](https://github.com/Alexays/Waybar/wiki/Module:-Clock#example)  point 2 you can find recommended action block.
Yeap, here a gap in man page. I'll check and fix man page soon.
As far as I remember there was an Issue, so when you setup timezone = "" it should use system default TZ. Isn't it ?

**Comment by Arnavion** [comment]
>New changes brought opportunities to redefine Clock actions.

I suggest bumping the major version number (0.9 -> 0.10 in this case) any time you make a change that breaks a previously working config.

>I'll check and fix man page soon.

Thanks.

>As far as I remember there was an Issue, so when you setup timezone = "" it should use system default TZ. Isn't it ?

I don't understand this question. As I wrote in the OP, `timezones: ["", ...]` used to work in v0.9.17 and does not work in v0.9.18.

**Comment by LukashonakV** [comment]
There was huge functionality changes which lead to the mess in clock config. For that purposes clock config was changed.
According timezones... let me check. What's wrong ..

**Comment by LukashonakV** [comment]
Hi @Arnavion ,
- The issue with "" in `timezones` and `timezone` is fixed.
- `clock` man page is aligned with Wiki
Please check

**Comment by Arnavion** [comment]
Thanks. I'm too lazy right now to set up a build environment :) so I'll take your word for it and close this.

**Comment by martin-greentrax** [comment]
Hey, I think the wording in the man page is still misleading as it says:

> "A list of timezones (as in timezone) to use for time display, changed using the scroll wheel."

But this is not the case with a minimal `clock` config. Only when one adds:

```
        "actions": {
            "on-scroll-up": "tz_up",
            "on-scroll-down": "tz_down"
        },
```
