### ISSUE TITLE
[Feature Request] Workspace styles for Hyprland

### ISSUE THREAD

**Issue by donovanglover** [Alexays/Waybar#2211]
Similar to the [Sway module](https://github.com/Alexays/Waybar/wiki/Module:-Sway#style-1), there should be custom styles for [Hyprland workspaces](https://github.com/Alexays/Waybar/wiki/Module:-Workspaces).

Personally, I would love to change the style of the active workspace if it has a fakefullscreen window.

For those that need this feature *now*, you can use Hyprland's [`renameworkspace` dispatcher](https://wiki.hyprland.org/Configuring/Dispatchers/#list-of-dispatchers) with a custom script.

**Comment by gardenappl** [comment]
I'm working on a PR that implements customization similar to Sway, but I'm not sure what the use-case is for `fakefullscreen`. Should it display a custom style if the focused window is `fakefullscreen` (I can kinda imagine this being useful), or should it do it if there's just one such window anywhere on the workspace (why?).

**Comment by donovanglover** [comment]
I use `fakefullscreen` to temporarily show windows in fullscreen while still having access to waybar. Sometimes I forget that there's another window on the same workspace, so an indicator would help me remember that the active window is fullscreen.

Currently I make fullscreen windows a different color with [`hyprland-autoname-workspaces`](https://github.com/hyprland-community/hyprland-autoname-workspaces) and [HTML tags](https://github.com/donovanglover/nix-config/blob/209fb4d9cad8ff52da0187e45673683413495224/home/hyprland-autoname-workspaces.nix#L48), although a waybar solution would be nice as well.

**Comment by gardenappl** [comment]
Interesting, I thought fakefullscreen didn't cover other windows.

I might implement this but only checking the current focused window.

**Comment by donovanglover** [comment]
You're right, I was confusing `fakefullscreen` with `fullscreen, 1`, which "maximizes and keeps gaps and bars". Sorry for the confusion.

And I agree, checking fullscreen for the current focused window would be great.

**Comment by gardenappl** [comment]
Oh that clears it up, thanks.

**Comment by gardenappl** [comment]
The PR was merged and I updated the wiki. (but right now you have to use the -git version to see changes)

**Comment by donovanglover** [comment]
It works great thank you! Very cool that the styles can apply to the entire bar. Lots of possibilities when it comes to customization.
