### ISSUE TITLE
wlr/taskbar: hide taskbar when no open windows

### ISSUE THREAD

**Issue by portus-zephyr** [Alexays/Waybar#2214]
here is my bar with open windows:
![Screenshot_2023-06-06-10-39-55](https://github.com/Alexays/Waybar/assets/66728045/4c77b678-85d3-4c07-af6e-0e7e220cc2fe)

here is my bar with no open windows:
 
![Screenshot_2023-06-06-10-40-20](https://github.com/Alexays/Waybar/assets/66728045/74904b81-c67e-4373-b8c7-e30a31b5c5ca)

it would be nice to remove the black line in the second image when no windows are open.

**Comment by Anakael** [comment]
I'll try to fix that

**Comment by Anakael** [comment]
Now you can use "empty" class for taskbar in order to set `background: transparent`

**Comment by emalsidog** [comment]
Hi. Seem like "empty" class does not work

**Comment by fluid46** [comment]
```css
#wlr-taskbar:empty {
  background: transparent;
}
```
returns:
style.css:48:13Invalid name of pseudo-class
