### ISSUE TITLE
Segmentation fault when reloading waybar with pkill -SIGUSR2 waybar

### ISSUE THREAD

**Issue by Lassebq** [Alexays/Waybar#2224]
Doesn't happen every time, has a chance to properly reload. But fails most of the time.

**Comment by Lassebq** [comment]
Seems to be related to #1749

**Comment by Fxzzi** [comment]
can confirm I also experience the same.

**Comment by Lassebq** [comment]
Some clarification: seems to happen only with tray module

**Comment by Lassebq** [comment]
Seems to be fixed? Running latest commit, no issues here

**Comment by Lassebq** [comment]
Can't reproduce original crash, although a similar crash happens on latest commit:
```
GLib-GIO:ERROR:../glib/gio/gapplicationimpl-dbus.c:837:g_application_impl_command_line: assertion failed: (object_id != 0)
Bail out! GLib-GIO:ERROR:../glib/gio/gapplicationimpl-dbus.c:837:g_application_impl_command_line: assertion failed: (object_id != 0)
zsh: IOT instruction (core dumped)  waybar -c .config/waybar/hyprland.jsonc
```
I think it happens much more frequently if you're running multiple bars, not sure

**Comment by huiser** [comment]
Happens only when I run a second bar.
