### ISSUE TITLE
Persistent workspace

### ISSUE THREAD

**Issue by mairm1340** [Alexays/Waybar#2230]
Hi 
I have the below workspaces configured and I need some assistance to ensure all these workspaces are seen always on the monitor. 

"wlr/workspaces": {
  //"format": "{name}",
  "format": "{name}: {icon}",
  "on-click": "activate",
  "all-outputs": true,
  "sort-by-number": true,
  "format-icons": {
   "1": "WWW  ",
   "2": "CLI  ",
   "3": "FILES  ",
   "4": "TEAMS  ",
   "5": "0365  ",
   "6": "RDP  ",
   "7": "MISC  ",
   "8": "VPN   ",
   "9": "VMware  ",
   "10": " Documents "
},

Can somone please assist me on this.

**Comment by zjeffer** [comment]
See my config for an example: https://github.com/zjeffer/dotfiles/blob/16f5c4994eceff52aa0cd5ef3f8c6055020b3955/.config/hypr/apps/waybar/config.jsonc#L40

**Comment by mairm1340** [comment]
![Uploading image.jpg…]()

**Comment by mairm1340** [comment]
"wlr/workspaces": {
  //"format": "{name}",
  "format": "{name}: {icon}",
  "on-click": "activate",
  "all-outputs": true,
  "sort-by-number": true,
"persistent_workspaces": {
      "1": [
        "HDMI-A-1"
      ],
      "2": [
        "HDMI-A-1"
      ],
      "3": [
        "HDMI-A-1"
      ],
      "4": [
        "HDMI-A-1"
      ],
      "5": [
        "HDMI-A-1"
      ],
      "6": [
        "HDMI-A-1"
      ],
      "7": [
        "HDMI-A-1"
      ],
      "8": [
        "HDMI-A-1"
      ],
      "9": [
        "HDMI-A-1"
      ],
      "10": [
        "HDMI-A-1"
      ],
      "11": [
        "HDMI-A-1"
      ],
    },
  "on-scroll-up": "hyprctl dispatch workspace e+1",
  "on-scroll-down": "hyprctl dispatch workspace e-1",
},

I modified the configuration like this ... still i see only the active one

**Comment by zjeffer** [comment]
I don't think that's something that waybar has control over. I think that's possible with hyprland's windowrules or workspace rules or something, you should check their wiki.

**Comment by imxyy1soope1** [comment]
> Thank you so much
> 
> This did help me to some extent.
> 
> Here is my modified one
> 
> //THIS IS MY CONFIG "wlr/workspaces": { //"format": "{icon}", "format": "{}", "on-click": "activate", "on-scroll-up": "hyprctl dispatch workspace r-1", "on-scroll-down": "hyprctl dispatch workspace r+1", "active-only": false, "all-outputs": false, "sort-by-number": true, "format-icons": { "urgent": "", "active": "", "default": "", "persistent": "" },
> 
> ```
> "persistent_workspaces": {
> 
>   "CLI ": [
>     "HDMI-A-1"
>   ],
>   " WWW ": [
>     "HDMI-A-1"
>   ],
>   " FILES ": [
>     "HDMI-A-1"
>   ],
>   " Teams ": [
>     "HDMI-A-1"
>   ],
>   " Emails  ": [
>     "HDMI-A-1"
>   ],
>   " VPN  ": [
>     "HDMI-A-1"
>   ],
>   " SecureCRT ": [
>     "HDMI-A-1"
>   ],
>   " RDP   ": [
>     "HDMI-A-1"
>   ],
>   " TechM ": [
>     "HDMI-A-1"
>   ],
>   " VMware   ": [
>     "HDMI-A-1"
>   ],
> }
> ```
> 
> },
> 
> //THIS IS MY CONFIG
> 
> How I can associate each workspace ? LIke for example workspace 1 should be CLI workspace 2 should be WWW workspace 3 should be RDP workspace 4 should be TEAMS workspace 5 should be EMAILS
> 
> I want to bind some apps to open in some workspace so that is not working for me. WHen i go on workspace 1 it takes me there but there are some other apps which I want to use on other ws/

I think you should replace "CLI ", "WWW " etc. into "1", "2" etc.
Here is my config:
```jsonc
---SNIP---
"wlr/workspaces": {
        "persistent_workspaces": {
            "1": ["DP-2"],
            "2": ["DP-2"],
            "3": ["DP-2"],
            "4": ["DP-2"],
            "5": ["DP-2"],
            "11": ["HDMI-A-1"],
            "12": ["HDMI-A-1"],
            "13": ["HDMI-A-1"],
            "14": ["HDMI-A-1"],
            "15": ["HDMI-A-1"]
        },
        "on-click": "activate",
        "sort-by-number": true,
        "format": "{icon}",
        "format-icons": {
            "1": "1",
            "2": "2",
            "3": "3",
            "4": "4",
            "5": "5",
            "6": "6",
            "7": "7",
            "8": "8",
            "9": "9",
            "10": "10",
            "11": "1",
            "12": "2",
            "13": "3",
            "14": "4",
            "15": "5",
            "16": "6",
            "17": "7",
            "18": "8",
            "19": "9",
            "110": "10"
        }
    },
---SNIP---
```
This works perfectly like this:
![image](https://github.com/Alexays/Waybar/assets/103114856/caa60b01-67c6-42b3-80e0-c5eecc727aad)

**Comment by khaneliman** [comment]
@mairm1340  Did you end up figuring this out or can this issue be closed?

**Comment by mairm1340** [comment]
Thank you very much!
