### ISSUE TITLE
[Bug]why waybar use so much cpu when i just enable a few basic module

### ISSUE THREAD

**Issue by DreamMaoMao** [Alexays/Waybar#2236]
![image](https://github.com/Alexays/Waybar/assets/30348075/477198cc-7bc4-497d-b063-08c44b137906)
![image](https://github.com/Alexays/Waybar/assets/30348075/0c2f72e7-fd63-4644-9ccc-79a3f9a89b39)
 
j just use basic module :   
"modules-left": ["wlr/workspaces"],
 "modules-right": ["tray","backlight","temperature","network","battery#bat0","cpu","memory","clock"]

but  the cpu usage is up to 30 percent

**Comment by DreamMaoMao** [comment]
Waybar version  v0.9.18-25-g83f3c23 (branch 'master')
os: ubuntu 23.04  hyprland

**Comment by DreamMaoMao** [comment]
`{
    "layer": "bottom", 
    "position": "top", 
    "height": 50,
    "spacing": 5, 

    "margin-bottom":-11,
    "modules-left": ["wlr/workspaces"],
    "modules-right": ["tray","backlight","temperature","network","battery#bat0","cpu","memory","clock"],

    "wlr/workspaces": {
        "format": "{icon}",
        "format-active": " {icon} ",
        "on-click": "~/.config/hypr/scripts/tools/switch_window {name}"
    },

    "keyboard-state": {
        "numlock": true,
        "capslock": true,
        "format": "{name} {icon}",
        "format-icons": {
            "locked": "",
            "unlocked": ""
        }
    },
    "tray": {
        "icon-size": 21,
        "spacing": 10
    },
    "clock": {
        "timezone": "America/New_York",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "interval": 60,
        "format": "{:%I:%M}",
        "max-length": 25
    },
    "cpu": {
        "interval":1,
        "format": "{icon0} {icon1} {icon2} {icon3}",
        "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
    },
    "memory": {
        "format": "{}% "
    },
    "temperature": {
        "thermal-zone": 2,
        "hwmon-path": "/sys/class/hwmon/hwmon1/temp1_input",
        "critical-threshold": 60,
        "format-critical": "{temperatureC}°C",
        "format": ""
    },
    "backlight": {
        "device": "amdgpu_bl0",
        "format": "{percent}% {icon}",
        "format-icons": ["", "", "", "", "", "", "", "", ""]
    },

    "battery#bat0": {
        "bat": "BAT0"
    },
    "network": {
        "interface": "wlp1s0", 
        "format-wifi": "{essid} {signalStrength}%",
        "format-ethernet": "{ifname}",
        "tooltip-format": "{ipaddr} via {gwaddr} {ifname}",
        "format-linked": "{ifname}",
        "format-disconnected": "No network",
        "format-icons":  ["", "", "", "", "", "", "", "", ""]
        }

}`

**Comment by DreamMaoMao** [comment]
my config

{
    "layer": "bottom", 
    "position": "top", 
    "height": 50,
    "spacing": 5, 

    "margin-bottom":-11,
    "modules-left": ["wlr/workspaces"],
    "modules-right": ["tray","backlight","temperature","network","battery#bat0","cpu","memory","clock"],

    "wlr/workspaces": {
        "format": "{icon}",
        "format-active": " {icon} ",
        "on-click": "~/.config/hypr/scripts/tools/switch_window {name}"
    },

    "keyboard-state": {
        "numlock": true,
        "capslock": true,
        "format": "{name} {icon}",
        "format-icons": {
            "locked": "",
            "unlocked": ""
        }
    },
    "tray": {
        "icon-size": 21,
        "spacing": 10
    },
    "clock": {
        "timezone": "America/New_York",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "interval": 60,
        "format": "{:%I:%M}",
        "max-length": 25
    },
    "cpu": {
        "interval":1,
        "format": "{icon0} {icon1} {icon2} {icon3}",
        "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
    },
    "memory": {
        "format": "{}% "
    },
    "temperature": {
        "thermal-zone": 2,
        "hwmon-path": "/sys/class/hwmon/hwmon1/temp1_input",
        "critical-threshold": 60,
        "format-critical": "{temperatureC}°C",
        "format": ""
    },
    "backlight": {
        "device": "amdgpu_bl0",
        "format": "{percent}% {icon}",
        "format-icons": ["", "", "", "", "", "", "", "", ""]
    },

    "battery#bat0": {
        "bat": "BAT0"
    },
    "network": {
        "interface": "wlp1s0", 
        "format-wifi": "{essid} {signalStrength}%",
        "format-ethernet": "{ifname}",
        "tooltip-format": "{ipaddr} via {gwaddr} {ifname}",
        "format-linked": "{ifname}",
        "format-disconnected": "No network",
        "format-icons":  ["", "", "", "", "", "", "", "", ""]
        }

}

**Comment by DreamMaoMao** [comment]
{
    "layer": "bottom", 
    "position": "top", 
    "height": 50,
    "spacing": 5, 

    "margin-bottom":-11,
    "modules-left": ["wlr/workspaces"],
    "modules-right": ["tray","backlight","temperature","network","battery#bat0","cpu","memory","clock"],

    "wlr/workspaces": {
        "format": "{icon}",
        "format-active": " {icon} ",
        "on-click": "~/.config/hypr/scripts/tools/switch_window {name}"
    },

    "keyboard-state": {
        "numlock": true,
        "capslock": true,
        "format": "{name} {icon}",
        "format-icons": {
            "locked": "",
            "unlocked": ""
        }
    },
    "tray": {
        "icon-size": 21,
        "spacing": 10
    },
    "clock": {
        "timezone": "America/New_York",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "interval": 60,
        "format": "{:%I:%M}",
        "max-length": 25
    },
    "cpu": {
        "interval":1,
        "format": "{icon0} {icon1} {icon2} {icon3}",
        "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
    },
    "memory": {
        "format": "{}% "
    },
    "temperature": {
        "thermal-zone": 2,
        "hwmon-path": "/sys/class/hwmon/hwmon1/temp1_input",
        "critical-threshold": 60,
        "format-critical": "{temperatureC}°C",
        "format": ""
    },
    "backlight": {
        "device": "amdgpu_bl0",
        "format": "{percent}% {icon}",
        "format-icons": ["", "", "", "", "", "", "", "", ""]
    },

    "battery#bat0": {
        "bat": "BAT0"
    },
    "network": {
        "interface": "wlp1s0", 
        "format-wifi": "{essid} {signalStrength}%",
        "format-ethernet": "{ifname}",
        "tooltip-format": "{ipaddr} via {gwaddr} {ifname}",
        "format-linked": "{ifname}",
        "format-disconnected": "No network",
        "format-icons":  ["", "", "", "", "", "", "", "", ""]
        }
}

**Comment by DreamMaoMao** [comment]
[my config file ](https://github.com/DreamMaoMao/mywaybar/blob/main/config)

**Comment by LukashonakV** [comment]
Can you turn off the rest of modules one by one to identify the module which consumes CPU?

**Comment by DreamMaoMao** [comment]
the three modules work together
![image](https://github.com/Alexays/Waybar/assets/30348075/06a41f75-3c92-48c2-bbce-3800975936c1)

**Comment by LukashonakV** [comment]
Can you turn off all modules and check again, please?

**Comment by LukashonakV** [comment]
Can you turn off all modules and check again, please?
Upd: which waybar do you use? From git, or OS repository.  What is the OS ?

**Comment by LukashonakV** [comment]
Can you turn off all modules and check again, please?
Upd: which waybar do you use? From git, or OS repository.  What is the OS ?

**Comment by DreamMaoMao** [comment]
> Can you turn off all modules and check again, please? Upd: which waybar do you use? From git, or OS repository. What is the OS ?

you said, "which waybar do you use? "What does that mean

**Comment by LukashonakV** [comment]
Means from Arch repo, or you did the compilation from the source?

**Comment by LukashonakV** [comment]
Means from Arch repo, or you did the compilation from the source?

**Comment by DreamMaoMao** [comment]
> Can you provide build log here please?

[meson build](https://github.com/DreamMaoMao/mywaybar/blob/main/meson_build.log)
[ninja -C build](https://github.com/DreamMaoMao/mywaybar/blob/main/ninja_build.log)

**Comment by DreamMaoMao** [comment]
I have found out what the problem is, is the style sheet color animation causing high cpu usage.
![image](https://github.com/Alexays/Waybar/assets/30348075/e2e2d779-7b2c-4e53-9f52-bdc895f916cb)
