### ISSUE TITLE
Tooltip calendar text overflows

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [Alexays/Waybar#2240]
Hi, after fixing my calendar configuration that was broken with version 0.9.18, I configured the year/month toggleable calendar - very useful.

However, the year calendar has some unexpected text overflow which breaks the formatting. This is how it looks on openSUSE Tumbleweed:
![20230616_19h45m29s_grim](https://github.com/Alexays/Waybar/assets/101266837/5bc498dc-0e80-4f53-94b9-0bb9668dcfe7)

This is the configuration that results in the above screenshot:
```json
     "clock#date": {
        "format": "{:%F %a}",
        "smooth-scrolling-threshold": 4,
        "tooltip-format": "<span color='#35b9ab'><tt><small>{calendar}</small></tt></span>",
        "calendar": {
            "mode-mon-col"      : 4,
            "weeks-pos"         : "left",
            "on-scroll"         : 1,
            "on-click-right"    : "mode",
            "format": {
                "months":    "<span color='#35b9ab'><b>{}</b></span>",
                "weeks":    "<span color='#73ba25'><b>{}</b></span>",
                "weekdays": "<span color='#21a4df'><b>{}</b></span>",
                "today":    "<span color='#35b9ab' background='#173f4f'><b>{}</b></span>"
            }
        },
        "actions": {
            "on-click-right"    : "mode",
            "on-scroll-up"      : "shift_up",
            "on-scroll-down"    : "shift_down"
        },
        "tooltip": true
    },
```
Is there something wrong with the configuration here or the css? Or is there a problem in the calendar with how text is split into a new line?

**Comment by LukashonakV** [comment]
Try to reduce `mode-mon-col` or, for test purposes, move `clock` to the center of waybar just to check

**Comment by LukashonakV** [comment]
The issue seems to me here with GTK Label Tooltip. I didn't find any API's which can help to increase the tooltip width. 
I'll create an issue to upstream once I have a time

**Comment by LukashonakV** [comment]
Upstream issue raised: [GTK Label Tooltip](https://gitlab.gnome.org/GNOME/gtk/-/issues/5900)

**Comment by FilippoBonazziSUSE** [comment]
Thanks for raising the upstream issue.

> Upd: @FilippoBonazziSUSE here is new [cava module](https://github.com/Alexays/Waybar/wiki/Module:-Cava) you might be interested in. See an [example](https://github.com/Alexays/Waybar/wiki/Module:-Cava#example)

How is this related?

**Comment by saltasatelites** [comment]
I've waybar running on Arch Linux but installed directly from github, no pacman, except dependencies.
My calendar window continues misconfigured. Someone has find how to solve that issue?
I am not sure if it has any kind of relationship with the fonts, since it doesn't recognize the calendar icon, but all other icons of the other modules.
Thanks in advance.

**Comment by saltasatelites** [comment]
Change the columns to 2 in "mode-mon-col" solves the issue, but it looks very small

**Comment by FilippoBonazziSUSE** [comment]
Hi, this is still broken, any chance this can be fixed?

**Comment by LukashonakV** [comment]
Hi @FilippoBonazziSUSE , unfortunately not any news from the gtk upstream [GTK3. Label tooltip shifted text](https://gitlab.gnome.org/GNOME/gtk/-/issues/5900)

**Comment by BrianCArnold** [comment]
Okay, so, this is a very simple hack, but it works pretty well, and doesn't require font sizing shenanigans:

```
        "clock#date": {
            "rotate": 0,
            "format-alt": "{:%Y/%m/%d}",
            "format": "{:%b %d, %Y}",
            // To set calendar width, write out the entire length of an entire line in the calendar:
            // `10 11 12 13 14 15 16 W00   10 11 12 13 14 15 16 W00   10 11 12 13 14 15 16 W00   10 11 12 13 14 15 16 W00`
            // Then replace every character in that line with a space:
            // `                                                                                                         `
            // Then take that space, and put it before or after (or both) of `{calendar}` with a newline (`\n`) between that empty line and the `{calendar}`.
            // For best results, probably both? Then also limit the amount of padding-top and/or padding-bottom in the `tooltip label` css.
            // Example:            10 11 12 13 14 15 16 W00   10 11 12 13 14 15 16 W00   10 11 12 13 14 15 16 W00   10 11 12 13 14 15 16 W00
            "tooltip-format": "<tt>                                                                                                         \n{calendar}</tt>",
            "calendar": {
              "mode"          : "year",
              "mode-mon-col"  : 4,
              "weeks-pos": "right",
              "on-scroll"     : 1,
              "format": {
                "months":     "<span color='#ffead3'><b>{}</b></span>",
                "days":       "<span color='#ecc6d9'><b>{}</b></span>",
                "weeks":      "<span color='#99ffdd'><b>W{}</b></span>",
                "weekdays":   "<span color='#ffcc66'><b>{}</b></span>",
                "today":      "<span color='#ff6699'><b><u>{}</u></b></span>"
              }
            },
            "interval": 1
        },
```
Proof: 
![image](https://github.com/Alexays/Waybar/assets/38593283/df97400c-87c7-4dfa-af1b-bde764a3bf5f)

**Comment by LukashonakV** [comment]
Hi there. there is merge request which should solve an issue. In the same time it created an issue and discussion in Gnome comunity:

1. [Gnome Issue#5900](https://gitlab.gnome.org/GNOME/gtk/-/issues/5900)
2. [Gnome discussion](https://discourse.gnome.org/t/label-set-markup/21020)

**Comment by LukashonakV** [comment]
Finally according this discussion
> [Gnome discussion](https://discourse.gnome.org/t/label-set-markup/21020)
solution is found and #3255 is ready to merge

**Comment by LukashonakV** [comment]
According to the gtk maintainer's mention tooltip for GtkLabel has limitations.  So, this MR  fixes the issue without any additional actions from the user side.

**Comment by LukashonakV** [comment]
Hi @FilippoBonazziSUSE,
Can you please check the issue once again in new 0.10.4 Waybar ?
