### ISSUE TITLE
[Question] custom weather module: execute script mutiple times

### ISSUE THREAD

**Issue by lvntcnylmz** [Alexays/Waybar#2252]
Hi, I am using Waybar on sway. i have a custom weather module. What i want to do is when i click on this module it will show the weather information of another city. is it possible to do this?

For example, by default the module shows the weather for New York. When I click on the module, it will show the weather for London. If I click again, it will return to New York.

---

`weather.sh`
```bash
#!/usr/bin/env bash

text=$(curl -s "https://wttr.in/$1?format=1")

if [[ $? == 0 ]]
then
    text=$(echo "$text" | sed -E "s/\s+/ /g")
    tooltip=$(curl -s "https://wttr.in/$1?format=%l:+%C+%c+%t+%w+%m")
    if [[ $? == 0 ]]
    then
        tooltip=$(echo "$tooltip" | sed -E "s/\s+/ /g")
        echo "{\"text\":\"$text\", \"tooltip\":\"$tooltip\"}"
        exit
    fi
fi

echo "{\"text\":\"Service Unavailable\", \"tooltip\":\"Service Unavailable\"}
```

---

`waybar/config.jsonc`
```json
"custom/weather": {
        "format": "{}",
        "format-alt": "{source $HOME/.config/waybar/scripts/weather.sh 'London' 2> /dev/null}",
        "return-type": "json",
        "exec": "$HOME/.config/waybar/scripts/weather.sh 'New York' 2> /dev/null",
        "interval": 300,
        "tooltip": true
    },
```

**Comment by zer0-x** [comment]
I think it's would be great to move/post this question in **Discussions** instead of **Issues**.

I don't think there is a way to do this with Waybar, but you can increment a number every time you click and save it in a file in `/tmp` or `/run/user/???`.
