### ISSUE TITLE
Calendar tooltip renders invalid month on first scroll, and highlights invalid day in year mode

### ISSUE THREAD

**Issue by ovk** [Alexays/Waybar#2254]
Clock module configuration:

```
    "clock": {
        "tooltip-format": "<tt>{calendar}</tt>",
        "calendar": {
            "mode": "month",
            "mode-mon-col": 3,
            "on-scroll": 1,
            "format": {
                "months":   "<span color='#d8dee9'><b>{}</b></span>",
                "days":     "<span><b>{}</b></span>",
                "weekdays": "<span color='#ebcb8b'><b>{}</b></span>",
                "today":    "<span color='#ebcb8b'><b><u>{}</u></b></span>"
            }
        },
        "actions":  {
            "on-click-right": "mode",
            "on-scroll-up": "shift_down",
            "on-scroll-down": "shift_up"
        }
    }

```

When tooltip with the calendar first appears, it looks correct and the "today" day highlighted correctly (doing this test on June 25):
![20230625_20h26m51s_grim](https://github.com/Alexays/Waybar/assets/693072/33e0f86d-3162-431a-9e19-3891c48c279e)

However, after first mouse wheel scroll the following appears, which is clearly incorrect:
![20230625_20h31m36s_grim](https://github.com/Alexays/Waybar/assets/693072/167b58a9-6c7f-4ec1-8a3d-b7130e841b05)

Surprisingly, the next scroll finally shows July (which is correct):
![20230625_20h31m40s_grim](https://github.com/Alexays/Waybar/assets/693072/77349044-242f-431e-ae78-4a6bb6dd8400)

The issue also appears in "year" mode in slightly different (and very confusing) way: if I switch mode after scrolling for one time , and then scroll back and forth in "year" mode, it will highlight invalid "today" date.

**Comment by LukashonakV** [comment]
Hi , @ovk . Is it reproducible or happened once?

**Comment by ovk** [comment]
It's fully reproducible on two different machines. I'm also wiling to troubleshoot it if needed.

**Comment by LukashonakV** [comment]
Actually, I'm on vacation.  So, I would be able to check this issue in 2 weeks.

**Comment by ovk** [comment]
@LukashonakV looks like #2340 does indeed fix the issue. Switching from 0.9.19 and main branch I can see this issue disappear.

**Comment by LukashonakV** [comment]
Great, @ovk. If there are no more issues so far, please close it. Thank you
