### ISSUE TITLE
hyprland/window module not showing information when separate-outputs set to true

### ISSUE THREAD

**Issue by smsteward** [Alexays/Waybar#2285]
Hi there! Been having an issue for the last few days regarding the `hyprland/window` module.

# Setup information
I have 3 monitors and use the same config for them all. I use the `hyprland/window` module with `"separate-outputs": true`, since I want each monitor's bar to show the title of the currently-focused (or most recently focused) window on that monitor, not the globally focused window on all 3 monitors.

This has not been an issue up until recently. I noticed that there was no text appearing, even when I had open windows on all monitors. I checked the output of `waybar -l debug` and noticed that it was complaining about a module error. I had the `waybar-hyprland-git` package from the AUR installed, which I removed in favor of `waybar-git`, and the module error went away, but not the issue.

After some tinkering, the culprit seems to be the `separate-outputs` option: the only way I can get the focused window title to appear is to use `"separate-outputs": false`, which breaks my intended use case, as changing this to false displays the currently focused window on all bars, not the actively-focused (or most recently focused) window on that specific monitor.
I haven't changed my config file in a long time, so it wasn't a config change I made to cause the breakage. Not sure if something changed upstream and I missed it in a changelog somewhere. Any help appreciated!

# Expected behavior
Waybar shows the title of the currently focused window (or the window that had focus before monitor focus shifted) on each monitor, using the `"separate-outputs": true` option, as has happened until recently.

# Current behavior
No text is displayed unless `separate-outputs` is set to false, which breaks my intended use case.

### Config file
[config.txt](https://github.com/Alexays/Waybar/files/11962284/config.txt)

**Comment by calvinchd** [comment]
Thanks for narrowing it down to the `separate-outputs` option. Been staying on an older build because of this issue and haven't had time to debug.
