### ISSUE TITLE
Add battery format for time remaining

### ISSUE THREAD

**Issue by Limero** [Alexays/Waybar#229]
It would be very useful if there was a format available for the battery module that would print the estimated remaining time.

I currently use the following in my custom bar script to get this information in the format **"5.3 hours"**:
`upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E time | awk '{print $4,$5}'`

**Comment by Alexays** [comment]
I think before implementing this I want to have #100

**Comment by lahwaacz** [comment]
upower does only [linear calculations](https://gitlab.freedesktop.org/upower/upower/blob/e06bfc6a120750ed629291ddcec02f62f178fab4/src/linux/up-device-supply.c#L803-819) which can be simply reproduced based on the ACPI data (see e.g. [i3status' implementation](https://github.com/i3/i3status/blob/a57cdc84e2f38ea99fd464d8b5b6446c769cc545/src/print_battery_info.c#L601-L609)). Anyway, there are _better_ tools which take the non-linear profiles into account, e.g. [ibam](http://ibam.sourceforge.net/).

**Comment by mreppen** [comment]
I implemented the same estimate as upower (before I saw this issue), currently displayed in the tooltip, and would be more than happy to make a PR.

I noticed that the new "Plugged" state is glitchy for me (before my changes). If I make a PR, I could have a look at correcting this as well, as I'm already familiar with the code.

**Comment by Alexays** [comment]
@mreppen I can't really test the `plugged` state since my battery doesn't support changing threshold..

**Comment by mreppen** [comment]
@Alexays That looks like it should fix it. I will test it later. Would you be interested in a PR for the battery estimate?

**Comment by Alexays** [comment]
@mreppen Sure, in the meantime, there will be two battery modules, one with upower and the other with inotify so you can add functionality :)

**Comment by Alexays** [comment]
Done in #331
