### ISSUE TITLE
[Error] hyprland/window is missing in waybar v0.9.19 - Arch linux

### ISSUE THREAD

**Issue by mrjerox** [Alexays/Waybar#2291]
Hello everyone, today my waybar warning no workspace with id 1 after update to v0.9.19 and missing hyprland/window @@. Before update everything is good with no problem :<<. I have rollback to v0.9.18 and it work again. I think it might a bug.

DE: Hyprland
OS: Arch Linux

**Comment by iynaix** [comment]
The hyprland/window issue was fixed in e4900db9a2e00e41f43e40d6a8d90c2466645c37,  which was unfortunately after the release of 0.9.19.

**Comment by khaneliman** [comment]
@Alexays or maybe you could just close it since its been resolved since that release
