### ISSUE TITLE
regression: pusleaudio/reverse-scrolling no longer works on 0.9.19

### ISSUE THREAD

**Issue by WhyNotHugo** [Alexays/Waybar#2298]
Prior to 0.9.19, when I held the mouse over the `pulseaudio` module, moving the mouse wheel towards me would increase the volume and moving it away from me would decrease the volume.

I found this counter-intuitive, so [I added `reverse-scrolling: 1` to my configuration](https://git.sr.ht/~whynothugo/dotfiles/commit/823562ebba5de18d4c21e006414d95b95cb756c2#home/.config/waybar/config.jsonc).

As of 0.9.19, this setting no longer has any effect. If it is absent, the behaviour is the same as above. If it is present, the behaviour is also the same as above.

**Comment by WhyNotHugo** [comment]
Huh, the wiki seems to indicate that `reverse-scrolling` has been renamed to `reverse-mouse-scrolling`, and `reverse-scrolling` now only applies no non-mice devices?

I really don't think that minor releases should redefine the meaning of configuration settings like this. Is there a CHANGELOG or NEWS or CHANGES file anywhere? I can't find any notes on what has changed.

**Comment by nekopsykose** [comment]
the shortlog in https://github.com/Alexays/Waybar/releases/tag/0.9.19 does mention that if you read every line, theoretically

**Comment by WhyNotHugo** [comment]
Oh, I hadn't seen that log. That's not an actual file in the repo, which explains why I couldn't find it. :sweat: 

So I guess this isn't a bug, it's just a breaking change in a minor release:

> Don't apply reverse scrolling to mice wheels by @korylprince in https://github.com/Alexays/Waybar/pull/2267

Wishlist: a short list of backwards incompatible changes for releases so we know what to expect.
