### ISSUE TITLE
Allow watching for non-present network interfaces

### ISSUE THREAD

**Issue by fmartingr** [Alexays/Waybar#230]
Launching waybar with a network module that includes a non-running network interface does not show the module.

I'm currently using it to monitor my VPN network interface `tun0`, but since that's not enabled when swaybar is launched, the module doesn't show up and is not shown when I connect the VPN.

Is there a way of considering `format-disconnected` (or add a custom value `format-not-present` or something like that) when the network interface is not present? 

`swaybar` output:
```
Disabling module "network#vpn", Can't found network interface
```

Module configuration:
``` javascript
{
    // ...
    "network#vpn": {
        "interface": "tun0",
        "format-wifi": "🔒",
        "format-ethernet": "🔒",
        "format-disconnected": "🔓",
        "on-click": ".dotfiles/bin/toggle-vpn"
    },
    // ...
}
```

**Comment by mithodin** [comment]
I've set up a custom script to do this in the meantime. I'm using vpnc which has the ability to run hooks on connect and disconnect, which I use to write "1" for connected or "0" for disconnected to a file.
Then, I use this script to display the status:
```
#!/bin/bash
statusfile="" #put your filename here
while true;
do
	if [ -f $statusfile ];
	then
		if [ $(cat $statusfile) == "1" ]; then
			echo "🔒"
		else
			echo "🔓"
		fi
		inotifywait -e modify --timeout 300 $statusfile &> /dev/null
	else
		sleep 30
	fi
done
```

**Comment by fmartingr** [comment]
@mithodin Yeah, there are alternative solutions like you posted, I just though it could be nice to have it supported from the appropriate module. Not sure how this will be prioritized butif any of you can help regarding what should I look for to fix this I will gladly open a PR, though I have no real experience with cpp I can try to do this myself.

**Comment by fmartingr** [comment]
@Alexays can confirm this is now fixed with the latest git version. Thanks a lot!
