### ISSUE TITLE
hyprland group windows labeled as hidden 

### ISSUE THREAD

**Issue by MightyPlaza** [Alexays/Waybar#2301]
Repro:
waybar >= introduced in https://github.com/Alexays/Waybar/commit/e2bfa5e019f62677aae786e5f202a87e06f7b3be
hyprland >= 0.26
use the "hyprland/window" module in waybar
create a group in hyprland with have at least 2 windows.

normal
![image](https://github.com/Alexays/Waybar/assets/123664421/0fff62b8-d4b0-4a3c-85a8-39457f01fc75)

grouped
![image](https://github.com/Alexays/Waybar/assets/123664421/09ed75ef-9dec-468d-bcb6-a6d681559f56)

**Comment by MightyPlaza** [comment]
Seems like happens whenever there is a hidden window in the current workspace, which sets the hidden_ var as true. Not sure what supposed to be the behaviour of hidden here

**Comment by gardenappl** [comment]
This was not intended, I left an explanation here: https://github.com/Alexays/Waybar/commit/cdece498c1e3849ea6e8ff7795ddce1ca8265803#commitcomment-121399218

I'll fix this shortly, in the meantime you can edit the default `style.css` to remove the #hidden rules. (I didn't know the default style even had such a rule)
