### ISSUE TITLE
Crash on Resume from Suspend

### ISSUE THREAD

**Issue by Riolku** [Alexays/Waybar#2304]
Ran into an issue today on sway + Arch (running waybar 0.9.19) where it crashed often on system resume.

# Steps

- Run waybar
- Disable the output, re-enable it, and suspend:
  `swaymsg output eDP-1 disable; swaymsg output eDP-1 enable; systemctl suspend`
- Resume the laptop

The issue seems to be related to some sort of mutex race condition. The errors vary, but all have to do with `wakeUp`.

I managed to reproduce with a config of:

```
{
    "ipc": true,
}
```

But the error is much more consistent with many modules. I failed to reproduce it with an empty config.

I built a debug binary from master and tested, applying the following diff to avoid catching the exception that kills waybar:

```
diff --git a/src/main.cpp b/src/main.cpp
index ff446ff..fe1a194 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -108,9 +108,6 @@ int main(int argc, char* argv[]) {
 
     delete client;
     return ret;
-  } catch (const std::exception& e) {
-    spdlog::error("{}", e.what());
-    return 1;
   } catch (const Glib::Exception& e) {
     spdlog::error("{}", static_cast<std::string>(e.what()));
     return 1;
```

This allowed me some intuition behind the error.

Here is a GDB log of reproducing the error with the minimal config above:

```
Temporary breakpoint 1 at 0xa0aff: file ../src/main.cpp, line 74.
Starting program: /home/keenan/Projects/Waybar/build/waybar 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffe1d8) at ../src/main.cpp:74
74	   auto client = waybar::Client::inst();
Continuing.
[New Thread 0x7ffff27b86c0 (LWP 62592)]
[New Thread 0x7ffff1bff6c0 (LWP 62593)]
[New Thread 0x7ffff13fe6c0 (LWP 62594)]
[New Thread 0x7ffff0bfd6c0 (LWP 62595)]
[New Thread 0x7fffe3fff6c0 (LWP 62596)]
[New Thread 0x7fffe37fe6c0 (LWP 62597)]
[Thread 0x7ffff0bfd6c0 (LWP 62595) exited]

Thread 1 "waybar" received signal SIGINT, Interrupt.
0x00007ffff6313c0f in poll () from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../lib64/libc.so.6
Quit
quit
Temporary breakpoint 1 at 0xa0aff: file ../src/main.cpp, line 74.
Starting program: /home/keenan/Projects/Waybar/build/waybar 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffe1d8) at ../src/main.cpp:74
74	   auto client = waybar::Client::inst();
Continuing.
[New Thread 0x7ffff27b86c0 (LWP 63152)]
[New Thread 0x7ffff1bff6c0 (LWP 63153)]
[New Thread 0x7ffff13fe6c0 (LWP 63154)]
[New Thread 0x7ffff0bfd6c0 (LWP 63155)]
[New Thread 0x7fffe3fff6c0 (LWP 63156)]
[New Thread 0x7fffdb7fe6c0 (LWP 63157)]
[New Thread 0x7fffe37fe6c0 (LWP 63158)]
[Thread 0x7fffe37fe6c0 (LWP 63158) exited]
[New Thread 0x7fffe37fe6c0 (LWP 63166)]
[Thread 0x7ffff0bfd6c0 (LWP 63155) exited]
[Thread 0x7fffe37fe6c0 (LWP 63166) exited]
[New Thread 0x7fffe37fe6c0 (LWP 63254)]

Thread 1 "waybar" received signal SIGABRT, Aborted.
0x00007ffff629f26c in ?? () from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../lib64/libc.so.6
warning: Memory read failed for corefile section, 4096 bytes at 0xffffffffff600000.
Saved corefile core.63146
quit
```

I've uploaded the [core file of this run](https://files.kgugeler.ca/waybar.core) to my own server because it's too large for github.

**Comment by helloworld1** [comment]
I think I have the same crash. After resume from suspend, waybar crashed

**Comment by Riolku** [comment]
Unsure if git bisect is finding a different segfault.

**Comment by mysfitt** [comment]
I believe that issue #2310 is a dup of this same bug. Please see my comment there as I did a backtrace to isolate the bug to a specific commit in the 0.9.19 release. The quick fix is to roll back to version 0.9.18.

**Comment by Alexays** [comment]
@xytovl Maybe you can check, seem related to your work

**Comment by xytovl** [comment]
With the given command
`swaymsg output eDP-1 disable; swaymsg output eDP-1 enable; systemctl suspend`
I could reproduce, I have made a commit in https://github.com/Alexays/Waybar/pull/2324 that fixes it for me. Can you verify this works for you?

**Comment by Riolku** [comment]
Seems to work.
