### ISSUE TITLE
font crash on waybar+hyprland+archlinux

### ISSUE THREAD

**Issue by Firestar-Reimu** [Alexays/Waybar#2309]
![20230713_11h44m21s_grim](https://github.com/Alexays/Waybar/assets/65082432/0e78bb63-39ee-4acd-971b-e34e5923fc74)

like this

I installed otf-font-awesome but some icons do not render

If I do not install otf-font-awesome, the middle 3 icons will not render too.

**Comment by khaneliman** [comment]
Is it just an outdated nerd font package?
