### ISSUE TITLE
sway module missing on openSUSE

### ISSUE THREAD

**Issue by linusboyle** [Alexays/Waybar#231]
Like #111, Seems this happen to openSUSE as well. I'm using sway 1.0 and waybar 0.4.0, and get the same message:

> Unknown module: sway/workspaces
Unknown module: sway/mode
Unknown module: sway/window

it's installed from X11:Wayland experimental repository, don't know if I need a recompilation.

**Comment by Alexays** [comment]
Sway modules are compiled if during waybar compilation the sway binary is found.

**Comment by linusboyle** [comment]
Thanks. But I'm afraid this behavior might confuse the packager, since waybar in Arch and openSUSE repository all have this problem.

**Comment by Alexays** [comment]
Ok so, i let the sway modules be compiled even if the binary is not found, that should resolve packager pb :)
6522a7acb4a87ecfa0f8e85a190b9743ba52a6f9
