### ISSUE TITLE
sway/workspace click warps cursor to focused window

### ISSUE THREAD

**Issue by phisch** [Alexays/Waybar#2315]
When clicking a workspace in the sway/workspaces module, it now warps the cursor to the focused window of that workspace.

I'm certain this is new behavior and I didn't find an option to disable this. I much prefer the old behavior of the cursor staying where it is.

Am I just missing the option to disable this?

**Comment by phisch** [comment]
This might be sway related, as it only happens sometimes. I'll report back when I figured out where this is coming from.

**Comment by txtsd** [comment]
Duplicate of #2290

**Comment by phisch** [comment]
Oh thanks, I must have missed that while searching! In that case I'm closing this!
