### ISSUE TITLE
mediaplayer.py fails when player starts

### ISSUE THREAD

**Issue by akhilman** [Alexays/Waybar#2319]
resources/custom_modules/mediaplayer.py fails as soon as I launch any media player.
```
(process:291946): playerctl-ERROR **: 16:22:49.549: could not get metadata: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/mpris/MediaPlayer2”
fish: Job 1, './mediaplayer.py' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

I believe the problem is caused by this line:
https://github.com/Alexays/Waybar/blob/7a5e7023341995302a57448ff05b12e7bcbb5e85/resources/custom_modules/mediaplayer.py#L68

So we could have a race condition. a player not yet registered dbus interface to call.

Removing this line fixes the issue and everything works just fine.

**Comment by zjeffer** [comment]
I made a lot of updates to that Python script in my dotfiles: https://github.com/zjeffer/dotfiles/blob/main/.config/hypr/apps/waybar/scripts/media-player.py

Maybe I should make a PR with my changes...

**Comment by zjeffer** [comment]
Removing that line means it won't show the update the module correctly when the new player appears, only when that player changes metadata the first time. 

If you for instance start spotify, it won't change metadata because it starts paused. I don't know why you get the crash, as I do the same in my script. Can you try my script and see if you get the same problem?

**Comment by akhilman** [comment]
> Can you try my script and see if you get the same problem?
Yes. I have the same fault with your script. 

I also found that this fault only relevant to the `celluloid` media player.
I also can add `sleep` call before pulling metadata and both scripts would not crash.

**Comment by zjeffer** [comment]
I can't seem to reproduce your issue with the celluloid media player (neither starting without a media fie and opening one in the app, nor opening celluloid using Open With on a media file). I do notice that celluloid does not seem to show report any metadata: playback status and title are not showing in the module...

**Comment by akhilman** [comment]
May be this is the version specific issue.
I'm running Debian Bookworm, celluloid 0.20-2+b1, libplayerctl2 2.4.1-2,  dbus 1.14.6-1.
Also I have very slow 10+ year old laptop.

In my case Celluloid is reporting status and patched script is showing correct title and play/pause status.

**Comment by akhilman** [comment]
I also can not reproduce this issue on machine with Manjaro. So this is perhaps Debian issue.
Closing.
