### ISSUE TITLE
Temperature module not working

### ISSUE THREAD

**Issue by JustMeErazem** [Alexays/Waybar#233]
Waybar version: 0.4.0
OS: Arch Linux (64-bit)
Desktop: Sway 1.0 (stable)

I tried adding the temperature module to my waybar:

```
 "temperature": {
    //"thermal-zone": 1,
    "hwmon-path": "/sys/class/hwmon/hwmon2/temp1_input",
    "critical-threshold": 80,
    "format-critical": "{temperatureC}°C ",
    "format": "{temperatureC}°C ",
    "interval": 2
  }
```

```
"modules-right": ["pulseaudio", "network", "cpu", "temperature", "memory", "backlight", "battery", "tray"],
```

But the temperature doesn't show up in my bar. I tried the default config suggested on github, but that doesn't work either.

The output of `cat /sys/class/hwmon/hwmon2/temp1_input` is "49000"
The same goes for the thermal zone temp suggested on the github modules page.

**Comment by Alexays** [comment]
Are there any logs related to this problem?

**Comment by JustMeErazem** [comment]
Which logs do you need/how do I capture them?

**Comment by Alexays** [comment]
Launch `waybar` from terminal and send me the output

**Comment by Bonnee** [comment]
I have the same issue on Arch. waybar returns `Unknown module: temperature`

**Comment by Alexays** [comment]
Oh ok, it's the person who has packaged waybar who doesn't enabled optional modules but I don't know who it is, otherwise you can use `waybar-git` from the aur or compile it by hand

**Comment by JustMeErazem** [comment]
Oh, I see, the Arch package is outdated (0.4.0). Thanks for the explanation.
