### ISSUE TITLE
Calendar shows wrong week numbers

### ISSUE THREAD

**Issue by J0nnyMak0** [Alexays/Waybar#2331]
I'm using the default calendar format  from `man waybar-clock` and I think the week numbers are wrong. Unless I'm missing something, the week number of the last week of the month should repeat at the first week of the following month (unless the first day of the month is a Sunday). However, currently the week number of the first and second weeks of the month repeat (if month doesn't start on a Sunday) and every month gets a new first week number.

```
      "calendar": {
                  "mode"          : "year",
                  "mode-mon-col"  : 3,
                  "weeks-pos"     : "right",
                  "on-scroll"     : 1,
                  "on-click-right": "mode",
                  "format": {
                              "months":     "<span color='#ffead3'><b>{}</b></span>",
                              "days":       "<span color='#ecc6d9'><b>{}</b></span>",
                              "weeks":      "<span color='#99ffdd'><b>W{}</b></span>",
                              "weekdays":   "<span color='#ffcc66'><b>{}</b></span>",
                              "today":      "<span color='#ff6699'><b><u>{}</u></b></span>"
                              }
            }
```

![waycal](https://github.com/Alexays/Waybar/assets/6559121/2ff7e996-b758-40e6-abf7-05e4b6fc7bfe)

**Comment by LukashonakV** [comment]
Hi @J0nnyMak0 , can you please share additional info:

1. `date '+%c'`
2. `echo $LANG`
3. `waybar --version`
4. `uname -a`
5. Please provide here the whole block for `clock` module

**Comment by J0nnyMak0** [comment]
> Hi @J0nnyMak0 , can you please share additional info:
> 
> 1. `date '+%c'`

Wed 19 Jul 2023 10:13:02 AM CDT

> 2. `echo $LANG`

en_US.UTF-8

> 3. `waybar --version`

Waybar v0.9.19-39-g1e2b9cb5 (branch 'master')

> 4. `uname -a`

Linux jonmhome 6.4.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Sat, 15 Jul 2023 19:25:49 +0000 x86_64 GNU/Linux

> 5. Please provide here the whole block for `clock` module

```
        "clock": {
                "timezone": "America/Chicago",
                "format": "{:%a}",
                "tooltip-format": "<tt><small>{calendar}</small></tt>",
                "calendar": {
                  "mode"          : "year",
                  "mode-mon-col"  : 3,
                  "weeks-pos"     : "right",
                  "on-scroll"     : 1,
                  "on-click-right": "mode",
                  "format": {
                              "months":     "<span color='#ffead3'><b>{}</b></span>",
                              "days":       "<span color='#ecc6d9'><b>{}</b></span>",
                              "weeks":      "<span color='#99ffdd'><b>W{}</b></span>",
                              "weekdays":   "<span color='#ffcc66'><b>{}</b></span>",
                              "today":      "<span color='#ff6699'><b><u>{}</u></b></span>"
                              }
               }
        }
```

**Comment by LukashonakV** [comment]
I reproduced the same issue in my machine. Need to take some time to clarify how your case should be look like. Now I suspect 3-rd party library is used by waybar calendar provides not ocrrect result. Utility  `date ` shows me correct results.... so . Will reply once I've got a clear vision on the case

**Comment by LukashonakV** [comment]
So... issue is found. But... needs to think now how to handle. It appears due to calendar for it's need uses date::sys_days typedef... which represents time point in UTC... Where there's another time point structure date::local_days which represents time point associated with timezone... I guess I'll provide new implementation.... Will notify once it's done.
Thank you

**Comment by ckudera** [comment]
I have the same problem as @randomn4me.

```
    "clock#date": {
        "format": "  {:%a. %d. %b. %Y}",
        "tooltip-format": "<tt>{calendar}</tt>",
        "locale": "en_GB.UTF-8",
        "calendar": {
            "mode": "month",
            "weeks-pos": "left",
            "on-scroll": 1,
            "format": {
                      "months": "<span color='#fff'><b>{}</b></span>",
                      "days": "<span color='#fff'><b>{}</b></span>",
                      "weeks": "<span color='#5c6370'><b>W{}</b></span>",
                      "weekdays": "<span color='#e06c75'><b>{}</b></span>",
                      "today": "<span color='#d74e42'><b>{}</b></span>"
            }
        },
        "actions":  {
            "on-scroll-up": "shift_down",
            "on-scroll-down": "shift_up"
        }
    },
```

```shell
~ > date '+%c'
Fri 19 Jan 2024 10:21:47 AM CET
~ > echo $LANG
en_US.UTF-8
~ > waybar --version
Waybar v0.9.24
~ > uname -a
Linux desktop 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64 GNU/Linux
```
