### ISSUE TITLE
[Feature request]: Adding dwl/window module

### ISSUE THREAD

**Issue by theshatterstone** [Alexays/Waybar#2332]
Hi. I've noticed that out of all the compositors that have their own tags modules (which now includes hyprland), the only one that does not have window module is DWL. I think it might be a good idea to change that, maybe using the same configuration style and css styling as other window title modules? Thanks.

**Comment by DreamMaoMao** [comment]
@theshatterstone 
This is not a problem with waybar but with your dwl, just add the foreign-toplevel protocol to dwl and you can use taskbar 
![image](https://github.com/Alexays/Waybar/assets/30348075/38df8d85-9167-4dce-8c1b-b74a097fa2bc)

**Comment by theshatterstone** [comment]
@DreamMaoMao I'm sorry, can you explain what you mean exactly? I'm talking about the window title not appearing, because there is no module for the window title, while it seems you're talking about the dwl/tags module, which does exist and I'm using it.

**Comment by DreamMaoMao** [comment]
> @DreamMaoMao I'm sorry, can you explain what you mean exactly? I'm talking about the window title not appearing, because there is no module for the window title, while it seems you're talking about the dwl/tags module, which does exist and I'm using it.

it means you can use `wlr/taskbar` moudle  instead of `dwl/tags` 

![image](https://github.com/Alexays/Waybar/assets/30348075/63bfbef9-cae6-4dec-b819-9d3fbb00f27e)

**Comment by DreamMaoMao** [comment]
file:///home/wrq/Images/8-230I0155054.jpg

**Comment by theshatterstone** [comment]
Seems to be fixed by #3005 ; Closing as completed
