### ISSUE TITLE
[feature] network module: distinction between disconnected and offline

### ISSUE THREAD

**Issue by X0rg** [Alexays/Waybar#234]
Hello,

If I enable airplane mode, then `format-disconnected` is used.
```
$ rfkill list all
0: phy0: Wireless LAN
    Soft blocked: yes
    Hard blocked: no
```
It would be great to have an other format for offline/airplane mode, or something similar to remember airplane mode is enabled.

**Comment by Alexays** [comment]
Already added with rfkill implementation
