### ISSUE TITLE
[module][cava] sensivity setting

### ISSUE THREAD

**Issue by pbosab** [Alexays/Waybar#2342]
arch, using latest git.

module always worked with the config from the waybar wiki.

since a couple of days (wasn't home before so couldn't check) the cava module always showed full bars (like full volume, before didn't).

I didn't edit anything, and manually enabling and disabling variables in the config found the problem. "sensivity": 100,

commenting it make cava works normally.

something changed? since i noticed this in the wiki:

`Manual sensitivity in %. It's recommended to be omitted when autosens = 1`

but the sample config:

```
"cava": {
//        "cava_config": "$XDG_CONFIG_HOME/cava/cava.conf",
        "framerate": 30,
        "autosens": 1,
        "sensitivity": 100,
        "bars": 14,
        "lower_cutoff_freq": 50,
        "higher_cutoff_freq": 10000,
        "method": "pulse",
        "source": "auto",
        "stereo": true,
        "reverse": false,
        "bar_delimiter": 0,
        "monstercat": false,
        "waves": false,
        "noise_reduction": 0.77,
        "input_delay": 2,
        "format-icons" : ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ],
        "actions": {
                   "on-click-right": "mode"
                   }
    },
```

thanks.

**Comment by LukashonakV** [comment]
Hi @pbosab . Please recheck wiki. It was an upstream issue. cava maintainer has fixed it, and this fix is included in the freshest Waybar. So, the behavior of the sensitivity is changed

**Comment by LukashonakV** [comment]
So @pbosab  I would say it's not an issue. If it's ok please close it. Thanks

**Comment by pbosab** [comment]
> So @pbosab I would say it's not an issue. If it's ok please close it. Thanks

sorry @LukashonakV didn't check cava github issues. closed.
