### ISSUE TITLE
Weird title behaivour since 0.9.20 (Hyprland)

### ISSUE THREAD

**Issue by alba4k** [Alexays/Waybar#2343]
![immagine](https://github.com/Alexays/Waybar/assets/84153269/bd4bba69-8562-4aa7-9c7e-6cbc184a6aa9)

It's supposed to look like this:
![immagine](https://github.com/Alexays/Waybar/assets/84153269/ce212440-2470-4aa6-83cd-dde20897177c)

This is the whole bar:
![immagine](https://github.com/Alexays/Waybar/assets/84153269/2cc4f3a1-b9bb-4429-8a41-63772da3b2c9)

It fixes itself after opening a window or changing workspace, the issue only appears when waybar first starts.

My configuration can be found [here](https://github.com/alba4k/.dotfiles/tree/master/.config/waybar)

**Comment by khaneliman** [comment]
@alba4k  is this resolved for you with the latest releases?

**Comment by alba4k** [comment]
will test as soon as I get home
