### ISSUE TITLE
doesnt work with fmt 10.

### ISSUE THREAD

**Issue by abenz1267** [Alexays/Waybar#2349]
```
waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory
```

Seems to need fmt 9. Arch just updated to fmt 10.

**Comment by manfred3000** [comment]
https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported

**Comment by edgerunnergit** [comment]
> ```
> waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory
> ```
> 
> Seems to need fmt 9. Arch just updated to fmt 10.

The problem resolves if you use just waybar instead of waybar-hyprland-git

**Comment by Mr-Pine** [comment]
If you are using waybar-hyprland-git you can just reinstall it and that should fix it
