### ISSUE TITLE
Error loading fmt library after update to version 10.

### ISSUE THREAD

**Issue by din-grogu** [Alexays/Waybar#2350]
`waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`

Downgrading to fmt version 9 solved the issue.

**Comment by Mr-Pine** [comment]
You are probably using waybar-hyprland-git. Reinstalling that package should fix your problem, if not, try the `waybar` package
See #2349

**Comment by din-grogu** [comment]
You are correct. Rebuilding the package solved the issue. Thanks a lot!
