### ISSUE TITLE
Strange Clock Format since today: 22:15:35,00019363

### ISSUE THREAD

**Issue by mrjncsk** [Alexays/Waybar#2351]
![Screenshot_2023-07-28-22-07-01_24578](https://github.com/Alexays/Waybar/assets/103059356/89467bf4-5849-41b8-af19-af82253e785f)

modules:
    "format": " {:%a %H:%M:%S}",

%S returns 35,00019363

**Comment by LukashonakV** [comment]
Is fixed in #2345

**Comment by mrjncsk** [comment]
thank you

**Comment by AtomicFS** [comment]
Temporary fix is to use `%OS` instead of `%S`.

**Comment by LukashonakV** [comment]
So because of this was fixed in #2345 @mrjncsk  please close the issue.
