### ISSUE TITLE
clock module: all spaces in tooltip-format are removed

### ISSUE THREAD

**Issue by kvarenzn** [Alexays/Waybar#2356]
here's a snippet of my configuration
```json5
"clock": {
    "tooltip-format": "<span size='12pt' font='Sarasa Mono SC'>{calendar}</span>",
    // ...
}
```
this "tooltip-format" will actually be formatted into

```xml
<spansize='12pt'font='SarasaMonoSC'>{calendar}</span>
```
and leads to a pango parse error

this bug was perhaps introduced by commit `4d9e0ea` five days ago, and the code that causes it is in lines 60 to 65 of `src/modules/clock.cpp`

**Comment by LukashonakV** [comment]
Thanks @kvarenzn , will check soon
