### ISSUE TITLE
Change the first day of the week on the `clock` module calendar?

### ISSUE THREAD

**Issue by PowerMan2206** [Alexays/Waybar#2359]
So right now Sunday is the default first day of the week. Is it possible to change this to Monday?

**Comment by apiraino** [comment]
This depends on your system locale. Check your env var `LC_TIME` by running the `locale` command. If it's something like `en_US.UTF-8` then you'll have Sunday as first day of the week.

Change your system locale to something that has Monday as first day of the week (like `en_GB.UTF-8`, `de_DE.UTF-8`, etc.) then restart Waybar.

**Comment by PowerMan2206** [comment]
Ah, got it. I was wondering why it didn't work, but then realized that I had to uncomment it from `/etc/locale.gen` and regenerate it. Works properly now, thanks!

**Comment by Jmvars** [comment]
> This depends on your system locale. Check your env var `LC_TIME` by running the `locale` command. If it's something like `en_US.UTF-8` then you'll have Sunday as first day of the week.
> 
> ~Change your system locale to something that has Monday as first day of the week (like `en_GB.UTF-8`, `de_DE.UTF-8`, etc.) then restart Waybar.~
> 
> EDIT: `waybar-clock` supports the config option `locale` (see [Wiki](https://github.com/Alexays/Waybar/wiki/Module:-Clock)) so just set a different locale in your Waybar config, then restart Waybar,

Thanks for this, had this same issue and luckily stumbled upon this post. My week now starts with Monday 👍
