### ISSUE TITLE
cross compiling fails (for arm)

### ISSUE THREAD

**Issue by DirectorX** [Alexays/Waybar#236]
cross compiling fails (for arm)

https://github.com/void-linux/void-packages/pull/10122

https://travis-ci.org/void-linux/void-packages/builds/509524073?utm_source=github_status&utm_medium=notification

**Comment by Alexays** [comment]
The weird thing is that it doesn't seem to compile with c++17 :/

**Comment by DirectorX** [comment]
https://github.com/void-linux/void-packages/pull/10122#issuecomment-475844900  @Alexays
