### ISSUE TITLE
Battery hotplug support

### ISSUE THREAD

**Issue by Gigadoc2** [Alexays/Waybar#237]
Currently, when starting waybar with a battery disconnected (mostly the case in multi-battery setups), waybar permanently disables the module for the "missing" battery.
Conversely, when a battery is disconnected while waybar is running, there is no special state to handle it and it is instead shown as empty (which is not as bad as the other case though).

It would be nice if waybar would - instead of disabling the module entirely - instead introduce a "disconnected" state. I'd say that it should be safe to assume a disconnected battery if the user explicitly specifies a name which is currently not present, as that is probably no accident.

**Comment by Gigadoc2** [comment]
So, I wrote a [custom module](https://git.revreso.de/gigadoc2/waybar-scripts/blob/master/battery.py) that does basically this.

It runs endlessly, getting its information from UPower over DBus.
Might be useful as inspiration for something proper, but I don't know if this style of "waiting for dbus" is applicable to waybar.

**Comment by Alexays** [comment]
Fixed with 8aee7492d494ce6ff6082791d64fa147751fdbf2
