### ISSUE TITLE
Removing "persistent_workspaces" from "hyprland/workspaces", module disappears

### ISSUE THREAD

**Issue by hekatonkheirex** [Alexays/Waybar#2374]
OS: Arch
Kernel: 6.4.7
Package: waybar-hyprland-git from AUR

Noticed that having persisten_workspaces, the styling doesn't work like polybar/Qtile bar (having occupied workspaces in another color)
![screenshot_20230801_220802](https://github.com/Alexays/Waybar/assets/63484218/0de61f60-9571-41e6-b6fe-15d28b501ea9)

So I decided to commenting out/removing out the persistent_worspaces, which results in "crashing" the module.
![screenshot_20230801_220811](https://github.com/Alexays/Waybar/assets/63484218/5ebceabd-aa91-4b97-af67-1df282d85e4b)

**Comment by Sohail-XD** [comment]
Have you checked hyprland wiki? 
https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#active-workspace-doesnt-show-up
Unrelated but your bar is so cool, can I get the dots :)

**Comment by zjeffer** [comment]
@hekatonkheirex I can't reproduce this. Can you share your config?

**Comment by hekatonkheirex** [comment]
> Have you checked hyprland wiki? https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#active-workspace-doesnt-show-up Unrelated but your bar is so cool, can I get the dots :)

This was a pull request from monday, so the Hyprland wiki is "outdated"

Here's the dots (the readme is outdated...) https://github.com/hekatonkheirex/dotfiles-hyprland

**Comment by hekatonkheirex** [comment]
> @hekatonkheirex I can't reproduce this. Can you share your config?
> 
> Also can you try if #2373 fixes this?

Here's the config file https://github.com/hekatonkheirex/dotfiles-hyprland/blob/main/.config/waybar/config.jsonc

And here's the css https://github.com/hekatonkheirex/dotfiles-hyprland/blob/main/.config/waybar/style.css

**Comment by hekatonkheirex** [comment]
I can confirm with the new PR now works well @zjeffer . Thank you!
