### ISSUE TITLE
Signals don't work in a custom module unless I restart waybar manually

### ISSUE THREAD

**Issue by Ozan8** [Alexays/Waybar#2376]
Hi! First of all, thank you for your work, I thoroughly enjoy using waybar. 

My issue is that my custom module. I use debian stable with sway, and waybar (v0.9.17). when I restart my computer, waybar doesnt follow the signals of one custom module. But when I restart the sway manually (control , shift , R), it starts receiving those signals and everything works. 

Steps I tried,
Changing the exec script (open to suggestions here)
changing the signal number (tried 8,9,7,3,11,69,91,23...)

MODULE: (show the number of task-spooled running and waiting tasks)
	"custom/queue": {
		"format": "⏳ {} ",
		"exec": "tsp | grep -e running -e queued | grep -c yt-dlp",
		"interval": "once",
		"signal": 9,
	},

SCRIPT:
.....
pkill -RTMIN+9 waybar

in my sway config, this is how waybar starts

bar { 
     swaybar_command waybar
}

I only saw one issue, where he solved it by changing the signal , saying that it doesnt work with number 8. but that didnt work for me.

**Comment by FabianUntermoser** [comment]
Having the same issue. Sending signals doesnt work.
