### ISSUE TITLE
%S format specifier in clock showing nanoseconds since 0.9.20

### ISSUE THREAD

**Issue by ti-mo** [Alexays/Waybar#2378]
Updated waybar to 0.9.20-2 (though I can't remember what I was running before) and getting some interesting clock output:

![image](https://github.com/Alexays/Waybar/assets/3214460/f58b4f02-957f-4b26-8485-fb0fe7a01bc5)

This is my format string: `"format": " {:%H:%M:%S   %d %b %Y}",`.

Is this expected? Any known workarounds?

**Comment by LukashonakV** [comment]
Fixed #2345. Users has already tested.

**Comment by ti-mo** [comment]
Woops, sorry for the noise! I looked for existing issues before opening, but I guess I didn't get the right search terms. :slightly_smiling_face: Closing.
