### ISSUE TITLE
Clock showing full time stamp

### ISSUE THREAD

**Issue by VictorGasnikov** [Alexays/Waybar#2391]
Since the last update, **%S** started showing seconds and nanoseconds at the same time.

![image](https://github.com/Alexays/Waybar/assets/46304693/ad26fb90-b62e-4119-ac5b-2e36bb2900f3)

My original config:

```
 "clock": {
     "tooltip-format": "<tt><small>{calendar}</small></tt>",
     "format-alt": "{:%Y-%m-%d}",
     "format": "{:%Y-%m-%d %H:%M:%S}",
     "interval": 1
 },
```

Which did not have this issue before the update.
Could you please fix it or tell me how to change the config to fix it?

**Comment by GalaxySnail** [comment]
It seems to be because something changed in fmt 10.0: https://github.com/fmtlib/fmt/releases/tag/10.0.0

> * Implemented formatting of subseconds. For example (godbolt):
>
> ``` cpp
> #include <fmt/chrono.h>
>
> int main() {
>   // prints 01.234567
>   fmt::print("{:%S}\n", std::chrono::microseconds(1234567));
> }
> ```
>
> Thanks patrickroocks (Patrick Roocks) phprus (Vladislav Shchapov), BRevzin (Barry Revzin).
>
> * Added precision support to `%S`. Thanks SappyJoy (Stepan Ponomaryov)

**Comment by LukashonakV** [comment]
See #2378, #2386 and please close the issue
