### ISSUE TITLE
MPRIS module takes too long to update metadata

### ISSUE THREAD

**Issue by Lassebq** [Alexays/Waybar#2392]
`mpris` module displays previous title for about 2-3 seconds before displaying the correct one while `playerctl metadata` displays the most up to date info.

**Comment by Prayag2** [comment]
Same

**Comment by skligys** [comment]
Could be because it refreshes every 5 seconds by default?  Try adding `"interval":1` in module's configuration for faster refresh.

**Comment by Lassebq** [comment]
Why is it interval based and not driven by dbus events?

**Comment by Lassebq** [comment]
I can listen for dbus events from a bash script, I think there is no excuse to not do it in cpp.

**Comment by EinderJam** [comment]
[This module](https://git.hrfee.pw/hrfee/waybar-mpris) look like it is using DBus (and is much more responsive in my experience), so it should be possible in an "official" module

**Comment by manfred3000** [comment]
IMHO the mpris module is at an "alpha" stage and too faulty to be made official yet...
The mpris controller posted in the wiki (custom modules) uses `playerctl`'s format capabilities (customizable to your liking) and does everything (I need and well):
```
"custom/media": {
    "format": "{icon}{}",
    "return-type": "json",
    "format-icons": {
        "Playing": " ",
        "Paused": " ",
    },
    "max-length":70,
    "exec": "playerctl -a metadata --format '{\"text\": \"{{playerName}}: {{artist}} - {{markup_escape(title)}}\", \"tooltip\": \"{{playerName}} : {{markup_escape(title)}}\", \"alt\": \"{{status}}\", \"class\": \"{{status}}\"}' -F",
    "on-click": "playerctl play-pause",
}
```

**Comment by Lassebq** [comment]
> [This module](https://git.hrfee.pw/hrfee/waybar-mpris) look like it is using DBus (and is much more responsive in my experience), so it should be possible in an "official" module

Thank you for bringing this to my attention
