### ISSUE TITLE
hyprland/workspaces: [error] argument not found

### ISSUE THREAD

**Issue by mutoroglin** [Alexays/Waybar#2394]
I use hyprland and waybar on Arch and so far I used the AUR `waybar-hyprland` package. I used that package for the persitent workspaces under hyprland. Since the recent version implemented native hyprland features, I switched to the package `waybar` but experience an error.
I get an error message on startup on my configuration of the `hyprland/workspaces` module:
```
[2023-08-12 10:14:49.958] [info] Using configuration file /home/lee/.config/waybar/config
[2023-08-12 10:14:49.958] [info] Using CSS file /home/lee/.config/waybar/style.css
[2023-08-12 10:14:49.969] [info] Hyprland IPC starting
[2023-08-12 10:14:50.023] [error] hyprland/workspaces: argument not found
```
This is my waybar confguration (excerpt):
```
    "modules-left": ["custom/power", "custom/gap", "hyprland/workspaces", "tray", "wlr/taskbar"],
    "modules-center": [],
    "modules-right": ["network", "backlight", "pulseaudio#mic", "pulseaudio", "battery", "clock"],

    // Modules configuration
    "hyprland/workspaces": {
        "format": "{name}"
    },
```
The error message disappears if I delete or comment out the line `"format": "{name}"`.
My waybar package/version: `waybar 0.9.20-2`
My hyprland version: `Tag: v0.27.2`

**Comment by zjeffer** [comment]
This is the same issue reported here: https://github.com/Alexays/Waybar/issues/2271#issuecomment-1673492668

Please use the latest git version if you want persistent workspaces, as described here: https://github.com/Alexays/Waybar/issues/2271#issuecomment-1675276403 (in your case, use `waybar-hyprland-git`)

**Comment by mutoroglin** [comment]
Thank you for the quick response, zjeffer!
I actually use the hyperland modification for `wlr/workspaces` already. I red about the new hyprland modules and was keen to try them out and check the functionality. I will use [#2271](https://github.com/Alexays/Waybar/issues/2271) to stay topical on further hyprland feature development.
