### ISSUE TITLE
hyprland/workspaces: waybar doesn't display active workspace correctly on startup

### ISSUE THREAD

**Issue by dalton-elmo** [Alexays/Waybar#2395]
I have two monitors. After login waybar shows active workspace on the left one, but actually focus is on the right.

I use `Waybar v0.9.20-64-gb084bf72 (branch 'master')`

`hyprctl monitors` output:
```
Monitor HDMI-A-1 (ID 0):
	1920x1080@60.000000 at 1920x0
	description: BNQ BenQ GW2406Z G5J0146801Q (HDMI-A-1)
	make: BNQ
	model: BenQ GW2406Z
	serial: G5J0146801Q
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 56 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 1):
	1920x1080@60.000000 at 0x0
	description: BNQ BenQ GW2406Z D9H0166901Q (DP-2)
	make: BNQ
	model: BenQ GW2406Z
	serial: D9H0166901Q
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 56 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
```

`DP-2` is on the left, `HDMI-A-1` is on the right.

By default Hyprland places the monitors incorrectly and I changed their positions in the config:
```
monitor=DP-2, preferred, 0x0, 1
monitor=HDMI-A-1, preferred, 1920x0, 1
```

After changing focus the problem disapears.

**Comment by zjeffer** [comment]
Strange, I don't have this problem. Do you set the monitor config *after* loading Waybar or before?

**Comment by dalton-elmo** [comment]
I tried load before and after monitor config however waybar still shows focus on the left one, but now I noticed one wierd thing: on startup second cursor appears in the upper left corner and disapears after moving actual cursor (I don't know if it's normal for Hyprland)

**Comment by dalton-elmo** [comment]
Sorry for misleading in the title, but I actually used `wlr/workspaces` instead.

I just didn't know that Hyprland has its own modules until now, and used wlr one because somebody else used it in their config and hyprland modules isn't mentioned in waybar man page. 

`hyprland/workspaces` doesn't have this problem. Anyway thanks.

**Comment by dalton-elmo** [comment]
Same issue with ``. For now I'm using `Waybar v0.9.22-24-g8eb614f6 (branch 'master')`.
