### ISSUE TITLE
Error with the wlr/workspaces module in Fedora

### ISSUE THREAD

**Issue by lxbx44** [Alexays/Waybar#2405]
When i launch waybar I get this warning:
```
--> waybar
[2023-08-14 23:37:05.893] [info] Using configuration file /home/lxbx/.config/waybar/config.jsonc
[2023-08-14 23:37:05.893] [info] Including resource file: ~/.config/waybar/modules.jsonc
[2023-08-14 23:37:05.894] [info] Including resource file: ~/.config/waybar/modules.jsonc
[2023-08-14 23:37:05.895] [info] Using CSS file /home/lxbx/.config/waybar/style.css
[2023-08-14 23:37:05.911] [warning] module wlr/workspaces: Unknown module: wlr/workspaces
[2023-08-14 23:37:05.913] [info] Hyprland IPC starting

(waybar:37468): GLib-GObject-CRITICAL **: 23:37:05.982: ../gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '73'

(waybar:37468): GLib-GObject-CRITICAL **: 23:37:05.982: ../gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '72'
[2023-08-14 23:37:05.983] [warning] module wrl/workspaces: Unknown module: wrl/workspaces
[2023-08-14 23:37:06.249] [info] Bar configured (width: 1346, height: 35) for output: eDP-1
[2023-08-14 23:37:06.249] [info] Bar configured (width: 2540, height: 35) for output: HDMI-A-1
```

The bar works perfectly fine except the workspaces section that doesnt show up

im using:
Fedora
hyprland wm

**Comment by Ogglord** [comment]
Afaik wlr/workspaces is still an experimental feature. You need to compile waybar yourself unless Fedora repos has a waybar-hyprland package. 

See: https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#compiling-manually

**Comment by zjeffer** [comment]
> module wrl/workspaces: Unknown module: wrl/workspaces

@lxbx44  You misspelled `wlr`. Fix the typo and the module should work.

**Comment by khaneliman** [comment]
@lxbx44 Did you resolve this already? Just checking if we can close this issue. Also wlr/workspaces is no longer supported in Hyprland latest build.

**Comment by lxbx44** [comment]
> @lxbx44 Did you resolve this already? Just checking if we can close this issue. Also wlr/workspaces is no longer supported in Hyprland latest build. 

Maybe that's the problem. I haven't solved it tho. You vN close it anyway, thanks

**Comment by zjeffer** [comment]
@lxbx44 Was the problem not the misspelling of `wlr`? 

But as @khaneliman says, wlr/workspaces is not supported anymore anyway, so you should switch over to hyprland/workspaces.

> You vN close it anyway, thanks

We can't close the issue because we are not maintainers, but you can, because you opened the issue ;)

**Comment by lxbx44** [comment]
> @lxbx44 Was the problem not the misspelling of `wlr`? 
> 
> But as @khaneliman says, wlr/workspaces is not supported anymore anyway, so you should switch over to hyprland/workspaces.
> 
> > You vN close it anyway, thanks
> 
> We can't close the issue because we are not maintainers, but you can, because you opened the issue ;)

Ohhh okay okay, that wasn't the issue :( i have tried using hyprland/workspaces and still didn't work. I simply use waybar without workspaces info. Its not a big deal :3 thanks tho
