### ISSUE TITLE
Can't build/install Waybar with fmt version 10

### ISSUE THREAD

**Issue by janemba** [Alexays/Waybar#2422]
Hello,

I have an issue building/installing `Waybar` from `git` . At `ninja -C build install` I have the following error:

[compile.log](https://github.com/Alexays/Waybar/files/12385148/compile.log)

I uploaded a file to avoid too long post.

**Comment by zjeffer** [comment]
Duplicate of #2415? Although your error log seems a lot longer.

**Comment by janemba** [comment]
It seems related and also I installed spdlog from git too.

**Comment by janemba** [comment]
So I more or less did what you did in #2415 and it compile now.
