### ISSUE TITLE
hyprland/language add on-click config options

### ISSUE THREAD

**Issue by waddyhussain** [Alexays/Waybar#2425]
Add support for on-click events (on-scroll events would be helpful too) to support customisations such as switching between different keyboard layouts

**Comment by TAforever** [comment]
Hi, this functionality has already been added.
Here is an example of my configuration

```json
    "hyprland/language": {
        "format-en": "us ",
        "format-ru": "ru ",
        "keyboard-name": "gaming-keyboard",
        "on-click": "hyprctl switchxkblayout gaming-keyboard next"
   },
```

**Comment by waddyhussain** [comment]
Thanks, marking as closed
