### ISSUE TITLE
Specify which config file to run?

### ISSUE THREAD

**Issue by kflak** [Alexays/Waybar#2426]
Is it possible to specify which config file to run? The use-case is the ability to specify different configs for sway and hyprland. Alternatively, is it possible to detect which of the WMs is running and set modules based on that?

**Comment by zjeffer** [comment]
`waybar --config <path-to-config.json> --style <path-to-style.css>`

Sway and hyprland have different ways of executing startup programs, so you can just specify which waybar you want to start in their respective config files.

**Comment by kflak** [comment]
Fantastic! Just what I was looking for! I can't find any mention of this in the documentation, maybe I just overlooked it? In any way, I think it would be  a good piece of information to make easily discoverable :-)
