### ISSUE TITLE
clock %S format specifier displays floating point

### ISSUE THREAD

**Issue by Panadero1** [Alexays/Waybar#2427]
I updated and now my clock's seconds are displaying in floating point representation instead of integer. See attached photo
![image](https://github.com/Alexays/Waybar/assets/23297689/4a1d9170-302b-4a6a-8f81-42e3079eedfa)

My clock configuration is:

```
clock": {
"interval": 1,
"format": "{:%Y-%m-%d %H:%M:%S}",
} 
```

This only happened recently as a result of updating

Probably a result of #2409

**Comment by jpalus** [comment]
> I updated and now my clock's seconds are displaying in floating point representation instead of integer. 

Works fine for me.

> Probably a result of https://github.com/Alexays/Waybar/pull/2409

What makes you think that exactly?

Are you using distribution which falls back to simple clock? By looking at recent commits it looks like dae7794bdfda81460beb26ad90a3beec2ab18bf2 might need to applied to simple clock as well?

**Comment by jpalus** [comment]
> By looking at recent commits it looks like https://github.com/Alexays/Waybar/commit/dae7794bdfda81460beb26ad90a3beec2ab18bf2 might need to applied to simple clock as well?

Actually not, it appears that `simpleclock.cpp` converts time to `time_t` which is expressed in seconds:
https://github.com/Alexays/Waybar/blob/b7a527b122831235fb36f661d415f5f3ed378d92/src/modules/simpleclock.cpp#L19-L22

Can't really help then. Clock rounds to full seconds so `%S` shouldn't show any fractional part while simple clock converts to `time_t`.

**Comment by Panadero1** [comment]
so why do you think this is displaying fractional? I didn't change my config through the update

**Comment by kaedwen** [comment]
Same on my side, also have just this simple config and get a floating point representation with `%S`

```
"clock": {
    "format-alt": "{:%Y-%m-%d}",
    "format": "{:%H:%M:%S}",
    "interval": 1
},
```

![image](https://github.com/Alexays/Waybar/assets/3512352/425200b7-f84e-43e7-ba49-ddf5931fc7ed)

**Comment by kaedwen** [comment]
ah just built the master branch and there the problem does not exist anymore

**Comment by manio** [comment]
Hi, only for reference:
Arch upgrade: ```upgraded waybar (0.9.20-2 -> 0.9.22-1)```
Fixes this problem for me as well :)

**Comment by jpalus** [comment]
Thanks @manio. That's the first comment from someone affected that has an actual merit.

The reason for fractional seconds, in this case, was distribution packaging issue caused by cherry pick of e9b29613 in https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/commit/76fca700672f93e580582b541a0f45b312322b69 while skipping dae7794.
