### ISSUE TITLE
hyprland/workspaces messed up after waking display

### ISSUE THREAD

**Issue by khaneliman** [Alexays/Waybar#2428]
I recently switched from the hyprland patch on wlr/workspaces to hyprland/workspaces and am noticing weird behavior on waking up monitor / unlocking after swayidle/swaylock. Not sure if it has to do with having multiple monitors or something... but I see a duplicated icon for a workspace and an icon for the special workspace. When I restart the waybar service it goes back to normal. 

![image](https://github.com/Alexays/Waybar/assets/1778670/f0ca14d1-5d6f-44d9-8966-e1964fde4009)
![image](https://github.com/Alexays/Waybar/assets/1778670/00fddaff-6db4-4c81-b0cf-397e66fb02dd)

```json
{
  "hyprland/workspaces": {
    "all-outputs": false,
    "format": "{icon}",
    "format-icons": {
      "1": "",
      "2": "",
      "3": "",
      "4": "",
      "5": "",
      "6": "",
      "7": "",
      "8": "󰢹",
      "urgent": "",
      "default": ""
    }
  },
  "hyprland/window": {
    "format": "{}",
    "separate-outputs": true
  },
  "hyprland/submap": {
    "format": "✌️ {}",
    "max-length": 8,
    "tooltip": false
  }
}
```

```json
[
  {
    "include": [
      "/nix/store/v5n9j2b1prw6bkxx8k8kmbhg4813nix4-default-modules.jsonc",
      "/nix/store/j7g4f9q2r1swgry51hdp3nhna95m2amj-default-modules.jsonc"
    ],
    "layer": "top",
    "margin-left": 20,
    "margin-right": 20,
    "margin-top": 10,
    "modules-center": [],
    "modules-left": [
      "custom/wlogout",
      "hyprland/workspaces",
      "custom/separator-left",
      "hyprland/window"
    ],
    "modules-right": [
      "tray",
      "custom/separator-right",
      "group/stats",
      "custom/separator-right",
      "group/notifications",
      "hyprland/submap",
      "custom/weather",
      "clock"
    ],
    "output": "DP-1",
    "position": "top"
  },
  {
    "include": [
      "/nix/store/v5n9j2b1prw6bkxx8k8kmbhg4813nix4-default-modules.jsonc",
      "/nix/store/j7g4f9q2r1swgry51hdp3nhna95m2amj-default-modules.jsonc"
    ],
    "layer": "top",
    "margin-left": 20,
    "margin-right": 20,
    "margin-top": 10,
    "modules-center": [],
    "modules-left": [
      "custom/wlogout",
      "hyprland/workspaces",
      "custom/separator-left",
      "hyprland/window"
    ],
    "modules-right": [
      "custom/weather",
      "clock"
    ],
    "output": "DP-3",
    "position": "top"
  }
]
```

**Comment by zjeffer** [comment]
* Can you provide the Waybar version you're using?
* Can you try to reproduce the error while running waybar on one monitor, and share the logs? Make sure you enable debug logging by launching waybar with `-l debug`

**Comment by khaneliman** [comment]
> * Can you provide the Waybar version you're using?
> 
> * Can you try to reproduce the error while running waybar on one monitor, and share the logs? Make sure you enable debug logging by launching waybar with `-l debug`

It's the latest release 9.22 that's in nixpkgs. I'll try adding an overlay to enable debug logging and see what I can find.

**Comment by khaneliman** [comment]
haven't seen it after last few commits.. closing for now
