### ISSUE TITLE
Difference in behaviour of persistent icon between wlr/workspaces and hyprland/workspaces

### ISSUE THREAD

**Issue by t-veor** [Alexays/Waybar#2430]
In wlr/workspaces, the "persistent" icon is only set if the workspace is not empty: https://github.com/Alexays/Waybar/blob/b7a527b122831235fb36f661d415f5f3ed378d92/src/modules/wlr/workspace_manager.cpp#L498-L503
But in hyprland/workspaces, the "persistent" icon is set if the workspace is a persistent one: https://github.com/Alexays/Waybar/blob/b7a527b122831235fb36f661d415f5f3ed378d92/src/modules/hyprland/workspaces.cpp#L390-L395

The behavior in wlr/workspaces allowed me to have this rule:
```
"format-icons": {
    "active": "",
    "default": "",
    "persistent": "",
},
```
where the active workspace gets the active icon, inactive workspaces that contain windows get the default icon (since they don't count as persistent, as they have a window in them), and inactive workspaces that don't contain windows get the persistent icon.

When I switched to using hyprland/workspaces, all inactive workspaces now use the persistent icon regardless of whether they have a window in them.

I like to have all my workspaces visible, and also an indication that a workspace contains a window... and I do think this way of doing it is pretty hacky, but I can't think of any other way I'm supposed to do this. It also seems this behaviour is intended considering on hyprland/workspaces, persistent workspaces do have the `.persistent` class taken away when they contain a window: https://github.com/Alexays/Waybar/blob/b7a527b122831235fb36f661d415f5f3ed378d92/src/modules/hyprland/workspaces.cpp#L325

so I guess this means I could technically work around it with some weird `.persistent::before` CSS rule, but it would be nice to use the `format-icon` config object to format the icons.

**Comment by zjeffer** [comment]
What if I added a way to add "empty" icons? If a persistent workspace is empty, it would get the "empty" icon, and if it has isn't, it would get the "persistent" icon. 

I should then probably add an "empty" css class, and change the "persistent" class to match the "persisten" icon.

What do you think?

**Comment by t-veor** [comment]
Yes, that's would be perfectly fine. In fact if it's documented it would be way better as then people don't have to hunt around for a way to do this.
