### ISSUE TITLE
persistent_workspaces should be persistent-workspaces

### ISSUE THREAD

**Issue by PucklaJ** [Alexays/Waybar#2443]
This key of the different `workspaces` modules should be named `persistent-workspaces` with a hyphen instead on an underscore to make it consistent with all other keys. This inconsistency actually led to an issue as I intuitively typed `persistent-workspaces`. I was wondering what I did wrong until I realized that I used a hyphen instead of an underscore. Therefore the naming should be consistent and use a hyphen instead of an underscore.

**Comment by khaneliman** [comment]
This is something that threw me off, as well. I think it's worth updating to maintain consistency... @zjeffer  thoughts?

**Comment by zjeffer** [comment]
I've been thinking about this as well, but I feel we should make both options possible, so no existing configs break, and maybe log a warning saying the old name is deprecated. After a while we can then remove the deprecated style.

**Comment by khaneliman** [comment]
> I've been thinking about this as well, but I feel we should make both options possible, so no existing configs break, and maybe log a warning saying the old name is deprecated. After a while we can then remove the deprecated style.

Guess that's one approach. :P I was taking the break -git people's now and publish in release notes for others. But, we can be more graceful too. lol
