### ISSUE TITLE
Symbol Lookup error

### ISSUE THREAD

**Issue by KSaiAkshit** [Alexays/Waybar#2448]
It was working fine till yesterday but doesn't seem to work today for some reason. I tried uninstalling and reinstalling it and building it from source. None of the other versions (extra/waybar, aur/waybar-hyprland) seem to work as well. I get this error when trying to spawn it from a terminal:

`waybar: symbol lookup error: waybar: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_`

OS: Arch
Waybar Version: 0.9.22-1

**Comment by KSaiAkshit** [comment]
Turns out it was an error with spdlog-git. Updating it fixed it.

**Comment by 4Gettt25** [comment]
I am currently having the same issue with the same error but updating spdlog-git doesnt fix it for me
Output of waybar:
waybar: symbol lookup error: waybar: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_

**Comment by loqusion** [comment]
@4Gettt25 I switched back to `spdlog` instead of `spdlog-git` and that seems to have fixed it for me.

**Comment by 4Gettt25** [comment]
Yes this also fixed it for me

**Comment by zebogan** [comment]
fixed for me as well
