### ISSUE TITLE
How can I remove waybar if I've installed manually?

### ISSUE THREAD

**Issue by mrp4sten** [Alexays/Waybar#2454]
I've allready download this respository and compile from zero to install waybar, now How can I uninstall it?

**Comment by sprngLf** [comment]
remove using your package manager  
in arch: `pacman -R waybar`  

remove auto init commands that calls waybar
then remove the config files, usually in `.config/waybar`

**Comment by tchofy** [comment]
Should be similar to the install command, so, while inside the Waybar folder from the cloned repo, ``ninja -C build uninstall``.

**Comment by mrp4sten** [comment]
Thanks but when I execute the command `ninja -C build uninstall`, in the output I can see the message info:

```shell
Uninstall finished.

Deleted: 0
Failded: 63
```

So I dont know if my solution was the correct way, I've already remove the files `/usr/local/bin/waybar` and the service `/usr/lib/systemd/user/waybar.service`

**Comment by tchofy** [comment]
Considering the ``Failded: 63``, either there's some leftover files and it couldn't be removed due to lack of privileges (will need sudo, so `sudo ninja -C build uninstall), or they've already been deleted.

**Comment by mrp4sten** [comment]
Thanks @tchofy :heart_decoration:
