### ISSUE TITLE
workspaces are not showing in Hyprland

### ISSUE THREAD

**Issue by bknightInfo** [Alexays/Waybar#2461]
Hi,

Since the last update to Waybar today. Workspaces seemed to be broken as they wont display.

![image](https://github.com/Alexays/Waybar/assets/95592623/44fe5668-6b87-49b3-88b7-499948aa6311)

my configuration
config
    "modules-left": [
        "custom/launcher",
        "wlr/workspaces",
        "cpu", 
        "memory"
        ],

Module:
   "wlr/workspaces": {
        "all-outputs": false,
        "sort-by-number": true,
        "on-click": "activate",
        "on-scroll-up": "hyprctl dispatch workspace e+1",
        "on-scroll-down": "hyprctl dispatch workspace e-1",
        "format": "{icon}",
        "format-icons": {
            "urgent": "",
            "active": "",
            "default": ""
        },
        "persistent_workspaces": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "5": ""
        }
    },

**Comment by khaneliman** [comment]
wlr/workspaces isn't supported in latest Hyprland. Need to use hyprland/workspaces.
