### ISSUE TITLE
wlr/workspaces suddenly empty (used with Hyprland)

### ISSUE THREAD

**Issue by ppenguin** [Alexays/Waybar#2463]
Since my latest update suddenly the workspace indicator shows always empty.
I didn't change the config, it is like before (nix format):
```nix
        modules-left = [
          "custom/menu"
          "wlr/workspaces"
          "custom/currentplayer"
          "custom/player"
        ];
    ...
        "wlr/workspaces" = {
             on-click = "activate";
        };
```

`hyprland/window` is working as before, so IPC is working...

Nominal versions are `waybar-0.9.22` and `Hyprland-0.23.1` but I tried (using overrides/overlays)  with different recent versions  of `waybar` and `Hyprland` as well (including current master), but it doesn't make any difference.

There's nothing suspicious in the logs and `hyprctl workspaces` shows an output as expected.

Any ideas how to debug this or what it could be?

**Comment by ppenguin** [comment]
This appears to be a (partial?) duplicate of #2462 so closing this...

**Comment by bknightInfo** [comment]
For hyprland wlr wont work now.
in your config change "wlr/workspaces" to "hyprland/workspaces"  this should fix your issues

**Comment by ppenguin** [comment]
> For hyprland wlr won't work now. in your config change "wlr/workspaces" to "hyprland/workspaces" this should fix your issues

Thanks, guess my closing and reference to the duplicate crossed your reply :wink: Can confirm that it works with `hyprland/workspaces` :+1:
