### ISSUE TITLE
persistent_workspaces doesn't seem to work anymore

### ISSUE THREAD

**Issue by bknightInfo** [Alexays/Waybar#2464]
Has anyone else noticed that persistent_workspaces doesn't seem to work anymore?

My workspace module:
    "hyprland/workspaces": {
        "all-outputs": false,
        "sort-by-number": true,
        "on-click": "activate",
        "on-scroll-up": "hyprctl dispatch workspace e+1",
        "on-scroll-down": "hyprctl dispatch workspace e-1",
        "format": "{icon}",
        "format-icons": {
            "urgent": "",
            "active": "",
            "default": ""
        },
        "persistent_workspaces": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "5": ""
        }
    },

**Comment by khaneliman** [comment]
That doesn't look like a supported config. The persistent workspaces is supposed to be a mapping of which workspaces are persistent on which outputs. 

https://github.com/Alexays/Waybar/wiki/Module:-Hyprland#workspaces

**Comment by khaneliman** [comment]
What version of waybar are you using? That also doesn't look like  a supported configuration? It's supposed to be workspace to output matching rules as defined https://github.com/Alexays/Waybar/wiki/Module:-Hyprland#workspaces

**Comment by bknightInfo** [comment]
Running  v0.9.22
It was working correctly until the update of yesterday

**Comment by khaneliman** [comment]
> Running v0.9.22 It was working correctly until the update of yesterday

v0.9.22 is 3 weeks old, if you're running off master what commit?

**Comment by bknightInfo** [comment]
> > Running v0.9.22 It was working correctly until the update of yesterday
> 
> v0.9.22 is 3 weeks old, if you're running off master what commit? Regardless, what are you expecting to happen with that persistent workspace config laid out like that? It looks like format-icons listed in the persistent_workspaces section.
> 
> These are the example configurations in the wiki ![image](https://user-images.githubusercontent.com/1778670/265886478-cbb97223-baa1-4629-938d-5ce6d6221421.png)

Thanks for the help.
Installed waybar-hyprland-git from the aur which solved the problem
