### ISSUE TITLE
Styling button of visible yet unfocused workspace on secondary monitor in Hyprland

### ISSUE THREAD

**Issue by tobsz** [Alexays/Waybar#2465]
Maybe I'm just blind, but is it still not possible to separately style the button of the active but unfocused workspace when using using Waybar with Hyprland. I mean doing `hyprctl monitors -j` yields something along:

```
[
  {
    "id": 0,
    "name": "eDP-1",
    [...]
    "activeWorkspace": {
      "id": 1,
      "name": "1"
    },
    [...]
    "focused": true,
    [...]
  },
  {
    "id": 1,
    "name": "HDMI-A-1",
    [...]
    "activeWorkspace": {
      "id": 3,
      "name": "3"
    },
    [...]
    "focused": false,
    [...]
  }
]
```
So, the active workspace for every monitor can be queried and is known and this would make it possible to style the active yet unfocused workspace on the non-focused monitor distinguishably, which would make correctly jumping between workspaces on different monitors much easier.

**Comment by khaneliman** [comment]
It does look like it's currently setup to expect a single active workspace. I will try and see if I can change it to be more like the other class decorations that allow for multiple.

**Comment by tobsz** [comment]
That would be a great quality of life improvement to be able to distinguish the visible workspace on the other monitor(s).

**Comment by zjeffer** [comment]
Can you test with this PR #2408 ? You should be able to use the "visible" icon and css class to style active workspaces on other monitors.

**Comment by khaneliman** [comment]
> Can you test with this PR #2408 ? You should be able to use the "visible" icon and css class to style active workspaces on other monitors.

Ah, yeah... that PR looks like it's trying to handle the same thing in a slightly different way of what I was thinking. Right now we're treating the focused workspace as active instead of marking all active workspaces as active.
