### ISSUE TITLE
hyprland/workspaces active CSS not applying to active workspace

### ISSUE THREAD

**Issue by smsteward** [Alexays/Waybar#2469]
## Issue

Hey everyone.

I really appreciate the work that y'all have done with the `hyprland` module. I've been tracking it for a while, and it's come a long way in a little time. Great work!

After the last commit, I've noticed that the `#workspaces button.active` CSS decorator is not working for me when paired with `persistent_workspaces` after the addition of `#workspaces button.visible`.

Here's my workflow:
* I have 7 persistent workspaces (1-7) shown on each of my three monitors (persistent workspaces colored blue via `#workspaces button.persistent`)
* The workspaces that are currently visible on each monitor are colored orange (via the new `#workspaces button.visible` CSS)
* What I want is the currently active workspace to be colored green

It's the last part that is not happening; the active workspace is not currently being colored according to the CSS I have set. I've tried all combinations of `all-outputs` and `active-only` and the end result is the same. The monitors that are visible on each workspace are correctly being colored orange (or blue if I remove the `#workspaces button.visible from CSS), but the active workspace is not being colored green.

My config file and CSS are attached. I'm not sure if there is a CSS priority and that active is the last on the list or not triggering properly, or if I'm just missing something obvious. I'm a SQL developer, so after spending all day looking at code for work, my brain is probably fried and I might be missing something.

Again, thanks for all the awesome work on this module. Y'all are great!
[config.txt](https://github.com/Alexays/Waybar/files/12528834/config.txt)
[style.txt](https://github.com/Alexays/Waybar/files/12528836/style.txt)

## System
* Arch Linux (kernel 6.4.12)
* Waybar v0.9.22-39-g80de22a1 (branch 'master') (using `waybar-git` from AUR)

**Comment by khaneliman** [comment]
The way the CSS is evaluated you need to order it in order of importance. I just updated my config to take advantage of the different classes. 

https://github.com/khaneliman/khanelinix/blob/main/modules/home/desktop/addons/waybar/style.css

**Comment by smsteward** [comment]
Yep, that did it alright...I need some more coffee. Curse my need to alphabetize everything :D

Thank you so much!
