### ISSUE TITLE
hyprland/workspaces ugent icon

### ISSUE THREAD

**Issue by SumitKhatri712** [Alexays/Waybar#2476]
Hi!
Since the change to `hyprland/workspaces` . I noticed that under `format-icons{}` , the urgent key value doesn't seem to work/exist.
There's no mention of it in the wiki. Nor does changing the value do anything.
#workspaces button.urgent in styles.css still seems to be working

**Comment by zjeffer** [comment]
Oops, looks like we forgot about the icon. Should be fixed in that PR I just made.
