### ISSUE TITLE
Group module: styling

### ISSUE THREAD

**Issue by QuentinDutot** [Alexays/Waybar#2478]
Looking for a way to write css for groups, but it seems like we can't target groups in the styles.

- `custom/<name>` is`#custom-<name>`
- `group/<name>` is `?`

**Comment by Alexays** [comment]
It'll be the name as class :)

**Comment by AdsonCicilioti** [comment]
@Alexays I don't understand... I've try style the class `.group-hardware` referencing the `"group/hardware"` module but nothing is affected.

Could you give us an example?

**Comment by gitacrobat** [comment]
This worked for me:
config: `group/calendar`
style.css: `#calendar`
