### ISSUE TITLE
hyprland/workspaces: Auto rename lost active information

### ISSUE THREAD

**Issue by foonathan** [Alexays/Waybar#2481]
I'm on the latest git commit of both waybar and Hyprland.

When I rename the active workspace, waybar correctly updates the name/icon, but while the workspace was correctly styled as active before, it no longer is after the rename. I have to switch to another workspace and back to force an update.

**Comment by khaneliman** [comment]
@foonathan Can you try with the PR https://github.com/Alexays/Waybar/pull/2485 ?

**Comment by foonathan** [comment]
I can confirm it's fixed. Thank you.
