### ISSUE TITLE
#window.empty do not work

### ISSUE THREAD

**Issue by Nyayurn** [Alexays/Waybar#2487]
[config.txt](https://github.com/Alexays/Waybar/files/12565328/config.txt)
[style.css.txt](https://github.com/Alexays/Waybar/files/12565329/style.css.txt)
Any window focus:
![Screen](https://github.com/Alexays/Waybar/assets/132195516/d98eccb8-ad15-4c30-9153-4e6048903e54)
No window:
![Screen](https://github.com/Alexays/Waybar/assets/132195516/823652a2-564b-4926-b925-b22209765adc)

**Comment by RobertMueller2** [comment]
I don't know the hyprland/window module too well, but you're trying to style the id #windowy and I believe that's not correct.

The whole waybar is an element with the name window and the id waybar.

Hyprland/window is an element with the name label and the id window.

The empty class is applied by the window module to the former, not the latter.

If you want to style the waybar, use
#waybar.empty or window#waybar.empty

If you want to style the module widget, use #waybar.empty #window or window#waybar.empty #window.

HTH
R.

**Comment by Nyayurn** [comment]
> I don't know the hyprland/window module too well, but you're trying to style the id #window and I believe that's not correct.
> 
> The whole waybar is an element with the name window and the id waybar.
> 
> Hyprland/window's widget is an element with the name label and the id window.
> 
> The empty class is applied by the window module to the former, not the latter.
> 
> If you want to style the waybar, use #waybar.empty or window#waybar.empty
> 
> If you want to style the module widget, use #waybar.empty #window or window#waybar.empty #window.
> 
> HTH R.

I just want to style the hyprland/window when it's show empty like wiki
![Screen](https://github.com/Alexays/Waybar/assets/132195516/effba6ae-788c-4a85-b9e0-d39186e03fe3)

**Comment by RobertMueller2** [comment]
OK, I see. The documentation implies that #window.empty can be styled. But I can't confirm that the class is set on #window when looking at the source code. Only on #waybar.

I tested it on a hyprland session too and indeed it does not work. I also tested the below, and it works for me:

```
window#waybar.empty #window {
  padding: 0px;
  margin: 0px;
  border: 0px;
/*  background-color: rgba(66,66,66,0.5); */ /* transparent */
  background-color: transparent;
}
```

Looking at the wiki though, this might be a bug. Somebody with more clue about the hyprland module will have to decide about that ;) In the meantime, you might be able to use the css above as a workaround.

**Comment by Nyayurn** [comment]
> OK, I see. The documentation implies that #window.empty can be styled. But I can't confirm that the class is set on #window when looking at the source code. Only on #waybar.
> 
> I tested it on a hyprland session too and indeed it does not work. I also tested the below, and it works for me:
> 
> ```
> window#waybar.empty #window {
>   padding: 0px;
>   margin: 0px;
>   border: 0px;
>   background-color: transparent;
> }
> ```
> 
> Looking at the wiki though, this might be a bug. Somebody with more clue about the hyprland module will have to decide about that ;) In the meantime, you might be able to use the css above as a workaround.

thanks, it's work
