### ISSUE TITLE
persistent workspace in hyprland not working

### ISSUE THREAD

**Issue by XxRiKxX** [Alexays/Waybar#2489]
"hyprland/workspaces": {
	    "format": "{icon}",
	    "all-outputs": true,
        "active-only": false,
        "format-icons": {
            "1": "一",
            "2": "二",
            "3": "三",
            "4": "四",
            "5": "五",
            "6": "六",
            "7": "七",
            "8": "八",
            "9": "九",
            "10": "十"
        },

        "persistent_workspaces": {
            "*": 10
        },
	"on-click": "activate"
	},

I want to it to show alll the 10 workspaces even those that are not active or occupied

**Comment by XxRiKxX** [comment]
nvm fixed it. and sorry for the disturbance.

**Comment by zjeffer** [comment]
Please also include how you fixed it, that info might be useful to other people.

[Don't be like DenverCoder9](https://xkcd.com/979/) :)

**Comment by XxRiKxX** [comment]
lol sorry. I just set all-outputs to false
