### ISSUE TITLE
unknown module cava

### ISSUE THREAD

**Issue by XxRiKxX** [Alexays/Waybar#2490]
I am using hyprland and waybar from the official repo (not the waybar-hyprland-git). the cava is working normally in terminal.

also how can I display cover art of the song when I hover on mpris module?

**Comment by stauersbol** [comment]
I assume you are doing what the hyprland wiki says about manual building? You can remove the part `--wrap-mode=nodownload` from the build command, I had to do that in order for it to work properly

**Comment by XxRiKxX** [comment]
why should I manually compile when it is available in the repo? and also the waybar wiki does not mention compiling from source to get the cava module working.

**Comment by manfred3000** [comment]
`waybar` is built without cava support:
https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/blob/main/PKGBUILD
You'll either have to kindly ask one of the maintainers if they'd consider enabling it, or built it yourself atm...

**Comment by stauersbol** [comment]
> why should I manually compile when it is available in the repo? and also the waybar wiki does not mention compiling from source to get the cava module working.

Never said you had to compile it manually, but I just explained the problem encountered with doing a manual compile and it seemed like you had the same issue

**Comment by XxRiKxX** [comment]
for now I have found a aur package called waybar-hyprland-cava-git. but I dont really get why they would exclude cava.

**Comment by manfred3000** [comment]
> I dont really get why they would exclude cava.

Because no Arch Package Maintainer cares (enough) about cava to package it for Arch Linux (the AUR is not Arch)...

**Comment by XxRiKxX** [comment]
no I mean why exclude it from the waybar.
