### ISSUE TITLE
The jsonparser doesn't work with escaped unicode characters

### ISSUE THREAD

**Issue by zjeffer** [Alexays/Waybar#2495]
I wrote a test for this:

```cpp
TEST_CASE("Json with unicode", "[json]") {
  SECTION("Parse json with unicode") {
	std::string stringToTest = R"({"test": "\xab"})";
	waybar::util::JsonParser parser;
	Json::Value jsonValue = parser.parse(stringToTest);
	REQUIRE(jsonValue["test"].asString() == "\xab");
  }
}
```

```
../test/JsonParser.cpp:20: FAILED:
due to unexpected exception with message:
  * Line 1, Column 10
    Bad escape sequence in string
  See Line 1, Column 13 for detail.
```

causes problems with hyprland IPC if for example the monitor description/model contains unicode characters: #2475 

I'm not sure if this is a problem with our parsing code (include/util/json.hpp), or a problem with the upstream jsoncpp library we're using?

**Comment by amplexus** [comment]
I have a monitor with hex values in the name as output by hyprctl monitors and am getting errors with waybar hyprland workspaces that looks kind of like https://github.com/Alexays/Waybar/issues/2475 but also kind of like https://github.com/Alexays/Waybar/issues/2398:
```
# hyprctl monitors
Monitor eDP-1 (ID 0):
	3840x2160@60.001999 at 0x0
	description: BOE 0x0866 (eDP-1)
	make: BOE
	model: 0x0866
	serial: 
	active workspace: 3 (3)
	reserved: 0 30 0 0
	scale: 2.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

I'm wondering whether the parser also is unhappy when it sees 0xXXXX characters in the input string (monitor metadata)?

**Comment by amplexus** [comment]
Ok never mind. I added a test to https://github.com/open-source-parsers/jsoncpp containing my  monitor description string and it didn't complain. My issue is unrelated to this bug.
