### ISSUE TITLE
colors not working properly in hyprland/workspaces module.

### ISSUE THREAD

**Issue by XxRiKxX** [Alexays/Waybar#2497]
no matter what color I set, its black for active, occupied and persistent. I am using the waybar-hyprland-git from aur. this is in my style .css

#workspaces {
    background: radial-gradient(@color1, @color3, @color5, transparent);
    border-radius: 0px;
}

#workspaces button {
    color: @color7;
    border-radius: 0px;
    border-bottom: 2px solid @color4;
}
#workspaces button:hover {
  color: @color6;
  background: none;
}
#workspaces button.active {
    color: @foreground;
    border-radius: 0px;
    border-bottom: 2px solid @color2;
}

#workspaces button.active:hover {
    color: @color9;
    background: none;
}

#workspaces button.persistent {
    color: @background;
    border-radius: 0px;
}

#workspaces button.persistent:hover {
    color: @cursor;
    background: none;
}

**Comment by ronitnallagatla** [comment]
Based on what I'm reading about [waybar-hyprland-git](https://aur.archlinux.org/packages/waybar-hyprland-git), this package is obsolete, and vanilla waybar works should work with hyprland.

**Comment by bklaase** [comment]
Could you link your complete css? I'll try and figure it out. I was able to get it to do whatever, so it must be possible ;)

Also install waybar binary package as suggested!
