### ISSUE TITLE
Hyprland/Workspaces: icon for named special workspace is not cleared on toggle

### ISSUE THREAD

**Issue by akowiz** [Alexays/Waybar#2505]
I am using the latest version of waybar (v0.9.22-43-g309dd05).

I have enabled the option to show the icon for the special workspace.

### with the default special workspace (works fine)

When I toggle "on" the unnamed (default) special workspace, the icon show up, then disappear when I toggle off this special workspace. Everything works fine in that situation.

![Captured_2023 09 13_11 49 03](https://github.com/Alexays/Waybar/assets/62418288/78a20114-0ac0-4072-ba3e-0f831b214fe7)

### With extra named special workspaces (issue)

I have defines an extra special workspace (to put "minimized" windows).

When I toggle "on" this named special workspace, the icon for special workspace show up on Waybar (as it should). But when I toggle "off" the named special workspace, the icon stay put (does not disappear). If I toggle "on" the named special workspace once more, an extra icon appear on Waybar, which doesn't disappear when I toggle "off" the named special workspace. 

After a while, my Waybar is cluttered with icons of the special workspace. The only way to get ride of the icons is to restart Waybar.

![Captured_2023 09 13_11 50 35](https://github.com/Alexays/Waybar/assets/62418288/35af9239-d102-4b87-96b3-f2802d6af233)

**Comment by zjeffer** [comment]
@MightyPlaza This was the strange behaviour I was talking about [here](https://github.com/Alexays/Waybar/issues/2271#issuecomment-1699813350). 

I didn't have really have time to explain it then (very busy at work atm and not a lot of energy left for things like these) but here's the explanation :wink:
