### ISSUE TITLE
Waybar cannot display workspaces

### ISSUE THREAD

**Issue by PILIHU2022** [Alexays/Waybar#2511]
- OS: Arch linux-zen 6.5.3
- WM:Hyprland
- Waybar:waybar-hyprland-git
![image](https://github.com/Alexays/Waybar/assets/100511118/e6f7b90e-07a0-4240-8315-3b1d6a02488e)

I used the configuration I wrote and checked for errors, but it didn't solve the problem. The same is true for the system tray.

**Comment by bknightInfo** [comment]
> * OS: Arch linux-zen 6.5.3
> * WM:Hyprland
> * Waybar:waybar-hyprland-git
>   ![image](https://user-images.githubusercontent.com/100511118/268423036-e6f7b90e-07a0-4240-8315-3b1d6a02488e.png)
> 
> I used the configuration I wrote and checked for errors, but it didn't solve the problem. The same is true for the system tray.

Two things
1) In your waybar configuration make sure you have changed wlr/workspaces to hyprland/workspaces
2) Waybar:waybar-hyprland-git is no longer need as hyprland changes have been incorporated into waybar-git

**Comment by PILIHU2022** [comment]
It works,thank you
