### ISSUE TITLE
Waybar Crashing (Multimonitor Setup + Swaylock Interaction)

### ISSUE THREAD

**Issue by skunkfox** [Alexays/Waybar#2520]
I am on Archcraft Sway Premium as my OS. I have my laptop connected to a dock with three monitors. I can't be sure, but it seems like what happens is that I'll leave my computer to idle, it will enter Swaylock, I will exit Swaylock, and everything is fine for a while and then waybar crashes.

I wish I had more specifics, luckily I did start waybar in debug mode and I have its stdout and stderr as well as a core dump. I'll attach my configuration files as well, let me know if there is anything else you need.

[waybar.err.txt](https://github.com/Alexays/Waybar/files/12665439/waybar.err.txt)
[waybar.out.txt](https://github.com/Alexays/Waybar/files/12665440/waybar.out.txt)
[configs.zip](https://github.com/Alexays/Waybar/files/12665476/configs.zip)
[coredump.txt.zip](https://github.com/Alexays/Waybar/files/12665479/coredump.txt.zip)

**Comment by Alexays** [comment]
Might be fixed with https://github.com/Alexays/Waybar/pull/3215
