### ISSUE TITLE
Keyboard state not working

### ISSUE THREAD

**Issue by CreativeKittens** [Alexays/Waybar#2521]
Keyboard state not working with warning below,

currently on hyprland and waybar version v0.9.22-69-g9b8adc19 (branch 'master')

`module keyboard-state: Disabling module "keyboard-state", Failed to find keyboard device: EACCES Permission denied`

**Comment by aspizu** [comment]
`sudo usermod -aG input aspizu`

Log out and log back in. (Don't forget this!)

**Comment by CreativeKittens** [comment]
> `sudo usermod -aG input aspizu`
> 
> Log out and log back in. (Don't forget this!)

thanks 👍
