### ISSUE TITLE
Hyprland: visible class not being applied to workspace buttons

### ISSUE THREAD

**Issue by GabrielFoxDev** [Alexays/Waybar#2523]
If I understand it correctly, when a workspace is visible (it's showing on a monitor, regardless of mouse focus), its button should have the `visible` class added to it.

This is not happening : (

![image](https://github.com/Alexays/Waybar/assets/90432575/c589ee99-257c-484d-a9ab-3152b142fb06)

This is my hyprland/workspaces config
```jsonc
// . . .
    "hyprland/workspaces": {
        "persistent_workspaces": {
            "1": ["DVI-I-1"],
            "2": ["DVI-I-1"],
            "3": ["DVI-I-1"],
            "4": ["HDMI-A-1"],
            "5": ["HDMI-A-1"],
            "6": ["HDMI-A-1"]
        },
	    "format": "<sup>{name}</sup>\n{icon}",
	    "format-icons": { // Nerd Font glyphs
		    "4": "",
		    "5": "",
		    "6": "󱎂",
		    "1": "",
		    "2": "",
		    "3": "󰺾"
	    }
    },
// . . .
```

Am I missing or misunderstanding something?

**Comment by GabrielFoxDev** [comment]
Hyprland v0.27.2-65-g5c50fac9
Waybar v0.9.22
Arch Linux

**Comment by khaneliman** [comment]
0.9.22 doesn't have that feature. https://github.com/Alexays/Waybar/compare/0.9.22...master#diff-19fcfa11dfbb35133193b000f1f88e5c337171946f2011a44c39f9cf3741cb7dR63

**Comment by GabrielFoxDev** [comment]
Okay, so I was missing something :P
Built from sources and it's working now, thanks! <3
