### ISSUE TITLE
Add battery status for plugged in, but not charging

### ISSUE THREAD

**Issue by norseghost** [Alexays/Waybar#253]
I'd like to distinguish from

- battery plugged in, but not charging (I set charging thresholds with TLP)
- battery charging
- battery discharging

preferably with different format_icons for each state (ex, discharging -> battery levels; charging -> battery levels with power symbol; plugged in/not charging -> power plug)

**Comment by sharethewisdom** [comment]
I'd like `#battery` to also have successive classes based on the states, e.g. `#battery:not(.charging)._30` would allow me to style an 'unloading bar' background animation spanning 30% of the module's total width.

**Comment by Alexays** [comment]
@sharethewisdom What do you mean? The state key is added as a class.

**Comment by Alexays** [comment]
Should be done with 5b3402e110eca2bb3f99c6c81fa78106f7a51d29

**Comment by sharethewisdom** [comment]
sorry, I was confusing states with statuses :confused:

so it was already possible to define `states = { "_90": 90 }` and use it as `#battery:not(.charging)._90 { animate: ... }` and include a css transition to change the background-size for `._80`, `._70`, ... classes.

**Comment by norseghost** [comment]
How would I go about defining formaticons for the charging state?
