### ISSUE TITLE
issues with corner

### ISSUE THREAD

**Issue by XxRiKxX** [Alexays/Waybar#2535]
![633](https://github.com/Alexays/Waybar/assets/102613873/37fa29b0-65c1-40c8-a6ba-27b10f518c9c)

this is my style.css

@import "colors-waybar.css";

* {
    font-family: 'Hurmit Nerd Font';
    font-size: 14px;
    font-weight: bold;
}

window#waybar {
    background: transparent;
    border-radius: 7px;
    border: 2px solid @color1;
}

#workspaces {
    border-radius: 0px;
}

#workspaces button {
    color: #808080;
    border-radius: 0px;
}
#workspaces button:hover {
  color: @color6;
  background: none;
}
#workspaces button.active {
    color: @foreground;
    border-radius: 0px;
}

#workspaces button.active:hover {
    color: @color1;
    background: none;
}

#window {
    color: @foreground;
}

**Comment by its-darsh** [comment]
Hello there, if you're using hyprland you can add this block into your layer rules on you hyprland.conf
```
layerrule = blur, waybar
layerrule = ignorezero, waybar
```
I hope this helps you out.

**Comment by LukashonakV** [comment]
Hi @XxRiKxX 
Or you could try
```json
window#waybar {
    background-color: @base01;
    border-bottom: 1px solid #181825;
    border-radius: 50px;
    transition-property: background-color;
    color: @base02;
}
```
[from my dot files](https://gitlab.com/Viktar/dotfiles/-/blob/main/.config/waybar/style.css?ref_type=heads)

![ps_2023-11-11-12_31_03](https://github.com/Alexays/Waybar/assets/23121044/86ccbc5c-6d80-47ba-aef8-136f56d826f3)
