### ISSUE TITLE
Feature request: in hyprland/workspaces allow also for window title and regex

### ISSUE THREAD

**Issue by euglevi** [Alexays/Waybar#2561]
I think that the recent commit on Hyprland dynamic window names on workspaces (58e506a6754fae213e409bcd079d38d03f70b958) by @Syndelis was very cool. It works very well in my setup.  If I understood correctly, at the moment it is only possible to use the window class to set the icon. Would it be possible/easy to add also the window title and/or allow for regex strings? I am sorry that I cannot help with this as I am not really proficient in coding.

**Comment by euglevi** [comment]
Thank you for taking up my proposal! The syntax you suggested looks fine to me. Better than having two separate configuration parameters. An even more advanced feature would be to allow for a combination of titles/classes. Maybe something like:

```
 "window-rewrite": {
  "class(firefox).title(.*facebook)": "",
}
```
where if you leave one of the two out, then it considers only classes or only titles. This combination could take precedence over the simple ones.

**Comment by euglevi** [comment]
A slash or a whitespace both look like good solutions to me!

**Comment by euglevi** [comment]
Thanks for all your work on this!

Now that I think of it, there could be another cool feature. Hyprctl also tells if the window is in fullscreen mode. It would be nice to have a graphical sign (asterisks, brackets, etc.) that tells when the window is maximized.

**Comment by gvolpe** [comment]
Apologies for spamming this PR, but is it possible to have the same for `hyprland/window`? 🙏🏽 https://github.com/Alexays/Waybar/issues/2389
