### ISSUE TITLE
waybar-wireplumber causes waybar to crash if the default output node does not have a "node.nick" value specified in pipewire.

### ISSUE THREAD

**Issue by ysdemiranda** [Alexays/Waybar#2571]
Hello, 

I'm trying to work around an unrelated issue with pipewire and proton. I'm implementing a script where I basically create a virtual node that tunnels "desktop audio" into my main output channels of a pro audio interface. When I change the default output for pulseaudio to a device that has no `node.nick` specified, waybar will crash and on restart it will recieve a SIGSEGV.
Steps to reproduce:
* set any node without a node.nick value as the default pulseaudio output while having waybar running or run waybar afterwards

For example:

**ALWAYS TURN OFF AMPLIFIERS BEFORE JUGGLING WITH VIRTUAL SOUND PIPES. IF YOU HAVE A PRO AUDIO INTERFACE YOU PROBABLY HAVE PRO AUDIO SPEAKERS AS WELL**

`pw-cli create-node adapter '{ factory.name=support.null-audio-sink node.name=my-gaming-sink media.class=Audio/Sink object.linger=true audio.position=[FL FR] audio.sample_rate=44100 }'`

and then

`pactl set-default-sink my-gaming-sink`

as taken from this thread: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3120

Actually setting the `node.nick` value to something causes waybar to work as expected.

**Comment by Mrcarrot1** [comment]
I ran into this issue myself; it is fixed in #2648 (merged into master 3 days ago).
