### ISSUE TITLE
ninja compile error for ../network.cpp/nla_get_s32 not declared in this scope

### ISSUE THREAD

**Issue by aus9** [Alexays/Waybar#258]
Hi
at this stage of compiling  (I run as root)
# ninja -C build
I see error
`../src/modules/network.cpp: In member function 'void waybar::modules::Network::parseSignal(nlattr** ':
../src/modules/network.cpp:504:28: error: 'nla_get_s32' was not declared in this scope
     signal_strength_dbm_ = nla_get_s32(bss[NL80211_BSS_SIGNAL_MBM]) / 100;
                            ^~~~~~~~~~~
../src/modules/network.cpp:504:28: note: suggested alternative: 'nla_get_u32'
     signal_strength_dbm_ = nla_get_s32(bss[NL80211_BSS_SIGNAL_MBM]) / 100;
                            ^~~~~~~~~~~
                            nla_get_u32`

I am compiling on a tower but my coding skills are not great. Any chance you know how to get around this?
Am compiling on Tinycore v 10 64 bit which defaults to /usr/local

If you need it...some dropbox links to various files

https://www.dropbox.com/s/mrsuscim5cyver2/meson-log.txt?dl=0
^^ only thing not found is .....Program clang-tidy found: NO

.ninja log converted from hidden file to txt file
https://www.dropbox.com/s/li8j6rckifcet57/ninja_log.txt?dl=0

build ninja
https://www.dropbox.com/s/pav70pimo8cz3hh/build.ninja?dl=0

my "incomplete" build script so far
https://www.dropbox.com/s/t40oe9ebracmtk0/build-waybar.sh?dl=0

umm not sure what else to link to....so if you have need more let me know please

thanks for sharing any thoughts

gordon aka aus9

**Comment by Alexays** [comment]
Seems we need to define nla_get_s32 when it's not available cause of an outdated version

**Comment by aus9** [comment]
Hi
what package on your system provides nla*?
I just did a private update of libnl but issue remains
`../src/modules/network.cpp:504:28: error: 'nla_get_s32' was not declared in this scope
     signal_strength_dbm_ = nla_get_s32(bss[NL80211_BSS_SIGNAL_MBM]) / 100`

Or
are you saying I just need to define it and if so....how?

thanks for sharing any thoughts on this matter

**Comment by aus9** [comment]
Hi
Similar compile issue for 0.6 release but libnl has been updated in repository
Still missing clang-tidy
I have not got tray support working correctly in sway so until I resolve that issue, please close this thread
Thanks
