### ISSUE TITLE
clock#date no longer appearing

### ISSUE THREAD

**Issue by Kagukara** [Alexays/Waybar#2580]
The date in my bar is no longer appearing.

Waybar Version: `Waybar v0.9.22-147-g5319cb6e (branch 'master')`

Before my date was under my clock like this:
![capture_2023-10-18_12-56-25](https://github.com/Alexays/Waybar/assets/43391109/fe264436-d253-4ce4-adbb-50305b21e481)

But now it looks like this:
![capture_2023-10-18_12-56-00](https://github.com/Alexays/Waybar/assets/43391109/a0292111-5e1f-4d30-99f5-d0463fc82df0)

How I have it setup in my config:
```
	"clock": {
		"interval": 60,
		"format": "{:%H\n%M}",
		"timezone": "Europe/London",
	},

	"clock#date": {
		"interval": 60,
	   	"format": "{: %d\n %m\n%Y}",
		"timezone": "Europe/London",
		"tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
	},
```

**Comment by romanstingler** [comment]
probably the same issue as https://github.com/Alexays/Waybar/issues/2579
plase try 
 0.9.22.r148.g871f9a12-1 
 is already up on chaotic-aur 
 or build your package yourself

**Comment by Kagukara** [comment]
Its now working using, `Waybar v0.9.22-148-g871f9a12 (branch 'master')`.
![image](https://github.com/Alexays/Waybar/assets/43391109/b58e86e9-4b38-40e6-81d9-3a1f793a0305)
