### ISSUE TITLE
faulty corners in waybar with hyprland 

### ISSUE THREAD

**Issue by AnkurAlpha** [Alexays/Waybar#2583]
I want some rounded corners in waybar for which I set it to something like this : 
~~~
window#waybar {
    background:rgba (0, 0, 0, 0.5);
    border-radius: 20px 20px 20px 20px; 
}
~~~ 
in style.css
but it shows me something like this : 
![2023-10-19T12:55:38,657360466+05:30](https://github.com/Alexays/Waybar/assets/132189303/87e1c037-b2f4-416a-a69a-c5278fae7c7f)
you can see on left and right side there is a little bit of rectangular transparent corner with rounded corners,
![2023-10-19T16:43:34,003422460+05:30](https://github.com/Alexays/Waybar/assets/132189303/8746ecf2-a5e5-49dc-abb9-bc8713790b50)
![2023-10-19T16:54:52,692079136+05:30](https://github.com/Alexays/Waybar/assets/132189303/7e2a272f-16fb-4bba-b842-0810a173cbeb)
The corners seems to be half rounded and half rectangular.

Any help for this issue will be appreciated :slightly_smiling_face: 
Thanks in advance :smile:

**Comment by mutoroglin** [comment]
I assume that the widget with the burger menu is the culprit with the pointy corners. Did you change the `background: transparent` on the elements subordinated `window#waybar`?

I can think of two ways to approach this issue.

In your css set the background property of all elements to transparent (that works for me, you may want to check my dotfiles):
```
* {
background: transparent
}
```
Alternatively start waybar with the GTK debugger tool `env GTK_DEBUG=interactive waybar` and check there the css properties of all elements in the hierarchy to see which one has a background and corner vlaue set.

**Comment by AnkurAlpha** [comment]
> In your css set the background property of all elements to transparent (that works for me, you may want to check my dotfiles):
> 
> ```
> * {
> background: transparent
> }
> ```

That gave me something like these : 
![2023-10-21T17:08:10,387123348+05:30](https://github.com/Alexays/Waybar/assets/132189303/8e3e1801-6514-408e-baab-00192e883d8e)

![2023-10-21T17:07:11,082834321+05:30](https://github.com/Alexays/Waybar/assets/132189303/52b9097a-7c11-4d7a-9de2-d2d75dff8f31)



> env GTK_DEBUG=interactive waybar


I am pretty newbi in these things, so I just clicked on some random stuffs that first appeared on screen after typing the commands sometimes it used blink for some of things : 

http://0x0.st/HJWh.mp4
 
IDK whether it would be any helpful or not :slightly_frowning_face:

**Comment by imxyy1soope1** [comment]
![图片](https://github.com/Alexays/Waybar/assets/103114856/4059eeee-4541-44f0-9a2b-f556e8060665)

**Comment by AnkurAlpha** [comment]
Thanks :smiley: !!!
I did this and it worked : 
~~~
#status bar
exec-once = waybar
# blurls = waybar
layerrule = blur , waybar
layerrule = ignorezero , waybar
~~~
![2023-10-22T18:32:04,593619558+05:30](https://github.com/Alexays/Waybar/assets/132189303/3d6584ad-9372-4d2f-9ff6-60870efb2937)

**Comment by command-z-z** [comment]
> Thanks 😃 !!! I did this and it worked :
> 
> ```
> #status bar
> exec-once = waybar
> # blurls = waybar
> layerrule = blur , waybar
> layerrule = ignorezero , waybar
> ```
> 
> ![2023-10-22T18:32:04,593619558+05:30](https://private-user-images.githubusercontent.com/132189303/277167725-3d6584ad-9372-4d2f-9ff6-60870efb2937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Njg3OTYsIm5iZiI6MTcxNjk2ODQ5NiwicGF0aCI6Ii8xMzIxODkzMDMvMjc3MTY3NzI1LTNkNjU4NGFkLTkzNzItNGQyZi05ZmY2LTYwODcwZWZiMjkzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwNzQxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTZjYTE3MGViM2JkYzBiMjBjMzJlMWE4ODAwMzMyMGJiM2Q5NWZiMWRhMGM4YjJkNjE3NjIzMTdhZmRiY2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7h9Mmi2ZdxEcTuSpgMpcbs3Id5LyIngEfVOBzhRPtU0)

I have same problem, but set layerrule is not work. Your waybar is in good condition now?

**Comment by command-z-z** [comment]
> Thanks 😃 !!! I did this and it worked :
> 
> ```
> #status bar
> exec-once = waybar
> # blurls = waybar
> layerrule = blur , waybar
> layerrule = ignorezero , waybar
> ```
> 
> ![2023-10-22T18:32:04,593619558+05:30](https://private-user-images.githubusercontent.com/132189303/277167725-3d6584ad-9372-4d2f-9ff6-60870efb2937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Njg5OTYsIm5iZiI6MTcxNjk2ODY5NiwicGF0aCI6Ii8xMzIxODkzMDMvMjc3MTY3NzI1LTNkNjU4NGFkLTkzNzItNGQyZi05ZmY2LTYwODcwZWZiMjkzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwNzQ0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWIzZmVhMTdjYWY4YzlhMDZmODk5MDVmN2VhYThlM2M1N2QwZWM2ZTRlOGFjOTU0MzhlYzMzNmJiYTY5ODVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AyoPMrPiTccRUyoIOuGWvdg_VRvf5XNjxq7fmH0gOsg)

Sorry to bother you, I fix it. I don't notice that i set `box-shadow: 1px 1px 10px 10px @mantle;` in waybar config so that this problem arises.

**Comment by AnkurAlpha** [comment]
> Your waybar is in good condition now?

Yup, if you want, you can see my configs [here](https://gitlab.com/AnkurAlpha/garuda-hyprland-settings/-/tree/main/etc/skel/.config/waybar?ref_type=heads) :eyes:
