### ISSUE TITLE
[Bug] first entered workspace doesn't follow `persistent_workspace` rule in Hyprland after eefd6e8

### ISSUE THREAD

**Issue by imxyy1soope1** [Alexays/Waybar#2597]
see the video

https://github.com/Alexays/Waybar/assets/103114856/a9072c22-ecbc-4af9-9571-5583dbaa12ea

**Comment by Syndelis** [comment]
Hi there, I believe I'm the author of eefd6e8. I don't quite understand the issue from the title and video alone, could you elaborate exactly what is not working?

**Comment by rehanzo** [comment]
> Hi there, I believe I'm the author of [eefd6e8](https://github.com/Alexays/Waybar/commit/eefd6e83367d8f7bfd0497a3901fffadd843b391). I don't quite understand the issue from the title and video alone, could you elaborate exactly what is not working?

workspace 1 ends up disappearing, even though its listed as a persistent workspace

**Comment by zjeffer** [comment]
I can confirm the same behaviour. 

I have 5 workspaces per monitor. If I open a window on the first monitor and then switch to a different workspace, the first workspace stays in the bar. If I move the window to a different workspace so the workspace is empty, and then move to another workspace, the workspace dissappears as if it isn't marked as persistent.

**Comment by Syndelis** [comment]
I think I found the problem. @imxyy1soope1 @rehanzo @zjeffer could you please try PR #2605 ?

**Comment by rehanzo** [comment]
> I think I found the problem. @imxyy1soope1 @rehanzo @zjeffer could you please try PR #2605 ?

So far seems to work well for me
