### ISSUE TITLE
hyprland - Persistent workspaces sometimes disappear

### ISSUE THREAD

**Issue by rehanzo** [Alexays/Waybar#2602]
On hyprland, when switching workspaces, occasionally a persistent workspace will disappear. This seems like a recent occurrence, as this hadn't happened to me prior. Particularly, it'll usually happen if I'm in an empty workspace, open a window, eventually close that window, and move to another workspace. It's not really too reproducible though.

**Comment by rehanzo** [comment]
Seems reverting the eefd6e8 pr may have solved it for me, but not entirely sure as I couldn't find out how to reproduce it. I'll update if it wasn't the offending commit.

**Comment by imxyy1soope1** [comment]
dup with #2597

**Comment by rehanzo** [comment]
> dup with #2597

Cool, closing.
