### ISSUE TITLE
[Bug]Several requests were sent at the same time in a short period of time, and some failed to respond

### ISSUE THREAD

**Issue by DreamMaoMao** [Alexays/Waybar#2607]
![image](https://github.com/Alexays/Waybar/assets/30348075/21fac9cf-e6a9-4c15-9b75-a0d09413a524)

https://github.com/Alexays/Waybar/assets/30348075/4dfc9d64-ff5e-4b96-9064-48c8137ebdbe

In the video, you can see that worksapce 3 sometimes does not show up, but from the log,waybar has successfully received the IPC request

**Comment by Syndelis** [comment]
Could you describe your setup so I can try to reproduce the problem? Specifically, these questions came to mind:
1. What is it you're doing that seemingly spawns/destroys 5 workspaces at once?
2. Are these workspaces populated by any windows?
3. Are they set as "persistent" on your Waybar/Hyprland configuration?

Thanks in advance for your time opening this issue and recording a video!

**Comment by DreamMaoMao** [comment]
> Could you describe your setup so I can try to reproduce the problem? Specifically, these questions came to mind:
> 
> 1. What is it you're doing that seemingly spawns/destroys 5 workspaces at once?
> 2. Are these workspaces populated by any windows?
> 3. Are they set as "persistent" on your Waybar/Hyprland configuration?
> 
> Thanks in advance for your time opening this issue and recording a video!

1.What is it you're doing that seemingly spawns/destroys 5 workspaces at once?
I am making a hyprland plugin[plugin](https://github.com/DreamMaoMao/hycov)

setup1 I moved the Windows of five workspaces to another workspace at the same time
setup2 I moved all the Windows I had previously moved back to the previous workspace

2.Are these workspaces populated by any windows?
the answer is no

3.Are they set as "persistent" on your Waybar/Hyprland configuration?
the answer is no 

logfile:

[waybar.log](https://github.com/Alexays/Waybar/files/13138352/waybar.log)

It is worth noting that when I have only three workspaces, this bug is very unlikely to occur, but when I have six workspaces with Windows, this operation is very likely to occur (repeat the operation once to five times).

This seems to be a software performance issue under high load.

**Comment by Syndelis** [comment]
> 2.Are these workspaces populated by any windows?
> the answer is no

Correct me if I'm wrong, but Hyprland deletes empty workspaces, so that should be an expected behavior (?)

**Comment by DreamMaoMao** [comment]
@Syndelis 
What I mean is that no window is occupied before the deletion request is sent

The workspace is already occupied by a window before the create request is sent

**Comment by DreamMaoMao** [comment]
When I sent five workspace creation requests, sometimes some workspaces didn't show up on waybar, but the hyprland operation didn't affect it, it just didn't show up on waybar when I jump to that workspace.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/Alexays/Waybar/assets/30348075/b97c3e8d-c94e-4307-8cb2-e8b58e2f6e10)

Sometimes this workspace symbol is repeated

These problems rarely occur when there are only three workspaces and three Windows, but they are likely to occur when the number of workspaces and Windows becomes large

**Comment by DreamMaoMao** [comment]
From the log, there is no problem with the ipc requests sent, but the number of Windows created and deleted is different from before

**Comment by DreamMaoMao** [comment]
![image](https://github.com/Alexays/Waybar/assets/30348075/70495b6f-e508-493b-a7b5-d1c1f4a0560f)
I tried to comment these two lines of code and found that the deletion and create loss issues were resolved (except for a few other minor issues)

So I think the problem is caused by asynchronous manipulation of global variables

**Comment by DreamMaoMao** [comment]
![image](https://github.com/Alexays/Waybar/assets/30348075/66947490-91cf-4f0b-ae31-2776001fbc60)
That is to say, when the code at label:1 is executed, and before label:3 is executed, another event may trigger the new "workspaces_to_remove_.push_back" at label:2, and this new data is not used by label:1 but was deleted in label:3.

![image](https://github.com/Alexays/Waybar/assets/30348075/9590c60d-f57e-41ca-bfe4-828b9ffb944c)
