### ISSUE TITLE
Bug? Reserve space when docking left/right

### ISSUE THREAD

**Issue by matthiasbeyer** [Alexays/Waybar#261]
According to [this discussion](https://github.com/swaywm/sway/issues/3373#issuecomment-483036360) it might be that waybar does not allocate space left/right when the bar is displayed on the left/right side.

Is this an waybar issue?

**Comment by Alexays** [comment]
You can force with the `width` or `height` option :)

**Comment by matthiasbeyer** [comment]
I tried `width` for it, but it did not work as expected.

**Comment by Alexays** [comment]
Fixed with 311c34ecbc61a3dd4f1f9b4954693bf134e17604
