### ISSUE TITLE
pulseaudio module don't reconnect au pipewire-pulse restart

### ISSUE THREAD

**Issue by cyrinux** [Alexays/Waybar#2619]
Hi,

I feel like I have several times to restart waybar to get the audio module updating.
For sure I reproduce it now when restart pipewire-pulse.service.

I'm bad in C++, doesn't those audio module try to auto-reconnect on the socket?

Regards

**Comment by kit-ty-kate** [comment]
I also hit the same issue. A simple `systemctl --user restart pipewire.service` makes the pulseaudio module show wrong values.
For example `{volume}` changes to `100` and stay this way even when I increase or decrease volume.

Restarting waybar fixes it but it's a bit annoying.
