### ISSUE TITLE
icons not appearing in the tray section?

### ISSUE THREAD

**Issue by formula-spectre** [Alexays/Waybar#2644]
running sway, version 1.8.1 and waybar v0.9.22
Distro: Gentoo Linux, musl libc  
electron applications work fine, say discord and element-desktop (even if they're in containers), but native applications don't work; for example, [telega.el](https://github.com/zevlg/telega.el) and kdeconnect-indicator, also I think calibre but I never tried the tray option  
is this a known bug? because I read some issues about it, but i did not understand if it was fixed or not

**Comment by archseer** [comment]
Could be https://github.com/Alexays/Waybar/pull/2626 ?

**Comment by formula-spectre** [comment]
it was a dbus problem  
i feel stupid  
sorry
