### ISSUE TITLE
Animated icons bug in the tray

### ISSUE THREAD

**Issue by Difrex** [Alexays/Waybar#266]
Hi,
just look the gif.

![waybar](https://user-images.githubusercontent.com/3982213/56123631-7f220f00-5f7d-11e9-9dfc-dca18f2d8616.gif)

Waybar version is `Waybar v0.5.1 (Apr 10 2019, branch 'master')`

**Comment by Alexays** [comment]
This should be fixed with 3273ee8b426e156e0834566c823cd36f8a1c8f25

**Comment by Difrex** [comment]
Great! Thanks!
