### ISSUE TITLE
After updating the version, my clock displays an error

### ISSUE THREAD

**Issue by 0a00** [Alexays/Waybar#2669]
After updating the version, my clock displays an error
![图片](https://github.com/Alexays/Waybar/assets/59482058/5054810f-511c-417d-bc09-db90b05c8676)

**Comment by LukashonakV** [comment]
Hi @0a00 , with PR#2659 clock now is using chrono format [ormatter#Format_specification](https://en.cppreference.com/w/cpp/chrono/system_clock/formatter#Format_specification)
So in your case row 71. Calendar symbol should be moved outside of brackets. Something like
```json
        "format": "{:%F %T}",
```

**Comment by LukashonakV** [comment]
Please close the issue if it helps
