### ISSUE TITLE
Add support for multiple bar's with the same file

### ISSUE THREAD

**Issue by thepenguinthatwants** [Alexays/Waybar#267]
When I used polybar I've gotten used to having a bar in bottom and a bar on top. Is it possible with Waybar?

Wondering if its already achievable by now? If so how?

**Comment by Difrex** [comment]
Just use a different config for each bar.
It working.
![2019-04-15_16-49-47](https://user-images.githubusercontent.com/3982213/56138038-b05f0700-5f9e-11e9-81d6-3c043a1c7e18.png)

**Comment by Alexays** [comment]
You can also use a single file, look at #147 :)

**Comment by thepenguinthatwants** [comment]
Thanks I guess I almost understand how it should work.

For some reasons I get only 1 waybar and the bottom one doesnt show. Or does it need another value as layer?

```
[{
    "layer": "top", // Waybar at top layer
 "position": "top", // Waybar position (top|bottom|left|right)
    "modules-left": ["sway/workspaces", "sway/mode"],
    "sway/workspaces": {
        "disable-scroll": true,
        "all-outputs": true,
        "format": " {icon} ",
        "format-icons": {
            "focused": "f",
            "default": "i"
        }
   }
},

{
    "layer": "top", // Waybar at top layer
   "position": "bottom", // Waybar position (top|bottom|left|right)
    "modules-right": [  "pulseaudio"],
    "pulseaudio": {
        "scroll-step": 5,
        "format": "{volume}% {icon}",
        "format-bluetooth": "{volume}% {icon}",
        "format-muted": "",
        "format-icons": {
            "headphones": "",
            "handsfree": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        },
        "on-click": "pavucontrol"
    }
}]
```

**Comment by Alexays** [comment]
@thepenguinthatwants Oh yeah if you want multiple bar on same screen without screen restriction, atm you need to launch multiple waybar process, i'll add the feature asap :)

**Comment by thepenguinthatwants** [comment]
Yeah I wanted multiple bar in the same screen. Only using this on my one screen laptop.

Cool!

**Comment by Alexays** [comment]
Done with 79a5e9ecee7fcb537e474071253c383ab82bf2e0

**Comment by thepenguinthatwants** [comment]
Cool!

So would it work just with my earlier example config? Or does it need something special to make it work?

**Comment by Alexays** [comment]
That's it!

**Comment by Th3Whit3Wolf** [comment]
This should be added to the wiki.

**Comment by thepenguinthatwants** [comment]
There is something strange after using top and bottom panel I cant see output in the panel.

```
set $Locker i3lock && sleep 1
set $mode_system (S)  | (L) 
mode "$mode_system" {
    bindsym l exec --no-startup-id $Locker, mode "default"
    bindsym s exec --no-startup-id systemctl poweroff -i, mode "default"  
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+Shift+e mode "$mode_system"

```

Normally I get output about these options in the panel. but after having two panels I cant get any visible output. I am using sway.
