### ISSUE TITLE
Question about hover on labels

### ISSUE THREAD

**Issue by Jeffser** [Alexays/Waybar#2682]
Hi, I was wondering how hover works on labels, I have this custom widget that shows what music I'm listening to

```JSONC
"custom/playerctl": {
        "interval": 1,
        "exec": "~/.config/waybar/scripts/playerctl.sh",
        "on-click": "playerctl play-pause",
        "on-scroll-up": "playerctl next",
        "on-scroll-down": "playerctl previous",
        "scroll-step": 10
},
```

and I wanted to add a style when the cursor hovers that widget like this

```CSS
#custom-playerctl:hover {
    background: white;
}
```

but it doesn't seem to work, is there a class that is applied to a widget when it is hovered?
thanks

**Comment by Alexays** [comment]
Fixed with https://github.com/Alexays/Waybar/pull/3145
