### ISSUE TITLE
Losing alternative format on Group module

### ISSUE THREAD

**Issue by ordy** [Alexays/Waybar#2685]
When I move a module like pulseaudio to a group, I can no longer left click on the icon to display the `format-alt` variant (right click still works as expected). However, I get it back if I set another copy anywhere on the waybar modules -left -center -right arrays.

With pusleaudio only part of the group:
![vid01](https://github.com/Alexays/Waybar/assets/22659443/ed1cee47-38c8-4c09-9cbf-3875cd6411e2)

And here clicks work when I have an extra instance of pusleaudio outside of the group module:
![vid02](https://github.com/Alexays/Waybar/assets/22659443/ea2f230d-c387-48d2-b7a9-019b4fc30575)

**Code:**

> pulseaudio

  ```json
      "pulseaudio": {
        "format": "{icon}",
        "format-alt": "{format_source}   {volume}%  {icon}", 
        "format-bluetooth": "<span font='11' rise='-800'>󰂰</span>", 
        "format-bluetooth-muted": "<span font='11' rise='-800'>󰂰</span>", 
        "format-muted": " {format_source}",
        "format-source": "{volume}%  <span font='11'>󰍰</span>",
        "format-source-muted": "<span font='11'>󰍱</span>",
        "format-icons": {
          "headphone": "<span font='11'>󰋋 </span>",
          "hands-free": "",
          "headset": "",
          "phone": "",
          "portable": "",
          "car": "",
          "default": [
            "<span font='12'>󰜟</span>"
          ]
        },
  ```

> group

  ```json
  "group/pulse-group": {
    "orientation": "inherit",
    "drawer": {
      "transition-duration": 300,
      "children-class": "drawer-child",
      "transition-left-to-right": false
    },
    "modules": [
      "pulseaudio",
      "pulseaudio/slider"
    ]
  },
  ```

Same results after testing with other modules that support `format-alt`.

**Comment by TheRialNiels** [comment]
I was going to ask if the format-alt was removed but you're right, when u added to a group module stop working.

I hope it can be fixed
