### ISSUE TITLE
button.active issues after update

### ISSUE THREAD

**Issue by Nocxium** [Alexays/Waybar#2689]
Im running waybar under Hyprland, and just did a upgrade, and for some reason button.active is acting up.
background-color etc is working fine, but not color.

#workspaces button.active {
    color: #00BFBC;
    border-color: #00BFBC;
    font-size: 18px;
}

Running
Waybar v0.9.24
Hyprland, built from branch  at commit v0.32.3  ().

**Comment by Soliprem** [comment]
Same. After the update I'm having issues with both that *and* the font

**Comment by Soliprem** [comment]
My issue was entirely fixed by fixing my font issue (Nerd Fonts changed naming from <name> Nerd Font to <name> NF. That broke a bunch of things on my end, incluing this

**Comment by Soliprem** [comment]
My issue was entirely fixed by fixing my font issue (Nerd Fonts changed naming from <name> Nerd Font to <name> NF. This originally broke a lot of stuff on my end, including OP's issue

**Comment by Nocxium** [comment]
Thanks for your response, but that doesn't seem to be my issue. My fonts are working fine and I recently tried removing persistent-workspaces, which makes the color come back. So button.active (specifically color) isnt working with persistent workspaces, but is working outside of it for some reason?

```
    "hyprland/workspaces": {
    //     "disable-scroll": true,
         "all-outputs": false,
         "format": "{icon}",
         "format-icons": {
         "active-only": false,
            "urgent": "",
            "active": "",
            "default": ""
         },
         "on-click":"activate",
         "persistent-workspaces": {
            // "*": 2
           "1": ["DVI-D-1", "HDMI-A-1", "eDP-1"],
           "2": ["DVI-D-1", "HDMI-A-1", "eDP-1"],
           "3": ["DVI-D-1", "HDMI-A-1", "eDP-1"],
           "4": ["DVI-D-1", "HDMI-A-1", "eDP-1"],
           "5": ["DVI-D-1", "HDMI-A-1", "eDP-1"]
         }

```
```
#workspaces {
/*    margin-top: 6px;*/
/*    margin-left: 12px;*/
/*    margin-bottom: 0px;*/
    border-radius: 10px;
    background: rgba(22, 19, 32,0.6);
    transition: none;
    font-size: 26px;
}

#workspaces button {
    transition: none;
    color: #5882AD;
    background: transparent;
    border-radius: 4px;
    border-left: 2px solid transparent;
    border-right: 2px solid transparent;
    padding:6px 16px 6px 12px;
}
#workspaces button:first-child{
/*    margin-left: 10px;*/
}
#workspaces button:last-child{
    padding-right: 18px;
}
#workspaces button.occupied {
    transition: none;
    color: #F28FAD;
    background: transparent;
    font-size: 4px;
}

#workspaces button.active {
    color: #A483B1;
    border-color: #A483B1;
}
#workspaces button.urgent {
    color: #FF7B89;
    border-color: #FF7B89;
}

#workspaces button:hover {
    transition: none;
    box-shadow: inherit;
    text-shadow: inherit;
    border-color: #D898D8;
    color: #D898D8;
}

#workspaces button.active:hover {
/*    color: #325379;*/
    border-color: #D898D8;
}

```

**Comment by Nocxium** [comment]
Alright, i was able to find a solution :) I had to restructure the code so button.persistent went above button.active, and also add button.empty inbetween. button.persistent color now holds the "busy" desktops color, while .empty holds the empty colors. I wonder when this change was implemented?

Anyways here is my relevant config if anyone else runs into the same problem:

```
#workspaces button.persistent {
    color: #00BFBC;
    font-size: 18px;
}

#workspaces button.empty {
    color: #3c485d;
}

#workspaces button.active {
    color: #00BFBC;
    border-color: #00BFBC;
    font-size: 18px;
}

```
