### ISSUE TITLE
Exception: Icon 'state-ok' not present in theme (null)

### ISSUE THREAD

**Issue by hughwilliams94** [Alexays/Waybar#269]
I am getting this issue when the Nextcloud Desktop Sync client is running in the tray. The icon state-ok.svg is present in the theme that I am currently using (/usr/share/icons/breeze-dark/status/22/state-ok.svg. More generally the icons in Waybar's tray do not seem to be respecting my set theme (Breeze Dark). Where is Waybar taking its theme settings from?
![image](https://user-images.githubusercontent.com/15379654/56229461-ddc8b500-6071-11e9-9d08-22d1d54ae5fa.png)

**Comment by Alexays** [comment]
Fixed with aeaa1927d958ecfd3510ddedecb511a59fdbd111

**Comment by hughwilliams94** [comment]
I am currently running `Waybar v0.5.1-15-g9564adb (Apr 17 2019, branch 'master')` and this issue does not appear to be resolved.

**Comment by Alexays** [comment]
Can you check with latest commit 6d6df4be0013b6632a18d78a21174c7a71d80ecb ?

**Comment by hughwilliams94** [comment]
No luck I am afraid, same error is shown with the latest build.

**Comment by Alexays** [comment]
Ok that's because my check was useless, must be good now with 29d8f365f81273b7ad6fcc6af41ca2cd7c579044, can you check? :)

**Comment by svalo** [comment]
I think I'm affected by this.

OS: Archlinux updated
Waybar: r968.b719569-1 or 0.9.0-2
Sway: 1:1.4-7

Excerpt from logs:

```
[2020-02-08 11:39:08.959] [error] Item 'Nextcloud': Icon 'state-sync' not present in theme Breeze
[2020-02-08 11:39:08.997] [error] Item 'Nextcloud': Icon 'state-ok' not present in theme Breeze
```
I tried also changing the gtk theme via gsettings and got

```
[2020-02-08 11:47:05.491] [error] Item 'Nextcloud': Icon 'state-ok' not present in theme 
[2020-02-08 11:47:09.849] [error] Item 'Nextcloud': Icon 'state-sync' not present in theme 
```

How can I be of help?

**Comment by svalo** [comment]
It is now working. It started working after I started a KDE Plasma session but I'm not sure if it is actually related

**Comment by hughwilliams94** [comment]
I found that no matter how I edited the gtk config files by hand the only way to get them to really take effect was setting them in KDE. Weird and pretty inconvenient, I think it comes from there being so many GTK config files in some many disparate places. I have no idea which to edit and what to put in each.
