### ISSUE TITLE
constant crashing from hyprland window module

### ISSUE THREAD

**Issue by Hellzbellz123** [Alexays/Waybar#2693]
i use hyprland git, and the last few days waybar has been crashing for me pretty randomly

the issue i am getting is this
[2023-11-25 19:55:21.419] [error] Hyprland IPC: Couldn't write (4)
waybar: ../waybar-git/src/modules/hyprland/window.cpp:138: void waybar::modules::hyprland::Window::queryActiveWorkspace(): Assertion `clients.isArray()' failed.

Waybar v0.9.24-30-g061c68ce (branch 'master')
Hyprland, built from branch main at commit 646f4bc63861e03b01fed3833bb65d1d014e1bf3 dirty (general: add workspace gaps (3877)).
Tag: v0.32.3-40-g646f4bc6

**Comment by DreamMaoMao** [comment]
https://github.com/Alexays/Waybar/pull/2789

I think this problem should be the same problem as this one, trying to read data being written by another asynchronous thread

**Comment by DreamMaoMao** [comment]
https://github.com/Alexays/Waybar/pull/2789

I believe they are the same problem

The original thread lock seems to have some problems, I will try to use shared_lock to fix
