### ISSUE TITLE
Clock module locale problem

### ISSUE THREAD

**Issue by jlaunay** [Alexays/Waybar#2694]
Since the recent commits, I can no longer display the days and months in French.

Here is a basic example

```json
{
    "layer": "top",
    "position": "bottom",
    "output": "DP-1",
    "height":"25",
    "spacing": "4",
    "modules-center":["clock"],

    "clock": {
        "format": "{:%A, %B %d, %Y (%R)}",
        "locale":"fr_FR.utf8",
        "interval": 1
    }
}
```
Giving
![image](https://github.com/Alexays/Waybar/assets/1137028/4521cc41-87e6-4b1a-811d-0384e8d1ddaf)

**Comment by jlaunay** [comment]
I've also tried with "timezone" but it doesn't make any difference either.

**Comment by LukashonakV** [comment]
Hi @jlaunay and @sakarie9 , due to under C++20 now is used base STD API (means standard library) according specification: [Format_specification](https://en.cppreference.com/w/cpp/chrono/system_clock/formatter#Format_specification) 
> The locale used for formatting is determined as follows:
>
>    the default "C" locale if L is not present in the format specification,
>    otherwise, the locale denoted by the [std::locale](https://en.cppreference.com/w/cpp/locale/locale) passed to the formatting function, if any,
>    otherwise (L is present but no [std::locale](https://en.cppreference.com/w/cpp/locale/locale) is passed to the formatting function), the global locale.

So please try to change a little bit you format string. For example:
```json
{
    "layer": "top",
    "position": "bottom",
    "output": "DP-1",
    "height":"25",
    "spacing": "4",
    "modules-center":["clock"],

    "clock": {
        "format": "{:L%A, %B %d, %Y (%R)}",
        "locale":"fr_FR.utf8",
        "interval": 1
    }
}
```
or

```json
"clock": {
    "interval": 1,
    "timezone": "Asia/Shanghai",
    "locale": "zh_CN.UTF-8",
    "format": "   {:L%m-%d %A %H:%M:%S}",
  },
```

**Comment by sakarie9** [comment]
>     "format": "   {:L%m-%d %A %H:%M:%S}",

This indeed solves my problem! BTW I believe it should be documented in the wiki

**Comment by jlaunay** [comment]
> Hi @jlaunay and @sakarie9 , due to with C++20 now is used base STD API (means standard library) according specification: [Format_specification](https://en.cppreference.com/w/cpp/chrono/system_clock/formatter#Format_specification)
> 
> > The locale used for formatting is determined as follows:
> > the default "C" locale if L is not present in the format specification,
> > otherwise, the locale denoted by the [std::locale](https://en.cppreference.com/w/cpp/locale/locale) passed to the formatting function, if any,
> > otherwise (L is present but no [std::locale](https://en.cppreference.com/w/cpp/locale/locale) is passed to the formatting function), the global locale.
> 
> So please try to change a little bit you format string. For example:

Problem solved for me too, I hadn't seen anything about it in the wiki.
Thanks !
