### ISSUE TITLE
spotify icon not showing on tray

### ISSUE THREAD

**Issue by ssamin69** [Alexays/Waybar#2698]
Spotify icon is not showing up on tray there is just a blank space 

![image](https://github.com/Alexays/Waybar/assets/72408262/c3f1c932-3091-49a0-9666-f5e25b825dcf)
![image](https://github.com/Alexays/Waybar/assets/72408262/ede13a55-d340-4d5a-b3aa-fec914a4db47)
tray config,
![image](https://github.com/Alexays/Waybar/assets/72408262/9558fb5b-c799-453a-b168-d56204c0dbc0)

**Comment by retubo** [comment]
I have the same problem. Did anyone find the solution?

**Comment by ssamin69** [comment]
> I have the same problem. Did anyone find the solution?

nope :(

**Comment by retubo** [comment]
Guys I found it! I was reading this thread and there was the solution. https://github.com/prasanthrangan/hyprdots/issues/856 

So what is happening is that if u have spotify without this option it will become a normal icon, if u want to have it in the tray u have to check this option in spotify config:
![image](https://github.com/Alexays/Waybar/assets/100074173/02a963b3-956f-4ac3-bdc7-8a80cc557323)

(the close button should minimize app instead of closing one)

**Comment by ssamin69** [comment]
> Guys I found it! I was reading this thread and there was the solution. [prasanthrangan/hyprdots#856](https://github.com/prasanthrangan/hyprdots/issues/856)
> 
> So what is happening is that if u have spotify without this option it will become a normal icon, if u want to have it in the tray u have to check this option in spotify config: ![image](https://private-user-images.githubusercontent.com/100074173/304908879-02a963b3-956f-4ac3-bdc7-8a80cc557323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjAwNzMsIm5iZiI6MTcwODQ1OTc3MywicGF0aCI6Ii8xMDAwNzQxNzMvMzA0OTA4ODc5LTAyYTk2M2IzLTk1NmYtNGFjMy1iZGM3LThhODBjYzU1NzMyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQyMDA5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTZlMzA4YTc2Y2NjNjI0MGY3OTliYWQ1OTIyMTJkZDA1ZjA0OWRiODEzMzYzZDlhODg2NGIzNjM1NDIyNTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gQe_s5iOdx0ZuCUWXjyhH2N5mQGA3LiQEJnzrHbghHY)
> 
> (the close button should minimize app instead of closing one)

thanks dude

**Comment by victorballester7** [comment]
You can also activate the option

`show-passive-items`

in the tray configuration:

```
  // System tray
  "tray": {
    "icon-size": 21,
    "spacing": 10,
    "show-passive-items": true
  },
```

**Comment by Chavamora** [comment]
> Guys I found it! I was reading this thread and there was the solution. [prasanthrangan/hyprdots#856](https://github.com/prasanthrangan/hyprdots/issues/856)
> 
> So what is happening is that if u have spotify without this option it will become a normal icon, if u want to have it in the tray u have to check this option in spotify config: ![image](https://github.com/Alexays/Waybar/assets/100074173/02a963b3-956f-4ac3-bdc7-8a80cc557323)
> 
> (the close button should minimize app instead of closing one)

what are you using for your screenshots? It looks nice

**Comment by retubo** [comment]
> > Guys I found it! I was reading this thread and there was the solution. [prasanthrangan/hyprdots#856](https://github.com/prasanthrangan/hyprdots/issues/856)
> > 
> > So what is happening is that if u have spotify without this option it will become a normal icon, if u want to have it in the tray u have to check this option in spotify config: ![image](https://github.com/Alexays/Waybar/assets/100074173/02a963b3-956f-4ac3-bdc7-8a80cc557323)
> > 
> > (the close button should minimize app instead of closing one)
> 
> what are you using for your screenshots? It looks nice

Hello!
Im using an script from imagemagick. 
I got it from the dotfiles of @linuxmobile. I just changed the color and my name on it
