### ISSUE TITLE
CSS transform property

### ISSUE THREAD

**Issue by ReekyMarko** [Alexays/Waybar#270]
Would it be possible to add support for the transform property in style.css? This would allow quite a bit more customization

**Comment by Alexays** [comment]
Waybar depends on gtk for that, so it's up to gtk to implement it

**Comment by chzzzh** [comment]
It crashes on `transform: rotate(90deg);`

**Comment by OBLIXi-ON** [comment]
Did you find any solution yet?

**Comment by nahuelDev23** [comment]
Did you find any solution yet?
