### ISSUE TITLE
window-rewrite missing firefox icon upon boot (hyprland/workspaces module)

### ISSUE THREAD

**Issue by Masber** [Alexays/Waybar#2718]
Hi, I am using waybar with hyprland, my issue is waybar is inconsistent in rendering the workspaces icons upon login. I have to kill and start warbar again in order to restore the missing icons.

hyprland instructions to start the apps:

```
exec-once=waybar & hyprpaper
exec-once=[workspace 1 silent] alacritty
exec-once=[workspace 2 silent] thunderbird & slack
exec-once=[workspace 3 silent] firefox
```

waybar hyprland/workspaces config

```
    "hyprland/workspaces": {
	"format": " <b>{icon}</b> {windows} ",
	"window-rewrite-default": "",
	"window-rewrite": {
	  "firefox": "󰈹",
	  "Alacritty": "󰞷",
	  "slack": "󰒱",
	  "thunderbird": "󰇮",
	  "spotify": "󰓇"
	},
        "on-scroll-up": "hyprctl dispatch workspace e+1",
        "on-scroll-down": "hyprctl dispatch workspace e-1",
        "on-click": "activate"
    },
    "hyprland/window": {
        "format": "{}",
    	"rewrite": {
        	"(.*) — Mozilla Firefox": "󰈹 $1",
        	"(.*) — Mozilla Thunderbird": "󰇮 $1",
        	"Alacritty": "󰞷 Alacritty",
        	"(.*) - Slack": "󰒱 $1",
	}
    },
```

These are how the workspaces looks like after boot

![20231203_13h02m59s_grim](https://github.com/Alexays/Waybar/assets/722064/b66e0440-97e4-4152-9bcd-29c2d616aaac)

and this after restart waybar `$ killall waybar ; waybar &`

![20231203_13h06m09s_grim](https://github.com/Alexays/Waybar/assets/722064/45903f90-d458-49e7-94b0-5203280908ed)

As you can see both the firefox and the terminal icons are missing even tho both apps are running

Any idea of what could happen?

thank you

**Comment by khaneliman** [comment]
Yeah, this has been an issue since the features creation and I keep wanting to take a stab at it when I have time... I basically just always do a systemctl --user restart waybar after login, for the time being. But, would rather it not be needed, obviously.

**Comment by Masber** [comment]
no problem, I understand this is pending issue, I can try your workaround, that is not a problem.

thank you very much for your help and waybar is very cool :)
