### ISSUE TITLE
[river/tags] only show tags with at least one window

### ISSUE THREAD

**Issue by tgy** [Alexays/Waybar#2721]
First of all, thanks for this awesome project! :)

I'm using `river/tags` to show the different tags / workspaces in river.

It seems that I can only show them all (I have 10).

Is there any way I can reproduce the behaviour I've been used to in Hyprland / i3 / Sway which is to only show workspaces (tags) that have at least one window?

Thanks!

**Comment by old-pronx** [comment]
This might be overkill, but I was able to do this by adding this to style.css

```
#tags button:not(.occupied):not(.focused) {
	font-size: 0;
	min-width: 0;
	min-height: 0;
	margin: -17px;
	padding: 0;
	border: 0;
	opacity: 0;
	box-shadow: none;
	background-color: transparent;
}
```

**Comment by tgy** [comment]
thanks a lot @old-pronx i've tried it and it works great :)
