### ISSUE TITLE
privacy: add support for vertical orientation

### ISSUE THREAD

**Issue by BluewyDiamond** [Alexays/Waybar#2729]
The privacy module isn't designed for vertical use, so it's not ideal for a vertical bar, even though it's useful.

**Comment by BluewyNetwork** [comment]
https://github.com/Alexays/Waybar/issues/2657

I didn't mean to duplicate the issue but I can't delete this one so I just closed it.

but basically what I did is to create multiple instance of the privacy module, one for screen share and so on
