### ISSUE TITLE
[clock] tooltip background transparency

### ISSUE THREAD

**Issue by Doomer-Cat** [Alexays/Waybar#2737]
Things I've tried:
1.  
```css
tooltip,
#clock.calendar,
#clock tooltip,
#clock > tooltip,
#clock {
    background: rgba(29, 32, 33, 0.75);
}
```
   
3. config: (rgba too)
 ```
<span background='#1d2021c0'><big>{:%d %B %Y}</big>\n<tt><small>{calendar}</small></tt></span>
```

![waybar_clock_calendar_issue_1](https://github.com/Alexays/Waybar/assets/81427193/c3c76e97-be0b-4237-b17e-246e74942e68)

**Comment by Doomer-Cat** [comment]
not sure but it looks like alpha isn't used correctly either

**Comment by mutoroglin** [comment]
I successfully use transprency on my tooltips, here is what I do in 'style.css':
'tooltip {
    background: rgba(204, 34, 0, 0.6);
}'

Your question made me curious and I checked your configuration to understand where transparency breaks, here is what I figured out:
 * '#clock tooltip' doesn't work on my system either
 * your inline css within the span does set the background color on the tooltip only for the text
 * I checked the CSS tree with 'env GTK_DEBUG=interactive waybar' but couldn't find an element tooltip subordinated to the modules

Hope this helps you at least a bit further.....

**Comment by T-D3V** [comment]
> I successfully use transprency on my tooltips, here is what I do in `style.css`: `tooltip { background: rgba(204, 34, 0, 0.6); } `
> 
> Your question made me curious and I checked your configuration to understand where transparency breaks, here is what I figured out:
> 
> * '#clock tooltip' doesn't work on my system either
> * your inline css within the span does set the background color on the tooltip only for the text
> * I checked the CSS tree with `env GTK_DEBUG=interactive waybar` but couldn't find an element tooltip subordinated to the modules
> 
> Hope this helps you at least a bit further.....

You single-handedly saved me, my GTK theme was screwing up my waybar too but thanks to the GTK_DEBUG env I now found out I need to set background initial on widgets inside waybar to fix it I thank you for this information, and it should be mentioned somewhere in the docs of waybar.

**Comment by Doomer-Cat** [comment]
> I successfully use transprency on my tooltips, here is what I do in `style.css`: `tooltip { background: rgba(204, 34, 0, 0.6); } `
> 
> Your question made me curious and I checked your configuration to understand where transparency breaks, here is what I figured out:
> 
> * '#clock tooltip' doesn't work on my system either
> * your inline css within the span does set the background color on the tooltip only for the text
> * I checked the CSS tree with `env GTK_DEBUG=interactive waybar` but couldn't find an element tooltip subordinated to the modules
> 
> Hope this helps you at least a bit further.....

sadly setting the background for all tooltips doesn't work for me 

i also tried `tooltip#clock` thinking that might work but didnt

**Comment by Doomer-Cat** [comment]
using `opacity` does work but with it being applied to text too sadly
```css
tooltip {
    opacity: 0.75;
}
```

**Comment by Doomer-Cat** [comment]
I finally figured it out 

So it was just the gtk theme setting it     (why didn't i look into the theme files?)

```css
tooltip * {
	background:	transparent;
}

tooltip.background {
	background:	rgba(29,32,33,0.8);
}
```


I achieved what i wanted, but i don't know how to change background-color indiviually for each module. 
So I changed the title. Please tell if anyone knows

**Comment by CodeByMeow** [comment]
> I finally figured it out
> 
> So it was just the set gtk theme setting it (why didn't i look into the theme files?)
> 
> ```css
> tooltip * {
> 	background:	transparent;
> }
> 
> tooltip.background {
> 	background:	rgba(29,32,33,0.8);
> }
> ```
> 
> I achieved what i wanted, but i don't know how to change background-color indiviually for each module. So I changed the title. Please tell if anyone knows

It worked!

**Comment by TollerNamen** [comment]
Thank you!
