### ISSUE TITLE
Bluetooth is showing no-controller instead of hiding the module

### ISSUE THREAD

**Issue by mylinuxforwork** [Alexays/Waybar#2748]
I'm not able to hide the module Bluetooth even if no controller is installed. It always shows no-controller. 
Is there a way to hide the module completely if no controller is installed/available in the system?

This is my module configuration:

```
    // Bluetooth
    "bluetooth": {
        "format": " {status}",
        "format-disabled": "",
        "format-off": "",
        "interval": 30,
        "on-click": "blueman-manager"
    },
```

And my style.css

```
#bluetooth, #bluetooth.on, #bluetooth.connected {
    background-color: @backgroundlight;
    font-size: 16px;
    color: @textcolor2;
    border-radius: 15px;
    padding: 2px 10px 0px 10px;
    margin: 5px 15px 5px 0px;
    opacity:0.8;
}

#bluetooth.off {
    background-color: transparent;
    padding: 0px;
    margin: 0px;
}
```

![image](https://github.com/Alexays/Waybar/assets/145253254/003eb2cf-5e58-49e2-a4d6-3ac04c516480)

**Comment by ArttX** [comment]
I do not know if you already found solution, but you can add `format-no-controller: ""` to hide icon, if there is not controller.

**Comment by mylinuxforwork** [comment]
Awesome. Thank you so much for your feedback. It worked very well.
