### ISSUE TITLE
Crash when detaching monitors

### ISSUE THREAD

**Issue by HarHarLinks** [Alexays/Waybar#2750]
My laptop is connected to 2 external DP-daisychained displays through a single USB-C connection. The directly connected monitor is the P27h-10.

My config is in 2 parts: one for the internal laptop display (`"output": "eDP-1"`)  and one for everything else (`"output": "!eDP-1"`).

Sometimes, as I (dis)connect the USB-C, waybar crashes. I managed to capture the following log using `waybar -l debug &> /tmp/waybar.log`.

```
179888   │ [2023-12-15 13:50:36.906] [debug] Output removed: Lenovo Group Limited LEN 
        │ P27h-10
179889   │ [2023-12-15 13:50:36.907] [debug] Output removed: ASUSTek COMPUTER INC ROG 
        │ XG279Q
179890   │ [2023-12-15 13:50:36.921] [info] Bar removed from output: DP-3
179891   │ [2023-12-15 13:50:36.936] [info] Bar removed from output: DP-4
179892   │ Gdk-Message: 13:50:36.942: Error 71 (Protocol error) dispatching to Wayland
        │  display.
```

Relatedly, it crashes about as frequently (or infrequently, but it keeps happening now and then) when closing the laptop to suspend it.

**Comment by Alexays** [comment]
Might be fixed with https://github.com/Alexays/Waybar/pull/3215
