### ISSUE TITLE
Active Window Class

### ISSUE THREAD

**Issue by Kakashiiiiy** [Alexays/Waybar#276]
Hey,
I have 2 monitors and it's good to know which workspace is active on which monitor (even if the Monitor ist not focused) so is there an option like **active_workspace** in swaybar?
I tried it with: 
`#workspaces button.active {
    background: rgba(34,139,34, 0.5);
}` 
But it seems that it does not work.

**Comment by Alexays** [comment]
Is the `visible` class resolve your issue?

**Comment by Kakashiiiiy** [comment]
Yes it solved it thank you. But for those who are reading this make sure you define `focused` after `visible` in style.css otherwise it gets somehow overwritten at least with my config.

**Comment by SethBarberee** [comment]
@Kakashiiiiy I would recommend editing the wiki to add this also for people viewing it later

**Comment by Kakashiiiiy** [comment]
Well my english is not the best and there is no "good" section where I could add this. @SethBarberee
