### ISSUE TITLE
Waybar using a subset of CSS?

### ISSUE THREAD

**Issue by linkert** [Alexays/Waybar#2761]
Sorry if this has been beaten to death on numerous occations - did not find a clear answer when searching.

Stuff like ```height``` and ```outline``` either crashes waybar (height) or does nothing (outline). I'm looking to utilize outlines in order to match the style of my hyprland style.

Thanks for any insight!

**Comment by mihokei** [comment]
As far as I know gtk3 subset:
https://docs.gtk.org/gtk3/css-overview.html

**Comment by RobertMueller2** [comment]
The answer to your question is "yes" ;)

Applying CSS to Waybar elements is done with [GTK](https://docs.gtk.org/gtk3/css-properties.html). I would expect everything to work which is supported by GTK 3.

`height` is not in the list of those properties.

As for `outline`, the doc says this: "GTK uses the CSS outline properties to render the ‘focus rectangle’.", but from reading it I am not sure if that refers just to the `-gtk-outline-radius` property, or all of them. Whether a focus rectangle is rendered is determined with [`has_visible_focus`](https://docs.gtk.org/gtk3/method.Widget.has_visible_focus.html). Quick look at the source says we don't set it, and I don't know if it'd be practical to do so.

Can you provide a screenshot of your hyprland style? Maybe somebody has other ideas how to match it.

**Comment by keithbowes** [comment]
I use outline in [my fork of the Mist theme](https://github.com/keithbowes/gtk-theme-mist) and it works fine.  I do wish `max-width`, `width`, and/or `overflow` were supported so that I could get the taskbar to not be wider than my screen.  It would be interesting if GTK did support `overflow`; it might make the GtkScrolledWindow widget redundant.
