### ISSUE TITLE
Automatic script call on event

### ISSUE THREAD

**Issue by jbirnick** [Alexays/Waybar#2779]
I'm using a `custom` module with the `interval` option. That is, my script is called regularly every few seconds.
In addition, I set commands for `on-click` and the other events.

Now, the problem is, my script will get called immediately after the event got executed. (Note, I do _not_ use a signal to get this behavior, it happens automatically.)

This is nowhere documented. In the [documentation](https://github.com/Alexays/Waybar/wiki/Module:-Custom) it rather says one should use the `signal` property to get such behavior. In particular, many examples there show something like
```
...
"on-click": "termite -e 'sudo pacman -Syu'; pkill -SIGRTMIN+8 waybar", // update system
...
```
which is completely redundant because as I said the script gets called automatically after events happened.

How to prevent these calls from happening automatically?

**Comment by manfred3000** [comment]
Add `"exec-on-event": false` to the module.
If you have `manpage` support, see `man 5 waybar-custom`...

**Comment by jbirnick** [comment]
Oh thanks, I interpreted this option differently when I read about it!
