### ISSUE TITLE
Window-rewrite rules are ignored when moving windows across monitors

### ISSUE THREAD

**Issue by aegagros** [Alexays/Waybar#2780]
Hello,

I have noticed the following on hyprland (haven't tested on sway or other wm); when moving windows across workspaces of the same monitor, window rules are respected and icons are rendered properly as expected. However, if I move a window to a workspace of another monitor, the icons are not rendered there (neither the default icon is rendered). If I restart waybar, icons are rendered properly.

My versions are the following:
- Waybar v0.9.24
- Hyprland v0.33.1

Let me know if you need more info to reproduce.

Other than that, congrats on a great toolbar; I have been using it (both on sway and hyprland) for several years.

**Comment by Syndelis** [comment]
Hi there @aegagros ! Could you please try PR #2780 and see if it resolves the issue for you?

**Comment by aegagros** [comment]
Hi, you probably mean #2817 right?

**Comment by Syndelis** [comment]
Yes! Sorry, got the links mixed up

**Comment by khaneliman** [comment]
This was resolved with me on https://github.com/Alexays/Waybar/pull/2817. If it's resolved for you, just close this whenever you get a chance.

**Comment by aegagros** [comment]
Yes; with a quick test I confirm that #2817 has fixed this issue. Thanks
