### ISSUE TITLE
Compilation fails after requiring a missing fmt/chrono.h

### ISSUE THREAD

**Issue by Kunagi7** [Alexays/Waybar#279]
The fmt.wrap file included at the subprojects folder is requiring the 5.2.1 version of the fmt library which doesn't include the chrono header support. This causes the build to fail:
```
../src/modules/mpd.cpp:3:10: fatal error: fmt/chrono.h: No such file or directory
 #include <fmt/chrono.h>
```

The correct version should be >=5.3.0. This version included the experimental chrono support:
https://github.com/fmtlib/fmt/releases/tag/5.3.0

Updated wrap file:
https://wrapdb.mesonbuild.com/v1/projects/fmt/5.3.0/1/get_wrap

**Comment by Alexays** [comment]
Updated with 0d0f5ed7db16e13ff96361f56faaa0dc7f4e95e9
