### ISSUE TITLE
Battery module not working 

### ISSUE THREAD

**Issue by rudy-in** [Alexays/Waybar#2795]
so i just made the waybar and added the battery module and the battery module it just doesn't show up on the waybar i checked a 100 times still thinking what is wrong with it

**Comment by apiraino** [comment]
The battery module works just fine here. Can you please post here a minimal configuration to reproduce your config? Also try running `waybar -l debug`, it should show more debug info.

**Comment by rudy-in** [comment]
the issue was solved i actually prepared a script that shows the batter module on the waybar so that it works for everybody else who use endeavouros

**Comment by apiraino** [comment]
nice. then feel free to close this issue.
