### ISSUE TITLE
Waybar height depends on font size, is blown up when emoji are present

### ISSUE THREAD

**Issue by NHOrus** [Alexays/Waybar#2819]
![20240109_08h03m54s_grim](https://github.com/Alexays/Waybar/assets/5390835/026ead18-4e6f-4eba-8514-d72270ba8573)

**Comment by NHOrus** [comment]
Problem caused by my awful combination of fontconfig templates.

**Comment by winteriscariot** [comment]
> Problem caused by my awful combination of fontconfig templates.

can you post your solution here? i'm attempting to get noto-color-emoji to function but adding the default fontconfig makes the emoji huge, like your issue here.

thanks!

**Comment by winteriscariot** [comment]
the solution here is to ensure that `10-scale-bitmap-fonts` is enabled:

`ln -s /usr/share/fontconfig/conf.default/10-scale-bitmap-fonts.conf ~/.config/fontconfig/conf.d/`

**Comment by Spixmaster** [comment]
The solution is mentioned in the [wiki](https://wiki.archlinux.org/title/Fonts#Emoji_and_symbols). [Bitmap font downscaling](https://wiki.archlinux.org/title/Font_configuration#Disable_scaling_of_bitmap_fonts) is indeed needed. However, I also needed a reboot.

1. `ln -s /usr/share/fontconfig/conf.avail/10-scale-bitmap-fonts.conf /etc/fonts/conf.d/`
2. `reboot`
