### ISSUE TITLE
Waybar Only Showing Certain Icons

### ISSUE THREAD

**Issue by RandomCoder982** [Alexays/Waybar#2822]
This is my first time posting on an online forum so sorry if I don't follow certain conventions.

This is my waybar config: https://pastebin.com/uLw8BYsL
And this is the output: 
![20240110_00h02m25s_grim](https://github.com/Alexays/Waybar/assets/121013355/0a95a373-9a6c-47c4-8082-2a228972bbb3)

Yet when I run this waybar config where I put the group at the top and removed the test line: https://pastebin.com/LK7knADd
I got this output instead: 
![20240110_00h06m55s_grim](https://github.com/Alexays/Waybar/assets/121013355/fa69b3e7-5923-451a-a24b-265ef9e0fb47)

Thank you in advanced for anyone who manages to figure this out, it's been bugging me for a while

Edited: Accidentally put the same file twice

**Comment by jramrath** [comment]
I have no idea what that `test` thing is about but looking at the second config file, you seem to have an extra `}` on line `84` just after `on-click ...` in `hyprland/workspaces`.

With the first config file, waybar didn't know what to do with everything in `test`, so it just skipped it.
In the second config file you removed `test` but left the closing bracket. Everything after that didn't get loaded.

I'm kind of surprised all that didn't throw an error.

**Comment by RandomCoder982** [comment]
Thanks, I can't test it out right now because I'm on windows but it seems like the most likely reason why.
