### ISSUE TITLE
Tab in tooltip is not aligned properly in bluetooth module

### ISSUE THREAD

**Issue by fritzrehde** [Alexays/Waybar#2823]
I noticed that for the built-in bluetooth module, the tooltip does not properly format the table, even though I used tab characters. See screenshot:
![20240110_10h56m34s_grim](https://github.com/Alexays/Waybar/assets/80471265/3722162a-41d1-43c1-8eb6-698e345c5f0c)
Here, I would expect the text to be aligned like:
```
2 connected
Fritz's Bose QC35   20%
M720 Triathlon      100%
```
or similar. Basically, I am asking whether [elastic tabstops](https://nick-gravgaard.com/elastic-tabstops/) are supported for this text. If not, it might be a cool feature to add to enhance the UI.

**Comment by mahaveergurjar** [comment]
You need to remove /t to fix this issue 
```
"tooltip-format-enumerate-connected-battery": "{device_alias} /t {device_battery_percentage}%"
    },
``` 
You can use these for -> , // for differentiate 
```
"tooltip-format-enumerate-connected-battery": "{device_alias} -> {device_battery_percentage}%"
    },
``` 
![240123_20h34m48s_screenshot](https://github.com/Alexays/Waybar/assets/57872034/2f49cd77-1a61-4b02-8a77-6f16d0102e24)
![240123_20h35m50s_screenshot](https://github.com/Alexays/Waybar/assets/57872034/78c9a3dd-6d92-49fb-aef2-806bf607381c)
