### ISSUE TITLE
Feature: Can we have capitalized version for `%p` in clock?

### ISSUE THREAD

**Issue by azzamsa** [Alexays/Waybar#2824]
Hi, 👋.

Feature: Can we have a capitalized version for `%p` in clock?

So instead of "08:10 am", I would like to have "08:10 AM".

I tried to capitalize in the CSS part, but Waybar doesn't support it.

Thank you so much for Waybar! 🍦

**Comment by apiraino** [comment]
What does your clock format config look like? Waybar should format date and time using the `date` format strings (see `man 1 date`).

Though I notice something weird:
```
    "clock": {
        "format": "{:%H:%M:%S %p %P}",
    },
```

I see it rendered as if it doesn't interpret `%P` :thinking: 
![grafik](https://github.com/Alexays/Waybar/assets/6098822/7fd16d19-2e00-4df9-b44e-deb3b31071ec)

From the shell it works as expected:
```
$ date +'%H:%M %p %P'
16:00 PM pm
```

**Comment by azzamsa** [comment]
> (scratch my previous comment)
> 
> The [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Clock) explains which formatters are available. See this page [fmt.dev/latest/syntax.html#chrono-specs](https://fmt.dev/latest/syntax.html#chrono-specs)

I have visited that wiki multiple times and the Chono spec, but had no luck. Can you pin point which one fixes my issue?

**Comment by apiraino** [comment]
@azzamsa the linked documentation points has the formatter `%p` which you seem to already use and does what you're looking for (capitalized 12/24 hours, [here an example](https://godbolt.org/z/43W1n6WG7)).

Unsure why you see it not capitalized. Does it also reproduce without using a stylesheet and a minimal configuration like:
```
    "clock": {
        "format": "{:%R %p}",
    }
```

Which window manager are you using?

**Comment by azzamsa** [comment]
> the linked documentation has the formatter %p which you seem to already use and does what you're looking for (capitalized 12/24 hours, here an example).

Oh, I see.

> Unsure why you see it not capitalized. Does it also reproduce without using a stylesheet and a minimal configuration like:

I am using Hyperland.

However, I don't use it anymore. I will come back here if the issue persists when I happen to use Hyperland again.
