### ISSUE TITLE
Wrong week number in calendar widget

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [Alexays/Waybar#2827]
Hi, I just noticed that now in 2024 the week number reported in the Waybar calendar widget is wrong. We're now in week 2 according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), and this is what the widget shows:
![20240112_17h06m30s_grim](https://github.com/Alexays/Waybar/assets/101266837/83e1eb2e-e11a-420e-9ef7-18ffb39b4458)

This is my calendar configuration, I don't think it's a configuration issue:
```json
    "clock#date": {
        "format": "{:%F %a}",
        "smooth-scrolling-threshold": 4,
        "tooltip-format": "<span color='#35b9ab'><tt><small>{calendar}</small></tt></span>",
        "calendar": {
            "mode-mon-col"      : 4,
            "weeks-pos"         : "left",
            "on-scroll"         : 1,
            "on-click-right"    : "mode",
            "format": {
                "months":    "<span color='#35b9ab'><b>{}</b></span>",
                "weeks":    "<span color='#73ba25'><b>{}</b></span>",
                "weekdays": "<span color='#21a4df'><b>{}</b></span>",
                "today":    "<span color='#35b9ab' background='#173f4f'><b>{}</b></span>"
            }
        },
        "actions": {
            "on-click-right"    : "mode",
            "on-scroll-up"      : "shift_up",
            "on-scroll-down"    : "shift_down"
        },
        "tooltip": true
    },
```

**Comment by FilippoBonazziSUSE** [comment]
I immediately realised this could be a configuration issue, hold on

**Comment by FilippoBonazziSUSE** [comment]
Turns out this is a configuration issue. If you want your weeks to start on Mondays, the fine manual tells you to specifiy `{:%W]` in the calendar format `week` option:

```diff
--- a/.config/waybar/config
+++ b/.config/waybar/config
@@ -103,7 +103,7 @@             "on-scroll"         : 1,
             "on-click-right"    : "mode",
             "format": {
                 "months":    "<span color='#35b9ab'><b>{}</b></span>",
-                "weeks":    "<span color='#73ba25'><b>{:%W}</b></span>",
+                "weeks":    "<span color='#73ba25'><b>{}</b></span>",
                 "weekdays": "<span color='#21a4df'><b>{}</b></span>",
                 "today":    "<span color='#35b9ab' background='#173f4f'><b>{}</b></span>"
             }
```

Sorry for the noise.

However, how come the widget is able to show weekdays in the order Monday -> Sunday, but then defaults to Sunday -> Saturday for week numbers (see image in first comment)? Could a consistency check be added here?

**Comment by tjavdar** [comment]
# Suggestion: 

The  "weeks" formatting  in calendar, in addition to '{:%U}' and '{:%W}', should allow '{:%V}' tag. 

Formatting like the one below,

      "clock": {
          "format": "{:%a, %b %d, v.%V | %H:%M}",
          "calendar": {
               "locale": "sv_SE",
               "format": {
                    "weeks": "<span color='#99ffdd'><b>{:%V}</b></span>"
               }
           }
      }

is accepted as of waybar 0.10.4-2 (Arch), but the readout of %V in "format" in the bar and %V in "weeks" of the pop-up calendar differ by 1. 

All three format tags should  be conformant with the readout of shell commands:  `date +%U`, `date +%W` and `date +%V`.

**Comment by be-neth** [comment]
This is still an issue for me.
It is impossible to get valid Week number from calendar widget today.

({:%V} is supposed to be my configuration, but it does'nt work.)

I think we should re-open this issue.

**Comment by FilippoBonazziSUSE** [comment]
With the new year again I found my configuration to be broken. My configuration with `%W` mentioned above shows a week number of `00`. Indeed using `%V` obtains what I want (ISO week number).

The default behaviour of waybar is not the expected one, and this is not very well documented either. Hopefully this is the last adjustment I need to make.

**Comment by RadxaYuntian** [comment]
I'm also bitten by this off-by-one issue and messed up some schedules. I'm on NixOS with waybar 0.13.0, and setting %V does not seems to have an affect --- still getting this week as W28 with week starts on Sunday:

```
    "clock": {
      "actions": {
        "on-click-backward": "tz_down",
        "on-click-forward": "tz_up",
        "on-click-right": "mode",
        "on-scroll-down": "shift_down",
        "on-scroll-up": "shift_up"
      },
      "calendar": {
        "format": {
          "days": "<span color='#ecc6d9'><b>{}</b></span>",
          "months": "<span color='#ffead3'><b>{}</b></span>",
          "today": "<span color='#ff6699'><b><u>{}</u></b></span>",
          "weekdays": "<span color='#ffcc66'><b>{}</b></span>",
          "weeks": "<span color='#99ffdd'><b>W{:%V}</b></span>"
        },
        "weeks-pos": "left"
      },
      "format": "T{:%H\n :%M}",
      "interval": 1,
      "tooltip-format": "<tt><big>{calendar}</big></tt>"
    },
```

**Comment by FilippoBonazziSUSE** [comment]
I found out that setting the `locale` manually in the waybar config seems to fix this. Apparently the waybar clock module ignores the system locale.

I think this somehow has to do with the "weeks start on Monday or Sunday" setting, which apparently cannot be controlled directly and is tied to locale. I'm a bit puzzled by this, since I expected that using the  ISO week number (`%V`) would be enough (it is enough when used as a format option to GNU coreutils `date`). So I think there is actually a bug in the waybar clock module or the date library it is using (I didn't investigate deeper) w.r.t. computing the ISO week number.

Anyway, here's my workaround with the manual locale setting:
```json
"clock": {
        ...
        "locale": "en_DK.UTF-8",
        ...
    },
```

**Comment by RadxaYuntian** [comment]
Tried a few locales:

* `C.UTF-8` & `en_US.UTF-8`: wrong week number + week starts on Sunday
* `zh_CN.UTF-8`: correct week number + week starts on Monday, but the weekdays header is off position (I don't know how to screenshot this popup window)

EDIT: messed around with it and I got the internal rendered text in the log:
```
<tt><big><span color='#ecc6d9'><b><span color='#ffead3'><b>七月 2025                 </b></span>
<span color='#ffcc66'><b>           一 二 三 四 五 六 日</b></span>
<span color='#99ffdd'><b>W26</b></span>     1  2  3  4  5  6
<span color='#99ffdd'><b>W27</b></span>  7  8  9 10 11 12 13
<span color='#99ffdd'><b>W28</b></span> 14 <span color='#ff6699'><b><u>15</u></b></span> 16 17 18 19 20
<span color='#99ffdd'><b>W29</b></span> 21 22 23 24 25 26 27
<span color='#99ffdd'><b>W30</b></span> 28 29 30 31         </b></span></big></tt>
```

EDIT 2: switched to hardcoded weekdays:
```
weekdays = "<span color='#ffcc66'><b>    Mo Tu We Th Fr Sa Su</b></span>";
```
