### ISSUE TITLE
Custom module with infinite loop achieved by sleeping don't even show up

### ISSUE THREAD

**Issue by raffaem** [Alexays/Waybar#2844]
Take for example this custom module:
```
#!/usr/bin/env python
import datetime
import time

while True:
    print(f"{{\"text\":\"{datetime.datetime.now().isoformat()}\"}}")
    time.sleep(1)
```

with this config:
```
"custom/testdate": {
        "exec": "python $HOME/.config/waybar/scripts/testdate",
        "format": "{}",
        "return-type": "json"
},
```

The module doesn't even shows up.

It looks like achieving infinite loop by sleeping for some reasons doesn't work.

If you remove the outer loop "while True" from the module, and use pool every second with `interval: 1` in the config, then it works correctly.

**Comment by RobertMueller2** [comment]
Does this help? https://github.com/Alexays/Waybar/discussions/2358

**Comment by raffaem** [comment]
> Does this help? #2358

It does.

Thank you very much.

Will write in the wiki about it.
