### ISSUE TITLE
Hyprland workspace buttons can't remove padding

### ISSUE THREAD

**Issue by SaurabhHarwande** [Alexays/Waybar#2858]
#### Summary
The workspace module on my waybar seems to be occupying too much height. I have exclusively set the padding and margin to 0. And the only margins that I can see on css are applied are on the x-axis, which should not be affecting height. The code I am using for module config and styling is below. Module is within the left panel.

I want the buttons to be having zero padding within them.
#### Code
```
"hyprland/workspaces": {
        "disable-scroll": true,
        "all-outputs": true,
        "warp-on-scroll": false,
        "format": "{icon}X",
        "format-icons": {
            "urgent": "",
            "active": "",
            "default": ""
        }
    },
```
```
* {
    /* `otf-font-awesome` is required to be installed for icons */
    font-family: FontAwesome, Roboto, Helvetica, Arial, sans-serif;
    font-size: 9px;
    padding: 0;
    margin: 0;
}
#workspaces {
    background: #555555;
}
#workspaces button {
    margin-right: 2px;
    color: #ffffff;
    padding: 0;
    margin: 0;
}

#workspaces button:hover {
    background: rgba(0, 0, 0, 0.2);
}

#workspaces button.active {
    background-color: #64727D;
}

#workspaces button.urgent {
    background-color: #eb4d4b;
}

#window,
#workspaces {
    margin: 0 4px;
}

/* If workspaces is the leftmost module, omit left margin */
.modules-left > widget:first-child > #workspaces {
    margin-left: 0;
}

/* If workspaces is the rightmost module, omit right margin */
.modules-right > widget:last-child > #workspaces {
    margin-right: 0;
}
```
##### With hyprland workspaces module
![image](https://github.com/Alexays/Waybar/assets/19163339/d86b0de7-6204-43b9-9d38-3bba13e11e80)
##### Without hyprland workspaces module
![image](https://github.com/Alexays/Waybar/assets/19163339/4b4d24ec-2102-4034-80a4-acd9565eede3)

**Comment by jramrath** [comment]
Something from `hyprland/workspaces` might have a `min-height`. Try setting `* { min-height: 0; }` in your css.

If that doesn't work, you can look at the css properties with [`env GTK_DEBUG=interactive waybar`](https://github.com/Alexays/Waybar/wiki/Styling#interactive-styling).

**Comment by SaurabhHarwande** [comment]
@jramrath 
Thanks a lot that solve the issue for me we should be good to close this now.
