### ISSUE TITLE
Can not have only sway/window or tray module

### ISSUE THREAD

**Issue by skielred** [Alexays/Waybar#286]
If the only modules enabled are `tray` or `sway/window` or both, waybar crashes on launch (without printing information).

## How to reproduce

Working config file:
```javascript
{
  "modules-left": ["clock"]
}
```
Not working config files:
```javascript
{
  "modules-left": ["tray"]
}
```
```javascript
{
  "modules-left": ["sway/window"]
}
```
```javascript
{
  "modules-left": ["sway/window", "tray"]
}
```

## Waybar version:
`Waybar v (Mar  3 2019, branch '')`

## Use case:
I want 2 status bars, one at the top with only window title and tray icons, one at the bottom with status information (CPU, workspaces, time, ...)

For now I'll add a dummy module to the top bar to bypass this issue, but a proper fix would be welcomed.

**Comment by Alexays** [comment]
Are you on the version from git or from package manager?
Because this should be fixed in the upcoming release
