### ISSUE TITLE
[HELP] couldnt see workspaces number in waybar after update after long time, did something chnage related to that

### ISSUE THREAD

**Issue by HakaishinShwet** [Alexays/Waybar#2868]
{
    "layer": "top",
    "position": "top",
    "mod": "dock",
    "exclusive": true,
    "passthrough": false,
    "gtk-layer-shell": true,
    "height": 50,
    "modules-left": ["custom/launch_wofi","wlr/workspaces","cpu","memory","disk","hyprland/window"],
    "modules-center": ["custom/lock_screen","custom/updates","clock","custom/power_btn"],
    "modules-right": ["temperature","battery","backlight","pulseaudio","pulseaudio#microphone","tray","cava","custom/light_dark","network"],
    
    "hyprland/window": {
        "format": "{}"
    },

    "custom/launch_wofi": {
        "format": "HAKAI",
        "on-click": "pkill wofi; wofi -n",
        "tooltip": false
    },

    "custom/lock_screen": {
        "format": "",
        "on-click": "sh -c '(sleep 0.5s; swaylock)' & disown",
        "tooltip": false
    },

    "custom/light_dark": {
        "format": "󰐾",
        "on-click": "~/.config/waybar/scripts/baraction light",
        "tooltip": false
    },

    "custom/power_btn": {
        "format": "",
        "on-click": "sh -c '(sleep 0.5s; wlogout --protocol layer-shell)' & disown",
        "tooltip": false
    },

    "cpu": {
        "interval": 10,
        "format": " {usage}%",
        "max-length": 10,
        "on-click": "kitty --start-as=fullscreen --title btop sh -c 'btop'"
    },

    "disk": {
        "interval": 30,
        "format": "󰋊 {percentage_used}%",
        "path": "/",
        "tooltip": true,
        "tooltip-format": "HDD - {used} used out of {total} on {path} ({percentage_used}%)",
        "on-click": "kitty --start-as=fullscreen --title btop sh -c 'btop'"
    },

    "memory": {
        "interval": 30,
        "format": " {}%",
        "max-length": 10,
        "tooltip": true,
        "tooltip-format": "Memory - {used:0.1f}GB used",
        "on-click": "kitty --start-as=fullscreen --title btop sh -c 'btop'"
    },

  
    "wlr/workspaces": {
        "disable-scroll": true,
        "all-outputs": true,
        "on-click": "activate",
        "persistent_workspaces": {
            "1": [],
            "2": [],
            "3": [],
            "4": [],
            "5": [],
            "6": [],
            "7": [],
            "8": [],
            "9": [],
            "10": []
        }
    },
    
    "custom/power_profile": {
        //shows the current power profile and switches to next on click
        "exec": "asusctl profile -p | sed s:'Active profile is'::",
        "interval": 30,
        "format": "󰈐{}", 
        "on-click": "asusctl profile -n; pkill -SIGRTMIN+8 waybar",
        "signal": 8
    },

   "custom/weather": {
        //shows the current weather and forecast
        "tooltip" : true,
        "format" : "{}",
        "interval" : 30,
        "exec" : "~/.config/waybar/scripts/waybar-wttr.py",
        "return-type" : "json"
    },

    "tray": {
        "icon-size": 18,
        "spacing": 10
    },

    "clock": {
        "format": "{:%I:%M %p}",
        "tooltip": true,
        "tooltip-format": "{: %A, %B %e %Y}"
    },

    "backlight": {
        "device": "intel_backlight",
        "format": "{icon} {percent}%",
        "format-icons": ["󰃞", "󰃟", "󰃠"],
        "on-scroll-up": "brightnessctl set 1%+",
        "on-scroll-down": "brightnessctl set 1%-",
        "min-length": 6
    },

    "battery": {
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    },

    "pulseaudio": {
        "format": "{icon} {volume}%",
        "format-muted": "",
        "on-click": "pamixer -t",
        "on-click-right": "pavucontrol",
        "on-scroll-up": "pamixer -i 5",
        "on-scroll-down": "pamixer -d 5",
        "scroll-step": 5,
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        }
    },

    "pulseaudio#microphone": {
        "format": "{format_source}",
        "format-source": " {volume}%",
        "format-source-muted": "",
        "on-click": "pamixer --default-source -t",
        "on-click-right": "pavucontrol",
        "on-scroll-up": "pamixer --default-source -i 5",
        "on-scroll-down": "pamixer --default-source -d 5",
        "scroll-step": 5
    },
    
    "temperature": {
        "thermal-zone": 1,
        "format": " {temperatureF}°F",
        "critical-threshold": 70,
        "format-critical": " {temperatureC}°C",
        "on-click": "kitty sh -c 'btop --utf-force'"

    },

    "network": {
        "interval": 2,
        "format-wifi": " {bandwidthDownBytes:>} {bandwidthUpBytes:>}",
        "format-linked": "{ifname} (No IP) no_entry",
        "format-disconnected": "Disconnected"
    },

     "cava": {
        "cava_config": "/home/hakaishin/.config/cava/config",
        "framerate": 60,
        "autosens": 1,
        "sensitivity": 100,
        "bars": 14,
        "lower_cutoff_freq": 50,
        "higher_cutoff_freq": 10000,
        "method": "pulse",
        "source": "auto",
        "stereo": true,
        "reverse": false,
        "bar_delimiter": 0,
        "monstercat": false,
        "waves": false,
        "noise_reduction": 0.77,
        "input_delay": 2,
        "format-icons" : ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ],
        "actions": {
                   "on-click-right": "mode"
                   }
    }

}

Previously could see workpsace number 1,2,3 etc in top left as per above conf but now i cant so please guide to fix it

**Comment by jernejmarcic** [comment]
yes now (since you are using hyprland) you have to use `hyprland/workspaces`
Eg my config (don't judge)
```
   "hyprland/window": {
        "format": "{}"
    },
    "hyprland/workspaces": {
        "on-scroll-up": "hyprctl dispatch workspace e+1",
        "on-scroll-down": "hyprctl dispatch workspace e-1",
    // Icons for 20 workspaces? Why wou may ask, Why not I anwser.
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",



        "all-outputs": true,
        "on-click": "activate",
        "format": "{icon}",
        "format-icons": {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "10",
      "11": "11",
      "12": "12",
      "13": "13",
      "14": "14",
      "15": "15",
      "16": "16",
      "17": "17",
      "18": "18",
      "19": "19",
      "20": "20",

 


            "urgent": "<span color='#dd532e'></span>", // The explamation point is now red to draw more attention to it
            // "active": "",
            "default": ""
          }
    },

```

**Comment by HakaishinShwet** [comment]
@jernejmarcic thanks buddy now its showing workspace number :-))
