### ISSUE TITLE
Examples wiki page empty

### ISSUE THREAD

**Issue by LelouBil** [Alexays/Waybar#2876]
When clicking on the example link in the README, it sends you to https://github.com/Alexays/Waybar/wiki/Examples

but then it asks you to create a new page because it doesn't exist

**Comment by apiraino** [comment]
By looking at the git history of the Wiki repository, I think that that page was inadvertedly deleted by a few confused users. After all, the wiki is publicly editable.

I reverted the commit culprit :slightly_smiling_face:
