### ISSUE TITLE
Keyboard state can not display icons

### ISSUE THREAD

**Issue by PILIHU2022** [Alexays/Waybar#2884]
I'm using `waybar-git 0.9.24.r143.g4c5ff80-1` in AUR, and I set icons like this
![image](https://github.com/Alexays/Waybar/assets/100511118/21cd606b-ec04-4734-a293-8db7fcd335b0)
and restart waybar, but it only can display the key states, like this
![image](https://github.com/Alexays/Waybar/assets/100511118/b81e78e5-3b96-468d-9cb7-410760328983)
I also set styles.css, and restart hyprland, but it still can not display the icons.
I even reboot my machine.
I am sure that I installed the icons fonts
How can I do to make it display the icons?

**Comment by jramrath** [comment]
You'll have to use `locked` and `unlocked` in instead of `lock` and `unlock`.

You can find the relevant wiki section [here](https://github.com/Alexays/Waybar/wiki/Module:-Keyboard-State#icons).

**Comment by PILIHU2022** [comment]
> You'll have to use `locked` and `unlocked` in instead of `lock` and `unlock`.
> 
> You can find the relevant wiki section [here](https://github.com/Alexays/Waybar/wiki/Module:-Keyboard-State#icons).

It works,thank you!

**Comment by PILIHU2022** [comment]
I made a careless mistake
