### ISSUE TITLE
keyboard-state does not work as expected when xkb_options caps:swapescape

### ISSUE THREAD

**Issue by pablomartinezbalsa** [Alexays/Waybar#2890]
Hi,
Caps indicator does not work in keyboard-state module when CAPS and ESC keys have been swapped.

sway config:

  _input "type:keyboard" {
    xkb_layout es
    xkb_variant cat
    repeat_delay 300
    repeat_rate 40
    xkb_capslock disabled
    xkb_numlock disabled
    xkb_options caps:swapescape
  }_

waybar config:
    _"keyboard-state": {
	"numlock": true,
	"capslock": true,
	"format": "{name} {icon}",
	"format-icons": {
		"locked": "",
		"unlocked": ""
	}
    }_

**Comment by joesri** [comment]
Hi.
There is an option "binding-keys" to customize the key to trigger this module. ESC is mapped to input event code 1. So the config would look like:
```
"keyboard-state": {
    "numlock": true,
    "capslock": true,
    "binding-keys": [1,69,70],
    "format": "{name} {icon}",
    "format-icons": {
        "locked": "",
        "unlocked": ""
    }
}
``` 
Salut!

**Comment by pablomartinezbalsa** [comment]
Hi Joesri,
Your solution worked perfectly.
Thanks a lot.
Best regards,
 Pablo.
