### ISSUE TITLE
Differing Font Awesome width

### ISSUE THREAD

**Issue by mooreye** [Alexays/Waybar#2892]
Different Font Awesome icons have different width and thus will cause the modules to the left to slightly change position if you for example have volume module on the right, and change between speakers and headphones (different format-icons). Is it possible to force a fontawesome glyph to have a fixed width?

**Comment by jramrath** [comment]
If you don't care about the icon being centered, try adding a space after the icon: `"format": "{icon} "`
This will make the icon clip into the space and shouldn't make the widget wider.

**Comment by mooreye** [comment]
> If you don't care about the icon being centered, try adding a space after the icon: `"format": "{icon} "` This will make the icon clip into the space and shouldn't make the widget wider.

Nope, it still changes width. On those screenshots you can see the width difference as the black part on the right:

![2024-02-08T15:35:37,063095470+01:00](https://github.com/Alexays/Waybar/assets/93423596/9d48dd6f-769b-4826-89bd-9a95e81071ca)
![2024-02-08T15:35:45,042424444+01:00](https://github.com/Alexays/Waybar/assets/93423596/5ab6d37c-1d0b-4ac2-aede-c0ae25df1952)

```
    "pulseaudio": {
        "format":       "{icon} {volume:4}%",
    "format-muted": "{icon}  ────",
        "format-icons": {
            "alsa_output.pci-0000_00_1f.3.hdmi-stereo":   "<span font='fontawesome6free'> </span>",
            "alsa_output.pci-0000_00_1f.3.analog-stereo": "<span font='fontawesome6free'> </span>",
            "default":                                    "<span font='fontawesome6free'></span>"
        },
```

**Comment by jones-josh** [comment]
Have you tried the mono or propo version of your nerd font?

**Comment by jones-josh** [comment]
Have you tried a mono propo variant of the font?

**Comment by mooreye** [comment]
> Have you tried a mono / propo variant of the font?

yes that works, thanks!
