### ISSUE TITLE
Battery time estimate is viewable while charging at 100%, leading to very large/ broken time estimates

### ISSUE THREAD

**Issue by OpenSauce04** [Alexays/Waybar#2893]
The battery life estimate can't usually be viewed when the battery is charging, but when the battery reaches 100%, the battery doesn't seem to be considered to be charging anymore. This allows the time estimate for the battery life to be viewed, leading to comedically high battery life estimates being displayed:
![image](https://github.com/Alexays/Waybar/assets/48618519/6ddc2159-79ec-43af-a299-e4124ca9a3e0)

This estimate also continues to rise extremely quickly; In the span of ~5 minutes, the estimate increases by over 250 hours.

A simple solution to this is likely to just disable viewing the battery estimate when the battery is charging at 100%, the same as any other scenario where the battery is charging.

I am running Waybar v0.9.24 on Fedora 39's Sway spin.

**Comment by OpenSauce04** [comment]
After a while of this, the battery estimate became so large that the text stopped rendering
![image](https://github.com/Alexays/Waybar/assets/48618519/c9db4521-7d08-48c7-bb5b-6088ee688f7f)

**Comment by jramrath** [comment]
By default the time remaining only shows up in the tooltip, which disables it when the battery is charging.

I assume you added `{time}` to `format`.
If so, you'll have to use `format-<status>` described [here](https://github.com/Alexays/Waybar/wiki/Module:-Battery#custom-formats) to override `format` while charging (and fully charged?).

**Comment by OpenSauce04** [comment]
Would this be an issue with Fedora's default Sway config then? This isn't something I changed myself

**Comment by OpenSauce04** [comment]
Fedora's config is using the undocumented `format-alt` to display this time estimate when the module is clicked

The time estimate cannot be checked when the battery is charging, with the exception of when the battery is full, and this behaviour seems to be inherent to Waybar as there is no further config to set up this behaviour

Unless I'm misunderstanding or missing something this does seem like a Waybar issue

**Comment by OpenSauce04** [comment]
Both Fedora and the default Sway config make use of `format-alt` to display this time estiamte:
https://github.com/Alexays/Waybar/blob/master/resources/config#L118

This appears to be a Waybar issue

**Comment by OpenSauce04** [comment]
> After a while of this, the battery estimate became so large that the text stopped rendering ![image](https://private-user-images.githubusercontent.com/48618519/303043537-c9db4521-7d08-48c7-bb5b-6088ee688f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDQxMDUsIm5iZiI6MTcwNzQwMzgwNSwicGF0aCI6Ii80ODYxODUxOS8zMDMwNDM1MzctYzlkYjQ1MjEtN2QwOC00OGM3LWJiNWItNjA4OGVlNjg4ZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE0NTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2Q5M2I4ZWRlYTM3ZTJmMGE2YjFjMWFlMWI1MGM2YTE1ZmU5MGIyYjFjMGM4NTAzZGFkMzUxZTRiNGVlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.94-Q-hgR1iMFarBsmgJowbLmQJdlKZQqn5_Qo-nzMng)

Looking at the source, this seems to be semi-intentional, as if the battery time estimate is 0, there is code written specifically to not return any text:
```c++
  if (full_hours == 0 && minutes == 0) {
    // Migh as well not show "0h 0min"
    return "";
  }
```

It being visible like this is likely still unintentional
