### ISSUE TITLE
Build error on gentoo

### ISSUE THREAD

**Issue by thedanilfez** [Alexays/Waybar#2918]
OS: Gentoo
Profile: default/linux/amd64/17.1/clang
Compiler: gcc (clang is default but for waybar its gcc set using package.env)

[logs.log](https://github.com/Alexays/Waybar/files/14271217/logs.log)

**Comment by o0nd7ots** [comment]
I am running profile `default/linux/amd64/17.1/desktop` and I can build 0.34 without errors.
