### ISSUE TITLE
Spotify widget formatting

### ISSUE THREAD

**Issue by ams-123** [Alexays/Waybar#293]
Hi,

The current mediaplayer.py script seems to malformat the spotify metadata:

![](https://f002.backblazeb2.com/file/arch-images/screenshot_2019-04-29-181009.png)

The python disctionary is getting displayed rather than the key values.

**Comment by Alexays** [comment]
You missed `return-type: "json"` i think

**Comment by ams-123** [comment]
Thanks Alexays. I'm using the mediaplayer.py script from the resources folder. Maybe I have a missing module or somrthing similar. WIll take a look.
