### ISSUE TITLE
Window title flickers when switching between outputs

### ISSUE THREAD

**Issue by cole-h** [Alexays/Waybar#294]
bb8ff5a99fbc67126aba3b4b75729009da97664c introduced a bug where, when quickly mousing over windows (surfaces in Wayland now, I guess) with different titles, the title gets displayed on ALL bars (each output) briefly, and then disappears. A workaround is  to set `"all-outputs": true,` in the config of `"sway/window"`.

Note: I didn't actually bisect that commit, so it could be earlier or later, but it is related (I wouldn't have tried `"all-outputs"` without looking at it).

## STR (for Sway)

1. Launch `waybar` with `"all-outputs"` set to false in config (as is default)
2. Open two different windows on two different outputs
3. Quickly mouse between the two and look at the bar of the opposite output
4. Observe title appearing briefly and then disappearing

**Comment by Alexays** [comment]
Fixed with 74137befba004e2b8bc1f24143632ead30afc42a
