### ISSUE TITLE
hyprland/workspaces: Persistent workspace disappear after being active

### ISSUE THREAD

**Issue by aruhier** [Alexays/Waybar#2945]
Hi,
With commit 11310b89f063a305de0d23aa4dd21d6ef365a776, a workspace set as persistent is not shown anymore after being active and then destroyed by Hyprland.

Config:
```
    "hyprland/workspaces": {
        "all-outputs": true,
        "format": " {icon}",
        "persistent-workspaces": {
            "*": [1, 2, 3, 4, 5, 6, 7, 8]
        },
    },
```

How to reproduce:

1. Start waybar with persistent workspaces. All persistent workspaces are shown correctly at start. Using my config above, it'll show this: <br/>![20240220_22h51m34s_grim](https://github.com/Alexays/Waybar/assets/1174685/03735e81-7dc1-4a9c-a6f1-114973cd27b3)
2. Switch to a an empty workspace in Hyprland, set as persistent in waybar. For example, switching to `i`, it works as intended: <br/>![20240220_22h51m51s_grim](https://github.com/Alexays/Waybar/assets/1174685/256c869c-a432-47bb-b9cf-b7e445c9e830)
3. Switch to another workspace in Hyprland. Workspace `i` is destroyed in Hyprland, and not persistent anymore in Waybar (it is not listed anymore): <br/>![20240220_22h52m04s_grim](https://github.com/Alexays/Waybar/assets/1174685/ac981b87-7732-49aa-a0b2-9b2611f6bf99)

Reverting commit 11310b89f063a305de0d23aa4dd21d6ef365a776 fixes this behavior.
CC @zjeffer for the #2603.

Edit: I forgot to specify that I don't set my workspaces as persistent in Hyperland, only in Waybar.

**Comment by zjeffer** [comment]
Thanks for the detailed report.

I might have time to look into this tomorrow. In the meantime, can you post the trace logs where you start the bar and do the exact things to reproduce this issue?

**Comment by zjeffer** [comment]
Nevermind, I can reproduce the issue locally. Will investigate.

**Comment by zjeffer** [comment]
Can you test that PR @aruhier ?

**Comment by aruhier** [comment]
I found the problem and I think I fixed it, I added a comment in your PR.

**Comment by alin742** [comment]
This PR worked fine for me.

**Comment by aruhier** [comment]
Do you set the workspace as persistent in Hyprland or only in Waybar?

**Comment by zjeffer** [comment]
I personally set it to persistent in Hyprland. 

The code is written in such a way that you shouldn't use both methods. You should either specify persistent workspaces in your waybar config, or specify them in your Hyprland config. No mixing.

**Comment by aruhier** [comment]
I'm asking this because that's when the PR didn't work, compared to what I proposed. Because the workspace exists in Hyprland, it'll be created by `initializeWorkspaces()`, but the persistency is not set in Waybar. Then because the workspace already exists in Waybar, the persistency state is not set with this PR.

If you set the workspace as persistent in Hyprland, then the workspace is never removed, which hides the issue.

**Comment by aruhier** [comment]
I wrote #2967, that fixes this bug.

> The code is written in such a way that you shouldn't use both methods. You should either specify persistent workspaces in your waybar config, or specify them in your Hyprland config. No mixing.

Tell me if I'm wrong, but it should also fix this. Waybar will prefer the persistency state set in the config compared to the one set in Hyprland, but the 2 methods should work well together.
