### ISSUE TITLE
can't update arch because of spdlog (1.13.0-1) breaking waybar-git dependency

### ISSUE THREAD

**Issue by CaneMandarinesco** [Alexays/Waybar#2957]
output:
installing spdlog (1.13.0-1) breaks dependency 'libspdlog.so=1.12-64' required by waybar-git

pls, how can i solve this? do i just have to wait?

**Comment by manfred3000** [comment]
This is not a `waybar` issue and you should ask at the Arch Linux (AUR sub)forum for support...

FWIW: Uninstall `waybar-git`, update your system with `pacman -Syu`, then rebuild waybar against `spdlog` v1.13...
