### ISSUE TITLE
per monitor styling hyprland workspaces

### ISSUE THREAD

**Issue by WinteruOfficiel** [Alexays/Waybar#2959]
Hello, I’m using arch with waybar (with the hyprland workspace module) and I want to highlight the current workspace I am but for each monitors, is that possible ?

like on monitor 1, I am on workspace 2 so on the waybar of monitor 1, workspace 2 is highlighted.
But on monitor 2, I am on workspace 4 so on the waybar of monitor 2, the 4th one is highlight.

**Comment by jramrath** [comment]
As long as `all-outputs: false`, you should be able to that with `#workspaces .visible { }` in your css.

**Comment by WinteruOfficiel** [comment]
I would prefer to keep all output as true, maybe you know have a different color based on where the workspace is.

**Comment by jramrath** [comment]
That would require a new css class showing where the workspace is visible. Something like `.HDMI-A-1`.

If I find the time I'll take a look.

**Comment by WinteruOfficiel** [comment]
Thanks a lot !!
