### ISSUE TITLE
The Idle Inhibitor icon isn`t changed on another monitor

### ISSUE THREAD

**Issue by gorsheninmv** [Alexays/Waybar#296]
I\`ve got an external monitor for my laptop and when I activate/deactivate the Idle Inhibitor by clicking on the icon on one monitor it won\`t switch on another one. It doesn\`t depend which monitor I click on.

**Comment by Alexays** [comment]
Idle inhibitor is linked to a surface which is different on each bar, it might not be possible to fix that.

**Comment by Synthetica9** [comment]
@Alexays Maybe you could create a file somewhere if idle is being inhibited (and watch it with something like libinotify/[GFileMonitor](https://developer.gnome.org/gio/stable/GFileMonitor.html))? 

This would have the additional advantage of allowing easy external control over the inhibit with a simple `rm`/`touch`.

**Comment by JordanL2** [comment]
I raised a draft PR for this, it works but the part that causes the idle inhibitor modules on other bars needs to be worked on.

**Comment by Alexays** [comment]
Closed by #906
