### ISSUE TITLE
Add option to adjust power consumption format replacement field precision

### ISSUE THREAD

**Issue by ajgae** [Alexays/Waybar#2963]
# current behavior

the `{power}` (power in watts) format replacement can take up a variable amount of characters, which sometimes leads to a shorter or longer character count for the battery module on my waybar:

![image](https://github.com/Alexays/Waybar/assets/69397914/599699d1-23ba-49a7-afcd-7e8aebb59c63)
![image](https://github.com/Alexays/Waybar/assets/69397914/8279a79d-5444-4043-a309-cfe009b069ec)

# better behavior

allow the user to specify the amount of decimal places so that character count stays constant (essentially something like `%4.2f` in `printf`)

**Comment by jramrath** [comment]
I think making an option to configure the number of decimals is not necessary. 

I'll make a PR to always shows two decimals.

**Comment by alebastr** [comment]
> essentially something like %4.2f in printf

That should translate to `{power:4.2f}`. Does it do what you wanted?

**Comment by phonetic112** [comment]
You could use padright() from the string library in Lua, but that might have some limitations if your generated text is larger than your field width so choose wisely.

**Comment by ajgae** [comment]
> That should translate to `{power:4.2f}`. Does it do what you wanted?

@alebastr sadly it does not, this seems to have no effect at all.

> I think making an option to configure the number of decimals is not necessary.
> 
> I'll make a PR to always shows two decimals.

@jramrath i think it might be good to have the option, as some people may be short on waybar space and want to only show one or even no decimals. But I think showing only two by default may still be an improvement. Do you know where in the codebase the format string interpolation is done, and whether it would be reasonably easy to implement an option for number of decimals? (something like `{power:4.2f}` like suggested above, or via an additional key-value pair in the json config file)?

**Comment by ajgae** [comment]
I see now that waybar uses the {fmt} library for label formatting. Given the [official example](https://fmt.dev/latest/api.html#_CPPv4I00EN3fmt3argEN6detail9named_argI4Char1TEEPK4CharRK1T) for how `fmt::arg` works, and the way it is used [in the battery module](https://github.com/Alexays/Waybar/blob/6703adc37fec45431eaa383a1fe8a4d6893d9b55/src/modules/battery.cpp#L668), it seems the `{power:4.2f}` suggestion _should_ work. Why does it not?
