### ISSUE TITLE
sway/workspaces displays __i3_scratch as a workspace if all-outputs is true

### ISSUE THREAD

**Issue by RobertMueller2** [Alexays/Waybar#2966]
This seems to be a consequence of bb843e0 / PR #2944.  Specifically, the commit replaced `get_workspaces` with `get_tree`. `get_tree` includes __i3_scratch as a workspace object on the output "__i3", while `get_workspaces` does not.

![satty-20240224-15:05:11](https://github.com/Alexays/Waybar/assets/29629287/23f8eb33-6442-42ce-9946-daceac6da816)

The upper waybar includes the commit, the bottom does not.

@grimpy 
Is this intended? I suppose it could be useful, even more so if I could specifically rename it or display a counter. Clicking it creates a new workspace "__i3_scratch" beneath the active output, not the invisible "__i3" output. That is a bit weird. While this is something that can be done through IPC without waybar altogether, and there's nothing we can do about it, I do feel if this were to be a feature in the module, it should get some special handling. The identification for this could be "workspace __i3_scratch on output __i3".

**Comment by grimpy** [comment]
Unfortunately that was noty intended behaviour, i never use the scratch
workspace.

I'm unsure what would be the best behaviour here, my gut feeling is to
filter out this special workspace, is it normally visible when its in use
or not even then?

**Comment by RobertMueller2** [comment]
Thanks for the reply. The scratchpad is just a place to store windows in, but it is never directly visible.

So far, sway/workspaces has not displayed it. That's not to say it couldn't be useful at all, but as mentioned above, not really without special handling. I think your intuition is correct here. We should filter it for now.

If somebody feels like including it in a more sophisticated fashion, that's always possible as a new feature down the road. I believe that might be better suited for a separate scratchpad module, though. (In fact I got that one on my list for trying out a Rust cffi waybar module, but who knows if I can pull that off within the next 3 or 4 years. :stuck_out_tongue: )
