### ISSUE TITLE
[Feature] Custom module formating

### ISSUE THREAD

**Issue by freerig** [Alexays/Waybar#2978]
I would like the script of my custom module in "exec" to return json such as `{"title": "NGGYU", "singer": "Rick"}`, and that we can use them in `format` and `tooltip-format`, with `{title}` and `{singer}`, for example, instead of having to return `{"text": "NGGYU - Rick"}` and use `{}`

Can you can add this functionality, keeping backwards compatibility eventualy ?

**Comment by RobertMueller2** [comment]
See PR #2441, which has not been merged yet.
