### ISSUE TITLE
Add parameter to idle_inhibitor command

### ISSUE THREAD

**Issue by cinghiopinghio** [Alexays/Waybar#299]
The `idle_inhibitor` module is very handy, although when going in _presentation_ mode, one can have other services to suspend (such as notifications, screen timers...).

In order to write a small script for that it would be helpful to know to which mode we are switching. A possibility would be to add a parameter to the `on-click` command such `cmd %m`, where `%m` is a parameter to be passed to the command `cmd` and  can be either `activating` or `deactivating`.

**Comment by Alexays** [comment]
Done in 5623bbecfe118ace2387c9f33c8ac1f2e0f7fa8c
The format is `on-click: "cmd {arg}"`
I will see to it that all the arguments available for the display format are also implemented properly for clicks events

**Comment by cinghiopinghio** [comment]
That was so fast!!! Thanks

**Comment by Alexays** [comment]
@cinghiopinghio It may not work as excepted, i'm on it ;)

**Comment by Alexays** [comment]
@cinghiopinghio Fixed with 1a024db03cf97afcbe44126fb40149632489fc06

**Comment by dlasky** [comment]
you think its worth extracting this behavior to a toggle module? I was going to just write a stupid little go script that handles the state as output.

The use case i'm thinking of is making an 'indicator' for virtboard so when i'm in tablet mode i can toggle the bus show hide commands.
