### ISSUE TITLE
sway/workspaces `persistent-workspaces` throws error and does not show up

### ISSUE THREAD

**Issue by italovieira** [Alexays/Waybar#2998]
I tried to set up persistent workspaces but following the examples in the [wiki](https://github.com/Alexays/Waybar/wiki/Module:-Sway#persistent-workspaces):

```
    "sway/workspaces": {
        "persistent-workspaces": {
            "1": [],
            "2": [],
            "3": []
        }
    },
```
But the result is no workspaces at all and a error:
```
 [error] Workspaces: in Json::Value::find(begin, end): requires objectValue or nullValue
```

**Comment by nut-3** [comment]
I'm experiencing same bug.
To add, it is not present on 0.9.24 tag, can reproduce only on build from master tree.
Could trace the error till `void Workspaces::onCmd(const struct Ipc::ipc_response &res)` in `src/modules/sway/workspaces.cpp`

**Comment by grimpy** [comment]
@nut-3 @italovieira I've created a merge request to fix this, could you verify this returns the expected behavior?

**Comment by italovieira** [comment]
> @nut-3 @italovieira I've created a merge request to fix this, could you verify this returns the expected behavior?

With your PR persistent workspaces shows up, but now there's another problem, the active workspace is not highlighted:

![image](https://github.com/Alexays/Waybar/assets/8337230/2c8a9f15-871f-4ae7-b098-cfd169047d03)

For comparison, in the `v0.9.24` the highlighting was as expected:
![image](https://github.com/Alexays/Waybar/assets/8337230/47a91736-2bca-4e38-b2ce-4c6e97f89db5)

**Comment by grimpy** [comment]
I updated the merge request that behaviour should be fixed aswell now
