### ISSUE TITLE
feature request: new release

### ISSUE THREAD

**Issue by StayPirate** [Alexays/Waybar#3002]
Hi @Alexays, would you mind to release a new version of Waybar? Last one is dated 3 Nov 2023 and is 283 commits behind master. I would like to get the fix in #2855. I'm in Archlinux and I'm using the [`waybar`](https://archlinux.org/packages/extra/x86_64/waybar/) package from official repos, otherwise I would need to replace it with the [AUR package](https://aur.archlinux.org/packages/waybar-git) which instead follows the master branch. TBH I like to stay with official packages when possible. Moreover, other downstream distros that repackage your software will benefit from a release. Thank you.

**Comment by Alexays** [comment]
Just released a new version 0.10.0 :)
That will take some time to be available in all packages managers
