### ISSUE TITLE
Missing tray icon for Discord

### ISSUE THREAD

**Issue by Stilic** [Alexays/Waybar#3003]
When I run Discord, the systray icon doesn't appear in my bar.
I'm using Artix Linux with Dinit and Labwc.
![image](https://github.com/Alexays/Waybar/assets/63605602/5a7dbc2b-0ee3-415d-95e3-61a6ff769594)

**Comment by Stilic** [comment]
It was an issue with the distro that I use, not Waybar itself.

**Comment by nyankittone** [comment]
@Stilic What did you do to solve it? I'm having the same issue on the same distro.

**Comment by Stilic** [comment]
> @Stilic What did you do to solve it? I'm having the same issue on the same distro.

I don't know.
It's been one year since I stopped using Artix.

**Comment by nyankittone** [comment]
@Stilic Fair enough, I suppose. Looks like I'll have to find my own solution then :) Thanks regardless!
