### ISSUE TITLE
#workspaces button.persistent not working in 0.10.0

### ISSUE THREAD

**Issue by kingprawn22** [Alexays/Waybar#3009]
I've updated to 0.10.0 since it includes an update that hides the tray when there are no icons, which works well, but some functionality of my style.css looks to have changed. I have 4 persistent workspaces, and I want to apply a different style to those that are 'active' (have open windows), and those that are not. I have also tried the default style.css (renaming 'persistent-workspaces' to 'persistent_workspaces' to make it work), and can see the same issue there also, comparing between waybar 0.10.0 and 0.9.17 (Debian).

```
/* remove inheritance from GTK */
button:hover {
	box-shadow: none; /* Remove predefined box-shadow */
	text-shadow: none; /* Remove predefined text-shadow */
	background: none; /* Remove predefined background color (white) */
	transition: none; /* Disable predefined animations */
}

* {
	border: 0;
	border-radius: 0;
	font-family: "JetBrains Mono";
	font-size: 13px;
	font-weight: bold;
}

/* main waybar colors */
window#waybar {
	background-color: rgba(0, 0, 0, 0.3);
	color: #dedede;
}

/* gap on left side */
.modules-left {
	margin-left: 15px;
}

/* gap on right side */
.modules-right {
	margin-right: 15px;
}

#workspaces button {
	min-width: 20px;
	padding-left: 5px;
	padding-right: 5px;
	/* applies to 'active' workspaces */
	color: #dedede;
}

/* applies to all workspaces set as persistent */                 
#workspaces button.persistent {
        color: #555;
}

/* currently selected workspace */
#workspaces button.focused {
        background: rgba (0, 0, 0, 0.4);
        border-bottom: 2px solid rgba(255, 255, 255, 0.2);
}

/* when hovering over workspace button */
#workspaces button:hover {
	background: rgba (0, 0, 0, 0.2);
}

/* use a dash for module separated by slash in config
#custom-search {
	margin-right: 20px;
	border-bottom: 2px solid rgba(255, 255, 255, 0.2);
}*/

#pulseaudio {
	margin-right: 20px;
	border-bottom: 2px solid rgba(255, 255, 255, 0.2);
}

#cpu {
	margin-right: 20px;
	border-bottom: 2px solid rgba(255, 255, 255, 0.2);
}

#memory {
	margin-right: 20px;
	border-bottom: 2px solid rgba(255, 255, 255, 0.2);
}
```

Is there a new way to apply a style to 'active' workspace buttons? I've tried using the 'active', 'visible' and 'persistent' css things but none of them seem to have an effect. I even used 'empty' to instead apply a style to the empty workspaces, but again this made no difference.

**Comment by ZakDggn** [comment]
Same issue here. It seems like everything was fine up until bb843e0 which completely broke persistent workspaces. It was mostly fixed in 7b3d155 but the styling no longer works.
