### ISSUE TITLE
Pulseaudio scroll-step does not correlate to volume percentage

### ISSUE THREAD

**Issue by cjbassi** [Alexays/Waybar#301]
i.e. scroll-step = 1 does not mean that scrolling one tick will change volume by 1 percentage point.

I have to scroll several times to change the percentage by 1 point. Changing the scroll-step multiplier to about 650 fixes this for me, but I don't think it's exact. Does anyone else have this problem? Or is it something on my end?

**Comment by varac** [comment]
Same here, weird, but not a big issue for me
