### ISSUE TITLE
Clock no longer displays longer format strings

### ISSUE THREAD

**Issue by Flootersmm** [Alexays/Waybar#3021]
Waybar 0.10.0 with kernel 6.8.1-arch1-1 has just today started to not accept longer format strings and appears blank if I use anything longer than :%H:%M, such as including glyphs or further format specifiers. Adjust min/max-length does nothing. 

In particular, I get no error messages.

The tooltip format string functions just fine. I made no changes and my clock more or less randomly broke. 

Reverting to Waybar 0.9.24-3-x86-64 has solved this temporarily.

**Comment by FelixJochems** [comment]
Think any format option is just broken at the moment, without the option is shows %H:%M but I cant get any other to work even manually entering the %H:%M format breaks it

**Comment by virtuallynaman** [comment]
> For me it only breaks with the glyphs I had in the formatting previously. Removing those brings back the time with the formatting I had set previously.
> 
> Did some more testing, putting the glyphs in the formatting options of other waybar modules works just fine so it is only the clock that has been broken.

++ Same behaviour

**Comment by DamianRyse** [comment]
> For me it only breaks with the glyphs I had in the formatting previously. Removing those brings back the time with the formatting I had set previously.
> 
> Did some more testing, putting the glyphs in the formatting options of other waybar modules works just fine so it is only the clock that has been broken.

I can confirm this issue. Had the same problem with the following format string: `"format": "{: %H:%M %p   %a, %b %e}",`

**Comment by GodGMN** [comment]
Same issue there. I updated yesterday and my clock stopped showing, I haven't changed my configuration file for weeks.

This is my format string: `"format": "{:󰥔  %R    %d/%m}",`

This is the error message:
```
[error] clock: format error: invalid arg-id in format string
```

I want to add that my whole system date got resetted, it has never happened before. I don't know if another update in some other time related package broke it. It may be totally unrelated but I find it rather weird that I had two issues related with date the same day.

**Comment by M2rsh** [comment]
Same here also updated yesterday 
format: `"format": "<b>{:󰥔 %H:%M 󰃭 %d/%m}</b>"`
error message: `[error] clock: chrono format error: no '%' at start of chrono-specs`

but the clock doesnt even show up
![image](https://github.com/Alexays/Waybar/assets/69349269/8bd2bf6b-9361-4fe6-a6c1-181d7dbc8a99)

**Comment by ordy** [comment]
@M2rsh that line works for me on 0.10 if you format it like this `"format": "<b>󰥔{:%H:%M 󰃭 %d/%m}</b>"` instead.

**Comment by M2rsh** [comment]
> <b>󰥔{:%H:%M 󰃭 %d/%m}</b>

![image](https://github.com/Alexays/Waybar/assets/69349269/dabe02b5-c522-4e17-b8ed-deef0cb0474e)
it kinda works i just added a space `<b>󰥔 {:%H:%M 󰃭 %d/%m}</b>"` and it works perfectly thanks

**Comment by DamianRyse** [comment]
> > 󰥔{:%H:%M 󰃭 %d/%m}
> 
> ![image](https://private-user-images.githubusercontent.com/69349269/313673517-dabe02b5-c522-4e17-b8ed-deef0cb0474e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjY2MzQsIm5iZiI6MTcxMDc2NjMzNCwicGF0aCI6Ii82OTM0OTI2OS8zMTM2NzM1MTctZGFiZTAyYjUtYzUyMi00ZTE3LWI4ZWQtZGVlZjBjYjA0NzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNDkyOWM3NGYyMTc1NmJkYjQ4NTdmODA5NDFkMmFmNWEyNzBmNzU0ZThjNzg2N2JjNjc3OTY1MmVjM2QxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFeU9SpdcFjDIslhO4PvEyKkpgr-NgC5d8XawzxcDy4) it kinda works i just added a space `<b>󰥔 {:%H:%M 󰃭 %d/%m}</b>"` and it works perfectly thanks

This indeed works for me as well!

**Comment by virtuallynaman** [comment]
> @M2rsh that line works for me on 0.10 if you format it like this `"format": "<b>󰥔{:%H:%M 󰃭 %d/%m}</b>"` instead.

thanks works with this format
`"format": "  {:%OI:%M %p}",` \
`"format-alt": "  {:%a, %d %b}"`

**Comment by kabeleh** [comment]
` "format": "{: %I:%M %p   %a, %b %e}",` sadly stopped working too.

**Comment by multisme** [comment]
Related to this
https://github.com/Alexays/Waybar/pull/2659
and this
https://github.com/fmtlib/fmt/issues/3445
The documentation should be updated to reflect the changes.

**Comment by nebulosa2007** [comment]
Quick fix for my config is:

```console
-  "format-alt": "{:Week %V of the %Y}"
+  "format-alt": "Week {:%V of the %Y}"
```
Just move all symbols or glyphs outside the brackets and it should start with `{:%....`.
