### ISSUE TITLE
sway/workspaces persistent-workspaces CSS class regression

### ISSUE THREAD

**Issue by phisch** [Alexays/Waybar#3025]
In the latest version `0.10.0`, the `sway/workspaces` module doesn't have the `persistent` CSS class anymore when they are shown because they are persistent.

I used this feature to display an "empty workspace" icon, because it previously only had this class when there was no window on that workspace.

There is currently no way to do this anymore. (no other classes that would indicate this)

**Comment by AlienTux** [comment]
Could this issue make Waybar crash altogether? And/or cause segmentation faults? Asking because I got a few problems and I don't know if I should open a new bug report.

**Comment by phisch** [comment]
Ah yes, this is a duplicate then!
I didn't find that one when I searched for existing issues!

Closing in favor of #3009
