### ISSUE TITLE
Waybar depends on wireplumber 0.4

### ISSUE THREAD

**Issue by luyu-wu** [Alexays/Waybar#3035]
After updating to wireplumber-0.5, waybar completely fails to load and compile.
I don't believe there's any breaking changes, I can probably fix this later tonight if I have some time...

Example:
![image](https://github.com/Alexays/Waybar/assets/116970666/78906fbe-9c3e-4c7f-8bfc-8814b650bd5a)

**Comment by DADA30000** [comment]
yep, failing to build on nixos

**Comment by khaneliman** [comment]
https://github.com/Alexays/Waybar/pull/2919 is upgrading API to build against .5

**Comment by luyu-wu** [comment]
Arch has now moved wireplumber 0.5 from extra-testing to extra, so this is a bit more of a concern now!
