### ISSUE TITLE
No Text Highlight Upon Workspace Buttons

### ISSUE THREAD

**Issue by TeusLollo** [Alexays/Waybar#3041]
It appears that when work underwent for https://github.com/Alexays/Waybar/issues/2998, there were some highlighting bugs, including this one https://github.com/Alexays/Waybar/issues/2998#issuecomment-1989577276, which was promptly fixed at https://github.com/grimpy/Waybar/commit/7b3d155608d030094f813b5c1908e0017c202547

However, I have discovered another bug that went unnoticed:

Workspace text highlighting for focused workspace in `0.9.24`

![z2](https://github.com/Alexays/Waybar/assets/106600734/350ce500-b553-45a5-be03-983dbef7bf1b)

Workspace text highlighting for focused workspace in `0.10.0`

![z1](https://github.com/Alexays/Waybar/assets/106600734/6ce3ea44-45b7-4b4a-802a-f9a774575609)

Relevant `style.css` code is as follows, and is confirmed to be working in `0.9.24`, but not anymore in `0.10.0`:

```
@define-color wkspbase		#b711ff;
@define-color wkspvisib		#56f665;
@define-color wkspurgen		#ff0d0a;

#workspaces {
    padding:    	0px 0px 0px 0px;
    min-width:  	0px;
    margin:     	0px 0px 0px 0px;
}

#workspaces button {
    padding:    	0px 10px 0px 10px;
    min-width:  	0px;
    margin:     	0px 0px 0px 0px;
    color:      	@wkspbase;
}

#workspaces button.visible {
    padding:    	0px 10px 0px 10px;
    min-width:  	0px;
    margin:     	0px 0px 0px 0px;
    color:      	@wkspvisib;
}

#workspaces button.focused {
    padding:    	0px 10px 0px 10px;
    min-width:  	0px;
    margin:     	0px 0px 0px 0px;
    border-top: 	3px solid @wkspbase;
    border-bottom: 	3px solid @wkspbase;
}

#workspaces button.urgent {
    padding:    	0px 10px 0px 10px;
    min-width:  	0px;
    margin:     	0px 0px 0px 0px;
    color:      	@wkspurgen;
}

```

Hence, on `0.10.0`, text highlighting seems broken for focused and urgent workspace states upon workspace buttons, regardless of workspace button non-text highlighting state. 

Workspace highlighting as described in https://github.com/Alexays/Waybar/issues/2998#issuecomment-1989577276 indeed was fixed, but not text highlighting, presumably since not many users actually rely on text highlighting, thus the bug went unnoticed.

**Comment by WhyNotHugo** [comment]
I have a similar issue and suspect that they're the same cause (please let me know if a separate issue is best).

```css
#workspaces button {
  padding: 0 5px;
  background-color: transparent;
  color: #ffffff;
  border-bottom: 3px solid transparent;
}

#workspaces button.visible {
  border-bottom: 3px solid #ffffff;
}
```

With waybar 0.10.0, visible workspaces don't have the last style applied to them; they look just like inactive workspaces.

**Comment by braun-steven** [comment]
Can confirm. Waybar `v0.10.0` broke the solutions to highlight a visible workspace on a second (unfocused) monitor proposed in https://github.com/Alexays/Waybar/issues/1403. Downgrading to `v0.9.24` resolved the issue.

**Comment by tokyovigilante** [comment]
`git bisect`:
```
7b3d155608d030094f813b5c1908e0017c202547 is the first bad commit
commit 7b3d155608d030094f813b5c1908e0017c202547
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Tue Mar 12 00:09:47 2024 +0200

    Fix peristant workspaces for sway

    Fixes: #2998

    Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>

 src/modules/sway/workspaces.cpp | 17 ++++++++++-------
 1 file changed, 10 insertions(+), 7 deletions(-)
```

**Comment by braun-steven** [comment]
> Can confirm. Waybar `v0.10.0` broke the solutions to highlight a visible workspace on a second (unfocused) monitor proposed in #1403. Downgrading to `v0.9.24` resolved the issue.

This is now fixed by https://github.com/Alexays/Waybar/commit/7cd2a6c00366998fcaa4f0d7f794529f9cf9c9bc

**Comment by WhyNotHugo** [comment]
I can confirm that this is fixed for me on `master`.

**Comment by rnestler** [comment]
Can also confirmed it is fixed on `master`. Will this be included in the next release?
