### ISSUE TITLE
segfault when powering other monitor off

### ISSUE THREAD

**Issue by Kommynct** [Alexays/Waybar#3047]
*** impl_ext_end_proxy called from wrong context, check thread and locking: Operation not permitted

I'm getting this error most of the time when I turn my screen off, and waybar crashes

https://gitlab.com/that1communist/dotfiles/-/blob/master/.config/waybar/config

these are my dotfiles if it helps

**Comment by asahi-m** [comment]
I have the same issue. It seems that happens when the privacy module is used.

**Comment by ErikReider** [comment]
> Waybar's pipewire backend [`42dc9cb`/src/util/pipewire/pipewire_backend.cpp](https://github.com/Alexays/Waybar/blob/42dc9cb85f27e3db02da83cd13624cfc5a7191d3/src/util/pipewire/pipewire_backend.cpp) does not use the locking scheme described in [docs.pipewire.org/page_thread_loop.html](https://docs.pipewire.org/page_thread_loop.html), but only an internal mutex in `handleRegistryEventGlobalRemove`. Do you have any thoughts on this, @ErikReider ?

Sorry for the late reply, thanks for fixing this oversight! :)
