### ISSUE TITLE
Hyprland workspaces module is disabled

### ISSUE THREAD

**Issue by 1-10-1** [Alexays/Waybar#3048]
Config: https://pastebin.com/3H2gu9FN
```
[2024-03-20 16:03:46.954] [warning] module hyprland/workspaces: Disabling module "hyprland/workspaces", Error parsing JSON: * Line 1, Column 1
  Syntax error: value, object or array expected.
```
Waybar Version: v0.10.0

**Comment by tomben13** [comment]
@1-10-1 Which version of hyprland are you using ?

**Comment by weeman1337** [comment]
Same happens for me when switching the monitor setup (set resolution for external scree, then turn off internal one).

Running v0.10.0 with Hyprland v0.36.0
Will re-test with the latest Hyprland version as soon as it arrives on NixOS unstable.

**Comment by 1-10-1** [comment]
> @1-10-1 Which version of hyprland are you using ? Can you upgrade to latest hyprland version and test again ?

I'm using v0.30.0 right now however I dont see why an outdated version of hyprland should cause this problem
I've made a program in C++ that listens to the hyprland socket for workspace changes and it works perfectly fine, and my implementation isn't very different from what waybar does

**Comment by tomben13** [comment]
Hyprland's API changed quite a bit and I believe that's the cause of your issue. You should upgrade

**Comment by 1-10-1** [comment]
Updating fixed it!
