### ISSUE TITLE
some modules cause waybar to overlap windows

### ISSUE THREAD

**Issue by Lefl1** [Alexays/Waybar#305]
Hello,

I can not seem to get waybar to respect my height settings, when I omit the "height" option in the config file, everything works fine but when I set it to some value, the bar seamingly stops shrinking after a while but the windows will still adjust to the height I set.
![bug](https://user-images.githubusercontent.com/19374353/57245817-0f62e980-703c-11e9-9f1b-ac5c22a4d272.png)
(You might want to click on the picture so it becomes more clear)
After some enabling and disabling of some modules I found that they wan't the bar not to be smaller than a certain size.
For example "sway/mode" and the "clock" module do this

My config file:
`{
    "layer": "top",
		"output": "DVI-D-1",
	"position": "top",
	"height": 25,
    "modules-left": ["sway/workspaces", "sway/mode"]
}
`
My style.css:
`* {
    font-family: Fira Code;
    font-size: 13px;
    min-height: 0;
}
`

**Comment by Alexays** [comment]
Some modules need a minimum height cause of font size, padding, ...
Check all of theses values :)

**Comment by Lefl1** [comment]
Hmm no, either I'm missing something or it's just broken, even when setting the the font size to an incredibly small size, the bar still won't resize.
but when starting waybar with the terminal I get this:
`Requested height: 25 exceeds the minimum height: 36 required by the modules`
I mean I get what it wants to tell me, but I don't understand why the modules require a certain size and don't just get smaller.

**Comment by Alexays** [comment]
This is surely a theme pb, on my side with your configs the minimum height is 27 :/

**Comment by Alexays** [comment]
I can make a configuration to disable the inheritance of the gtk theme but you will have to do more style to remove the default paddings

**Comment by Lefl1** [comment]
Starting wayber with `GTK_Theme=Adwaita waybar` does not seem to fix the issue.

**Comment by Lefl1** [comment]
I had most of my GTK programs improperly scaled (they were huge), which I didn't noticed because I mostly use the Terminal now.
It's not completly gone now, the clock still sets the min height to 19 on my second monitor, but setting `GDK_DPI_SCALE=0.5` fixed both my GTK apps and waybar for me
