### ISSUE TITLE
Waybar crashes by clicking application icon from waybar

### ISSUE THREAD

**Issue by ALEX5402** [Alexays/Waybar#3053]
### Description
-  Waybar crashes when i click into the app icon on the waybar 3 to 4 times
- here is the taskbar [module](https://pastebin.com/raw/FwpzUZ9y) for waybar
- waybar version  v0.10.0

### Steps to Reproduce

1. run waybar from anywhere you like 
2. just click on the taskbar app icon which one is running 
3. and suddenly waybar crashes after click 2 or 3 times on any app icon

### Expected Behavior
- its need to be focus to the clicked application

### Actual Behavior
- it crashes the waybar

### Here is a video how it happens

https://github.com/prasanthrangan/hyprdots/assets/76860596/958ffae0-54ad-4754-ba1e-47cbabb0999a

### Environment

- EndeavourOS Linux x86_64
- 6.8.1-zen1-1-zen 
- Installation Environment On my Main Hardware 
- AMD Ryzen 5 5500GT with Radeon Graphics (12) @ 4.457GHz
- Resolution : 1920x1080 
- here is my all installed packages 
[packages.txt](https://0x0.st/Xrvz.txt)

### Additional Information
- here is the [logs](https://pastebin.com/raw/XipySYgZ)

**Comment by tomben13** [comment]
#3049 may have fixed your issue. Could you try running git version ?

**Comment by ALEX5402** [comment]
> #3049 may have fixed your issue. Could you try running git version ?

Thanks alot it worked ❤️
