### ISSUE TITLE
crash with g_log_set_writer_func() called multiple times

### ISSUE THREAD

**Issue by terminatorbs** [Alexays/Waybar#3056]
After updating my arch linux today, waybar won't start anymore.

starting it in the terminal, there's a few warnings and errors that have always been there, but the new thing is the last line:

F 17:25:38.343188               GLib (null):(null):(null): g_log_set_writer_func() called multiple times

no idea what caused this, and sadly it was a bit of a bigger update so i don't have time to find out what exactly caused it right now.

**Comment by Fxzzi** [comment]
Also facing this issue.

**Comment by epyonavenger** [comment]
Seems to be the Wireplumber module again, or at least, it was for me. I commented that out in my config and it starts happily again.

**Comment by piny4man** [comment]
As @epyonavenger said, I removed `wireplumber` and It's working for me again

**Comment by epyonavenger** [comment]
Following up, I swapped `wireplumber` with `pulseaudio` (I keep the 2 configs identical since the last time the `wireplumber` had issues) and that seems to work fine, so it really is (at least for me) restricted to `wireplumber` alone, as opposed to any/all audio, or the audio of my specific system.

**Comment by Alexays** [comment]
Can you check with latest version?

**Comment by epyonavenger** [comment]
When you say "latest version", do you mean git master, or the latest release? I think all of us are on the latest release.

**Comment by JohnHolmesII** [comment]
I am facing this issue with the Arch package as well. I just built locally (HEAD is currently commit `cc084f5f86776b3b5b9708a99bed49b991eb48af`) and it works. Maybe push a point release?

**Comment by JohnHolmesII** [comment]
@heftig

**Comment by Alexays** [comment]
I mean the latest commit on master, wireplumber patch is not needed anymore as fixed on master :)

**Comment by Parmjot-Singh** [comment]
I've opened an issue on the Arch Linux GitLab, seen [here](https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/issues/1)
