### ISSUE TITLE
v0.10.0 Clock format: `chrono format error: no '%' at start of chrono-specs`

### ISSUE THREAD

**Issue by mrusme** [Alexays/Waybar#3058]
Before the update to v0.10.0 this format for the clock used to work:

```json
    "format": "  <span color='#aaaaaa'>{:<span color='#ffffff'>%I:%M</span> %p}</span>",
```

However, now with v0.10.0 it appears that the `<span ..>` within the `{: ... }` is something that doesn't work anymore.

Is there a different way to specify such a format now? Or is this a bug? Thank you!

**Comment by isabelincorp** [comment]
I think it's the space at the start, I ran into a similar issue, but it turns out removing it and adding a margin fixed it.

**Comment by thenicebro** [comment]
https://github.com/Alexays/Waybar/wiki/Module:-Clock, It maybe help you.

**Comment by tamirzb** [comment]
I also had this issue. I think something changed in version 0.10.0 so that now you cannot have the `{:` part of the format not starting with `%` (as the error says).

Basically I think this might work, although I do think it's a pretty weird solution:
```json
 "format": "  <span color='#aaaaaa'><span color='#ffffff'>{:%I:%M</span> %p}</span>",
```

No idea why did this suddenly change in version 0.10.0.

**Comment by Kagukara** [comment]
In waybar 0.9.24 I was able to have "format": "{: %d\n %m\n%Y}", which centred the text to the centre. I can no longer do this in 0.10.0. Is there an alternative way to do this?

**Comment by KarthikNayak** [comment]
For me changing `format = "🕑 {:%R 📅 %d/%m}"`  to `format = "{:🕑 %R 📅 %d/%m}"`  worked

**Comment by crimsonduelist** [comment]
Is this also not the same as #3021 ?

**Comment by mrusme** [comment]
> Is this also not the same as #3021 ?

It appears to be. I did a quick search on the exact error message before I created this issue, but nothing showed up back at the time -- probably because the author of the other issue did not include it in their initial description.

Going to close this one in favor of the other issue.
