### ISSUE TITLE
waybar not launching

### ISSUE THREAD

**Issue by aloispichler** [Alexays/Waybar#3062]
Since today, I am getting the following error message, and waybar is not doing anything at all. Any ideas???

waybar: error while loading shared libraries: libwireplumber-0.4.so.0: cannot open shared object file: No such file or directory

**Comment by ianmurphy1** [comment]
Likewise,

Looks like libwireplumber got an update https://archlinux.org/packages/extra/x86_64/libwireplumber/

**Comment by Alexays** [comment]
Fixed with latest master version

**Comment by aloispichler** [comment]
It works. Thank you.
