### ISSUE TITLE
Waybar doesn't display anything or show any errors. Only happens on my laptop.

### ISSUE THREAD

**Issue by ralgar** [Alexays/Waybar#3063]
As the title says, Waybar doesn't display anything or throw any errors on my laptop. It seems to run fine, except no bars are shown.

I'm using the exact same dotfiles, distro (Arch), and compositor (Hyprland) on both of my systems. Both are completely up-to-date, but only my laptop has this problem. It has an Intel HD4000 iGPU.

The issue has persisted for several months now. I've tried rolling back to earlier versions (as far as v0.9.22), but it doesn't help.

Running Waybar from the terminal doesn't produce any useful output:

```
[2024-03-22 15:14:16.851] [info] Using configuration file /home/user/.config/waybar/config
[2024-03-22 15:14:16.853] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2024-03-22 15:14:16.853] [info] Using CSS file /home/user/.config/waybar/style.css
```

I'm willing to help diagnose however I can, but I really have no idea where to even begin with this.

**Comment by ralgar** [comment]
Disregard. Turned out to be a config issue

**Comment by mainrs** [comment]
Could you elaborate a little bit more? I'm in the exact same situation. I haven't changed my config in months and it just stopped working today...

**Comment by stickynotememo** [comment]
<img width="485" height="270" alt="Image" src="https://github.com/user-attachments/assets/7572fa02-0b1f-45be-86fd-5d43c8784ab8" />

**Comment by crivotz** [comment]
Same here :D different year but same problem.
However in my case the problem is in sway ;)

**Comment by ralgar** [comment]
In my case I had pulled the latest commits from my dotfiles repo, and forgotten to apply the patch for my laptop, resulting in the wrong outputs being configured.
