### ISSUE TITLE
docs(calendar): Example is not consistent with the documentation

### ISSUE THREAD

**Issue by max-ishere** [Alexays/Waybar#3075]
In [Module Clock example \#2](https://github.com/Alexays/Waybar/wiki/Module:-Clock#example)
the JSON contains `clock.calendar.on-click-right`, which is not documented in the table for `clock: calendar`. It appears as the key was moved to `clock.calendar.actions`, but was not removed from the example. However it is not clear from the docs which is wrong - the example or the calendar table.

**Comment by its-19818942118** [comment]
well right click expands the table? its default behaviour i think.

**Comment by max-ishere** [comment]
That's not the issue. The issue is that the example is not consistent with the table above.

**Comment by its-19818942118** [comment]
Well a documentation isn't always checked or maintained could be a problem but in this case tis but a scratch 
I think other than this every thing is well documentated

**Comment by max-ishere** [comment]
> I think other than this every thing is well documentated

You'll never know for sure unless you manually check or use the CI to generate docs...

**Comment by its-19818942118** [comment]
If there are no other issues pls close this issue

**Comment by max-ishere** [comment]
Excuse me. Is it resolved?

**Comment by max-ishere** [comment]
I looked in the source code and I couldn't quickly find which is the way to do it
- `clock.calendar.on-click-right`
- or `clock.calendar.actions.on-click-right`
I am just asking that the docs accurately say which one it is. This should stay open until the docs say something consistent.

**Comment by max-ishere** [comment]
In this table there's nothing about on-click-right
![image](https://github.com/Alexays/Waybar/assets/47008271/9451e786-91de-448a-a533-fc9e65a8b532)
but this example says there could be.
```json
 "clock": {
        "format": "{:%H:%M}  ",
        "format-alt": "{:%A, %B %d, %Y (%R)}  ",
        "tooltip-format": "<tt><small>{calendar}</small></tt>",
        "calendar": {
                    "mode"          : "year",
                    "mode-mon-col"  : 3,
                    "weeks-pos"     : "right",
                    "on-scroll"     : 1,
                    "on-click-right": "mode",
                    "format": {
                              "months":     "<span color='#ffead3'><b>{}</b></span>",
                              "days":       "<span color='#ecc6d9'><b>{}</b></span>",
                              "weeks":      "<span color='#99ffdd'><b>W{}</b></span>",
                              "weekdays":   "<span color='#ffcc66'><b>{}</b></span>",
                              "today":      "<span color='#ff6699'><b><u>{}</u></b></span>"
                              }
                    },
        "actions":  {
                    "on-click-right": "mode",
                    "on-click-forward": "tz_up",
                    "on-click-backward": "tz_down",
                    "on-scroll-up": "shift_up",
                    "on-scroll-down": "shift_down"
                    }
    },
```

**Comment by max-ishere** [comment]
So can this be fixed? Either find out if there's a `clock.calendar.on-*` and add it to the table or remove it from the example.

**Comment by max-ishere** [comment]
This is what the original issue was about and its not been corrected.

**Comment by LukashonakV** [comment]
Hi @max-ishere , can you please recheck [Example#2](https://github.com/Alexays/Waybar/wiki/Module:-Clock#example)
Is it Ok now?

**Comment by max-ishere** [comment]
I assume the example has been updated to match the code, but the table hasn't been. There's no table that describes how actions work. Some something like

clock:
| actions | see below |

clock: actions:
Any of the on- events can have the following events associated with them
| mode | .... |

--------
Or something like that

**Comment by max-ishere** [comment]
I haven't looked at the code so if you know how that all works please update it.

**Comment by LukashonakV** [comment]
Hi @max-ishere , mouse buttons, which can be used, are described at [Waybar wiki](https://github.com/Alexays/Waybar/wiki/Configuration#module-config). There is no need to repeat this section every module due to its general configuration.

**Comment by max-ishere** [comment]
Where, outside of examples is the usage of the actions table explained? It's just there... What I expected for consistency with other pages is some explanation in the `clock:` table at least.

**Comment by LukashonakV** [comment]
Not sure I got you. .... Actions table - describes clock action can be assigned to the mouse buttons. Table itself provides info about action name - how it should be in the config and the goal,,, what exact action does.. For me it seem quite clear.
These action list belong to the clock functionality. 
Please provide a clear example (it might be any other waybar wiki page) or something... to understand what is the issue here.

**Comment by max-ishere** [comment]
Oh,,,,, I was on mobile and now on desktop I looked through the wiki and finally saw this:
https://github.com/Alexays/Waybar/wiki/Configuration#module-actions-config

Dont remeber seeing that before. I was a little confused.

**Comment by max-ishere** [comment]
I think thats it, I'll close this one
