### ISSUE TITLE
Tray symbols don't stop drawer from closing

### ISSUE THREAD

**Issue by Neolanco** [Alexays/Waybar#3091]
When a tray module is inside a drawer group, hovering over a symbol inside the tray will not stop the tray from closing.  This seems to only affect the actual symbols,  as hovering over a spacing area of the tray will stop the drawer from closing. Increasing said spacing makes this more obvious. 
![tray-drawer-waybar](https://github.com/Alexays/Waybar/assets/89191880/d8c3f8dd-09e9-4502-b021-d83fb484cac0)

(I know my config is a mess atm ^^' )

**Comment by ordy** [comment]
The issue has been reported in #2906

Setting the spacing/padding to 0 on the tray icons is the only way to make it work until it's fixed.
