### ISSUE TITLE
Compile fails - gcc 9 - 0.6.2

### ISSUE THREAD

**Issue by evilbulgarian** [Alexays/Waybar#310]
o' -MF 'waybar@exe/src_modules_battery.cpp.o.d' -o 'waybar@exe/src_modules_battery.cpp.o' -c ../Waybar-0.6.2/src/modules/battery.cpp
../Waybar-0.6.2/src/modules/battery.cpp: In member function 'void waybar::modules::Battery::getBatteries()':
../Waybar-0.6.2/src/modules/battery.cpp:57:27: error: no match for 'operator/' (operand types are 'const std::filesystem::__cxx11::directory_entry' and 'const char [9]')
   57 |           fs::exists(node / "capacity") && fs::exists(node / "uevent") &&
      |                      ~~~~ ^ ~~~~~~~~~~
      |                      |      |
      |                      |      const char [9]
      |                      const std::filesystem::__cxx11::directory_entry
../Waybar-0.6.2/src/modules/battery.cpp:57:60: error: no match for 'operator/' (operand types are 'const std::filesystem::__cxx11::directory_entry' and 'const char [7]')
   57 |           fs::exists(node / "capacity") && fs::exists(node / "uevent") &&
      |                                                       ~~~~ ^ ~~~~~~~~
      |                                                       |      |
      |                                                       |      const char [7]
      |                                                       const std::filesystem::__cxx11::directory_entry
../Waybar-0.6.2/src/modules/battery.cpp:58:27: error: no match for 'operator/' (operand types are 'const std::filesystem::__cxx11::directory_entry' and 'const char [7]')
   58 |           fs::exists(node / "status")) {
      |                      ~~~~ ^ ~~~~~~~~
      |                      |      |
      |                      |      const char [7]
      |                      const std::filesystem::__cxx11::directory_entry
../Waybar-0.6.2/src/modules/battery.cpp:63:27: error: no match for 'operator/' (operand types are 'const std::filesystem::__cxx11::directory_entry' and 'const char [7]')
   63 |           fs::exists(node / "online")) {
      |                      ~~~~ ^ ~~~~~~~~
      |                      |      |
      |                      |      const char [7]
      |                      const std::filesystem::__cxx11::directory_entry
[31/54] x86_64-pc-linux-gnu-g++ -Iwaybar@exe -I. -I../Waybar-0.6.2 -I../Waybar-0.6.2/include -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/include/jsoncpp -I/usr/include/gtkmm-3.0 -I/usr/lib64/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib64/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib64/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib64/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib64/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libdbusmenu-gtk3-0.4 -I/usr/include/libdbusmenu-glib-0.4 -I/usr/include/libnl3 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++17 '-DVERSION=" (" __DATE__ ", branch '"'"''"'"')"' -DHAVE_SWAY -DHAVE_LIBNL -DHAVE_LIBPULSE -DHAVE_DBUSMENU -DHAVE_LIBUDEV -DHAVE_LIBMPDCLIENT -march=skylake -O2 -mabm -mrtm -D_REENTRANT -pthread  -MD -MQ 'waybar@exe/src_modules_clock.cpp.o' -MF 'waybar@exe/src_modules_clock.cpp.o.d' -o 'waybar@exe/src_modules_clock.cpp.o' -c ../Waybar-0.6.2/src/modules/clock.cpp
ninja: build stopped: subcommand failed.
 * ERROR: gui-apps/waybar-0.6.2::x-portage failed (compile phase):
 *   ninja -v -j2 -l4 -C /tmp/portage/gui-apps/waybar-0.6.2/work/waybar-0.6.2-build failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_compile
 *   environment, line 2124:  Called meson_src_compile
 *   environment, line 1229:  Called eninja '-C' '/tmp/portage/gui-apps/waybar-0.6.2/work/waybar-0.6.2-build'
 *   environment, line  818:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=gui-apps/waybar-0.6.2::x-portage'`,
 * the complete build log and the output of `emerge -pqv '=gui-apps/waybar-0.6.2::x-portage'`.
 * The complete build log is located at '/var/log/portage/elog/gui-apps:waybar-0.6.2:20190510-184358.log'.
 * For convenience, a symlink to the build log is located at '/tmp/portage/gui-apps/waybar-0.6.2/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/gui-apps/waybar-0.6.2/temp/environment'.
 * Working directory: '/tmp/portage/gui-apps/waybar-0.6.2/work/Waybar-0.6.2'
 * S: '/tmp/portage/gui-apps/waybar-0.6.2/work/Waybar-0.6.2'

Portage 2.3.62 (python 3.6.5-final-0, default/linux/amd64/17.0/desktop/plasma/systemd, gcc-9.1.0, glibc-2.29-r2, 5.1.0+ x86_64)
=================================================================
System uname: Linux-5.1.0+-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.6
KiB Mem:    16222052 total,   1407632 free
KiB Swap:   16382972 total,  16373184 free
Head commit of repository gentoo: 0d55fb2434771a28e4e0d8a8929bdb6212b4f32b

Head commit of repository go-overlay: 987dc60ab2e71948c4d78ab218b13e020a97e350

Head commit of repository mozilla: 3bd456110c048cda2fe3affba74aa8947af8abe5

Head commit of repository rust: 6ae9b2ccb199db9866e5216bf9d1433aa0c992e9

Head commit of repository steam-overlay: 1724b9a5e972f96dcc1c3d820559ef99ffbbb03a

Head commit of repository tlp: 347474a5abaa0118dfd8f456b70a521a12d66540

Head commit of repository throttled: 937b9ec326a5a2fb3f43c1045dccacd199ddaa91

sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.31.1 p5) 2.31.1
distcc 3.3.2 x86_64-pc-linux-gnu [enabled]
ccache version 3.6 [disabled]
app-shells/bash:          4.4_p23-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.26.2::gentoo
dev-lang/python:          2.7.15::gentoo, 3.6.5::gentoo
dev-util/ccache:          3.6::gentoo
dev-util/cmake:           3.9.6::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.15.1-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.31.1-r4::gentoo
sys-devel/gcc:            6.4.0::gentoo, 9.1.0::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 4.14-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: https://anongit.gentoo.org/git/repo/gentoo.git
    priority: -1000

x-portage
    location: /usr/local/portage
    masters: gentoo
    priority: 0

go-overlay
    location: /var/lib/layman/go-overlay
    sync-type: git
    sync-uri: https://github.com/Dr-Terrible/go-overlay.git
    masters: gentoo
    priority: 50

mozilla
    location: /var/lib/layman/mozilla
    sync-type: git
    sync-uri: https://anongit.gentoo.org/git/proj/mozilla.git
    masters: gentoo
    priority: 50

rust
    location: /var/lib/layman/rust-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo/gentoo-rust.git
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam
    sync-type: git
    sync-uri: https://github.com/anyc/steam-overlay.git
    masters: gentoo
    priority: 50

tlp
    location: /var/lib/layman/tlp
    sync-type: git
    sync-uri: git://github.com/dywisor/tlp-portage.git
    masters: gentoo
    priority: 50

throttled
    location: /usr/local/portage/throttled
    sync-type: git
    sync-uri: https://github.com/erpalma/throttled-overlay.git
    masters: gentoo
    priority: 9999

Installed sets: @steam
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -O2 -pipe -mabm -mrtm"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/easy-rsa /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=skylake -O2 -pipe -mabm -mrtm"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distcc distcc-pump distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LC_ALL="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="en bg"
MAKEOPTS="-j12 -l4"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/tmp"
USE="256-color X a52 aac aalib acpi adns alaw alsa alt-font-width amd64 archive asf aspell async autoipd autoreplace avahi bash-completion bluetooth branding btrfs bzip2 c++0x cairo caps cdda cdinstall cdr chroot cli client-libs crypt cryptsetup cups curl custom-cflags custom-optimization cxx dbus declarative dhcp disk-partition divx divx4linux dolphin dri dri3 dts dvd dvdr egl emerald enca encode epub evdev exif faac farstream ffmpeg flac focused-urgency font-styles fpm fts3 fuse g722 gallium gbm gd gdbm gecko-sdk geoclue geoip gif glamor gles glibc-omitfp glitz gmedia gnome-keyring gnutls google gphoto2 gps gsm gstreamer gudev haptic hardcoded-tables hddtemp hidpi history hwaccel hwdb i3 ibmacpi iconv id3tag imagemagick imap imlib inotify inspector introspection iproute2 ipv6 ithreads jabber javascript jemalloc jpeg jumbo-build kde kdehiddenvisibility kdenlive kdepim kdexdeltas kipi kwallet lame laptop lcdfilter lcms libcaca libinput libkms libnotify libtirpc lm_sensors logrotate lto lzma lzo mad matroska minizip mmx mmxext mng mobi mousewheel mozbranding moznocompose moznoirc moznomail mozsvg mp3 mp4 mpeg mtp multilib musicbrainz mysql ncurses network networkmanager nfsv3 nonfsv4 nptl nsplugin offensive ogg openconnect opengl openmp optimized-qmake otr pam pango pch pcre pdf pgo phonon pic pie plasma png pnp policykit postproc ppds pulseaudio qml qt5 rar rdesktop readline rpc rss rtc rtmp s3tc samba sasl scrobbler sdl seccomp secondary-wheel secure-delete semantic-desktop shared-dricore sip sipim smi smime smtp sna snmp speex spell sqlite srt sse sse2 sse3 ssl ssse3 stroke svc svg swaybar swaybg swaygrab swaylock swaymsg system-cairo system-ffmpeg system-icu system-jpeg system-libvpx system-sqlite systemd telepathy theora thinkpad threads tidy tiff tinfo tordns truetype udev udisks udisks2 ulaw unicode upower urandom usb user-session userlocales v4l2 vaapi vim vim-syntax vnc vorbis vpx wayland wayland-compositor webp widevine widgets wifi windeco wma wmp x264 xattr xcb xcomposite xforms xml xmp xosd xrandr xscreensaver xv xvfb xvid xwayland yahoo zeroconf zip zlib zsh-completion" ABI_X86="64 32" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="pc efi-64" INPUT_DEVICES="keyboard libinput" KERNEL="linux" L10N="en bg" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-1" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby24" USERLAND="GNU" VIDEO_CARDS="intel i965 iris" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by Alexays** [comment]
Fixed with 80e9ea746bc0d744cd60a7916fa3bdd2e39c8f3e
