### ISSUE TITLE
Setting the font size with a span element inside a custom script?

### ISSUE THREAD

**Issue by Spelis** [Alexays/Waybar#3103]
i have this span element:
```<span background="#c0caf5" color="#c0caf5"></span>```

and i was wondering if i could set the font size here as well without using the style.css file

**Comment by vague2k** [comment]
here's an example from my config `<span font='13' rise='-1000'>󰍛</span> {used} GiB`

the font property is self explanatory .

the rise property will add bottom padding to whatever is inside the span if it's value is positive, vice versa if it's negative.

here's the docs for the[ pango markup](https://docs.gtk.org/Pango/pango_markup.html#pango-markup). You might need to scroll down a tiny bit

**Comment by Spelis** [comment]
> here's an example from my config `<span font='13' rise='-1000'>󰍛</span> {used} GiB`
> 
> the font property is self explanatory .
> 
> the rise property will add bottom padding to whatever is inside the span if it's value is positive, vice versa if it's negative.
> 
> here's the docs for the[ pango markup](https://docs.gtk.org/Pango/pango_markup.html#pango-markup). You might need to scroll down a tiny bit

Thanks man! I'll check it out later today (it's 2:30 am) but I was wondering: what does rise do?

**Comment by Spelis** [comment]
Thanks man! I'll check it out later today

**Comment by vague2k** [comment]
By the way, I reccomend marking this as complete If your issue is solved (not that I wanna tell you how to run your life but just saying ¯\\ (ツ) /¯)
