### ISSUE TITLE
Pulseaudio "on-scroll-up" and "on-scroll-down" doesn`t work

### ISSUE THREAD

**Issue by Oqtavus** [Alexays/Waybar#311]
My command in this options doesn`t replaces the default behaviour. However "on-click" and "on-click-right" works well.

Sorry for my bad English.

**Comment by Alexays** [comment]
You defined in you pulseaudio config "on-scroll-up" and thats doesnt work, right?

**Comment by Oqtavus** [comment]
Yes. In others modules "on-scroll-up" works well. Problems with pulseaudio module only.

**Comment by Alexays** [comment]
Fixed with 4f1defe6d5b119cc07b5cb081c2d7d450f61faac
