### ISSUE TITLE
Persittent workspaces seems to be broken

### ISSUE THREAD

**Issue by xiro-codes** [Alexays/Waybar#3112]
after update to 0.10.0:
![bug](https://github.com/Alexays/Waybar/assets/146094155/b361c354-162a-4135-8e07-882e131fb8c2)

before: 
![bug](https://github.com/Alexays/Waybar/assets/146094155/d8c609dd-1e56-48b3-b53a-47921d89f0aa)

config:
https://app.warp.dev/block/fRkBkruidxbTZdY0UUU5nv

**Comment by ordy** [comment]
It's been fixed in #3037

Not released yet, but you can compile from master and update your package if you need it now.

**Comment by xiro-codes** [comment]
Np
