### ISSUE TITLE
Add direction css property

### ISSUE THREAD

**Issue by nakibrayan3** [Alexays/Waybar#3119]
My system Locale is `ar_SA.UTF-8` (Arabic), and because Waybar is made with gtk it's rendered in reverse for RTL languages.

This is actually preferred because the UI make more since like this, but the problem here is that the workspace index numbers are ordered in reverse, 

They look like this:
[ 9 ] [ 8 ] [ 7 ] [ 6 ] [ 5 ] [ 4 ] [ 3 ] [ 2 ] [ 1 ]

Instead of this:
[ 1 ] [ 2 ] [ 3 ] [ 4 ] [ 5] [ 6 ] [ 7 ] [ 8 ] [ 9 ]

and the numbers in the keyboard are ordered like the second example, so it's confusing to have the numbers ordered in the opposite direction of what you see on the screen, and i all ways select the wrong workspace because of it.

this is usually easy to fix, just use `direction: ltr;` CSS property in `#workspaces`.

but when i do that i get this error: `'direction' is not a valid property name`

I think this CSS property is available in gtk, so i don't know why i can't use it in waybar?

**Comment by ordy** [comment]
GTK 3 does support directions but I don't think there is a gtk css property available for that.

There is a selector for direction tho: like `#workspaces:dir(ltr)` when you want to only style modules that follow said rule.

Checking the workspaces doc, it looks like there is an `alphabetical_sort` option, but it's either broken or I can't seem to make it work.

**Comment by nakibrayan3** [comment]
yes this works, thank you :)
