### ISSUE TITLE
[openrc] waybar not starting

### ISSUE THREAD

**Issue by end3r-man** [Alexays/Waybar#3124]
`bfd:[enderman]:~$ waybar
[2024-04-08 18:53:31.929] [info] Using configuration file /etc/xdg/waybar/config.jsonc
[2024-04-08 18:53:31.931] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2024-04-08 18:53:31.931] [info] Using CSS file /etc/xdg/waybar/style.css
[2024-04-08 18:53:31.937] [warning] Mapping is not an object
[2024-04-08 18:53:31.947] [error] media stopped unexpectedly, is it endless?
socket(): Too many open files
fork(): Cannot allocate memory
shared memfd open() failed: Too many open files
Failed to create secure directory (/run/user/1000/pulse): Too many open files
socket(): Too many open files
fork(): Cannot allocate memory
shared memfd open() failed: Too many open files
Failed to create secure directory (/run/user/1000/pulse): Too many open files`

installed xdg-desktop-portal and wlr, gtk still having the same issue how to fix this

**Comment by end3r-man** [comment]
fixed

**Comment by urystem** [comment]
> fixed

How?)

**Comment by end3r-man** [comment]
> > fixed
> 
> How?)

after ruining pipewire its worked

**Comment by dkragen** [comment]
Not really clear.  Did you really mean _ruining_ pipewire?  Or _running_ pipewire?  And in either case, how?

**Comment by end3r-man** [comment]
> Not really clear. Did you really mean _ruining_ pipewire? Or _running_ pipewire? And in either case, how?

running pipewire

**Comment by end3r-man** [comment]
> Not really clear. Did you really mean _ruining_ pipewire? Or _running_ pipewire? And in either case, how?

my case the media plugin need audio service to get the vol info, and the pipewire doesn't started as a startup application after adding that to sway config its working fine add 

` exec pipewire && exec wireplumber `

**Comment by justaCasualCoder** [comment]
I had to run `pipewire` and `pipewire-pulse`:
```bash
pipewire &
pipewire-pulse
```
Tested on Alpine Linux Edge

**Comment by end3r-man** [comment]
> I had to run `pipewire` and `pipewire-pulse`:
> 
> ```shell
> pipewire &
> pipewire-pulse
> ```
> 
> Tested on Alpine Linux Edge

ok ill try it
