### ISSUE TITLE
Font changed after NixOS update

### ISSUE THREAD

**Issue by ArtemChandragupta** [Alexays/Waybar#3135]
Yesterday I updated my NixOS without changing any font-related things, but my waybar font have changed from this:
![image](https://github.com/Alexays/Waybar/assets/90765302/8c472c3e-01eb-4ab2-964d-16b0ede6f260)
to this:
![swappy-20240413_134507](https://github.com/Alexays/Waybar/assets/90765302/2f574a62-f6a4-4389-a13e-d54cd26e87cc)
New font seems to be one of nerdfonts, the old font seemed to be the default, but I don't know for sure, so I'll be glad if I find out what kind of font it is.

I have this in my waybar config:
```
* {
          border: none;
          font-family: JetBrainsMono Nerd Font, sans-serif;
          font-size: 14px;
        }
```
and this are my system fonts:

```
fonts.packages = with pkgs; [
  font-awesome
  iosevka
  material-design-icons
  nerdfonts
];
```

**Comment by ordy** [comment]
Because your nerd font has been patched with the new version.

left: old version (from a 5 months old copy of JetBrainsMono Nerd Font)
right: current version

![image](https://github.com/Alexays/Waybar/assets/22659443/748bf78c-3ddf-43fc-83ef-6d48555555b0)

**Comment by ArtemChandragupta** [comment]
Are there any good ways to get the old font back, or is it better to rely on upstream?

**Comment by ordy** [comment]
I'm not familiar with nix but on arch if I needed an older version of the font to display on waybar, I'd just go on NF's repo (https://github.com/ryanoasis/nerd-fonts/commits/master/patched-fonts/JetBrainsMono) and view the code on a previous commit to download to files and then simply copy the TTF to my `.local/share/fonts` folder.

However that means not getting any update on new icons.

Another option would be to use the base JetBrains Mono and another font with old/different glyphs as a fallback.
