### ISSUE TITLE
sway/window not working sometimes

### ISSUE THREAD

**Issue by jparsert** [Alexays/Waybar#314]
As the title says. sway/window only shows the title of firefox and its tabs. It does not show the title of a terminator session or VS code, thunderbird or anything else.

**Comment by Alexays** [comment]
Sway/mode don't show any titles, do you mean sway/window?

**Comment by jparsert** [comment]
Yes, of course i fixed it.

**Comment by TheKiteEatingTree** [comment]
sway/window seems to stop working for me as soon as I introduce a vertical split.  I think it has to do with the layout, not the applications involved

**Comment by TheKiteEatingTree** [comment]
Awesome, thanks! That fixes it for me. Just to clarify for anyone else the option actually seems to be `"all-outputs": true`

**Comment by jparsert** [comment]
This does not seem to be fixing it for me adding the following in the waybar config:
	"sway/window" : {
		"all-outputs": true
	},

**Comment by jparsert** [comment]
do I need to update waybar to the newest version (git version) for it to work?

**Comment by Alexays** [comment]
@jparsert Show me your waybar config file :)

**Comment by Alexays** [comment]
Should be fixed with 486b5a5d3897faefbe778b776f0914365344efbe
