### ISSUE TITLE
Clock widget not working properly

### ISSUE THREAD

**Issue by kernaltrap8** [Alexays/Waybar#3170]
The clock widget in my waybar is not working correctly.
![image](https://github.com/Alexays/Waybar/assets/94473358/f22506b8-a3fb-47d6-9727-f0c02d2f7273)
I have edited the config to be this:
```
 "clock": {
        "timezone": "America/New_York",
        "tooltip-format": "<big>{:%I:%M %p}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": "{:%Y-%m-%d}"
    },
````
and it is still in 24 hour format. I have no other configs other than the one in `/etc/xdg/waybar/config.jsonc`.

I am using the Hyprland WM on Gentoo.

**Comment by ordy** [comment]
You are editing the tooltip tho, not the clock format itself :thinking: 

Add `"format": "<big>{:%I:%M %p}</big>",`

**Comment by kernaltrap8** [comment]
> You are editing the tooltip tho, not the clock format itself 🤔
> 
> Add `"format": "<big>{:%I:%M %p}</big>",`

haha okay, my mistake then

**Comment by kernaltrap8** [comment]
oh also, is there a way i can make a widget so i can display the current song playing from Spotify? or really any media source. i have moved to wayfire and kinda miss that feature from KDE

**Comment by ordy** [comment]
Of course, check the mpdris module. [](https://github.com/Alexays/Waybar/wiki/Module:-MPRIS)
