### ISSUE TITLE
Hyprland modules didn't work since socket is moved from /tmp/hypr to XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by mintyleaf** [Alexays/Waybar#3179]
https://github.com/hyprwm/Hyprland/pull/5788

> For those users, I'd recommend checking whether `$XDG_RUNTIME_DIR/hypr` exists. If yes, use that, if not, use the old `/tmp/hypr`

`ln -s $XDG_RUNTIME_DIR/hypr /tmp/hypr` can be used as workaround

**Comment by mintyleaf** [comment]
https://github.com/Alexays/Waybar/pull/3183

merged

**Comment by AFAgarap** [comment]
![image](https://github.com/Alexays/Waybar/assets/11130276/a3b9abfc-2fba-4f1e-a267-f5627b6fe069)
