### ISSUE TITLE
Hover effects on tray icons don't work

### ISSUE THREAD

**Issue by Kommynct** [Alexays/Waybar#3182]
```
#tray > .active {
	opacity: 0.8;
}
#tray > .active:hover {
	opacity: 1;
}
```
All this does is make the opacity of the tray icons permanently 0.8

@haug1

**Comment by haug1** [comment]
I think this is expected behavior. Would probably have to add hover handling for tray icons specifically inside the tray module. (So this is a new feature request.)

**Comment by zjeffer** [comment]
@Kommynct This should be fixed now
