### ISSUE TITLE
workspace number not showing

### ISSUE THREAD

**Issue by AFAgarap** [Alexays/Waybar#3184]
![image](https://github.com/Alexays/Waybar/assets/11130276/835c2fd9-e87e-40ab-ad93-4709385156e3)

latest waybar and latest hyprland

**Comment by dxy2233** [comment]
same

**Comment by AFAgarap** [comment]
I'm already using a manually built waybar based on https://github.com/Alexays/Waybar/commit/f41458ea24a57bb71b629089396c31fe4dd97f1c

**Comment by AFAgarap** [comment]
my bad. it's ok now. thanks
