### ISSUE TITLE
Waybar Can't Connect to Hyprland Socket

### ISSUE THREAD

**Issue by AFWL** [Alexays/Waybar#3187]
[A recent commit](https://github.com/hyprwm/Hyprland/commit/a5a648091760ac002120fab18247e5292b6482de) has moved the Hyprland IPC socket to $XDG_RUNTINE_DIR/hypr. Waybar can no longer connect to the old socket as it doesn't exist.

**Comment by SwayKh** [comment]
Check #3184 and #3179
