### ISSUE TITLE
Taskbar doesn't respond to switching workspaces

### ISSUE THREAD

**Issue by hdm9527** [Alexays/Waybar#3200]
OS: Arch Linux
DE: Hyprland

The taskbar switching workspaces in the stable version of hyprland works, for some reason I switched to the `hyprland-git` version and the taskbar clicking on the icon doesn't switch workspaces.

https://github.com/Alexays/Waybar/assets/39702328/9459e463-2690-4e9a-80f1-ecb43883e74d

**Comment by random2907** [comment]
add focus_on_activate=true in misc to fix it in hyprland.conf

**Comment by hdm9527** [comment]
> add focus_on_activate=true in misc to fix it in hyprland.conf

Thanks. It works fine.
