### ISSUE TITLE
How can I set font size for icons in `workspace` ?

### ISSUE THREAD

**Issue by PILIHU2022** [Alexays/Waybar#3207]
I want to set font size for icons because they are too small to see, like this:
![image](https://github.com/Alexays/Waybar/assets/100511118/c117a0bf-30e0-4500-9791-4c72da6fe6a4)
and I set it in `style.css` with ```font-size: 25px;```. But I  doesn't work, how can I do it?

This is my style.css:
https://github.com/PILIHU2022/My-dotfiles/blob/6a1f74bf0834de886a0874215c5ae96d2ef6a017/Config/hypr/waybar/style/style-dark.css

**Comment by ordy** [comment]
There are different ways, either using the specific selectors on the buttons

```
#workspaces button.active label,
#workspaces button.persistent label {
  font-size: 25px;
}
```
Just on label to make it default to everything

```
#workspaces label {
  font-size: 25px;
}
```

Or with pango markups in your config file.

```
"format-icons": {
      "1": "<span font='25'>1</span>"
      ...
}
```

**Comment by PILIHU2022** [comment]
> There are different ways, either using the specific selectors on the buttons
> 
> ```
> /* .active on hyprland, .focused on sway */
> #workspaces button.active label,
> #workspaces button.persistent label {
>   font-size: 25px;
> }
> ```
> Just on label to make it default to everything
> 
> ```
> #workspaces label {
>   font-size: 25px;
> }
> ```
> 
> Or with pango markups in your config file.
> 
> ```
> "format-icons": {
>       "1": "<span font='25'>1</span>"
>       ...
> }
> ```

OK, thank you! I will try the ways later.
