### ISSUE TITLE
different format-icons for battery module

### ISSUE THREAD

**Issue by AlecTroemel** [Alexays/Waybar#321]
I'd like to be able to use a different set of icons for when my battery is charging, something like this

```json
    "battery": {
        "format": "{capacity}% {icon}",
        "format-icons": {
            "charging": ["", "", "", "", "", "", ""],
            "default": ["", "", "", "", "", "", "", "", "", ""]
        },
        "interval": 30,
        "states": {
            "warning": 25,
            "critical": 10
        },
        "tooltip": false
    },
```

is this currently possible? The exact config above is not working for me but I wouldn't be surprised if I had a typo

**Comment by Alexays** [comment]
Done with 4b4b74db0c29e7e3ef1e60899d3cf916d023bd5d

**Comment by Eriarer** [comment]
this is mine:
`"battery": {
        "states": {
           "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format-charging": "{icon} {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": {
            "default":["!󰂎!", "!󰁺!", "!󰁻", "!󰁼", "󰁽 ", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"],
            "charging":["󰢜", "󰂆", "󰂇", "󰂈", "󰢝", "󰂉", "󰢞", "󰂊", "󰂋", "󰂅"]
        },
        "tooltip-format": "{capacity}%",
        "min-length": 5
    }
`
