### ISSUE TITLE
New release 10.3 needed

### ISSUE THREAD

**Issue by JohnRTitor** [Alexays/Waybar#3212]
Since Hyprland released 40.0 update just today, programs like Waybar that listen to sockets are officially broken.

 In Waybar, this is particular creates a problem as workspaces are not visible at all. It did get fixed in #3183 but it still needs a release, before Hyprland releases reaches distros.

**Comment by CelestialCrafter** [comment]
+1, update the nix flake too please

**Comment by JohnRTitor** [comment]
For me, the workspaces tab is broken in the latest git commit (231d6972d7a023e9358ab7deda509baac49006cb), does this happen to you too? This is not observed in 79ae530bd29cb561d6f48773e894dd62fe353b7f.

**Comment by Alexays** [comment]
Just released a new version 0.10.3
