### ISSUE TITLE
CI got stuck on `clang-tidy` action

### ISSUE THREAD

**Issue by haug1** [Alexays/Waybar#3214]
`clang-tidy.yaml` github action got stuck on step "clang-tidy"(implemented by 3rd party `cpp-linter/cpp-linter-action@v2.9.1`)  got stuck, it says "Nothing to restart" in the output and nothing happens. Unfortunately I have no way of stopping the workflow runs:
https://github.com/Alexays/Waybar/actions/runs/8960847161/job/24607814715
https://github.com/Alexays/Waybar/actions/runs/8960701502/job/24607501750

Sorry to have caused this.. :sweat_smile:

**Comment by Alexays** [comment]
Just disabled this workflow atm

**Comment by haug1** [comment]
I've spotted more instances of the workflow running right now. You may want to cancel them, @Alexays.
