### ISSUE TITLE
feature request: add config line number in warning and error messages

### ISSUE THREAD

**Issue by mttbx** [Alexays/Waybar#3217]
add config line number if possible when there's an error in waybar config.

**Comment by zjeffer** [comment]
JSON parsing errors already show the line number if you do something like this:

```jsonc
{
    "this-key-has-novalue": ,
    "this-key-does": true
}
```
which shows:
```
./build/waybar --config config.jsonc
[2024-05-06 19:52:13.594] [info] Using configuration file config.jsonc
[2024-05-06 19:52:13.595] [error] Error parsing JSON: * Line 2, Column 27
  Syntax error: value, object or array expected.
```

What other kind of config errors do you mean?

**Comment by mttbx** [comment]
I don't remember what error it is. But some errors are not shown with line number.
