### ISSUE TITLE
Need to adjust swarbar's opacity

### ISSUE THREAD

**Issue by blakemcbride** [Alexays/Waybar#3226]
I am using the following to make swaybar disappear and only appear when I press the $mod key:

sway config:
```
bar {
    swaybar_command waybar
    position top
    hidden_state hide
    mode hide
    modifier Mod4
}
```
swaybar config:
```
    "ipc": true,
```
The only problem I have with it is the bar's opacity. I can still see what's behind it. I don't like that. I need a way to adjust swaybar's opacity.

**Comment by haug1** [comment]
You can easily set waybar's opacity in your `style.css`, please read the documentation on how you configure and style the app, if you haven't already. You may want to check and set the `background-color` and `opacity` setting on `window#waybar` specifically.

**Comment by blakemcbride** [comment]
Thank you!  I got it to work.

Just a comment -

Fleshing out "man waybar-styles"

And being more explicit about what  mode indicators and workspace buttons are in "man 5 sway-bar" would be real helpful.

Thanks!

**Comment by haug1** [comment]
> Fleshing out "man waybar-styles"
> And being more explicit about what mode indicators and workspace buttons are in "man 5 sway-bar" would be real helpful.

It's a good comment. Pretty sure I can speak on @Alexays' behalf and welcome you to make a PR with the improvements you see fit. :slightly_smiling_face:

**Comment by blakemcbride** [comment]
Given my lack of knowledge on this topic and the time I already spend on open-source projects ([https://github.com/blakemcbride](https://github.com/blakemcbride)), it will not be possible for me to make these changes.  But thanks for all of the help!  I really, really love sway and swaybar! 🙂
