### ISSUE TITLE
[feature] Network down-/up-speed

### ISSUE THREAD

**Issue by piu130** [Alexays/Waybar#323]
Would be nice to be able to configure the network module to display the down- and up-speed of the interface.

I don't know how you get the network information (I can't read C++) but according to [this](https://askubuntu.com/questions/913887/get-current-wireless-download-and-upload-speed-on-the-command-line) post we can calculate it with information from `/proc/net/dev` for example.

**Comment by Alexays** [comment]
Done in #328
