### ISSUE TITLE
Decoupling module backend and UI

### ISSUE THREAD

**Issue by haug1** [Alexays/Waybar#3233]
I've noticed that if I have a custom module that I've configured to execute once, it actually executes twice if I have two displays connected. It would be nice (and it's a big ask in terms of implementation, I think), if the "backend" of the modules were decoupled from the UI, the backend could send the signals to all the UI consumers instead of the current flow, where the UI and the module backend is strictly coupled together and render update commands need to be executed per UI window instance not allowing separation like that.

**Comment by apiraino** [comment]
related to #2772

**Comment by haug1** [comment]
Perfect, and you describe it more to the point. I'll close this one.
