### ISSUE TITLE
Fedora missing release 0.10.3

### ISSUE THREAD

**Issue by coquer** [Alexays/Waybar#3238]
Hi boiz

Do you have plan to push the latest release to Fedora repos? https://packages.fedoraproject.org/pkgs/waybar/waybar/

Seems to be missing.

Cheers

**Comment by ordy** [comment]
That's the fedora package maintainers responsibility, not Waybar.

So either wait, build from source or contact them at `waybar-maintainers@fedoraproject.org`

Should not take too long for them to push an update though, so it's probably better to just wait a few days.

**Comment by coquer** [comment]
Thanks a lot :)
