### ISSUE TITLE
Battery module rewrite

### ISSUE THREAD

**Issue by Alexays** [Alexays/Waybar#324]
Using udev
Will closes #229 #237

**Comment by unresolvedsymbol** [comment]
This should be an added module/mode because not everyone has upower

**Comment by lockywolf** [comment]
At the moment, if a battery is not present, the only thing the module does is complain in the log:
```
[warning] module battery: Disabling module "battery", No batteries.
```

May I suggest that that module present itself in a deliberately "broken" state, rather than silently failing, in order to urge the user to resolve the issue?
