### ISSUE TITLE
Hyprland workspaces not showing

### ISSUE THREAD

**Issue by definetly-not-carl** [Alexays/Waybar#3287]
I'm on the last available version of Fedora 39, with its relative latest packages for hyprland and waybar. Since the update I cannot see any workspace (I've already changed from wlr/workspaces to hyprland/workspaces (or whatever it is called) and it gives me the following error if I try to force it ```[error] Hyprland IPC: Couldn't connect to /tmp/hyprcba1ade848feac44b2eda677503900639581c3f4_1716231492_362678026/.socket.sock. (3)```.
Does anybody know what is the problem?

If it matters I have been using the same rice on this Lenovo T14 for one year and it's the first time it gives me this problem. As you can see no workspace is shown. And it is included in the modules

![20240520_21h48m19s_grim](https://github.com/Alexays/Waybar/assets/106332590/4c0bc4e7-252e-4c48-a8bb-6c42d0f758d5)

**Comment by Atemo-C** [comment]
Same thing here since I updated my NixOS system.
```log
[2024-05-21 13:09:04.375] [error] Hyprland IPC: Unable to connect?
[2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
[2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
[2024-05-21 13:09:04.375] [error] Monitor 'DP-1' does not have an ID? Using 0
[2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
[2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
[2024-05-21 13:09:04.376] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
```
Same error keeps appearing when I try to interact with my virtual desktops on the bar. They also show as empty.
![image](https://github.com/Alexays/Waybar/assets/160250128/f5c2ef7c-13f1-4181-a459-590e940e16b2)

I would have to guess this is related to [this issue](https://github.com/Alexays/Waybar/issues/3280).

**Comment by agentx3** [comment]
> Same thing here since I updated my NixOS system.
> 
> ```
> [2024-05-21 13:09:04.375] [error] Hyprland IPC: Unable to connect?
> [2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
> [2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
> [2024-05-21 13:09:04.375] [error] Monitor 'DP-1' does not have an ID? Using 0
> [2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
> [2024-05-21 13:09:04.375] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
> [2024-05-21 13:09:04.376] [error] Hyprland IPC: Couldn't connect to /tmp/hypr/2ccd45a84475fab46c6fecd2fe226d3173104743_1716286760_140508043/.socket.sock. (3)
> ```
> 
> Same error keeps appearing when I try to interact with my virtual desktops on the bar. They also show as empty. ![image](https://private-user-images.githubusercontent.com/160250128/332401900-f5c2ef7c-13f1-4181-a459-590e940e16b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODgyMTcsIm5iZiI6MTcxNjQ4NzkxNywicGF0aCI6Ii8xNjAyNTAxMjgvMzMyNDAxOTAwLWY1YzJlZjdjLTEzZjEtNDE4MS1hNDU5LTU5MGU5NDBlMTZiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxODExNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmY2ZTczYTdlNGUyYmYxNzZmYTZkNDYyYTgxZGYxMjM1N2EyNmQwOTllN2Q1Njg1NjFlNzNmOTQ4ZWM0YWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pmco8c5Ru3weNkasFebUXXsHA_vg-i6uwWL30ubOmpw)
> 
> I would have to guess this is related to [this issue](https://github.com/Alexays/Waybar/issues/3280).

Make sure to check your versions, there might be a mismatch between Hyprland versions and waybar. I'm running Hyprland 0.40 and waybar 0.10.3 and it works fine for me (I'm on 24.05-beta branch FYI).

**Comment by Atemo-C** [comment]
> Make sure to check your versions, there might be a mismatch between Hyprland versions and waybar. I'm running Hyprland 0.40 and waybar 0.10.3 and it works fine for me (I'm on 24.05-beta branch FYI).


Hyprland on NixOS using the unstable package;
`0.40.0-unstable-2024-05-12`

Waybar on NixOS using the stable package;
`0.9.24`

I will try to use Waybar from the unstable branch (`0.10.3`) and I will report back if this does fix the problem or not.

**Comment by Atemo-C** [comment]
Changing to the latest version available to me does indeed fix the issue for me. Thank you for that simple suggestion that I had not thought about, @agentx3.

**Comment by definetly-not-carl** [comment]
UPDATE: with the upgrade to F40, the semi-circular tab to the left ceased to exist. I hope that an update can fix this problem
