### ISSUE TITLE
"error while loading shared libraries: libiniparser.so.1" after latest iniparser update

### ISSUE THREAD

**Issue by Koko2110** [Alexays/Waybar#3288]
Hello,

it seems today's iniparser update (4.2.1-1 -> 4.2.2-1) breaks waybar in some way. I am getting the error:

`waybar: error while loading shared libraries: libiniparser.so.1: cannot open shared object file: No such file or directory`

I can confirm that by downgrading iniparser everything goes back to how it should be. If it is of significance, I am on Arch Linux and hyprland.

**Comment by mutoroglin** [comment]
I had the problem that even after the recompilation and installation of the fixed libcava waybar still reported the error with the missing iniparser library. A recomilation of waybar fxed the problem for me.

**Comment by LukashonakV** [comment]
I  guess the issue is solved here.

**Comment by Koko2110** [comment]
The libcava update on the following day seemed to solve it for me too. I held out on closing the issue, since the maintainer of the AUR package had left a comment stating that it was a temporary patch and was awaiting feedback, but it seems it's all good now.

Thanks to everyone who helped out!
