### ISSUE TITLE
Multi-battery setup

### ISSUE THREAD

**Issue by t184256** [Alexays/Waybar#329]
Can I have two battery plugins active at the same time? If yes, how?

**Comment by Alexays** [comment]
Look at the default config file :)

**Comment by t184256** [comment]
Ouch. Sorry for the noise.

**Comment by Alexays** [comment]
No problem, you can also look at the wiki, specialy this [part](https://github.com/Alexays/Waybar/wiki/Configuration#multiple-instances-of-a-module).

**Comment by t184256** [comment]
Cool, got it working. The only thing missing is probably hot-plug support, will track #237.
