### ISSUE TITLE
Privacy module does not hide itself when not in use [Bug]

### ISSUE THREAD

**Issue by missonserch** [Alexays/Waybar#3298]
Privacy module does not hide itself when not in use when "audio-out" is omitted from configuration.
Config of privacy module:

```
  "privacy": {
    "icon-spacing": 14,
    "icon-size": 14,
    "transition-duration": 250,
    "modules": [
      {
        "type": "screenshare",
        "tooltip": true,
        "tooltip-icon-size": 24
      },
      //{
      //  "type": "audio-out",
      //  "tooltip": true,
      //  "tooltip-icon-size": 24
      //},
      {
        "type": "audio-in",
        "tooltip": true,
        "tooltip-icon-size": 24
      }
    ]
  },
```

(Opened OBS)
![20240524_18h16m24s_grim](https://github.com/Alexays/Waybar/assets/142168463/0c6a818e-b38f-4977-bff4-c667c3a1c9a0)
(no software is recording sound/screen or outputting audio)
![20240524_18h13m41s_grim](https://github.com/Alexays/Waybar/assets/142168463/2277b270-faae-48b4-8f21-41967fe4ddf9)

If "audio-out" module is included in the config, privacy module disappears from waybar as expected

**Comment by missonserch** [comment]
forgot to mention, I use arch with hyprland, ask me if you need more info

**Comment by joshuajeschek** [comment]
I can confirm this, I also use arch with hyprland. I don't think that should matter tho?

**Comment by missonserch** [comment]
> I can confirm this, I also use arch with hyprland. I don't think that should matter tho?

Arch probably don’t matter, hyprland might, however, in general pointing out your environment is good practice when reporting a bug.

**Comment by RobertMueller2** [comment]
Which version are you using? This was recently changed with 4fbd4f212a80009e92d179f9e96a50562891c2e8. I have not attempted a repro, but the code looks to me like it *should work*. ;)

**Comment by RobertMueller2** [comment]
Fair enough. Fwiw, the commit is newer than last waybar release (0.10.3). I have no knowledge about what specific distro packages have or do, though.

**Comment by joshuajeschek** [comment]
I just installed waybar throught the AUR, it does actually work now. I guess it will just take a bit until it arrives in the repo :)

**Comment by missonserch** [comment]
Upgraded the package, issue resolved.
