### ISSUE TITLE
sway mode not visualized

### ISSUE THREAD

**Issue by ConYel** [Alexays/Waybar#3335]
I moved from swaybar to waybar lately and this custom mode I was using before it is not visible with waybar anymore:

```
set $mode_system System (e)xit, (s)leep, (r)eboot, (p)oweroff
mode "$mode_system" {
    bindsym e exec swaymsg exit, mode "default"
    bindsym r exec systemctl reboot, mode "default"
    bindsym p exec systemctl poweroff, mode "default"
    bindsym s exec systemctl suspend, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
```

Any work around?
thank you for maintaining this project!

**Comment by RobertMueller2** [comment]
Is the lack of display specific to this particular mode, or better: are other modes displayed correctly?

What's your configuration and style for the sway/mode module, please?

**Comment by ConYel** [comment]
Hello!
I have it on my sway/config directly.
there isn't any style currently.
With swaybar it was displayed on the top of the window.

**Comment by RobertMueller2** [comment]
Well yes, that configures a mode in sway. But in order for the mode to be displayed on your Waybar once the mode is activated, Waybar's sway/mode module needs enabling in the Waybar config, please check: https://github.com/Alexays/Waybar/wiki/Module:-Sway#mode

Do you have a Waybar user config, or are you using a distro config?

**Comment by ConYel** [comment]
Ah! So I have to configure it on waybar to be seen!
Thank you for the clarification!
So how can I add it?
Yes here it is:
```
{
    "layer": "top",
    "position": "top",
    "height": 24,
    "margin-left": 5,
    "margin-right": 5,
    "margin-top": 5,
    "modules-left": ["sway/workspaces"],
    "modules-center": [],
    "modules-right": ["network", "temperature", "cpu", "memory", "battery", "clock"],
    "sway/workspaces": {
        "disable-scroll": true,
        "disable-click": true,
    },
    "tray": {
        "spacing": 10,
    },
    "clock": {
        "format": "{:%a %Y %b %d %R}"
    },
    "custom/germany": {
        "format": "{}",
        "exec": "TZ=Europe/Berlin date \"+%H:%M %Z\"",
        "interval": 30,
    },
    "cpu": {
        "format": " {usage}%"
    },
    "memory": {
        "format": " {}%"
    },
    "temperature": {
        "critical-threshold": 75,
        "format": " {temperatureC}°C"
    },
    "battery": {
        "bat": "BAT0",
        "full-at": 95,
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 15
        },
        "format": "{icon} {capacity}%",
        "format-icons": ["", "", "", "", ""]
    },
    "network": {
        "format-wifi": " {essid}",
        "format-disconnected": "⚠ Disconnected"
    },
    "pulseaudio": {
        "format": "{icon} {volume}%",
        "format-muted": "",
        "format-icons": {
            "headphones": "",
            "default": ["", ""]
        },
        "on-click": "pavucontrol"
    },
}

```

**Comment by RobertMueller2** [comment]
Thanks for posting your config.

Basically, waybar has three sections where modules can appear, "modules-left", "modules-center", "modules-right". You can add "sway/mode" to either of those lists. I think a good place for it is next to the workspaces module on the left. So for that you'd change
```
"modules-left": ["sway/workspaces"],
```
to
```
"modules-left": ["sway/workspaces", "sway/mode"],
```

Then, you can add a config section, e.g. between "sway/workspaces" and "tray" you could add something like
```
    "sway/mode": {
        "format": "<span style=\"italic\">{}</span>"
    },
```
If you don't add it, there should be a default config without any formatting, but displaying the mode (I think).

Depending on what styling you use, you might also want to add a css configuration for `#mode` to your waybar style.css file.

One additional hint: the modules-center section is a good place for a window or task module if you want to use that, e.g. sway/window or wlr/taskbar.

**Comment by ConYel** [comment]
Thank you very much for all this information!
I used the modules/left as you suggested and worked fine!

**Comment by RobertMueller2** [comment]
Good to hear it worked. :)
If your issue is solved, can you please close it? Thank you! :)
