### ISSUE TITLE
Custom modules: ability to hide a module?

### ISSUE THREAD

**Issue by vikanezrimaya** [Alexays/Waybar#3341]
I have a persistent module that uses JSON output to Waybar. I want it to be able to hide itself when the module thinks it has nothing useful to display — however, after reviewing [src/modules/custom.cpp](https://github.com/Alexays/Waybar/blob/master/src/modules/custom.cpp) I found no obvious way for a JSON module to hide itself (other than exiting with a non-zero exit code, being restarted and not producing any output — but I would like to avoid that for efficiency reasons).

Possible API design:
 - `{}` hides the module
 - `{"display": false}` (a new key) hides the module until a new update arrives where it is unset or set to `true`
 - empty line hides the module until a non-empty line is produced

**Comment by RobertMueller2** [comment]
I'm not 100% sure I understand it correctly, but when I return {} from a continuous script, the module does disable its event box. Is that not what you want to achieve?

E.g. test-output2.sh
```
#!/bin/sh

TEXT="";
TOOLTIP="DND is enabled";

if [ -e /home/user/tmp/testxyz ];then
  TEXT="";
  TOOLTIP="Notifications are enabled";
  printf '{"text": "%s", "tooltip": "%s"}\n' "$TEXT" "$TOOLTIP"
fi

printf '{}'
```

test config:
```
{
    "layer": "top", // Waybar at top layer
    "position": "top", // Waybar position (top|bottom|left|right)
    "height" : 50,
    "modules-center": ["custom/test-output"],

    "custom/test-output": {
      "exec": "/home/user/tmp/test-output2.sh",
      "return-type":"json",
      "interval": 1,
    },
}
```

test style:
```
window {
    background-color: transparent;
}

#custom-test-output {
    color: #ffffff;
    background-color: #ff0000;
}
```

testxyz exists: ![satty-20240630-11:52:26](https://github.com/Alexays/Waybar/assets/29629287/cdcb3266-045c-4bc4-b6a9-22d9b36fa92b)
testxyz gone: ![satty-20240630-11:53:29](https://github.com/Alexays/Waybar/assets/29629287/578a8ccb-ee14-42ba-b48b-c3b620f782da)

**Comment by RobertMueller2** [comment]
Thanks for elaborating. Can you try #3395 with ` "hide-empty-text": true,`?

I should imagine the name of the config option is subject to change if the PR is merged. ;)

**Comment by RobertMueller2** [comment]
I had no idea, thanks. :D
