### ISSUE TITLE
Regression in clock module formatting

### ISSUE THREAD

**Issue by exit91** [Alexays/Waybar#3347]
Regression from Version 0.9.24 to version 0.10.3:

The clock module shows an empty string, instead of the time according to the custom formatting.

```json
    "clock": {
        "format": "{:󰃭 %a %d %b 󰅐 %H:%M}"
    },
```

Removing the unicode characters `󰃭` and `󰅐` preceding `%a` and `%H` makes the rendering work again.

Error log:
```
[2024-06-10 09:21:26.734] [error] clock: chrono format error: no '%' at start of chrono-specs
[2024-06-10 09:21:26.838] [error] clock: chrono format error: no '%' at start of chrono-specs
```

**Comment by khaneliman** [comment]
Hmm.. assuming it has to do with the chrono API change. https://github.com/Alexays/Waybar/commit/86a38980e4a2eb242379b9221b06784d3e0d3eef But, I'm curious if you git-bisect if that's true..

**Comment by exit91** [comment]
I did a git bisect, but I had to skip those commits which didn't build via `nix build`

Here's the final output

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c4907a6065f6c14e9ea880bf92fc7c8356fd4ec0
32e241dc477fc26cbc044b1f3b76b0109eec5698
f228c138021e5af1c99bd96d3915cb95bc723af7
19f3ce6f856c11735ba0781d8bf21a49f84c4840
cc084f5f86776b3b5b9708a99bed49b991eb48af
e30ddda23a6c0e128c8b58c7ba095b845fd63f6e
38634a0ca85dcc6f35aab8c314bc892366620c9d
abd7ca2a1efb451bd27c01687621d96e1a8e1cb8
c6cbf57a386fce915fa57b31601ba38cd2ac8c58
fe0716bf398a69188a20f871918f555c40ae86d1
9d95eaaac41c3286a6a400275d0da3eb0ba52c43
e3ceaf63d11968c171f9a80f485bd40baa2e6f90
2326727ccbf0456ccfd631e748955f7f67c44a4e
487ab2325996b922b5f62e1930040b6d71bfd39f
c420b40668de351226c03b1b3822aae529dc4d21
5056309963dec9e944da6b11a593e94bbe02db5f
Keine binäre Suche mehr möglich!
```

**Comment by exit91** [comment]
I tried to build `0.10.0` (which did not have the regression) again, but with the `flake.lock` from commit `5056309963dec9e944da6b11a593e94bbe02db5f`, and this build *does* exhibit the bug.

**Comment by exit91** [comment]
Seems to be a duplicate of these, which are closed, probably due to the existence of a workaround.

https://github.com/Alexays/Waybar/issues/3058
https://github.com/Alexays/Waybar/issues/3021

Feel free to close this issue as well.
