### ISSUE TITLE
backlight: wrong percentage output using amdgpu_bl0 

### ISSUE THREAD

**Issue by isheshukov** [Alexays/Waybar#335]
Hey,

so waybar's formula for counting backlights percentage is `100 * actual_brightness/max_brightness` but on my amdgpu drivers `actual_brightness` is in (0, 65535) interval so waybar reports wrong percentage.

I haven't came up with a better solution #336  than to replace `actual_brightness` with `brightness` for amdgpu_bl0. 

Maybe there are more such devices and better methods should be used...

**Comment by isheshukov** [comment]
#336

**Comment by Alexays** [comment]
Done with #336

**Comment by patrick96** [comment]
Just wanted to let you know that the underlying issue with `actual_brightness` has been fixed in the linux kernel 5.9 and above.

* Bug report: https://bugzilla.kernel.org/show_bug.cgi?id=203905
* Fixing commit: https://github.com/torvalds/linux/commit/69d9f4278d0f9d24607645f10e5ac5c59c77a4ac
