### ISSUE TITLE
Weather widget wont open unless I manually run it waybar

### ISSUE THREAD

**Issue by 4j0x** [Alexays/Waybar#3352]
![captura-2024-06-11-1718090495](https://github.com/Alexays/Waybar/assets/54780610/36033a8e-759f-4d97-86b9-086aa40e5966)
The screenshot shows me running waybar twice (once by the autostart on top and the 2nd by me manually in the terminal)

the commands run is `waybar` & both times no difference

When I run way waybar myself in terminal the logs do not show any errors or anything of note

**Comment by apiraino** [comment]
Autostart from which window manager? Please post your waybar config. It must be something in the way the weather widget is started.

**Comment by 4j0x** [comment]
Autostart from hyprland 
with the command `waybar &`

custom-weather.jsonc
```json
{
  "custom/weather": {
    "exec": "wttrbar --fahrenheit --location Dallas",
    "restart-interval": 300,
    "tooltip": true,
    "format": "{}°",
    "return-type": "json",
    "on-click": "kitty --hold --class center-float wttr Dallas",
    "on-click-right": "kitty --hold --class center-float wttr -v2 Dallas",
    "on-click-middle": "xdg-open https://wttr.in/Dallas?u"
  }
}
```
bar-1.jsonc
```
{
  "include": [
    "~/.config/waybar/modules/custom-cava.jsonc",
    "~/.config/waybar/modules/custom-wf-recorder.jsonc",
    "~/.config/waybar/modules/custom-updates.jsonc",
    "~/.config/waybar/modules/custom-music.jsonc",
    "~/.config/waybar/modules/custom-logo.jsonc",
    "~/.config/waybar/modules/custom-notifications.jsonc",
    "~/.config/waybar/modules/custom-weather.jsonc",
    "~/.config/waybar/modules/hyprland-language.jsonc",
    "~/.config/waybar/modules/hyprland-workspaces.jsonc",
    "~/.config/waybar/modules/clock-1.jsonc",
    "~/.config/waybar/modules/pulseaudio.jsonc"
  ],
  "modules-left": ["custom/arch", "hyprland/workspaces", "custom/cava"],
  "modules-center": ["custom/music"],
  "modules-right": [
    "custom/weather",
    "clock#cl1",
    "pulseaudio",
    "custom/notifications"
  ]
}
```

**Comment by 4j0x** [comment]
most likely an issue with wttr but not 100% sure

**Comment by scqcasc** [comment]
In case this is still a problem, I solved this just now.  I was having the same problem.  The issue is wttrbar was not seen by the PATH defined by Hyprland.  I'm sure there is a better solution, but my short term fix is the sym link ~/.local/bin/wttrbar to /usr/bin/wttrbar.   Now it works as it should.
