### ISSUE TITLE
[Bug]: Waybar No Icons and Date Tooltip not Centered;Hyprland v0.41.0

### ISSUE THREAD

**Issue by vampirepapi** [Alexays/Waybar#3357]
Description

Before when you have apps running their icons appear on the top right part (based on my preferred waybay config) now they are missing. Also as I remember the Calendar tooltip is centered and now it's not. This happened after I updated to the latest linux firmware.
Screenshots

    Firefox icon not showing in the icon area
   ![image](https://github.com/Alexays/Waybar/assets/39551118/c16a145a-baea-4e16-b3b7-de69b3c05743)
    Uncentered Calendar Tooltip
  ![image](https://github.com/Alexays/Waybar/assets/39551118/21a04fa1-36f2-4b4b-8e3b-2d0e235d7898)

Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

    Linux Distro: EndeavourOS
    Linux Version: Linux dadsgift 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux
    Hyprland Version:

Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794
flags: (if any)

    Installation Environment: On The Main Hardware

**Comment by 299792458ms** [comment]
[#3342 ](url) this happened to me too (tooltips)

**Comment by kRHYME7** [comment]
@vampirepapi  https://github.com/prasanthrangan/hyprdots/issues/1579#issuecomment-2165806170 The ` wlr/taskbar ` is already fixed.

**Comment by vampirepapi** [comment]
> @vampirepapi [prasanthrangan/hyprdots#1579 (comment)](https://github.com/prasanthrangan/hyprdots/issues/1579#issuecomment-2165806170) The `wlr/taskbar` is already fixed.

Thanks man, it worked!
