### ISSUE TITLE
wlr/taskbar

### ISSUE THREAD

**Issue by aloispichler** [Alexays/Waybar#3358]
on hyprland, `wlr/taskbar` stopped working – does not show up – since the last release of hyprland.

**Comment by DevZiaus** [comment]
same problem here

**Comment by londeril** [comment]
+1 here, too - Hyprland 0.41 on OpenSuse Tumleweed

**Comment by wiler6** [comment]
yep, me too

**Comment by itsmenewbie03** [comment]
This worked on my machine
https://github.com/prasanthrangan/hyprdots/issues/1579#issuecomment-2165806170

**Comment by vampirepapi** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1579#issuecomment-2165806170

try this

**Comment by aloispichler** [comment]
started to work again in hyprland 0.41.1-1, https://archlinux.org/packages/extra/x86_64/hyprland/

**Comment by kooskaspers** [comment]
jep, fixed.

**Comment by RobertMueller2** [comment]
if it's working again, can you close the issue, please? Thanks.
