### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by roflcow2** [Alexays/Waybar#3367]
Pretty sure I'm being an idiot, but I can't figure it out. I was issue #6518 and I was politely told I was being an idiot and that I hadn't updated my hyprland. I have it installed from aur package hyprland-git, but for some reason I cannot get it to update. I have tried  uninstalling and reinstalling hyprland-git, all its dependencies and anything else I can think of.  

AUR Explicit (1): hyprland-git-0-1
:: PKGBUILD up to date, skipping download: hyprland-git
  1 hyprland-git                             (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/christopher/.cache/yay/hyprland-git
HEAD is now at 2ac9c86 add cpio to deps
Removing Hyprland/
Removing hyprland-protocols/
Skipping repository src/hyprland-protocols
Skipping repository src/Hyprland
Skipping repository src/tracy
Skipping repository src/udis86
Skipping repository src/wlroots
Removing tracy/
Removing udis86/
Removing wlroots/
  1 hyprland-git                             (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
==> Making package: hyprland-git 0.35.0.r104.bc3f5b94-1 (Mon 17 Jun 2024 07:33:59 AM EDT)
==> Retrieving sources...
  -> Cloning Hyprland git repo...
Cloning into bare repository '/home/christopher/.cache/yay/hyprland-git/Hyprland'...
remote: Enumerating objects: 46295, done.
remote: Counting objects: 100% (46295/46295), done.
remote: Compressing objects: 100% (10279/10279), done.
remote: Total 46295 (delta 36047), reused 45964 (delta 35874), pack-reused 0
Receiving objects: 100% (46295/46295), 181.91 MiB | 10.22 MiB/s, done.
Resolving deltas: 100% (36047/36047), done.
  -> Cloning wlroots git repo...
Cloning into bare repository '/home/christopher/.cache/yay/hyprland-git/wlroots'...
remote: Enumerating objects: 59779, done.
remote: Counting objects: 100% (6827/6827), done.
remote: Compressing objects: 100% (4639/4639), done.
remote: Total 59779 (delta 5346), reused 2499 (delta 2184), pack-reused 52952 (from 1)
Receiving objects: 100% (59779/59779), 13.95 MiB | 9.17 MiB/s, done.
Resolving deltas: 100% (46682/46682), done.
  -> Cloning hyprland-protocols git repo...
Cloning into bare repository '/home/christopher/.cache/yay/hyprland-git/hyprland-protocols'...
remote: Enumerating objects: 155, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 155 (delta 42), reused 41 (delta 34), pack-reused 98
Receiving objects: 100% (155/155), 32.57 KiB | 926.00 KiB/s, done.
Resolving deltas: 100% (80/80), done.
  -> Cloning udis86 git repo...
Cloning into bare repository '/home/christopher/.cache/yay/hyprland-git/udis86'...
remote: Enumerating objects: 2477, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 2477 (delta 34), reused 46 (delta 20), pack-reused 2414
Receiving objects: 100% (2477/2477), 1.81 MiB | 4.98 MiB/s, done.
Resolving deltas: 100% (1503/1503), done.
  -> Cloning tracy git repo...
Cloning into bare repository '/home/christopher/.cache/yay/hyprland-git/tracy'...
remote: Enumerating objects: 41512, done.
remote: Counting objects: 100% (12487/12487), done.
remote: Compressing objects: 100% (934/934), done.
remote: Total 41512 (delta 11774), reused 11870 (delta 11545), pack-reused 29025
Receiving objects: 100% (41512/41512), 31.18 MiB | 10.28 MiB/s, done.
Resolving deltas: 100% (29600/29600), done.
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with b2sums...
    Hyprland ... Skipped
    wlroots ... Skipped
    hyprland-protocols ... Skipped
    udis86 ... Skipped
    tracy ... Skipped
:: (1/1) Parsing SRCINFO: hyprland-git
==> Making package: hyprland-git 0.35.0.r104.bc3f5b94-1 (Mon 17 Jun 2024 07:34:31 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating Hyprland git repo...
  -> Updating wlroots git repo...
  -> Updating hyprland-protocols git repo...
  -> Updating udis86 git repo...
  -> Updating tracy git repo...
==> Validating source files with b2sums...
    Hyprland ... Skipped
    wlroots ... Skipped
    hyprland-protocols ... Skipped
    udis86 ... Skipped
    tracy ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of Hyprland git repo...
Cloning into 'Hyprland'...
done.
  -> Creating working copy of wlroots git repo...
Cloning into 'wlroots'...
done.
  -> Creating working copy of hyprland-protocols git repo...
Cloning into 'hyprland-protocols'...
done.
  -> Creating working copy of udis86 git repo...
Cloning into 'udis86'...
done.
  -> Creating working copy of tracy git repo...
Cloning into 'tracy'...
done.
==> Starting prepare()...
Submodule 'subprojects/hyprland-protocols' (https://github.com/hyprwm/hyprland-protocols) registered for path 'subprojects/hyprland-protocols'
Submodule 'subprojects/tracy' (https://github.com/wolfpld/tracy) registered for path 'subprojects/tracy'
Submodule 'subprojects/udis86' (https://github.com/canihavesomecoffee/udis86) registered for path 'subprojects/udis86'
Submodule 'subprojects/wlroots-hyprland' (https://github.com/hyprwm/wlroots-hyprland) registered for path 'subprojects/wlroots-hyprland'
Cloning into '/home/christopher/.cache/yay/hyprland-git/src/Hyprland/subprojects/hyprland-protocols'...
done.
Cloning into '/home/christopher/.cache/yay/hyprland-git/src/Hyprland/subprojects/tracy'...
done.
Cloning into '/home/christopher/.cache/yay/hyprland-git/src/Hyprland/subprojects/udis86'...
done.
Cloning into '/home/christopher/.cache/yay/hyprland-git/src/Hyprland/subprojects/wlroots-hyprland'...
Submodule path 'subprojects/hyprland-protocols': checked out 'e06482e0e611130cd1929f75e8c1cf679e57d161'
Submodule path 'subprojects/tracy': checked out '37aff70dfa50cf6307b3fee6074d627dc2929143'
Submodule path 'subprojects/udis86': checked out '5336633af70f3917760a6d441ff02d93477b0c86'
Submodule path 'subprojects/wlroots-hyprland': checked out '422207dbcf0949e28042403edab539159282885e'
fatal: cannot change to 'subprojects/wlroots': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: hyprland-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-git - exit status 4

**Comment by roflcow2** [comment]
I have just realized I am in the wrong github. My bad

**Comment by khaneliman** [comment]
@roflcow2 can you close this ?

**Comment by khaneliman** [comment]
@Alexays or whenever you get a chance?

**Comment by roflcow2** [comment]
my bad
