### ISSUE TITLE
hyprland/workspaces no longer display persistent workspaces

### ISSUE THREAD

**Issue by Akira-uestc** [Alexays/Waybar#3368]
can not show persistent workspaces

```
my config:
    "hyprland/workspaces": {
        "disable-scroll": true,
        "active-only": false,
        "all-outputs": true,
        "on-click": "activate",
        "persistent_workspaces": {
            "1": [],
            "2": [],
            "3": [],
            "4": []
        }
    },
```

compared to v0.10.3, the newest git version only display active workspace

![24-06-17_20-23-16](https://github.com/Alexays/Waybar/assets/124018024/33217faf-894a-47af-a407-1abff9f5e5f8)

**Comment by khaneliman** [comment]
Field was renamed, use persistent-workspaces.
