### ISSUE TITLE
crashes due to many uncaught exceptions in hyprland module

### ISSUE THREAD

**Issue by maaarghk** [Alexays/Waybar#3388]
```
[2024-06-28 13:25:12.496] [error] Hyprland IPC: Couldn't write (4)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing JSON: * Line 1, Column 1
  Syntax error: value, object or array expected.

[1]    2547530 IOT instruction (core dumped)  waybar
```

Seems an empty string is returned to caller here but the caller expects a valid JSON string: https://github.com/Alexays/Waybar/blob/ccc3c132124623bde5127937fe4fc9aa45a9d35d/src/modules/hyprland/backend.cpp#L199 which then fails to parse as JSON. 

the vast majority of calls to `getSocket1Reply` or `getSocket1JsonReply` ought to be wrapped in try/catch, i don't think this is really a fatal class of error, I get crashes constantly when load is high. maybe an option to increase the socket timeout would alleviate the issue?

**Comment by khaneliman** [comment]
Could you try https://github.com/Alexays/Waybar/pull/3389
