### ISSUE TITLE
[Question] Can tray apps be "restored" via commandline?

### ISSUE THREAD

**Issue by lunatic-gh** [Alexays/Waybar#3392]
Hi,

So, some apps (eg. discord) have that issue on linux, where sometimes if you reopen them (eg. via a taskbar, a start menu, or a launcher like rofi), they will open another instance, instead of reopening the existing one.

In discord this is even a bigger issue, because when that happens, it will entirely ignore the stored token, requiring a manual re-login every time this happens, which is very very annoying with 2fa enabled.

And for some people like me, it is just into muscle-memory to open apps via a menu instead of clicking a tray icon (that may not even exist for some people)

The fix would be to modify the launch-script to restore the active instance if one exists, problem is i don't know if there is a way to do that. Anyone got an idea if that's possible?

**Comment by RobertMueller2** [comment]
How an application checks for another instance running or what it does in that case is up to the application, so I think each application will have to be looked at separately. Regarding discord, I'd consider this a bug, especially if the behaviour is intermittent, so my first suggestion would be a bug report to discord.

As a workaround, you could add a wrapper script. E.g. if your normal discord binary is `/usr/bin/discord`, place one in `/usr/local/bin/discord`, this should have precedence (if `/usr/local/bin` appears before `/usr/bin` in your PATH environment variable). The wrapper script could:
* try to create a lockfile and error out if it exists
* or check process list and error out if discord is running
* or try window activation and run discord if window activation fails. Details depend on your compositor, with sway: `swaymsg [class=\"discord\"] focus || discord`

If you're running the application from a .Desktop file, additional considerations might be necessary.

**Comment by RobertMueller2** [comment]
After looking into this a bit more, it is possible to activate a tray icon with a DBus query. E.g. this opened a discord window for me:

```
qdbus :1.577 /StatusNotifierItem org.kde.StatusNotifierItem.Activate
```

The service name is arbitrary, though. It's possible to find out a process id for a service with

```
qdbus  org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetConnectionUnixProcessID :1.577
```

A list of services can be retrieved with
```
qdbus --session
```

Or perhaps systemd's `busctl --user` might be even better, listing the pid right away.

Some services have well-known names, but discord doesn't appear to be one of them. I think it should be possible to combine this with the above suggestions (get the PID, focus the window etc.). Perhaps there's a more practical way to determine which service you want to activate. 

To answer your question though, it does look possible. ;)

**Comment by lunatic-gh** [comment]
Thanks for looking into it, i could get it to work, much thanks!
