### ISSUE TITLE
Extend windows module to show all windows of a workspace

### ISSUE THREAD

**Issue by AGCaesar** [Alexays/Waybar#340]
Thank you so much for implementing issue #210 
I have another request to get a little awesomewm feel to sway:
AwesomeWM shows all winndows in a workspace on the bar. You can minimize and restore windows by clicking on it, a bit like in windows:
https://i.imgur.com/nCvpNG2.png
Is it possible to extend the "window" module
_The window module displays the title of the currently focused window_
To show all windows and allow minimizing?

**Comment by Alexays** [comment]
Dups of #186 
And currently worked by @Anakael in #343

**Comment by AGCaesar** [comment]
Sorry for missing the dupe!
You are all doing great work :)
