### ISSUE TITLE
Symbol lookup error after upgrading wireplumber

### ISSUE THREAD

**Issue by intervinn** [Alexays/Waybar#3405]
I've been upgrading waybar aswell as pipewire and wireplumber to the newest, then ran into this error when starting waybar:
```
❯ waybar
waybar: symbol lookup error: /usr/lib/libwireplumber-0.5.so.0: undefined symbol: pw_log_set_level_string
```

waybar version: 0.10.3-1
distro: arch (and hyprland)

**Comment by intervinn** [comment]
ok it doesnt seem like a direct problem with wireplumber, since the message is the same even after uninstalling it

**Comment by intervinn** [comment]
updated all the packages, now working (don't repeat my mistake, update your packages even since youve installed an os!)

**Comment by intervinn** [comment]
yeah i did that and closed this issue right after, quite silly right

**Comment by Cobeta-beta** [comment]
I just reinstalled arch, since it was falling apart already. :P
