### ISSUE TITLE
[Question] Waybar tray menu tooltip

### ISSUE THREAD

**Issue by KomaDi** [Alexays/Waybar#3408]
Hello, for some reason my tray menu have a border. Cursor is displaying that i can resize it. it's like a window border. How to remove it? P.S Hyprland
![traymenu](https://github.com/Alexays/Waybar/assets/87398325/309b2114-9bb4-42f0-b1a6-35d73c2c32e0)

**Comment by KomaDi** [comment]
i made background transparent and now i can see that tray menu have another background behind main. How to remove it?
![изображение](https://github.com/Alexays/Waybar/assets/87398325/c742d3ce-e1a3-4a08-be43-91f69cfe1c48)

**Comment by KomaDi** [comment]
i found that `#tray window` is working for that, but how to full disable it? There's border around it 
![изображение](https://github.com/Alexays/Waybar/assets/87398325/baa1ffb3-5e77-49cf-b456-fdd3c7120253)

**Comment by KomaDi** [comment]
Oh, now it's fully disabled. Just needed to configure `#tray window decoration`.
![изображение](https://github.com/Alexays/Waybar/assets/87398325/cd86d1a5-9db8-4585-9059-5d1ad8acc5b3)

**Comment by TallenPeli** [comment]
> Could you explain how you removed the edge of the tray menu? I searched a lot and did not find the solution

```css
#tray window decoration {
  box-shadow: none;
}
```

I know it's a bit late but it's here if anyone else is wondering for future reference
