### ISSUE TITLE
Workspace order is broken after today's changes 

### ISSUE THREAD

**Issue by alebastr** [Alexays/Waybar#341]
![image](https://user-images.githubusercontent.com/2681151/58035498-c439e380-7add-11e9-9976-bef552b55cf2.png)
Config: [here](https://git.alebastr.su/alebastr/dotfiles/raw/master/config/waybar/config)

Steps to reproduce:
- open windows on 1, 3
- restart waybar
- switch to 2, open window

**Comment by Alexays** [comment]
@Organic-Code

**Comment by Alexays** [comment]
Fixed with 4accdd4524e5fbfa76f36bff7eeeef7ad7dc7796
