### ISSUE TITLE
 Display exception when starting waybar

### ISSUE THREAD

**Issue by AhDEV-free** [Alexays/Waybar#3413]
<img width="1309" alt="image" src="https://github.com/Alexays/Waybar/assets/57929887/149ec318-2517-4fa9-b584-3535d00b9d37">

Display exception when starting waybar

used with hyprland

Have you ever encountered the problem that the icon cannot be displayed on hyprland?

**Comment by yangyingchao** [comment]
missing required font?

**Comment by AhDEV-free** [comment]
> missing required font?

yes, Add the font, and then use hyprland to start normally
