### ISSUE TITLE
[clock] Printed tooltip year/month is based on currently selected calendar entry

### ISSUE THREAD

**Issue by Zapeth** [Alexays/Waybar#3414]
Given a clock configuration that displays a time formatted string and a scrollable calendar in the tooltip, it looks like the printed string is based on the currently selected year/month of the calendar.

I'm not sure if this is intentional behavior, but I would expect any time formatted string to always be based on the current time (with a given timezone offset), especially since the calendar already includes the information of the currently selected year/month.

Sample config for testing the behavior:
```
 "clock": {
        ...
        "tooltip-format": "<big>{:%Y %B %d}</big>\n<tt><small>{calendar}</small></tt>",
        "actions":  {
                "on-scroll-up": "shift_up",
                "on-scroll-down": "shift_down"
        }
    },
```
When scrolling up/down the printed month/year (`%B` and `%Y`) changes, but the date stays the same (`%d`), I would expect all formatted values to be constant when scrolling (ie the current year/month/date).

**Comment by RobertMueller2** [comment]
I got this gem from my ancient waybar config:

![satty-20240707-14:02:18](https://github.com/user-attachments/assets/e8e20d48-3e90-47a1-b1c7-80026159246b)

I /think/ the {calendar} replacement wasn't always this powerful, so stating the month + year separately was the only way to indicate which month you're actually displaying in the calendar.
