### ISSUE TITLE
Network module does not update when switching interfaces

### ISSUE THREAD

**Issue by MichaelAquilina** [Alexays/Waybar#344]
I've noticed that if I am connected to ethernet and wifi (e.g. I am at my desk) then the network module will correctly show an ethernet connection.

However if I then disconnect from ethernet to move around with my laptop, the network module does not update to show that I am now using wifi. The only way to solve this currently is to restart waybar.

**Comment by Alexays** [comment]
Fixed with 48a58cd979aadee71cd4e988f148ba430a71aa75
Also fixed when ethernet is connected after wifi and ethernet is the prefered external iface.
