### ISSUE TITLE
"on-" events and where to find them.

### ISSUE THREAD

**Issue by zhexyez** [Alexays/Waybar#3445]
Sorry for this, but I can't find any reference for "on-" events, so I could `exec` the script on `Alt-Shift` press. Point me into the right direction, please. Thanks.

**Comment by RobertMueller2** [comment]
Refer to the man pages as well as the wiki. Some of the event handling is centralised into central classes (AModule), but not all modules make use of that. The modules' individual man pages should list them either way.
