### ISSUE TITLE
Limiting title length in wlr/taskbar module

### ISSUE THREAD

**Issue by polarbub** [Alexays/Waybar#3451]
I have taskbar on the right and some windows with really long titles. These titles cause waybar to expand to be much bigger than I would like. I would like to truncate them to 30 characters or so. I have tried using a rewrite `"(.{30}).+" : "\\1`, but it seems that [std::regex_replace](https://github.com/Alexays/Waybar/blob/15e1547661bfc5fe9b3d45bb0d9cea11cf07db7f/src/util/rewrite_string.cpp#L22C47-L22C61) doesn't support referencing capturing groups in the original string. Is there some proper way to do this?
![long](https://github.com/user-attachments/assets/f210f5de-6b4d-42b6-9233-9e9b364b9a2a)

**Comment by bergentroll** [comment]
` "format": "{title:.30}"` does the trick!
