### ISSUE TITLE
"gdbus-codegen" not found

### ISSUE THREAD

**Issue by mutoroglin** [Alexays/Waybar#3453]
Hi everyone!

I failed compilng the new release 0.10.4. I get following error:
```
Run-time dependency cava found: YES 0.10.2
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Program gdbus-codegen found: NO

protocol/meson.build:44:16: ERROR: Program 'gdbus-codegen' not found or not executable

A full log can be found at /home/user/waybar-cava/src/Waybar-0.10.4/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
```
I struggle to identify a missing dependency? I also didn't find a hint in the changelog what I may have missed to add?
Does anyone experience the same issue, any tip how this can be solved?

**Comment by mutoroglin** [comment]
I fgured out that `gdbus-codegen` is part of `glib2`. Installing the arch package `glib2-devel` fixed the compilation problems.

**Comment by walzerblack** [comment]
> I fgured out that `gdbus-codegen` is part of `glib2`. Installing the arch package `glib2-devel` fixed the compilation problems.

you are a hero
