### ISSUE TITLE
Change in bar.cpp L407 breaks SIGUSR1 visibility toggle

### ISSUE THREAD

**Issue by maga-tama** [Alexays/Waybar#3455]
Reverting to
```
void waybar::Bar::setVisible(bool value) {
  visible = value;
```
solves the issue.

**Comment by RobertMueller2** [comment]
@khaneliman I think clang-tidy made a mistake here, this is related to 14c3235c12eae0615dda9b1e71c6b8fd6cb20cd3. 

If `visible` was just a local variable in `void waybar::Bar::setVisible` the refactor would have made sense. But it's actually a class variable, and within the method it is now masked by the parameter which it wasn't before.

**Comment by khaneliman** [comment]
> @khaneliman I think clang-tidy made a mistake here, this is related to [14c3235](https://github.com/Alexays/Waybar/commit/14c3235c12eae0615dda9b1e71c6b8fd6cb20cd3).
> 
> If `visible` was just a local variable in `void waybar::Bar::setVisible` the refactor would have made sense. But it's actually a class variable, and within the method it is now masked by the parameter which it wasn't before. So not really a refactor. ;)

Thanks, not sure why it would have suggested that looking at the code more closely...
