### ISSUE TITLE
argument not found

### ISSUE THREAD

**Issue by DerMerten** [Alexays/Waybar#3465]
hello,
I tried to create a custom module, but I get an error "argument not found"
I want to create a module with the auto-cpufreq to show me the current powermode, but I got this error. 
`[error] custom/auto-cpufreq: argument not found`
this is the config I add:
```
   "custom/auto-cpufreq" : {
      "format": "{icon}",
      "tooltip-format": "governor: {governor}",
      "tooltip": true,
      "escape" : true,
      "exec": "/usr/local/bin/auto-cpufreq-status.sh",
      "interval" : 10,
      "format-icons": {
        "default": "",
        "performance": "",
        "balance_power": "",
        "powersave": ""
      }
    },
```
and this the script that get executed: 
```
#!/bin/bash

governor=$(cpufreqctl.auto-cpufreq -g | tr ' ' '\n'|  head -n 1)

echo governor: $governor
```
this is the output I got, if I run the script manual, but the icon dose not change:
`
governor: performance
`
maybe I'm missing something, can anyone help? Thanks

**Comment by RobertMueller2** [comment]
I assume you want to show the governor in the tooltip. Then you should use `"tooltip-format" : "{}"`. Your script should output `$text\n$tooltip\n$class`, alternatively, use json. See https://github.com/Alexays/Waybar/wiki/Module:-Custom or the manpage. (The former seems to be a bit more up-
to-date.)

At this point there are no named format strings for custom modules, so using `{governor}` isn't going to work. There's a PR #2441 to allow this for json, but not merged at this point.

**Comment by RobertMueller2** [comment]
No, sorry for the confusion, I was just trying to add some context. `{governor}` won't work, there are no named format strings in custom module at this point. This should work:

```
#!/bin/sh

governor=$(cpufreqctl.auto-cpufreq -g | tr ' ' '\n' | head -n 1)

output=""
case $governor in
    "performance")
        output=""
        ;;
    "balance_power")
        output=""
        ;;
        
    "powersave")
        output=""
        ;;
    *)
        :
        ;;
esac

echo "${output}\ngovernor: ${governor}\nnormal"
```

```
{
    "layer": "top", // Waybar at top layer
    "position": "top", // Waybar position (top|bottom|left|right)
    "height" : 20,
    "modules-center": ["custom/auto-cpufreq"],

   "custom/auto-cpufreq" : {
      "format": "{}",
      "tooltip": true,
      "escape" : true,
      "exec": "/usr/local/bin/auto-cpufreq-status.sh",
      "interval" : 10,
      "format-icons": {
        "default": "",
        "performance": "",
        "balance_power": "",
        "powersave": ""
      }
    }

}
```

**Comment by DerMerten** [comment]
thank you very much, it works
