### ISSUE TITLE
Did latest update break persistent workspaces?

### ISSUE THREAD

**Issue by Hexanchus29** [Alexays/Waybar#3466]
My workspaces module config:

"hyprland/workspaces": {
    "disable-scroll": true,
    "all-outputs": true,
    "on-click": "activate",
    "persistent_workspaces": {
        "1": [],
        "2": [],
        "3": [],
        "4": [],
        "5": [],
        "6": [],
        "7": [],
        "8": [],
        "9": [],
        "10": []
    }
},

Before i updated, i could see all 10 workspaces at all times. After updating, i only see workspaces with a window active in them.

**Comment by Hexanchus29** [comment]
My specs:

7900GRE
7800X3D
Linux zen kernel 
Hyprland

**Comment by bjyberg** [comment]
I was finding the same issue on Sway with similar specs to you otherwise: Arch Linux + zen kernel. I looked back into the docs and it seems that at some point, the key was changed to "persistent-workspaces" rather than "persistent_workspaces". Changing this in my config worked for me.

**Comment by Hexanchus29** [comment]
Thank you so much!!!! This worked

**Comment by khaneliman** [comment]
Yeah, about a year ago we deprecated the name to match the "-" name scheme. Recently, we removed the "_" support.
