### ISSUE TITLE
Toggling waybar no longer works after reinstall

### ISSUE THREAD

**Issue by Eugenenoble2005** [Alexays/Waybar#3467]
I've just reinstalled my system and the following command no longer restarts waybar:
```
killall -SIGUSR1  waybar 
```
It was a partial reinstall that is, my /home partition with all my configs was left untouched while my /root was purged. I've reinstalled waybar and the command above no longer toggles it. Is there something i'm not doing right or forgot to install or configure for this to work?

I also get this warning when staring waybar with the terminal:
```
[warning] Failed to open bar ipc connection: Socket path is empty
``` 
Does this have something to do with it? Thanks

**Comment by khaneliman** [comment]
Are you using latest git or latest release? There was a bug in last release related to toggling waybar.

**Comment by Eugenenoble2005** [comment]
> Are you using latest git or latest release? There was a bug in last release related to toggling waybar. 

Hi, I'm using the latest standard release on arch Linux from pacman. Version 0.10.4-1

**Comment by mrtnvgr** [comment]
+1

**Comment by khaneliman** [comment]
Yeah, need to be on -git version. Last release had this bug.

**Comment by Eugenenoble2005** [comment]
Can confirm this is fixed on upgrade to the -git version. Thank You
