### ISSUE TITLE
Custom module styles no longer applying (v0.6.6)

### ISSUE THREAD

**Issue by Chadsr** [Alexays/Waybar#347]
Hi and first of all, thanks for your awesome work on waybar!

I just upgraded from 0.6.5 to 0.6.6 (0.6.6-6-gb673279) from the AUR and noticed that my CSS styles for custom modules are no longer being applied. If I switch back to 0.6.5 everything is fine again.

Did anything intentionally change in the syntax of applying styles to custom modules, or is this perhaps a bug?

**Comment by Alexays** [comment]
Fixed with 755d38d4d6e382980e7ba9619b0226feec27f7d0
