### ISSUE TITLE
SIGUSR1 does not unhide waybar anymore

### ISSUE THREAD

**Issue by KosmX** [Alexays/Waybar#3477]

**Comment by Pierceisgone** [comment]
This is also happening for me on Arch Linux with Hyprland.
hyprland 0.41.2-3
waybar 0.10.4-1
6.10.0-arch1-2

**Comment by KorigamiK** [comment]
@Alexays please review

**Comment by RobertMueller2** [comment]
Have you tried with current git version, e.g. everything from cb8fc1c10d32f719c3a41a26efa780f9fb6145ad or later?

**Comment by KosmX** [comment]
fixed with #3459
