### ISSUE TITLE
Waybar becomes unresponsive after some time

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#348]
As title says, it just stops responding to clicks and also stops updating displayed information. It happens randomly, but always after some time of running, not right away.

**Comment by Alexays** [comment]
It'll be complicated to debug :/

**Comment by eternal-sorrow** [comment]
All I can say, it began after updating to 0.6.6.

**Comment by eternal-sorrow** [comment]
I've just caught the moment it becomes unresponsive. I stopped redrawing bus still responded to clicks for several seconds and then hanged completely.

**Comment by eternal-sorrow** [comment]
Now after I updated sway to 1.1.1, waybar never becomes unresponsive, but just stops redrawing itself.

**Comment by Alexays** [comment]
Never got the pb, are there any common points when it becomes unresponsive?

**Comment by eternal-sorrow** [comment]
I haven't noticed any. Just after some time of normal workflow it stops updating its appearance. I.e. when I switch workspaces, it keeps highlighting the old one, clock stops, window title does not change, etc.

The only thing I noticed, it's always works normal right after I unlock screen after PC stayed Idle for some time if it worked normal before screen was locked. So it doesn't hang while idle, but hangs at some point when I'm working.

**Comment by Alexays** [comment]
Do you have some custom modules?

**Comment by eternal-sorrow** [comment]
Yes, I do. Two of them actually.

**Comment by wfrced** [comment]
Experiencing the same problem, but I'm not using any custom modules.

**Comment by Gigadoc2** [comment]
This happens for me as well, but *only* with custom modules running.

The modules in question are two instances of https://git.revreso.de/gigadoc2/waybar-scripts/blob/master/battery.py in case this is relevant.

**Comment by Gigadoc2** [comment]
Correction: it did just happen without custom modules. It just took longer.

**Comment by Alexays** [comment]
Can you test with `test` branch :)

**Comment by Alexays** [comment]
So anyone tested with the test branch? :)

**Comment by Gigadoc2** [comment]
I *just* started running it :sweat_smile: 
So far I can't see the bug, but I've only been running the test branch for 2 hours or so, the bug sometimes took longer.

**Comment by eternal-sorrow** [comment]
For me the bug did not happen since I updated to 0.6.8. But it does not matter, because that's totally normal for this bug. Sometimes I do not see it for several days, sometime it happens several times a day.

**Comment by Alexays** [comment]
Will close this issue if no one has the bug again when 0.7.0 will be released :)

**Comment by eternal-sorrow** [comment]
Now, after this time I can say: this really does not happen anymore. If nobody has objections, I think it's safe to close the issue.

**Comment by wfrced** [comment]
Yeah, seems fine now.

**Comment by Gigadoc2** [comment]
I've been running the test branch until now, and I did not encounter the bug anymore. Will now change to 0.6.8 and see what happens there.
