### ISSUE TITLE
regression: since 0.10.4, battery level is wrong

### ISSUE THREAD

**Issue by josch** [Alexays/Waybar#3482]
The battery meter is showing 100% while in reality, the battery level is much lower. This is on the MNT Pocket Reform and was discussed here: https://community.mnt.re/t/after-apt-upgrade-today-battery-in-waybar-stuck-at-100/2299/1

Bisecting waybar git revealed that commit d68bcbd is the culprit and reverting it fixes the issue.

**Comment by khaneliman** [comment]
In reading that forum, was this an issue in the code change in Waybar? Or that the firmware for the device incorrectly reported battery level ?

**Comment by josch** [comment]
Apologies, our motherboard firmware indeed did have a bug which was only revealed after waybar changed behaviour. The correct fix is to change our firmware and not waybar. Sorry for the noise!
