### ISSUE TITLE
Clock is stuck on 12H Format

### ISSUE THREAD

**Issue by ElryDeveloper** [Alexays/Waybar#3485]
Idk why but i always end up having a 12H Formatted Clock, idk what else to do...

![image](https://github.com/user-attachments/assets/8e6d9f8d-c6ff-4edc-b155-2278193e6362)

And this is the code of the clock:
```
    "clock": {
        "format": "{:%H:%M}",
        "timezone": "Europe/Berlin",
        "rotate": ${r_deg},
    },
```
This is my waybar code:
`1|31|bottom|( custom/cpuinfo custom/gpuinfo  memory )|( wlr/taskbar custom/spotify )|( clock pulseaudio custom/updates custom/power)`

**Comment by ElryDeveloper** [comment]
Im using Hyprland - Hyprdots, so i assume its using https://archlinux.org/packages/extra/x86_64/waybar/
Does the config.jsonc rebuild automatically when waybar starts or do i need to do that manually ?
With the other modules it seemed waybar updatated as soon as i reloaded it.

**Comment by RobertMueller2** [comment]
My assumption about simpleclock was wrong, I missed that it passes `{:%H:%M}` as default format to AModule.

So let's look at the config. The config.jsonc is generated by hyprdots, I don't know how or when hyprdots does it. I'm not using it.

I'm not sure which hyprdots you use (apparently there is more than one), but https://github.com/prasanthrangan/hyprdots uses `"format": "{:%I:%M %p}",` while https://github.com/yashlakhtariya/ysl-hyprdots uses `"format": "{:%r}",`. Both would look like in your screenshot.

So might be an idea to have a look at the actual generated `.config/waybar/config.jsonc`, I assume you pasted the one from `.config/waybar/modules/clock.jsonc`, correct?

**Comment by ElryDeveloper** [comment]
https://github.com/prasanthrangan/hyprdots
And from one of their users i got the info to use %H %M to get 24hrs which didnt do anything, its still 12 Hours with a PM at the end even tho its no longer %I %M %p.

I attached my jsonc file for waybar, idk maybe you can read more out of it, i can just tell if i edited any other of the waybar parts a simple restart of waybar always did the trick, but apparently not for the clock, idk if im doing something wrong.

[config.jsonc](https://github.com/user-attachments/files/16432004/config.jsonc)

**Comment by RobertMueller2** [comment]
Here's your clock configuration according to the file you attached. Please have a look at the format, that's different from what you posted above.

```
    "clock": {
        "format": "{:%I:%M %p}",
        "rotate": 0,
        "format-alt": "{:%R 󰃭 %d·%m·%y}",
        "tooltip-format": "<span>{calendar}</span>",
        "calendar": {
            "mode": "month",
            "mode-mon-col": 3,
            "on-scroll": 1,
            "on-click-right": "mode",
            "format": {
                "months": "<span color='#ffead3'><b>{}</b></span>",
                "weekdays": "<span color='#ffcc66'><b>{}</b></span>",
                "today": "<span color='#ff6699'><b>{}</b></span>"
            }
        },
        "actions": {
            "on-click-right": "mode",
            "on-click-forward": "tz_up",
            "on-click-backward": "tz_down",
            "on-scroll-up": "shift_up",
            "on-scroll-down": "shift_down"
        }
    },
```

I can't comment on how hyprdots is supposed to work with updating the configs. I don't mind helping if I can, but it'll probably be a lot faster if you ask the hyprdots people.

**Comment by ElryDeveloper** [comment]
Well my Clock.jsonc has it correctly 
![image](https://github.com/user-attachments/assets/cd3f5766-5f64-4ace-9b99-18668841054f)
So its just a compilation error, so its not waybar and i will close the issue
