### ISSUE TITLE
[hyprland/workspaces] Persistent workspaces not working

### ISSUE THREAD

**Issue by Paynzin** [Alexays/Waybar#3489]
In my config I have 6 persistent workspaces enabled but after an update they suddenly just stopped working.

[this](https://gist.github.com/Paynzin/034267084ea3c2a193c730dc3a756a37) is my config.

screenshot:
![image](https://github.com/user-attachments/assets/1cc8dc30-d96c-4e89-a149-4d97b375bba8)

**OS:** ArchLinux
**WM:** Hyprland
**PORTALS:** xdg-desktop-portal-hyprland

**Comment by CaptainOddessy** [comment]
I am also facing this problem.

**Comment by RobertMueller2** [comment]
Can you try to use `persistent-workspaces` instead of persistent_workspaces`? See #3466.

**Comment by CaptainOddessy** [comment]
Thank you so much!!!! This worked

**Comment by mathcale** [comment]
> Can you try to use `persistent-workspaces` instead of `persistent_workspaces`? See #3466.

Was facing this same issue and this solved it. Thanks!
