### ISSUE TITLE
waybar-menu: menu-file path is not expanded

### ISSUE THREAD

**Issue by jlebras** [Alexays/Waybar#3490]
Hello, new user of waybar there, thank you for your work !

I followed the [documentation](https://man.archlinux.org/man/waybar-menu.5.en) about waybar menu configuration but somehow was unable to display a menu when clicking (actually waybar segfaults).

After digging the logs, I found that waybar could not find the xml file describing the menu as a GtkBuilder.
The path used was identical to the one from the doc (~/.config/waybar/power_menu.xml), I tried with $HOME and same thing.

The waybar log shows the path "as-is" without path expansion so I guess there is no expansion at all on the string provided.
After providing a full path it worked.

I looked quickly at the code and the file is opened [there](https://github.com/Alexays/Waybar/blob/003dd3a9a260a212648b6ab4a70f058c6437d40d/src/ALabel.cpp#L63) without any processing of the path from the config.

I don't know if it's a bug or intended behaviour (could be handy though).

**Comment by yangyingchao** [comment]
I wasn't aware of this feature before, but I would like to use it. Therefore, I have opened a PR for this :) 

It does not hurt to expand the filepath anyway.

**Comment by yangyingchao** [comment]
I wasn't aware of this feature before, but I would like to use it. Therefore, I have opened a PR for this :) 

It does not hurt to expand the filepath anyway.

**Comment by AtomicTacoSauce** [comment]
Ok, I've been wrestling with this for quite some time. The power_menu.xml icon/menu just simply will not show up on fedora 41 sway regardless of applying everything from this thread and several others. I'm at a loss as to where to go next, because waybar works perfectly...it's just that one power module that won't show up in the tray.

**Comment by seyedmm** [comment]
Hi. Found a solution on [reddit](https://www.reddit.com/r/waybar/comments/1g7o1jl/comment/ltk80ss/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). Put [this file](https://github.com/Alexays/Waybar/blob/master/resources/custom_modules/power_menu.xml) in $HOME/.config/waybar/power_menu.xml
