### ISSUE TITLE
USR1 signal on version 0.10.4 does not restore waybar

### ISSUE THREAD

**Issue by paolomainardi** [Alexays/Waybar#3497]
As reported in the title, the USR1 signal toggle just hides the bar and does not reappear; I had to downgrade to 0.10.3 on Archlinux and the latest version of Sway.

Let me know if I should provide some other useful info.

**Comment by RobertMueller2** [comment]
Probably not needed, this looks similar to #3455,#3477 . 

Can you try if #3459 fixes this for you?

**Comment by paolomainardi** [comment]
Already landed on Arch: https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/commit/0306af03fcb6de6aee1e288f42b0bf1b223513bd it works!
