### ISSUE TITLE
Icon only styles?

### ISSUE THREAD

**Issue by luispabon** [Alexays/Waybar#350]
Sometimes text icons are very small indeed, see below:

![image](https://user-images.githubusercontent.com/6388823/58287755-b91ad800-7da9-11e9-95de-1fbdbd39e1ce.png)

Is there anty way I can target icons only with CSS? Often it's simply a matter of increasing their font size, but if I can't target only icons then text becomes massive in comparison.

**Comment by Alexays** [comment]
You can do it with pango markup atm, e.g.
```json
"format": "<span font='12'>{icon}</span> {capacity}%"
```

**Comment by Neules** [comment]
It works with pango, but it screws up text's vertical alignment too like in this screenshot, where "archimago" is a text going with the icon in the following way, for instance:
```
"format": "<span font='22'></span> ~ {}",
"exec" : "cat /etc/hostname",
```

![this](https://user-images.githubusercontent.com/34288954/94587038-529da800-0282-11eb-9f47-8e4d6b5b096e.png)

**Comment by LucasTavaresA** [comment]
this is a better source imo https://docs.gtk.org/Pango/pango_markup.html, had to change line_height cause the bar becomes too big

**Comment by rustbuckett** [comment]
I was having a similar issue. The pango markup works, but would be tedious to enter this for every icon in my config. Instead, I installed [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts), then used fc-list to find the font name that I wanted and added that to style.css. Now the icons match the font size.

**Comment by diegodorado** [comment]
Use the nerdfont variant Propo, i.e.:  "JetBrainsMono Nerd Font Propo", which isn't strictly monospaced, and works well in this scenario
