### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Jimmytalksalot** [Alexays/Waybar#3505]
so I wanted to make new module, I'm new linux user, so I'm not smart when configuring thingy.

i tried to get new module on waybar, but it wont show up, I need help on how fix, (sorry for bad Engli) 

},
"custom/apple": {
	"format": "󰺁 HINT!",
	"on-click": "rofi -show drun",
	"tooltip": false,
	"tooltip-format": "dada",
},

when I put code in, the module so show up when I add to waybar.

"modules-left": [	
	"group/mobo_drawer",
	"hyprland/workspaces#rw",
	"tray",
	"mpris", 
	],
    
"modules-center": [
	"clock#2",
	"custom/swaync",
	],
    
"modules-right": [
	"hyprland/window",  
	"battery",
 	"group/audio", 
	"custom/power",
	],
}

it works wen I do preset modules, but not when I make new one, please help.

**Comment by IAGOnGithub** [comment]
First of all, you need to add `"custom/apple"` to one of the module groups or else it won't show up.

```diff
...
"modules-right": [
"hyprland/window",
"battery",
"group/audio",
+"custom/apple",
"custom/power"
]
...
```

**Comment by Jimmytalksalot** [comment]
the fuck u think i did

**Comment by Jimmytalksalot** [comment]
the problem was the thing that I added the thing on the very beginning of the first line.

**Comment by Jimmytalksalot** [comment]
> First of all, you need to add `"custom/apple"` to one of the module groups or else it won't show up.
> 
> ```diff
> ...
> "modules-right": [
> "hyprland/window",
> "battery",
> "group/audio",
> +"custom/apple",
> "custom/power"
> ]
> ...
> ```

quit helping people, actually quit.

**Comment by Jimmytalksalot** [comment]
ok im sorry for being rude,

**Comment by IAGOnGithub** [comment]
what
