### ISSUE TITLE
Different locales for date and time are ineffective.

### ISSUE THREAD

**Issue by siyia2** [Alexays/Waybar#3509]
// CLOCK/DATE STUFF
"clock": {
    "format": "{:%a %d %b, %H:%M}",
    "on-click": "gsimplecal",
    "on-click-right": "killall gsimplecal",
    "scroll-step": 1,
    "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
    "tooltip": true,
    "locale": "el_GR.UTF-8"
},

"clock#utc": {
    "format": "UTC {:%H:%M}",
    "on-click": "gsimplecal",
    "on-click-right": "killall gsimplecal",
    "scroll-step": 1,
    "tooltip-format": "UTC {:%A, %d %B %Y, %H:%M}",
    "tooltip": true,
    "timezone": "UTC",
    "locale": "el_GR.UTF-8"
}

my locale is effectively applied when hovering over date, but not directly on waybar.

**Comment by TeChn4K** [comment]
Did you try the tips here? : https://github.com/Alexays/Waybar/wiki/Module:-Clock#troubleshooting

> if using clock instead of simpleclock, the locale will default to C regardless of the locale settings. To override this behavior you have to perpend L to the formatting string. For example, {:%a %m %d} becomes {:L%a %m %d}.

**Comment by siyia2** [comment]
Great it works, i think this tip got added along the way, closin...
