### ISSUE TITLE
Media module casuing error

### ISSUE THREAD

**Issue by husam212** [Alexays/Waybar#355]
`custom/media` module is causing this error: `[error] media stopped unexpectedly, is it endless?`

**Comment by Alexays** [comment]
Launch the script by hand, you may missing some dependencies :)

**Comment by husam212** [comment]
Running it manually works, it outputs this:
```
{"text": "Falkenbach - Heathen Foray", "class": "custom-spotify", "alt": "spotify"}
```

**Comment by anhvo8836** [comment]
I can't seem to get the custom/media module to work. Hoping you can help!

Im using the waybar-hyprland-git package from the AUR

When launching waybar from the terminal, I get the "media stopped unexpectedly, is it endless error". I've left the custom/media block exactly how it comes in the waybar config file, absolutely no changes.

I've downloaded the mediaplayer.py script from the repo, placed it into $HOME/.config/waybar and made it executable. I've also made no changes to the file. When manually running the script (python $HOME/.config/waybar/mediaplayer.py), I get the following error...

Traceback (most recent call last) 
File "/home/anh/.config/waybar/mediaplayer.py", line 8, in <module>
gi.require_version('Playerctl', '2.0')
/\/\/\/\/\/\/\/\/\
AttributeError: module 'gi' has no attribute 'require_session'

**Comment by smlrods** [comment]
I fixed the issue by running the following command to grant execute permissions to the mediaplayer.py script in the Waybar configuration directory:

```bash
chmod +x $HOME/.config/waybar/mediaplayer.py
```

**Comment by tjc0726** [comment]
> I can't seem to get the custom/media module to work. Hoping you can help!
> 
> Im using the waybar-hyprland-git package from the AUR
> 
> When launching waybar from the terminal, I get the "media stopped unexpectedly, is it endless error". I've left the custom/media block exactly how it comes in the waybar config file, absolutely no changes.
> 
> I've downloaded the mediaplayer.py script from the repo, placed it into $HOME/.config/waybar and made it executable. I've also made no changes to the file. When manually running the script (python $HOME/.config/waybar/mediaplayer.py), I get the following error...
> 
> Traceback (most recent call last) File "/home/anh/.config/waybar/mediaplayer.py", line 8, in < module > gi.require_version('Playerctl', '2.0') AttributeError: module 'gi' has no attribute 'require_version'

try
`sudo pacman -S python-gobject` or similar
