### ISSUE TITLE
I'm getting color bledding on the edge of cava module(custom)

### ISSUE THREAD

**Issue by Ace-c** [Alexays/Waybar#3550]
![2024-08-22-184852_hyprshot](https://github.com/user-attachments/assets/2a5d27fc-5041-4c54-bb78-cc74edb64d5b)

This is not only with cava, It's also with the workspace, maybe the animation cause problems.

Here's my script for cava : 
```
#! /bin/bash
is_cava_ServerExist=`ps -ef|grep -m 1 cava|grep -v "grep"|wc -l`
if [ "$is_cava_ServerExist" = "0" ]; then
	echo "cava_server not found" > /dev/null 2>&1
#	exit;
elif [ "$is_cava_ServerExist" = "1" ]; then
  killall cava
fi

bar="▁▂▃▄▅▆▇█"
dict="s/;//g;"

# creating "dictionary" to replace char with bar
i=0
while [ $i -lt ${#bar} ]
do
    dict="${dict}s/$i/${bar:$i:1}/g;"
    i=$((i=i+1))
done

# make sure to clean pipe
pipe="/tmp/cava.fifo"
if [ -p $pipe ]; then
    unlink $pipe
fi
mkfifo $pipe

# write cava config
config_file="/tmp/waybar_cava_config"
echo "
[general]
bars = 20
[output]
method = raw
raw_target = $pipe
noise_reduction = 0.7
data_format = ascii
ascii_max_range = 5
" > $config_file

# run cava in the background
cava -p $config_file &

# reading data from fifo
while read -r cmd; do
    echo $cmd | sed $dict
done < $pipe
```

I also tried Inbuilt cava module but same Issue...

**Comment by StarsEnd33A2D17** [comment]
I just tested your script with waybar v0.11.0, and it seems to be working fine. You might want to check the CSS?

**Comment by Ace-c** [comment]
Script was never a problem, I just included if anyone asked for script.. I think the problem is with my waybar version, like there is multiple version of it .. one for support with waybar-cava-git, and mine is the one in official arch repo ... or other way around, as you recommend I should check my CSS.. well let me see

**Comment by Ace-c** [comment]
This is my css for cava module - I think it's okay, but maybe some padding or margin stuff caused problem.. since it was with waybar drawer

box#cava {
  margin-left: 2px;
  margin-right: 7px;
  margin-top: 7px;
  margin-bottom: 7px;
  padding-left: 10px;
  padding-right: 10px;
  border-radius: 10px;
  background-color: transparent;
  color: @cava;
}

**Comment by StarsEnd33A2D17** [comment]
Try removing all CSS first and test to see if the issue persists. If the problem persists, build and test with the latest git version for further investigation. (not the cava-git branch).

**Comment by Ace-c** [comment]
The culprit was #box, I had to think out of box of this...
