### ISSUE TITLE
CSS transition unatrual

### ISSUE THREAD

**Issue by littleblack111** [Alexays/Waybar#3558]
So I seen 
![image](https://github.com/user-attachments/assets/3ef7590e-c277-418c-a094-935c8bcbf4a4)
I really love its worksapce. but they didn't release their dots.

Hence. I tried re-creating the effect myself. css:
```
#workspaces {
    background-color: @BACKGROUND;
    border-radius: 16px;
}

#workspaces button {
    border-radius: 16px; 
    background-color: @YELLOW;
    margin-top: 4px;
    margin-bottom: 2px;
    margin-left: 1px;
    margin-right: 1px;
    transition: all 0.3s;
}

#workspaces button.active {
    background-color: @ACCENT;
    margin-left: 4px;
    margin-right: 4px;
    padding-left: 10px;
    padding-right: 10px;
}


#workspaces button.empty {
    background-color: @FOREGROUND;
    border-radius: 12px;
}

#workspaces button.urgent {
    background-color: @RED;
    border-radius: 16px 16px 16px 16px; 
}
```
and the format-icons is just space

not only the transition seem very laggy. at the last few second of it. looks like just skipped the transition and put its postion there. cant really record atm(cuz i didnt finish setting up everything(xdg-desktop-portal etc))

and also if anyone know how did they do the workspace. please tell me

**Comment by daviiiL** [comment]
You can add a transition timing function, such as "linear", to your button transition like:
`transition: all 0.3s **linear**;`

**Comment by littleblack111** [comment]
what?! that fixes it.

**Comment by littleblack111** [comment]
tried to use the same cubic-bezier for my hyprland worksapce animation(    bezier = fast-slow, 0.33, 0.8, 0, 1). but it still snaps it. dunno why, linear seems to be the only one that give a fluent ending...
