### ISSUE TITLE
Clock module doesn't change with system timezone change

### ISSUE THREAD

**Issue by ThatOneCalculator** [Alexays/Waybar#3570]
Right now, I'm in Argentina (ART timezone) coming from Los Angeles (PDT timezone). My system clock updated automatically -- when I'm in GNOME, the time shows correctly, the `date` command shows the time correctly, as well as `tty-clock`, `swaylock`, `timedatectl`, etc. However, Waybar's clock module is still stuck in my old timezone. 

![image](https://github.com/user-attachments/assets/ae4ecd8f-b17b-43cc-ab6c-b4c639d30c32)

![image](https://github.com/user-attachments/assets/e8d127e9-105e-4ce3-9646-42d5b694695d)

**Comment by pbosab** [comment]
happened to me too today, do you have testing repo enabled? if yes, the problem comes from "core-testing/tzdata" version 2024b-1
downgrading to 2024a-2 solved the issue for me.

**Comment by ThatOneCalculator** [comment]
I don't have the testing repo enabled -- my version is `2024a-2`.

**Comment by RedBlizard** [comment]
I have the same problem, also no testing repo installed just the regular package.

**Comment by eeelbrens** [comment]
well tzdata-2024b-1 was just released to core. and so I have the same issue with my waybar clock and I currently have no means of downgrade. this time it defaulted to UTC for me (down from a UTC+3 region)

**Comment by grgpw** [comment]
there's also an error/warning when starting waybar:

`[2024-09-08 14:37:19.653] [warning] Timezone: Europe/Berlin. std::chrono::tzdb: cannot locate zone: Europe/Berlin`

**Comment by RedBlizard** [comment]
If you need the older tzdata package well here you have ! just go to the letter T scroll all the way down and download the older package !   https://archive.archlinux.org/packages/

**Comment by ThatOneCalculator** [comment]
Again, the older version doesn't work. I think this is a bug with waybar's implementation.

**Comment by samuelemusiani** [comment]
I also have this problem and if I try to set the `timezone` i get:
```
[2024-09-08 15:30:26.444] [warning] Timezone: Europe/Rome. std::chrono::tzdb: cannot locate zone: Europe/Rome
```

I hope for a fix :)

**Comment by eeelbrens** [comment]
> there's also an error/warning when starting waybar:
> 
> `[2024-09-08 14:37:19.653] [warning] Timezone: Europe/Berlin. std::chrono::tzdb: cannot locate zone: Europe/Berlin`

strange... I don't get any errors

**Comment by eeelbrens** [comment]
also downgrading my tzdata package did fix it for me

**Comment by alba4k** [comment]
I haven't moved a single meter, however...
![immagine](https://github.com/user-attachments/assets/94a56286-c908-4e67-889e-08d52006c604)

**Comment by steveWang** [comment]
I believe this is a C++ standard library bug -- I filed an issue for libc++, and it seems that libstdc++ fixed the bug (but just haven't shipped a version containing the fix).

https://github.com/llvm/llvm-project/issues/107779

**Comment by ThatOneCalculator** [comment]
For now, should Waybar maybe switch to using the `date` command (or some library that uses it)?

**Comment by 3ri4nG0ld** [comment]
It was literally driving me crazy, I thought I had something wrong with my configuration.
I hope they fix it soon, it's quite annoying to have a late time on the clock.

**Comment by bradrn** [comment]
I just updated Waybar and am also experiencing this issue. As suggested by @eeelbrens, downgrading `tzdata` has fixed it for now.

**Comment by ThatOneCalculator** [comment]
And again, that doesn't work for everyone. Furthermore, downgrading system libraries generally isn't rhe best idea.

**Comment by bradrn** [comment]
Yes, I’m aware. I only wanted to document that this solution worked for me too.

**Comment by robertsbd** [comment]
Just commenting that I am also experiencing this issue as of yesterday, probably after running pacman -Syu in arch by the sounds of it.

**Comment by Kamiksss** [comment]
I've experienced this issue after one of the system updates. Downgrading tzdata to version 2024-a1 fixed the problem.

**Comment by ThatOneCalculator** [comment]
Obviously not a permanent or complete solution, but I've added this for now as a stopgap to my config:

```json
	"custom/clock": {
		"format": " {}",
		"exec": "date +'%I:%M'",
		"interval": 1
	},
```

**Comment by VladP812** [comment]
Thanks to tzdata devs, I'm 1 hour younger now.
My condolences to people living in UTC- time zones.

**Comment by Magnitudexx** [comment]
Updated to tzdata 2024b-2 and i am happy to say it now works as expected

**Comment by adnanzareef** [comment]
Well, the latest ```gcc``` update fixed the issue on Arch Linux without ```tzdata``` downgrading.

**Comment by eeelbrens** [comment]
yeah I did check and update both packages and it's been fixed
@ThatOneCalculator I guess time to close that issue now

**Comment by ThatOneCalculator** [comment]
@eeelbrens I think you guys were having a different issue from me.

I'm currently on Waybar 0.11, tzdata 2024b-2, and I'm STILL getting the original timezone issue.

The current time is actually 14:33.

![image](https://github.com/user-attachments/assets/182acde8-47a3-4633-8d7b-37c225d54a96)

This is ***NOT*** about it being at UTC -- this is about it being stuck in my old timezone.

**Comment by ThatOneCalculator** [comment]
This now seems to be resolved

**Comment by lypeInvictvs** [comment]
My solucion (for portuguese):

I created a script "_dia-semana.sh_" (in **script** folder)

```
#!/bin/bash
dias=("Dom" "Seg" "Ter" "Qua" "Qui" "Sex" "Sáb")
meses=("JAN" "FEV" "MAR" "ABR" "MAI" "JUN" "JUL" "AGO" "SET" "OUT" "NOV" "DEZ")

echo "<U+F073> ${dias[$(date +%w)]}, $(date +%d)/${meses[$(date +%m)-1]}/$(date +%Y) 
<U+F017> $(date +%H:%M:%S)"
```


in then (config.jsonc):

```
 
"modules-left": [
 //          "clock",
             "custom/date",

        "hyprland/workspaces"
    ],
```

```
"custom/date": {
        "exec": "~/.config/waybar/scripts/dia-semana.sh",
    "interval": 1
    },
```

Result:

![Image](https://github.com/user-attachments/assets/23150eec-04f7-4599-972a-f9a127ff3617)
