### ISSUE TITLE
Once hidden waybar cannot be shown

### ISSUE THREAD

**Issue by hramrach** [Alexays/Waybar#3578]
From FAQ:

> You can toggle the visibility of the bars with:
> 
> `killall -SIGUSR1 waybar`

However, the bar stays hidden when sending SIGUSR1, only SIGUSR2 shows it again.

Version: 0.10.4

**Comment by leon-erd** [comment]
Is this https://github.com/Alexays/Waybar/issues/3497 not related? Can you test if this is fixed on latest git?
Because version 0.10.4 is from July 17 and the fix landed on July 20

**Comment by hramrach** [comment]
Thanks for looking into this. Yes, that fix should resolve it. Will try to apply it to the ditribution package in some way.
