### ISSUE TITLE
Child process does not stops

### ISSUE THREAD

**Issue by niktob560** [Alexays/Waybar#358]
After killing waybar (for refreshing config, etc), child processes keeps working  
I spent 10 minutes on killing custom script with loop for checking capslock state  
Fix that plz :)  
ArchLinux, waybar-git from AUR  
Waybar v0.6.6-28-gfcf2d18 (May 30 2019, branch 'master')

**Comment by toke** [comment]
I had looked into that and I have a "rough" version. But as I'm not fluent in C++ it's a bit harsh and still dies with a segfault some seconds later (which is not as bad a it has to be exited anyway ;))

BUT: As a fix for (at least bash-scripts) it should be possible to add `set -euo pipefail` in them and if one of the outputs fail it should exit.

**Comment by b-zee** [comment]
I have encountered the same problem and can confirm processes do not exit. I was testing styles and 'reloaded' sway multiple times.

Excerpt from `ps --forest aux`:

```
user      17502  0.0  0.0   7172  2804 tty1     S    13:12   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      17509  0.0  0.1 177584 19112 tty1     Sl   13:12   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      17567  0.0  0.0   7172  2856 tty1     S    13:12   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      17574  0.0  0.1 177584 19208 tty1     Sl   13:12   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      17657  0.0  0.0   7172  2952 tty1     S    13:14   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      17663  0.0  0.1 177584 19188 tty1     Sl   13:14   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      17737  0.0  0.0   7172  2724 tty1     S    13:15   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      17743  0.0  0.1 177584 19116 tty1     Sl   13:15   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      17928  0.0  0.0   7172  2772 tty1     S    13:16   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      17932  0.0  0.1 177584 19188 tty1     Sl   13:16   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      17989  0.0  0.0   7172  2744 tty1     S    13:17   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      17996  0.0  0.1 177584 19124 tty1     Sl   13:17   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      18056  0.0  0.0   7172  2816 tty1     S    13:17   0:00 sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      18063  0.0  0.1 177584 19100 tty1     Sl   13:17   0:00  \_ python /home/user/.config/waybar/mediaplayer.py
user      18592  0.0  0.3 980108 54124 tty1     Sl+  13:20   0:00 waybar -b bar-0
user      18608  0.0  0.0   7172  2956 tty1     S    13:20   0:00  \_ sh -c python $HOME/.config/waybar/mediaplayer.py 2> /dev/null
user      18614  0.0  0.1 177584 19140 tty1     Sl   13:20   0:00      \_ python /home/user/.config/waybar/mediaplayer.py
```

**Comment by fourstepper** [comment]
This issue is also present for me - perhaps this could be somehow handled from the mediaplayer.py script itself?

**Comment by daym** [comment]
I spent several months wondering why I'm getting a red screen of death at random intervals.

I finally got fed up enough and debugged it.

The reason is that I run swaylock like this:

```
    "custom/lock": {
        "format": "{icon} {}",
        "return-type": "json",
        "format-icons": {
            "default": "Lock"
        },
        "escape": true,
    }
```

And because in reaction to this issue waybar implemented autokill of child processes.

So I have a question: How do I use waybar as a launcher now? I DO NOT want my programs to be killed when I turn off a screen :P

**Comment by ninetailedtori** [comment]
I'm currently using process detaching through `& disown` but tmux or screen works too. When gtklock gets killed by Waybar I don't get a RSOD so it helps with testing, as if I just resume from suspend I can see it die if I didn't detach it right, so that's been how I've tested a few methods. Bit unsure rn. Also gotta add an after-sleep.service to relaunch waybar lmao.
