### ISSUE TITLE
clock module showing UTC time instead of the local time.

### ISSUE THREAD

**Issue by rik-x2907** [Alexays/Waybar#3584]
I have set the timezone in the config as well but nothing changed. the date command is showing the local time.

**Comment by pradyparanjpe** [comment]
I'm having the same problem.

**My platform**:
**OS**: Arch Linux x86_64
**Kernel**: 6.10.8-arch1-1 
**Pacman info**:
*Waybar Version*         : 0.10.4-2
*Build Date*      : Friday 02 August 2024 12:51:47 PM
**Waybar version**: Waybar v0.10.4
**Waybar config**:     `"format": "{:%Y-%m-%d %H:%M:%S}",`

**Comment by Spark117318** [comment]
See #3575 . It might related to tzdata. Downgrading the tzdata can solve it.

**Comment by dR3b** [comment]
Yes same error after tzdata update. `timedatectl` shows the right "Local time".

**Comment by trembel** [comment]
Same issue here.

**Comment by steepboy** [comment]
The same, waybar shows only UTC time

**Comment by seocamo** [comment]
i got this problem too, i try the timezone too but it don't help, i trye the timedatectl too and it give me the right info.

**Comment by steepboy** [comment]
> i got this problem too, i try the timezone too but it don't help, i trye the timedatectl too and it give me the right info.

@seocamo  I found a way to fix it, you need to downgrade tzdate to 2024a- 2. Here is a link to past versions https://archive.archlinux.org/packages/t/tzdata/

**Comment by seocamo** [comment]
> > i got this problem too, i try the timezone too but it don't help, i trye the timedatectl too and it give me the right info.
> 
> @seocamo I found a way to fix it, you need to downgrade tzdate to 2024a- 2. Here is a link to past versions https://archive.archlinux.org/packages/t/tzdata/ (Correction, it wasn't even me, it was written above)

Thx, yes this works

a little more info, i was looking on the source and it had a env TZ that it look at, 4 months ago, so i try to set it and it don't change anything, so it look like it is one of the commits 10 months ago ?? and then i see this message is there missing data in the tzdata package or do waybar use it wrong ??

**Comment by tjavdar** [comment]
UTC time shown in waybar also in my case. (waybar-0.10.4-2, tzdata-2024b-1 on Arch).

- Noteworthy:  datetimecontrol, i3status do show right time (they must refer to tzdata?)
- Tried to specify  `"timezone": "Europe/Stockholm"`  explicitly in the  `clock` module of  `~/config/waybar/config`, did not help
- Downgrading to  `tzdata-2024a-2` fixed it for me too.

Obzervation: `tzdata` on Arch is listed to be required by `glibc` and `Python`, so it must be used by **many** other programs, seems to be a very essential part. I'm inclined to think that waybar access to tzdata is somehow broken.

**Comment by odomingao** [comment]
Downgrading tzdata caused some breakage for me. Not complete system breakage, but some programs started segfaulting after the downgrade.

**Comment by tgy** [comment]
Spent the whole day thinking it was 2 hours earlier, we gotta do something :face_with_head_bandage:

**Comment by zachkarr** [comment]
waybar-v0.10.4
tzdata-2024b-1

I am experiencing this issue on two different machines, both running Garuda Hyprland. Yesterday, I updated the packages on my laptop and noticed that the time was 5 hours ahead.

Today, when I used my desktop, Waybar was showing the correct time. I ran pkill waybar && hyprctl dispatch exec waybar to verify that Waybar would still display the correct time, which it did. However, after updating my desktop and upgrading the tzdata package, I reloaded Waybar, and it now showed the time as 5 hours ahead.

Adding the timezone to the clock configuration for Waybar doesn't seem to have any effect, as others have also mentioned.

For reference, here is the output of timedatectl:

Local time: Mon 2024-09-09 19:19:54 CDT
Universal time: Tue 2024-09-10 00:19:54 UTC
RTC time: Tue 2024-09-10 00:19:54
Time zone: America/Chicago (CDT, -0500)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no

I haven't noticed any other applications displaying the incorrect time.

**Comment by CrossScarDev** [comment]
setting timezone causes warning: `[warning] Timezone: US/Pacific. std::chrono::tzdb: cannot locate zone: US/Pacific`

**Comment by tgy** [comment]
The release from IANA that seems to be causing issue is `2024b`: [Release 2024b - 2024-09-04 12:27:47 -0700](https://data.iana.org/time-zones/tzdb/NEWS). Nothing peculiar in the commit by @andyrtr [here](https://gitlab.archlinux.org/archlinux/packaging/packages/tzdata/-/commit/3fd32dfbf1b0e4ac78eedef0dee5263cbee42e1d).

**Comment by EssenSea** [comment]
same problem here.

**Comment by nduartech** [comment]
I am also facing the same issue, would be great if there was a patch :)

**Comment by tgy** [comment]
```
cd /tmp
wget 'https://archive.archlinux.org/packages/t/tzdata/tzdata-2024a-2-x86_64.pkg.tar.zst'
sudo pacman -U tzdata-2024a-2-x86_64.pkg.tar.zst
```

**Comment by jbiel** [comment]
New GCC packages with a fix for this [have been built](https://github.com/Alexays/Waybar/issues/3575#issuecomment-2340418175) and are now in `core-staging` before they're released as GA.

If you downgrade tzdata and don't pin the downgrade, pacman will upgrade it again. Also, someone noted segfaults after downgrading tzdata. I'm choosing to run the updated GCC for now, as that will be automatically upgraded when appropriate.

```
cd /tmp
wget https://mirror.pkgbuild.com/core-staging/os/x86_64/gcc-14.2.1+r134+gab884fffe3fc-1-x86_64.pkg.tar.zst
wget https://mirror.pkgbuild.com/core-staging/os/x86_64/gcc-libs-14.2.1+r134+gab884fffe3fc-1-x86_64.pkg.tar.zst
sudo pacman -U gcc-14.2.1+r134+gab884fffe3fc-1-x86_64.pkg.tar.zst gcc-libs-14.2.1+r134+gab884fffe3fc-1-x86_64.pkg.tar.zst
```

**Comment by alba4k** [comment]
@jbiel just a heads up, this will also work

`sudo pacman -U https://mirror.pkgbuild.com/core-staging/os/x86_64/gcc-14.2.1+r134+gab884fffe3fc-1-x86_64.pkg.tar.zst https://mirror.pkgbuild.com/core-staging/os/x86_64/gcc-libs-14.2.1+r134+gab884fffe3fc-1-x86_64.pkg.tar.zst`

**Comment by aloispichler** [comment]
back to normal after `yay -Syu`.

**Comment by haansn08** [comment]
10 pm. Wife goes to bed early. I write an email and do some internet stuff. I go to bed. Look at the phone. Suddenly it's past midnight! "There is a bug with the time display!" I exclaim.

My wife responds, "There is a bug with your head, that's what it is."

I believe her.

**Comment by asahi-m** [comment]
It seems that the latest Arch Linux update (maybe 14.2.1+r134+gab884fffe3fc-1?) fixed this.

**Comment by rudolflovrencic** [comment]
I can cofirm that the issue is gone on Arch. I guess one of these updates fixed it:
- `upgraded tzdata (2024b-1 -> 2024b-2)`
- `upgraded gcc-libs (14.2.1+r32+geccf707e5ce-1 -> 14.2.1+r134+gab884fffe3fc-1)`

**Comment by Phantomwise** [comment]
Same here, I updated Arch and now I don't get the weird `[warning] Timezone: Europe/Paris. std::chrono::tzdb: cannot locate zone: Europe/Paris` error anymore and my clock shows the correct time \o/

**Comment by itaranto** [comment]
@rik-x2907 This has been solved by using the latest `tzdata` package, can you please close this issue?

There's _a lot_ of threads about the clock module having issues with timezones, it's very hard to understand.

**Comment by jennydaman** [comment]
I can confirm that the latest waybar and tzdata packages on Arch Linux work. However, I am still experiencing this issue with waybar installed from nixpkgs-unstable using home-manager on Arch Linux.

**Comment by eoli3n** [comment]
downgrading a package ``is not`` a fix, it is a workaround

**Comment by rossabaker** [comment]
NixOS, waybar-0.14.0, gcc-15.2.0, `America/Indiana/Indianapolis`:

Mine fails when my `/etc/localtime` link is more than two path segments deep into `zoneinfo`.  I believe it's [gcc.gnu.org/bugzilla/show_bug.cgi?id=122567](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122567).

I can work around it in one of two ways:

- Set `/etc/localtime` to a name with fewer than three segments.  `timedatectl` is one way to do this:

  ```console
  # timedatectl set-timezone America/Indianapolis
  ```

- Create an `/etc/timezone` file with any valid time zone name.  libgcc falls back to this after failing to parse /etc/localtime.

  ```console
  # echo "America/Indiana/Indianapolis" > /etc/timezone
  ```
