### ISSUE TITLE
[Newbie] [Custom] AUR updates module broke after update (arch linux)

### ISSUE THREAD

**Issue by Sk7Str1pe** [Alexays/Waybar#3594]
![2024-09-12-224933_hyprshot](https://github.com/user-attachments/assets/026bc91c-476c-4200-a509-8772dc664c8b)
my module structure. after update it suddenly stopped to work. is syntax bad or its waybar issue? and what should i do to fix it? (waybar-updates command exists)

**Comment by PaoloReyes** [comment]
Same problem here, looks like icon manual indexes are the problem

**Comment by PaoloReyes** [comment]
Still not know how to solve it

**Comment by PaoloReyes** [comment]
You can try running waybar on your terminal.

Mine is showing this 
![image](https://github.com/user-attachments/assets/99c16d02-dbb0-4a2a-a4e1-2465c2e51e60)

**Comment by PaoloReyes** [comment]
And my config is pretty similar to yours 
![image](https://github.com/user-attachments/assets/b6d201af-c8ba-434c-9975-a63237d06618)

**Comment by PaoloReyes** [comment]
Looks like the only change was an update on fmt dependency. Ill try downgrading and see if ti solves it

**Comment by derfehler** [comment]
fmt is the problem

**Comment by PaoloReyes** [comment]
Yes, it is but i am not able to downgrade since breaks compiled libraries, I will just try to downgrade waybar

**Comment by KorcakDaniel** [comment]
> Yes, it is but i am not able to downgrade since breaks compiled libraries, I will just try to downgrade waybar

Downgrading waybar won't solve anything, since it needs fmt version 10 to work, and that version was overwritten with 11 due to rolling release.

I've tried soft linking the library from version 11 to 10, but there were some symbols missing. Maybe running the version 10 in parallel would work, but I haven't tried that yet.
https://gitlab.archlinux.org/archlinux/packaging/packages/fmt/-/tree/10.2.0-1

Either you could wait or submit a PR with a fix. 😀

**Comment by PaoloReyes** [comment]
I found a solution, downgrade fmt, spdlog and waybar. That solve it for me

**Comment by PaoloReyes** [comment]
These are the versions that worked 

spdlog: https://gitlab.archlinux.org/archlinux/packaging/packages/spdlog/-/tree/1.14.1-1?ref_type=tags
fmt: https://gitlab.archlinux.org/archlinux/packaging/packages/fmt/-/tree/10.2.0-1
waybar: https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/tree/0.10.4-2?ref_type=tags

**Comment by psa-anddev** [comment]
I managed to find a way to make this work without having to downgrade. It seems, the problem occurs when you set the format to be `"{icon} {}"`. What I have done is to comment the format line out and instead pipe my update script into `xargs` and echo the icon and the number. My script is called `pacman-updates` so, I change the exec line to be `pacman-updates | xargs -I{} echo 📦 {}`. That, in my case, shows the updates as I expected to see them. Once the issue with fmt is fixed, all you need to do is uncomment the format property and reset exec to just call your script.

**Comment by Alexays** [comment]
Should be good with latest version (0.11.0)

**Comment by kerichdev** [comment]
(it is not, in fact, good with the latest version)

![image](https://github.com/user-attachments/assets/e6e196de-9103-41f5-85c5-142ad6a24ced)
building waybar from the latest commit as of rn still has the same issue

**Comment by Sk7Str1pe** [comment]
> Should be good with latest version (0.11.0)

![Uploading image.png…]()
nope its not, built latest commit, nothing changed

**Comment by Sk7Str1pe** [comment]
> Should be good with latest version (0.11.0)

no, its not. just built waybar-git from aur
`[2024-09-13 15:31:49.908] [info] Using configuration file /home/Sk7Str1p3/.config/waybar/config.jsonc
[2024-09-13 15:31:49.908] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2024-09-13 15:31:49.908] [info] Using CSS file /home/Sk7Str1p3/.config/waybar/style.css
[2024-09-13 15:31:49.911] [info] Hyprland IPC starting
[2024-09-13 15:31:49.911] [info] Loading persistent workspaces from Waybar config
[2024-09-13 15:31:49.911] [info] Loading persistent workspaces from Hyprland workspace rules
[2024-09-13 15:31:49.912] [warning] module cava: Unknown module: cava
[2024-09-13 15:31:52.362] [error] custom/pacman: cannot switch from manual to automatic argument indexing`
 version is Waybar v0.11.0-4-gd177969f (branch 'master')

**Comment by alekgr** [comment]
this is s till an issue 


waybar v0.11.0-4-gd177969f (branch 'master')
 alek@rocket  ~  hyprctl dispatch exec waybar
ok
 alek@rocket  ~  killall waybar
 alek@rocket  ~  waybar
[2024-09-13 17:10:22.819] [info] Using configuration file /home/alek/.config/waybar/config
[2024-09-13 17:10:22.821] [info] Discovered appearance 'dark'
[2024-09-13 17:10:22.821] [info] Using CSS file /home/alek/.config/waybar/style.css
[2024-09-13 17:10:22.825] [info] Hyprland IPC starting
[2024-09-13 17:10:22.826] [info] Loading persistent workspaces from Hyprland workspace rules
[2024-09-13 17:10:22.892] [info] Found device AT Translated Set 2 keyboard at '/dev/input/event2'
[2024-09-13 17:10:23.462] [info] Found device Keychron Keychron K2 at '/dev/input/event10'
[2024-09-13 17:10:23.816] [info] Bar configured (width: 3840, height: 37) for output: HDMI-A-1
[2024-09-13 17:10:23.816] [info] Bar configured (width: 3840, height: 30) for output: HDMI-A-1
/usr/bin/waybar-updates: line 185: [: : integer expression expected
/usr/bin/waybar-updates: line 185: [: : integer expression expected
[2024-09-13 17:10:25.012] [error] custom/pacman: cannot switch from manual to automatic argument indexing

waybar-updates still broken

**Comment by Sk7Str1pe** [comment]
So @Alexays nothing changed. It still says "cannot switch from manual to automatic argument indexing". Latest working version - 0.10.4-2

**Comment by Koko2110** [comment]
> So @Alexays nothing changed. It still says "cannot switch from manual to automatic argument indexing". Latest working version - 0.10.4-2

I was having that issue for days on end and was also thinking the new version didn't fix it. However, I solved it by deleting the binaries from the waybar package manually and reinstalling. Seems that on Arch at least pacman doesn't rebuild them for some reason, even though I had specified to perform a clean build.

You can use `pacman -Ql waybar` to see which files the package has in `/usr/bin`, remove them and reinstall if you are on Arch.

**Comment by justbispo** [comment]
I had the same error `cannot switch from manual to automatic argument indexing`. What actually fixed was to change `"format": "{icon} {}"` to `"format": "{} {icon}"` on my pacman custom module and change `"format": "{icon} {text}"` to `"format": "{} {icon}"` on my custom media module, which comes from the default config file.

**Comment by savely-krasovsky** [comment]
I am the maintainer of `waybar-updates`, this format should fix integer issue `"format": "{icon}{0}"`

**Comment by Sk7Str1p3** [comment]
I think issue is solved
