### ISSUE TITLE
arch fmt(libfmt) current version is up to 11, so libfmt.so.10 is no longer exists.

### ISSUE THREAD

**Issue by EssenSea** [Alexays/Waybar#3596]
waybar: error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory.

current fmt in /usr/lib: 
/usr/lib/libfmt.so.11
/usr/lib/libfmt.so.11.0.2
/usr/lib/libfmt.so

**Comment by peiwithhao** [comment]
i got same wrong few hours ago, so i tried the AUR waybar-cava-git,it works!
But actually i better want to build myself ,so i will try build it from source for solving it! :)

**Comment by OSITO326** [comment]
I had the same problem 🫠

Downgrade the package `fmt` -> v10.2.0-1 for temporary solution, until they update waybar 😅

**Comment by jakeyhanna** [comment]
I seem to still have this problem even with waybar 0.11.0
