### ISSUE TITLE
tray module not showing icons

### ISSUE THREAD

**Issue by Akira-uestc** [Alexays/Waybar#3597]
## version
built from d177969

## description
no icon in tray module
![图片](https://github.com/user-attachments/assets/00a005b5-fc77-4b52-b3db-0c78667e57fb)

## log
```
** (waybar:3152): WARNING **: 17:53:34.711: Status Notifier Item with bus name ':1.6' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
[2024-09-13 17:53:34.712] [error] Failed to create DBus Proxy for :1.6 /org/ayatana/NotificationItem/nm_applet: std::bad_cast

** (waybar:3152): WARNING **: 17:53:35.008: Status Notifier Item with bus name ':1.6' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
[2024-09-13 17:53:35.009] [error] Failed to create DBus Proxy for :1.63 /StatusNotifierItem: std::bad_cast
```

## config
```
    "tray": {
        "icon-size": 18,
        "spacing": 5
    }
```

**Comment by mohammedbilalns** [comment]
i am facing the same issue 
```
** (waybar:2129): WARNING **: 15:55:40.683: Status Notifier Item with bus name ':1.24' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
[2024-09-13 15:55:40.684] [error] Failed to create DBus Proxy for :1.24 /org/ayatana/NotificationItem/nm_applet: std::bad_cast

** (waybar:2129): WARNING **: 15:55:42.197: Status Notifier Item with bus name ':1.24' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
[2024-09-13 15:55:42.204] [error] Failed to create DBus Proxy for :1.60 /org/blueman/sni: std::bad_cast
```

**Comment by GbGp** [comment]
The error originates here in 'get_variant<std::string>(value)':
https://github.com/Alexays/Waybar/blob/d177969f51b3435308a520c9c0385ae80579b255/src/modules/sni/item.cpp#L137
when `name == ItemIsMenu` (and value is supposed to be bool? not sure).

Anyway works for me when I comment out this line.

**Comment by bashprompt** [comment]
Same:
[2024-09-13 07:46:38.934] [error] Failed to create DBus Proxy for :1.25 /org/ayatana/NotificationItem/pcloud1: std::bad_cast

**Comment by warpje5** [comment]
yeah same here. icons for custom/playerctl module doesnt work also, but i believe its fmt issue.
![image](https://github.com/user-attachments/assets/ad2b2f81-8df1-4aa2-9f27-a9ba73d7b0e9)

**Comment by EssenSea** [comment]
same problem.

**Comment by dhaneshdutta** [comment]
facing the same issue

**Comment by 909oce** [comment]
+1

**Comment by Arae-1** [comment]
same problem here

**Comment by mutoroglin** [comment]
I've got the same problems

**Comment by alebastr** [comment]
@Alexays https://github.com/Alexays/Waybar/commit/c2f1a7894b0b99779a482fcc85d30861f461e21a updated fmt to 11.0.1, but this version is known to have a compatibility issue with gtkmm: https://github.com/fmtlib/fmt/issues/4052. Do you mind reverting both fmt dependency bump and your later attempt to fix the compilation in https://github.com/Alexays/Waybar/commit/a4d31ab10d1630cb9104c695d7b777ca12468904?

We need fmt < 11.0.0 or >= 11.0.2, but 11.0.2 is not yet available on wrapdb so it's better to stick with older version. In the meanwhile, I'll try to update the version in wrapdb.

**Comment by Arae-1** [comment]
> same problem here

interestingly it works totally fine when launched from the terminal, however using hyprland's `exec-once` feature it doesn't display 
![image](https://github.com/user-attachments/assets/c75221d0-70e4-46c6-b6ad-813571db73c3)

**Comment by SwayKh** [comment]
I have this same issue, But I wanted to add, That for some reason when I change the font size in style.css the icons reappear for me and disappear when reloading the bar. I have `"reload_style_on_change": true,` to show the font changes instantly.

**Comment by thyeun** [comment]
Version 0.11.0-2 still facing this issue, tray module not showing icons.

**Comment by Akira-uestc** [comment]
> Can confirm, not fixed on Arch (CachyOS). Please reopen.
> 
> ```
> $ waybar
> [2024-09-15 14:06:18.419] [info] Using configuration file /home/user/.config/waybar/config
> [2024-09-15 14:06:18.421] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
> [2024-09-15 14:06:18.421] [info] Using CSS file /home/user/.config/waybar/style.css
> [2024-09-15 14:06:18.467] [warning] module sway/language: Disabling module "sway/language", Socket path is empty
> [2024-09-15 14:06:18.585] [error] Failed to create DBus Proxy for :1.121 /StatusNotifierItem: std::bad_cast
> [2024-09-15 14:06:18.585] [error] Failed to create DBus Proxy for :1.126 /StatusNotifierItem: std::bad_cast
> [2024-09-15 14:06:18.588] [info] Bar configured (width: 2560, height: 30) for output: eDP-1
> [2024-09-15 14:06:18.588] [info] Bar configured (width: 2560, height: 30) for output: eDP-1
> [2024-09-15 14:06:18.588] [error] Item '': No icon name or pixmap given.
> [2024-09-15 14:06:18.588] [error] Item '': No icon name or pixmap given.
> [2024-09-15 14:06:19.634] [error] Failed to create DBus Proxy for :1.131 /org/blueman/sni: std::bad_cast
> ```
> 
> ```
> $ waybar --version
> Waybar v0.11.0
> ```
> 
> ```
> $ pacman -Q waybar
> waybar 0.11.0-2.1
> ```
> 
> ```
> $ pacman -Qi waybar
> Installed From  : cachyos-extra-v3
> Name            : waybar
> Version         : 0.11.0-2.1
> Description     : Highly customizable Wayland bar for Sway and Wlroots based compositors
> Architecture    : x86_64
> URL             : https://github.com/Alexays/Waybar/
> Licenses        : MIT
> Groups          : None
> Provides        : None
> Depends On      : atkmm  cairomm  fmt  gcc-libs  glib2  glibc  glibmm  gtk-layer-shell  gtk3  gtkmm3  jack  jsoncpp  libdbusmenu-gtk3  libevdev  libinput
>                   libmpdclient  libnl  libpipewire  libpulse  libsigc++  libwireplumber  libxkbcommon  playerctl  sndio  spdlog  systemd-libs  upower  wayland
>                   libatkmm-1.6.so=1-64  libcairomm-1.0.so=1-64  libgtk-3.so=0-64  libjack.so=0-64  libjsoncpp.so=26-64  libpipewire-0.3.so=0-64
>                   libsndio.so=7-64  libspdlog.so=1.14-64  libudev.so=1-64  libupower-glib.so=3-64
> Optional Deps   : otf-font-awesome: Icons in the default configuration
> Required By     : None
> Optional For    : None
> Conflicts With  : None
> Replaces        : None
> Installed Size  : 2,07 MiB
> Packager        : CachyOS <admin@cachyos.org>
> Build Date      : So 15 Sep 2024 12:15:17 CEST
> Install Date    : So 15 Sep 2024 14:04:33 CEST
> Install Reason  : Explicitly installed
> Install Script  : No
> Validated By    : Signature
> ```

I use `waybar-git` in AUR and the latest git version works for me.
Try:
```
git clone https://aur.archlinux.org/waybar-git.git
cd waybar-git
makepkg -si
```

**Comment by grgpw** [comment]
obviously, there wasn't a new release yet

**Comment by dR3b** [comment]
Arch Linux: extra/waybar `0.11.0-3` work's! Thanks!

**Comment by GaetanLepage** [comment]
> obviously, there wasn't a new release yet

In such cases, can a minor release be done ?

**Comment by kzdixon** [comment]
You should really consider adding this fix to some new release so maintainers properly pick this up. Gentoo recently pushed out 0.11.0 and I was puzzled as to why tray icons suddenly stopped working. Downgrading to 0.10.4 solved it, which I had tried after stumbling my way into a few issues linked to this one.

**Comment by sentakuhm** [comment]
using hyprland-git and i tried both waybar from official arch repo and waybar-git, i get error:
```
** (waybar:43763): WARNING **: 11:35:43.869: Status Notifier Item with bus name ':1.21' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
```
and no try icons.

**Comment by walrus-dot-jpg** [comment]
If you have KDE plasma installed...

`pkill kded6`

The tray will appear instantly. kded6 will restart itself whenever a KDE application is opened, so it is best to run `pkill kded6` every time waybar restarts. I have noticed no issues with kde apps after doing this.

**Comment by givtrah** [comment]
This is still an issue in Waybar 0.14.0. Please fix, its getting tiresome.
