### ISSUE TITLE
Documentations

### ISSUE THREAD

**Issue by Alexays** [Alexays/Waybar#36]

**Comment by OneMoreByte** [comment]
I'd like to try to help this project. Could I try tackling this?

**Comment by Alexays** [comment]
@OneMoreBye Yeah, you can totally go on this, Thanks :D

**Comment by Robinhuett** [comment]
I have stared with the documentation.
I have attached the current state and also added it here for aa first look at it: https://github.com/Robinhuett/Waybar/wiki

[Configuration.txt](https://github.com/Alexays/Waybar/files/2573815/Configuration.txt)
[Customization.txt](https://github.com/Alexays/Waybar/files/2573816/Customization.txt)
[FAQ.txt](https://github.com/Alexays/Waybar/files/2573817/FAQ.txt)
[Home.txt](https://github.com/Alexays/Waybar/files/2573818/Home.txt)
[Installation.txt](https://github.com/Alexays/Waybar/files/2573819/Installation.txt)
[Modules.txt](https://github.com/Alexays/Waybar/files/2573820/Modules.txt)

**Comment by Alexays** [comment]
Oh! Big thanks @Robinhuett, it's perfect! <3
I have made the changes and will make the necessary changes in the future :)

**Comment by Robinhuett** [comment]
No problem. Glad you like it :)
Unfortunatly I have to admit, that already have found some typos in the following pages:
- Configuration
- Customization
- FAQ
- Modules

I have fixed them in my copy of the wiki. It's nothing to major, but better to not have tem in there :)
