### ISSUE TITLE
Bell icon not appearing after system update.

### ISSUE THREAD

**Issue by DHDcc** [Alexays/Waybar#3605]
* Distribution: ArchLinux
* wm: Hyprland
* Kernel version: 6.10.10
* waybar version: v0.10.4

After updating my system, the bell icon on my bar just disappeared.
Here the error I got after updating my system:
```[2024-09-14 19:19:37.526] [error] custom/notify: cannot switch from manual to automatic argument indexing```

here my config for ```custom/notify```: 
```
    "custom/notify": {
      "escape": true,
      "exec": "swaync-client -swb",
      "exec-if": "which swaync-client",
      "format": "{icon} {}",
      "format-icons": {
        "dnd-inhibited-none": " <sup></sup>",
        "dnd-inhibited-notification": "<span foreground='#f38ba8'><sup></sup></span>",
        "dnd-none": " ",
        "dnd-notification": " <span foreground='#f38ba8'><sup></sup></span>",
        "inhibited-none": "<sup>󰜺</sup>",
        "inhibited-notification": "󰵙<span foreground='#f38ba8'><sup></sup></span>",
        "none": " ",
        "notification": " <span foreground='#f38ba8'><sup></sup></span>"
      },
      "on-click": "sleep 0.1 && swaync-client -t -sw",
      "return-type": "json",
      "tooltip": false
    },
```

Before update:
![1726335141_grim](https://github.com/user-attachments/assets/acb82dbb-5c68-4d73-89de-1820456d1932)

After update:
![1726335049_grim](https://github.com/user-attachments/assets/8ccde55d-efb2-482b-8026-91e61f56f8b5)

**Comment by PaoloReyes** [comment]
They said updating to waybar 0.11.0 should solve it. But others say it does not. For me downgrading fmt made the trick

**Comment by DHDcc** [comment]
Updating waybar to 0.11.0 does't work and downgrading it to 0.10.3 gave me this error: ```waybar: error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory```

**Comment by PaoloReyes** [comment]
Downgrade fmt package

**Comment by PaoloReyes** [comment]
I think it will give another error with sdplog package, downgrade it and then should run flowlessly

**Comment by DHDcc** [comment]
Yeah, it's working. I hope they fix this soon.

**Comment by NeobinX** [comment]
- Arch/Garuda Linux
- Hyprland
- Waybar 0.11.0-3 from `extra`
- fmt 11.0.2-1 from `extra`

Getting the same error:
`[error] custom/updates: cannot switch from manual to automatic argument indexing`

`custom/updates`:
```
    "custom/updates": {
        "format": "{icon} {}",
        "return-type": "json",
        "format-icons": {
            "has-updates": "󱍷",
            "updated": "󰂪",
            "interval": 3600
        },
        "exec-if": "which waybar-module-pacman-updates",
        "exec": "waybar-module-pacman-updates",
        "on-click": "foot -e update"
    },
```

`waybar-module-pacman-updates` output:
`{"text":"0","tooltip":"System updated","class": "updated","alt":"updated"}`

Don't know, if the (source of the) error is already obvious; but providing my observations, in case it helps in some way:
- Only `"format": "{icon} {}"` gives the error and does not display anything.
- `"format": "{icon}"` gives no error and displays the icon.
- `"format": "{}"` gives no error and displays the numerical update count (`0`).

Thank you in advance.

**Comment by SWarrener** [comment]
> * Arch/Garuda Linux
> 
>     * Hyprland
> 
>     * Waybar 0.11.0-3 from `extra`
> 
>     * fmt 11.0.2-1 from `extra`
> 
> 
> Getting the same error: `[error] custom/updates: cannot switch from manual to automatic argument indexing`
> 
> `custom/updates`:
> 
> ```
>     "custom/updates": {
>         "format": "{icon} {}",
>         "return-type": "json",
>         "format-icons": {
>             "has-updates": "󱍷",
>             "updated": "󰂪",
>             "interval": 3600
>         },
>         "exec-if": "which waybar-module-pacman-updates",
>         "exec": "waybar-module-pacman-updates",
>         "on-click": "foot -e update"
>     },
> ```
> 
> `waybar-module-pacman-updates` output: `{"text":"0","tooltip":"System updated","class": "updated","alt":"updated"}`
> 
> Don't know, if the (source of the) error is already obvious; but providing my observations, in case it helps in some way:
> 
>     * Only `"format": "{icon} {}"` gives the error and does not display anything.
> 
>     * `"format": "{icon}"` gives no error and displays the icon.
> 
>     * `"format": "{}"` gives no error and displays the numerical update count (`0`).
> 
> 
> Thank you in advance.

I am using the same custom module as this, but noticed that while `"format": "{icon} {}"` does not work and gives an error, `"format": "{} {icon}"` works as expected. This is all on 0.11.0-3

**Comment by DHDcc** [comment]
> > * Arch/Garuda Linux
> >   
> >   * Hyprland
> >   * Waybar 0.11.0-3 from `extra`
> >   * fmt 11.0.2-1 from `extra`
> > 
> > Getting the same error: `[error] custom/updates: cannot switch from manual to automatic argument indexing`
> > `custom/updates`:
> > ```
> >     "custom/updates": {
> >         "format": "{icon} {}",
> >         "return-type": "json",
> >         "format-icons": {
> >             "has-updates": "󱍷",
> >             "updated": "󰂪",
> >             "interval": 3600
> >         },
> >         "exec-if": "which waybar-module-pacman-updates",
> >         "exec": "waybar-module-pacman-updates",
> >         "on-click": "foot -e update"
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `waybar-module-pacman-updates` output: `{"text":"0","tooltip":"System updated","class": "updated","alt":"updated"}`
> > Don't know, if the (source of the) error is already obvious; but providing my observations, in case it helps in some way:
> > ```
> > * Only `"format": "{icon} {}"` gives the error and does not display anything.
> > 
> > * `"format": "{icon}"` gives no error and displays the icon.
> > 
> > * `"format": "{}"` gives no error and displays the numerical update count (`0`).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you in advance.
> 
> I am using the same custom module as this, but noticed that while `"format": "{icon} {}"` does not work and gives an error, `"format": "{} {icon}"` works as expected. This is all on 0.11.0-3

Yeah, I'm seeing the same result on my end.

**Comment by winter-again** [comment]
Having same problem. Like the error says, sounds like it's an issue of using `{icon}` (manual) before `{}` (automatic) in the format field.

**Comment by lukasfink1** [comment]
It seems that fmt doesn’t accept mixing manual (`{icon}` or `{0}`) and automatic field indexing (`{}`) anymore.

The problem can be worked around by replacing `{}` in your format string with `{0}`.

Example:

```
      "format": "{icon} {}",
```

has to be replaced with:

```
      "format": "{icon} {0}",
```

**Comment by ConfusedSky** [comment]
> It seems that fmt doesn’t accept mixing manual (`{icon}` or `{0}`) and automatic field indexing (`{}`) anymore.
> 
> The problem can be worked around by replacing `{}` in your format string with `{0}`.
> 
> Example:
> 
> ```
>       "format": "{icon} {}",
> ```
> 
> has to be replaced with:
> 
> ```
>       "format": "{icon} {0}",
> ```

Thank you! This worked for me. I appreciate it. Also thank you for opening #3617 should help people avoid this in the future.
