### ISSUE TITLE
Temperature icon is sometimes cut off

### ISSUE THREAD

**Issue by pedrocr** [Alexays/Waybar#361]
Depending on the values being displayed the temperature icon is being cut off in the bar. Here's the display when everything is correct:

![normal](https://user-images.githubusercontent.com/246322/58749001-17198080-8478-11e9-8840-719a6f1eb004.png)

And here's when the icon is cutoff:

![bug](https://user-images.githubusercontent.com/246322/58749006-1ed92500-8478-11e9-99ba-75bbf564fa33.png)

Here's my style and config files:

[config](https://github.com/Alexays/Waybar/files/3243788/config.txt)
[style.css](https://github.com/Alexays/Waybar/files/3243789/style.css.txt)

**Comment by Ventto** [comment]
Have you tried to replace the temp icon with plain text to see if it is cut off as well ?

**Comment by Alexays** [comment]
Seems a dup of #363
