### ISSUE TITLE
tray icons not showing on upgrade to 0.11.0

### ISSUE THREAD

**Issue by adamthiede** [Alexays/Waybar#3616]
OS: alpine linux edge
WM: sway

On previous versions I got tray icons, now I get no tray icons and the following is logged to stdout when I try to launch an application, (example `nm-applet --indicator`):

```
[2024-09-16 06:07:27.303] [error] Failed to create DBus Proxy for :1.78 /org/ayatana/NotificationItem/nm_applet: std::bad_cast
```

I've confirmed that running the default bar (with i3blocks as status_command) shows tray icons. I've also confirmed downgrading waybar to 0.10.4 does display a tray.

Any more info I can supply?

**Comment by izmyname** [comment]
https://github.com/Alexays/Waybar/commit/0d02f6877d88551ea2be0cd151c1e6354e208b1c 

Your distro packagers need to update waybar package.

**Comment by adamthiede** [comment]
Thanks, I can add the patch to the package.

My apologies for opening a redundant issue; I thought I had searched correctly. Duplicate of https://github.com/Alexays/Waybar/issues/3597.

**Comment by cpiber** [comment]
> Your distro packagers need to update waybar package.

There's not even a new release...

**Comment by brosasaki** [comment]
seconding cpiber, there needs to be a 0.11.1 release. Non-"bleeding edge" distros exist

**Comment by adamthiede** [comment]
It's common practice for packagers to apply patches; see arch linux's solution here: https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/commit/6a5bf9f04eb4024ecdaddcb1c9737599f76934ee
