### ISSUE TITLE
[BUG] Custom modules containing only static text fail to render

### ISSUE THREAD

**Issue by matt-della** [Alexays/Waybar#362]
The latest package update on Arch Linux (Waybar v0.6.7 - Installed 2019-06-01) seems to have broken this feature. The bug affects any module without an "exec" field that produces a detectable output. For example, see the following three modules:

```
    "custom/test1": {
        "format": "test1"
    },
    "custom/test2": {
        "format": "{}",
	"exec": "echo test2",
	"interval": "once"
    },
    "custom/test3": {
       "format": "{}test3",
	"exec": "echo",
	"interval": "once"
    }
```

**Test1**, which is what I've been using for static bar elements (powerline arrows, for example), now fails to render. **Test2** renders as expected. As an experiment, I created **Test3** with a no-op command (`echo` without any arguments, in this case) to see how that impacted things. Since this command produces no output, it appears that Waybar simply ignores it and fails to render the module.

**Comment by Alexays** [comment]
Fixed with 9dbf057f58e4d5aa2ae7f1725e6d6f3af89dc744
