### ISSUE TITLE
Group click-to-reveal doesn't work?

### ISSUE THREAD

**Issue by JeesusKrisostoomus** [Alexays/Waybar#3625]
Maybe i don't understand how it works, but i think that when you make a group and put click-to-reveal there it just doesn't work. Still opens on hover.

https://github.com/Alexays/Waybar/wiki/Module:-Group according to the wiki this functionality should exist.

My current group snippet:
```
"group/hby1": {
        "orientation": "inherit",
        "click-to-reveal": true,
        "drawer": {
            "transition-duration": 500,
            "children-class": "hby1",
            "transition-left-to-right": true
        },
        "modules": [
            ...
        ]
    },
```
Waybar version: v0.11.0 (v0.10.4 had the same problem)
OS: Arch
DE: KDE Plasma 6.1.5

EDIT:
Also tried it without drawer part and it still was so

**Comment by RobertMueller2** [comment]
"click-to-reveal" is an option for drawer, I don't think it works as an option for group.

**Comment by RobertMueller2** [comment]
You're right though, it's not in the correct place in the wiki.

**Comment by JeesusKrisostoomus** [comment]
> You're right though, it's not in the correct place in the wiki. EDIT: fixed in the wiki.

Thank you <3
