### ISSUE TITLE
module `hyprland/workspaces` only shows one workspace

### ISSUE THREAD

**Issue by Gigas002** [Alexays/Waybar#3627]
hyprland version `0.43`
waybar version `0.11.0`

**Comment by Gigas002** [comment]
Hmm, working after reboot, dunno why. Closing for now

**Comment by Gigas002** [comment]
It still happens sometimes, but I don't understand how to repo, almost randomly. Will reopen issue if understand what's going on

**Comment by jetm** [comment]
Yes, me too. Still looking at how to reproduce it because it doesn't always happen.
