### ISSUE TITLE
Using FontAwesome OTFs results in a bunch of missing icons in the default config

### ISSUE THREAD

**Issue by pedrocr** [Alexays/Waybar#363]
I've tried waybar with both the Font Awesome packaged under Ubuntu/Debian (confusingly called 5.0.10+really4.7.0) as well as 5.8.2 downloaded from the website as well as current git master from here:

https://github.com/FortAwesome/Font-Awesome/tree/master/otfs

All of them result in missing icons replaced by weird accented letters. Here's an example of how the config file renders with FontAwesome as downloaded from the website (version 5.8.2):

![missingicons](https://user-images.githubusercontent.com/246322/58762053-4ba63e80-8543-11e9-9d9d-2138afcc3e04.png)

**Comment by ethanmad** [comment]
Thanks for posting your solution. Putting the FontAwesome font at the end works better for me, though; when it's at the front, all text is displayed using FontAwesome.

**Comment by georgkrause** [comment]
Got this, too. Is there another solution?

**Comment by aqxa1** [comment]
I don't know if this applies to all distributions, but you can also add this change in /etc/xdg/waybar/style.css (saving the need to modify the source).

**Comment by niobium93** [comment]
```
font-family: Roboto, Helvetica, Arial, sans-serif, "Font Awesome 5 Free";
```
didn't work for me, I had to do:
```
font-family: Roboto, "Font Awesome 5 Free";
```
