### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by mitchelljkotler** [Alexays/Waybar#3636]
I had waybar setup and working fine.  Today I woke my laptop up, and the bar was missing.  I ran `waybar` from the command line and find it now seg faults:

```
> waybar
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
[1]    3825892 segmentation fault (core dumped)  waybar
```
I hadn't changed anything.  I tried upgrading waybar and installing from source, but still get the same issue.

```
> waybar --version
Waybar v0.11.0-35-g07f75e30 (branch 'master')
```

I am on Ubuntu 22.04

**Comment by mitchelljkotler** [comment]
I have the language module commented out in the config.  Is there anything else I can do to disable it and allow waybar to start?  I will try to figure out what is wrong with my xkbcommon as well.  Thanks.

**Comment by LukashonakV** [comment]
As I see:

1. sway/language
2. hyprland/language
3. niri/language 

Only these modules use the library. Check any of them and disable temporary.
+ I guess you need to reinstall 

1. libxkbcommon-dev
2. libxkbregistry-dev

Both actual for Debian repository and should be the same for Ubuntu

**Comment by LukashonakV** [comment]
And I missed... you wrote,  you woke up your laptop.. Means wayabr crashes the only after sleeping.. on even on system startup?

**Comment by LukashonakV** [comment]
Hi @mitchelljkotler if issue is no more actual,  please close it
