### ISSUE TITLE
Build Failure Nix Flake

### ISSUE THREAD

**Issue by techyporcupine** [Alexays/Waybar#3639]
Hello! I recently updated the Waybar input in my flake and it fails to build with
```
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/ga7wi6s76i1gl0dwmwy82wcqyc3kqa4f-source
       > source root is source
       > /build/source /build
       > patching script interpreter paths in .
       > /build
       > Running phase: patchPhase
       > applying patch /nix/store/4dh7h9pnzxfa0l74116cz0x3ssnkpac7-fix-tray
       > patching file src/modules/sni/item.cpp
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 5 out of 5 hunks ignored -- saving rejects to file src/modules/sni/item.cpp.rej
       > patching file subprojects/fmt.wrap
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 1 out of 1 hunk ignored -- saving rejects to file subprojects/fmt.wrap.rej
```

Let me know if any more info is needed!

**Comment by mslxl** [comment]
I met the same problem. 

But it is so strange that I can run waybar by `nix run github:Alexays/Waybar#waybar`. And here is no patch operation in this repo(I didn't find it). 

There is a patch operations related to waybar in nixpkgs: https://github.com/NixOS/nixpkgs/blob/5aaceeaf016fe2187f3fc6bda0520b8b468a1c3e/pkgs/by-name/wa/waybar/package.nix#L94-L104, but I did not use it. I run waybar by adding line `exec-once = ${waybar.packages.${system}.waybar}/bin/waybar` in hyprland config. Then I do not know how to solve it next.

Hope these info would help others.

**Comment by mslxl** [comment]
Wait, it use overrideAttrs?

https://github.com/Alexays/Waybar/blob/07f75e303c4d6de8198e30239a808bfbc0d80ea5/nix/default.nix#L15-L19

Maybe we should change it.
