### ISSUE TITLE
It would be nice to be able to disable the overlays

### ISSUE THREAD

**Issue by pedrocr** [Alexays/Waybar#365]
I don't really like the overlays but haven't found a way to disable them. Is there one? Would you take a patch to do that?

**Comment by Alexays** [comment]
Do you mean tooltip?

**Comment by pedrocr** [comment]
Probably. I mean the text that shows up in the middle of the screen when you hover over the date for example.

**Comment by Alexays** [comment]
You can disable it by adding to each modules config, `"disable-tooltip": true`

**Comment by pedrocr** [comment]
Thanks. For future reference it's actually `"tooltip": false`
