### ISSUE TITLE
The clock in the waybar has gone wrong

### ISSUE THREAD

**Issue by Dmitryi** [Alexays/Waybar#3655]
The clock in the waybar has gone off by three hours and is now behind the time in my time zone. In tmux, the time shows exactly how it should be. If you switch to KDE, the time also shows how it should be. The clock went wrong only in the way bar.
config clock in waybar
```    
"clock": {
        "timezone": "Europe/Moscow",
        "interval": 1,
        "format": " {:%a %H:%M %d.%m.%Y}",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": "{:%Y-%m-%d}"
    }
```

**Comment by bobblkabb** [comment]
The same here, on all 3 computers.
"timezone": "Europe/Berlin"

**Comment by steevelefort** [comment]
Hello,
Same thing here. The clock widget seems to ignore the timezone ("Europe/Paris" for me).
The 'date' command print the right time on my terminal.

**Comment by rousty88** [comment]
Yes I have the same issue. Waybar just showing/defaulting to UTC time instead of CEST. In my settings I have `timezone` set to `Europe/Berlin` but it does nothing.

When I run `timedatectl` in terminal it shows the correct local time. Just a Waybar specific issue.

**Comment by Sim23F** [comment]
I have the same issue 

when running `timedatectl`:
```
$ timedatectl 
               Local time: Thu 2024-10-10 12:45:17 CEST
           Universal time: Thu 2024-10-10 10:45:17 UTC
                 RTC time: Thu 2024-10-10 10:45:17
                Time zone: Europe/Rome (CEST, +0200)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
```

when running `waybar` from the terminal, i get this warning:
`[2024-10-10 12:46:26.984] [warning] Timezone: Europe/Rome. std::chrono::tzdb: cannot locate zone: Europe/Rome`

when running [this c++ program to list timezones](https://wandbox.org/permlink/gwAXlc3DPAnW3bLW) i get this output:
```
All available time zones:
Etc/GMT
Etc/UTC

All time zone links:
Etc/GMT+0
Etc/GMT-0
Etc/GMT0
Etc/Greenwich
Etc/UCT
Etc/Universal
Etc/Zulu
GMT
GMT+0
GMT-0
GMT0
Greenwich
UCT
UTC
Universal
Zulu

My time zone:
Etc/UTC
```

the problem seems to be in the chrono library which is having trouble identifying most time zones

**Comment by WhyNotHugo** [comment]
Also seeing this on Alpine Linux, since about 2 weeks ago. Adding an explicit timezone to the config fixes things for me:

    "timezone": "America/Argentina/Buenos_Aires",

The annoyance is having to keep this in sync with the system timezone manually.

**Comment by pitchispleb** [comment]
`"timezone": "Europe/Berlin",`
does nothing for me. i replaced it with the posted line from @WhyNotHugo but still nothing changes. time is still shown as UTC, although system is on CEST

```
Information for package waybar:
-------------------------------
Repository     : Main Repository (OSS)
Name           : waybar
Version        : 0.11.0-2.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 1.9 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : waybar-0.11.0-2.1.src
Upstream URL   : https://github.com/Alexays/Waybar
```

**Comment by WhyNotHugo** [comment]
There seem to be two different causes for this issue, and my suggestion only works in one of those situations.

**Comment by Sim23F** [comment]
Since many of us are in European timezones, could it be that we're all using the same distro, openSUSE? 
That would suggest an issue with the opensuse packages

**Comment by Dmitryi** [comment]
> Since many of us are in European timezones, could it be that we're all using the same distro, openSUSE? That would suggest an issue with the opensuse packages

OpenSUSE Tumbleweed

**Comment by Sim23F** [comment]
I tested that both the waybar's clock and the chrono library works as intended in a snapshot where libstdc++ was one version behind.
Unfortunately that version is no longer in the repos

**Comment by WhyNotHugo** [comment]
Alpine Linux here.

**Comment by Sim23F** [comment]
It seems that the newly released update to the C++ library has solved the issue.

**Comment by rousty88** [comment]
Yes, the issue is fixed for me after running a system update this morning.

**Comment by Dmitryi** [comment]
After today's update, the clock began to show an adequate time.

**Comment by WhyNotHugo** [comment]
What do you mean by "today's update"? There hasn't been a release in 30 days, and no commits in `master` in the last two weeks.

**Comment by WhyNotHugo** [comment]
If a distro a patching this issue, can you link to the patch, or leave the issue open until this is fixed upstream?

**Comment by Sim23F** [comment]
You on Alpine seems to have a different issue than the one we were having on Opensuse Tumbleweed.
Our issue was not caused by the `waybar` package but rather by the incompatibility between the previous version of the c++ std library and the latest version of `timezone` (wich may have a different name on Alpine)
