### ISSUE TITLE
CSS properties not working?!?

### ISSUE THREAD

**Issue by shaymanorigins** [Alexays/Waybar#3656]
When i try to edit my css, adding clip-path, display, transform and some other variables, my waybar closes and it tells me its an invalid property

**Comment by Blubberland** [comment]
First line in [this section of the documentation](https://github.com/Alexays/Waybar/wiki/Styling#interactive-styling) says:

> GTK is used to apply styles and works with [a limited subset of CSS](https://docs.gtk.org/gtk3/css-properties.html).
