### ISSUE TITLE
Support CSS text-align

### ISSUE THREAD

**Issue by pedrocr** [Alexays/Waybar#366]
For things like sway/window it would be nice to have CSS support for `text-align` to be able to adjust how the text is displayed in the bar.

**Comment by Alexays** [comment]
Atm text-align is not supported on gtk label, we need to wait a gtk update

**Comment by pedrocr** [comment]
Seems like gtk does that with something other than CSS:

https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-justify

So maybe adding `text-align` is not in the plans.

**Comment by Alexays** [comment]
But for your case, why not simply move module to the left/right block?

**Comment by pedrocr** [comment]
The module is in the left block. But the actual text of the window title is centered and I wanted to make it left aligned. It's not too bad this way either, just a tweak to see if it felt better.

**Comment by Alexays** [comment]
Can you share me a screenshot?
Window title module width must not be larger than the text size

**Comment by pedrocr** [comment]
Sure, here it is:

![waybar](https://user-images.githubusercontent.com/246322/59287125-f2d45580-8c68-11e9-8ddc-127ad3d6fe1c.png)

Config is:

```
    "modules-left": ["sway/workspaces", "sway/window"],
    "modules-center": [],
    "modules-right": ["cpu", "memory", "temperature", "pulseaudio", "backlight", "network", "battery", "tray", 
```

I can add some CSS coloring on `sway/window` if that helps diagnose it.

**Comment by Alexays** [comment]
Fixed with 3c9b533997ae21ebdd09dd40c7612616fbf0beb5

**Comment by pedrocr** [comment]
Thanks. Just tested it. Now it's left aligned when put in `modules-left` and centered in the total bar when in `modules-center`, so seems to be working as intended. The previous behavior was actually not horrible though. It centered the window title in the space between left and right modules.

**Comment by krnl0138** [comment]
@pedrocr @Alexays Really sorry, but is it possible to get back to the previous state with centered and filled module between two others? Or to toggle between those options?

**Comment by MyNameIsCosmo** [comment]
Would using [GtkJustification](https://developer.gnome.org/gtk3/stable/gtk3-Standard-Enumerations.html#GtkJustification) to get `text-align: [left,center,right]` be a course of action?

I'd be happy to start a PR implementing this if it would be accepted.

**Comment by Alexays** [comment]
@MyNameIsCosmo You can implement a justification for Label modules. it'll be a great improvement :)

**Comment by MatthiasGrandl** [comment]
So is there anything like this implemented? On a vertical bar, this would be very handy, as thing will look very messy if everything is left aligned.

**Comment by flipflop133** [comment]
Is there any progress on this? Doesn't GTK 4 fix the problem?
As you can see on the screenshot below, not having an `align-center` property makes things look quite ugly in this particular situation, isn't there any temporary workaround?
![image](https://user-images.githubusercontent.com/48946818/107794181-67716880-6d57-11eb-971d-0d39ba9bc6fb.png)

**Comment by Cornelius-Figgle** [comment]
![image](https://github.com/Alexays/Waybar/assets/110970234/3345a0ba-508a-472b-a7d2-183a4667c172)

same problem as @flipflop133, need to be able to center the text in the network module (specifically the signal strength, but ideally the whole module so it also applies to the Ethernet versions of this)

Any updates on how to do this?

**Comment by Runeword** [comment]
![20230617_17h14m17s_grim](https://github.com/Alexays/Waybar/assets/60324746/652c577b-e81f-43d4-9d31-8b43d48ca298)
Same problem with any module.

**Comment by John-Dennehy** [comment]
Same alignment issue as others when using a vertical bar.  

On a separate but related topic; is there somewhere I can find which css attributes do/not work? As far as I can see there is no mention of this in the styling wiki, so have lost days trying to get css working as expected (web dev by trade, but novice with linux).

**Comment by flipflop133** [comment]
> Same alignment issue as others when using a vertical bar.
> 
> On a separate but related topic; is there somewhere I can find which css attributes do/not work? As far as I can see there is no mention of this in the styling wiki, so have lost days trying to get css working as expected (web dev by trade, but novice with linux).

afaik, waybar is using gtk 3 css, so you can look [here](https://docs.gtk.org/gtk3/css-overview.html).

**Comment by shasherazi** [comment]
Is there any progress on this? Maybe reopen the issue if no solution has been found

**Comment by banana-peeled** [comment]
For anyone having the same problem: add `"justify": "center"` (or left/right) to the module in the config file.

**Comment by zen2** [comment]
> For anyone having the same problem: add `"justify": "center"` (or left/right) to the module in the config file.

That doesn't align several lines:
![Image](https://github.com/user-attachments/assets/b0525035-5429-4c13-9cac-d260ad3b72ce)
I suppose it is because of justification.

**Comment by John-Paul-R** [comment]
In case anyone is having trouble centering font-icons vertically, I found that using a proportional font, as suggested in [this YT video](https://www.youtube.com/watch?v=JfTT8sbtX7M) made my problems disappear.

**Comment by rvsfirecreeper** [comment]
@banana-peeled This doesn't work for all modules seemingly

**Comment by sillianlillian** [comment]
> For anyone having the same problem: add `"justify": "center"` (or left/right) to the module in the config file.

my clock was looking goofy as hell and this saved it lol thank you so much
