### ISSUE TITLE
enable-bar-scroll: true option broken

### ISSUE THREAD

**Issue by cinocode** [Alexays/Waybar#367]
I just tried to add "enable-bar-scroll": true to my config and it seems to be broken. When I scroll (doesn't matter if on the bar or on the workspace switcher) the target workspace flickers for a split second and then the currently active workspace is focussed again.
With this option removed I con scroll on the workspace switcher without any issues.

Here's the relevant part of my waybar config:
    "sway/workspaces": {
        "format": "{name}",
        "disable-scroll-wraparound": true,
        "enable-bar-scroll": true
    },
[Or my entire waybar config - enable bar scroll is not in there](https://github.com/cinocode/dotfiles/tree/master/.config/waybar)

I'm on:
5.1.6-arch1-1-ARCH
sway 1.1.1-1
waybar 0.6.7-1

Thanks for the great work on this project!

**Comment by junglerobba** [comment]
This happens if workspace_auto_back_and_forth is enabled in sway (which it is from looking at your dotfiles). I had the same issue until I disabled that, and can get it again just by turning it back on.

**Comment by nenad** [comment]
Okay, I believe I figured a fix for this without disabling `workspace_auto_back_and_forth` in sway. The fix is to compile waybar (or get it from the `waybar-git` AUR package), and edit the `"smooth-scrolling-threshold"` property of the `sway/workspaces` module to a high value, or at least a value that will suit your needs.

**Comment by cinocode** [comment]
Hi, thanks for the fix. I tested with the waybar-git aur package and your config. Works great.

Just FYI since I look at the PR - my issue was just with mouse scrolling (not touchpad). But the problem is reintroduced, if I delete the smooth-scrolling line from my config.
Maybe it makes sense to have a default value for the scrolling - so other people don't come accross the same issue as me?
Aside from that we could close this since it works for me now.

**Comment by Synthetica9** [comment]
> Maybe it makes sense to have a default value for the scrolling - so other people don't come accross the same issue as me?

I didn't add this to preserve the old behaviour when the config file was unchanged ([xkcd 1172](https://xkcd.com/1172/) springs to mind), but the following would fix that:

```patch
diff --git a/src/AModule.cpp b/src/AModule.cpp
index 38e9785..6b5beb5 100644
--- a/src/AModule.cpp
+++ b/src/AModule.cpp
@@ -64,7 +64,7 @@ AModule::SCROLL_DIR AModule::getScrollDir(GdkEventScroll* e) {
       distance_scrolled_y_ += e->delta_y;
       distance_scrolled_x_ += e->delta_x;
 
-      gdouble threshold = 0;
+      gdouble threshold = 1;
       if (config_["smooth-scrolling-threshold"].isNumeric()) {
         threshold = config_["smooth-scrolling-threshold"].asDouble();
       }
```

**Comment by WhyNotHugo** [comment]
@Synthetica9 So, this won't be fixed and users would have to compile from source for `enable-bar-scroll` to work?

**Comment by Synthetica9** [comment]
@WhyNotHugo The default won't be changed (I think, but I'm not the repo owner, @Alexays is). You can still change this behaviour with `"smooth_scrolling_threshold"` in your config.

**Comment by Alexays** [comment]
@WhyNotHugo as @Synthetica9 said, there is no need to compile from source, just use the `"smooth_scrolling_threshold"` option.

**Comment by WhyNotHugo** [comment]
I've set `smooth-scrolling-threshold` to `1`, but I still get the original symptoms: the target workspace flickers for a split second and then the currently active workspace is focussed again.

It's unclear to me what `smooth-scrolling-threshold` is or why it's needed here. To what value do I need to set it for waybar to unbreak with `enable-bar-scroll`?  Maybe this can be documented?

Or even better still, how about just setting `smooth-scrolling-threshold` to the right value when `enable-bar-scroll` is set? I can't see anyone actively relying on this flicker-and-no-change behaviour.

**Comment by WhyNotHugo** [comment]
Looks like 0.9.5 fixed this bug and `enable-bar-scroll` now works properly by itself.

It is no longer necessary to have `smooth-scrolling-threshold: 4.0` for this feature to work -- actually, the workaround now breaks scrolling, and one has to scroll four times to switch a single workspace.

**Comment by Synthetica9** [comment]
Hmm, now scrolling to switch workspaces seems to be broken on smooth scrolling devices now... I'll see if I can bisect the exact commit that broke it
