### ISSUE TITLE
Second Waybar on Hyprland doesn't show up

### ISSUE THREAD

**Issue by Piuvelocedellamerda** [Alexays/Waybar#3678]
Hey there, pretty new to Linux, configuring stuff etc

I just installed Waybar and started configuring it starting from the "Minimal Configuration" in the Wiki. I found out that it's possible to setup a second bar inside the same config file by just using `position`. It's not working for me right now. I also found in some older issues that you can do it manually but it's a bit complicated for me that i just started out :(

Config:
```
{
	"name": "topbar",
	"position": "top",
	"layer": "top",
	"modules-left": ["hyprland/workspaces", "hyprland/mode"],
	"modules-center": ["hyprland/window"],
	"modules-right": ["battery", "block"],
	"hyprland/window": {
		"max-length": 50

},
	"battery": {
		"format": "{capacity}%",
	},
	"clock": {
		"format-alt": "{:%a, %d. %b %H:%M}"
	
	}

}

{
	"name": "bottombbar",
	"mode": "dock",
	"position": "bottom",
	"layer": "top",
	"height": 30,
}
```

Thank you in advance, let me know if you guys need something else to understand better the problem :)

**Comment by Piuvelocedellamerda** [comment]
Ok, for others with the same problem, I was wrong; it's pretty easy to do it manually. Create a new config file in `~/.config/waybar/`. This is the specific config file for your second status bar. After that, open your Hyprland config file, usually located in` ~/.config/hypr/hyprland.conf`. Now you can set up a new process for the second status bar with `exec-once waybar -c`. After the `-c`, type the location of the file. Now your second Waybar process will load when you start Hyprland. Also, if someone knows why I can't do it with a single config file, just let me know :)

**Comment by marcorampin** [comment]
Hi,
you were missing a comma at the closing bracket of the top bar, it should work now (I already added it on the quoted code, so you can just copy the code below)

> Hey there, pretty new to Linux, configuring stuff etc
> 
> I just installed Waybar and started configuring it starting from the "Minimal Configuration" in the Wiki. I found out that it's possible to setup a second bar inside the same config file by just using `position`. It's not working for me right now. I also found in some older issues that you can do it manually but it's a bit complicated for me that i just started out :(
> 
> Config:
> 
> ```
> {
> 	"name": "topbar",
> 	"position": "top",
> 	"layer": "top",
> 	"modules-left": ["hyprland/workspaces", "hyprland/mode"],
> 	"modules-center": ["hyprland/window"],
> 	"modules-right": ["battery", "block"],
> 	"hyprland/window": {
> 		"max-length": 50
>     	},
> 	"battery": {
> 		"format": "{capacity}%",
> 	},
> 	"clock": {
> 		"format-alt": "{:%a, %d. %b %H:%M}"
> 	}
> },
>
> {
> 	"name": "bottombbar",
> 	"mode": "dock",
> 	"position": "bottom",
> 	"layer": "top",
> 	"height": 30,
> }
> ```
> 
> Thank you in advance, let me know if you guys need something else to understand better the problem :)

**Comment by Piuvelocedellamerda** [comment]
Hey there, I tried to add the comma at the end of the 1st bar section but nothing really happened

**Comment by marcorampin** [comment]
Maybe the square brackets containing all the config are missing?
e.g. 
```
[
	{
		"name": "topbar",
		"position": "top",
		...
	},
	{
		"name": "bottombar",
		"position": "bottom",
		...
	}
]
```
