### ISSUE TITLE
border radius options?

### ISSUE THREAD

**Issue by Set2Minecraft** [Alexays/Waybar#3687]
Is there a way to control individual border radius corners or sides in style.css?

something like: border-radius-right: 0px

including top, bottom, left and the corners?
Am I missing something obvious?

**Comment by marcorampin** [comment]
You can either specify `border-top-left-radius: 0px` or write the four different values (from top-left in clockwise direction) `border-radius: 0px 5px 10px 15px`.

For more options (you can also test it directly):
https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

**Comment by Set2Minecraft** [comment]
Ah, Thanks!
