### ISSUE TITLE
reload_style_on_change value errors out.

### ISSUE THREAD

**Issue by Alucard8181** [Alexays/Waybar#3688]
When adding this line to the config file:
"reload_style_on_change": "true",
Waybar errors out:
[error] Value is not convertible to bool.

**Comment by marcorampin** [comment]
Write the value without quotation marks (`"reload_style_on_change": true,`)

**Comment by Alucard8181** [comment]
Dam! Heaving hard time with the syntax.. Thanks for the help.
Trying to utilize the provided help as much as possible...
