### ISSUE TITLE
How to call system environment variables in the `waybar` configuration file?

### ISSUE THREAD

**Issue by pengshp** [Alexays/Waybar#3699]
My `MPD` is started using the `socket` method, it is listenning `${XDG_RUNTIME_DIR}/mpd/socket`
In the `server` field of the `mpd` module, I want to use the system environment variable`$XDG_RUNTIME_DIR`, how to write the configuration item?

```bash
systemctl --user status mpd.socket
● mpd.socket
     Loaded: loaded (/usr/lib/systemd/user/mpd.socket; enabled; preset: enabled)
     Active: active (listening) since Sat 2024-10-19 05:36:00 CST; 17s ago
 Invocation: 1bda14c942b7457c9d9948fc25830b1a
   Triggers: ● mpd.service
     Listen: /run/user/1003/mpd/socket (Stream)
```
`$XDG_RUNTIME_DIR` = `/run/user/1003`

```jsonc
"mpd": {
        "server": "??????",
}
```

**Comment by JanValiska** [comment]
Expanding of environment variables inside "mpd/server" is not implemented. The server property is plain string read from config file.

Workaround could be to unset "server" key. Do not write it to the config file at all. In that case the NULL pointer will be passed to `mpd_connection_new()` call and client library will use `$MPD_HOST` as host to connect to.  Don't forget set global environment variable `$MPD_HOST` in your `.profile` or another file that is sourced during login to. Something like:

`export MPD_HOST="$XDG_RUNTIME_DIR/mpd/socket"` 

Shell is good for variable expansions :)

**Comment by pengshp** [comment]
Thank you for your answer, it works!
