### ISSUE TITLE
Crash when started under Wayfire

### ISSUE THREAD

**Issue by notramo** [Alexays/Waybar#37]
**os:** Arch Linux
**version:** r118.0dba3abc-2 (Arch package version - can't get version with `--version` flag either under X, or Wayfire)
**output:**
```
 ~ >>> waybar
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Exception: waybar killed by signal aborted (core dumped)
[tty], line 1: waybar
 ~ >>> 
```
It works fine on the same system when started under `sway`.

**Comment by Alexays** [comment]
Fixed on d0933ab50fd9a5638170ce0cd67e7e33c860831e
