### ISSUE TITLE
Adding multiple lines to a tooltip.

### ISSUE THREAD

**Issue by ItsFireStorm** [Alexays/Waybar#3701]
This is my first time using waybar, and so far, my first configuration is going smoothly, however, I have one issue, I'm trying to fill the wifi module tooltip with as much information as possible (signal strength, ssid, IP address, etc.), the problem is that placing it all in one line makes it awkward to look at, and at some points, unreadable. 

I tried to place them all together using this (formatted like this for easier readability, it's all joined together in the config file):
```
"tooltip-format-wifi": ["{essid} ({signalStrength}% signal strength)", 
                       "{ipaddr}/{cidr} via {gwaddr}", 
                       "{bandwidthUpBits} {bandwithDownBits}"
                       ],
```

Hoping this would do the trick, but it prints out the default tooltip.
Given this is my first time and I do not know most stuff, try to go easy on me?

Thanks in advance.

Update:
Someone I know suggested to use `<br>`, I've tried, and this unfortunately doesn't work.
```
"tooltip-format-wifi": "{essid} ({signalStrength}% signal strength) <br> 
                        {ipaddr}/{cidr} via {gwaddr} <br>
                        {bandwidthUpBits} {bandwithDownBits}",
```

**Comment by manfred3000** [comment]
Opening an issue for questions like this is a bit over the top - but FWIW you've simply got to add newlines `\n`

**Comment by ItsFireStorm** [comment]
> Opening an issue for questions like this is a bit over the top - but FWIW you've simply got to add newlines `\n`

Thanks for the guidance, I'll be sure to post issues like this in Discussions next time.
