### ISSUE TITLE
Sway workspaces module visual glitch

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#371]
Sometimes randomly workspaces module starts glitching. The screenshot illustrates how it looks.
![2019-06-06-230500](https://user-images.githubusercontent.com/4847726/59035089-085a1180-885c-11e9-9ad3-4b14f017cd68.png)
 The dark transparent colour is the basic colour of my bar and grey is the colour that highlights the current workspace. But when it glitches, small strips on the sides of the workspace button keep the highlight colour even after I switch to another workspace. On this screenshot I visited all open workspaces and that's what it looks like now.

**Comment by pedrocr** [comment]
Just had this happen to me as well. Colors were different because of style but effect was the same. Restarting Waybar fixed it.

**Comment by Alexays** [comment]
Fixed on master :)
