### ISSUE TITLE
Tooltip takes focus when displayed

### ISSUE THREAD

**Issue by X0rg** [Alexays/Waybar#374]
(I have see #172, but my request is a bit different)

Sometimes, when I put the mouse cursor in the web browser's search bar, I accidentally hover Waybar's icons (well, when I remove my hand from the mouse, it moves a bit).
When it happens, the tooltip is shown and takes the focus. So, text I write in the search bar go to the tooltip, so entered letters do not appear, and that closes the tooltip, and new letters appear in search bar, but the tooltip reappear and it starts again.

I do not think my description is very clear, so here is an example: I type `azertyuiop` in the search bar, but it display `etuo` due to tooltip popping.
I have some useful tooltips so that is why I do not disable them.

Do tooltips really need to take the focus?

**Comment by Useless-Pony** [comment]
Assuming you're useing sway you can add the line `no_focus [app_id="waybar"]` to your sway config, atleast untill an offical/better fix is proposed.
One problem with this is the background of the tooltip is now white, but that (probably) can be changed in waybar's style.css .. I've not figgured out the spacific for that but changeing the catchall changes it.

**Comment by X0rg** [comment]
Yes, I'm using Sway.
Oh, very nice, the `no_focus [app_id="waybar"]` did the trick. Thank you very much @Useless-Pony!

**Comment by ildar** [comment]
The possible workaround could be setting some recognizable TITLE to tooltips so that the composer can set no_focus by app_id and title.
