### ISSUE TITLE
Tray, icon/picture - incorrect colors

### ISSUE THREAD

**Issue by adjivas** [Alexays/Waybar#3789]
Hello,

I’m trying to display an icon in the tray menu. 

I tested the example code from [tray-item-rs (linux-named-resource)](https://github.com/olback/tray-item-rs/tree/master/examples/linux-named-resource) using this icon:  
![image](https://raw.githubusercontent.com/olback/tray-item-rs/refs/heads/master/examples/resources/tray_icon-green.png)

However, when displayed with Waybar, the icon appears with incorrect colors:  
![image](https://github.com/user-attachments/assets/123a841c-f7fc-4327-922c-1d068011b804)

Do you have any suggestions or information on how I can resolve this issue? 

That my Waybar version:
```shell
% waybar --version
Waybar v0.11.0
```

Thank's by advance!

**Comment by RobertMueller2** [comment]
You say, "when displayed with Waybar". Out of curiosity, what else have you tried it with? I assume this is exclusive for Waybar? In that case I'd probably first look at the CSS.

**Comment by adjivas** [comment]
Well I try without my custom CSS and it's the same bug

**Comment by RobertMueller2** [comment]
And have you tried the program elsewhere where there is a tray, like KDE, eww, ironbar, ... ?

**Comment by adjivas** [comment]
Thank's for this idea
I did the test with ironbar, and it reproduced the same behavior 
So I close this ticket
