### ISSUE TITLE
Pango markup don't seem to work with a custom module

### ISSUE THREAD

**Issue by janemba** [Alexays/Waybar#3795]
Hello,

I've made a very custom module to display text coming from a server which is `JSON` formatted.

I would like to style a part of the text using pango markup but its not working.

My config file below:
```
    "custom/news": {
        "format": "{}",
        "exec": "$HOME/.config/waybar/scripts/newsreader.py",
        "interval": 120,
        "escape": true,
        "max-length": 120,
        "return-type": "json",
        "on-click": "xdg-open $($HOME/.config/waybar/scripts/newsreader.py --url)",
        "on-click-right": "xdg-open $($HOME/.config/waybar/scripts/newsreader.py --comments)"
    }
```

Basically, `exec` field receive the following text:
```
{"text": "story :: Show HN: TeaTime – distributed book library powered by SQLite, IPFS and GitHub :: 23", "tooltip": "hackernews:\n\t<span style=\"italic\">left-click: goto news\n\tright-click: goto comments</span>"}
```

Above, I'm trying to set in italic a part of `tooltip` field. However, the `tooltip` itself display the whole string in waybar with the `span` tag.

How can I make it right ?

(I'm on wayland with hyprland)

**Comment by RobertMueller2** [comment]
Have you tried to remove `"escape": true`?

**Comment by RobertMueller2** [comment]
![satty-20241128-16:42:20](https://github.com/user-attachments/assets/2cce9702-3be1-4b8c-b222-a19819e1fd35)

I meant, did you try without the highlighted line? Because with `"escape" : true`, the custom module first processes the output through [markup_escape_text](https://docs.gtk.org/glib/func.markup_escape_text.html), so e.g. `<span>` becomes `&lt;span&gt;`.

**Comment by janemba** [comment]
Oups *remove* , sorry.

I just deleted it and now it works thank you.
