### ISSUE TITLE
[More screenshots] - Could there be a list of at the least 3 different screenshots?

### ISSUE THREAD

**Issue by rubyFeedback** [Alexays/Waybar#380]
Hello Alex,

Would it be possible to showcase a few more examples of waybar? Ideally also with the configuration used to achieve the specific layout; a bit like conky (if you know conky - https://github.com/brndnmtthws/conky it is not quite the same but there are three screenshots examples given).

Right now there is https://raw.githubusercontent.com/alexays/waybar/master/preview-2.png for Waybar - it would be nice and interesting, perhaps to some folks, if more examples could be added.

This is not a high priority request and feel free to disregard it - I just thought it may be useful to see a few more creative ways how Waybar could be used.

**Comment by Alexays** [comment]
Look at https://github.com/Alexays/Waybar/wiki/Examples
I'll add more examples :)
