### ISSUE TITLE
Fake icons grouping

### ISSUE THREAD

**Issue by janemba** [Alexays/Waybar#3803]
Hello,

I would like to "group' some icons in my waybar similar to the tray. I've made a screenshot of my waybar to explain. But basically, I would like some icons on right side to be grouped like the icons  group which contains bluetooth.

![image_2024-12-02_151803603](https://github.com/user-attachments/assets/a815d8eb-adf1-40da-9f26-31802cd1cfcc)

I guess, I need some `CSS` tweaking but I have no idea how to do that.

Thanks

**Comment by lirtle** [comment]
this can be achieved by grouping modules

https://github.com/Alexays/Waybar/wiki/Module:-Group

**Comment by janemba** [comment]
@lirtle 
It works thanks. However, how can I decrease the space between the icons. I tried with `padding` in `CSS` but it doesn't to make it.

**Comment by lirtle** [comment]
@janemba Yeah, you'll probably have to play around with the styling of the the modules inside the group as well as the styling of the group itself.

**Comment by janemba** [comment]
Sure thanks.
