### ISSUE TITLE
Pulseaudio module: automatic update at (dis)connecting bluetooth device

### ISSUE THREAD

**Issue by niktob560** [Alexays/Waybar#382]
on (dis)connecting bluetooth audio device (maybe on change of DEFAULT_SINK?) module still showing old volume info. Is that a bug?  
Waybar v0.6.6-28-gfcf2d18 (May 30 2019, branch 'master')

**Comment by zeroxfourc** [comment]
This happens when you plug in or remove a USB sound card as well. I think waybar doesn't follow DEFAULT_SINK changes properly.
