### ISSUE TITLE
Tray icon cannot be right-clicked twice

### ISSUE THREAD

**Issue by dlblv** [Alexays/Waybar#3825]
Way to reproduce:
1. Start `waybar` with `tray` module
2. Start an application, drawing a tray icon
3. Right-click on that icon -> you get an application-specific context menu
4. Right-click on the same icon -> nothing happens, context menu is not drawn, my compositor (`niri`) refocuses current window

**But** if there are multiple icons in a tray, any **other** icon is right-clickable and after any **other** icon is right-clicked, the **first one**becomes clickable again. So the workaround for this issue is to click icons in order, but never twice in a row.
Also, after some cooldown period the **first** icon becomes clickable again.

**Comment by YaLTeR** [comment]
It's likely a niri issue: https://github.com/YaLTeR/niri/issues/311

**Comment by dlblv** [comment]
> It's likely a niri issue: [YaLTeR/niri#311](https://github.com/YaLTeR/niri/issues/311)

Correct, the same issue with another bars.
