### ISSUE TITLE
[warning] module tray: Unknown module: tray

### ISSUE THREAD

**Issue by Mishio595** [Alexays/Waybar#384]
Before today, the tray was working properly. All I've done was add a custom module, which is working properly, but now the console outputs the warning in the title. I'm on commit 028b184f7b68d4263e2ee789b5b6555ca60f24b1

**Comment by Alexays** [comment]
You must have dbus menu gtk

**Comment by nathanblair** [comment]
@Alexays , could you elaborate more on dbus menu gtk?

On alpine there is a libdbusmenu-gtk3 package that provides the /usr/lib/libdbusmenu-gtk3.so library. Is this what is needed?

Thanks!
