### ISSUE TITLE
Waybar background turns black when Chromium is the only window in the workspace

### ISSUE THREAD

**Issue by Kyuunex** [Alexays/Waybar#3840]
Waybar background turns black when Chromium (Native wayland) is the only window in the workspace

![2024-12-21T05:19:28+00:00](https://github.com/user-attachments/assets/9975522b-a384-4acc-87e2-0b40d7179ed2)

![2024-12-21T05:19:05+00:00](https://github.com/user-attachments/assets/3ed0b387-bfe3-4dc7-b3d3-c08ef6f52bc2)

smart gaps has no effect on this
happens on both sway and hyprland

[config.json](https://github.com/user-attachments/files/18217316/config.json)

[style.txt](https://github.com/user-attachments/files/18217320/style.txt)
gh wont let me upload css so i renamed it to txt

**Comment by Kyuunex** [comment]
chromium launch flag im using is `--ozone-platform=wayland`. also it's ungoogled chromium but i doubt it makes a difference.

**Comment by 909oce** [comment]
im having the same issue, but it has nothing to do with chromium, just whenever i close a window on hyprland it causes a black background. reloading waybar fixes it, but then when i close a window again it happens again.

**Comment by msmafra** [comment]
> Waybar background turns black when Chromium (Native wayland) is the only window in the workspace
> 
> ![2024-12-21T05:19:28+00:00](https://private-user-images.githubusercontent.com/5400432/397906446-9975522b-a384-4acc-87e2-0b40d7179ed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjQ4MjIsIm5iZiI6MTczNDk2NDUyMiwicGF0aCI6Ii81NDAwNDMyLzM5NzkwNjQ0Ni05OTc1NTIyYi1hMzg0LTRhY2MtODdlMi0wYjQwZDcxNzllZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTQzNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDcwZGY2MWQyZWIyODZmZDI2NDJiMjdkNWFhNmYwYzUyNzY3YzhkMDZiZWVjMjhhYmRmZjlhZTExNDFiMjk1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lKBm4JETRqHYsKSEuvS4uIgeRNgM00cdrUz_25D5fgo)
> 
> ![2024-12-21T05:19:05+00:00](https://private-user-images.githubusercontent.com/5400432/397906448-3ed0b387-bfe3-4dc7-b3d3-c08ef6f52bc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjQ4MjIsIm5iZiI6MTczNDk2NDUyMiwicGF0aCI6Ii81NDAwNDMyLzM5NzkwNjQ0OC0zZWQwYjM4Ny1iZmUzLTRkYzctYjNkMy1jMDhlZjZmNTJiYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTQzNTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVmMWMxYjUyMzBjZjg1M2FiOGRhYjEzNGMwMjM4MTNkNTU2ZTM4ZmMwZGNhZjc3YjM5MjAzMWM3MTkzNzM1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EOP8TrZpRp76_ZdZjt7tHqYMaHhmIG4HlKy302S34XM)
> 
> smart gaps has no effect on this happens on both sway and hyprland
> 
> [config.json](https://github.com/user-attachments/files/18217316/config.json)
> 
> [style.txt](https://github.com/user-attachments/files/18217320/style.txt) gh wont let me upload css so i renamed it to txt

You have this on your .css file, that would set the bar to black when only using chromium:
```
window#waybar.chromium {
    background-color: #000000;
    border: none;
}
```
It doesn't consistently work for me it seems, I tested some months back, it worked with some apps but not others, testing with your full config it doesn't work for  me with chromium, firefox etc but works with kitty. Kitty sets its title property to only kitty, the others don't. It must be it. but Why it doesn't work for chromium on my system I dunno.
```
	class: Io.github.ungoogled_software.ungoogled_chromium
	title: Nova guia - Chromium
	initialClass: Io.github.ungoogled_software.ungoogled_chromium
	initialTitle: Nova guia - Chromium
---
	class: Org.chromium.Chromium
	title: Chromium Docs - Ozone Overview - Chromium
	initialClass: Org.chromium.Chromium
	initialTitle: Chromium Docs - Ozone Overview - Chromium
---
	class: kitty
	title: ~
	initialClass: kitty
	initialTitle: kitty
```

**Comment by msmafra** [comment]
> Thank you. I don't know how that got there and why i didn't notice it, but removing it fixed the issue. It was probably there for a long time but the issue didn't happen in past.
> 
> oh well.

It's inconsistent for me with both waybar and waybar-git on Fedora.
