### ISSUE TITLE
enable-bar-scroll shouldn't trigger on modules that handle scroll events

### ISSUE THREAD

**Issue by nenad** [Alexays/Waybar#386]
@RX14 mentioned in [a comment](https://github.com/Alexays/Waybar/pull/322#issuecomment-494037425) in #322 that the scrolling event should be consumed by the modules first, if they handle it. Personally, I use the scroll wheel to control the volume on the pulseaudio module, but with `enable-bar-scroll`, my workspaces are changed as well.

**Expected behavior**

My volume is changed, but not my workspaces when I scroll over a module that handles mouse wheel events.

**Comment by RX14** [comment]
I spent a long time trying to debug this but the gtk docs seem to be misleading:

Whatever you return from the scroll event handler, the scroll event bubbles as if you returned false.

**Comment by somini** [comment]
This can be worked around with #884
