### ISSUE TITLE
Conditionally execute backlight module

### ISSUE THREAD

**Issue by jeffa5** [Alexays/Waybar#393]
I typically have a laptop connected to an external monitor and disable the laptop's display. When I do this the backlight module shows `0%` as expected but it would be nice to have an option to disable displaying this module if the output is disabled. Maybe something like `exec-if`?

I don't know if this is something that has already been discussed, I couldn't find it easily. Hopefully this may be of interest to others too.

**Comment by Alexays** [comment]
This is a nice idea, and should be generic to other modules :)

**Comment by jeffa5** [comment]
I've had a go at working on this in #394
