### ISSUE TITLE
enable-bar-scroll causes waybar to freeze on scroll

### ISSUE THREAD

**Issue by ibrokemypie** [Alexays/Waybar#395]
after enabling enable-bar-scroll, whenever i scroll on waybar anywhere it changes workspace once, but then the entire bar freezes until I restart it

**Comment by dano6** [comment]
I can confirm this issue, it happens after 0.7 release update.
my config file: https://pastebin.com/xFp2VfQz
Steps to reproduce:
1. open 4 or more windows
2. scroll on waybar like crazy
3. waybar is frozen

**Comment by ibrokemypie** [comment]
for me this occurs even with a single scroll

**Comment by AndreasBackx** [comment]
I can confirm this. My custom scripts report a broken pipe when I do this.

**Comment by sheenobu** [comment]
https://gist.github.com/sheenobu/0be4ed7f9224f5b995156c47aca48bb7

looks like the ipc mutex is getting contention on two separate threads. one thread has it open and it is stuck on the workspace thread, which has it's own mutex it's locked on. the other is stuck waiting on the ipc mutex
