### ISSUE TITLE
Support for multiple batterys 

### ISSUE THREAD

**Issue by ctucx** [Alexays/Waybar#40]
some devices have more than one battery, eg. some lenovo devices.
so it would be pretty cool to have support for displaying more than one battery.

**Comment by ctucx** [comment]
would be cool to have an option for this, yes.

**Comment by vidister** [comment]
I'm implemented this feature. I will create a pull request as soon as I have cleaned up the code.

**Comment by Alexays** [comment]
@vidister Do you need help before you can make a PR ?

**Comment by Alexays** [comment]
Done in 7f1f217d84ae7f3b020ce28cd920f15722e15f52
