### ISSUE TITLE
Evolution alarm/reminder tray in waybar

### ISSUE THREAD

**Issue by copypaste10** [Alexays/Waybar#406]
Hello,

your project is really great. It's even better and simpler than i3status to configure. Obviously I use waybar on Sway. My only problem is: Evolution alarm/reminder throws a d-bus notification to mako (which displays it several seconds), but no Evolution reminder tray appears on waybar.

For example you use a full DE such as MATE. Evolution throws a notification about an upcoming appointment. At the same time Evolution drops an Evolution tray icon on the tray panel of MATE. I tried to start Evolution as x11 on Sway, but it still does not work.

**Comment by Alexays** [comment]
The application need to support the new protocol `StatusNotifierItem` used by `libappindicator` the old one is not supported..
The old one can be supported if we implement #254
