### ISSUE TITLE
crash when using pulseaudio module

### ISSUE THREAD

**Issue by norseghost** [Alexays/Waybar#415]
My pulsaudio action is crashing when I left-click over it. Running the on-click command directly works, as did clickng on the audio module a few version back.

config:
````
  "pulseaudio": {
        "scroll-step": 5,
        "format": "{volume}% {icon}",
        "format-bluetooth": "{volume}% {icon}",
        "format-muted": "",
        "format-icons": {
            "headphones": "",
            "handsfree": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        },
        "on-click": "pactl set-sink-mute $(pacmd list-sinks |awk '/* index:/{print $3}') toggle",
        "on-click-right": "pavucontrol",
        "tooltip": false
    },
````
waybar output:
````
(waybar:31179): glibmm-ERROR **: 01:43:19.455: 
unhandled exception (type std::exception) in signal handler:
what: argument not found

Trace/breakpoint trap (core dumped)
````

**Comment by sheenobu** [comment]
this is the problem: `awk '/* index:/{print $3}`

The {} in here are being parsed as variables coming out of waybar. it's probably crashing trying to figure out what variable "print $3" resolves to. Best bet is to wrap:

     pactl set-sink-mute $(pacmd list-sinks |awk '/* index:/{print $3}') toggle

into a 'toggle-mute' script sitting somewhere on your computer. If you must inline it, you can replace awk with perl:

     pactl set-sink-mute $(pacmd list-sinks | perl -ne '/index: (.*)/ && print $1') toggle

**Comment by norseghost** [comment]
why, thank you!
