### ISSUE TITLE
Media player module doesn't appear

### ISSUE THREAD

**Issue by hughwilliams94** [Alexays/Waybar#419]
The refactored script works well apart from one problem, it doesn't show up if Spotify is started after Waybar. I have to kill Waybar and restart it to get the module to appear. I am using the exact script from resources and the same config block. Running waybar from the terminal I can't see any errors.

**Comment by Alexays** [comment]
Any idea @SibrenVasse?

**Comment by SibrenVasse** [comment]
Yeah if the command line argument --player is not used, the module will not pick up new players while running. I've created a pull request. (#421)
