### ISSUE TITLE
Handle continuous scripts

### ISSUE THREAD

**Issue by ctucx** [Alexays/Waybar#42]
hey,
the rendering and of the bar stops when a custom module doesn't exit after output (eg continuous output).

**Comment by Alexays** [comment]
Thanks, I will check this soon :)

**Comment by Alexays** [comment]
@ctucx Waybar now handle continuous script test it on master :)
In order to tell that your script is endless just remove interval from it config.
Tell me if is working for you :D

**Comment by ctucx** [comment]
i'll try it tomorrow :D
