### ISSUE TITLE
Specific per-module CSS style doesnt override wildcard one

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#423]
In my  stylesheet I have `color` style set in the wildcard block (`*{ ... }`). When I set color in the specific module blocks, (i.e.`#window { ... }`), it doesn't apply - in all the modules text has the same color no matter what.

**Comment by Alexays** [comment]
Weird, this is more a gtk issue than a waybar one, i'm still going to look at it.

**Comment by Alexays** [comment]
You still have the problem? because I can't reproduce it, blocks order is important you mind check it :)
