### ISSUE TITLE
Popups like in Gnome

### ISSUE THREAD

**Issue by piegamesde** [Alexays/Waybar#427]
I'd like to create a pulseaudio equivalent module for JACK audio. It'll probably be like <https://extensions.gnome.org/extension/1138/jackconnect/>, with an integrated patch matrix.

In Gnome, there is some standard to create those pop-ups in the tray. Is there (or could there be) something similar for waybar?

**Comment by Alexays** [comment]
You can dot it with per example a custom tooltip, look at gtk doc :)
