### ISSUE TITLE
Usage with i3/sway ?

### ISSUE THREAD

**Issue by spjz** [Alexays/Waybar#43]
Configuring Sway or presumably i3 using the following seems to execute the bar correctly, but causes the default task switcher bar to be drawn regardless. Your documentation doesn't explain how to mitigate this

```
bar {
   status_command waybar
}
```

**Comment by Alexays** [comment]
Just execute the binary :)

**Comment by SethBarberee** [comment]
`swaybar_command waybar` is what you need. I currently use that on my sway config

**Comment by spjz** [comment]
Ah great thanks
-------- Original message --------From: Seth Barberee <notifications@github.com> Date: 10/09/2018  19:48  (GMT+00:00) To: Alexays/Waybar <Waybar@noreply.github.com> Cc: Joe Doherty <papaverjosepherum@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Alexays/Waybar] Usage with i3/sway ? (#43) 
swaybar_command waybar is what you need. I currently use that on my sway config

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Alexays/Waybar","title":"Alexays/Waybar","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Alexays/Waybar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SethBarberee in #43: `swaybar_command waybar` is what you need. I currently use that on my sway config"}],"action":{"name":"View Issue","url":"https://github.com/Alexays/Waybar/issues/43#issuecomment-420019850"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Alexays/Waybar/issues/43#issuecomment-420019850",
"url": "https://github.com/Alexays/Waybar/issues/43#issuecomment-420019850",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Alexays/Waybar] Usage with i3/sway ? (#43)",
"sections": [
{
"text": "",
"activityTitle": "**Seth Barberee**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SethBarberee",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Alexays/Waybar\",\n\"issueId\": 43,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Alexays/Waybar\",\n\"issueId\": 43\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Alexays/Waybar/issues/43#issuecomment-420019850"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 377979422\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Alexays** [comment]
Thanks for the tip @SethBarberee
