### ISSUE TITLE
SIGSEGV in waybar::Bar::layerSurfaceHandleConfigure

### ISSUE THREAD

**Issue by aplund** [Alexays/Waybar#433]
I get the following crash at seemingly random times.  It seems that it most commonly occurs at suspend/resume or after unlocking the screen with swaylock, though these are rather anecdotal.  I'm running waybar 0.7.2 on archlinux.

	Core was generated by `/usr/bin/waybar'.
	Program terminated with signal SIGSEGV, Segmentation fault.
	#0  0x00007f5bb656f0b7 in Gtk::Widget::set_size_request (this=0x562014e4b670, 
	    width=1920, height=30) at /usr/src/debug/gtkmm/gtk/gtkmm/../gtkmm/widget.h:365
	365	/usr/src/debug/gtkmm/gtk/gtkmm/../gtkmm/widget.h: No such file or directory.
	[Current thread is 1 (Thread 0x7f5bb23a59c0 (LWP 26900))]
	(gdb) set pagination off
	(gdb) bt
	#0  0x00007f5bb656f0b7 in Gtk::Widget::set_size_request(int, int) (this=0x562014e4b670, width=1920, height=30) at /usr/src/debug/gtkmm/gtk/gtkmm/../gtkmm/widget.h:365
	#1  0x0000562013a7684c in waybar::Bar::layerSurfaceHandleConfigure(void*, zwlr_layer_surface_v1*, unsigned int, unsigned int, unsigned int) (data=0x562014e4b640, surface=0x562014e34480, serial=105569, width=1920, height=30) at /usr/src/debug/Waybar-0.7.2/src/bar.cpp:241
	#2  0x00007f5bb47f36da in ffi_call_unix64 () at /usr/src/debug/libffi-3.2.1/src/x86/unix64.S:76
	#3  0x00007f5bb47f300b in ffi_call (cif=cif@entry=0x7ffd0be70e10, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7ffd0be70ee0) at /usr/src/debug/libffi-3.2.1/src/x86/ffi64.c:525
	#4  0x00007f5bb69a8caf in wl_closure_invoke (closure=closure@entry=0x562014e19e20, flags=flags@entry=1, target=<optimized out>, target@entry=0x562014e34480, opcode=opcode@entry=0, data=<optimized out>) at /usr/src/debug/wayland-1.17.0/src/connection.c:1014
	#5  0x00007f5bb69a56b1 in dispatch_event (display=display@entry=0x562014bff620, queue=<optimized out>) at /usr/src/debug/wayland-1.17.0/src/wayland-client.c:1430
	#6  0x00007f5bb69a6c5c in dispatch_queue (queue=0x562014bff6e8, display=0x562014bff620) at /usr/src/debug/wayland-1.17.0/src/wayland-client.c:1576
	#7  0x00007f5bb69a6c5c in wl_display_dispatch_queue_pending (display=0x562014bff620, queue=0x562014bff6e8) at /usr/src/debug/wayland-1.17.0/src/wayland-client.c:1818
	#8  0x00007f5bb69a70c0 in wl_display_roundtrip_queue (display=0x562014bff620, queue=0x562014bff6e8) at /usr/src/debug/wayland-1.17.0/src/wayland-client.c:1241
	#9  0x00007f5bb69a710d in wl_display_roundtrip (display=<optimized out>) at /usr/src/debug/wayland-1.17.0/src/wayland-client.c:1270
	#10 0x0000562013a767a9 in waybar::Bar::onMap(_GdkEventAny*) (this=0x562014e4b640, ev=<optimized out>) at /usr/src/debug/Waybar-0.7.2/src/bar.cpp:120
	#11 0x00007f5bb656a51a in sigc::slot1<void, _GdkEventAny*>::operator()(_GdkEventAny* const&) const (_A_a1=@0x7ffd0be71138: 0x7f5ba4005840, this=0x562014ee41f8) at /usr/include/sigc++-2.0/sigc++/functors/slot_base.h:335
	#12 0x00007f5bb656a51a in (anonymous namespace)::Widget_signal_delete_event_notify_callback(GtkWidget*, GdkEventAny*, void*) (self=<optimized out>, p0=<optimized out>, data=0x562014ee41f0) at /usr/src/debug/gtkmm/gtk/gtkmm/widget.cc:1560
	#17 0x00007f5bb553a778 in <emit signal ??? on instance ???> (instance=instance@entry=0x562014c26a60, signal_id=<optimized out>, detail=detail@entry=0) at /usr/src/debug/glib/gobject/gsignal.c:3447
	    #13 0x00007f5bb5be75bf in _gtk_marshal_BOOLEAN__BOXED (closure=0x562014ee4240, return_value=0x7ffd0be712e0, n_param_values=<optimized out>, param_values=0x7ffd0be71340, invocation_hint=<optimized out>, marshal_data=<optimized out>) at /usr/src/debug/build/gtk/gtkmarshalers.c:84
	    #14 0x00007f5bb5547d4b in g_closure_invoke (closure=0x562014ee4240, return_value=0x7ffd0be712e0, n_param_values=2, param_values=0x7ffd0be71340, invocation_hint=0x7ffd0be712c0) at /usr/src/debug/glib/gobject/gclosure.c:810
	    #15 0x00007f5bb5535889 in signal_emit_unlocked_R (node=node@entry=0x562014c4d9d0, detail=detail@entry=0, instance=instance@entry=0x562014c26a60, emission_return=emission_return@entry=0x7ffd0be71460, instance_and_params=instance_and_params@entry=0x7ffd0be71340) at /usr/src/debug/glib/gobject/gsignal.c:3635
	    #16 0x00007f5bb5538e6d in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffd0be71510) at /usr/src/debug/glib/gobject/gsignal.c:3401
	#18 0x00007f5bb59536e6 in gtk_widget_event_internal (event=0x7f5ba4005840, widget=0x562014c26a60) at /usr/src/debug/gtk/gtk/gtkwidget.c:7789
	#19 0x00007f5bb59536e6 in gtk_widget_event_internal (widget=0x562014c26a60, event=0x7f5ba4005840) at /usr/src/debug/gtk/gtk/gtkwidget.c:7658
	#20 0x00007f5bb5a9c703 in gtk_main_do_event (event=<optimized out>) at /usr/src/debug/gtk/gtk/gtkmain.c:1855
	#21 0x00007f5bb5a9c703 in gtk_main_do_event (event=<optimized out>) at /usr/src/debug/gtk/gtk/gtkmain.c:1685
	#22 0x00007f5bb57b04e4 in _gdk_event_emit (event=0x7f5ba4005840) at /usr/src/debug/gtk/gdk/gdkevents.c:73
	#23 0x00007f5bb57b04e4 in _gdk_event_emit (event=0x7f5ba4005840) at /usr/src/debug/gtk/gdk/gdkevents.c:67
	#24 0x00007f5bb577fcc4 in gdk_event_source_dispatch (base=<optimized out>, callback=<optimized out>, data=<optimized out>) at /usr/src/debug/gtk/gdk/wayland/gdkeventsource.c:124
	#25 0x00007f5bb545b0e3 in g_main_dispatch (context=0x562014c13000) at /usr/src/debug/glib/glib/gmain.c:3189
	#26 0x00007f5bb545b0e3 in g_main_context_dispatch (context=context@entry=0x562014c13000) at /usr/src/debug/glib/glib/gmain.c:3854
	#27 0x00007f5bb545cef1 in g_main_context_iterate (context=context@entry=0x562014c13000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /usr/src/debug/glib/glib/gmain.c:3927
	#28 0x00007f5bb545cf31 in g_main_context_iteration (context=context@entry=0x562014c13000, may_block=may_block@entry=1) at /usr/src/debug/glib/glib/gmain.c:3988
	#29 0x00007f5bb560ea7e in g_application_run (application=0x562014bb2210, argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/glib/gio/gapplication.c:2516
	#30 0x0000562013a46052 in waybar::Client::main(int, char**) (this=this@entry=0x562014b6e010, argc=<optimized out>, argc@entry=1, argv=<optimized out>, argv@entry=0x7ffd0be722d8) at /usr/src/debug/Waybar-0.7.2/src/client.cpp:290
	#31 0x0000562013a45076 in main(int, char**) (argc=1, argv=0x7ffd0be722d8) at /usr/src/debug/Waybar-0.7.2/src/main.cpp:22

**Comment by Alexays** [comment]
Should be fixed with recent fix.
Could you confirm?
I'll reopen otherwise.
