### ISSUE TITLE
Waybar not showing up

### ISSUE THREAD

**Issue by forkbomb9** [Alexays/Waybar#44]
I currently tried to run waybar under sway, and nothing showed up. It don't work neither from the terminal nor the `swaybar_command waybar` Any thoughts on why it's not working?

Arch Linux up-to-date kernel 4.18.6
sway 0.15.2-4-g6add71f6
waybar r128.28c65c64

**Comment by forkbomb9** [comment]
I'm stupid. Simple mistake in the config file

**Comment by ZJaume** [comment]
What was your mistake? I'm also using swaybar_command and it doesn't display

**Comment by Alexays** [comment]
@ZJaume Try to launch waybar by hand using the binary and paste the output here ;)

**Comment by Alexays** [comment]
@ZJaume What your env? (os, wm)

**Comment by ZJaume** [comment]
Sway (latest master) on Arch Linux

**Comment by Alexays** [comment]
Strange even when launching by hand it doesn't display?

**Comment by ZJaume** [comment]
Launhing by hand it displays, but swaybar_command or exec (commenting bar section) on the swayconfig does not work.

**Comment by ZJaume** [comment]
Sorry for that answer, now I have tried with exec waybar commenting bar settings and it's running
