### ISSUE TITLE
workspace: urgent color won't work

### ISSUE THREAD

**Issue by GitHubRepositoryX** [Alexays/Waybar#451]
using: sleep 3; echo -e '\a' rings the visual bell in alacritty, but when typing the command and switching to an different workspace "super + 2". The workspace with alacritty don't change the backgorund color. How can I fix this?

If #workspaces button.urgent is not set in the style.css, will this function simply be disabled and waybar won't actively displaying different colors on urgent windows?

config:
{
    "layer": "top",
    "modules-left": ["sway/workspaces", "sway/window"],
    "modules-right": ["network", "memory", "cpu", "pulseaudio", "backlight", "battery", "clock"],
    "sway/window": {
        "max-length": 100,
        "tooltip": false
    },
    "network": {
        "interval": 5,
        "format": "",
        "format-wifi": " up:{bandwidthUpBits} down:{bandwidthDownBits}",
        "format-ethernet": " up:{bandwidthUpBits} down:{bandwidthDownBits}",
        "format-disconnected": "",
        "tooltip": false
    },
    "memory": {
        "interval": 5,
        "format": " {used:0.1f}G/{total:0.1f}G",
        "tooltip": false
    },
    "cpu": {
        "interval": 5,
        "format": " {usage}%",
        "max-length": 10,
        "tooltip": false
    },
    "pulseaudio": {
        "format": "{icon} {volume}%",
        "format-bluetooth": "{icon} ",
        "format-muted": "",
        "format-icons": {
            "headphones": "",
            "handsfree": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        },
        "scroll-step": 1,
        "on-click": "pactl set-sink-mute 0 false",
        "on-click-right": "pactl set-sink-mute 0 true",
        "tooltip": false
    },
    "backlight": {
        "interval": 2,
        "format": "{icon}",
        "format-icons": ["", ""],
        "on-scroll-up": "light -A 1",
        "on-scroll-down": "light -U 1",
        "on-click": "light -A 10",
        "on-click-right": "light -U 10"
   },
    "battery": {
        "interval": 60,
        "format": "{icon} {capacity}%",
        "format-icons": ["", "", "", "", ""],
        "tooltip": false
    },
    "clock": {
        "interval": 1,
        "format": "{:%H:%M}",
        "format-alt": "{:%a, %d. %b  %H:%M}",
        "tooltip": false
    }
}

style.css:
* {
    border: none;
    border-radius: 0;
    font-family: Ubuntu Mono, FontAwesome;
    font-size: 15px;
    min-height: 0;
}

window#waybar {
    background: rgba(46, 52, 64, 0.8);
    border-bottom: 0px;
    color: #D8DEE9;
}

#workspaces button {
    padding: 0 5px;
    background: transparent;
    border-bottom: 0px;
    color: #D8DEE9;
}

#workspaces button.focused {
    background: #A3BE8C;
    border-bottom: 0px;
    color: #2E3440;
}

#workspaces button.urgent {
    background: #BF616A;
    border-bottom: 0px;
    color: #2E3440;
}

#window, #network, #memory, #cpu, #pulseaudio, #backlight, #battery, #clock {
    padding: 0 0px;
    margin: 0 5px;
}

#clock {
    background-color: transparent;
}

#battery {
    background-color: transparent;
    color: #D8DEE9;
}

#battery.charging {
    background-color: transparent;
    color: #A3BE8C;
}

@keyframes blink {
    to {
        background-color: transparent;
        color: #D8DEE9;
    }
}

#battery.warning:not(.charging) {
    background: transparent;
    color: #D8DEE9;
    animation-name: blink;
    animation-duration: 0.5s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}

**Comment by xPMo** [comment]
Urgency is an X11 property, native wayland (using the xdg-shell protocol) windows have no mechanism for providing urgency hints.
