### ISSUE TITLE
Modules pushed off screen don't return

### ISSUE THREAD

**Issue by HardDie** [Alexays/Waybar#452]
It seems to be related to bug 390, but this does not solve this problem.

First we see a normal top bar
![1](https://user-images.githubusercontent.com/18051793/64227214-4d3d2500-ceeb-11e9-8aba-c15a065e23dd.png)

On the second, one of the widgets gets too wide and pushes the right side out of the screen
![2](https://user-images.githubusercontent.com/18051793/64227215-4dd5bb80-ceeb-11e9-84cb-54a4968b4e73.png)

On the third, the widget became normal, but the right side is still pushed off the screen
![3](https://user-images.githubusercontent.com/18051793/64227216-4dd5bb80-ceeb-11e9-9227-4c944b1e1785.png)

**Comment by Alexays** [comment]
Can you share your config? :)

**Comment by HardDie** [comment]
Yes)
[conf](https://github.com/HardDie/My_linux_settings/blob/master/.config/sway/waybar.conf)
[style](https://github.com/HardDie/My_linux_settings/blob/master/.config/sway/style.css)

Running command in sway [config](https://github.com/HardDie/My_linux_settings/blob/master/.config/sway/config):
`bar {
    swaybar_command waybar -c ~/.config/sway/waybar.conf -s ~/.config/sway/style.css
}`

These are just bash scripts that display information using echo.

[Here](https://github.com/HardDie/My_linux_settings/tree/master/.my_scripts/.data) you can find scripts

**Comment by Alexays** [comment]
I'll check, in the meantime you can use 'max-length' settings for modules that have pretty big output :)

**Comment by HardDie** [comment]
Yes, maybe, but I have laptop with small display 1024x600 and a lot widgets)
This is not critical, just sometimes a little annoying when I need to restart the session)
I hope for some solution) Thank you)

**Comment by HardDie** [comment]
It looks like this problem has been fixed. In version 0.9.2 it works fine.
Thanks!)
