### ISSUE TITLE
changing clock type

### ISSUE THREAD

**Issue by saltybutter24** [Alexays/Waybar#453]
how do i change the clock to am pm time not 24 hour

**Comment by cafehaine** [comment]
https://github.com/Alexays/Waybar/wiki/Module:-Clock
http://www.cplusplus.com/reference/ctime/strftime/
so use this format `%I:%M %p` for the clock module

**Comment by saltybutter24** [comment]
> https://github.com/Alexays/Waybar/wiki/Module:-Clock
> http://www.cplusplus.com/reference/ctime/strftime/
> so use this format `%I:%M %p` for the clock module

thx for the help
