### ISSUE TITLE
how to test: battery not charging/blink

### ISSUE THREAD

**Issue by GitHubRepositoryX** [Alexays/Waybar#454]
Is there a way to test how this will look like?

`@keyframes blink {
    to {
        color: #D8DEE9;
    }
}

#battery.warning:not(.charging) {
    animation-name: blink;
    animation-duration: 0.5s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}`

**Comment by Alexays** [comment]
Check your `states` in the battery config
