### ISSUE TITLE
Disable swaynag after exiting Suspend

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [Alexays/Waybar#457]
I use this power [button](https://github.com/Alexays/Waybar/issues/202#issuecomment-484342124) in my waybar. But after leaving Suspend Swaynag does not hide anywhere, it remains visible on the screen. It would be nice to be able to hide it after exiting Suspend. 

What do you think about this?

**Comment by Alexays** [comment]
Swaynag it's not a Waybar feature but a sway one.
You should check Sway repo [swaywm/sway](https://github.com/swaywm/sway) :)

**Comment by Khomyak-sibiryak** [comment]
> You should check Sway repo swaywm/sway :)
Should I create a request in the Sway repo, and not here? Did I understand correctly?
> edit: look at this https://old.reddit.com/r/swaywm/comments/d0uo7g/disable_swaynag_window_after_exiting_suspend/
I am the author of the topic on Reddit.

**Comment by Alexays** [comment]
Oh my bad, yeah you can create an issue in the Sway repo cause Swaynag is a sway program.

**Comment by Khomyak-sibiryak** [comment]
OK, thanks for answer!
