### ISSUE TITLE
Waybar takes a long time to load/start when Wi-Fi is disabled

### ISSUE THREAD

**Issue by ysooqe** [Alexays/Waybar#461]
I would like to report a small issue. Unfortunately, I am not sure if the information I provide is sufficient enough. Let me know if any additional information is needed.

**Current Waybar version**
0.8.0 (0.8.0-2 installed from the official Arch repositories)
running on Arch with sway (version 1.2)

**Expected behaviour**
When Waybar is started, it loads quickly and without any delay.

**Actual behaviour**
When Waybar is started, either from a terminal or from a configuration file of a window manager like sway (with `swaybar_command waybar` in my case), and Wi-Fi is disabled (soft-blocked by rfkill) while the network module is enabled and used in the righthand side section of Waybar, it takes a long time (around 3 to 4 seconds) to load the bar.

**Steps to reproduce**
Disable (soft-block) Wi-Fi and start waybar (with the network module enabled in the waybar config) either from a terminal or reload the (sway-)configuration file that calls waybar.

**Additional Information**
If the network module of waybar is disable/not used, it loads/starts quickly as expected. So I think there might be an issue with the module itself.

**Comment by agwilt** [comment]
I'm pretty sure it's the module, see lines like https://github.com/Alexays/Waybar/blob/5ee4c54b13fe65371cbe88b1896dbabb760cb289/src/modules/network.cpp#L529.
where it sleeps for half a second before re-trying. Simply replacing 500ms with 50ms fixes it for me.

**Comment by Alexays** [comment]
Fixed with 211b1c27851beac46017aef3e55f4dbb10343783
