### ISSUE TITLE
Wifi signalStrength can be > 100%

### ISSUE THREAD

**Issue by tbm** [Alexays/Waybar#466]
Wifi signalStrength is 104% here:

![wifi-percentage](https://user-images.githubusercontent.com/1556037/65123609-e6902f00-d9f3-11e9-910e-76fd4cdfa6d2.png)

I think this should never be more than 100%.

I assume it's because of these assumptions in the code:

```
    // WiFi-hardware usually operates in the range -90 to -20dBm.
    const int hardwareMax = -20;
    const int hardwareMin = -90;
```

**Comment by Alexays** [comment]
Fixed with 334bc1e52ad3e7c60f1663799b84963c98f1d527
