### ISSUE TITLE
Abnormal CPU usage of the CPU module

### ISSUE THREAD

**Issue by jeremejevs** [Alexays/Waybar#47]
For some reason, even with a 30 second interval, the CPU module makes Waybar consume a lot of cycles (~75% of a core). As soon as I disable it and restart Waybar, it remains idle. I also have the RAM module enabled, but no problems there. Persists between reboots.

**Comment by Alexays** [comment]
First thx for reporting.
It's weird, you're on which distribution ?

**Comment by jeremejevs** [comment]
Arch, up-to-date.
