### ISSUE TITLE
Improve documentation about font fallback

### ISSUE THREAD

**Issue by jplatte** [Alexays/Waybar#473]
See discussion in https://github.com/Alexays/Waybar/pull/364. The existing font list in the default style and examples doesn't seem to be very useful.

I would recommend only listing a single font, if any, in the default style / examples, and add a comment to the css files that explains how to create a custom font or configure fontconfig to make icons work consistently.

**Comment by Alexays** [comment]
I'll try to check why gtk failed to pick some icon.
