### ISSUE TITLE
Waybar overlapping bemenu

### ISSUE THREAD

**Issue by olly1240** [Alexays/Waybar#474]
I'm not sure this is waybar related but when I start bemenu by shortcut, waybar overlaps it and makes it difficult to see what am I writing to bemenu. If I kill waybar, then open bemenu and with bemenu open launch waybar from a terminal it doesn't overlap but if I close that bemenu instance and open it again it shows that weird overlapping behaviour

**Comment by eknoes** [comment]
You can configure Waybar such that it is behind bemenu with `"layer": "bottom"` in the config file of Waybar.
