### ISSUE TITLE
network not showing up at all.

### ISSUE THREAD

**Issue by mh4nx7net** [Alexays/Waybar#476]
i've try by default configuration. of course by change oo they're logical interface name first 
pref: nmcli/ ifconfig/ip a
but it's still didn't showing up  yet... what wrong on here ? are there who have same issues as me 
thanks for reply

**Comment by Alexays** [comment]
What about logs?

**Comment by mh4nx7net** [comment]
how i can find them ?

**Comment by Alexays** [comment]
Launch waybar within your terminal.

**Comment by kdb424** [comment]
@mh4nx7net I had the same issue on artix. Running waybar in your terminal will likely show that you are missing the network module. If running on arch, or an arch like distro you can try waybar-git as that solved it for me, though would likely be a problem with the arch package.
