### ISSUE TITLE
Battery not charging when plugged in (status=Unknown) is intentional and should not show chargin icon.

### ISSUE THREAD

**Issue by dhanjit** [Alexays/Waybar#478]
Battery not charging when plugged in is intentional. It shows as "Unknown" in `cat /sys/class/power_supply/BAT1/status`.

There is a fallback in `battery.cpp` when status is `Unknown` that defaults to `getAdapterStatus`. Refer https://github.com/Alexays/Waybar/blob/97e3226801680211081abce54fe099c8b0bf5c18/src/modules/battery.cpp#L153-L155

This sets `status` to either `Charging` or `Discharging`.
https://github.com/Alexays/Waybar/blob/97e3226801680211081abce54fe099c8b0bf5c18/src/modules/battery.cpp#L132-L135

More reading where battery can be plugged and not charge.
https://wiki.archlinux.org/index.php/Tp_smapi 
https://forums.lenovo.com/t5/Lenovo-P-Y-and-Z-series/Conservation-Mode-in-Lenovo-Energy-Manager-plugged-in-not/ta-p/1677271

Another approach to take up this issue is to have support for conservation mode and enable or disable it from the waybar. Relevant: https://wiki.archlinux.org/index.php/Laptop/Lenovo#Battery_Conservation_Mode_on_IdeaPad_laptops

Offtopic: Windows apparently already does this automatically but hides it from the user.

**Comment by Alexays** [comment]
Ok maybe in the fallback instead of outputing `Charging`, we can just say `Plugged`?

**Comment by Alexays** [comment]
Done in 048d8d328ec41c6f1a18e2ad695a401a83a4d9b8
