### ISSUE TITLE
add {index} in workspace modules

### ISSUE THREAD

**Issue by victordiaz** [Alexays/Waybar#48]
As far as I've seen, I can show in my workspace area the name of the workspace and icon. 
Would it be possible to add {index}?

**Comment by Alexays** [comment]
Can you check on master with {index} ;) ?

**Comment by victordiaz** [comment]
Using master and using {index} inside format I get the following

```
unhandled exception (type std::exception) in signal handler:
what: argument not found
fish: Job 2, “./build/waybar” terminated by signal SIGTRAP (Trace or breakpoint trap)
```
Using {name} or {icon} works as expected

**Comment by Alexays** [comment]
That'll teach me to push without testing.
I'll test and keep you informed ;)
