### ISSUE TITLE
Failed to run on-click-'s command line including curled braces

### ISSUE THREAD

**Issue by Ventto** [Alexays/Waybar#484]
I cannot run a command line including curled braces in `on-click-*` options.

Here is an example of configuration file:

```json
{
    "layer": "top",
    "position": "bottom",
    "modules-center": [ "custom/test" ],
    "custom/test": {
        "format": "{}",
        "exec": "${HOME}/.config/waybar/modules/test/exec.sh",
        "on-click": "${HOME}/.config/waybar/modules/test/onclick.sh",
        "on-click-right": "echo command | awk '{print $1}'",
        "interval": 3
    }
}
```

Triggering `on-click` or `on-click-right`, for instance makes *waybar* fail and exist witht the following error message: 

```
(waybar:75012): glibmm-ERROR **: 17:01:49.909: 
unhandled exception (type std::exception) in signal handler:
what: argument not found
```

Located into [`AModule.cpp`](https://github.com/Alexays/Waybar/blob/12b30ca25f8575abf7c3f67c84e6a56ef7330661/src/AModule.cpp#L49), it appears that the `fmt::format()` function looks for the `{arg}` named argument in the given `format` string which does not exist. It will fail if the `format` string contains any `{...}` curled-brace substring.

**Comment by Alexays** [comment]
Fixed with #485
