### ISSUE TITLE
Dual battery bugs

### ISSUE THREAD

**Issue by SairesArt** [Alexays/Waybar#490]
Removing one of my thinkpad's two batteries makes waybar lose it's sanity.
It usually shows a random amount above 200%. After a couple of minutes it shows either 0%, 5% whilst flashing white/red or copies the second batteries amount. Clicking the battery module to show remaining time and back to percentage again resets the amount to a random value above 200%. Although I'd really love to have my batteries charge past 100% :]
Also for some reason it breaks the wifi module the first time I remove one of the batteries, making it shows disconnected for about a minute, even though I'm clearly still connected to a hotspot...
![bugs](https://user-images.githubusercontent.com/10562480/67602744-984f1800-f777-11e9-9a8e-87bf25cd81f0.png)

**Comment by pedrocr** [comment]
@SairesArt this is possibly fixed in current master. Could you please test and see?
