### ISSUE TITLE
Option to specify mpd password

### ISSUE THREAD

**Issue by maxigaz** [Alexays/Waybar#492]
My mpd server is protected with a password. While I can access it from [Polybar](https://gitlab.com/polybar/polybar/wikis/Module:-mpd) by giving the `password` the correct value in its configuration file, I can’t find such an option in the man page of Waybar v0.8.0 or in the [master branch](https://github.com/Alexays/Waybar/blob/master/man/waybar-mpd.5.scd).

**Comment by Alexays** [comment]
@minijackson Can you give a shot? :D

**Comment by minijackson** [comment]
I can try, but since I don't have much off time, I'd prefer to mentor someone, if someone wants to give this issue a shot ^^

**Comment by Alexays** [comment]
Done in #888 888
