### ISSUE TITLE
Network module does not detect disconnected state

### ISSUE THREAD

**Issue by tobiasjakobi** [Alexays/Waybar#494]
Hi,

using git master here. I noticed that the network module incorrectly detects my Ethernet device as 'linked', even though the interface is down and the cable is disconnected.

This is the output of ip:
2: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 80:fa:5b:24:a6:69 brd ff:ff:ff:ff:ff:ff

I haven't checked how the network module sources its information, but sysfs provides an operstate and carrier (which can only be read when the interface is UP). I have used this information in my custom Bash script to get the correct information about the if.

--- Tobias

**Comment by tobiasjakobi** [comment]
I had another look at this, and I think we already have the required information available. In handleEvents() we already copy some fields of the ifi object. My suggestion is to also copy ifi_flags and evaluate it in getNetworkState(). ifi_flags seems to provide exactly the information that ip presents in angle brackets (for my example above the BROADCAST and MULTICAST flags are set). For connections of ethernet type UP and LOWER_UP should be present.

Also netlink seems to provide more fine grained carrier state, see section 3.5.9 here:
https://www.infradead.org/~tgr/libnl/doc/route.html

**Comment by marcplustwo** [comment]
This might be similar to what I'm experiencing. In general it seems that the network module does not update properly. When I disable my wifi chip via rfkill, Waybar does not register that change. Only upon clicking on the module twice (once for alt-view and again back to normal), the icon is updated.

I verified that in `network.cpp` update()` is called regularly (interval is set to 10).

This is in version `0.9.0-2` from the arch repos.

**Comment by Geo25rey** [comment]
@marcplustwo Was #568 supposed to fix this issue?

**Comment by tobiasjakobi** [comment]
> @marcplustwo Was #568 supposed to fix this issue?

No, the PR has nothing to do with wired network connections.

**Comment by niktob560** [comment]
I have a little(but not a lot) similar issue
In case of disabling Wi-Fi via hardware button (status accessible via rfkill) network module shows that is already connected to the last Wi-Fi network
``netctl-auto list`` shows that it is not connected to any network in this case
