### ISSUE TITLE
Battery max capacity shows < 100%

### ISSUE THREAD

**Issue by davidlick** [Alexays/Waybar#496]
I only have one battery in my computer. The capacity is topping out at 92%. It's about 5 years old so I'm guessing waybar is calculating the capacity as current_charge / design_charge. Is there a way to have it reported as current_charge / last_full_charge kind of like i3status does?

**Comment by SamHH** [comment]
Seconding this, my battery tops out at 76% of its original capacity.

The [full-at](https://github.com/polybar/polybar/wiki/Module:-battery) option is how Polybar handles this.

**Comment by Alexays** [comment]
Done in master,
Added a full-alt config to battery module
