### ISSUE TITLE
pulseaudio module source indicator issue

### ISSUE THREAD

**Issue by diraol** [Alexays/Waybar#497]
I'm facing two issues.

First, with "source", it usually stays at 100% level, despite my mic being muted or with the volume around 10%.
If I open Pavucontrol, change the value, then it is updated in the waybar. But as soon as I close the Pavucontrol then the mic is back to "100% & on", no matter the current status (on, off, muted, 10%, 70%, 100%, etc).

Relevant config:
```
 "pulseaudio": {
        "format": "{volume}% {icon} {format_source}",
        "format-bluetooth": "{volume}% {icon} {format_source}",
        "format-bluetooth-muted": "ﳌ {icon} {format_source}",
        "format-muted": "🔇 {format_source}",
        "format-source": "{volume}% ",
        "format-source-muted": "",
        "format-icons": {
            "headphones": "🎧",
			"default": [
                "🔈",
                "🔉",
                "🔊"
			]
        },
        "scroll-step": 5,
        "on-click": "pavucontrol"
    },
```

**Comment by Alexays** [comment]
Should be fixed with #599
