### ISSUE TITLE
Clock does not updating

### ISSUE THREAD

**Issue by niktob560** [Alexays/Waybar#498]
Clock module does not automatically updating  
Waybar version: ``Waybar v0.8.0-55-g67f6dad (Oct 29 2019, branch 'master')``  
Updates at click and changing mode of clock  
Module in config:  
```
    "clock": {
        "tooltip-format": "{:%Y-%m-%d | %H:%M}",
        "format-alt": "{:%Y-%m-%d}"
    },
```

**Comment by niktob560** [comment]
Not only clock doesn't updates, battarey module too

**Comment by Alexays** [comment]
Really werid, can you give me your config?

**Comment by niktob560** [comment]
sway: [config](https://pastebin.com/qP3GcGy0)  
bar: [config](https://pastebin.com/xJ76XeB8)
styles: [style.css](https://pastebin.com/VihY8B44)
it happens not always, but it's annoying

**Comment by kisy** [comment]
```json
"clock": {
    "interval": 60,
    "format": "{:%H:%M}",
    "max-length": 25
}
```

Add intervel settings

**Comment by Alexays** [comment]
Adding an `interval` of 60 is useless as the default is 60 😄
@niktob560 do you still have this problem?

**Comment by niktob560** [comment]
adding ``"interval": 30`` into clock config solved problem with it
Battery module works without interval

**Comment by Alexays** [comment]
@niktob560 does it update every two minutes if you set an interval of 60?

**Comment by niktob560** [comment]
no, it works correctly
tested just now - it's updating at least every minute

**Comment by Alexays** [comment]
So it's work, what's the problem?
If you don't set an interval, it doesnt work?

**Comment by rileysu** [comment]
> So it's works, what's the problem?
> If you don't set an interval, it doesnt work?

I seem to be getting this issue too. I'll test with an interval to see if it fixes the problem.

**Comment by Alexays** [comment]
Is the issue persist with latest waybar versions?
I'll close the issue, please reopen it otherwise

**Comment by MrGamerDoesGames** [comment]
> ```json
> "clock": {
>     "interval": 60,
>     "format": "{:%H:%M}",
>     "max-length": 25
> }
> ```
> 
> Add intervel settings

love you bro
