### ISSUE TITLE
Unknown module: pulseaudio

### ISSUE THREAD

**Issue by adc17** [Alexays/Waybar#499]
Hi, I'm confused by this error message as I thought pulseaudio was a built-in module: 
```
[warning] module pulseaudio: Unknown module: pulseaudio
```

waybar --version: Waybar v0.8.0
OS: Nixos 19.09

How can I debug this?

**Comment by tobiasjakobi** [comment]
What do you understand by built-in? Waybar is always one single binary. A Waybar module is not like a kernel module.

Concerning your problem, you distribution probably hasn't build Waybar with pulseaudio support.

**Comment by adc17** [comment]
> What do you understand by built-in?

I meant included in the waybar binary, so I wasn't clear on how it could be missing.

> distribution probably hasn't build Waybar with pulseaudio support.

Thanks, this was helpful and correct. For future readers I set this in my `configuration.nix` to force building with pulseaudio support:

```
  nixpkgs.config.pulseaudio = true;
```

**Comment by Kaligule** [comment]
@adc17 I am currently facing the same problem, but your proposed solution doesn't seem to work. Do you think it might be possible for you to share your nixos config so I could debug mine against it? Thanks a lot in advance.

**Comment by adc17** [comment]
Hi @Kaligule, here is my primary [nixos config](https://github.com/adc17/nix-configs/tree/ccbf62f43f55e5568f7d0dcb1d1043cdcd00bd88/t440p). My [sway](https://github.com/adc17/dotfiles/tree/0867f80a906f21ed778763cd277628c627f545b5/sway) and [waybar](https://github.com/adc17/dotfiles/tree/0867f80a906f21ed778763cd277628c627f545b5/waybar) configs might also be useful. Hope it helps!
