### ISSUE TITLE
Is there any way to have icons with different colors than text?

### ISSUE THREAD

**Issue by victordiaz** [Alexays/Waybar#50]
I've checked already with the GTK inspector to see if the icon is wrapped in a tag that I can reference using CSS, but the icon (fontawesome) is in the same level as the text. 

Tried as well to wrap the icon using a <span> tag but I got the tag rendered as a text. 

I think it would be great to custom wrap elements in tags (I dont know how difficult is with the current implementation) for a finer css styling

I can imagine something like 
```
<button>
<span class = "index">{index}</span>
<span class = "icon">{icon}</span>
<span class = "name"></span>
</button>
```

btw I really love the project and styling with css is supergreat!

**Comment by Alexays** [comment]
Now possible on master (bd62c4cbc55f57566069a4addeea43c69fb10827)
```<span color=\"#fff\">{}</span>```
By using [PangoMarkupFormat](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html#PangoMarkupFormat)

**Comment by Arnaudv6** [comment]
fornat -> format
just lost quite some time searching this one...

**Comment by AndreasBackx** [comment]
Is there a better way of handling this perhaps? It'd be neat if we could keep all styling in our CSS file.

**Comment by Fxzzi** [comment]
Currently using the method in the previous comment but I agree in having the icon class for the css so we can change all the colours in one place
