### ISSUE TITLE
Using state for exec command

### ISSUE THREAD

**Issue by tmarti2** [Alexays/Waybar#500]
Hi,
I'm using the following module : 
```
"custom/pacman": {
        "states": {
            "zero": 0,
            "low": 50,
            "medium": 100,
            "high": 200
        },
        "format": "{} ",
        "interval": 3600,
        "exec": "checkupdates | wc -l",
        "exec-if": "exit 0",
        "tooltip": false,
        "on-click": "kitty pacman -Syu; pkill -SIGRTMIN+8 waybar",
        "signal": 8
}
```
I tried to use state like I did for othe rmodules, with
```
#custom-pacman.zero {
    color: #00FF00
}
[...]
```
So that the color would change depending on the number of packages with updates.
But it doesn't seem to work. Is that possible? Am I doing something wrong?
Thanks

**Comment by Alexays** [comment]
ATM  states is not compatible with Custom modules, otherwise you can implement a script that check the ouput of `checkupdates | wc -l` and so returning a json with the classes that you want waybar to apply.

**Comment by tmarti2** [comment]
I did this :
```
#/bin/zsh
nb=$(checkupdates | wc -l)
echo -e "{\"class\":\"pacman\",\"percentage\":\""$nb"\"}"
```
and 
```
"format": "{percentage} ",
```
And so it works in style.css with custom-pacman.pacman.
But I only have 1 style possible right? I can't really change the color depending on percentage value?
