### ISSUE TITLE
Battery Module: status not read correctly

### ISSUE THREAD

**Issue by morten-b** [Alexays/Waybar#504]
Using custom formats for the battery module does not read correctly from `/sys/class/power_supply/<bat>/status`

When `/sys/class/power_supply/<bat>/status` outputs `Not Charging` the config file must say `"format-not"`. It cuts of the last part after the space.

**Comment by Alexays** [comment]
Fixed with c8821a5e7ff9de5f55189a5128d6413b9505dd51 and d40cc6f23a7dba1736dadd0fe180c2bed0831785
