### ISSUE TITLE
Document "on-middle-click" option

### ISSUE THREAD

**Issue by fuzxi** [Alexays/Waybar#505]
Similar to `on-click` and `on-right-click`, I'd like an `on-middle-click` option. This is one of the few features I'm missing from `polybar`, as I used it with the mpd module: left click for previous track, middle click for play/pause, right click for next track.

**Comment by cprussin** [comment]
ha, I was just about to put in this ticket myself earlier today.

While spelunking the code to see how to add it, I found that the option already exists: `on-click-middle`.  It's just not documented.  See https://github.com/Alexays/Waybar/blob/master/src/AModule.cpp#L11

**Comment by Alexays** [comment]
Oh yeah, if someone wants to update wiki and doc to add the missing clicks?

**Comment by fuzxi** [comment]
I made appropriate edits to the wiki and updated the custom module man page in PR #517

**Comment by Alexays** [comment]
Done in #517 by @fuzxi
