### ISSUE TITLE
PulseAudio volume does not correspond to pavucontrol

### ISSUE THREAD

**Issue by Ranguvar** [Alexays/Waybar#51]
I have sway config set to increment/decrement volume by 5%, and pavucontrol reflects this.
Waybar's audio display module seems to usually show 4% increments however.

Just a little annoyance, bugs me quite a bit.
I'll look and try to fix it, just been a while since I did C, and never really touched C++.

**Comment by Alexays** [comment]
Can you check on master if is fixed :)

**Comment by Ranguvar** [comment]
Beautiful!
