### ISSUE TITLE
Wifi shows disconnected status after suspend/wakeup on iwd

### ISSUE THREAD

**Issue by hajdamak** [Alexays/Waybar#511]
Network module after suspend/wakeup displays disconnected status although wifi works fine.

os: latest arch
waybar 0.8.0-4
iwd 1.1-2

**Comment by Alexays** [comment]
Similar to #494

**Comment by husam212** [comment]
I noticed querying wifi `nmcli device wifi` fixes the issue, not sure why, I'm running that periodically every few seconds as a temporary solution.
