### ISSUE TITLE
Wifi connect status on IPV6 only

### ISSUE THREAD

**Issue by thomasths27** [Alexays/Waybar#513]
Hi,

i have waybar running on a device without a ipv4 address.
Waybar shows my interface always as disconnected even when IPV6 connectivity is available.
My network manager is netctl.
I am not really sure if i overlooked something.

Thank you for your time

**Comment by jomority** [comment]
The network module uses IPv4 by default for connectivity detection.

You can change this with the `family` [option](https://github.com/Alexays/Waybar/wiki/Module:-Network). You didn't overlook it, it was not documented. 

You will notice that currently the displaying of the IPv6 address is broken. I have already created a pull request for the fix (#540).
