### ISSUE TITLE
change inline color in modules

### ISSUE THREAD

**Issue by eoli3n** [Alexays/Waybar#516]
Hi,

I want to recreate my polybar clock module with waybar
Is there any way to add colors in 

```
"clock": {
        "format": "{:%e%m%y %H%M%S}",
        "tooltip": false
}
```

With polybar i did something like 

```
date = "%d%{F#92}%m%{F-}%{F#49}%y%{F-}"
```

![img](https://x0.at/xOu.png)

I don't know how to do this, even with custom module.

**Comment by Alexays** [comment]
You can use https://github.com/Alexays/Waybar/wiki/Configuration#module-format for that :)

**Comment by lmanul** [comment]
I apologize this is a completely gratuitous comment, but I would like to thank Alexis and the Waybar community in general for being so kind and welcoming. This bug report is a perfect example.

Many owners/maintainers would be less nice/patient by asking to search before filing a bug, to "RTFM", etc, etc. Instead Alexis's answer is informative, patient, and friendly. Kudos :-)

**Comment by ironlungx** [comment]
Can I use variables in the inline css? something like this:
```json
"format": "<span color='@green'> {icon}</span>"
```
