### ISSUE TITLE
Output Exclusion

### ISSUE THREAD

**Issue by lucid-daemon** [Alexays/Waybar#518]
I'd like to display a waybar on all outputs BUT my primary output that only shows "sway/workspaces" and display my normal waybar on my primary output. At the moment if i define a waybar (workspaces only) without assigning an output and defining a waybar with all my preferences for my eDP-1 then i get 2 bars on eDP-1.

Is it possible to exclude an output in the "output" field?

**Comment by mab122** [comment]
Hi, is this closed issue? Because it is mentioned in configuration part at https://github.com/Alexays/Waybar/wiki/Configuration#multi-output-config
but output exclusion does not seem to work for me. I am using Waybar v0.9.2 (Apr 11 2020, branch 'makepkg')

**Comment by Alexays** [comment]
@mab122 Wiki was updated a bit early, it's now possible as #596 is merged!

**Comment by lucid-daemon** [comment]
It doesn't work for me.
I've tested this with Waybar v0.9.2-64-g4b28518 (May 12 2020, branch 'master') from the AUR.

My Config:

```
[
  {
    "output": ["!eDP-1"],
    "layer": "top",
    "modules-left": ["sway/workspaces", "sway/mode"],
    "modules-right": ["clock", "tray"]
  },

  {
    "output": ["eDP-1"],
    "height": 38,
    "layer": "top",
    "modules-left": ["sway/workspaces", "sway/mode", "custom/media"],
    "modules-right": ["mpd", "idle_inhibitor", "blah", "blah", "blah"],
SNIP
  }
]
```

The first bar isn't displayed on any screen, the bar for eDP-1 is displayed normally.

**Comment by lucid-daemon** [comment]
My mistake
correcting the line
`"output": ["!eDP-1"],`
to
`"output": "!eDP-1",`
fixed it
