### ISSUE TITLE
Issue with long window titles

### ISSUE THREAD

**Issue by ForTheReallys** [Alexays/Waybar#52]
I have my center module set to sway/window but when the title reaches a certain length, it shifts my right modules further right and off the screen.  Can this be fixed with CSS or is this just a bug?

Thanks!

**Comment by Alexays** [comment]
I can't reproduce it anymore, can you?

**Comment by Robinhuett** [comment]
Unfortunatly I can still reproduce this issue, just by having a window with a really long title in focus an no `max-length` set.

**Comment by Robinhuett** [comment]
Works like a charm :)
This can be closed than
