### ISSUE TITLE
Creating a custom module

### ISSUE THREAD

**Issue by 4e554c4c** [Alexays/Waybar#521]
Hello,

This is most likely a question and not an issue; however I'm posting it here because I don't know where else to.

I am trying to create a custom waybar module to display whether or not my Yubikey needs to be touched or not.

I created a program which outputs json depending on the state of the yubikey—either
```json
{"text": "","percentage": 0,"class":"active"}
````
if it needs attention; or
```json
{"text": "","percentage": 0,"class":"inactive"}
```
if it does not.

It does this in a constant polling fashion so it is always running.

The relevant portion of my `config` is as follows
```json
    "custom/yubikey": {
        "interval": "once",
        "return-type": "json",
        "exec": "~/.config/waybar/modules/touch",
        "format": "{icon}",
        "format-icons": ["<key icon>"],
        "escape": true
    }
```
and I wish to theme it such that `#custom-yubikey-inactive` is invisible while `custom-yubikey-active` is blinking or high res.

However, at the moment currently nothing shows up. Even if the program outputs json the module never appears. I am currently styling `#custom-yubikey` as every other module, so I'm not quite sure what is wrong.

**Comment by tmccombs** [comment]
Probably not the only problem, but I think that you probably don't want to set interval to once, if it is continuously running.

**Comment by Alexays** [comment]
When text is empty the module will not show anything...

**Comment by keepclean** [comment]
> When text is empty the module will not show anything...

Do you mean `text` inside json which were generated by a script?

> #custom-yubikey-inactive

According to ` waybar-custom (5)` man page, style should be in format `#custom-<name>.<class>`

**Comment by 4e554c4c** [comment]
So if the text is empty the module will not show, even if there is content in the `format` area?
Also I am running this script with `once` as it remains in the background and should not be started multiple times.

**Comment by maximbaz** [comment]
@4e554c4c FYI in case you are still looking into creating a Yubikey module, and in case you are using [yubikey-touch-detector](https://github.com/maximbaz/yubikey-touch-detector), here's how I did it, works really well with waybar:

https://github.com/maximbaz/dotfiles/blob/master/bin/waybar-yubikey

```
"custom/yubikey": {
    "exec": "waybar-yubikey",
    "return-type": "json"
},
```
