### ISSUE TITLE
Have a way to send events to custom module

### ISSUE THREAD

**Issue by tmccombs** [Alexays/Waybar#523]
Currently, you can handle mouse events by running a command, but it doesn't look like there is a way to send the mouse event to a continuously running module program, so that the module program can update the message in response to a mouse event. For example, I was thinking about how I might create a custom module  similar to the clock module but with #522.  It is possible to do this by using some other kind of IPC which is triggered by a command on mouse events to inform the module program, but it would be simpler to implement the module if the event was sent to the program over stdin.

**Comment by Alexays** [comment]
I'll not implement something like that on the waybar side, you can write such scripts to handle your need.
For the clock module you can trigger a timezone change on click and the script will echo the new time based on the new timezone. :)

**Comment by tmccombs** [comment]
> you can write such scripts to handle your nee
Yes, it is possible, but it's certainly not simple.

> For the clock module you can trigger a timezone change on click
 I don't want to change the system timezone on click, I just want to change the display in waybar.
