### ISSUE TITLE
{desc} doesn't work in the pulseaudio module

### ISSUE THREAD

**Issue by sarna** [Alexays/Waybar#528]
Hi,
When I put {desc} in "format" nothing changes, and when I put it in "format-source" or "format-source-muted" the module disappears completely from the bar. Is it a known issue, or is something wrong with my install?

Waybar v0.8.0
sway version 1.2
Linux 5.4.2 on Manjaro 18.1.4

**Comment by Alexays** [comment]
{desc} is only available on latest version 0.9.0
