### ISSUE TITLE
style second instance of a module

### ISSUE THREAD

**Issue by eoli3n** [Alexays/Waybar#544]
if i create two modules ``network`` and ``network#speed``, how to style the second one ?
tried
```
#network {
    border-bottom: 2px solid @purple;
}

#network#speed {
    border-bottom: 2px solid @red;
}
```
But it applies ``#network`` for the 2 modules

**Comment by Alexays** [comment]
By using `#network.speed`, you can update the wiki if is not mentioned :)

**Comment by eoli3n** [comment]
Done, thx
