### ISSUE TITLE
False positive in version detection from git

### ISSUE THREAD

**Issue by z3ntu** [Alexays/Waybar#547]
In Alpine Linux packaging, git is installed in the build environment and as such meson will find git. The meson.build from Waybar then runs `git describe` (etc) and will determine the version from it. 
Unfortunately this leads to a pretty strange version string in Alpine:
```
/ # waybar --version
Waybar vv20191219-989-g06c9c19fa9 (Jan  7 2020, branch 'master')
```
I would propose that the meson.build also checks if `git rev-parse --show-toplevel` is actually Waybar and not something else (by using relative paths from meson.build). Or provide a build-time options for that can be used by distribution to turn that off.

p.s.: another example when git is installed but Waybar is built from a source tarball:
```
Waybar v (Jan  7 2020, branch '')
```

**Comment by Alexays** [comment]
Latest commit fix the issue in my case, do you agree?
d5bd3be8de0f7f20f97628969fb328ffb5822b07

**Comment by z3ntu** [comment]
Still an issue on the master branch:
```
Waybar v (Apr  5 2020, branch '')
```

**Comment by Alexays** [comment]
Ok so we need to implement `git rev-parse --show-toplevel` and check current dir.

**Comment by Alexays** [comment]
If you want to give a shot

**Comment by Alexays** [comment]
Done the check in 49ae944d65218ee667de4cbcc86793c5d4d9c5b9
