### ISSUE TITLE
[BUG] using iwd's dhcpcd client: network module does not refresh.

### ISSUE THREAD

**Issue by libXq** [Alexays/Waybar#549]
system info:
Archlinux:
waybar 0.9.0-1
iwd 1.4-1

in ~/.config/waybar/config
```
    "network": {
        "interval": 10,
        "format": "",
        "format-wifi": " up:{bandwidthUpBits} down:{bandwidthDownBits}",
        "format-ethernet": " up:{bandwidthUpBits} down:{bandwidthDownBits}",
        "format-disconnected": "",
        "tooltip": false
    },
```
in /etc/iwd/main.conf
```
[General]
EnableNetworkConfiguration=true

[Scan]
DisablePeriodicScan=true
```

how to reproduce:
1. start sway with waybar
2. systemctl start iwd

>>> waybar-network-module won't get updated

how to fix:
first, not really a fix:
restarting waybar after iwd service got started, refreshes the network-module now it displays correct data.

secound:
changing ~/.config/waybar/conf
```
    "network": {
        "interval": 10,
        "interface": "wlan0",
        "format": "",
        "format-wifi": " up:{bandwidthUpBits} down:{bandwidthDownBits}",
        "format-ethernet": " up:{bandwidthUpBits} down:{bandwidthDownBits}",
        "format-disconnected": "",
        "tooltip": false
    },
```

ethernet connection wont get displayed by adding the interface "wlan0", but format-wifi is getting displayed correctly, no waybar refresh required.

**Comment by JadElClemens** [comment]
Having this issue intermittently. For me, sometimes the module does refresh (switching between disconnected and wifi states), but it doesn't refresh other information like signal strength.

Other times, especially after suspend or closing my laptop screen, the module won't refresh at all (i.e. change from disconnected to wifi state).

**Comment by libXq** [comment]
By chaning
/etc/iwd/main.conf to

```
[General]
EnableNetworkConfiguration=true
UseDefaultInterface=true

[Scan]
DisablePeriodicScan=true
```

the problem seems to be fixed, probably coused by iwd.

**Comment by JadElClemens** [comment]
> By chaning
> /etc/iwd/main.conf to
> 
> ```
> [General]
> EnableNetworkConfiguration=true
> UseDefaultInterface=true
> 
> [Scan]
> DisablePeriodicScan=true
> ```
> 
> the problem seems to be fixed, probably coused by iwd.

This works for me as well. I only had to add `UseDefaultInterface=true`, setting `DisablePeriodicScan=true` was unnecessary for me.
