### ISSUE TITLE
Module battery doesn't update

### ISSUE THREAD

**Issue by Ogromny** [Alexays/Waybar#55]
Hi,

All of my modules are working except the module battery ( He's just `update` once ).

Here is my config 
```
{
	"layer": "top",
	"height": 36,
	"modules-left": [
		"sway/workspaces"
	],
	"modules-center": [
		"sway/window"
	],
	"modules-right": [
		"network",
		"pulseaudio",
		"battery",
		"clock"
	],
	"sway/workspaces": {
		// todo
	},
	"sway-window": {
		"max-length": 80
	},
	"network": {
		"format-wifi": "{essid} ({ifname}) ",
		"format-ethernet": "{essid} (ifname) ",
		"format-disconnected": "睊"
	},
	"pulseaudio": {
		"format": "{volume}% ",
		"format-muted": "婢"
	},
	"battery": {
		"format": "{capacity}% {icon}",
		"format-icons": ["", "", "", "", ""]
	},
	"clock": {
 		"format-alt": "{:%d/%m/%Y}"
	}
}
```

**Comment by Alexays** [comment]
Battery module use inotify to watch changes, maybe you reach the limit of watches :/
try `sudo sysctl fs.inotify.max_user_watches=524288` to allow more watches.
First do you get `Unable to listen batteries.` when you launch Waybar ?

**Comment by Ogromny** [comment]
When i launch Waybar I get
```
(waybar:7497): Gtk-WARNING **: 10:13:50.673: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(waybar:7497): Gtk-WARNING **: 10:13:50.674: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(waybar:7497): Gtk-WARNING **: 10:13:50.674: Theme parsing error: gtk.css:129:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(waybar:7497): Gtk-WARNING **: 10:13:50.674: Theme parsing error: gtk.css:130:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(waybar:7497): Gtk-WARNING **: 10:13:50.674: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(waybar:7497): Gtk-WARNING **: 10:13:50.674: Theme parsing error: gtk.css:135:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(waybar:7497): Gtk-WARNING **: 10:13:50.675: Theme parsing error: gtk.css:142:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
Bar configured (width: 2880, height: 36) for output: eDP-1
```

and `fs.inotify.max_user_watches` is already at 524288

**Comment by Alexays** [comment]
Can you give me the output of  `ls -lR /sys/class/power_supply/**/*`
thx :)

**Comment by Ogromny** [comment]
lrwxrwxrwx 1 root root    0 25 oct.  11:12 /sys/class/power_supply/ADP1/device -> ../../../ACPI0003:00
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/ADP1/online
lrwxrwxrwx 1 root root    0 25 oct.  09:03 /sys/class/power_supply/ADP1/subsystem -> ../../../../../../class/power_supply
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/ADP1/type
-rw-r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/ADP1/uevent
-rw-r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/alarm
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/capacity
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/charge_full
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/charge_full_design
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/charge_now
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/current_avg
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/current_now
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/cycle_count
lrwxrwxrwx 1 root root    0 25 oct.  09:08 /sys/class/power_supply/BAT0/device -> ../../../ACPI0002:00
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/manufacturer
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/model_name
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/present
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/status
lrwxrwxrwx 1 root root    0 25 oct.  09:03 /sys/class/power_supply/BAT0/subsystem -> ../../../../../../../../../../class/power_supply
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/technology
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/temp
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/type
-rw-r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/uevent
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/voltage_min_design
-r--r--r-- 1 root root 4096 25 oct.  11:13 /sys/class/power_supply/BAT0/voltage_now

/sys/class/power_supply/ADP1/power:
total 0
-rw-r--r-- 1 root root 4096 25 oct.  11:13 async
-rw-r--r-- 1 root root 4096 25 oct.  11:13 autosuspend_delay_ms
-rw-r--r-- 1 root root 4096 25 oct.  11:13 control
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_active_kids
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_active_time
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_enabled
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_status
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_suspended_time
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_usage
-rw-r--r-- 1 root root 4096 25 oct.  11:13 wakeup
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_abort_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_active
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_active_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_expire_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_last_time_ms
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_max_time_ms
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_prevent_sleep_time_ms
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_total_time_ms

/sys/class/power_supply/BAT0/power:
total 0
-rw-r--r-- 1 root root 4096 25 oct.  11:13 async
-rw-r--r-- 1 root root 4096 25 oct.  11:13 autosuspend_delay_ms
-rw-r--r-- 1 root root 4096 25 oct.  11:13 control
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_active_kids
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_active_time
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_enabled
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_status
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_suspended_time
-r--r--r-- 1 root root 4096 25 oct.  11:13 runtime_usage
-rw-r--r-- 1 root root 4096 25 oct.  11:13 wakeup
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_abort_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_active
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_active_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_expire_count
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_last_time_ms
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_max_time_ms
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_prevent_sleep_time_ms
-r--r--r-- 1 root root 4096 25 oct.  11:13 wakeup_total_time_ms

**Comment by Alexays** [comment]
Ok, I found out why :? it's because the /sys/class/power_supply file is a sysfs and not a real file so it can't be watched correctly with inotify, I have to find another solution, udev for example

**Comment by Alexays** [comment]
I'm stupid, the issue already exists. #41
