### ISSUE TITLE
[Wiki] Improve documentation on how to install Font Awesome OTF

### ISSUE THREAD

**Issue by apiraino** [Alexays/Waybar#551]
Hi!

I spent a bit of time before understanding how to install the Font Awesome package on a computer, it is a required package for the default Waybar installation.

I thought about slightly improving the Wiki with this little patch.

Make sense?
[patch.diff.log](https://github.com/Alexays/Waybar/files/4053884/patch.diff.log)

Thanks for evaluating this !

**Comment by Alexays** [comment]
Yeah feel free to update the wiki if you encounter any problems :)
