### ISSUE TITLE
Segfault upon disconnecting thunderbolt dock

### ISSUE THREAD

**Issue by luispabon** [Alexays/Waybar#558]
https://gist.github.com/luispabon/8042e039c3d17a6cd107a6e00f374534

Waybar b9cd51a9cc9042166d94f6127ab37c60ff3e917f
Sway 1.3-rc3
Ubuntu 19.10

This typically happens upon disconnecting my thunderbolt dock (2 displays on it, 1hdmi 1dp and couple of input devices, dock built in audio), just before putting the laptop to sleep. I can see waybar crashing before sleep though. 

It's been happening for a while though.

**Comment by Alexays** [comment]
Fixed on master :)

**Comment by luispabon** [comment]
noyce :ok_hand: :+1:
