### ISSUE TITLE
Enable to choose Pulseaudio device

### ISSUE THREAD

**Issue by gordonzola** [Alexays/Waybar#559]
Hi.

I’m using the Pulseaudio module, but it randomly selects one of my audio devices. I’d like to specify a device in the module settings. Would this be possible?

Thanks

**Comment by daenney** [comment]
You should configure Pulse Audio to do that for you instead. You can start by [telling Pulse Audio to ignore certain devices](https://jamielinux.com/blog/tell-pulseaudio-to-ignore-a-usb-device-using-udev/) if you never want to use those. After that, you can set a default audio device using pavucontrol > Output Devices and click the green checkmark box next to what you want to be your default/fallback device.

**Comment by hypergig** [comment]
Maybe also use the custom module to display your current pa device.. this way you at least don't give your co-workers heart attacks when you press play... you may even be able to do a change device onclick if you are clever enough. Then please share that because I want that too :stuck_out_tongue:

**Comment by yiyunliu** [comment]
I have a use case where changing the default sink of pulseaudio isn't desirable. My fallback pulseaudio device is jack sink, whose volume is always set to 100%. Instead, I use pulseaudio to change the volume of the onboard soundcard of my laptop. This allows me to get a consistent volume for both jack and pulseaudio clients. In this scenario, jack sink is the default device but its volume doesn't really matter.
