### ISSUE TITLE
'date' tz_dep meson dependency

### ISSUE THREAD

**Issue by colemickens** [Alexays/Waybar#562]
What system package needs to be available for the `tz_dep` dependency that was recently added to meson.build? I can't seem to get Waybar building since it was added. Thanks.

**Comment by alebastr** [comment]
https://repology.org/project/howard-hinnant-date/versions
It's likely that there's no system package for your OS. You'll have to build it yourself or allow meson to download it from internet.

**Comment by colemickens** [comment]
Alright. Building it is easy, but packaging it will be harder since it doesn't seem to have or install any pkg-config files. The Nix build sandbox won't allow downloads at build time so packaging is my only recourse, so that I can update it for nixpkgs-wayland users.

Anyway, this answers the question - I'll patch in the pkg-config files and get it building again. Thanks!

**Comment by colemickens** [comment]
In case anyone wants to follow breadcrumbs: https://github.com/HowardHinnant/date/issues/537

**Comment by apiraino** [comment]
Would this be a blocker for releasing packaged version of Waybar?

**Comment by colemickens** [comment]
@apiraino I doubt it - might just add a small lag whenever this lands in a release and maintainers pull it (or maybe not if they let it download and build from the Waybar build). Anyway, I was able to get it packaged for Nix/NixOS fairly easily (already is for nixpkgs-wayland users). I'll submit it to Nix/NixOS and send a PR to the 'date' library as well so that it will install pkg-config files for all users, right now I'm patching it in in our build definition.

**Comment by apiraino** [comment]
Great, thank you! :+1:
