### ISSUE TITLE
clock module error "Timezone database not found at"...

### ISSUE THREAD

**Issue by lann** [Alexays/Waybar#566]
[2020-01-28 16:51:44.183] [warning] module clock: Disabling module "clock", Timezone database not found at "/home/lann/Downloads/tzdata"

**Comment by lann** [comment]
Seems likely due to #560

**Comment by lann** [comment]
Workaround:
```bash
$ cd ~/Downloads
$ mkdir tzdata
$ cd tzdata
$ wget https://data.iana.org/time-zones/releases/tzdata2019c.tar.gz
$ tar xf tzdata2019c.tar.gz
```

**Comment by varac** [comment]
I get the same issue. Workaround works!

**Comment by layus** [comment]
@mjec Any idea why this happens ?

**Comment by mjec** [comment]
It looks like this only happens if the `date` library is configured not to use system tzdb; see https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L3387-L3497.

By default Waybar should be using the system tzdb: https://github.com/Alexays/Waybar/blob/master/meson.build#L85.

@varac / @lann, what distribution are you running, and what steps did you take to compile or install Waybar?

**Comment by lann** [comment]
Looks like that option was set to false in my checkout for some reason (based on `strings` in the libtz object file). Deleting `build` and re-running meson fixed it.

**Comment by varac** [comment]
> @varac / @lann, what distribution are you running, and what steps did you take to compile or install Waybar?

I'm using ubuntu 19.10, sway version 1.4-f681d529 (Jan 22 2020, branch 'heads/1.4'), and compile waybar with

     meson --reconfigure build && ninja -C build && sudo ninja -C build install

**Comment by lann** [comment]
@varac I'm on 19.10 too. I suspect the issue is caused by some bit of build state that might not get reset by `--reconfigure`. I fixed it with the nuclear option (deleting `build/`).

**Comment by varac** [comment]
> @varac I'm on 19.10 too. I suspect the issue is caused by some bit of build state that might not get reset by `--reconfigure`. I fixed it with the nuclear option (deleting `build/`).

Thx @ianhattendorf I removed the build folder for now, will report back once I hit this again.
