### ISSUE TITLE
waybar-git AUR broken dependency on HowardHinnant/date

### ISSUE THREAD

**Issue by BlueGone** [Alexays/Waybar#567]
The commit https://github.com/Alexays/Waybar/commit/3130a57622ce173f43475487a9a5314694442f1b seem to introduce a broken dependency for the building of the AUR package [`waybar-git`](https://aur.archlinux.org/packages/waybar-git/). The broken dependency is described in [this comment on AUR](https://aur.archlinux.org/packages/waybar-git/#comment-726235).

The commit introducing the broken dependency seems to include a wrap file, so I don't know exactly why meson doesn't use it.
The meson config step also log this :
```
Run-time dependency date found: NO (tried pkgconfig and cmake)
Not looking for a fallback subproject for the dependency date because:
Use of fallbackdependencies is disabled.
```

**Comment by jomority** [comment]
This was already fixed in [this](https://aur.archlinux.org/cgit/aur.git/commit/?h=waybar-git&id=4e5d63bdeb532e34ec03e55be9adf78722a99e88) commit. You have to do a clean build.

You should report these kind of errors directly in the AUR (either with a comment, or flag a package as out-of-date).
