### ISSUE TITLE
Electron-based apps' tray icons aren't showing up

### ISSUE THREAD

**Issue by jeremejevs** [Alexays/Waybar#57]
Tested Slack, Caprine, Discord and Keybase, no tray icon. Tried with `XDG_CURRENT_DESKTOP=Unity`, as suggested in several places, to force AppIndicators, but that doesn't help.

Just in case, my setup is right, I can see Telegram's tray.

**Comment by Alexays** [comment]
I just saw that, I may have an idea why if I have time I'll do it tomorrow ;)

**Comment by Alexays** [comment]
I can't get the electron apps to use appindicator, if I use xembed-sni-proxy, they appear in the tray but it's buggy, XDG_CURRENT_DESKTOP no longer seems to work

**Comment by Alexays** [comment]
Ok got it working, i need to install libappindicator-gtk3
and launch eletron apps with `env XDG_CURRENT_DESKTOP=Unity slack`

**Comment by jeremejevs** [comment]
Thanks, [this has helped](https://aur.archlinux.org/cgit/aur.git/commit/?h=waybar-git&id=d7cc0ddd38f2fab6e10f68f459bda3a28b3ed712)!

![](https://i.imgur.com/1biwiH7.png)

**Comment by jeremejevs** [comment]
Hmm, launching Telegram crashes the bar now though :smile:

**Comment by Alexays** [comment]
Yep if telegram was launched with DG_CURRENT_DESKTOP=Unity it crashed.
I'll look

**Comment by jeremejevs** [comment]
Ah, indeed, `XDG_CURRENT_DESKTOP= telegram-desktop` works fine. Looks like setting it to `Unity` makes Telegram use AppIndicator instead of StatusIcon:

https://github.com/telegramdesktop/tdesktop/blob/c7a4d67cfb63af74f6da6ca35aea9ad08cf65588/Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp#L118-L121

**Comment by Alexays** [comment]
Now fixed on master @jeremejevs

**Comment by jeremejevs** [comment]
Can confirm, thanks again!
