### ISSUE TITLE
Custom module exec-if ignored

### ISSUE THREAD

**Issue by abmantis** [Alexays/Waybar#572]
I have a custom module which checks if Spotify is running. Randomly, it starts executing the music.sh script (and the icon starts showing up on Waybar), even if Spotify hasn't been opened. On that moment, if I do pgrep on the terminal, it outputs nothing. Also, restarting Waybar makes the icon go away and the script stops being executing. 
It seems that for some reason, Waybar ignores the exec-if after some time.

    "custom/spotify": {
        "format": "{icon}",
        "format-alt": "{icon} {}",
        "format-alt-click": "click-right",
        "interval": 10,
        "return-type": "json",
        "exec": "~/.config/waybar/modules/music.sh",
        "exec-if": "pgrep spotify",
        "escape": true,
        "on-click": "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause",        
        "format-icons": {
          "default": ""
        }
    }

**EDIT:** It starts misbehaving when I click some of the modules I have on the bar, such as the date/time, which opens gnome calendar or the network module, which runs "_gnome-terminal -- nmtui_".  Maybe an issue with opening gnome apps?

**Comment by varac** [comment]
@abmantis I'm interested in your `music.sh` script since I'd like to use a spotify/mpris module as well.
could you please share it ?

**Comment by abmantis** [comment]
@varac Sure. Here you go: https://github.com/abmantis/dotfiles/blob/master/sway/.config/waybar/modules/music.sh

**Comment by whtv** [comment]
`exec-if` doesn’t seem to work at all for me. The following code will show the output of `myscript`:
```
"custom/myscript": {
        "exec": "myscript",
        "exec-if": "false",
        "format": "{}"
}
```

**Comment by Alexays** [comment]
@whtv Your custom module ignore exec-if because you don't have an interval defined.
And so it's an continuous script.

**Comment by whtv** [comment]
Ah, I see. That makes sense I guess. So is `exec-if` also bound to `interval`? That is, run `exec-if` every `interval` and in case it succeeded run `exec`?

**Comment by Alexays** [comment]
Yep that's it!

**Comment by abmantis** [comment]
What about the reported issue? Still experiencing it.

**Comment by Alexays** [comment]
@abmantis can you check with the latest changes on master?

**Comment by abmantis** [comment]
@Alexays Still happens (on two different machines, one with Ubuntu 19.10 and the other with Arch). A few seconds after I click the network, for example, it starts running the music.sh script.

I changed the click action of the network module to "echo 'x'" and I'm able to reproduce the issue with that.

**Comment by RobinOpletal** [comment]
@whtv have you had success with this?

**Comment by X0rg** [comment]
Same issue here with a custom module:
```json
    "custom/backup": {
        "interval": 1,
        "format": "",
        "exec": "~/.config/waybar/backup.sh",
        "exec-if": "pgrep restic",
        "return-type": "json"
    }
```
Waybar shows the icon while `restic` is not running.
```shell
$ pgrep restic
$ echo $?
1
```

**Comment by abmantis** [comment]
The issue is probably due to pgrep matching the subprocess launched by waybar to run pgrep. .

**Comment by X0rg** [comment]
@abmantis Before the `pgrep restic`, I used `test $(systemctl is-active backup.service) = activating` and I had the same issue. :confused:

**Comment by Alexays** [comment]
Can you check with the latest commit 9b9d13ab0d90f16f6d64e7e9dc7394bf80121785?

**Comment by X0rg** [comment]
@Alexays It looks like you deleted your comment.  
About 9b9d13ab0d90f16f6d64e7e9dc7394bf80121785, it seems better, but a minor issue still remain for me: when `exec-if` condition is false, module partially appears (only style, without format) until `interval`.

**Comment by Alexays** [comment]
@X0rg Yep should be better with 2ffc96d0b2c7758729f6672b6075e583c5fe9839

**Comment by X0rg** [comment]
@Alexays Unfortunately, nope (Waybar v0.9.2-97-g49ae944 (May 24 2020, branch 'master')).

**Comment by Alexays** [comment]
@X0rg Can you check with the latest commit? 😃

**Comment by X0rg** [comment]
@Alexays LGTM with r102 (3b16946). :tada: 

@abmantis Can you confirm the fix for you?

**Comment by abmantis** [comment]
Seems to be fixed indeed! Thanks
