### ISSUE TITLE
Scroll calendar to prev/next month

### ISSUE THREAD

**Issue by skligys** [Alexays/Waybar#581]
I was thinking how I could see the previous/next months in the new calendar tooltip, and could not see a good way.
- One option is to always display 3 months (as in cal -3) but then the tooltip is huge.
- Awesome WM scrolls to previous month on left click and to next month on right click but that doesn't match left/right click actions in other modules.
- Mouse scroll up/down could scroll months but right now scrolling seems to be reserved to executing external executables.

Please advise!

**Comment by Alexays** [comment]
@maximbaz I'll go if possible by using https://developer.gnome.org/gtkmm/stable/classGtk_1_1Calendar.html
and replace the tooltip widget with the calendar one that can give an output like this:
![image](https://user-images.githubusercontent.com/13947260/79052128-8cc3b080-7c34-11ea-8bc3-c4456959e50f.png)
Using gtkmm you can IMO do something like this.
Get the tooltip window using:
```
auto window = label_. get_tooltip_window();
auto widget = window.get_child()
window.remove(widget); // In order to replace current widget
window.add(GtkCalendar);
```
I don't know if it's gonna work, but it's worth a try. 😄

**Comment by maximbaz** [comment]
Thanks for the input, this is an interesting idea!

(keeping a mind that I have very little C++ experience 😛) here's what I managed to investigate so far:

- most importantly, in `update()` method `label_.get_tooltip_window()` always returns null for me, I speculate that the window is only being created when the tooltip is actually being rendered on screen and `update()` is called before that
- trying to create a completely new window for the tooltip doesn't crash waybar, but then the tooltip simply doesn't show up at all:
  ```cpp
  auto gtkCalendar = Gtk::Calendar();
  auto gtkCalendarWindow = Gtk::Window();
  gtkCalendarWindow.add(gtkCalendar);
  gtkCalendar.show();
  label_.set_tooltip_window(gtkCalendarWindow);
  ```
- trying to find some examples of drawing this calendar I only found this reference: https://gitlab.gnome.org/GNOME/gnome-panel/-/blob/master/modules/clock/calendar-window.c#L1598

Any hints are very appreciated 🙂 

@skligys or anyone else, if you have some ideas, do feel free to jump in 😉

**Comment by Alexays** [comment]
@maximbaz You may need to use `set_has_tooltip(true)`, can you try?

**Comment by Alexays** [comment]
And try to set the tooltip on the event_box parent

**Comment by maximbaz** [comment]
Thanks! As far as I could see setting `set_has_tooltip(true)` on `label_`, `event_box_` or `event_box_.get_parent()` had no effect; `get_tooltip_window()` still returns null and `set_tooltip_window()` as in the snippet above still does nothing, nothing appears on hover.

**Comment by LukashonakV** [comment]
Hi @skligys , @maximbaz calendar scrolling is supported by the clock module. See [Clock WIKI](https://github.com/Alexays/Waybar/wiki/Module:-Clock) + there's open https://github.com/Alexays/Waybar/pull/2019 which implements of module action redefinition

**Comment by LukashonakV** [comment]
Hi @skligys , @maximbaz   #2019 is merge into the master.
So now your are able to redefine Clock actions on your wish. 
Please see: 
1. [Module actions config](https://github.com/Alexays/Waybar/wiki/Configuration#module-actions-config)
2. [Wiki clock](https://github.com/Alexays/Waybar/wiki/Module:-Clock)

If it's Ok for you , please close an issue.
Thank you

**Comment by skligys** [comment]
Yes, thank you very much for code changes.  I rebuilt waybar, and am using calendar with your changes.  Works very well for me.

Closing the bug.

**Comment by LukashonakV** [comment]
Hi @skligys  please close the issue then as an author. Thanks )
