### ISSUE TITLE
Default gateway as format replacement

### ISSUE THREAD

**Issue by mb720** [Alexays/Waybar#582]
Hi and thanks a lot for Waybar!

I'm really impressed with Waybar's ease of configuration! 👍
I was wondering whether there's a way to show the default gateway in the bar, the one you get with

    ip route show default | awk '{print $3}'

**Comment by Alexays** [comment]
Look at custom modules in the wiki ;)
https://github.com/Alexays/Waybar/wiki/Module:-Custom
