### ISSUE TITLE
Huge tray icons

### ISSUE THREAD

**Issue by xajler** [Alexays/Waybar#59]
Thanks for this great bar for `sway`, I really enjoy using it, much more than `polybar`...
I have problem with non electron apps showing in tray they are huge:

![waybar-02](https://user-images.githubusercontent.com/40003/47566031-ada62200-d92a-11e8-9778-eb79b7af3c78.png)

 Combined electron and normal tray icon:

![waybar-04](https://user-images.githubusercontent.com/40003/47566038-b26ad600-d92a-11e8-832d-e72e4e7c1a62.png)

Only electron tray icon:

![waybar-03](https://user-images.githubusercontent.com/40003/47566046-b8f94d80-d92a-11e8-9a30-24b6eeed9dec.png)

And full photo, using your latest [commit: 07d8dfb](https://github.com/Alexays/Waybar/commit/07d8dfb3d68b95d46641c57559a3baeb433d6c2c) with added tray space...

![waybar-01](https://user-images.githubusercontent.com/40003/47566127-ffe74300-d92a-11e8-9419-831c57eca4e2.png)

If you can do something with it, it would be great. I've used `nitrokey-app` and `lxqt-powermanagement` for normal tray icons.

And if you plan a `mpd` integration, not sure how much people use it, `polybar` was having it. Currently I've hacked it up to behave as it looked in `polybar`...

**Comment by xajler** [comment]
And both of them are QT apps, maybe there is something about QT and tray icons.

**Comment by Alexays** [comment]
it's okay it's fixed and as a bonus we can choose a size in the tray configuration 🎉

**Comment by xajler** [comment]
Great, thank you!
