### ISSUE TITLE
How to change position of tooltips?

### ISSUE THREAD

**Issue by JordanL2** [Alexays/Waybar#590]
I'm using the latest master from git, with gtk-layer-shell enabled. My bar is at the bottom. When I mouse over modules, the tooltip is placed roughly 50-100 pixels above the module. I'd prefer it to be closer to the module if possible, looking at the code I couldn't work out what determines this. I thought "margin-bottom" might be it, but that seems to have no effect. Is it possible to change where the layer shell tooltips are positioned?

**Comment by Alexays** [comment]
It's up to GTK, sorry :/

**Comment by gruvw** [comment]
Is there a way to achieve this?
