### ISSUE TITLE
What's the 'date' dependency in 0.9.1?

### ISSUE THREAD

**Issue by jubalh** [Alexays/Waybar#594]
With 0.9.1 I get:
```
[   23s] Run-time dependency date found: NO (tried pkgconfig and cmake)
[   23s] Looking for a fallback subproject for the dependency date
[   23s] 
[   23s] meson.build:85:0: ERROR: Git program not found.
```

What is 'date' actually? Not sure which package is meant by this. PKGCONFIG doesnt seem to know about it.

**Comment by bisco2** [comment]
Its this one: https://github.com/HowardHinnant/date

**Comment by jubalh** [comment]
Seems not packaged in Debian nor openSUSE. Also seems to be a header only library. Maybe you could add it to the repo as a fallback if it's not found on the system?

**Comment by bisco2** [comment]
> Seems not packaged in Debian nor openSUSE.

Yeah, I am already looking into packaging `date` for Debian, since I'm one of the `waybar` maintainers in Debian and we will need that for uploading a new `waybar` release ;)

> Maybe you could add it to the repo as a fallback if it's not found on the system?

I'm not a part of `waybar` upstream, but I think thats what `subprojects/date.wrap` is for.

**Comment by Alexays** [comment]
@bisco2 Yeah subprojects/date.wrap is the fallback, but it seems to use git.. so you'll need to install it.

**Comment by jubalh** [comment]
> Yeah subprojects/date.wrap is the fallback, but it seems to use git.. so you'll need to install it.

Unfortunately there won't be a network connection available in the buildroot.

**Comment by denisok** [comment]
> > Yeah subprojects/date.wrap is the fallback, but it seems to use git.. so you'll need to install it.
> 
> Unfortunately there won't be a network connection available in the buildroot.

I just did `meson subprojects download`, deleted everything except `date` there and repacked tar.gz.
Later I could just add script that would do that, that is usual thing for such kind of dependencies in OBS.
https://build.opensuse.org/request/show/788449

**Comment by denisok** [comment]
@MichaelAquilina ^ package for openSUSE on its way. you could install it from dev project if you want it earlier.

**Comment by jubalh** [comment]
I accepted https://build.opensuse.org/request/show/788449 and forwarded to Factory.

**Comment by Alexays** [comment]
I'm going to close this issue, but just out of curiosity, how did you solve the problem?

**Comment by jubalh** [comment]
We downloaded the date dependency with `meson subprojects download` and added it to our tarball. Which is pretty ugly :(

**Comment by kanyck** [comment]
I've the same issue on Gentoo. Waybar doesn't compile due to missing `date` dependency. This ought to be resolved somehow.

**Comment by kanyck** [comment]
UPD: I've found the package in overlays, so I was able to update. Actually, it's ebuild author who missed new dependency. From the other hand, it's strange that such a simple task did require such an exotic package to be fulfilled. That's a kludge. Hope you won't pull dbus next release...
Thanks!
