### ISSUE TITLE
RAM free/used

### ISSUE THREAD

**Issue by Alexays** [Alexays/Waybar#6]
![screenshot_2018-08-09-22 07 44](https://user-images.githubusercontent.com/13947260/43922994-b34bfc62-9c20-11e8-8ba7-bd3da145a07b.png)

@BlueGone You agree you have same problem on your computer ?

**Comment by Alexays** [comment]
```bash
free -h
              total        used        free      shared  buff/cache   available
Mem:           11Gi       2.0Gi       1.9Gi       346Mi       7.6Gi       8.9Gi
Swap:            0B          0B          0B
```
Ok this is coherent for me if i take only (used + buff)
But i have also 8.9Gi available we may use available rather than free no ?

**Comment by BlueGone** [comment]
Available is free+cache. We should take into account the cache memory as free memory to be accurate.

**Comment by Ranguvar** [comment]
Still aiming to consider cached as available in the future?
As-is, I just disable memory module.

**Comment by Alexays** [comment]
@Ranguvar I found out why the value is not correct, it's that we use the available memory to calculate the memory used which is not correct, we should probably use /proc/meminfo
