### ISSUE TITLE
Terminator doesn't startup

### ISSUE THREAD

**Issue by masm11** [Alexays/Waybar#600]
I have a config including:
```
    "custom/terminal": {
        "format": " Terminator",
        "on-click": "terminator",
        "tooltip": false
    },
```

I start waybar, and click the Terminator button, then terminator window opens.
However I click the icon the second time, then one doesn't open.

I traced in the terminator. It uses `os.uname()` of python, and it forks and executes
`uname -p`, `read()` from the process, and `wait()`s finishing of the process.
But the process already disappears, so can't `wait()`.

I think who is `wait()`ing, and it may be waybar, because waybar is anscestor of the `uname -p`.

Is there any posibility?

I'm using waybar 0.9.0 with wayfire 2d49da0 on archlinux.

**Comment by kepet19** [comment]
I just tried it on my machine, and there does not seem to be a problem, I used the same config as you and I uses sway. 1.4
waybar 0.8.0

maybe you can fixed it with is instead `"terminator & disown"`
```
    "custom/terminal": {
        "format": " Terminator",
        "on-click": "terminator & disown",
        "tooltip": false
    },
```

**Comment by FreeFull** [comment]
Alternatively, you could do something like `"on-click": "swaymsg exec terminator",`

**Comment by masm11** [comment]
Thank you.

Terminator runs successfully on the first click, but it doesn't on the second click.

Here is the error message:
```
Traceback (most recent call last):
  File "/usr/bin/terminator", line 114, in <module>
    TERMINATOR = Terminator()
  File "/usr/lib/python2.7/site-packages/terminatorlib/terminator.py", line 72, in __init__
    self.prepare_attributes()
  File "/usr/lib/python2.7/site-packages/terminatorlib/terminator.py", line 97, in prepare_attributes
    self.pid_cwd = get_pid_cwd()
  File "/usr/lib/python2.7/site-packages/terminatorlib/cwd.py", line 42, in get_pid_cwd
    system = platform.system()
  File "/usr/lib/python2.7/platform.py", line 1303, in system
    return uname()[0]
  File "/usr/lib/python2.7/platform.py", line 1270, in uname
    processor = _syscmd_uname('-p','')
  File "/usr/lib/python2.7/platform.py", line 1005, in _syscmd_uname
    rc = f.close()
IOError: [Errno 10] 子プロセスがありません
```
The last line is in Japanese. It means "No child processes".

`terminator & disown` doesn't help for me.

`swaymsg exec terminator` works on sway without this problems, but I don't use sway. I'm using wayfire, and swaymsg doesn't work on wayfire.

**Comment by masm11** [comment]
In `include/util/command.hpp`, there is this line:
```c
    signal(SIGCHLD,SIG_IGN);
```
While SIGCHLD is ignored, a child process which exited is automatically waitpid()'ed.

That is why:
1. I click the Terminator button.
2. forkExec() is called.
3. It forks.
4. If child, then executes terminator.
   This succeeds, because SIGCHLD is not ignored.
5. If parent, then does `signal(SIGCHLD, SIG_IGN)`
6. I click the Terminator button again.
7. forkExec() is called.
8. It forks.
9. If child, then executes terminator.
   This fails, because SIGCHLD is ignored.

Terminator forks, executes `uname`, and waitpid() it, but the waitpid() fails because SIGCHLD is ignored.

Could you insert a line as follows?
```c
  if (!pid) {
    setpgid(pid, pid);
    signal(SIGCHLD, SIG_DFL);                // this line.
    execl("/bin/sh", "sh", "-c", cmd.c_str(), (char*)0);
    exit(0);
  } else {
    signal(SIGCHLD,SIG_IGN);
  }
```

However, I don't know why that wasn't reproduced in kepet19's machine.

**Comment by Alexays** [comment]
Hey @masm11 thanks for debugging!
I wonder why SIG_DFL is needed...
Can you make a PR with the change?

**Comment by masm11** [comment]
I made a PR #636.

**Comment by masm11** [comment]
I confirmed that that problem was fixed. Thanks.
