### ISSUE TITLE
Identify output by model and serial

### ISSUE THREAD

**Issue by Gigadoc2** [Alexays/Waybar#602]
Currently it seems only possible to match against "connector names" like `DP-3` and such.
It would be a nice addition when one could match with the full name and serial number, like for example in Sway: `Goldstar Company Ltd IPS235 Serial Number` (and yes, that model as "Serial Number" for a serial number :man_facepalming:).

That would be helpful in case of unreliable "connector names" (they might change on every boot for example), or when the same connector is sometimes used for different purposes.

**Comment by Soundtoxin** [comment]
big +1 for this, when I undock my laptop it sometimes relabels my outputs which totally breaks waybar. I refer to outputs by model and serial in my sway config, but waybar doesn't support this, so I have to edit my config each time they change it seems.
