### ISSUE TITLE
pulseaudio module only detects new default device after volume change

### ISSUE THREAD

**Issue by siwyd** [Alexays/Waybar#605]
I have a small script I use to quickly switch between output devices. Basically, it sets a new default device and moves all of the sink-inputs to the new sink. I've noticed that Waybar doesn't pick up the change of default device (reproducible when using Pulsemixer or something like that to pick a default device).

Waybar only seems to pick up on the new device when the volume is changed on it. So right now I have this hacky workaround in my script to have Waybar pick up the change:
```
ponymix increase 1
ponymix decrease 1
```

Would it be possible to have the module pick up the change in device without any volume changes?

**Comment by mssdvd** [comment]
[i3blocks -contrib's module volume-pulseaudio](https://github.com/vivien/i3blocks-contrib/tree/master/volume-pulseaudio) has cool features like changing the default output and muting the volume.

**Comment by nolanl** [comment]
I have this problem as well, using pipewire's pulse compability. waybar 0.9.17 from Debian 12. Even changing the volume didn't fix it for me, I had to restart waybar for it to detect the change in output.

**Comment by xlucn** [comment]
Having this as well. Really hope this could be worked on.

What I observe:
- Sometimes the pulseaudio module can't pick up the change of current device (usually when I connect/disconnect a bluetooth earphone) at all.
- The volume change by scrolling on the module actually changes the device that the module shows at the time, not the actually used one.
- Wireplumber module detects the change successfully.
- Switch default devices back-and-forth in `pavucontrol`, and the module probably will detect it after that. Any reason device connection does not trigger the module to update?
