### ISSUE TITLE
Leading Zeros in Clock Module

### ISSUE THREAD

**Issue by smsegal** [Alexays/Waybar#607]
I've just updated to the latest release on the AUR, and my previous time format string has stopped working. 
I was previously using `"{:%l:%M %p}"` which would give e.g 1:55 PM without leading zeros. 
Looking at the reference linked on the wiki, I see the particular library you are using does not have the `%l` format string. This wouldn't be an issue, as that same page says you can use `%NI` to get a 12 hour clock with _N_ leading zeros.
However, trying to set N=0 (or any other number) results in the format string parsing incorrectly and showing up in the bar as the literal string %0I in my clock module. 
Here is the actual format string I'm trying to use for reference. 
```
  "clock": {
    "format": "{:%0I:%M %p}",
    "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
    "format-alt": "{:%Y-%m-%d}"
  }
```

Thanks for the great work on Waybar so far.

**Comment by Alexays** [comment]
Fixed with #715 unless timezone is specified.
While waiting for a [HowardHinnant/date](https://github.com/HowardHinnant/date) update.
