### ISSUE TITLE
Sway workspaces: custom order

### ISSUE THREAD

**Issue by Sweenu** [Alexays/Waybar#608]
My workspaces are not numbered but named like so:
`a s d f u i o p music telegram`

I wish there was a way to have them always sorted like so in the sway-workspaces module.

I looked into using the `number` argument of the sway `workspace` command, but this does not do the trick as it creates workspaces whose numbers are in the name.
For example, if I do:
```bash
swaymsg workspace 2 s
```
It does create a workspace with the number 2 assigned to it but names it "2 s" which is not what I am looking for.

A solution would be to implement an option similar to the swaybar's `strip_workspaces_number` option.

Linked to: https://github.com/swaywm/sway/issues/5051

**Comment by Alexays** [comment]
Documentation is now updated, {name} refer to the stripped value and {value} the unchanged given by sway, it's ok?

**Comment by Sweenu** [comment]
That's perfect, thank you!
