### ISSUE TITLE
[0.9.1]: Waybar overlaps with windows

### ISSUE THREAD

**Issue by daenney** [Alexays/Waybar#609]
This appears to have broken for me in 0.9.1, but now Waybar doesn't seem to "take up" space on my screen. I have the bar at the top in Sway, and any application I now launch ends up with its header area underneath Waybar if the layer is set to top, and over Waybar if the layer is set to bottom (i.e non-accessible at all in the last case). Before 0.9.1 applications would be docked underneath Waybar, ensuring that the bar was always visible at the top of my screen and essentially pushed windows down a bit, for the height of the bar.

This is happening on Arch Linux for me since 0.9.1 was pushed 3 days ago. The only notable difference I can see on the packaging side is that now it's built with gtk-layer-shell: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/waybar&id=ed3ad45e65f88aede0cf8d8f729f5f8c23ccac28

**Comment by daenney** [comment]
In case it matters, I have an explicit `height` set in my config, of 26.

**Comment by daenney** [comment]
Setting `"gtk-layer-shell": false` in my config restores the old behaviour, but it seems useful to be able to use GTK layer shell.

This begs the question though, how do I configure this to behave correctly with `"gtk-layer-shell": true` instead?

**Comment by alebastr** [comment]
@daenney, is there a `width` in your config? Can you try removing it?

**Comment by daenney** [comment]
Removing the width does indeed restore the old behaviour. This is very surprising to me, I would never have connected the two.
