### ISSUE TITLE
Udiskie doesn't show in tray

### ISSUE THREAD

**Issue by robertjk** [Alexays/Waybar#616]
Running `udiskie` should show a tray icon. It always worked for me on i3. Since I switched to sway no tray icon is displayed. There already is [an issue about it](https://github.com/coldfix/udiskie/issues/199) in udiskie repository, but the maintainer doesn't know how to solve it. Nor do I. Maybe you guys understand it better and can identify the issue.

My setup:
- Arch Linux
- Sway 1.4
- Waybar 0.9.1

**Comment by soyuka** [comment]
Use 
```
exec udiskie --appindicator -t
```

Make sure you installed `libappindicator-gtk3`

**Comment by robertjk** [comment]
I did that and there are still some issues. See screenshots here: https://github.com/coldfix/udiskie/issues/199#issuecomment-598814096.

**Comment by Alexays** [comment]
I'm closing this ticket as the problem doesn't come directly from Waybar.
Hoping that udisk's dev will find a solution.
