### ISSUE TITLE
Way to apply margin to icons in workspace names

### ISSUE THREAD

**Issue by robertjk** [Alexays/Waybar#619]
## Problem

[sway/workspaces](https://github.com/Alexays/Waybar/wiki/Module:-Sway#workspaces) allows to set icons for each workspace. How can I apply margins to those icons in `style.css`?

## Spaces not enough

I know I can use spaces to add some whitespace, but that's not a very precise control over spacing. In my case one space is too less, two spaces are too much and I'd like something in between.

## Impossible selector

The best solution would be control the spacing using CSS margins with pixel units. The problem is I cannot figure out what selector I should use to target the icon.

I tried having this in `~/.config/waybar/config`:

```
"sway/workspaces": {
    (...)
    "format": "<span>{icon}<span> {name}",
    (...)
},
```

And then applying those styles in `~/.config/waybar/style.css`:

```css
#workspaces button span {
    margin-right: <some-value>;
}
```

But it doesn't work.

**Comment by Alexays** [comment]
Dups of #527
I'll work on it as soon as i can

**Comment by broskees** [comment]
This doesn't work for me either. This is closed as completed, is it not going to be implemented or should this work?
