### ISSUE TITLE
Muting bluetooth headphones doesn't change symbol

### ISSUE THREAD

**Issue by hassec** [Alexays/Waybar#620]
I notice this happening on waybar-git from the AUR .
Once my headphones are connected I correctly see the headphones symbol with the volume, but when I mute it via the pavucontrol window or pactl, the icon does not switch to the muted icon...

**Comment by Alexays** [comment]
Do you have `format-bluetooth-muted`?
I will add that if `format-bluetooth-muted` doesn't exist, it uses `format-muted`

**Comment by Alexays** [comment]
Should be good with 9acf5587fa2e7d3575b06682a8b8d936a995e861
