### ISSUE TITLE
Nerd Font icons that are really Arabic symbols makes text render backwards

### ISSUE THREAD

**Issue by haval0** [Alexays/Waybar#628]
I am using Nerd Font for icons for my Sway workspaces. Two of these icons, notably ﭮ and ﭮ, are based on Arabic symbols. This makes the entire description render backwards for these workspaces, so it becomes "{icon} :{name}" instead of "{name}: {icon}". For example it renders as "{discord icon} :9" instead of "9: {discord icon}". I'm guessing it is rendered backwards because Arabic is supposed to be rendered backwards. There should be some way to escape this way of rendering Arabic and make it render like normal Latin text instead.

**Comment by rdbo** [comment]
I'm getting the same issue with the cut-off headphone symbol as well: "ﳌ", not really sure why
