### ISSUE TITLE
Battery consumption

### ISSUE THREAD

**Issue by WhyNotHugo** [Alexays/Waybar#633]
Hi! I'm moved to waybar from `i3pystatus`, and something I'm missing is the ability to show the battery consumption (eg: discharging at 9.0W, or recharging at 17.8W, etc).

Might this be possible to add to the Battery module's formatting options? Thanks!

**Comment by biiiep** [comment]
i really miss this feature too ;) 

Is there a way to set this up yet?

**Comment by HarHarLinks** [comment]
At least "Power draw in watts" exists: https://github.com/Alexays/Waybar/wiki/Module:-Battery#format-replacements

**Comment by ajgae** [comment]
Shouldn't this be closed? It seems that the `{power}` format replacement does exactly that

**Comment by WhyNotHugo** [comment]
Indeed, `{power}` works fine.
