### ISSUE TITLE
Modules not aligned

### ISSUE THREAD

**Issue by tugurio** [Alexays/Waybar#638]
I've been using Waybar for some months now and I still have a problem that I am not able to fix.
There are some modules which have text slightly above the other ones. It is visible in the image. They are: PulseAudio, Memory, Disk and Clock
Is it just or are someone else experiencing this?
https://ibb.co/3RczL9p

**Comment by LaserEyess** [comment]
I am experiencing this as well, it's manifesting when I change the locale of the clock module. 

With `locale: "ja_JP.UTF-8",`: https://0x0.st/ipM7.png
With that line commented: https://0x0.st/ipMF.png

There are slight alignment issues with other modules but it's extremely obvious with a Japanese locale.
