### ISSUE TITLE
equivalent of sway's 'include' directive

### ISSUE THREAD

**Issue by kermorgant** [Alexays/Waybar#639]
Hi,

I store my sway config in a git repository and reuse across multiple machines.

I'm using sway's `include` directive to deal with the small differences between setups 

`include ~/.config/sway/`hostname`/*`

Not sure how to achieve something similar with waybar. I feel I should create as many different configs as needed, and  then create appropriate symlinks depending on which machine I'm on.

Could one improvement be to allow an argument to specify a filename doing something like this ?

```
bar {
    swaybar_command waybar ~/path/to/custom_config
}
```

PS: thanks a lot for this bar, just started using it and it feels like a great addition to my setup !

**Comment by Alexays** [comment]
Hi!
You can already pass config file to waybar using -c arg.
```
waybar -c ~/path/to/custom_config
```
waybar --help for more information

**Comment by kermorgant** [comment]
thanks! 
For some reason, it only works when using exec (and in that case, sway reloading had no effect on waybar)

So the following won't work :
```
bar {
    swaybar_command waybar -c ~/path/to/custom_config
}
```

not a big issue anyway

**Comment by Alexays** [comment]
You may need to quote the cmd.
e.g. 
```
bar {
    swaybar_command "waybar -c ~/path/to/custom_config"
}
```

**Comment by kermorgant** [comment]
> bar {
>     swaybar_command "waybar -c ~/path/to/custom_config"
> }

Tried it, didn't work

**Comment by Alexays** [comment]
And with an absolute path to config?

**Comment by johannesneyer** [comment]
It would still be nice to have something like sways "include". I have the same problem and I think putting the non-common parts in extra files is much nicer than having nearly the same file for each machine with only slightly differences.

**Comment by mmonaco** [comment]
I opened swaywm/sway#5724 about the ability to pass args to swaybg_command.

However, IMO waybar is really lacking here. Everywhere else that I tend to have machine-specific config, the bulk of the config is generic and is in dotfiles. The small bits of machine/host-specific config is able to be include in ".d" directories, include *.config, etc. The options for waybar feel clunky: custom startup/wrapper scripts to generate json/css, use a templating engine, store whole configs for each host separately (and resolve the above FR).

Sure, we can take the stance that waybar shouldn't need to do anything here, but I think it would really help to provide a nice out-of-the-box experience for users. **Especially** since I believe the difficulty here is largely caused by the design choice to use raw json and css for configuration.

**Comment by cmprmsd** [comment]
Hey! Is this a waybar or sway issue? 
I cannot pass --config and --style.
* `/home/user/path` won't work
* `$HOME/path` won't work
* `~/path` won't work

**Comment by albsch** [comment]
Anyone stumbling here: Waybar supports the include directive now:
https://github.com/Alexays/Waybar/wiki/Configuration

**Comment by hboetes** [comment]
```
# Start bar to display a workspace bar                                                                                                                                        
# bug: https://github.com/swaywm/sway/issues/5724                                                                                                                             
# bar {                                                                                                                                                                       
#     swaybar_command waybar                                                                                                                                                  
# }                                                                                                                                                                           
# Workaround                                                                                                                                                                  
exec_always --no-startup-id pkill waybar; waybar -c ~/.config/waybar/sway
```

**Comment by IIlllllII** [comment]
> ```
> # Start bar to display a workspace bar                                                                                                                                        
> # bug: https://github.com/swaywm/sway/issues/5724                                                                                                                             
> # bar {                                                                                                                                                                       
> #     swaybar_command waybar                                                                                                                                                  
> # }                                                                                                                                                                           
> # Workaround                                                                                                                                                                  
> exec_always --no-startup-id pkill waybar; waybar -c ~/.config/waybar/sway
> ```

Are the two commands exactly equivalent?
By the way, I think it's only an issue with Sway.

**Comment by viktorsmari** [comment]
I have the same issue. Is it not possible to use args with the `swaybar_command`?

```bash
bar {
  swaybar_command waybar # this works without issues

  # this does NOT work
  swaybar_command waybar -c /home/viktor/dotfiles/waybar/.config/waybar/config.jsonc -s /home/viktor/dotfiles/waybar/.config/waybar/style.css
```
 
```bash
# this works fine when called directly in a terminal, just not inside the config
waybar -c /home/viktor/dotfiles/waybar/.config/waybar/config.jsonc -s /home/viktor/dotfiles/waybar/.config/waybar/style.css
```
