### ISSUE TITLE
mediaplayer.py prevents waybar as a systemd user service from stopping on shutdown

### ISSUE THREAD

**Issue by Androide7461** [Alexays/Waybar#640]
This is my journalctl output for the shutdown process: 
[waybar_journalctl.txt](https://github.com/Alexays/Waybar/files/4411460/waybar_journalctl.txt)

I configured my waybar service exactly as stated here https://github.com/swaywm/sway/wiki/Systemd-integration

(I hope this is the right place to open this issue. I am sorry in advance if it was the wrong place.)

**Comment by Androide7461** [comment]
After some playing around with my config, I am pretty sure now that mediaplayer.py causes this problem. So I think that there is a bug in mediaplayer.py.

**Comment by Alexays** [comment]
Should be fixed with waybar latest versions
