### ISSUE TITLE
Completely invisible under GTK 3.24.17

### ISSUE THREAD

**Issue by p4block** [Alexays/Waybar#642]
It just dropped in arch testing and with it installed, waybar is completely invisible and doesn't even take up space in sway. 

Nothing in the logs appears different. It also tells me the loglevel option doesn't exist.

Tried on both my dotfiles and a fresh sway session on a new user.

**Comment by nwg-piotr** [comment]
Same here (already on stable). Latest updates:

```
gtk-update-icon-cache (1:3.24.16-1 -> 1:3.24.17-1)
gtk3 (1:3.24.16-1 -> 1:3.24.17-1)
```

**Comment by rhysperry111** [comment]
Same here. Issue also happening with `wofi`

**Comment by dschrempf** [comment]
Downgrade to gtk3 3.24.16 makes the bar reappear.

**Comment by michaelnew** [comment]
[wofi](https://hg.sr.ht/~scoopta/wofi) no longer appears either, FWIW.

**Comment by alebastr** [comment]
Reported as https://gitlab.gnome.org/GNOME/gtk/-/issues/2572.
Should be a trivial fix, if I understand the breaking commits correctly.

**Comment by ReekyMarko** [comment]
This is already fixed and merged upstream. Nothing can be done at this end, so this should be closed.

**Comment by Alexays** [comment]
Hopefully it'll be deployed soon.
