### ISSUE TITLE
Waybar no longer appers after Arch update

### ISSUE THREAD

**Issue by CodeGradox** [Alexays/Waybar#643]
Today I ran a system update on Arch and restarted the machine. When I logged back in the waybar was no longer visible. I have no clue which of the updates did this, but I don't think I saw sway or waybar among the updates. I updated my packages on my laptop and the same thing happened.

Waybar itself does not seem to crash. I've tried to start waybar from the console with `--log_level trace` but it does not print any errors.
```
[~] $ waybar --log-level trace
[2020-04-03 23:24:23.563] [info] Resources files: /home/magnus/.config/waybar/config, /home/magnus/.config/waybar/style.css
Unknown option --log-level
[2020-04-03 23:24:23.566] [debug] Output detected: HDMI-A-1 (Unknown U3277WB)
[2020-04-03 23:24:23.569] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
```

My style and config files as per now.
https://gist.github.com/CodeGradox/4fee8406a676c9b2fcd745bc4c21e633

I'm running Linux version 5.4.30-1-lts with Waybar version v0.9.1

**Comment by CodeGradox** [comment]
Must be related to https://github.com/Alexays/Waybar/issues/642.

**Comment by dschrempf** [comment]
Same here, I thought I am going mad here ...

**Comment by iatone93** [comment]
> Same here, I thought I am going mad here ...

:D me too

**Comment by Alexays** [comment]
Dups of #642
