### ISSUE TITLE
workspace 10 in wrong order

### ISSUE THREAD

**Issue by iatone93** [Alexays/Waybar#644]
![sway_noelle](https://user-images.githubusercontent.com/47673987/78411602-77390000-7610-11ea-9a51-c9706c10fdbd.png)

When using "persistent_workspaces" in waybar config workspace "10" appears between "1" and "2". Workspaces "5"-"9" are ordered as intended.

"sway/workspaces": {
       "persistent_workspaces": {
           "1": [],
           "2": [],
           "3": [],
           "4": []
       }, 
        "format-default": "{name}",
        "format": "{icon}",
        "format-icons": {
            "1": "",
            "2": "",
            "3": "",
            "4": ""
            //"urgent": "",
            //"focused": "",
            //"default": ""
        },
       "disable-scroll": true,
       "all-outputs": false
    },

**Comment by Alexays** [comment]
Dups of #482
