### ISSUE TITLE
Stopped showing up

### ISSUE THREAD

**Issue by Begggs** [Alexays/Waybar#648]
I'm using Arch Linux with Sway and all packages are up-to-date. Yesterday all worked fine, but now Waybar stopped showing up even if launching it manually. I tried to rename my config files, so Waybar used default ones, but it didn't help. The command line output is something like:
`[2020-04-05 00:19:20.046] [info] Resources files: /home/begs/.config/waybar/config, /home/begs/.config/waybar/style.css
[2020-04-05 00:19:20.060] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity`
and it always been this

**Comment by jwinnie** [comment]
Yes, me too! Arch Linux, all packages up to date.

Output of `waybar -l debug`:

```
[2020-04-04 14:28:24.833] [info] Resources files: /home/jwinnie/.config/waybar/config, /home/jwinnie/.config/waybar/style.css
Unknown option -l
[2020-04-04 14:28:24.836] [debug] Output detected: HDMI-A-1 (Dell Inc. DELL U2715H)
```

And then nothing shows up. The waybar process keeps running without errors, though.

**Comment by jwinnie** [comment]
Maybe it has something to do with another package/dependency being updated? I can't find anything that might break waybar in the recent updates list, though... https://www.archlinux.org/packages/?sort=-last_update

**Comment by scrufulufugus** [comment]
gtk3 is the culprit. I downgraded it to 3.24.16-1 and it solved the issue.

**Comment by jwinnie** [comment]
So a GTK3 point release is a breaking change? That's pretty bad design...

**Comment by hpidcock** [comment]
Breaking GTK3 commit is https://gitlab.gnome.org/GNOME/gtk/-/commit/7f12dc2b66bba15b2e1c0ca077fa4ae58962ec0f

**Comment by nathanblair** [comment]
I can report the same experience on Void. I'm trying to check my update logs now to see but I too believe the culprit to be a gtk3 package upgrade. Going to try to roll back to 3.24.16

**Comment by Alexays** [comment]
Yep dups of #645
