### ISSUE TITLE
Feature request: keyboard layout

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#66]
Would be really nice to have the module showing current keyboard layout. Or maybe a help to write the custom module script with this capability.

**Comment by harishkrupo** [comment]
Create a custom module with something like this in a script and run it in the exec: ?
`setxkbmap -query | grep layout | cut -f2 -d":" | tr -d '[:space:]'`

**Comment by eternal-sorrow** [comment]
@harishkrupo it doesn't work. It always shows `us` (my default layout) even when I use another layout.

**Comment by harishkrupo** [comment]
okay, will need to check. How do you pick a different layout?

**Comment by jeremejevs** [comment]
@harishkrupo If you're using Sway: https://github.com/swaywm/sway/wiki#input-configuration

**Comment by rvi64** [comment]
if somebody needs it:

    "custom/lang": {
        "exec": "swaymsg -t get_inputs|grep -4 'AT T'|tail -1|sed 's/.*: //;s/\"//g'|cut -c 1-2|tr '[a-z]' '[A-Z]'",
        "interval": 1
    },

- Note: `grep -4 'AT T'` finds my particular keyboard, you probably want to change values in the script

this polls it every second, but ideally it should work as in pulseaudio module, to update whenever layout updates.
for that it needs some integration with wlroots/sway or something, and values like `"name": "AT T"` to identify which exact keyboard to use

**Comment by harishkrupo** [comment]
@rvi64 Thanks!
Similar suggestions here: 
- https://github.com/Alexays/Waybar/pull/85#issuecomment-438534936
- https://github.com/Alexays/Waybar/pull/85#issuecomment-440228399

There is an ongoing work to create a new protocol to get this information. See [here](https://github.com/Alexays/Waybar/pull/85#issuecomment-440228399)
Unfortunately, I got busy with some other work . :( 
I will try to start work on this again.

**Comment by rvi64** [comment]
here's a version without jq, only unix utils, shows EN by default, and first two upper case letters otherwise
```
  "custom/lang": {
    "exec": "swaymsg -t get_inputs | grep layout_name | grep -v En | awk 'END{if(NR == 0){print \"EN\"}else{print toupper(substr($2,2,2))}}'",
    "interval": 1,
    "format": "{} "
  },

```

**Comment by krtko1** [comment]
here's a another version with only unix utils, shows proper language name two letters shortcut 

.config/waybar/modules/layout.sh
```
#!/bin/bash
  
KEYBOARD=$(swaymsg -pt get_config | awk '{if ($1 == "input") {name=$2}; if($1 == "xkb_layout") {print name; exit}}')

ACTIVE_LANGUAGE=$(swaymsg -t get_inputs | grep -5 $KEYBOARD | tail -1 | sed 's/.*"\(.*\)".*$/\1/gi')

zcat `man --where xkeyboard-config` | awk -F'[\t(]' -v var="$ACTIVE_LANGUAGE" 'index($0,var)>=1 {print $1; exit}'
```

.config/waybar/config
```
    "custom/layout": {
        "exec": "~/.config/waybar/modules/layout.sh",
        "interval": 1,
        "format": "{} "
    }
```

**Comment by eternal-sorrow** [comment]
> gzip: skipping: /usr/share/man/man7/xkeyboard-config.7.bz2 unrecognized format
You assume that man page is compressed with gzip.

Also, don't you think, parsing man isn't the right way to do this? The right way is parsing /usr/share/X11/xkb/rules/evdev.xml I guess.

**Comment by krtko1** [comment]
@eternal-sorrow 
EDIT2: I change to script to not start every time

.config/waybar/modules/layout.sh
```
#!/bin/bash
  
KEYBOARD=$(swaymsg -pt get_config | awk '{if ($1 == "input") {name=$2}; if($1 == "xkb_layout") {print name; exit}}')

MANPAGE=$(man --where xkeyboard-config)
case `file -bi $MANPAGE | grep -o "^[^/]*/[^;]*"` in
    'application/x-gzip') CAT='zcat';;
    'application/x-bzip2') CAT='bzcat';;
    'application/x-tar') CAT='tar -O -xf';;
    'application/x-xz') CAT='xzcat';;
    'text/plain') CAT='cat';;
esac

while true; do
    ACTIVE_LANGUAGE=$(swaymsg -t get_inputs | grep -5 $KEYBOARD | tail -1 | sed 's/.*"\(.*\)".*$/\1/gi')
    $CAT $MANPAGE | awk -F'[\t(]' -v var="$ACTIVE_LANGUAGE" 'index($0,var)>=1 {print $1; exit}'

    sleep 1
done
```
.config/waybar/config
```
    "custom/layout": {
        "exec": "~/.config/waybar/modules/layout.sh", // DO NOT RUN multiple times
        "format": "{} "
    }
```

**Comment by eternal-sorrow** [comment]
Here's my python version. You'll need the latest git version of [acrisci/i3ipc-python](https://github.com/acrisci/i3ipc-python) installed.
Set `KBD_NAME` to the name of your keyboard device (see `swaymsg -t get_inputs`).
```python
#!/usr/bin/env -S python3 -u

import time
import i3ipc

KBD_NAME = "1:1:AT_Translated_Set_2_keyboard"

sway = i3ipc.Connection()

while True:
	inputs = sway.get_inputs()
	keyboard = [i for i in inputs if i['identifier'] == KBD_NAME][0]
	layout = keyboard['xkb_active_layout_name']
	print(layout[:2].lower())
	time.sleep(1)
```

**Comment by vyachkonovalov** [comment]
We can get updates from `swaymsg -mrt subscribe` (no "interval" setting needed) https://github.com/Alexays/Waybar/pull/85#issuecomment-560100037

**Comment by exdeniz** [comment]
> Here's my python version. You'll need the latest git version of [acrisci/i3ipc-python](https://github.com/acrisci/i3ipc-python) installed.
> Set `KBD_NAME` to the name of your keyboard device (see `swaymsg -t get_inputs`).
> 
> ```python
> #!/usr/bin/env -S python3 -u
> 
> import time
> import i3ipc
> 
> KBD_NAME = "1:1:AT_Translated_Set_2_keyboard"
> 
> sway = i3ipc.Connection()
> 
> while True:
> 	inputs = sway.get_inputs()
> 	keyboard = [i for i in inputs if i['identifier'] == KBD_NAME][0]
> 	layout = keyboard['xkb_active_layout_name']
> 	print(layout[:2].lower())
> 	time.sleep(1)
> ```

Not work for me.
```
print inputs [<i3ipc.replies.InputReply object at 0x7f988d156dc0>, <i3ipc.replies.InputReply object at 0x7f988d1379d0>, <i3ipc.replies.InputReply object at 0x7f988d137b50>, <i3ipc.replies.InputReply object at 0x7f988cfc0910>, <i3ipc.replies.InputReply object at 0x7f988cd69d60>, <i3ipc.replies.InputReply object at 0x7f988cd69dc0>, <i3ipc.replies.InputReply object at 0x7f988cd69e20>, <i3ipc.replies.InputReply object at 0x7f988cd69e50>, <i3ipc.replies.InputReply object at 0x7f988cd69e80>, <i3ipc.replies.InputReply object at 0x7f988cd69eb0>]
Traceback (most recent call last):
  File "./layout.py", line 13, in <module>
    keyboard = [i for i in inputs if i['identifier'] == KBD_NAME][0]
  File "./layout.py", line 13, in <listcomp>
    keyboard = [i for i in inputs if i['identifier'] == KBD_NAME][0]
TypeError: 'InputReply' object is not subscriptable
```

**Comment by eternal-sorrow** [comment]
This version is very outdated. It uses polling and old i3ipc API. Use that one https://github.com/Alexays/Waybar/pull/85#issuecomment-526235072 or one of other from that thread.

**Comment by Hexawolf** [comment]
Sway now has `subscribe` message type. Here is my waybar config entry that prints current layout:

```
"custom/layout": {
    "tooltip": false,
    "exec": "swaymsg -mrt subscribe '[\"input\"]' | jq -r --unbuffered \"select(.change == \\\"xkb_layout\\\") | .input | select(.identifier == \\\"1:1:AT_Translated_Set_2_keyboard\\\" and .type == \\\"keyboard\\\") | .xkb_active_layout_name | .[0:2] | ascii_upcase\""
},
```

**However:**

- When killed, waybar disowns `sh` process and it keeps running until you kill `swaymsg -mrt subscribe ["input"]` process.
- Notice that `"1:1:AT_Translated_Set_2_keyboard"` - it seems that keyboard identification is a fundamental problem to wayland protocol. There seems to be no reliable way to differentiate between a real keyboard and "keyboards" that are actually power buttons and other special buttons.
- Remember to install `jq`

**Comment by krtko1** [comment]
@Hexawolf I created pull request with waybar module which shows keyboard layout. Yes it still use `1:1:AT_Translated_Set_2_keyboard` but it can show short layout names from `/usr/share/X11/xkb/rules/evdev.xml`.

**Comment by Hexawolf** [comment]
One might want to use a more generic version while pull request is still not merged:

```json
"custom/layout": {
    "tooltip": false,
    "exec": "swaymsg -mrt subscribe '[\"input\"]' | jq -r --unbuffered \"select(.change == \\\"xkb_lay
out\\\") | .input | select(.type == \\\"keyboard\\\") | .xkb_active_layout_name | .[0:2] | ascii_upcase\""
}
```

**Comment by donnex** [comment]
I just built a little bit on the previous answers and uses the following to show flags for layouts in waybar.

```
"custom/keyboard_layout": {
    "exec": "waybar_sway_keyboard_layout",
    "tooltip": false
}
```

waybar_sway_keyboard_layout
```
#!/bin/sh

DEFAULT_LAYOUT="English (US)"

# Kill old instances since waybar don't kill them when exited
[ "$(pgrep -a 'swaymsg' | grep -c '["input"]')" -gt 0 ] &&
  pgrep -a 'swaymsg' | grep '["input"]' | cut -d ' ' -f1 | xargs -r kill

# Sleep for a short while in order to prevent startup issues in waybar
sleep 0.5

keyboard_flag() {
  while read -r layout; do
    if [ "$layout" = "English (US)" ]; then
      layout_waybar="🇺🇸"
    elif [ "$layout" = "Swedish" ]; then
      layout_waybar="🇸🇪"
    else
      layout_waybar="$layout"
    fi

    printf '%s\n' "$layout_waybar"
  done
}

echo "$DEFAULT_LAYOUT" | keyboard_flag
swaymsg -mrt subscribe '["input"]' | jq -r --unbuffered "select(.change == \"xkb_layout\") | .input | select(.type == \"keyboard\") | .xkb_active_layout_name" | keyboard_flag
```

**Comment by Hexawolf** [comment]
I made a simple C program for displaying layouts using sway IPC subscription:
https://github.com/Hexawolf/swaylay

**Comment by BlueGone** [comment]
#659 should solve this.

**Comment by asahaf** [comment]
I've a custom python script to get the layout using i3ipc library (python-i3ipc). it subscribes to input changes to get notified when the layout changes without the need to poll in a loop.

```
#!/usr/bin/env -S python3 -u
# vi:syntax=python


import os
import signal

import i3ipc

pri_layout_code = "EN"
sec_layout_code = "AR"
sec_layout_name = "arabic"
input_event_change = "xkb_layout"

sway_sock_path = os.environ["SWAYSOCK"]
sway = i3ipc.Connection(socket_path=sway_sock_path, auto_reconnect=False)


def on_posix_signal(sig, frame):
    sway.main_quit()


signal.signal(signal.SIGHUP, on_posix_signal)
signal.signal(signal.SIGINT, on_posix_signal)
signal.signal(signal.SIGQUIT, on_posix_signal)
signal.signal(signal.SIGTERM, on_posix_signal)

# print the primary layout as it's the default
print(pri_layout_code)


def on_input_change(conn, event):
    if event.change != input_event_change:
        return
    if event.input.xkb_active_layout_name.lower() == sec_layout_name:
        print(sec_layout_code)
    else:
        print(pri_layout_code)


def on_shutdown_or_reload(conn, event):
    conn.main_quit()


sway.on(i3ipc.Event.INPUT, on_input_change)
sway.on(i3ipc.Event.SHUTDOWN, on_shutdown_or_reload)
sway.on(i3ipc.Event.SHUTDOWN_EXIT, on_shutdown_or_reload)
sway.on(i3ipc.Event.SHUTDOWN_RESTART, on_shutdown_or_reload)
sway.on(i3ipc.Event.BARCONFIG_UPDATE, on_shutdown_or_reload)
sway.main()
```

**Comment by krtko1** [comment]
if I read correctly, #659 also interact just to input change

**Comment by asahaf** [comment]
@krtko1 yes it does subscribe to input change events

**Comment by Begggs** [comment]
I rewrote a jq version in sed and embedded it into the single 'exec' object, so it doesn't need any external script execuion:
`"exec": "swaymsg --type get_inputs | grep \"xkb_active_layout_name\" | sed -u '1!d; s/^.*xkb_active_layout_name\": \"//; s/ (US)//; s/\",//' && swaymsg --type subscribe --monitor '[\"input\"]' | sed -u 's/^.*xkb_active_layout_name\": \"//; s/\",.*$//; s/ (US)//'",`

**Comment by kblcuk** [comment]
FWIW those running Waybar in Sway can just use `sway/language`: https://github.com/Alexays/Waybar/blob/master/man/waybar-sway-language.5.scd

**Comment by tigerjack** [comment]
> FWIW those running Waybar in Sway can just use `sway/language`: https://github.com/Alexays/Waybar/blob/master/man/waybar-sway-language.5.scd

Great, I just added it and it seems to work. Do you think it would be possible to add also the variant together with the layout name?

**Comment by Anakael** [comment]
Any updates here?

**Comment by hirmanpour** [comment]
Two enhancements to sway/language could be added:
- The first is to minimally differentiate between several keyboards belonging to the same language by adding an index to the indicator. For example, I use a standard US keyboard and a US keyboard with dead keys. They both show as EN. In Gnome they would show as EN1 and EN2
- The second, perhaps easier to implement, is to offer the formatting option to show the full name of the keyboard used : e.g. "US Intl Keyboard (with dead keys)" could be displayed when hovering on the indicator.

**Comment by Anakael** [comment]
@hirmanpour 
I think I can implement the first option.

**Comment by hirmanpour** [comment]
That would be great !

As a side note regarding the first option, according to [ArchWiki](https://wiki.archlinux.org/title/Sway) one can get the current layout with this command:

`swaymsg -t get_inputs | jq -r '.[] | select(.identifier == "kbd_identifier") | .xkb_active_layout_name'`

But that depends on `kbd_identifier`, which is different for each computer model. 

For a plug-in general solution, one would need, unless a kbd_identifier is manually specified by the end user, to automatically extract the `kbd_identifier` from the list of inputs (assuming there is only one input with type "keyboard" attached, which seems a reasonable assumption that would work for 99%+ of users), and feed it into this command.

**Comment by bnjw5jhyxn** [comment]
@hirmanpour I might just be in the 1% of users who got unlucky here, but here is the output of
```
swaymsg -t get_inputs | jq -r '.[] | select(.type == "keyboard") | .identifier'
```
on my laptop:
```
0:0:HP_WMI_hotkeys
0:0:HP_Wireless_hotkeys
1:1:AT_Translated_Set_2_keyboard
1032:21248:HP_Wide_Vision_HD_Camera:_HP_Wi
0:1:Power_Button
0:6:Video_Bus
0:1:Power_Button
```

**Comment by Anakael** [comment]
@hirmanpour 
Implemented in https://github.com/Alexays/Waybar/pull/1159

**Comment by hirmanpour** [comment]
@bnjw5jhyxn  Oh god ! Lucky one percenter ;-)

Could it be that I might also be the proud  owner of 7 keyboards, without knowing it ???

**Comment by hirmanpour** [comment]
@Anakael  Many thanks !

**Comment by gbrlsnchs** [comment]
Does this only work for Sway?

**Comment by Anakael** [comment]
@gbrlsnchs 
Yes, `sway/language` works only with sway.

**Comment by soppelmann** [comment]
`sway/language` currently doesn't differentiate between English layouts.
I use a UK keyboard on my laptop and a US keyboard at home but both show up as EN.
English is the language not the layout. Perhaps a `sway/layout` would be a better name.

**Comment by Anakael** [comment]
> `sway/language` currently doesn't differentiate between English layouts.
> I use a UK keyboard on my laptop and a US keyboard at home but both show up as EN.
> English is the language not the layout. Perhaps a `sway/layout` would be a better name.

Renaming the module name will break compatibility.

**Comment by Anakael** [comment]
> `sway/language` currently doesn't differentiate between English layouts.
> I use a UK keyboard on my laptop and a US keyboard at home but both show up as EN.

keyboard != layout.

With last update UK layout should be written as `gb` for flag `{name}` and `English (UK)` for `{long}` flag.
![image](https://user-images.githubusercontent.com/17771546/130125145-3be6f532-1fe6-46d2-96a5-79e619be1730.png)
![image](https://user-images.githubusercontent.com/17771546/130125308-8cd109df-ca5f-4b34-abc1-7c7c9de758fc.png)

**Comment by boredland** [comment]
I really like the default sway/language module, but would it be possible to display it conditionally if there is more than 2 layouts configured? otherwise it is wasting that precious space 🌴

**Comment by keithbowes** [comment]
> setxkbmap -query | grep layout | cut -f2 -d":" | tr -d '[:space:]'

`bash: setxkbmap: Command not found`

Hm.

**Comment by Anakael** [comment]
> 

could you try install libxkbcommon?

**Comment by dancer69** [comment]
I landed here searching a way to display a layout indicator to waybar using niri as WM/composer. Seems that the implementation in waybar is only for sway. Based of the discussion here I managed to implement it as a custom module though:
`"custom/lang":{
	"exec": "if [[ $(niri msg keyboard-layouts | grep '*') =~ 'English' ]]; then    echo 'EN'; else echo 'GR'; fi",
	"interval":1
},`

**Comment by dancer69** [comment]
Thanks, I didn't know that. This was the discussion I found from googling and because there wasn't mentioned niri is supposed that there wasn't.

**Comment by savager2k03** [comment]
tooltip-format is missing for niri/language though
