### ISSUE TITLE
Popups of tray icons always displayed behind window

### ISSUE THREAD

**Issue by Shadowghost** [Alexays/Waybar#660]
When clicking on a tray icon (blueman-applet, nm-applet) its popup opens but is only properly clickable when no windows is opened on the workspace. When any window is opened the popup is opened behind that window and you can't do anything useful with it. You can see that it's opened by looking at the bar, there will be a small white frame underneath the tray icon - that's the upper border of the popup.
Is this a configuration issue on my side or something related to recent changes on sway/wayland or waybar? I'm using sway (not sway-git) and waybar-git on archlinux.

**Comment by Alexays** [comment]
Should be fixed as https://github.com/swaywm/sway/pull/4781 is merged :)
