### ISSUE TITLE
feature request - click, scroll events

### ISSUE THREAD

**Issue by zetorian** [Alexays/Waybar#67]
this seems like something that would be incredibly useful, especially if configured. launch pavucontrol when clicking the pulseaudio module for example would be quite helpful to me personally.

I would be more than happy to assist with development / reworking if you could give me a bit of guidance as to where you would like this implemented.

**Comment by Eyenseo** [comment]
Can scroll-events be tackled with this issue to? I use them to increase and decrease volume and backlight.

**Comment by harishkrupo** [comment]
For scroll events on pulseaudio, I have raised a PR https://github.com/Alexays/Waybar/pull/68.
I believe we could make it configurable such that user preferred commands are invoked on those events.
Something like this:
```
    "pulseaudio": {
        "format": "{volume}% {icon}",
        "format-bluetooth": "{volume}% {icon}",
        "format-muted": "",

        "on-click" : "<cmd>",
        "on-scroll-up" : "<cmd>",
        "on-scroll-down" : "<cmd>",

        "format-icons": {
            "headphones": "",
            "handsfree": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        }
    },
```

**Comment by Alexays** [comment]
@harishkrupo Yep can you move your scroll code in ALabel.cpp and maybe if on-scroll-up/down is not set, it raise the volume in pulseaudio ? 😄
So it's in all the Label modules (Cpu, Memory, ...)

**Comment by harishkrupo** [comment]
@Alexays Yup, Doing that. I was going to add that code in IModule (add a new file called src/IModule.cpp) as I observed that some of the modules are not subclasses of Alabel?

**Comment by Alexays** [comment]
@harishkrupo IModule is a interface so don't do this :/
Only in ALabel, is what we want :)

**Comment by harishkrupo** [comment]
@Alexays Got it. Will post patches soon.

**Comment by harishkrupo** [comment]
@zetorian This is merged. Please check: https://github.com/Alexays/Waybar/pull/68
