### ISSUE TITLE
Feature request: style for active workspace

### ISSUE THREAD

**Issue by dev-zero** [Alexays/Waybar#674]
I couldn't figure out how to style the active workspace on a screen differently: when switching screens it would be nice to see on the other screen what it's active workspace (number) is.

**Comment by tobiaspc** [comment]
That is already possible, check my config:
```
#workspaces button {
    padding: 0 5px;
    background-color: #555555;
    color: #CCCCCC;
    border-bottom: 0px solid #555555;
}
#workspaces button:hover {
    box-shadow: inherit;
    text-shadow: inherit;
    background: #555555;
    border: #555555;
    border-bottom: 0px solid #555555;
}

#workspaces button.visible {
    background-color: #777777;
    color: #DDDDDD;
    border-bottom: 0px solid #556B2F;
}

#workspaces button.focused {
    background-color: #556B2F;
    color: #FFFFFF;
    border-bottom: 0px solid #556B2F;
}

#workspaces button.unfocused {
    background-color: #0000FF;
    color: #999999;
    border-bottom: 0px solid #556B2F;
}

#workspaces button.urgent {
    background-color: #FF0000;
    color: #FFFFFF;

}

```


button.visible is what you want to configure.

**Comment by dev-zero** [comment]
uh, oh, I must have overlooked that one while checking the man page for waybar-sway-workspaces, sorry & thanks!

**Comment by rnestler** [comment]
I was also struggling to find the correct style to configure this and fixed it in the wiki: https://github.com/Alexays/Waybar/wiki/Module:-Workspaces
