### ISSUE TITLE
Is backlight device name amdgpu_bl1 supported?

### ISSUE THREAD

**Issue by nwg-piotr** [Alexays/Waybar#679]
I recently bought the MSI Alpha 15 machine, which uses `amdgpu_bl1` as the backlight device name. If I understand your code properly, the Backlight module expects the `amdgpu_bl0` name, does it? Could it be altered to work in both cases?

**Comment by Alexays** [comment]
Should be fixed with e01a081f2f17376c55d6f5348cae3d8e940fc07f

**Comment by nwg-piotr** [comment]
Many thanks! I was about to write a temporary external script, but you were faster. :)
