### ISSUE TITLE
[Question] Temperature module

### ISSUE THREAD

**Issue by fourstepper** [Alexays/Waybar#681]
I am trying to get the temp module working using the guide at 

https://github.com/Alexays/Waybar/wiki/Module:-Temperature

My current config looks like this:

```
    "temperature": {
	"thermal-zone": 2,
	"hwmon-path": "/sys/class/hwmon/hwmon2/temp1_input",
	"critical-threshold": 80,
	"format-critical": "{temperatureC}°C ",
	"format": "{temperatureC}°C "
    },
```
Unfortunately, this module doesn't display any values. When I use the program lm-sensors, the output displays correctly

I am looking to monitor CPU temps.

How would I ago about troubleshooting this?

Thank you!

**Comment by cryptoluks** [comment]
Does `cat /sys/class/hwmon/hwmon2/temp1_input` output any value?

**Comment by RobinOpletal** [comment]
cat /sys/class/hwmon/hwmon2/temp1_input
cat: /sys/class/hwmon/hwmon2/temp1_input: No such file or directory

Before I was getting a nonsense number, 28 C while sensors said around 60 C

**Comment by fourstepper** [comment]
As this doesn't really have much priority for me, I will try to research this on my own and will close this :) Thank you for Waybar!

**Comment by cryptoluks** [comment]
Have a look at the values from `sensors`

```
❯ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +42.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +46.8°C  (high = +70.0°C)
Tctl:         +46.8°C  

amdgpu-pci-0500
Adapter: PCI adapter
vddgfx:           N/A  
vddnb:            N/A  
edge:         +46.0°C  (crit = +80.0°C, hyst =  +0.0°C)

thinkpad-isa-0000
Adapter: ISA adapter
fan1:           0 RPM
temp1:        +46.0°C  
temp2:         +0.0°C  
temp3:         +0.0°C  
temp4:         +0.0°C  
temp5:         +0.0°C  
temp6:         +0.0°C  
temp7:         +0.0°C  
temp8:         +0.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.48 V  
```

and just look for a corresponding file reporting the wished temperature:

```
❯ awk '{print FILENAME ":" $0}' /sys/class/hwmon/hwmon*/temp*input
/sys/class/hwmon/hwmon2/temp1_input:44000
/sys/class/hwmon/hwmon2/temp2_input:44000
/sys/class/hwmon/hwmon3/temp1_input:44000
/sys/class/hwmon/hwmon3/temp2_input:0
/sys/class/hwmon/hwmon3/temp3_input:0
/sys/class/hwmon/hwmon3/temp4_input:0
/sys/class/hwmon/hwmon3/temp5_input:0
/sys/class/hwmon/hwmon3/temp6_input:0
/sys/class/hwmon/hwmon3/temp7_input:0
/sys/class/hwmon/hwmon3/temp8_input:0
/sys/class/hwmon/hwmon4/temp1_input:44000
/sys/class/hwmon/hwmon5/temp1_input:44000
```
If you are unsure which temperature is reporting your core temperature, just spawn some load with e. g. `dd`:

```
dd if=/dev/zero of=/dev/null &
```

Do not forget to kill them later: `killall dd`

Probably there is a better way to output directly which files `sensors` is using. But I am not aware of it.

Hope this helps.
