### ISSUE TITLE
exec-if condition not respected in a custom module

### ISSUE THREAD

**Issue by fourstepper** [Alexays/Waybar#682]
I am trying to use the mediaplayer.py script as called in 
https://github.com/Alexays/Waybar/blob/master/resources/config and defined in https://github.com/Alexays/Waybar/blob/master/resources/custom_modules/mediaplayer.py

I have edited the script slightly for it to fit my needs better:
```
        "custom/media": {
        "format": "{icon} {}",
        "return-type": "json",
        "max-length": 40,
        "format-icons": {
            "spotify": "",
            "default": "🎜"
        },
        "escape": true,
        "exec": "$HOME/.config/waybar/custom_modules/mediaplayer.py --player spotify 2> /dev/null",
        "exec-if": "pgrep spotify",
        "on-click": "playerctl --player=spotify play-pause",
        "on-click-right": "playerctl --player=spotify next",
        "on-click-middle": "playerctl --player=spotify previous"
    },
```

If I reload the configuration, it seems that the script is executed again and again, even though the condition of exec-if is not met (e.g. doesn't return 0)

![image](https://user-images.githubusercontent.com/49439044/80214413-144cee80-863b-11ea-9003-4870d0526531.png)

![image](https://user-images.githubusercontent.com/49439044/80214338-f2ec0280-863a-11ea-9e72-b90cdd49e9eb.png)

(Side note: I realized the above command output might be misleading, I have been testing it and issued the command a few times without reloading the config. The number of processes only rises when I indeed reload the configuration)

Could this potentially be a bug or is there something I am missing/doing wrong?

Thank you!

**Comment by Alexays** [comment]
Should be fixed on master.
Can you confirm?

**Comment by fourstepper** [comment]
Hi, thanks for the heads-up, I will test this as soon as possible and report back.

All the best!

**Comment by Alexays** [comment]
Reopen the issue if not fixed ;)
