### ISSUE TITLE
Feature request: more complete bluetooth module

### ISSUE THREAD

**Issue by tardypad** [Alexays/Waybar#688]
I'm not using yet the current bluetooth module as it's not released yet but from what I see it only displays whether the adapter is activated or not.

It'd be nice to have some more information available to be displayed:
- list of connected devices
- whether the controller is discoverable
- whether the controller is pairable
-...

My personal use case is "I want to display the bluetooth icon only when some devices are connected to it".
I guess there would be several different "format-connected", "format-disconnected",... config keys like for other modules to allow this.

I'm currently using a custom module and script for this purpose using bluetoothctl. 
But a more robust native module would be welcome.

**Comment by mnussbaum** [comment]
It would be great if bluetooth device battery levels could be displayed as well
