### ISSUE TITLE
Clock module not working

### ISSUE THREAD

**Issue by Ramojus** [Alexays/Waybar#698]
When I add clock module, with this configuration ```"format": "{:%H:%M}",``` it doesn't show up in the bar, all the other modules do, but this one is just not working for me. This is with sway on arch.

**Comment by cristobaltapia** [comment]
I am having this problem too. Until yesterday it was working though.

**Comment by Alexays** [comment]
Workaround added to Wiki while waiting for the date lib update
https://github.com/Alexays/Waybar/wiki/Module:-Clock#troubleshooting

**Comment by mielouk** [comment]
Sorry for reviving this closed thread, but I tried setting the LC_TIME as described in this [ArchWiki article](https://wiki.archlinux.org/index.php/Locale#LC_TIME:_date_and_time_format) to either de_DE.UTF-8 or en_DK.UTF-8 and both didn't help. 

Not  sure what you mean by 
`set locale to C in the config file (musl)`
