### ISSUE TITLE
Remove MPD module connection logging

### ISSUE THREAD

**Issue by tardypad** [Alexays/Waybar#706]
The MPD module keeps spamming my general sway log with a couple of the following messages every 30sec.
```
[info] mpd: Connected to MPD
[warning] mpd: Connection to MPD closed
```
Those particular messages are probably worthless for everybody. I believe they should be removed by default.

**Comment by Alexays** [comment]
Done on master

**Comment by eternal-sorrow** [comment]
Why does it reconnect anyway? Is it really needed to close mpd connection and reconnect every 30 seconds?
