### ISSUE TITLE
Python script does not work in waybar

### ISSUE THREAD

**Issue by mithodin** [Alexays/Waybar#708]
I have written this python script, to output the contents of the scratchpad every time a window is updated.
```

#!/usr/bin/env python3
import i3ipc
import os
import sys

def print_ev(sway,event):
    scratchpad = sway.get_tree().scratchpad()
    print(" | ".join([d.name for d in scratchpad.descendants()]))

try:
    socket = os.environ["SWAYSOCK"]
except KeyError:
    sys.exit(1)

sway = i3ipc.Connection(socket_path=socket)
tree = sway.get_tree()
scratchpad = tree.scratchpad()
sway.on(i3ipc.Event.WINDOW_MOVE,print_ev)
sway.main()
```
This works perfectly on the shell, but Waybar doesn't show the output if I use it as a custom module. Why is this? A simple

```
#!/usr/bin/env python3
print("Hello World")
```
works fine, so it's not like python itself is the problem.

**Comment by Alexays** [comment]
Can you share your custom module configuration?

**Comment by mithodin** [comment]
it's just an exec of the python script. I managed to fix it by wrapping the call like this:
```
unbuffer scratchpad.py | cat
```
