### ISSUE TITLE
libappindicator not working.

### ISSUE THREAD

**Issue by eoconnor6797** [Alexays/Waybar#711]
Whenever I run waybar I receive this message: 
`For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity` 
despite having libappindicator-gtk3 installed and the correct environment variable. Therefore none of the app indicators are displayed.

error:
![image](https://user-images.githubusercontent.com/5209596/82135921-1e938000-97d6-11ea-88d5-e308de3ae516.png)

libappindicator info:
![image](https://user-images.githubusercontent.com/5209596/82135949-55699600-97d6-11ea-83b1-4eb59f9b5061.png)

env variable:
![image](https://user-images.githubusercontent.com/5209596/82135956-631f1b80-97d6-11ea-9725-f8be36fc7f7b.png)

**Comment by eoconnor6797** [comment]
its appears to have been an issue with my unicode characters not displaying correctly. after installing some more fonts I seem to resolved the issue.

**Comment by Ulexus** [comment]
@eoconnor6797 What give you the indication that it was a font problem?  I am having the same problem after upgrading, but it previously been working just fine for many months.
