### ISSUE TITLE
Disk module wrong info

### ISSUE THREAD

**Issue by LukashonakV** [Alexays/Waybar#712]
Dear maintainer,
Recently I decided to move from Debian(KDE) to Arch Wayland + Sway+Waybar.
_sway version 1.4_
_Waybar v0.9.2_
While challenging I faced with the issue. Disk module shows me wrong info.
`"disk": {`
          `"interval": 3,`
          `"format": "{free} / {used} = {total} > {percentage_free} -> {percentage_used}",`
          `"path": "/home"`
       `}`

df -h /home
`Filesystem      Size  Used Avail Use% Mounted on`
`/dev/sda8        67G  8.3G   56G  13% /home`

In the same time waybar shows me: `15.1GiB / 11.6Gib = 66.8GiB > 82 -> 17`
The same issue for every path or mount point I'm trying to use.

Could you find the reason and fix it if necessary.
Many thanks and have a good day :)

**Comment by jbeich** [comment]
Does https://github.com/Alexays/Waybar/pull/720 help?
