### ISSUE TITLE
The folder temperature is changing on reboot and broke the temperature module

### ISSUE THREAD

**Issue by bluebyt65** [Alexays/Waybar#717]
Temperature module is working fine until I reboot. This is because the folder is changing for the temperature of the CPU. Can be the folder hwmon2, hwmon3, hwmon4 
Example path "hwmon-path": "/sys/class/hwmon/hwmon3/temp1_input"
If I don't define the path, waybar is taking the temperature of ACPI interface.

I just have an idea maybe putting a wild card like this can solve the problem:
 "/sys/class/hwmon/hwmon%/temp1_input"

**Comment by cryptoluks** [comment]
I experienced the same issue but did not investigate further as it disappeared for now.. Using `hwmon3`.

As a temporary fix, you could periodically run a custom script to read out the correct temperature and write it to a file which is used by waybar. Not pretty but should work..

**Comment by Alexays** [comment]
Maybe `hwmon-path-abs` can help?

**Comment by bluebyt65** [comment]
I tried to use the option "hwmon-path-abs", but I don't understand how its working.
e.g. I found that path of temp1_input can be on hwmon0 to hwmon5.
I tried this:
"hwmon-path-abs": "/sys/devices/platform/coretemp.0/hwmon/hwmon#/temp1_input"

or this:
"hwmon-path-abs": "/sys/devices/platform/coretemp.0/hwmon/temp1_input"
