### ISSUE TITLE
Waybar on Mir

### ISSUE THREAD

**Issue by pixelr0** [Alexays/Waybar#718]
Waybar on Mir https://discourse.ubuntu.com/t/waybar-on-mir/16383

**Comment by AlanGriffiths** [comment]
Waybar on egmde
![image](https://user-images.githubusercontent.com/9048879/85039885-16858200-b180-11ea-8eee-87698ddad5fe.png)

https://discourse.ubuntu.com/t/waybar-on-mir/16383/2

**Comment by Alexays** [comment]
Ohh nice to see that's work on other compositors 😍
