### ISSUE TITLE
Dynamic workspace names

### ISSUE THREAD

**Issue by Kommynct** [Alexays/Waybar#727]
https://github.com/cboddy/i3-workspace-names-daemon

Something like this would be incredibly useful to me.

**Comment by zimbipw** [comment]
Is this doing what you're looking for?
https://github.com/johnae/persway

**Comment by Kommynct** [comment]
That doesn't allow you to change the workspace names in any usable way, because it changes the acutal name of the workspace rather than changing just the name/icon. I think something implemented directly into waybar would be necessary to make this a useful function.

**Comment by Kommynct** [comment]
https://github.com/pierrechevalier83/workstyle

This now exists, closing
