### ISSUE TITLE
Taskbar module questions

### ISSUE THREAD

**Issue by bluebyt65** [Alexays/Waybar#728]
I just tried the taskbar module.
When I set this to icon, "format": "{icon}", this work
I tried "format": "{title}" or "{app_id}" but the taskbar doesn't appeared.

Also how to define the style.css?
I added this but it has no effect on waybar.
#taskbar
#taskbar button
#taskbar button.maximized
#taskbar button.minimized
#taskbar button.active
#taskbar button.fullscreen

Ok I will wait until the wiki has been updated you close this If you want, by the way I been using the taskbar module since 4 days now and it working well! here my config:
 "wlr/taskbar": {
    "format": "{icon}",
	"tooltip-format": "{title}",
	"on-click": "activate",
	"all-outputs": false,
	"active-first": true,
	"icon-size": 32,
	"icon-theme" : "Obsidian",	
	"on-click-right": "minimize"

**Comment by AGCaesar** [comment]
Did you do or install anything special for this to work with sway? It cant get it to work with my setup. Can you show a screenshot of how it looks? :)

**Comment by bluebyt65** [comment]
Did you install the latest version? (5 days ago)
By the way I use Wayfire. (I will post a screenshot later)
You have to edit the config and style.css file as following:
**config file:**
"wlr/taskbar": {
"format": "{icon}",
"tooltip-format": "{title}",
"on-click": "activate",
"all-outputs": false,
"active-first": true,
"icon-size": 32,
"icon-theme" : "Obsidian",
"on-click-right": "minimize"

**style.css**
#taskbar,

**Comment by AGCaesar** [comment]
Thanks for the help. I usw waybar-git on archlinux and it should ne the latest version...
My config is this: https://pastebin.com/KvgQRc2h
But it still does not show any taskbar. Is it my fault or does it not work on sway? Any other hints? :)

**Comment by Alexays** [comment]
@AGCaesar Sway doesn't support toplevel manager ATM
https://github.com/swaywm/sway/pull/4476

**Comment by AGCaesar** [comment]
@Alexays Thank you, I did not realize this. Thems like they are working on it but work has stopped for quite some time...

**Comment by AGCaesar** [comment]
Let's see if https://github.com/swaywm/sway/pull/5477 fixes this :)

**Comment by l3nkz** [comment]
Hi, there seems to be a bug with the format option. I will have a look into this.

Did you already figure out how the styling works? It uses the same approach as the sway/workspaces module. With 
#taskbar you can style the whole taskbar module, with #taskbar button you can style the individual elements for the windows (toplevels) and the four substyles (#taskbar button.{active,fullscreen,maximized,minimized}) can be used to add additional styling when the window (toplevel) has the corresponding state.

My config for example looks like this:
**config**
```
"wlr/taskbar": {
    "icon-theme": "Numix-Circle",
    "icon-size": 12,
    "on-click": "activate",
    "on-click-right": "minimize",
    "format": "{icon}"
},
```
**style.css**
```
#taskbar {
    border-radius: 0px 8px 8px 0;
    padding: 0 3px;
    margin: 0 0px;
    color: #ffffff;
    background-color: rgba(120,118,117,0.3);
}
#taskbar button {
    border-radius: 3px 3px 3px 3px;
    padding: 0 0 0 3px;
    margin: 3px 1;
    color: #ffffff;
    background-color: rgba(120,118,117,0.1);
}
#taskbar button.active {
    background-color: rgba(120,118,117,0.8);
}
```

**Comment by AGCaesar** [comment]
I gave it a short try with a fresh sway build and it seems to work well!
Thank you al lot!

**Comment by bluebyt65** [comment]
Thanks l3nkz! with your style.css yes I can understand easily now!
