### ISSUE TITLE
waybar doesn't appear on new screens unless restarted

### ISSUE THREAD

**Issue by Soundtoxin** [Alexays/Waybar#730]
I have my main bar configured like so:
```
"output": ["DP-3", "eDP-1"],
```
Typically I am docked with DP-3 and DP-4 outputs. DP-4 has its own separate bar with less modules turned on because it's in portrait and has less width. When I undock, I want eDP-1 to replace DP-3 as being the "main" screen with the main bar on it. So, I have this bar enabled for both outputs.
While I'm docked, eDP-1 is disabled with its lid closed. When I undock and open the laptop (this enables its output, by the way), there is no bar in sight. If I kill waybar and then start it again, the bar appears, so my config must not be completely wrong.
When I dock again after undocking and having no bar, I now have no bar on any screen. It wouldn't have surprised me if waybar were just crashing at some point along the way here, but I can still find it running if I search for it in htop.

edit: I'm on Waybar v0.9.1, installed from Guix. I wonder if this is fixed in 0.9.2 by this PR: https://github.com/Alexays/Waybar/pull/598
I'll see if I can get anyone to update the package.

**Comment by Alexays** [comment]
This issue should be fixed with recents changes, can you give a shot?

**Comment by Soundtoxin** [comment]
Sorry I haven't been able to answer yet. I don't think I can easily access a newer version right now, but as soon as I'm able to test this, I'll get back to you.
