### ISSUE TITLE
Tray dialog is hidden behind opened windows in sway

### ISSUE THREAD

**Issue by rsansores** [Alexays/Waybar#732]
The tray dialog is behind the windows so is impossible to click it or read it in sway.

![2020-06-04-103038_screenshot](https://user-images.githubusercontent.com/2236118/83777033-8b1fd300-a64e-11ea-93a9-49c409d26706.png)

**Comment by ranisalt** [comment]
Change the config to have `"layer": "top"`. By default it does this, not sure why, does not look sane.

**Comment by X0rg** [comment]
I had the same issue until I discovered `layer` option was unset in my configuration file. Thanks for the tip @ranisalt!

**Comment by wfleming** [comment]
Has anybody else had an issue with this setting and dmenu (or a similar launcher)? The `"layer": "top` setting for Wayland took care of tray icon menus, but now when I launch dmenu it's hidden behind the waybar.

Anybody else know if there's something I could do with `for_window` to identify dmenu windows and move layer them over the waybar?

Alternatively, has anybody found this isn't a problem with other launchers? I'm using dmenu partially out of habit: if there are similarly minimalist launchers that are better behaved on wayland I'm open to switching.

**Comment by X0rg** [comment]
> Alternatively, has anybody found this isn't a problem with other launchers? I'm using dmenu partially out of habit: if there are similarly minimalist launchers that are better behaved on wayland I'm open to switching.

@wfleming I'm using [Wofi](https://hg.sr.ht/~scoopta/wofi), a Rofi-like menu for Wayland. I had some focus issues with X11-based menus like Rofi.

**Comment by wfleming** [comment]
Thanks @X0rg I'll check that out!

**Comment by David96** [comment]
The "layer: top" thing should no longer be necessary. Which version of sway do you use? It should render popups at the top layer since quite some time now, so the bar can be set to layer bottom to not interfere with stuff like dmenu/bemenu.

**Comment by qubidt** [comment]
> It should render popups at the top layer since quite some time now, so the bar can be set to layer bottom to not interfere with stuff like dmenu/bemenu.

If I'm reading the changelog right, this was fixed in 1.5-rc1. I hit this in the latest stable 1.4 (that's what is in the Arch repos). That's a good tip tho, thank you
