### ISSUE TITLE
Taskbar: sh: minimize: command not found

### ISSUE THREAD

**Issue by kanyck** [Alexays/Waybar#735]
I think I don't fully understand the logic behind the taskbar.
My understanding is that "activate" should bring me to this window/viewport, but it does nothing. (I'm using wayfire). "minimize" should put the window into the tray, but it calls shell instead. So far I just can see what windows are open, without possibility of any sencible action.

**Comment by l3nkz** [comment]
Hi, can you share your config? I am using wayfire as well and the actions work as expected for me.

**Comment by KierPrev** [comment]
I'm having the same problem (minimize command not found) now, on right click.
![image](https://github.com/Alexays/Waybar/assets/44746791/97ed8d4a-f7ea-4c92-ae3e-a7b69bb14a8c)

**Comment by l3nkz** [comment]
Hm, this is really wired. I can't reproduce the behavior. And looking at the code, this should just work. waybar should try to execute the command. This is not supported by the plugin and hence should result in a different output if it doesn't know the action instead.

**Comment by Yaakoss** [comment]
Hi, i'm on waybar 10.1 on arch.
i got the same issue with minimize and minimize-raise. 
```
"wlr/taskbar": {
       "format": "{}",
       "separate-outputs": true,
       "on-click": "activate",
       "on-click-right": "minimize-raise",
},
```

it just does not work and if waybar is started in a terminal i see
`sh: Zeile 1: minimize-raise: Kommando nicht gefunden.` (Line 1: command not found)
