### ISSUE TITLE
Calendar display issue

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#740]
Clock module has this config:
```
	"clock": {
		"format": "{:%a %F   %H:%M:%S}",
		"tooltip-format": "<tt>{calendar}</tt>",
		"interval": 1
	},
```
It looks like this:
![2020-06-09-070040](https://user-images.githubusercontent.com/4847726/84080647-06291680-a9cc-11ea-8f8b-c63db16b7612.png)

**Comment by Anakael** [comment]
Can you share your style config for clock?
It seems like you use wrong font or something like that.

**Comment by eternal-sorrow** [comment]
Just recently I found out that if I restart the Waybar, it works normally. The problem only occurs when waybar is started automatically at sway startup.

**Comment by eternal-sorrow** [comment]
Also, after I updated to the recent sway 1.5-rc1, I can't reproduce the issue anymore.
