### ISSUE TITLE
Per-output styling?

### ISSUE THREAD

**Issue by akobel** [Alexays/Waybar#741]
Is there any way to apply a style per-output, e.g. by adding the output name as a class for all CSS-stylable objects?

Use case: I have a multi-DPI setup (different output scales) and significantly different output widths. I want to show the "same" Waybar configuration on all screens, except that I need a slightly smaller font on one of the displays to fit all items. Per-output configuration is possible for the config, but not for the stylesheet file; so right now, my only choice would be to more or less duplicate the config file (except for the output configuration), fire up two Waybar instances and apply different styles via the command line option, which sounds like a lame workaround...

**Comment by Alexays** [comment]
It's already possible as the output name/defined name/position in the config is set. 
https://github.com/Alexays/Waybar/blob/master/src/bar.cpp#L24
We may want to update doc/wiki for that

**Comment by akobel** [comment]
Thanks, that was the right pointer (plus the hint about `env GTK_DEBUG=interactive waybar` in the wiki). In the meantime, for anyone stumbling across the issue: It's just the main window that gets the class, *not* every item (which makes perfect sense, of course). That is, a proper base style for all elements would be applied as, e.g., `window.eDP-1 * { font-size: 10pt; }`.
