### ISSUE TITLE
Pulseaudio - Icon not working vor Audio output (pci 5.1)

### ISSUE THREAD

**Issue by josefbachmann** [Alexays/Waybar#743]
Hi

I try to add an icon to my speakers in the puselaudio section of my config.
```
"format-icons": {
             "headset": "foo",
             "speaker": "bar", 
             [...]
```
the icon for headset is working fine since 'headset' is found in pulseaudio:

```
pacmd list-sinks | grep -i "headset"
	name: <alsa_output.usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-00.analog-stereo>
	card: 1 <alsa_card.usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-00>
		udev.id = "usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-00"
		device.product.name = "HyperX Cloud Flight Wireless Headset"
		device.serial = "Kingston_HyperX_Cloud_Flight_Wireless_Headset"
		device.form_factor = "headset"
		device.description = "HyperX Cloud Flight Wireless Headset Analog Stereo"
		device.icon_name = "audio-headset-usb"
```
the name of my main surround system in pulseaudio is:
```
  * index: 3
	name: <alsa_output.pci-0000_0b_00.3.analog-surround-51>
```
in this name is no string of the current supported format-icons visible [Waybar-Wiki: PulseAudio](https://github.com/Alexays/Waybar/wiki/Module:-PulseAudio)

as written here:

> Yep, but you can still define `bluez_sink.40_EF_4C_39_89_B2.a2dp_sink` in your config with an icon :)

_Originally posted by @Alexays in https://github.com/Alexays/Waybar/issues/169#issuecomment-462674341_

i thought i can add the full sink name in place of "speaker" or something:
```
"format-icons": {
             "headset": "foo",
             "<alsa_output.pci-0000_0b_00.3.analog-surround-51>": "bar", 
             [...]
```
which pulseaudio field is searched for the format-icons? i added a description to my output device:
```
pacmd list-sinks | grep -i "speaker"
		device.description = "speaker"
```
but that doesn't work either...

I hope my problem is understandable. Is there a way to make this work?

Thx & reetings
Joe

**Comment by Alexays** [comment]
Hey can you try with:
```
"format-icons": {
             "headset": "foo",
             "alsa_output.pci-0000_0b_00.3.analog-surround-51": "bar", 
             [...]
```
As <> should not be included

**Comment by josefbachmann** [comment]
> Hey can you try with:
> 
> ```
> "format-icons": {
>              "headset": "foo",
>              "alsa_output.pci-0000_0b_00.3.analog-surround-51": "bar", 
>              [...]
> ```
> 
> As <> should not be included

Hi @Alexays 
Thanks for the reply. It does not work.

current config
`        "format-icons": {
            "headset": "",
            "alsa_output.pci-0000_0b_00.3.analog-surround-51": "bar",
            "default": ["-", "-"]
`

When I switch to speakers as default startup, the icon is correctly shown in waybar `-`. When i switch to the headphones and back to my speakers, which ar not recogniced withe `"alsa_output[...]`, there is still the headset symbol shown and not the default symbol.

I hope you undestand what I mean. 

so i have two problems:

1. when i switch away from headset to unknown source, there is still the headset symbol and not the default symbol.
2. "alsa_output.pci-0000_0b_00.3.analog-surround-51" as identifier still doesn't work.

well i learned to live with this problem so I will close this issue in a week if no one replies until then.

thanks and bye.
