### ISSUE TITLE
Can't seem to use bitmap fonts

### ISSUE THREAD

**Issue by halexanderc** [Alexays/Waybar#749]
I'm on Fedora 32 and I'm trying to use an .otb font, however every time I put it as first in the `font-family` all the characters in the bar just throw errors. Placing behind a .ttf font in the ordering will only change the icons. 

The font I'm using is [https://github.com/slavfox/Cozette](url).

**Comment by Alexays** [comment]
GTK issue 😢 
https://www.phoronix.com/scan.php?page=news_item&px=Pango-No-More-Bitmap-Fonts
