### ISSUE TITLE
Can only dismiss tray icon context menu by clicking waybar

### ISSUE THREAD

**Issue by ChrisLane** [Alexays/Waybar#750]
When I right click a tray icon in Waybar for an app, a context menu will open. I am only able to dismiss the context menu by clicking somewhere else on Waybar.

### Steps to reproduce
1. Configure Waybar to have the `tray` module
2. Open an app that has a tray icon with a right click context menu
3. Right click the tray icon
4. Attempt to dismiss the context menu by clicking somewhere else on the screen (not the Waybar)

### Expected behaviour
Able to click anywhere outside of the context menu to dismiss it

### Actual behaviour
Only able to dismiss the context menu by clicking the waybar

### Versions
- Arch Linux 5.7.4
- Waybar v0.9.2
- sway version 1.4-2270b4c2 (Jun 19 2020, branch 'master')
- wlroots version 0.10.0-g58df3eda (Jun 19 2020 branch 'master')

### Additional Info
Apps with tray context menus tested:
- Quassel Client
- Telegram Desktop
- Discord

**Comment by David96** [comment]
This is a known issue which is not very likely to be solved any time soon: https://github.com/wmww/gtk-layer-shell/issues/9
