### ISSUE TITLE
Taskbar: Missing application icons when the .desktop is in a folder not being searched or hicolor theme is being used as fallback

### ISSUE THREAD

**Issue by ghost** [Alexays/Waybar#754]
Some applications are not displaying their taskbar icons.

https://github.com/Alexays/Waybar/blob/8f684f703eb9c8a4e8b8ad02890622c486e960ea/src/modules/wlr/taskbar.cpp#L30

Does not include values like  `~/.local/share/applications` and Flatpak's `~/.local/share/flatpak/exports/share/applications` (--user), `/var/lib/flatpak/exports/share/applications`. Maybe the `$XDG_DATA_DIRS` environment variable, with the additional /applications sub-folder directory, could be used too?

The second search is from the icon theme.
https://github.com/Alexays/Waybar/blob/8f684f703eb9c8a4e8b8ad02890622c486e960ea/src/modules/wlr/taskbar.cpp#L67

`hicolor` is [the default fallback theme](https://developer.gnome.org/icon-theme-spec/) and it's why the icons were showing up for me on GNOME and Plasma. It could be hardcoded as the fallback theme after everything else fails.

Or multiple choices for `icon-theme`.

```json
"wlr/taskbar": {
    "icon-theme": "my-main-theme, my-custom-theme, hicolor"
}
```

**Comment by l3nkz** [comment]
> Some applications are not displaying their taskbar icons.
> 
> https://github.com/Alexays/Waybar/blob/8f684f703eb9c8a4e8b8ad02890622c486e960ea/src/modules/wlr/taskbar.cpp#L30
> 
> Does not include values like `~/.local/share/applications` and Flatpak's `~/.local/share/flatpak/exports/share/applications` (--user), `/var/lib/flatpak/exports/share/applications`. Maybe the `$XDG_DATA_DIRS` environment variable, with the additional /applications sub-folder directory, could be used too?

I just looked in the definition of `$XDG_DATA_DIRS` and it seems as if this is a good idea. Because if this environment variable is not set one should use `/usr/share` and  `/usr/local/share` which are the folders that I already use. Changing the code so that I use `$XDG_DATA_DIRS` should be an easy change.

> The second search is from the icon theme.
> https://github.com/Alexays/Waybar/blob/8f684f703eb9c8a4e8b8ad02890622c486e960ea/src/modules/wlr/taskbar.cpp#L67
> 
> `hicolor` is [the default fallback theme](https://developer.gnome.org/icon-theme-spec/) and it's why the icons were showing up for me on GNOME and Plasma. It could be hardcoded as the fallback theme after everything else fails.

Hm, this also sounds like a reasonable idea.

> Or multiple choices for `icon-theme`.
> 
> ```json
> "wlr/taskbar": {
>     "icon-theme": "my-main-theme, my-custom-theme, hicolor"
> }
> ```

I am not sure if there is actually a real use case for this. But if I implement the additional fallback to the system default, extending it so that multiple icon themes can be specified is actually very trivial. I will have a look into this.

**Comment by Khyber3737** [comment]
I forgot to add:

Some of the calls like Gtk::IconTheme::get_default() _might_ be returning the hicolor fallback but the idea is to allow prioritizing, like saying use my icon-theme version but if the **icon** (not the theme) doesn't exist use the fallback. I tried to add some paths and I'm still not getting all icons but I'll wait for your patch,, maybe I misunderstood how it works. The program Cuttlefish has an option _View icon in other themes_ that displays the icons being loaded.

When using `{icon}` format if it fails to load the icon the button icon area is not getting a placeholder with `icon-size` width/height. Maybe the tray has the same issue I didn't tested it.

**Comment by Anakael** [comment]
Worth adding that there are icon theme with another folder structure:
Not size/type/icon
But type/size/icon
I don't know exactly how Gtk::IconTheme handle it, but I think it should be considered in the first method of search.

**Comment by l3nkz** [comment]
> Worth adding that there are icon theme with another folder structure:
> Not size/type/icon
> But type/size/icon
> I don't know exactly how Gtk::IconTheme handle it, but I think it should be considered in the first method of search.

I think this is handled already by GTK … At least I didn't bother until now and for me it worked without any problems. But maybe it is worth to double check with the GTK manual.

**Comment by l3nkz** [comment]
> When using `{icon}` format if it fails to load the icon the button icon area is not getting a placeholder with `icon-size` width/height. Maybe the tray has the same issue I didn't tested it.

This is the wanted behavior (at least from my side). If the icon can not be loaded, the GtkImage for the icon is not shown, hence no placeholder. My fix would be to have some default (= no-icon-found-icon) which should be shown instead. But unfortunately, I haven't had a good idea yet which icon to use, that would always be available. Maybe, I add it as an option or ship some default icon with the module … not sure yet.

**Comment by l3nkz** [comment]
@Khyber3737 can you try my changes? Do the help with your problems?

**Comment by Khyber3737** [comment]
> /home/khyberm/.local/share:/home/khyberm/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

My distro's `XDG_DATA_DIRS` doesn't have `~/.local/share` so I changed it. I have icons there in both theme/size/apps and theme/apps/size. And in both formats like `16` and `16x16`, and `scalable`. Cuttlefish and my DEs can load them no matter the format but I wanted to make sure.

`"icon-theme": ["breeze", "hicolor"]` seems to be working for KDE programs. Now I see the correct icon even when I know there's a fallback.

VeraCrypt icon is working now. It's a pixmap `/usr/share/pixmaps/veracrypt.xpm` that even Cuttlefish doesn't load.

Wine now shows the fallback icon when my custom icon couldn't be loaded.

Flatpak icons from what I can tell not a single one works.

```
[debug] Use custom icon theme: breeze
[debug] Use custom icon theme: hicolor
[debug] Using 'desktop' search path prefix:
[debug] Using 'desktop' search path prefix: /home/khyberm/.local/share/
[debug] Using 'desktop' search path prefix: /home/khyberm/.local/share/flatpak/exports/share/
[debug] Using 'desktop' search path prefix: /var/lib/flatpak/exports/share/
[debug] Using 'desktop' search path prefix: /usr/local/share/
[debug] Using 'desktop' search path prefix: /usr/share/
[debug] Couldn't find icon for org.kde.krunner
[debug] Couldn't find icon for firefox-custom
[debug] Couldn't find icon for lutris
```

Lutris is the Flatpak. Firefox a custom .desktop. Krunner the default from my distro.

If I'm not mistaken the only icons from `~/.local/share` that works are the ones that are **scalable**, except for the Lutris Flatpak that doesn't load the svg and I confirmed they are there (it's a symlink on disk and Cuttlefish can load it).

Thanks

**Comment by Khyber3737** [comment]
@l3nkz Could the problem be that `app_id` doesn't match the `.desktop` file? `org.kde.krunner` is at `/usr/share/kglobalaccel/krunner.desktop`

https://github.com/Alexays/Waybar/blob/bc112eaae114403e19145bf64e898c499772385c/src/modules/wlr/taskbar.cpp#L96

**Comment by starsareintherose** [comment]
it seems that it still present in here, if I use tela theme and newsflash miss the icon
