### ISSUE TITLE
Custom modules can't show ampersand

### ISSUE THREAD

**Issue by billop** [Alexays/Waybar#756]
```    
"custom/foo": {
        "exec": "echo '&'",
        "interval": 5,
}
```

For some reason that just ends up in a blank space with a fixed width showing up.

**Comment by jamespeapen** [comment]
Try  ```"exec": "echo '&amp;'"```

**Comment by billop** [comment]
That worked. I feel like ampersands should be displayed properly by waybar however, whether by substitution or something else.

**Comment by minhduc0711** [comment]
Duplicate of https://github.com/Alexays/Waybar/issues/162, and I guess we can close this now.
> Now you can escape the script output by setting `escape` to `true`.

**Comment by billop** [comment]
Thanks, that's great to see.
