### ISSUE TITLE
AUR package build failing

### ISSUE THREAD

**Issue by Patricol** [Alexays/Waybar#760]
Apologies if this is the wrong place to report this.

The waybar-git AUR package needs to be edited; as per [this comment](https://aur.archlinux.org/packages/waybar-git/#comment-746421).

Attempts to use the PKGBUILD as-is currently fail.

Standard procedure is to flag the package as out of date; which was done about a month ago.
I noticed that @Alexays is the maintainer; so I'm creating this issue just in case it makes it easier for him/you to keep track of the problem.

Thank you so much!

**Comment by Alexays** [comment]
Sorry about the dealy, should be good now 😃
