### ISSUE TITLE
Incorrect values for CPU load format replacement?

### ISSUE THREAD

**Issue by gvccandido** [Alexays/Waybar#769]
The CPU `{load}` format replacement doesn't show the same values as `uptime` and `top`, for example.

The latter two are what is mostly presented as the load metric. However, in Waybar, the value obtained with `getloadavg(load, 1)` is scaled with the number of CPUs to show it as a percentage of CPU usage.

This seems to be a very rare way to present the load value, and I also think that it does not make so much sense as there is already the `{usage}` format.

Is there any reason for it?

**Comment by dron1885** [comment]
Not sure if related, but it seems that the reported value is incorrect. Or at the very least not what's expected. On my 12 core CPU, the module can report values up to 133%.
It's doesn't show the same as a total on hover pop-up.
![image](https://user-images.githubusercontent.com/45915083/103490673-81518e80-4e2e-11eb-9e93-61db375f1cee.png)
