### ISSUE TITLE
Tooltips do not appear

### ISSUE THREAD

**Issue by tmccombs** [Alexays/Waybar#771]
Tooltips no longer appear for me at all. 

This may be related to #63 .

I do see a warning when I should be getting a tooltip:

> (waybar:13089): Gdk-WARNING **: 01:38:38.880: Couldn't map window 0x563082887b70 as subsurface because its parent is not mapped.

**Comment by tmccombs** [comment]
oh, I had "layer" set to "bottom". I don't remember why. If I change it to "top", the tooltips appear.

**Comment by tmccombs** [comment]
I remember why I had it set to bottom. When it is set to top, if an application has a popup that overlaps waybar, then it will be covered by waybar.

**Comment by tmccombs** [comment]
setting it to bottom no longer has this issue.

**Comment by ashish-kus** [comment]
I don't know for what reason this issue is not solver for me, Sometime tooltip don't show up I need to restart waybar then it works.

**Comment by the-nummer-zone** [comment]
> I don't know for what reason this issue is not solver for me, Sometime tooltip don't show up I need to restart waybar then it works.

this is still the case for me, all this time later...

**Comment by HexChap** [comment]
Same here
