### ISSUE TITLE
Workspace buttons

### ISSUE THREAD

**Issue by cacheiforindicium** [Alexays/Waybar#774]
Hi,

I have two questions regarding the workspace buttons.

1. I'm trying to make the size of the workspace icons larger, by using the following in style.css
```
#workspaces button {
    padding: 5 5px;
    background: transparent;
    font-size: 50px;
}
```

However, font-size does not affect the size of the icons/button. In which way can I modify the size of the icon?

2. I am using format-icons as shown on the wiki example:
```
"sway/workspaces": {
    "disable-scroll": true,
    "all-outputs": true,
    "format": "{name}: {icon}",
    "format-icons": {
        "1": "",
        "2": "",
        "3": "",
        "4": "",
        "5": "",
        "urgent": "",
        "focused": "",
        "default": ""
    }
}
```

Is it possible to edit specific buttons from the workspace? For example, if I only want to give icon "1" a blue color, can I do this? #workspaces button affects all workspace buttons, and I haven't figured out how to style specific buttons.

EDIT:

For issue 1, I figured it is caused be the font-size declared in the first section:

```
* {
    border: none;
    border-radius: 0;
    font-family: "OverpassMono";
    font-size: 10px;
    min-height: 0;
}
```

Can I somehow overwrite this 10px only for the workspace buttons?

**Comment by freed00m** [comment]
I would like that also,

there should be a  way of match individual buttons.

Adding worskpace numbers as button's gtk id would be nice, or better a individual class. 

This is not enought .)
```
#workspaces button:nth-child(3) {
  background-color: #ffffff;
}
```

**Comment by bagnaram** [comment]
You can also specify the icon as a CSS background property and have control of the size and position

**Comment by ilkecan** [comment]
> However, font-size does not affect the size of the icons/button. In which way can I modify the size of the icon?

Not sure how it was 2 years ago, but you can currently do this with:
``` css
#workspaces button label {
  font-size: 50px;
}
```
Notice the `label` at the end of selector.

> if I only want to give icon "1" a blue color, can I do this?

Again you need to add `label` to the selector:
``` css
#workspaces button:nth-child(1) label {
  color: blue;
}
```

**Comment by Alexays** [comment]
Thx @ilkecan!

**Comment by aram-otf** [comment]
@ilkecan This post save me a lot!!!!! Thanks ilkecan <33333
