### ISSUE TITLE
Multiline tooltips?

### ISSUE THREAD

**Issue by oqwa** [Alexays/Waybar#794]
Does waybar support multiline tooltips? I would use it for more detailed additional information.

**Comment by jamespeapen** [comment]
You can use ```\r``` or ```\n``` to get multiline tooltips. Here's a multiline tooltip for the network with the IP address on a new line:
```    
    "network": {
        "format-wifi": "  {ipaddr} ({signalStrength}%)",
        "format-ethernet": "  {ifname}: {ipaddr}/{cidr}",
        "format-linked": "  {ifname} (No IP)",
        "format-disconnected": "⚠  Disconnected",
        "format-alt": "{essid}: {ifname}",
        "tooltip-format": "{essid}\r{ipaddr}"
    }

````

**Comment by oqwa** [comment]
Hmm, thank you! First I tried \n but it doesn't worked for me. But \r works.
