### ISSUE TITLE
If bar height gets very large at some point it never liberates the reserved space

### ISSUE THREAD

**Issue by vberger** [Alexays/Waybar#799]
While testing some stuff, I started a demo Wayland app which set its title to some very large string, containing several newlines. As a result, waybar grew a lot in height to display the full title, including the newlines, and the space reserved for it by sway grew as well.

Once that demo app was closed, waybar returned to its normal size, but the space reserved for it by sway did not, resulting in a huge empty gap on my screen between the bar and the windows.

Looks like the reserved space in layer shell is only updated when the bar grows, but not when it shrinks?

**Comment by alebastr** [comment]
> Looks like the reserved space in layer shell is only updated when the bar grows, but not when it shrinks?

Looking at the code, that's exactly how it works when gtk-layer-shell is used. The old layer-shell code was relying on `layer_surface.configure` event for that, gtk-layer-shell code path is not using it and `Bar::onConfigure` code doesn't look right.

Need to look how to fix that without affecting fallback layer-shell code.
