### ISSUE TITLE
Sway/workspace: Workspace names not in the same order as Sway internally stores them.

### ISSUE THREAD

**Issue by pkillnine** [Alexays/Waybar#802]
As a result, when running `workspace next`, the next workspace may not be the next one in the bar. Sway goes through them in the order that they are created, and Waybar sorts them into Alphabetical order.

This doesn't seem to be a problem for numbered workspaces.

This can be worked around by prefixing named workspaces with numbers, as Waybar orders those according to their prefixed numbers. I think it would be simpler and more consistent to have Waybar's workspace list match Sway's though, and if alphabetical order is desired, then to change the order of workspaces in Sway somehow.

My guess is that here is where Waybar sorts the workspace names, and where they go out of sync with Sway's internal list of workspaces: https://github.com/Alexays/Waybar/blob/master/src/modules/sway/workspaces.cpp#L118

EDIT:  As suggested by danshick in freenode/#sway, I removed lines 116 - 160 in         https://github.com/Alexays/Waybar/blob/5ebd3594e484baa085920dfe1f5312c57e5509d0/src/modules/sway/workspaces.cpp#L115, and the workspaces now appear in the correct order, so it is here where they are being sorted.

**Comment by mreppen** [comment]
@Arnavion In the first post EDIT it is said removing some lines fixes the problem. Was there any issue with that solution leading to your post with the custom module?
