### ISSUE TITLE
libfmt.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by brodi1** [Alexays/Waybar#812]
OS: ArchLinux
waybar (package)version: 0.9.3(-2)

waybar doesn't start anymore since I updated my system (pacman + AUR).
I tried also downgrading waybar to 0.9.3-1 & 0.9.2-3 but that also didn't help....

Here is what happens with diffrent versions of waybar (on my system):

- waybar-0.9.3-2: memory dump
- waybar-0.9.3-1: `waybar: error while loading shared libraries: libfmt.so.6: cannot open shared object file: No such file or directory`
- waybar-0.9.3-1: `waybar: error while loading shared libraries: libfmt.so.6: cannot open shared object file: No such file or directory`

I tried to reinstall fmt a couple of times and I tried to build it from source but that also didn't help....

**Comment by Alexays** [comment]
What is the version of the installed fmtlib ?

**Comment by brodi1** [comment]
@Alexays 7.0.3-1

**Comment by Alexays** [comment]
Can you try to force rebuild of the AUR package?

**Comment by brodi1** [comment]
@Alexays you mean **waybar-git** from AUR right? I just installed it and it works like a charm.... :open_mouth:

**Comment by Alexays** [comment]
Ah, I don't maintain the packaged one in the community repo, @maximbaz can you try to take a look since you're a maintainer?

**Comment by maximbaz** [comment]
Happy to help! 🙂 

> waybar-0.9.3-2: memory dump

This is a valid bug, already reported as https://github.com/Alexays/Waybar/issues/810, see there for a workaround

> waybar-0.9.3-1: waybar: error while loading shared libraries: libfmt.so.6: cannot open shared object file: No such file or directory

Downgrade is not supported because we released a new version of `fmt`, if you really want to go this path, you need to downgrade a lot more stuff, but this is not supported and you are on your own there.

I suggest just follow the workaround in #810 for now, once we find a patch I'll of course add it to community/waybar.

**Comment by brodi1** [comment]
@maximbaz I installed **waybar-0.9.3-3** and now everything works fine! Thank you very much! :+1: :smile: :+1:

**Comment by EysseW** [comment]
I have this exact issue. Both on waybar and on waybar-git both with fmt and with fmt-git. Please help!
