### ISSUE TITLE
Custom modules disappear with interval set

### ISSUE THREAD

**Issue by rgouicem** [Alexays/Waybar#815]
Hi.

Since the 0.9.3 version, some custom modules are broken. They disappear after an action is performed on them. This action can be a click or when the `interval` is reached (when `interval` is an integer).

For example, I have a daemon that checks for package updates (Arch) and writes the result in a file in json format. My waybar module only reads this file once (with `interval: "once"`) then waits to be updated when the daemon sends a signal to it. Here is the module:

```
"custom/pikaur": {
    	"format": "{}",
	"return-type": "json",
	"exec": "cat /tmp/pkg.log",
	"on-click": "pkill -USR1 pkg_daemon.sh",
	"on-click-right": "gnome-terminal -- pikaur -Syu",
	"interval": "once",
	"signal": 8,
	"tooltip": false
}
```

After a click on the module, it disappears from the bar. Removing the `interval` field fixes the problem, so I guess the problem comes from this field. On other modules with `interval` set to an integer value, I also have the same problem.

I can put the code of the `pkg_daemon.sh` script if needed, but since it happens with all custom modules with `interval` set, I don't think it is necessary.

**Comment by Alexays** [comment]
Can you try with latest master changes?
This should be fixed, i'll release a new version soon

**Comment by rgouicem** [comment]
Just tried, no problem with the master branch.

I'll be waiting for the new version then ;)
Thanks!
