### ISSUE TITLE
Locale option in clock module no longer has an effect

### ISSUE THREAD

**Issue by gebner** [Alexays/Waybar#835]
The following configuration should show the current date in French:
```json
{
  "modules-center": ["clock"],

  "clock": {
    "locale": "fr_FR.UTF-8",
    "format": "{:%d %B %Y}"
  }
}
```

This used to work in 0.9.2.  However now it prints `23 August 2020` in English (the system locale).  I believe this is due to changes in https://github.com/Alexays/Waybar/pull/715

**Comment by jmissao** [comment]
I'm having the same issue.
However, by looking at the first commit #715 , I've found that the workaround (or is it intended?) is to set "timezone" as well. Then, the format respects the locale once again.

**Comment by martin-greentrax** [comment]
@gebner @jmissao  Does this work for you now? 

```
    "clock": {
        "timezone": "Europe/Berlin",
        "locale": "de_DE.UTF-8",
        "format": "{:%A}"
    },

```
This gives me "Wednesday" while I expect the German "Mittwoch".
