### ISSUE TITLE
Custom module that executes swaylock leaves bar in weird state

### ISSUE THREAD

**Issue by EricPraline** [Alexays/Waybar#836]
System: Debian testing, up to date
sway 1.5
swaylock 1.5
swaybar v0.9.3-36-g3c5fd4b (compiled from source)

Given the following near-minimal config:
`{
    "modules-left": ["sway/workspaces"],
    "modules-right": ["custom/lock"],
    "sway/workspaces": {
        "format": "{name}"
    },
    "custom/lock": {
        "format": "Lock",
        "on-click": "swaylock"
    }
}`,
clicking on the lock module and then unlocking sway again leaves the bar in the following weird state: Everything still renders correctly, but no matter where on the bar the mouse pointer is, left clicking always executes swaylock again. The hover states of the workspace buttons are not triggered either; it feels like the lock module's "hit box" has grown to cover the entire bar.

Upon unlocking sway, waybar will sometimes, but not always, print the following message:
(waybar:13780): Gdk-WARNING **: 13:27:10.305: Couldn't map window 0x563a804a6a40 as subsurface because its parent is not mapped.

**Comment by danieldg** [comment]
Try https://github.com/danieldg/Waybar/commit/7738a601bf250e5118523ac171cdaa3e6c20e4e5 and see if it fixes this for you too. If so, it might belong in a merge request.

**Comment by EricPraline** [comment]
Thanks for your reply.
Yes, this fixes it for me.
