### ISSUE TITLE
Cursor theme issues

### ISSUE THREAD

**Issue by hughwilliams94** [Alexays/Waybar#84]
Running waybar on Sway and when the mouse hovers over the bar my cursor theme changes. The cursor is consistent in gtk and qt apps but changes when over waybar. Any idea where I need to specify the theme to ensure consistency?

**Comment by Alexays** [comment]
What is your gtk theme that I can test?

**Comment by hughwilliams94** [comment]
Breeze-gtk

**Comment by hughwilliams94** [comment]
Set using lxappearance

**Comment by hughwilliams94** [comment]
Any way I can help you troubleshoot this a little more?

**Comment by Alexays** [comment]
Hi, sorry for the delay :/
even if I put a theme to cursor it doesn't change for me, other tips?

**Comment by StaticRocket** [comment]
Did you set your cursor theme through the environmental variable `SWAY_CURSOR_THEME`?

**Comment by rustysec** [comment]
I looked at the source a few week's ago and I think the environmental variable is not implemented anymore (it was in 0.15). It now uses the system default, so setting that `Inherits` works.

**Comment by rustysec** [comment]
I looked at the source a few week's ago and I think the environmental variable is not implemented anymore (it was in 0.15). It now uses the system default, so setting that `Inherits` works.

**Comment by hughwilliams94** [comment]
Sorry to be so delayed, setting Inherits seems to have worked for me.

**Comment by aDogCalledSpot** [comment]
I'm having the same issue here but using inherits doesn't seem to work - it works for Sway but the cursor theme changes when hovering Waybar. I'm also trying to use the Breeze Cursor.

**Comment by Armoken** [comment]
I fixed it using `gsettings set $gnome-schema cursor-theme 'Qogir-dark` as it declared in 
https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland

**Comment by iambumblehead** [comment]
the cursor would shrink to a small size when hovered over waybar.  Now the cursor grows to a giant size when hovered over waybar. Does anyone know of a solution to this?

_~/.icons/default/index.theme_
```erl
[Icon Theme]
Name=Default
Inherits=Adwaita
```
