### ISSUE TITLE
Memory module tooltip is wrong and hardcoded

### ISSUE THREAD

**Issue by HarHarLinks** [Alexays/Waybar#845]
https://github.com/Alexays/Waybar/blob/44119db436da9c06d98d200f1b69411f6bd52359/src/modules/memory/common.cpp#L39

The number is in Gigabytes (or actually more likely, Gibibytes GiB), however it is formatted as Gigabits (Gb).

Further this is hardcoded here and would be nice to be able to manipulate via the usual "tooltip-format" in the config.

**Comment by Alexays** [comment]
Fixed with #587
