### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by LiteracyFanatic** [Alexays/Waybar#846]
The CPU usage of `waybar` slowly increases over time until it takes up 100% of one of my cores. The rate of increase is fairly steady at ~0.04% per minute. This started fairly recently, say within the last month or so. I've tested with `0.9.2`, `0.9.3`, and the most recent git commit and the issue is present with all of them. I don't think this was happening when `0.9.2` was the stable release, so it may be related to a dependency. I'm running an up-to-date Arch Linux with `sway v1.5`. I've attached log output from both `sway` and `waybar` as well as my config for `waybar`. The logs run until `waybar` reaches 10% CPU usage (up from an inital 0.21%) at which point I killed the process. I'm not sure whether this is relevant, but I run an `i3` session in another virtual terminal. I spend most of my time there, only switching to `sway` when I want to watch video without tearing.

```
{
    "layer": "top", // Waybar at top layer
    // "position": "bottom", // Waybar position (top|bottom|left|right)
    "height": 30, // Waybar height (to be removed for auto height)
    // "width": 1280, // Waybar width
    // Choose the order of the modules
    "modules-left": [
        "sway/workspaces",
        "sway/mode",
        "custom/media"
    ],
    "modules-center": [],
    "modules-right": [
        "network",
        "backlight",
        "pulseaudio",
        "battery",
        "clock",
        "tray"
    ],
    "sway/workspaces": {
        "disable-scroll": true,
        "all-outputs": true,
        "format": "{name}: {icon}",
        "format-icons": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "5": "調",
            "urgent": "",
            "focused": "",
            "default": ""
        }
    },
    "mpd": {
        "format": "{stateIcon} {consumeIcon}{randomIcon}{repeatIcon}{singleIcon}{artist} - {album} - {title} ({elapsedTime:%M:%S}/{totalTime:%M:%S}) ",
        "format-disconnected": "Disconnected ",
        "format-stopped": "{consumeIcon}{randomIcon}{repeatIcon}{singleIcon}Stopped ",
        "unknown-tag": "N/A",
        "interval": 2,
        "consume-icons": {
            "on": " "
        },
        "random-icons": {
            "off": "<span color=\"#f53c3c\"></span> ",
            "on": " "
        },
        "repeat-icons": {
            "on": " "
        },
        "single-icons": {
            "on": "1 "
        },
        "state-icons": {
            "paused": "",
            "playing": ""
        },
        "tooltip-format": "MPD (connected)",
        "tooltip-format-disconnected": "MPD (disconnected)"
    },
    "tray": {
        // "icon-size": 21,
        "spacing": 10
    },
    "clock": {
        "format": "{:%I:%M %p}",
        "tooltip-format": "{:%Y-%m-%d | %I:%M %p}",
        "format-alt": "{:%Y-%m-%d}"
    },
    "backlight": {
        // "device": "acpi_video1",
        "format": "{percent}% {icon}",
        "on-scroll-up": "pkexec brillo -A 5",
        "on-scroll-down": "pkexec brillo -U 5",
        "smooth-scrolling-threshold": 3,
        "format-icons": [
            "",
            ""
        ]
    },
    "battery": {
        "states": {
            // "good": 95,
            "warning": 30,
            "critical": 15
        },
        "bat": "BAT0",
        "adapter": "ADP1",
        "format": "{capacity}% {icon}",
        "format-charging": "{capacity}% ",
        "format-plugged": "{capacity}% ",
        "format-alt": "{time} {icon}",
        // "format-good": "", // An empty format will hide the module
        // "format-full": "",
        "format-icons": [
            "",
            "",
            "",
            "",
            ""
        ]
    },
    "network": {
        // "interface": "wlp2*", // (Optional) To force the use of this interface
        "format-wifi": "{essid} ({signalStrength}%) ",
        "format-ethernet": "{ifname}: {ipaddr}/{cidr} ",
        "format-linked": "{ifname} (No IP) ",
        "format-disconnected": "Disconnected ⚠",
        "format-alt": "{ifname}: {ipaddr}/{cidr}"
    },
    "pulseaudio": {
        "scroll-step": 5, // %, can be a float
        "smooth-scrolling-threshold": 3,
        "format": "{volume}% {icon} {format_source}",
        "format-bluetooth": "{volume}% {icon} {format_source}",
        "format-bluetooth-muted": " {icon} {format_source}",
        "format-muted": " {format_source}",
        "format-source": "",
        "format-source-muted": "",
        "format-icons": {
            "default": [
                "",
                "",
                ""
            ]
        },
        "on-click": "pavucontrol"
    }
}
```
[sway.log](https://github.com/Alexays/Waybar/files/5154023/sway.log)
[waybar.log](https://github.com/Alexays/Waybar/files/5154024/waybar.log)

**Comment by eoli3n** [comment]
High CPU usage here too, i use sway on 3 displays but not too little intervals so,
![waybar](https://user-images.githubusercontent.com/14223657/98436435-82d73280-20db-11eb-83aa-0684ff42bd01.png)

[config, modules, waybar.sh](https://github.com/eoli3n/dotfiles/tree/master/roles/waybar/files/waybar)
##### Logs
```
** (waybar:3852298): WARNING **: 09:25:33.069: Status Notifier Item with bus name ':1.4' and object path '/org/ayatana/NotificationItem/variety' is already registered
[2020-11-07 09:25:33.381] [info] Bar configured (width: 1920, height: 18) for output: DP-3
[2020-11-07 09:25:33.381] [info] Bar configured (width: 1920, height: 18) for output: DP-3
[2020-11-07 09:25:33.381] [info] Bar configured (width: 1371, height: 18) for output: eDP-1
[2020-11-07 09:25:33.381] [info] Bar configured (width: 1371, height: 18) for output: eDP-1
[2020-11-07 09:25:33.381] [info] Bar configured (width: 1920, height: 19) for output: DP-2
[2020-11-07 09:25:33.381] [info] Bar configured (width: 1920, height: 18) for output: DP-2
[2020-11-07 09:25:33.393] [info] Bar configured (width: 1371, height: 18) for output: eDP-1
[2020-11-07 09:25:33.395] [info] Bar configured (width: 1371, height: 18) for output: eDP-1
==> ERROR: Cannot fetch updates
```

**Comment by davidthewatson** [comment]
I'm seeing this also running Sway on Garuda Linux:

![2022-03-11T12:54:14,221601080-05:00](https://user-images.githubusercontent.com/150892/157923511-7cdd94e2-ade3-459e-a429-6e9598d01adf.png)

I can provide more details, FWIW:

     watson@acer in ~ took 17s
     λ sway --version
    sway version 1.7
    
     watson@acer in ~ took 14ms
     λ uname -a
    Linux acer-swift-silver 5.16.13-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 08 Mar 2022 20:07:38 +0000 x86_64 GNU/Linux

**Comment by ovk** [comment]
Same issue with Sway & Arch Linux.

**Comment by eguiraud** [comment]
I'm also on Arch + Sway and I _do not_ see this (waybar is at basically 0% CPU usage after 8 hours of uptime) -- it might depend on some particular widgets. My configuration is:

```
{
	"layer": "top",
	"position": "bottom",

	"modules-left": [
		"sway/workspaces",
		"custom/right-arrow-dark"
	],
	"modules-center": [
		"custom/left-arrow-dark",
		"clock#1",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"clock#2",
		"custom/right-arrow-dark",
		"custom/right-arrow-light",
		"clock#3",
		"custom/right-arrow-dark"
	],
	"modules-right": [
		"custom/left-arrow-dark",
		"pulseaudio",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"memory",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"cpu",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"battery",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"disk",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"tray"
	],

	"custom/left-arrow-dark": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-light": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-dark": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-light": {
		"format": "",
		"tooltip": false
	},

	"sway/workspaces": {
		"disable-scroll": true,
		"format": "{name}"
	},

	"clock#1": {
		"format": "{:%a}",
		"tooltip": false
	},
	"clock#2": {
		"format": "{:%H:%M}",
		"tooltip": false
	},
	"clock#3": {
		"format": "{:%b %d}",
		"tooltip": false
	},

	"pulseaudio": {
		"format": "{icon} {volume:2}%",
		"format-bluetooth": "{icon} {volume}%",
		"format-muted": "MUTE",
		"format-icons": {
			"headphones": "",
			"default": [
				"",
				""
			]
		},
		"scroll-step": 5,
		"on-click": "pamixer -t",
		"on-click-right": "pavucontrol"
	},
	"memory": {
		"interval": 5,
		"format": " {}%"
	},
	"cpu": {
		"interval": 5,
		"format": " {load}"
	},
	"battery": {
		"states": {
			"good": 90,
			"warning": 20,
			"critical": 10
		},
		"format": "{icon} {capacity}%",
		"format-icons": [
			"",
			"",
			"",
			"",
			""
		]
	},
	"disk": {
		"format": " {free}",
	},
	"tray": {
		"icon-size": 25
	}
}
```

**Comment by Chedski** [comment]
I've been experiencing this issue myself, and it seems to be related to CSS animations.

**Comment by Chedski** [comment]
I tested a few things, it only happens when something is animated with CSS. Using the exact same CSS code (with some changes to selectors) in other similar applications (specifically, [eww](https://github.com/elkowar/eww)) doesn't cause this high CPU usage, so it does seem to be specific to waybar.

**Comment by LOSEARDES77** [comment]
This still happening thes days my cpu jumps to 90C and the solution i found was adding with cron a script to reload the bar

**Comment by The-Toblin** [comment]
Taking out any mentions of `animation` in `style.css` reduces the CPU usage from ~300% to around ~92%. Still unacceptably high. It will also still spike to several hundred percent every now and then. I've seen spikes, lasting 10-15 seconds, of over 400% CPU use, indicating it's using several cores.

**Comment by LOSEARDES77** [comment]
> Taking out any mentions of `animation` in `style.css` reduces the CPU usage from ~300% to around ~92%. Still unacceptably high. It will also still spike to several hundred percent every now and then. I've seen spikes, lasting 10-15 seconds, of over 400% CPU use, indicating it's using several cores.

i did remove every css animation and transition just in case and still spiking on my laptop so i might just use other bar for safty if but thanks for your response!

**Comment by The-Toblin** [comment]
> i did remove every css animation and transition just in case and still spiking on my laptop so i might just use other bar for safty if but thanks for your response!
I'm not convinced that the CSS animations are the culprit. It's likely something else behind the scenes going wrong. For now, I have disabled my bar and might start using an alternative for the time being, but I do like waybar and I would like to go back to it when it isn't eating my power bill :)

So, developer, if you need anything from us, please let us know and we'll provide.

**Comment by eoli3n** [comment]
I think a new bug is occurring, as I faced the same issue again today, after an upgrade (latest from archlinux).

**Comment by LOSEARDES77** [comment]
I just comed back to arch and on the latest version so maybe it is

**Comment by The-Toblin** [comment]
I just installed `0.9.24-1` on ArchLinux and for now, the problem seems to be gone for me. Still haven't added animations back, but the idle CPU use of waybar is completely negligable atm. 0.2%.

**Comment by eguiraud** [comment]
The new problem was https://github.com/Alexays/Waybar/issues/2631, fixed in 0.9.24-1

**Comment by Chedski** [comment]
Has anyone checked to make sure the CPU usage with CSS animations was fixed?

**Comment by minsoehan** [comment]
I have same issue. the waybar take cpu up to 90-100% suddenly. I use Arch+sway+waybar.

**Comment by KyleGeil** [comment]
i have the same problem but when i removed the "memory" module it went back to normal

**Comment by Niron68** [comment]
Waybar take 30% of my cpu when i use modules with css animations

**Comment by otaviojr** [comment]
Yes, impressive, here it consumes 30% per custom module.. those modules using custom/xxx.

If I disable all custom/xxx modules everything gets back to normal.

So, right now, I believe that the problem lies with custom modules in general...

The modules timeout does nothing.. I tried to increase them, decrease them... no changes... 30% of cpu usage per module...

**Comment by otaviojr** [comment]
I solved my case with custom modules...

Now it appears something so dummy...

the update script can not send rfkill signal... which make no sense, because the component will already update after calling the script...

But... I did it...

And when you do it, the signal will wake up that thread from his sleeping every time, which will cause the high CPU usage, because the thread will never sleep...

I will let that here, you know, maybe someone else could have this amazing idea... send rfkill signal from the update script itself....

**Comment by ayuuuvauuu** [comment]
+1
