### ISSUE TITLE
[Feature Request] - tooltip-format for pulseaudio module

### ISSUE THREAD

**Issue by returntrip** [Alexays/Waybar#853]
I use two `pulseaudio` modules: one for input and one for output. It would be great if the tooltip for the input could show the source instead of the description of the currently selected output.

**Comment by kamushadenes** [comment]
Same here, also different classes for sink mute and source mute would be awesome!

**Comment by OJFord** [comment]
`tooltip-format` seems to have been added in #974 linked above.

**Comment by returntrip** [comment]
Closed by #974 . Thanks @kamushadenes!
