### ISSUE TITLE
clock module not working

### ISSUE THREAD

**Issue by busywhistling** [Alexays/Waybar#854]
Hi, I recently reinstalled Arch (hence there's a chance I might've missed some essential configuration) and right now the clock module is not working with waybar. I get the following error:
```bash
[2020-09-09 15:21:34.659] [error] clock: Could not get current timezone
```
I saw the troubleshooting section in the wiki, and added `LC_TIME=en_US.UTF-8` to my `/etc/locale.conf`.
Could someone point me in the direction to resolve this? Thanks.

**Comment by FreeFull** [comment]
You can list available timezones with `timedatectl list-timezones` and set a timezone with `timedatectl set-timezone Zone/SubZone` or `ln -sf /usr/share/zoneinfo/Zone/SubZone /etc/localtime`, probably as the root user.
Reference: https://wiki.archlinux.org/index.php/System_time#Time_zone

**Comment by busywhistling** [comment]
That works perfectly! Thanks!
