### ISSUE TITLE
Clock set with "interval": "1" only updates every minute

### ISSUE THREAD

**Issue by jeffmakes** [Alexays/Waybar#856]
Hi,

Thanks for this great tool!

I'm running Waybar 0.9.3 on Sway 1.4 on Fedora 32.
I would like a seconds display on my clock. This is my config:

    "clock": {
        // "timezone": "America/New_York",
        "interval": "1",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": "{:%Y-%m-%d}",
        "format": "{:%A %e %B %Y %H:%M:%S}"
    },

That time format outputs correctly, but only updates every minute.

Any thoughts?
Cheers,
Jeff

**Comment by alebastr** [comment]
Interval accepts only integer values or `"once"`. Everything else is ignored.
`"interval": 1` (without quotes) should work.

**Comment by jeffmakes** [comment]
Thanks @alebastr, that's what I was missing.
