### ISSUE TITLE
 [ISSUE] DISCORD AND DISCORD BETA NOT SHOWING UP IN TRAY

### ISSUE THREAD

**Issue by Ultra-Hax** [Alexays/Waybar#864]
Discord and discord beta/pta is not showing up in tray please fix this issue

**Comment by FreeFull** [comment]
Any details on how to reproduce this, or error messages? Discord does show a tray icon for me, and there's no way to fix the issue without knowing what's causing it.

**Comment by Ultra-Hax** [comment]
to reproduce this open up discord and it wont show in the tray

**Comment by Ultra-Hax** [comment]
wait discord shows a icon for u?

**Comment by Ultra-Hax** [comment]
i have system tray in my waybar

**Comment by Ultra-Hax** [comment]
so y discord not showing for me but i shows for u

**Comment by Ultra-Hax** [comment]
my os is artix linux openrc

**Comment by Ultra-Hax** [comment]
wait i realized u cant ssee it in system tray but its there

**Comment by scaryrawr** [comment]
Are you setting `XDG_SESSION_TYPE` and `XDG_CURRENT_DESKTOP`?

In my sway config I have:
```sh
exec export XDG_SESSION_TYPE=wayland
exec export XDG_CURRENT_DESKTOP=sway
```

**Comment by FreeFull** [comment]
> Are you setting `XDG_SESSION_TYPE` and `XDG_CURRENT_DESKTOP`?
> 
> In my sway config I have:
> 
> ```shell
> exec export XDG_SESSION_TYPE=wayland
> exec export XDG_CURRENT_DESKTOP=sway
> ```

Note that exporting env variables inside your sway config doesn't do anything. You have to actually export those environment variables before you start sway.

**Comment by scaryrawr** [comment]
> > Are you setting `XDG_SESSION_TYPE` and `XDG_CURRENT_DESKTOP`?
> > In my sway config I have:
> > ```shell
> > exec export XDG_SESSION_TYPE=wayland
> > exec export XDG_CURRENT_DESKTOP=sway
> > ```
> 
> Note that exporting env variables inside your sway config doesn't do anything. You have to actually export those environment variables before you start sway.

That's what I've read, but oddly it works for the tray icons for me.
