### ISSUE TITLE
Newline (\n) shown as icon in CPU and MEMORY modules.

### ISSUE THREAD

**Issue by dron1885** [Alexays/Waybar#865]
On Arch Linux update 0.9.4 changed behavior for (at least) `cpu` and `memory` modules.

How it set up in config:
```
   "cpu": {
        "interval": 3,
        "format": "CPU\n{}%",
        "max-length": 10
    },
    "memory": {
        "interval": 3,
        "format": "RAM\n{}%",
        "max-length": 10
    }
```

Output for 0.9.3:
![Screenshot_200924_152115](https://user-images.githubusercontent.com/45915083/94144284-9e62e280-fe79-11ea-93fe-2cd5e1f4e989.png)

Output for 0.9.4:
![Screenshot_200924_152233](https://user-images.githubusercontent.com/45915083/94144426-c81c0980-fe79-11ea-91df-95785a941cc4.png)

As I use side position it's quite noticeable.
A `pulseaudio` and `clock` modules are giving correct output for a \n in both versions.

**Comment by alebastr** [comment]
#828. Removing `max-length` from the module configuration should restore the old behavior.

Skipping `set_single_line_mode` for vertical bars could a good idea, but to achieve that modules need to be aware of the bar position.

**Comment by hissssst** [comment]
Experiencing the same issue
