### ISSUE TITLE
Minimum `fmt` version is wrong.

### ISSUE THREAD

**Issue by ericonr** [Alexays/Waybar#871]
I get linking errors when using fmt version 6.2.1, which went away when updating to 7.0.3. The version in meson is `>=5.3.0`, which is almost certainly wrong.

**Comment by ericonr** [comment]
Hmm this might instead be due to the relationship between spdlog and fmt, actually.

**Comment by Alexays** [comment]
Seems a problem with spdlog yeah

**Comment by ericonr** [comment]
I think this one should probably be brought up with upstream spdlog instead, so I will close it for now.

Thanks!
