### ISSUE TITLE
Add support for Wayfire

### ISSUE THREAD

**Issue by alexherbo2** [Alexays/Waybar#872]
[Wayfire]

[Wayfire]: https://wayfire.org

**Comment by bluebyt65** [comment]
It's working with Wayfire you can set Waybar to start automatically  in the file wayfire.ini
[autostart]
bar = waybar

You can see it in action:
https://www.youtube.com/watch?v=gWzuFT7Muss&ab_channel=BrunoSt-Gelais

**Comment by alexherbo2** [comment]
How do you see the windows?

**Comment by bluebyt65** [comment]
Sorry I don't understand the question, can you elaborate?

**Comment by Alexays** [comment]
Wayfire is already supported.
If you encounter problems to make it work, do not hesitate to reopen and give more details.
