### ISSUE TITLE
Fallback font size

### ISSUE THREAD

**Issue by yorickvP** [Alexays/Waybar#876]
Since my update to waybar b9f83dc7, my waybar has been changing size a lot, when any emoji happens to be in the text.
Normal size: ![](https://pub.yori.cc/s/yGB500e2dOwg_201006110820.png)
Bar size with emoji: ![](https://pub.yori.cc/s/0mq320NnbVRi_201006110927.png)

**Comment by yorickvP** [comment]
Update: bisecting this in nixpkgs-wayland leads to https://github.com/colemickens/nixpkgs-wayland/commit/2a1e32ec84e9fa575a138d5d81c24e5440c9caa5, which leaves 1310 package updates left to test

**Comment by yorickvP** [comment]
This is a distro fontconfig issue, I'll move it there!

**Comment by skylize** [comment]
@yorickvP Been having the same problem. Could you link to wherever you moved this issue? or share a solution if you found one? Thanks

**Comment by yorickvP** [comment]
Hi! This issue was caused by mismatching between the installed fontconfig library version and the fontconfig data. Rebooting fixed it for me.
