### ISSUE TITLE
clock module should reuse default timezone (`TZ` or `/etc/localtime`)

### ISSUE THREAD

**Issue by lanodan** [Alexays/Waybar#878]
After updating to Waybar 0.9.3 (with plus rfkill+sndio) I ended up with the following error and the clock module simply being absent from the bar:
```
[2020-10-08 05:49:13.955] [error] clock: Could not get current timezone
```

I fixed it by copying my timezone into the config but this isn't something I should have to do, it should fallback to the `TZ` environment variable and then `/etc/localtime`.

**Comment by LukashonakV** [comment]
Hi @lanodan can you check again please? It was implemented at https://github.com/Alexays/Waybar/pull/2001

**Comment by LukashonakV** [comment]
Hi @lanodan , up

**Comment by lanodan** [comment]
Doesn't seems to be fixed, at least I'm getting the same error on f29a400c97d6cc339c5be2ca6c5467c04323b766

That is:
	[2023-03-02 01:59:29.303] [warning] module clock: Disabling module "clock", Could not get current timezone

(At least the logs do follow the timezone information)

**Comment by LukashonakV** [comment]
Hi @lanodan , can you please:
1. Provide waybar config
2. Provide Linux OS you're using
Thanks
