### ISSUE TITLE
Workspace order wrong if all-outputs == true

### ISSUE THREAD

**Issue by David96** [Alexays/Waybar#88]
Hey,
first of all, thanks for this cool status bar!

So as you might have noticed I just spent some time fixing some issues with the workspace module but this appears to be one I don't know how to fix.

The bug: if you open workspace 1 and 3 on output 1 and then workspace 2 on output 2, they are ordered 1 - 3 - 2.

To me this actually seems like an issue with GTK rather than your code. The calls to box_.reorder_child seem to be correct to me. I added some debugging and they always call the function with the right number for the corresponding workspace. Only GTK seems to ignore this number as the workspaces are always shown in the order they are received from the IPC command and that orders them by output. Sadly I couldn't find much information as to how reorder_child is to be used.

A solution would most likely be to create an ordered list from the workspaces_ Json Value but that seems suboptimal to me.

**Comment by Alexays** [comment]
Fixed in add9e925f4f242e37f6a5e50aaabcf9acbcb4eae
But I think the workspace module needs to be rewritten to be more optimized
