### ISSUE TITLE
TravisCI status is no longer visible

### ISSUE THREAD

**Issue by jbeich** [Alexays/Waybar#885]
Looking at new commits and pull requests CI status icon is either missing or permanently yellow (aka "Expected: waiting for status to be reported"). However, https://travis-ci.org/github/Alexays/Waybar/pull_requests seems fine. Can you try to re-install Travis via [marketplace](https://github.com/marketplace/travis-ci)?

See also https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

**Comment by Alexays** [comment]
Should be done, thanks for the report!
