### ISSUE TITLE
Waybar shows wrong calendar week

### ISSUE THREAD

**Issue by m4xxed** [Alexays/Waybar#894]
Waybar shows week W42 in clock module, even though it is currently week W43.

my clock module: 

"clock": {
"interval": 1,
"format-alt": " {:%H:%M:%S}",
"format": "{: W%W - %a. %d.%m.%Y - %H:%M:%S}",
},

**Comment by m4xxed** [comment]
After further testing with:
"format": "{: W%OW - %a. %d.%m.%Y - %H:%M:%S}",
 the issue persists.

My current workaround is just to add a +1 behind the output to remind me of the offset:
"format": "{: W%W+1 - %a. %d.%m.%Y - %H:%M:%S}",

**Comment by m4xxed** [comment]
I might have figured it out: 

The issue might be that the calculation of the first week is as follows:

"The week number of the year as a decimal number. The first Monday of the year is the first day of week 01. Days of the same year prior to that are in week 00. If the result is a single digit, it is prefixed with 0. The modified command %OW produces the locale's alternative representation." (source: https://howardhinnant.github.io/date/date.html#to_stream_formatting)

However the first calendar week in Germany is defined as the first week of the year that holds at least 4 days of the new year. This year, that would be one week earlier, which leads to this week officially being the 43th week, but the first Monday fell on the week afterwards, hence it calculates that this is the 42nd week.

Not sure if you can do anything about it, but at least now we know (if you weren't already aware of the issue).

**Comment by olemartinorg** [comment]
You can have it use ISO week numbers with `%V`. Different parts of the world use different methods for calculating the week number.

**Comment by m4xxed** [comment]
That is a good idea, I totally overlooked that option. Thank you, I'll close the issue now.
