### ISSUE TITLE
Battery module doesn't work with format-icons object

### ISSUE THREAD

**Issue by 0xdec** [Alexays/Waybar#896]
Using the following configuration for the battery module, nothing is displayed during either charging or discharging. I had a good look through `ALabel.cpp` and I'm pretty sure this config should work just fine, but nothing shows up. If I change `"default"` to `"discharging"`, then the capacity percentage at least shows while charging or discharging, but no icons are shown. If I replace `format-icons` with a plain array of icons, then everything works fine, but I'd like to have a different array depending on the battery status (charging/discharging).

```jsonc
"battery": {
        "bat": "BAT0",
        "adapter": "AC",
        "states": {
            // "good": 95,
            "warning": 25,
            "critical": 15
        },
        "format": "{icon} {capacity}%",
        "format-icons": {
            "default": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"],
            "charging": ["󰢟", "󰢜", "󰂆", "󰂇", "󰂈", "󰢝", "󰂉", "󰢞", "󰂊", "󰂋", "󰂅"]
        }
    }
```

**Comment by heiserhorn** [comment]
maybe I am wrong but  changig fmt::arg("icon", getIcon(capacity, state)) to fmt::arg("icon", getIcon(capacity, status)) on line 183 in src/modules/battery.cpp should work. Now the question is: is the currenly implemented behavior the desired one or not..only the dev can say.

**Comment by Alexays** [comment]
Weird this should be fixed a long time ago,
https://github.com/Alexays/Waybar/blob/14a6cec6d1dbcd6e9a5cd64d8b0ca69c17a7b1e1/src/modules/battery.cpp#L204
And the line you referencing @heiserhorn doesnt exsit anymore :/

**Comment by heiserhorn** [comment]
yes @Alexays I mistakenly referenced a previous version.

What should be the syntax then to have two different sets of icons for example for charging vs default?

**Comment by 0xdec** [comment]
The strange thing is that I believe the relevant code is the same for pulseaudio and battery, yet the former works while the latter does not.
