### ISSUE TITLE
Waybar doesn't start anymore

### ISSUE THREAD

**Issue by bluebyt65** [Alexays/Waybar#897]
Gnome 3.38
Wayfire version 0.5.0-e92f43a
Wlroots-git 0.11.0.r69.g79c7591d-1

> waybar
[2020-10-24 07:43:32.979] [info] Resources files: /home/bluebyt/.config/waybar/config, /home/bluebyt/.config/waybar/style.css
[2020-10-24 07:43:58.012] [warning] Using different foreign toplevel manager protocol version: 3
[2020-10-24 07:43:58.018] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
Gdk-Message: 07:43:58.036: Error 2 (No such file or directory) dispatching to Wayland display.
wc: write error

**Comment by bluebyt65** [comment]
If you disable the taskbar module, waybar is ok.

**Comment by alebastr** [comment]
@bluebyt65 can you please test #898? I confirmed that it fixes the issue on sway, but I don't have wayfire.

**Comment by bluebyt65** [comment]
Hello alebastr, I just try the branch: https://github.com/alebastr/Waybar/tree/fix-globals-versions
But I have the same problem.
waybar
[2020-10-25 15:05:09.050] [info] Resources files: /home/bluebyt/.config/waybar/config, /home/bluebyt/.config/waybar/style.css
[2020-10-25 15:05:09.064] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
Gdk-Message: 15:05:09.083: Error 2 (No such file or directory) dispatching to Wayland display.
wc: write error  
Thanks for working of this!

**Comment by alebastr** [comment]
>  Wayfire version 0.5.0-e92f43a

Right... you may also need https://github.com/WayfireWM/wayfire/commit/4deab08abe9f1e9b35f1215f06b5a6e9d9518c01. Before this commit (a few hours ago) it was unconditionally sending `parent` event despite the protocol version negotiated by the client.
And if that doesn't help, please run `env WAYLAND_DEBUG=client your/build/of/waybar` and attach the output to the issue.

Meanwhile I'll add a dummy event handler to the PR to make sure that this can't happen.

**Comment by Alexays** [comment]
> > Wayfire version 0.5.0-e92f43a
> 
> Right... you may also need [WayfireWM/wayfire@4deab08](https://github.com/WayfireWM/wayfire/commit/4deab08abe9f1e9b35f1215f06b5a6e9d9518c01). Before this commit (a few hours ago) it was unconditionally sending `parent` event despite the protocol version negotiated by the client.
> And if that doesn't help, please run `env WAYLAND_DEBUG=client your/build/of/waybar` and attach the output to the issue.
> 
> Meanwhile I'll add a dummy event handler to the PR to make sure that this can't happen.

Hmm, I was too fast to merge? 😄
