### ISSUE TITLE
[Feature Request] Support (and/or documentation) for tooltip styling with CSS

### ISSUE THREAD

**Issue by FjorgeTheHuman** [Alexays/Waybar#904]
I haven't been able to find any documentation about formatting tool tips on the wiki. I think this would be a useful feature for a more uniform look in Waybar. If it's already a feature, then please add some documentation for it. Thanks!

**Comment by trobjo** [comment]
You can probably style the toolbars for Waybar exclusively, but you can also use the global css stylesheet in ~/.config/gtk-3.0/gtk.css 

My settings are: 

```

tooltip {
    background: @theme_base_color;
    background-clip: padding-box;
    border-color: alpha(@unfocused_borders, 0.8);
    border-radius: 2px;
    box-shadow: 0 1px 2px 1px alpha(mix(@theme_base_color, #000000, 0.5), 0.25);
}

tooltip label {
    color: mix(@theme_text_color, #ffffff, 0.25);
    padding: 4px;
    text-shadow: none;
}
```

**Comment by FjorgeTheHuman** [comment]
Ah that worked! Thanks!
