### ISSUE TITLE
Clicking Tray Crashes Waybar

### ISSUE THREAD

**Issue by ibrokemypie** [Alexays/Waybar#908]
The [wayland fork of obs-studio](https://aur.archlinux.org/packages/obs-studio-wayland/) places a seemingly broken tray icon in the tray, and clicking the icon results in a segfault with a core dump logged in journalctl. This is with waybar v0.9.4-64-gfaacd76 (branch 'master')

**Comment by cryptoluks** [comment]
Could you provide a backtrace with gdb to check where it crashes?

Kill waybar and restart it through `gdb` with `gdb waybar`, type `run` into the `gdb` shell and provoke the crash. Continue with enter in the `gdb` shell and you should see the backtrace.
