### ISSUE TITLE
Build failed meson.build:12:0: ERROR:  Module "fs" does not exist

### ISSUE THREAD

**Issue by hugosxm** [Alexays/Waybar#909]
Hi,

thanks for waybar, i've been using it since my switch from i3 to sway, it is a really great status bar !

I wanted to update it so i git a git pull and meson build but i ran into this : 

`╰meson build                                    
The Meson build system
Version: 0.49.2
Source dir: /home/xxx/GIT/Waybar
Build dir: /home/xxx/GIT/Waybar/build
Build type: native build
Project name: waybar
Project version: 0.9.4
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Native C++ compiler: c++ (gcc 8.3.0 "c++ (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:12:0: ERROR:  Module "fs" does not exist`

I'm on debian 10.6, all packages for dependencies are up to date following this : 

`sudo apt install \
  clang-tidy \
  gobject-introspection \
  libdbusmenu-gtk3-dev \
  libfmt-dev \
  libgirepository1.0-dev \
  libgtk-3-dev \
  libgtkmm-3.0-dev \
  libinput-dev \
  libjsoncpp-dev \
  libmpdclient-dev \
  libnl-3-dev \
  libnl-genl-3-dev \
  libpulse-dev \
  libsigc++-2.0-dev \
  libspdlog-dev \
  libwayland-dev \
  scdoc`

Did i miss something ?

Thnaks by advance

**Comment by alebastr** [comment]
One of the recent changes (https://github.com/Alexays/Waybar/commit/73681a30e5ad70a3308b883deedd2b5ad694d8c6) added the code that relies on meson >= 0.53.0.

You can try replacing `basename = fs.name(path)` with something regex-based and getting rid of the `fs` import.

**Comment by hugosxm** [comment]
Thanks, updated meson and did a git clone in a new folder did the trick !
