### ISSUE TITLE
[Clock] Question: Calendar font (proportional vs. monospace) and localization

### ISSUE THREAD

**Issue by kanyck** [Alexays/Waybar#910]
The calendar font is defaulted to some proportional one. Obviously it should be monospace in order the numbers to be aligned properly. Couldn't find any CSS to change this...
Also, it shows month in English thus doesn't respect current locale settings.

**Comment by jsteinaker** [comment]
I don't use a CJK locale (spanish speaker here) but, using the last git version:

1) calendar font is monospaced for me
2) month and days of the week are shown in spanish

With #976 closed, I think it's pretty safe to say this issue is fixed now.

**Comment by LukashonakV** [comment]
Hi @kanyck , calendar font can be configured through style.css or using the direct pango style format for each calendar section. See [Clock module](https://github.com/Alexays/Waybar/wiki/Module:-Clock)
Can you get the freshest release and check again. If it's Ok please close the issue as resolved. Thank you

**Comment by kanyck** [comment]
Thanks!
