### ISSUE TITLE
module bluetooth: Unknown module: bluetooth

### ISSUE THREAD

**Issue by cristobaltapia** [Alexays/Waybar#914]
Hi,
I installed the latest git version of Waybar in Archlinux and I am getting this error:

```
[2020-11-06 10:08:58.333] [warning] module bluetooth: Unknown module: bluetooth
```

It used to work some time ago, but for a while (I don't know exactly how long) the bluetooth module does not work anymore.

**Comment by cryptoluks** [comment]
Hi,

for me it also doesn't work. Maybe this commit broke it as it gets excluded from build:

https://github.com/Alexays/Waybar/commit/fdfb60c633681908e81337ce793350588add2478#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4

I'm not an expert regarding the meson build stuff, but probably you could just replace `get_option('rfkill').enabled()` with `get_option('rfkill').auto()` to force building of bluetooth module: https://github.com/Alexays/Waybar/blob/05b12602d4f1fde4c13309a0b3a70afb010d3231/meson.build#L230

**Comment by Alexays** [comment]
Hi, that's weird cause rfkill is defined as auto here
https://github.com/Alexays/Waybar/blob/05b12602d4f1fde4c13309a0b3a70afb010d3231/meson_options.txt#L10

**Comment by alebastr** [comment]
`auto` and `enabled` are different states of feature (unless `--auto-features=enabled` is specified).
The check should probably look like `if is_linux and not get_option('rfkill').disabled()`

**Comment by maximbaz** [comment]
By the way we do specify `--auto-features=enabled` when building the Arch package, and bluetooth module works for me with `0.9.4-3` 🤔 Is it possible that some dependency is missing that I happened to have locally?

**Comment by guanghwang** [comment]
The `aur` package might be the cause. After I switch from the latest git version to the community version on Arch, Bluetooth module works. I noticed that the `aur` version is built without `rfkill` support.

**Comment by cristobaltapia** [comment]
@guanghwang That't true. I also noticed that. I forgot to close the issue though. Closing now.
