### ISSUE TITLE
wlr/taskbar doesn't work

### ISSUE THREAD

**Issue by snakedye** [Alexays/Waybar#916]
It's completely nonfunctional on stable release on Arch and haft work on the git version.

On the git version, only the title of the first app open shows up.

[waybar.log](https://github.com/Alexays/Waybar/files/5541435/waybar.log)

**Comment by nboughton** [comment]
I'm seeing the same thing. Also on Arch using the community/waybar package.

**Comment by ManiaciaChao** [comment]
Wasn't it already fixed in https://github.com/Alexays/Waybar/pull/898? Package `aur/waybar-git` works for me.
![image](https://user-images.githubusercontent.com/13493748/99909780-7383f600-2d25-11eb-8fba-f0e5f6d2e42f.png)

**Comment by nboughton** [comment]
waybar-git fixes it for me.

**Comment by Alexays** [comment]
I'll release a new version soon with the fix :)
