### ISSUE TITLE
left bar width ignored from config

### ISSUE THREAD

**Issue by japhir** [Alexays/Waybar#919]
I'm trying to configure a single secondary bar, that displays on the left side of the screen with a single module in it that simply tracks the number of tasks in a file (my GTD Inbox file).

The problem I have, is that the bar is created at 1920x1080 in stead of my desired 24x1080. This means it overlaps with everything and I effectively cannot use that screen anymore. I end this by `> killall waybar`.

Here's the config:

```
// -*- mode: json -*-
{
    "layer": "left",
    "height": 1080,
    "width": 24,
    "output": "eDP-1",
    "modules-left": ["custom/inbox"],

    "custom/inbox": {
	"format": "{}",
	"interval": 30,
	"exec": "/home/japhir/bin/inboxsize",
	"on-click": "emacsclient -c ~/org/inbox.org",
	"rotate": 90,
        "max-length": 200,
        "states": { // in the future I might want to colour the bars according to this?
	    "good": 0,
            "warning": 20,
            "critical": 100
	},
    },
}
```

with this exec part for the module:

```
#!/usr/bin/bash
size=$(cat ~/org/inbox.org | grep "^*" | wc -l)
# size=3
start=1
for (( c=$start; c<=$size; c++ ))
do
    echo -n "█"
done
echo ""
```

I felt so proud hacking this together :)

**Comment by japhir** [comment]
If I don't specify any height/width, it doesn't draw a bar. If I specify only the 

``` 
[2020-11-20 20:11:26.132] [info] Bar configured (width: 1920, height: 1080) for output: eDP-1
```

**Comment by JordanL2** [comment]
Try:
```
"layer": "top",
"position": "left",
```

It seems you mixed up layer and position - layer is whether it's in front of, or behind, other windows.
https://github.com/Alexays/Waybar/wiki/Configuration

**Comment by japhir** [comment]
Thanks! It's working as desired now!
