### ISSUE TITLE
PulseAudio volume change via scoll is super slow

### ISSUE THREAD

**Issue by Robinhuett** [Alexays/Waybar#92]
As mentioned [here](https://github.com/Alexays/Waybar/blob/2d2fb8804068770c604293e9128fc59b6b962e43/src/modules/pulseaudio.cpp#L77-L78), the change value doesn't seem to be the same for everyone.
And since PulseAudio doesn't seem to provide min & max values the easiest would be to let the user set a step size.

This could be done by replacing line 78 
https://github.com/Alexays/Waybar/blob/2d2fb8804068770c604293e9128fc59b6b962e43/src/modules/pulseaudio.cpp#L77-L78
with something like this: 
```cpp
uint16_t change = config_["scroll-resolution"].isUInt() ? config_["scroll-resolution"].asUInt() : 100;
```

I can open a PR for this, but wanated to open an issue fist, in case there are better ideas how to haandle this.

**Comment by Alexays** [comment]
Yeah, maybe we can call it "scroll-step" and so multiply the value by 100?

**Comment by Robinhuett** [comment]
I like `scroll-step`, it's short and I think pretty self-explanatory.
Also the Idea to multiply by 100 is cool :)
