### ISSUE TITLE
wlr/taskbar: polkit-gnome-authentication-agent-1 window crashes waybar

### ISSUE THREAD

**Issue by cryptoluks** [Alexays/Waybar#922]
Hi,

if `wlr/taskbar` is active in waybar config, the dialog from `polkit-gnome-authentication-agent-1` crashes waybar. Even with `waybar --log-level trace` there can only be the segfaul observed:

```
[2020-11-24 13:45:52.994] [debug] Task (7) user: systemctl daemon-reload [Mate-terminal] <AMif> changed
[1]    9186 segmentation fault (core dumped)  waybar --log-level trace
```

The dialog can be triggered with for example running `systemctl daemon-reload` as a user.

When removing `wlr/taskbar` from modules, no crash happens at all.

Thanks.

**Comment by clapbr** [comment]
Can confirm this.

**Comment by cryptoluks** [comment]
I captured a backtrace with `gdb`:

```
#0  0x00007ffff78a1cda in Gio::Icon::to_string[abi:cxx11]() const () at /usr/lib/libgiomm-2.4.so.1
#1  0x00005555555dc511 in  ()
#2  0x00005555555dd18b in  ()
#3  0x00005555555ddd12 in  ()
#4  0x00007ffff64b8acd in  () at /usr/lib/libffi.so.7
#5  0x00007ffff64b803a in  () at /usr/lib/libffi.so.7
#6  0x00007ffff7f96e92 in  () at /usr/lib/libwayland-client.so.0
#7  0x00007ffff7f936c1 in  () at /usr/lib/libwayland-client.so.0
#8  0x00007ffff7f94ccc in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#9  0x00007ffff6ecd475 in  () at /usr/lib/libgdk-3.so.0
#10 0x00007ffff6e9315b in gdk_display_get_event () at /usr/lib/libgdk-3.so.0
#11 0x00007ffff6ed2ca4 in  () at /usr/lib/libgdk-3.so.0
#12 0x00007ffff6b6c914 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff6bc07d1 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff6b6b121 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff6d72d1e in g_application_run () at /usr/lib/libgio-2.0.so.0
#16 0x000055555557fa3a in  ()
#17 0x000055555557ecac in main ()
```

So obviously no symbols are resolving for the waybar stuff, but at the `to_string` method of `libgiomm` library it seems to crash. This functions seems to be called in `taskbar.cpp` here: 

https://github.com/Alexays/Waybar/blob/fd11711673a4b17fd69aaa198dbe483e72fb24bb/src/modules/wlr/taskbar.cpp#L99

**Comment by Alexays** [comment]
@cryptoluks Can yout test with latest commit (374d5ae5a198611011b8f78fc97a20b7ece5a049) on master?

**Comment by cryptoluks** [comment]
> @cryptoluks Can yout test with latest commit ([05b1260](https://github.com/Alexays/Waybar/commit/05b12602d4f1fde4c13309a0b3a70afb010d3231)) on master?

Jup, with the nullptr check it works for me. No more crashing. Thanks for the fast fix!
