### ISSUE TITLE
mpd: big delays when updating

### ISSUE THREAD

**Issue by YerinAlexey** [Alexays/Waybar#926]
After changing MPD status, Waybar updates the module only after 1-2 seconds. This is not a problem with MPD because `mpc idleloop` gives information without any delays. Logs don't show anything.

Waybar version: freshly built from git, but also reproduces on `0.9.4-5` from Arch repos

**Comment by YerinAlexey** [comment]
Just as a note, this bug bisects to 8f961ac3976048d7a389d77737d9694f26fe863d

**Comment by rk-zero** [comment]
I would like to add to this: If for whatever reason the mpd server is not available waybar goes unresponsive. I was trying to wrap my head around why it lagged so badly, maybe lowering the connection attempts would help.

**Comment by YerinAlexey** [comment]
> I would like to add to this: If for whatever reason the mpd server is not available waybar goes unresponsive.

I'm not sure why that would happen, on cf5db8f6631e4d165d52479a153e3792108edef7 it seems to work fine when the server is not available. I haven't tried later versions
