### ISSUE TITLE
clock : calendar set next prev month

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Alexays/Waybar#939]
I've set clock and calendar (https://github.com/Alexays/Waybar/wiki/Module:-Clock) :
`<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>`

The idea is display calendar right click => next month
left click => prev month
I don't find how can i do this ?
Is that possible ?

**Comment by derdeagle** [comment]
That'd be a really useful feature!

**Comment by LukashonakV** [comment]
Hi @DavidHenryThoreau , this functionally is implemented.  Please check the freshet Waybar , recheck WIKI clock section and if it's ok for you,  close the issue. Thanks

**Comment by DavidHenryThoreau** [comment]
Really nice and interesting features :o ! Works great ! Thanks for commit ;)
