### ISSUE TITLE
Pulseaudio section doesn't change when default sink changes

### ISSUE THREAD

**Issue by colemickens** [Alexays/Waybar#940]
It seems like when PA started, it had the wrong audio device set as default. Now, I've updated it, but `waybar` still shows the volume for the wrong device.

**Comment by pan1997** [comment]
`❯ waybar --version
Waybar v0.9.4`
Was able to verify that waybar is updated when changing default/fallback device. Using `pavucontrol 4.0` to change the default device as show in the attached screenshots.
[brefore](https://drive.google.com/file/d/1AEMmk2tAIYXa_pCxjymj3htb1xs88B6t/view?usp=sharing)
[after](https://drive.google.com/file/d/1kVCRSGE8mSjqoHk4iqtPF1vmzD9baX8N/view?usp=sharing)

**Comment by Alexays** [comment]
Yes should be fixed with newer versions
