### ISSUE TITLE
wlr/taskbar cause crashing

### ISSUE THREAD

**Issue by barni2000** [Alexays/Waybar#943]
wlr/taskbar prevent restart waybar after crashing.
I always got this message:
Gdk-Message: 02:27:22.001: Error 2 (No such file or directory) dispatching to Wayland display.

If I remove the wlr/taskbar module from the config I can restart the waybar.

OS: Arch Linux
**waybar: 0.9.4**
gtkmm: 3.24.3
gtk-layer-shell: 0.5.2
wayland: 1.18.0

**Comment by pan1997** [comment]
I too face this error message and crash of waybar on this setup (running sway on arch)
`
[2020-12-15 10:39:21.654] [error] Failed to register as toplevel manager
Gdk-Message: 10:39:21.665: Error 2 (No such file or directory) dispatching to Wayland display.
`
I tried building the master branch, and it was able to display the taskbar correctly, so **i think this has been fixed** (didn't go through the commit log or blame of the taskbar to figure out the exact issue)

**Comment by barni2000** [comment]
@pan1997 I will check the master version, i only sad if I remove the taskbar from the config it works as expected. (I can restart the bar, if the taskbar is in the config i cannot restart it.) It is not a blame it is  a reproduction case.

**Comment by barni2000** [comment]
Ok I checked the master it seems to be fixed thanks.
