### ISSUE TITLE
exec-if broken if test command outputs text

### ISSUE THREAD

**Issue by eoli3n** [Alexays/Waybar#947]
waybar v0.9.4

### What fails
If i run a module with ``exec-if`` command which print text, it breaks the test:
```
    "custom/kubernetes": {
        "format": "<span foreground='#929292'></span> {}", ■
        "interval": 5,
        "exec": "~/.config/waybar/modules/kubernetes.sh",
        "exec-if": "echo test"
    },
```
I get at each iteration
```
sh: line 1: echo: write error: Broken pipe
```
Then module doesnt output ``format``.

### How it would work

Exec-if could only test return code and not error if exec-if commands output text.
It outputs module anyway if test return code is ok.

### Workaround
```
    "custom/kubernetes": {
        "format": "<span foreground='#929292'></span> {}", ■
        "interval": 5,
        "exec": "~/.config/waybar/modules/kubernetes.sh",
        "exec-if": "echo test > /dev/null"
    },
```

**Comment by OJFord** [comment]
@Alexays I am still experiencing this with v0.9.17 (latest release at the time of writing, from January, after this was closed as completed).

```
"exec-if": "systemctl --failed --output=json | jq --exit-status 'length > 0'"
```

nor reduced to (I suspected the pipe at first, before finding this issue):
```
"exec-if": "jq --null-input --exit-status 'true'",
```

OP's workaround does seem to work though, thanks 👍🏻
