### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ainola** [Alexays/Waybar#948]
Hello! Thanks for all your hard work on this!

The MPD module seems to be causing some issues with our users on Arch Linux. The current stable version gave us a report of an MPD-related crash of Waybar [1]. A related patch was backported  [2] from the upstream repository to fix the crash. However, it appears that backporting this introduces other issues. related to formatting [3].

Is the tip of master in such a state that a new release could safely be cut or should I expect to wait a while longer before the next release?

Thank you!

[1] https://github.com/Alexays/Waybar/issues/775
[2] https://github.com/Alexays/Waybar/pull/887/files
[3] https://bugs.archlinux.org/task/68992

**Comment by Alexays** [comment]
I should have done one a few days ago.
https://github.com/Alexays/Waybar/commit/4b29aef048b640f162cd4d0b7ad082fc20b1c0b8
