### ISSUE TITLE
Window title flickering

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#95]
When I hover mouse cursor over window title on panel, it starts to flicker after several seconds I hold cursor over it. As far as I can see, it's caused by tooltip. Somehow tooltip is being interpreted by panel as separate window and tries to show it's own title.

**Comment by Alexays** [comment]
Yeah, it's a known issue #63, it didn't do it until a sway/wlroots update, I'd have to look where it came from.
