### ISSUE TITLE
`sway/language` is rendered as ellipsis when using many other modules

### ISSUE THREAD

**Issue by maximbaz** [Alexays/Waybar#952]
I realize this sounds strange, but it seems having many other modules in your waybar breaks `sway/language`...

Lets make a custom module first, so save the below in `/tmp/test.sh`:

```sh
#!/bin/bash

printf '{"text":"hello"}\n'
```

Now in your waybar config add the following:

```
{
    "layer": "top",
    "height": 25,
    "modules-right": [
        "sway/language",
        "custom/test",
        "custom/test",
        "custom/test",
        "custom/test",
        "custom/test"
    ],

    "custom/test": {
        "exec": "/tmp/test.sh",
        "return-type": "json"
    }
}
```

This should render `En` and a few `hello` words. Now keep adding `custom/test`, add say 5 at a time, and restart waybar.

At some point (for me this happens when I have 19 `custom/test`, I will see 19 `hello` but `sway/language` will be rendered as `...` instead of `En`. There are no errors printed by waybar process.

Let me know if I could provide with more details? I'm quite confused where to look further...

**Comment by gnull** [comment]
Having the same issue. It seems that `sway/language` shows an ellipsis even when it's not the leftmost module on the bar. And I've never seen another module producing this behaviour.

| ![image](https://user-images.githubusercontent.com/7102119/121939041-d3d39700-cd4c-11eb-9cac-9db86d83aa03.png) |
| -- |
| Just in case, this is the screenshot of what it looks like on my screen. The `sway/language` is right between Slack icon and my brightness indicator. |

I use two monitors and, interestingly, this behaviour happens only on the smaller one, where the Waybar items cover more than the half of its width.

**Comment by solarfl4re** [comment]
I increased the `min-width` for `#language` in my `style.css` file until they all showed - for me that was:
```css
#language {
/*    snip  */
    min-width: 30px;
}
```

**Comment by gnull** [comment]
I did the same and I haven't seen the ellipsis since then. Thanks a lot for the workaround @solarfl4re!

This probably suggests a way to debug—and possibly fix—the issue. Could it be that the GTK UI element that is used to display the language module puts the ellipsis there when it thinks the contents don't fit?

**Comment by telychko** [comment]
> I increased the `min-width` for `#language` in my `style.css` file until they all showed - for me that was:
> 
> ```css
> #language {
> /*    snip  */
>     min-width: 30px;
> }
> ```

It does not work if the scale of the output is not 1.

I have `output eDP-1 scale 1.5` in my sway config, and the workaround does not work. I tried to change the min-width by the greater value, but it has no effect.

Environment:
Arch linux
Waybar v0.9.15
sway version 1.7
