### ISSUE TITLE
Really center module-center

### ISSUE THREAD

**Issue by flipflop133** [Alexays/Waybar#957]
I wonder if it was possible to really center the module-center like in polybar?
Because on the picture below my spotify module doesn't look really centered.
![image](https://user-images.githubusercontent.com/48946818/103157344-2ecefd00-47b2-11eb-8f3b-14fed8ba94ba.png)

**Comment by Alexays** [comment]
module-center is really centered, maybe that you added some unwanted padding to the module?

**Comment by flipflop133** [comment]
It is centered by being on the middle of the bar, but polybar provides an option to center the centered modules proportionnaly to left and right modules, so if there's more modules on the right it's still centered proportionnaly.
The polybar option is called fixed-center.
Link: https://github.com/polybar/polybar/wiki/Configuration#bar-settings
