### ISSUE TITLE
Some problems after reinstall

### ISSUE THREAD

**Issue by PowerMan2206** [Alexays/Waybar#968]
I had a tiny, barely noticable problem with my Arch installation and instead of fixing it I decided that it was a good idea to just burn the whole bitch down and reinstall from the bottom up. Before this, I backed up all important files and configs and stuff. Funny thing, reinstalling didn't fix it.

But anyhow, the problems are these:
* the text is black (as you can imagine, it looks bad on a dark background)
* the top bar (one with the Sway workspaces) is 24 pixels tall. I'm *pretty* sure it was just 20 before

So was there a Waybar update that changed stuff in between the 20 minutes of reinstalling or did something wacky happen?

On Arch with (you guessed it) Sway.

**Comment by PowerMan2206** [comment]
Also, right clicking on a tray icom (Discord, qBitTorrent, etc.) the background is white while the foreground (text) is dark. Before the reinstall it was the other way around (dark background, white text) as is by my GTK theme. Does this have something to do with GTK? I didn't even know Waybar uses GTK...

**Comment by Alexays** [comment]
Your problems is most probably related to your GTK theme as yes Waybar use GTK 😄

**Comment by PowerMan2206** [comment]
Ah, I see. Weird that it just broke like that even with all the dotfiles copied over. I'll look into that, then. Thanks

**Comment by PowerMan2206** [comment]
**Weather update to those with a similar problem:**
I fixed this by running `gsettings set org.gnome.desktop.interface gtk-theme [gtk-theme]`, in my case `gsettings set org.gnome.desktop.interface gtk-theme Sweet`.

*Thanks, Arch wiki!*
