### ISSUE TITLE
Feature request: adding button.focused_inactive in style.css

### ISSUE THREAD

**Issue by rikiki667** [Alexays/Waybar#97]
Hi,

Could you add the button.focused_inactive parameter support in style.css file ?
It could be useful in sway to follow workspace number when you have multiple monitors ;)

Best regards,

**Comment by Robinhuett** [comment]
I'm not sure if I understand this correctly.
In sway a workspace an be inactive or active (visible). When a workspace gets focus it also becomes active. So focused and inactive is an imposible combination.

The currently available styles for workspaces and their sway-bar mathch are:
```
#workspaces button.focused = focused_workspace
#workspaces button.visible = active_workspace
#workspaces button         = inactive_workspace
#workspaces button.urgent  = urgent_workspace
```

**Comment by rikiki667** [comment]
the idea is to have a classic focused workspace the first screen you used and add one on the unused screen to know which workspace is printed on this second screen.

**Comment by rikiki667** [comment]
Yes, you're right, that's a mistake...I close the issue, sorry :)
