### ISSUE TITLE
"on-click|on-click-right" targets will always execute the "exec" target too

### ISSUE THREAD

**Issue by jbauernberger** [Alexays/Waybar#971]
Hi,

sorry if this is a silly question.

It appeares that waybar/conf  `exec` directive for custom module will always run (e.g. regardless if interval is up) whenever an on-click action gets triggered? 

If I have a script `foo/foo_bar` which accepts different options `-a|-b|-c` then calling these from targets (`exec`, `on-click`, `on-click-right`). In this case the `exec` target (in the below example `foo/foo_bar -a`) will always get triggered **in addition** to the `on-click` or `on-click-right`. It's is like the `click` targets will also cancel the interval timer from the other exec thread?

```
    "custom/foo": {
        "exec": "~/src/foo/foo_bar -a", // return text of waybar in json only
        "return-type": "json",
        "interval": 300,
        "format": "{} {icon}",
        "format-icons": [""],
        "on-click-right": "alacritty -e bash -i ~/src/foo/foo_bar -b", // pipe output to less
        "on-click": "~/src/foo/foo_bar -c" // send dunst notification
    },
```

I thought this was interesting to know, since it's not documented anywhere (not sure if it's expected behavior?) and it took me a while to figure out the answer to _"why does waybar call my script twice anytime there is on-click?"_ :) 

cheers
~joachim

**Comment by qoheniac** [comment]
This _is_ documented! See [here](ps://github.com/Alexays/Waybar/wiki/Module:-Custom): the default value for `exec-on-event` ist `true`.
