### ISSUE TITLE
Wireless mouse battery not detected by the battery module and can't be added manually

### ISSUE THREAD

**Issue by p4block** [Alexays/Waybar#972]
I got a wireless mouse with a battery and you can manually look the voltage and stuff with cat just fine in its sysfs folder. 

```
hal@arch /sys/class/power_supply % ls -lh
lrwxrwxrwx root root 0 B Mon Jan 11 04:38:38 2021   hidpp_battery_0@ ⇒ ../../devices/pci0000:00/0000:00:07.1/0000:0c:00.3/usb5/5-3/5-3:1.2/0003:046D:C539.000B/0003:046D:407F.0010/power_supply/hidpp_battery_0

```
However an unconfigured battery module will detect no batteries and any attempt at telling it to use "hidpp_battery_0" will fail.

This can be worked around with scripting, but would be cool if wireless mice and other peripherals worked out of the box.

**Comment by p4block** [comment]
Note that this mouse only reports battery _voltage_ and not a fixed percentage so it could definitely be crashy if it was detected (or maybe it is getting detected and failing gracefully)

**Comment by nloewen** [comment]
My HID++ 2.0 mouse (Logitech MX Master 2S) has these sysfs interfaces.

status = Charging, Discharging, Unknown
capacity_level = Critical, Low, Normal, Full, Unknown

capacity_level is only available when status is Discharging.
status and capacity_level are unknown when the device goes into low power mode after a short period of inactivity.

**Comment by jinnko** [comment]
Similar issue with my Logitech M590 mouse and K780 keyboard connected using the UnifyingReceiver.

Using `upower -e | xargs -n1 upower -i` I'm able to enumerate existing batteries and see the values reported by the mouse and keyboard, but unable to get them reported by waybar-battery.

**Comment by p4block** [comment]
On Linux 5.15 rc1 there's support for (at least) my mouse and it now shows proper capacity in sysfs 

```
/sys/class/power_supply/hidpp_battery_0/ cat capacity 
68
```

The module even shows up in waybar but as 0%
![image](https://user-images.githubusercontent.com/5960575/133773411-05157880-25b5-42a4-afab-04c2a9f62b66.png)

Something is being weird here

**Comment by appetrosyan** [comment]
I own a Logitech g903. It should be detected properly, but instead I get a 

![image](https://user-images.githubusercontent.com/15856657/148608379-c3722dc8-81f1-40a7-9582-d64233c331db.png)

![image](https://user-images.githubusercontent.com/15856657/148608565-a4546a77-acc6-40dc-bed9-93a25d9d68d3.png)

**Comment by p4block** [comment]
Today, waybar showed the correct % of the mouse, but after a while it started going to 0%, 100%, disappear... But it's the first time it has actually shown the percentage.

The kernel sysfs interface is probably weird, some fix got there to 5.16 but it's not fixed completely

**Comment by hajosattila** [comment]
Similar issue with my Keychron K8
- Arch
- Keychron K8 (/sys/class/power_supply/hid-dc:2c:26:26:48:e8-battery)

**Comment by 5n00p4eg** [comment]
Same on Fedora. I'm using Keychron K6
```
cat /sys/class/power_supply/hid-dc:2c:26:ef:0f:4a-battery/capacity
91
```

the module shows 0 or 100, randomly.

**Comment by p4block** [comment]
Fixed at some point by what I presume is the kernel. Working perfectly on my system for a while.
