### ISSUE TITLE
Consider adding upower status to battery module

### ISSUE THREAD

**Issue by kamushadenes** [Alexays/Waybar#975]
Hello,

WDYT about exposing upower fields as formatting options for the battery module?

Sample output:

```
upower -i /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               LGC-LGC6.5
  model:                DELL 2XXFW08
  serial:               4214
  power supply:         yes
  updated:              Tue 12 Jan 2021 06:57:53 PM -03 (54 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              50.9732 Wh
    energy-empty:        0 Wh
    energy-full:         50.9732 Wh
    energy-full-design:  50.9732 Wh
    energy-rate:         0 W
    voltage:             8.618 V
    percentage:          100%
    capacity:            100%
    technology:          lithium-polymer
    icon-name:          'battery-full-charged-symbolic'
```

**Comment by XDjackieXD** [comment]
For some HP laptops (in my case an Elitebook 840 G6), the "current_now" sysfs path returns no useful value but upower gets current values and a good runtime estimate so I'd really like to have upower instead or additionally to sysfs for the battery module.

**Comment by rubdos** [comment]
Another good reason to support upower: logitech mouses via logid seem to expose their battery status to upower, but not in sys-class-power. Would be cool to see the battery status of my MX Master 2S:

```
Device: /org/freedesktop/UPower/devices/mouse_dev_FF_D5_18_0E_70_BB
  native-path:          /org/bluez/hci0/dev_FF_D5_18_0E_70_BB
  model:                MX Master 2S
  serial:               FF:D5:18:0E:70:BB
  power supply:         no
  updated:              Wed 01 Sep 2021 10:08:42 AM CEST (18979 seconds ago)
  has history:          yes
  has statistics:       no
  mouse
    present:             yes
    rechargeable:        no
    state:               unknown
    warning-level:       none
    percentage:          50%
    icon-name:          'battery-missing-symbolic'
```

**Comment by gnull** [comment]
Upower can also show the battery status of a bluetooth headset (and any other bluetooth device, I suppose). Not a critical feature but nice to have, makes you feel like a first-class desktop user ☺.

**Comment by ErikReider** [comment]
I created this in the meantime [waybar-battery-module](https://github.com/ErikReider/waybar-battery-module)

**Comment by gnull** [comment]
@ErikReider @Alexays could this end up in Waybar repo? This would simplify distribution and support a lot. For example, waybar will automatically end up in the packages for all the supported distros.

**Comment by ErikReider** [comment]
Atm no. It's written in Vala and has a few issues which are needed to be ironed out first (mostly suspend issues). Integration would be cool though! :)

**Comment by ErikReider** [comment]
@gnull you can test the PR if you want. I'd appreciate some feedback :)

**Comment by gnull** [comment]
Sorry, @ErikReider, I've been spending a lot of time afk these weeks. I'm starting to test the PR now.

At the moment it seems to be working great. Thanks a lot!

I see that the current configuration works a bit differently from the other modules. (Can't configure/disable icons, can't customize tooltip format.) But I guess designing config format is a next step that needs some more thinking and maybe user feedback.

**Comment by ErikReider** [comment]
> Sorry, @ErikReider, I've been spending a lot of time afk these weeks. I'm starting to test the PR now.
> 
> At the moment it seems to be working great. Thanks a lot!
> 
> I see that the current configuration works a bit differently from the other modules. (Can't configure/disable icons, can't customize tooltip format.) But I guess designing config format is a next step that needs some more thinking and maybe user feedback.

It uses stock GTK icons that UPower provides. Changing your GTK icon theme changes the icon used

**Comment by gnull** [comment]
Just an idea. The way I imagined would be ideal to have upower display the data is to have an instance of the module for each battery the user wants to keep track of. For example, I have my laptop battery, a bluetooth speaker and bluetooth headphones. I'd want to put an instance of upower module for each on my Waybar (maybe with different colors or labels), and have the modules be displayed or hidden based on whether the device is connected.

**Comment by ErikReider** [comment]
> Just an idea. The way I imagined would be ideal to have upower display the data is to have an instance of the module for each battery the user wants to keep track of. For example, I have my laptop battery, a bluetooth speaker and bluetooth headphones. I'd want to put an instance of upower module for each on my Waybar (maybe with different colors or labels), and have the modules be displayed or hidden based on whether the device is connected.

What's difficult with this is that the device path changes every time the device gets disconnected and reconnected. A solution would be to display all devices in the panel (a config option)
