### ISSUE TITLE
module clock: Unknown module: clock

### ISSUE THREAD

**Issue by NieTiger** [Alexays/Waybar#977]
I'm running Debian Testing, installed Waybar from the official repo and running the default config.

Relevant config:

```jsonc
{
    "modules-right": ["clock"],
    "clock": {
        // "timezone": "America/New_York",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": "{:%Y-%m-%d}"
    },
}
```

log:

```
[warning] module clock: Unknown module: clock
```

```
~ waybar -v
Waybar v0.9.5
```

Clock module does not render in the bar. Any idea whats wrong?

**Comment by ihabunek** [comment]
Check out https://github.com/Alexays/Waybar/issues/668

**Comment by NieTiger** [comment]
Thanks for the link! I don't think having an extra dependency is a good reason to not compile a status bar without clock support, but what do I know.

This custom snippet works for me (for those who come later):

```
    "custom/clock": {
        "exec": "date +'%H:%M %S'",
        "interval": 1
    },
```

**Comment by kevr** [comment]
How exactly do you style the `custom/clock` module? Thanks for the snippet! Having trouble figuring out what its CSS ID would be.

**Comment by serxoz** [comment]
@kevr  take a look here: https://github.com/Alexays/Waybar/wiki/Module:-Custom#style
