### ISSUE TITLE
clock module does not render when waybar is started from sway config

### ISSUE THREAD

**Issue by berto91** [Alexays/Waybar#978]
When waybar is started via the sway config like this
```js
bar {
    swaybar_command waybar
}
```
The clock module does not show up.
The same is true if waybar is started 'in background' by other means like a script started from bemenu or via a user systemd job.

If, however, waybar is started from a terminal by simply entering
`~ waybar`
The clock module does show up as expected.

The waybar verion is v0.9.5 and is running on linux arch on a Intel Nuc 10 Performance
Strangely, on different hardware the problem does not show up

**Comment by savchenko** [comment]
Problem isn't new, you might consider something like:
```json5
    "custom/clock": {
        "exec": "echo '  '$(date +'%H:%M')'  '",
        "interval": 5
    }
```
and then add "custom/clock" to your `modules-*`.

**Comment by berto91** [comment]
Seems like a good enough workaround. Thanks!

**Comment by rilott** [comment]
if someone else finds this, my timezone wasn't set (/etc/localtime does not exist), so I just set one in the clock config and the clock appeared in my bar
```"timezone": "Europe/London",```

**Comment by VesperQuartz** [comment]
Why is this closed, cause this is still an issue

**Comment by savchenko** [comment]
@VesperQuartz works with:
```
Waybar v0.12.0
sway version 1.10.1
```

Debian 13.
