### ISSUE TITLE
Crash upon opening new window (sometimes)

### ISSUE THREAD

**Issue by acly7946** [Alexays/Waybar#979]
**Details:**
- Waybar v0.9.5
- sway version 1.5.1
- Arch Linux

**Issue:**
Waybar _sometimes_ crashes when any new window is opened. Redirecting stderr to a file yields the following errors:
```
** (waybar:28307): WARNING **: 11:13:30.358: Dropped dispatcher message as the dispatcher no longer exists
Gdk-Message: 11:13:44.220: Error reading events from display: Invalid argument
```

**Other:**
waybar is executed as 'exec waybar' in sway config.

**Configuration**
config - https://gist.github.com/acly7946/ac8775b018aa7f30e6c850b556a523cc
style.css - https://gist.github.com/acly7946/bcb77cfbebe43dec12f4b6a795050860

**Comment by Alexays** [comment]
Should be fixed on master
