### ISSUE TITLE
Panel size change on dual screen when i swich

### ISSUE THREAD

**Issue by rikiki667** [Alexays/Waybar#98]
Hi,

I have a dual screen configuration with sway. One waybar panel is displayed on each of them. But when i switch from one screen to another, the size of waybar panel seem to loose one or two pixel on the screen i left.

Best regards,

**Comment by Robinhuett** [comment]
Could you please attach your `style.css` so I can test this?

**Comment by rikiki667** [comment]
My style.css:

* {
  font-family: Iosevka Term Bold;
  font-size: 13px;
  font-weight: bold;
  background: #111111;
  color: #f4d3bd;
  padding: 0 4px;
}
#workspaces button {
  padding: 0 0px;
}

#workspaces button.visible{
  border-bottom: 3px solid #dc5757;
}

#workspaces button.focused {
  border-bottom: 3px solid #dc5757;
}

#mode {
  background: #f9807a;
  border-bottom: 3px solid red;
}

**Comment by rikiki667** [comment]
I tested some configurations of style.css since my first post and the problem disappeared. I'm not sure this is a bug and in that case, i can't reproduce it anymore...I closed the issue.

**Comment by Robinhuett** [comment]
Glad you got it sorted out. I could also not reproduce it.
I can only imagine, that you had different styles for `#workspaces button.visible` and `#workspaces button.focused` that resulted in a different heigth.
