### ISSUE TITLE
Network module cannot start hidden

### ISSUE THREAD

**Issue by qoheniac** [Alexays/Waybar#986]
For example, if I configure the network module like this

    "network#wifi": {
        "format-ethernet": "",
        "format-wifi": "Connected",
        "format-linked": "",
        "format-disconnected": "",
        "tooltip-format": "Tooltip",
     },

and run waybar while not connected to network, then some space is visible in the bar and I can see the tooltip. If I then connect to Wi-Fi and disconnect again, the gap is gone.

(Waybar version 0.9.5)

**Comment by qoheniac** [comment]
Using only `"format"` and `"format-disconnect"` I was able to hide a network module for VPNs (didn't test it for other interfaces) but after that it did not come back again. As that is probably a different problem I opened a second issue for that here: https://github.com/Alexays/Waybar/issues/987

**Comment by rYR79435** [comment]
I can confirm this issue. My config:
```
"network": {
    "format-wifi": "{essid} ({signalStrength}%) ",
    "format-disconnected": "Disconnected ⚠",
    "format-ethernet": ""
}
```

Before:
![20210407_20h07m56s_grim](https://user-images.githubusercontent.com/60985157/113914705-1cffeb80-97de-11eb-9780-02ada4465c70.png)
After:
![20210407_20h08m35s_grim](https://user-images.githubusercontent.com/60985157/113914711-1ec9af00-97de-11eb-93e6-33552dfde74d.png)
