### ISSUE TITLE
"killall -SIGUSR2 waybar" kills and not reloads

### ISSUE THREAD

**Issue by qoheniac** [Alexays/Waybar#988]
If I run `killall -SIGUSR2 waybar` it kills the waybar process while the [FAQ](https://github.com/Alexays/Waybar/wiki/FAQ#how-can-I-reload-the-configuration-without-restarting-waybar) states that this command reloads the configuration (`killall -SIGUSR1 waybar` works as expected).

(Waybar version 0.9.5)

**Comment by qubidt** [comment]
this was just added in #842, it's not yet in the current release (0.9.5)

**Comment by qoheniac** [comment]
Thanks for clearing this up!
