### ISSUE TITLE
Duplicated/repeated modules on multi monitor setup

### ISSUE THREAD

**Issue by kamushadenes** [Alexays/Waybar#989]
Hello there!

After scratching my head for some time trying to determine why a "tailing" script (one that loops itself) was wielding weird results, I figured out that, on multi monitor setups, waybar is duplicating all modules instead of running only once and reusing the output.

I think this is intended behavior, but is it possible to avoid that?

Besides that particular script, I have more than a few scripts that perform network requests, some of them being to paid services that charge per-request, effectively multiplying my cost by the number of monitors. Still, I would like them to show up on all my outputs.

While I can deal with that locally (and in fact I have for some, with some caching in the scripts' code), I wonder if it would be possible to do that with waybar only, as some of them (specially the tailing script) can't be cached in this manner.

Thanks!

**Comment by kamushadenes** [comment]
Resorted to systemd timers and scripts outputting to a common directory, then replaced all `exec`s with `cat` to said outputs.

Bit hackish, but works. I still believe such a feature should be supported, so I'll keep this open.

**Comment by Alexays** [comment]
dups of #368
