### ISSUE TITLE
Waybar modules appear to be too close together; No spacing option?

### ISSUE THREAD

**Issue by LiterallyJohnny** [Alexays/Waybar#993]
I think the spacing for the Waybar modules seem too close together. [Here is an example.](https://imgur.com/a/OWoqOa1)

I don't see a spacing option that I can use to add a bit of space between the modules anywhere.

Is there a spacing option somewhere that I can use?

**Comment by johnnynalley** [comment]
I found the spacing option.

Edit: Wow, 5 years ago - I was 14 when I made this comment. My bad for not telling yall where the spacing option is.

**Comment by bradyslot** [comment]
> I found the spacing option.

Could you please share the solution?

**Comment by UltraBlackLinux** [comment]
yeah, please share that.

**Comment by UltraBlackLinux** [comment]
@bradyslot 
I found it:
```css
...
#tray,
#mpd {
    margin: 3px; 
}
```

**Comment by agzam** [comment]
That adds margin for everything, what's the specific module css class? I've been trying:

.modules-right > * {
    margin: 0 20px;
}

but that doesn't work

update: I have found it, turns out it has to be like this:

```
.modules-right > widget > * {
    margin: 0 10px 0 0;
}
```

also, running waybar with `GTK_DEBUG=interactive waybar` is useful.
